// Chapter 3: Professional Image — PREMIUM FLASHCARDS
// Created from textbook image analysis
// Categories: Personal Hygiene, Professional Dress, Grooming, Communication, Ethics, Shop Standards

import { Flashcard } from '@/types'

export const chapter3PremiumFlashcards: Flashcard[] = [
  // CATEGORY 1: PERSONAL HYGIENE
  {
    id: 'fc-3-001',
    chapter_id: 'ch-3',
    front: 'Why is daily bathing essential for a professional barber?',
    back: 'Daily bathing prevents body odor, removes bacteria, and ensures personal cleanliness. Clients notice hygiene immediately — it builds trust and professionalism before you even pick up a tool.',
    category: 'Personal Hygiene',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-3-002',
    chapter_id: 'ch-3',
    front: 'How often should a barber wash their hands during the workday?',
    back: 'Wash hands before and after EVERY client, after eating, after using the restroom, and anytime hands become contaminated. This is both hygiene and state board law.',
    category: 'Personal Hygiene',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-3-003',
    chapter_id: 'ch-3',
    front: 'Why should barbers keep their nails short and clean?',
    back: 'Short, clean nails prevent bacteria buildup, avoid scratching clients, and maintain a professional appearance. Long nails harbor germs and look unprofessional in a barber setting.',
    category: 'Personal Hygiene',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-3-004',
    chapter_id: 'ch-3',
    front: 'What is the proper way to maintain oral hygiene as a barber?',
    back: 'Brush teeth at least twice daily, use mouthwash, and keep breath mints available. You work in close proximity to clients — bad breath is unprofessional and offensive.',
    category: 'Personal Hygiene',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-3-005',
    chapter_id: 'ch-3',
    front: 'Why should barbers avoid wearing strong fragrances?',
    back: 'Strong cologne, perfume, or aftershave can trigger allergies, overwhelm clients in close quarters, and clash with shop sanitizers. Use lightly scented or unscented products.',
    category: 'Personal Hygiene',
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-3-006',
    chapter_id: 'ch-3',
    front: 'How often should a barber\'s uniform or work clothes be washed?',
    back: 'Daily or after every shift. Hair clippings, product residue, and sweat accumulate quickly. A fresh uniform every day is essential for hygiene and professional image.',
    category: 'Personal Hygiene',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },

  // CATEGORY 2: PROFESSIONAL DRESS
  {
    id: 'fc-3-007',
    chapter_id: 'ch-3',
    front: 'What type of footwear is most appropriate for barbers?',
    back: 'Closed-toe, non-slip, supportive shoes. They protect against dropped tools, prevent slips on wet floors, and provide comfort during long hours of standing.',
    category: 'Professional Dress',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-3-008',
    chapter_id: 'ch-3',
    front: 'Why is it important for barbers to wear a clean uniform or apron?',
    back: 'A clean uniform protects clothing from hair and products, presents a professional image, and shows clients you take hygiene seriously. It is your walking advertisement.',
    category: 'Professional Dress',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-3-009',
    chapter_id: 'ch-3',
    front: 'What jewelry is considered appropriate for barbers to wear while working?',
    back: 'Minimal jewelry — small stud earrings, simple wedding bands. Avoid dangling jewelry, large rings, or bracelets that can catch hair, scratch clients, or harbor bacteria.',
    category: 'Professional Dress',
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-3-010',
    chapter_id: 'ch-3',
    front: 'Why should barbers avoid wearing revealing or inappropriate clothing?',
    back: 'Revealing clothing looks unprofessional and may make clients uncomfortable. Barbering is a professional service — dress modestly and appropriately for a workplace setting.',
    category: 'Professional Dress',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },

  // CATEGORY 3: GROOMING STANDARDS
  {
    id: 'fc-3-011',
    chapter_id: 'ch-3',
    front: 'What hairstyle is considered most professional for barbers?',
    back: 'A neat, clean, well-groomed hairstyle. Avoid extreme colors, unkempt styles, or looks that appear unprofessional. You are a walking advertisement for your skills.',
    category: 'Grooming Standards',
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-3-012',
    chapter_id: 'ch-3',
    front: 'Why is it important for barbers to maintain a well-groomed beard or facial hair?',
    back: 'Well-groomed facial hair demonstrates your grooming skills to clients. If you cannot maintain your own beard, clients will question your ability to maintain theirs.',
    category: 'Grooming Standards',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-3-013',
    chapter_id: 'ch-3',
    front: 'What should a barber do if they have a visible tattoo?',
    back: 'Follow shop policy — cover it if required, or choose employers with flexible policies. Some shops require tattoos to be covered for a more traditional professional appearance.',
    category: 'Grooming Standards',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-3-014',
    chapter_id: 'ch-3',
    front: 'Why is good posture important when working as a barber?',
    back: 'Good posture prevents back pain, projects confidence, and shows professionalism. Slouching looks lazy and can lead to chronic pain from long hours of standing.',
    category: 'Grooming Standards',
    difficulty: 'easy',
    order_index: 14,
    is_active: true,
  },

  // CATEGORY 4: CLIENT COMMUNICATION
  {
    id: 'fc-3-015',
    chapter_id: 'ch-3',
    front: 'How long do clients typically take to form a first impression of their barber?',
    back: 'Within the first 7 seconds. A clean, professional appearance signals competence and attention to detail before you even speak.',
    category: 'Client Communication',
    difficulty: 'easy',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-3-016',
    chapter_id: 'ch-3',
    front: 'What is active listening and why is it important in barbering?',
    back: 'Active listening means giving full attention, maintaining eye contact, nodding, and asking clarifying questions. It ensures you understand exactly what the client wants.',
    category: 'Client Communication',
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-3-017',
    chapter_id: 'ch-3',
    front: 'Why should barbers avoid using their phone during client services?',
    back: 'Using phones during services is unprofessional, distracts from quality work, and makes clients feel undervalued. Phones also harbor bacteria. Keep them stored away.',
    category: 'Client Communication',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-3-018',
    chapter_id: 'ch-3',
    front: 'What should a barber do if they are running late for an appointment?',
    back: 'Call the client as soon as possible to inform them. Apologize sincerely, offer a revised time, and thank them for their patience. Never leave a client waiting without notice.',
    category: 'Client Communication',
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-3-019',
    chapter_id: 'ch-3',
    front: 'How should a barber handle a client who is unhappy with their haircut?',
    back: 'Stay calm, listen without defending, apologize sincerely, and offer to fix it immediately. Say: "I\'m sorry you\'re not happy. Let me fix this for you right now."',
    category: 'Client Communication',
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-3-020',
    chapter_id: 'ch-3',
    front: 'Why is it important to get client permission before posting their photo on social media?',
    back: 'It is legally required and respects client privacy. Posting without consent can damage trust, violate privacy laws, and harm your professional reputation.',
    category: 'Client Communication',
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },

  // CATEGORY 5: PROFESSIONAL ETHICS
  {
    id: 'fc-3-021',
    chapter_id: 'ch-3',
    front: 'Why should barbers avoid gossiping about clients or coworkers?',
    back: 'Gossiping is unprofessional, damages trust, creates a toxic work environment, and violates client confidentiality. Professional barbers maintain discretion at all times.',
    category: 'Professional Ethics',
    difficulty: 'medium',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-3-022',
    chapter_id: 'ch-3',
    front: 'What is client confidentiality and why does it matter?',
    back: 'Client confidentiality means keeping personal information, conversations, and details private. Violating it destroys trust and can have legal consequences.',
    category: 'Professional Ethics',
    difficulty: 'easy',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-3-023',
    chapter_id: 'ch-3',
    front: 'Why should a barber not diagnose skin or scalp conditions?',
    back: 'Barbers are not medical professionals. Diagnosing conditions is outside your scope of practice. Recognize abnormalities and refer clients to a dermatologist or doctor.',
    category: 'Professional Ethics',
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-3-024',
    chapter_id: 'ch-3',
    front: 'What should a barber do if a client offers a large tip?',
    back: 'Accept it graciously with a sincere thank you. Large tips reflect excellent service. Never demand tips or make clients feel obligated to tip.',
    category: 'Professional Ethics',
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },

  // CATEGORY 6: SHOP STANDARDS
  {
    id: 'fc-3-025',
    chapter_id: 'ch-3',
    front: 'Why is it important to keep your barber station clean and organized?',
    back: 'A clean station shows professionalism, prevents cross-contamination, helps you work efficiently, and makes clients feel comfortable. Messy stations suggest sloppy work.',
    category: 'Shop Standards',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-3-026',
    chapter_id: 'ch-3',
    front: 'What is the proper way to handle tools that fall on the floor during a service?',
    back: 'Replace them with clean tools or stop and disinfect them thoroughly before reuse. Tools that touch the floor are contaminated and must be sanitized.',
    category: 'Shop Standards',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-3-027',
    chapter_id: 'ch-3',
    front: 'Why should barbers sweep up hair clippings immediately after each client?',
    back: 'Immediate cleanup maintains hygiene, prevents slipping hazards, shows respect for the next client, and keeps the shop looking professional.',
    category: 'Shop Standards',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-3-028',
    chapter_id: 'ch-3',
    front: 'What is the purpose of an anti-fatigue mat at a barber station?',
    back: 'Anti-fatigue mats provide cushioned flooring that reduces leg and back strain from standing for long periods. They help prevent chronic pain and fatigue.',
    category: 'Shop Standards',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },

  // CATEGORY 7: PROFESSIONAL DEVELOPMENT
  {
    id: 'fc-3-029',
    chapter_id: 'ch-3',
    front: 'Why is continuing education important for barbers?',
    back: 'Continuing education keeps skills current, introduces new techniques, maintains licensure, and shows clients you are committed to excellence. The industry constantly evolves.',
    category: 'Professional Development',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-3-030',
    chapter_id: 'ch-3',
    front: 'What is the purpose of a professional portfolio for a barber?',
    back: 'A portfolio showcases your best work, demonstrates your range of skills, helps attract new clients, and can be used for job applications or shop promotions.',
    category: 'Professional Development',
    difficulty: 'easy',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-3-031',
    chapter_id: 'ch-3',
    front: 'Why should barbers maintain a positive attitude even during busy or stressful days?',
    back: 'A positive attitude affects client experience, coworker relationships, and your own mental health. Clients can sense negativity — it drives them away. Stay professional.',
    category: 'Professional Development',
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-3-032',
    chapter_id: 'ch-3',
    front: 'What is the most important factor in building a loyal client base?',
    back: 'Consistently delivering excellent service and building genuine relationships. Clients return because of trust, quality, and how you make them feel — not just price.',
    category: 'Professional Development',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },

  // CATEGORY 8: STATE BOARD PREPARATION
  {
    id: 'fc-3-033',
    chapter_id: 'ch-3',
    front: 'What does the term "professional image" encompass in barbering?',
    back: 'Professional image includes personal hygiene, grooming, dress, communication skills, attitude, and behavior. It is the total impression you make on clients and employers.',
    category: 'State Board Preparation',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-3-034',
    chapter_id: 'ch-3',
    front: 'Why is punctuality considered a critical professional trait for barbers?',
    back: 'Punctuality shows respect for clients\' time, demonstrates reliability, and keeps the schedule running smoothly. Being late costs money and damages your reputation.',
    category: 'State Board Preparation',
    difficulty: 'easy',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-3-035',
    chapter_id: 'ch-3',
    front: 'What should a barber consider before posting anything on social media?',
    back: 'Ask: "Would I want my grandmother, my boss, and my best client to see this?" If no, do not post it. Social media is permanent and reflects your professional image.',
    category: 'State Board Preparation',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-3-036',
    chapter_id: 'ch-3',
    front: 'Why is it important for barbers to understand and follow state regulations?',
    back: 'State regulations protect public health, ensure safety standards, and maintain professional credibility. Violations can result in fines, license suspension, or shop closure.',
    category: 'State Board Preparation',
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },

  // CATEGORY 9: HEALTH AND WELLNESS
  {
    id: 'fc-3-037',
    chapter_id: 'ch-3',
    front: 'What is carpal tunnel syndrome and how can barbers prevent it?',
    back: 'Carpal tunnel is nerve compression causing hand pain/numbness from repetitive tool use. Prevent it with ergonomic tools, wrist stretches, and taking regular breaks.',
    category: 'Health and Wellness',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-3-038',
    chapter_id: 'ch-3',
    front: 'Why should barbers take regular breaks during the workday?',
    back: 'Breaks prevent fatigue, reduce injury risk, maintain mental focus, and improve service quality. A tired barber makes mistakes and provides poor client experiences.',
    category: 'Health and Wellness',
    difficulty: 'easy',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-3-039',
    chapter_id: 'ch-3',
    front: 'What is the proper chair height adjustment for client comfort and barber ergonomics?',
    back: 'Adjust the chair so the client\'s head is at the barber\'s elbow level. This prevents strain, allows proper posture, and provides optimal working angles.',
    category: 'Health and Wellness',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-3-040',
    chapter_id: 'ch-3',
    front: 'Why is it important for barbers to maintain their own physical fitness?',
    back: 'Physical fitness improves stamina for long workdays, reduces injury risk, and projects a healthy professional image. Barbering is physically demanding work.',
    category: 'Health and Wellness',
    difficulty: 'easy',
    order_index: 40,
    is_active: true,
  },
]

export default chapter3PremiumFlashcards
