// Chapter 2 Reassessment Reserve Questions
// Life Skills — 25 reserve questions (one per active concept)
//
// POST-LOCK ADDITIVE (founder-approved Option A, 2026-09-09):
//   48 locked initial questions + 25 reserve = 73 combined capacity.
//   These questions are the reassessment reserve. They are NEVER served by
//   the initial chapter quiz (which reads chapter-2-premium-quiz only).
//   They become available to a student ONLY through the 6C reassessment path,
//   after the historical-exclusion engine has ruled out previously seen items.
//
//   IDs run qq-2-051 through qq-2-075. Retired IDs qq-2-033 / qq-2-036 remain
//   permanently unused (historical attempts may reference them).
//
//   Authoring standards: original ASCYN wording from canonical Chapter 2
//   teaching; exactly one defensible answer; three plausible distractors;
//   substantive explanation; no publisher reproduction; no Pivot Point;
//   no unsupported board claims; no longest-answer giveaway; no trivial
//   paraphrase of any locked question.

import { QuizQuestion } from '@/types'

export const chapter2ReassessmentQuestions: QuizQuestion[] = [
  // ═══════════════════════════════════════════════════════════
  // RESERVE — formerly single-item concepts (first priority)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-2-051',
    quiz_id: 'quiz-2',
    question: 'A barber student plans a four-hour study block for a theory review but usually loses focus after the first hour. Which approach best applies Chapter 2\'s time-management tools?',
    answer_a: 'Break the four hours into Pomodoro cycles — 25 minutes of focus, 5-minute breaks, a longer break after four rounds',
    answer_b: 'Study in one uninterrupted four-hour sitting so momentum is never broken and no time is lost to breaks',
    answer_c: 'Switch to a different subject every five to ten minutes so the material stays fresh across the entire four-hour block',
    answer_d: 'Move the study block to the night before the exam, when the pressure of the deadline makes concentration easiest',
    correct_answer: 'a',
    explanation: 'The Pomodoro Technique sustains focus through short, structured work cycles with planned breaks. Marathon sessions invite fatigue and diminishing retention, while panic-cramming the night before sacrifices real learning.',
    difficulty: 'medium',
    order_index: 51,
  },
  {
    id: 'qq-2-052',
    quiz_id: 'quiz-2',
    question: 'A barber student failed a chapter quiz with a 62% and can retake it in one week. They work all day Saturday and Sunday. Which plan best applies Chapter 2\'s study habits?',
    answer_a: 'Reread the entire chapter once the night before the retake, so every section feels as fresh as possible going in',
    answer_b: 'Schedule short daily review sessions Monday through Friday, turning each missed question into a flashcard and self-testing daily',
    answer_c: 'Highlight every important paragraph in the chapter during one long study session on Sunday night after work ends',
    answer_d: 'Trust that having seen the questions on the first attempt is enough, and use the week to rest instead of reviewing',
    correct_answer: 'b',
    explanation: 'Short, spaced study sessions with active self-testing beat one long cram. Converting missed questions into flashcards targets the actual gaps, and daily retrieval moves material into long-term memory before the retake.',
    difficulty: 'hard',
    order_index: 52,
  },
  {
    id: 'qq-2-053',
    quiz_id: 'quiz-2',
    question: 'A barber notices they have been short-tempered with coworkers all week and feel drained even on their days off. What is the best first response according to Chapter 2?',
    answer_a: 'Push through it and book more clients, keeping busy enough that there is no time left to dwell on the feeling',
    answer_b: 'Withdraw from coworkers for a while and keep interactions minimal so the irritability stays hidden from the team',
    answer_c: 'Recognize it as an early burnout signal and deliberately rebuild rest, breaks, and recovery time into the week',
    answer_d: 'Give it another month before changing anything, since most rough patches eventually pass on their own with time',
    correct_answer: 'c',
    explanation: 'Irritability and fatigue that rest does not fix are early burnout signs. Chapter 2 teaches responding early — adjusting schedule, breaks, and self-care — rather than pushing harder, hiding it, or waiting for collapse.',
    difficulty: 'medium',
    order_index: 53,
  },
  {
    id: 'qq-2-054',
    quiz_id: 'quiz-2',
    question: 'A client texts their barber at 10:45 PM asking to move tomorrow\'s appointment. The barber\'s posted hours end at 7 PM. Which response best protects work-life balance while staying professional?',
    answer_a: 'Reply immediately so the client never feels ignored, treating every late message as part of good client service',
    answer_b: 'Leave the message completely unanswered and sort the scheduling out when the client arrives at the shop tomorrow',
    answer_c: 'Reply to this one now, then mute all future client messages so late-night texting cannot become a habit',
    answer_d: 'Reply the next morning within business hours, politely confirming the schedule change and any new appointment time',
    correct_answer: 'd',
    explanation: 'Healthy boundaries mean clients get reliable, professional responses inside posted hours — not instant availability at all times. Answering the next business morning respects both the client and the barber\'s personal time.',
    difficulty: 'medium',
    order_index: 54,
  },
  {
    id: 'qq-2-055',
    quiz_id: 'quiz-2',
    question: 'A new client sits down and says only, "Just clean it up however." What should the barber do first, according to Chapter 2\'s active-listening guidance?',
    answer_a: 'Ask a few clarifying questions and paraphrase the plan back before touching the clippers',
    answer_b: 'Deliver the barber\'s signature cut, since the client left the decision completely open to professional judgment',
    answer_c: 'Start with a very conservative trim and adjust from there only if the client complains about the result',
    answer_d: 'Hand the client a style book and wait patiently until they pick out something specific enough to follow',
    correct_answer: 'a',
    explanation: 'Vague requests are where active listening earns its place: ask clarifying questions, then confirm the plan by paraphrasing it back. Assuming, guessing, or staying silent invites a result the client never wanted.',
    difficulty: 'medium',
    order_index: 55,
  },
  {
    id: 'qq-2-056',
    quiz_id: 'quiz-2',
    question: 'A coworker has left hair and tools across a shared station for the third day in a row, and clients can see it. What is the most professional way to handle the conflict?',
    answer_a: 'Clean it up loudly during their next appointment so they get the hint while clients are there to see it happen',
    answer_b: 'Ask to speak privately, describe the specific behavior calmly, and agree together on shared station expectations',
    answer_c: 'Report them to the shop owner right away so that a formal warning about the mess goes on their record immediately',
    answer_d: 'Move your own tools to a different station and simply avoid speaking to the coworker until the behavior stops',
    correct_answer: 'b',
    explanation: 'Chapter 2 conflict resolution is private, calm, and focused on the behavior — not the person. Public callouts humiliate, instant escalation skips a step, and avoidance lets the problem harden into resentment.',
    difficulty: 'hard',
    order_index: 56,
  },
  {
    id: 'qq-2-057',
    quiz_id: 'quiz-2',
    question: 'A barber student wants to start building a professional network before graduating. According to Chapter 2, what is the best first step?',
    answer_a: 'Build a large social media following first, so shops can see real influence before any personal introduction happens',
    answer_b: 'Wait until licensed, since students have nothing of value to offer established shop owners or working barbers yet',
    answer_c: 'Form genuine relationships with instructors, classmates, and local barbers through everyday conversation',
    answer_d: 'Pay for local advertising early, so that shop owners already recognize the student\'s name before they ever meet',
    correct_answer: 'c',
    explanation: 'Networking starts with the genuine relationships already around you — instructors, classmates, and working barbers. Authentic connections built now become referrals, mentors, and job leads later.',
    difficulty: 'easy',
    order_index: 57,
  },
  {
    id: 'qq-2-058',
    quiz_id: 'quiz-2',
    question: 'An experienced barber is mentoring a new hire who is slow with fades and losing confidence. Which approach reflects Chapter 2\'s mentorship guidance?',
    answer_a: 'Take over every fade personally so clients stay happy, and let the new hire learn by watching each finished cut',
    answer_b: 'Correct each mistake immediately and specifically in front of clients, so the feedback is timely and memorable',
    answer_c: 'Assign the new hire only simple, low-pressure cuts for a while and let their confidence rebuild on its own',
    answer_d: 'Demonstrate the technique, then let them practice with encouragement and one small goal at a time',
    correct_answer: 'd',
    explanation: 'Good mentors model the skill, then create room to practice with specific encouragement and incremental goals. Taking over teaches nothing, public criticism wounds confidence, and avoiding challenge stalls growth.',
    difficulty: 'medium',
    order_index: 58,
  },
  {
    id: 'qq-2-059',
    quiz_id: 'quiz-2',
    question: 'A barber finishes a long Saturday and is scheduled to open the shop Sunday morning. What does Chapter 2\'s shop-etiquette guidance expect before they leave?',
    answer_a: 'Clean and reset their station and return shared tools so the next barber starts ready',
    answer_b: 'Leave tools soaking overnight for whichever barber is assigned to close the shop that evening',
    answer_c: 'Handle the cleanup only if the shop manager specifically reminds them before they head out',
    answer_d: 'Focus on their own clients and trust that each barber will handle their own mess in the morning',
    correct_answer: 'a',
    explanation: 'Shop etiquette means leaving shared spaces better than you found them — your station reset, shared tools returned. The next barber should be able to start work immediately, not inherit your cleanup.',
    difficulty: 'easy',
    order_index: 59,
  },
  // ═══════════════════════════════════════════════════════════
  // RESERVE — remaining active concepts
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-2-060',
    quiz_id: 'quiz-2',
    question: 'Among Chapter 2\'s essential life skills, which one most directly determines whether first-time clients become regulars?',
    answer_a: 'Punctuality, because clients organize their whole day around the appointment and remember every minute of waiting',
    answer_b: 'Genuine client relationship building, because clients return to barbers they trust and like',
    answer_c: 'Time management, because shorter appointments fit more easily into the busy schedules of working clients',
    answer_d: 'Goal setting, because written growth targets keep a barber\'s day-to-day service quality consistently high',
    correct_answer: 'b',
    explanation: 'Technical skill gets a client in the chair once; genuine relationship building is what brings them back. Chapter 2 lists it among the essential life skills because loyalty is built on trust and connection, not convenience alone.',
    difficulty: 'easy',
    order_index: 60,
  },
  {
    id: 'qq-2-061',
    quiz_id: 'quiz-2',
    question: 'Two barbers graduate with equal technical talent. Five years later, one owns a busy chair and the other has left the industry. According to Chapter 2, what most likely separated them?',
    answer_a: 'Natural charisma — some barbers are simply born with a personality that draws clients in',
    answer_b: 'Luck, since one of them happened to land a chair in a shop with far better walk-in traffic',
    answer_c: 'Consistent daily habits — showing up reliably, tracking goals, managing money, and applying feedback',
    answer_d: 'Credentials, because one of them graduated from a more expensive and better-known barber school',
    correct_answer: 'c',
    explanation: 'Chapter 2\'s core message: what separates thriving barbers is not talent, charisma, or luck — it is learnable daily habits practiced consistently over years. Reliability, goal tracking, money management, and coachability compound into careers.',
    difficulty: 'medium',
    order_index: 61,
  },
  {
    id: 'qq-2-062',
    quiz_id: 'quiz-2',
    question: 'A student practices only on days they "feel motivated," and their skills stay uneven. Which Chapter 2 change actually fixes this pattern?',
    answer_a: 'Set bigger and more exciting goals, so that the motivation itself becomes stronger and lasts longer',
    answer_b: 'Watch technique videos on the unmotivated days, treating observation as a full substitute for practice',
    answer_c: 'Take a complete day off after every practice session, using guaranteed rest as the reward system',
    answer_d: 'Commit to a small scheduled practice routine followed whether or not they feel like it',
    correct_answer: 'd',
    explanation: 'Motivation rises and falls; discipline is the routine you keep regardless of mood. A small scheduled practice habit carried out daily — especially on unmotivated days — is what evens out skill growth.',
    difficulty: 'easy',
    order_index: 62,
  },
  {
    id: 'qq-2-063',
    quiz_id: 'quiz-2',
    question: 'Why does Chapter 2 recommend reading a draft mission statement out loud and revisiting it over time?',
    answer_a: 'A mission statement should sound like you, and it can evolve as your career grows',
    answer_b: 'Reading the draft aloud is the fastest known way to memorize it for future job interviews',
    answer_c: 'Potential clients will often ask to hear your mission statement before they agree to book',
    answer_d: 'Most instructors require a spoken presentation of the mission statement for a passing grade',
    correct_answer: 'a',
    explanation: 'The refine step — reading aloud and living with the draft — makes the statement authentically yours. Chapter 2 treats a mission statement as a living document you commit to daily and review as your career develops, not a one-time assignment.',
    difficulty: 'medium',
    order_index: 63,
  },
  {
    id: 'qq-2-064',
    quiz_id: 'quiz-2',
    question: 'A client loudly announces to the shop that their fade is "crooked" while other clients watch. Which response best demonstrates a healthy, positive professional attitude?',
    answer_a: 'Defend the cut on the spot and calmly remind the client that they chose this style themselves',
    answer_b: 'Stay calm, invite the client to talk it through at the chair, listen, and offer to adjust the cut professionally',
    answer_c: 'Apologize repeatedly right away and offer the cut completely free just to end the scene as quickly as possible',
    answer_d: 'Keep working on your current client without reacting, and let the shop manager handle the situation instead',
    correct_answer: 'b',
    explanation: 'This is emotional stability, diplomacy, and receptivity working together: no defensiveness, no public argument, no panic-pleasing. Acknowledging the concern calmly and offering a professional fix protects both the client and the shop\'s atmosphere.',
    difficulty: 'hard',
    order_index: 64,
  },
  {
    id: 'qq-2-065',
    quiz_id: 'quiz-2',
    question: 'A barber\'s written goal says: "Get better at beard work soon." Which rewrite turns it into a SMART goal?',
    answer_a: '"Become the best beard barber in the city, and do it as quickly as I possibly can manage"',
    answer_b: '"Practice beard work more often and pay much closer attention to how each trim goes"',
    answer_c: '"Complete 20 supervised beard trims with instructor sign-off by the end of next month"',
    answer_d: '"Watch at least one beard tutorial every single night until my technique noticeably improves"',
    correct_answer: 'c',
    explanation: 'SMART goals are Specific, Measurable, Achievable, Relevant, and Time-bound. "20 supervised beard trims with sign-off by end of next month" names the skill, the count, the verification, and the deadline; the others stay vague or unmeasurable.',
    difficulty: 'hard',
    order_index: 65,
  },
  {
    id: 'qq-2-066',
    quiz_id: 'quiz-2',
    question: 'Three months into a twelve-month client-building goal, a barber tracking weekly numbers is slightly behind pace but steadily improving. What does Chapter 2 recommend?',
    answer_a: 'Abandon the goal entirely, since the original twelve-month pace is no longer fully realistic',
    answer_b: 'Stop tracking the weekly numbers, because watching them this closely only creates pressure',
    answer_c: 'Double every remaining weekly target immediately so the goal catches back up on schedule',
    answer_d: 'Keep the goal, adjust the timeline or milestones, and keep tracking the trend',
    correct_answer: 'd',
    explanation: 'Tracking exists to inform adjustment, not to trigger abandonment. Behind pace but improving means the system is working — refine the timeline or break milestones smaller, and keep measuring the trend.',
    difficulty: 'medium',
    order_index: 66,
  },
  {
    id: 'qq-2-067',
    quiz_id: 'quiz-2',
    question: 'A barber keeps running 20 minutes behind because every client "just needs one small extra." Which fix best applies Chapter 2\'s time-management strategies?',
    answer_a: 'Book realistic service times with a buffer block, and offer extras as rebooking options when the block is full',
    answer_b: 'Start every single appointment 20 minutes early so the little extras get absorbed without anyone noticing',
    answer_c: 'Stop offering extras of any kind at all, so that the daily schedule can never slip behind again',
    answer_d: 'Shorten the sanitation steps slightly between clients so the lost minutes come back over the day',
    correct_answer: 'a',
    explanation: 'The leak is unrealistic booking, not client requests. Realistic service times plus a planned buffer absorb small extras honestly, and anything bigger becomes a rebooked service. Sanitation time is never a time-management lever.',
    difficulty: 'hard',
    order_index: 67,
  },
  {
    id: 'qq-2-068',
    quiz_id: 'quiz-2',
    question: 'Why does Chapter 2 favor short reviews spread across several days over one long reread the night before a test?',
    answer_a: 'Spread-out sessions simply take less total study time than a single long session ever could',
    answer_b: 'Spaced repetition moves material into long-term memory far better than a single cram session',
    answer_c: 'Long study sessions wear out the notes physically and make them much harder to reread later',
    answer_d: 'Instructors can usually tell when a student crammed and will grade that student more harshly',
    correct_answer: 'b',
    explanation: 'Spaced repetition — short, repeated retrieval over days — is what transfers material into long-term memory. A single long reread produces familiarity that fades fast, which is exactly what fails students on exam day.',
    difficulty: 'easy',
    order_index: 68,
  },
  {
    id: 'qq-2-069',
    quiz_id: 'quiz-2',
    question: 'A barber realizes they accidentally charged a client $20 too much two days ago. The client has not noticed. What should the barber do?',
    answer_a: 'Keep the money this once, since the transaction is already recorded and correcting it complicates the books',
    answer_b: 'Wait and see whether the client ever mentions the overcharge at one of their future visits before acting on it',
    answer_c: 'Contact the client promptly, explain the error honestly, and refund the $20',
    answer_d: 'Quietly take $20 off the price of the client\'s next visit without ever mentioning the original mistake to them',
    correct_answer: 'c',
    explanation: 'Professional ethics is what you do when no one is watching. Proactively correcting the error — before being caught — turns a mistake into proof of integrity; silent fixes and waiting it out both gamble with the client\'s trust.',
    difficulty: 'hard',
    order_index: 69,
  },
  {
    id: 'qq-2-070',
    quiz_id: 'quiz-2',
    question: 'A regular client\'s spouse calls the shop asking what time the client\'s appointment is and whether they "still talk about the divorce." How should the barber respond?',
    answer_a: 'Share only the appointment time, but stay completely quiet about anything the client said regarding the divorce',
    answer_b: 'Confirm the appointment time openly, since a spouse counts as immediate family rather than an outside party',
    answer_c: 'Tell the spouse to ask the client directly, and then mention the strange phone call to coworkers afterward',
    answer_d: 'Politely explain that client appointments and conversations are confidential and cannot be shared without permission',
    correct_answer: 'd',
    explanation: 'Confidentiality covers everything — appointment times, service details, and especially personal conversations. Even a spouse gets nothing without the client\'s permission, and the call itself is not shop gossip.',
    difficulty: 'hard',
    order_index: 70,
  },
  {
    id: 'qq-2-071',
    quiz_id: 'quiz-2',
    question: 'A barber listens fully to a client\'s complaint, apologizes sincerely, and fixes the cut at no charge. According to Chapter 2, what is the likely long-term result of handling it this way?',
    answer_a: 'The client often becomes more loyal than if the problem had never happened at all',
    answer_b: 'The client returns exactly one more time, then quietly moves on to find another barber',
    answer_c: 'The client learns to expect complimentary fixes at every single future appointment',
    answer_d: 'The client posts a positive review, but only if they are given additional compensation',
    correct_answer: 'a',
    explanation: 'This is the service recovery paradox applied: a complaint handled with full listening, a sincere apology, and a real fix can deepen loyalty beyond where it started. Poor handling, by contrast, loses the client silently forever.',
    difficulty: 'medium',
    order_index: 71,
  },
  {
    id: 'qq-2-072',
    quiz_id: 'quiz-2',
    question: 'Chapter 2 says clients "hear" more than a barber\'s words. What does that mean in daily practice?',
    answer_a: 'Clients listen most carefully whenever the barber slows down and speaks with extra volume',
    answer_b: 'Tone of voice and body language carry part of the message, so they must match the words',
    answer_c: 'Clients form their impression of a barber mostly from the shop\'s music choices and decor',
    answer_d: 'Written aftercare instructions end up mattering far more than chair-side conversation does',
    correct_answer: 'b',
    explanation: 'Effective communication has three working parts: words, tone, and body language. When they conflict, the client believes the tone and body language — so professionalism means aligning all three, not just choosing good words.',
    difficulty: 'easy',
    order_index: 72,
  },
  {
    id: 'qq-2-073',
    quiz_id: 'quiz-2',
    question: 'A client describes a hair practice from their culture that the barber has never heard of. Which response best demonstrates cultural competence?',
    answer_a: 'Politely steer the client toward styles the barber already knows how to execute well',
    answer_b: 'Pretend to understand it completely and improvise the rest of the way through the service',
    answer_c: 'Show respectful curiosity — ask questions to understand it and adapt the service without judgment',
    answer_d: 'Suggest the client might honestly prefer a shop that specializes in "that kind of hair"',
    correct_answer: 'c',
    explanation: 'Cultural competence is respectful curiosity plus adaptation: ask, learn, and serve without judgment. Steering, bluffing, and referring away all tell the client their background is an inconvenience rather than a welcome part of service.',
    difficulty: 'hard',
    order_index: 73,
  },
  {
    id: 'qq-2-074',
    quiz_id: 'quiz-2',
    question: 'Which of the following is the best example of the specialization strategy described in Chapter 2?',
    answer_a: 'Offering every possible service on the menu so that no potential client is ever turned away',
    answer_b: 'Matching the exact service menu and pricing structure of the busiest barbershop in town',
    answer_c: 'Rotating to a brand-new specialty every month or two so that every skill stays equally fresh',
    answer_d: 'Becoming known for a signature skill — like precision fades or beard design — that sets you apart in the market',
    correct_answer: 'd',
    explanation: 'Specialization means developing a signature skill the market remembers you for. Generalizing, imitating competitors, and constant rotation all make a barber interchangeable; a recognized specialty builds reputation and pricing power.',
    difficulty: 'medium',
    order_index: 74,
  },
  {
    id: 'qq-2-075',
    quiz_id: 'quiz-2',
    question: 'A booth renter\'s income swings from $900 one week to $300 the next. Which Chapter 2 practice offers the most stable starting point for managing this?',
    answer_a: 'Keep business and personal money in separate accounts and budget against a conservative average week',
    answer_b: 'Build the entire monthly budget around the single best week so the spending plan stays ambitious',
    answer_c: 'Deposit everything into one shared personal account and keep a mental running total of the balance',
    answer_d: 'Hold off on any real budgeting until the weekly income becomes steady and perfectly predictable',
    correct_answer: 'a',
    explanation: 'Separate accounts keep business money visible, and budgeting against a conservative average absorbs slow weeks. Treat this as a starting framework to adjust as income patterns become clearer — not a fixed rule that fits every barber.',
    difficulty: 'medium',
    order_index: 75,
  },
]
