// Chapter 11: Treatment of the Hair and Scalp — PREMIUM FLASHCARDS
// Generated from textbook images — original wording, board-exam focused
// Total: 80 cards covering key terms, procedures, safety, and practical application

import { Flashcard } from './flashcards-data'

export const chapter11PremiumFlashcards: Flashcard[] = [
  // ═══════════════════════════════════════════════════
  // CATEGORY: Shampoo Service Fundamentals
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-11-001',
    chapter_id: 'ch-11',
    front: 'What is the primary purpose of a shampoo service?',
    back: 'To cleanse the scalp and hair, removing oils, dirt, and product buildup before cutting or styling.',
    category: 'Shampoo Service',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-11-002',
    chapter_id: 'ch-11',
    front: 'Why should barbers shampoo hair before cutting?',
    back: 'Clean hair is free from oils and products that can interfere with cutting tools and haircut results.',
    category: 'Shampoo Service',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-11-003',
    chapter_id: 'ch-11',
    front: 'What is the pH range of most shampoo products?',
    back: '4.5 to 7.5 — milder than soaps and detergents, leaving hair more manageable.',
    category: 'Shampoo Service',
    difficulty: 'medium',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-11-004',
    chapter_id: 'ch-11',
    front: 'What is the pH range of most hair conditioners?',
    back: '3.0 to 5.5 — helps restore moisture and smooth the cuticle after cleansing.',
    category: 'Shampoo Service',
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-11-005',
    chapter_id: 'ch-11',
    front: 'What are the two main types of draping capes used in barbering?',
    back: 'Shampoo capes (waterproof vinyl for wet/chemical services) and haircutting capes (nylon or synthetic for dry services).',
    category: 'Shampoo Service',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-11-006',
    chapter_id: 'ch-11',
    front: 'Why is a neck strip or towel required between the client\'s skin and the cape?',
    back: 'To prevent direct contact between the cape and client\'s skin, maintaining infection control compliance with state barber laws.',
    category: 'Shampoo Service',
    difficulty: 'medium',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-11-007',
    chapter_id: 'ch-11',
    front: 'What draping is required for a chemical service?',
    back: 'A cloth towel under the cape, folded over the neckband, plus a second towel over the cape neckline secured with a clip for drip protection.',
    category: 'Shampoo Service',
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-11-008',
    chapter_id: 'ch-11',
    front: 'What are the two methods of shampooing and rinsing?',
    back: 'Reclined method (client lies back in shampoo bowl) and inclined method (client bends forward over sink).',
    category: 'Shampoo Service',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-11-009',
    chapter_id: 'ch-11',
    front: 'Which shampooing method is most commonly used and why?',
    back: 'The reclined method — it is more comfortable for the client and allows greater speed and efficiency for the barber.',
    category: 'Shampoo Service',
    difficulty: 'easy',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-11-010',
    chapter_id: 'ch-11',
    front: 'What is draping?',
    back: 'Covering the client\'s skin and clothing with a cape and neck barrier for protection during services.',
    category: 'Shampoo Service',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY: Water Temperature & Safety
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-11-011',
    chapter_id: 'ch-11',
    front: 'What water temperature is recommended for shampooing?',
    back: 'Comfortably warm water — cold water causes discomfort and poor lathering; hot water can burn the scalp or cause dryness.',
    category: 'Safety & Technique',
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-11-012',
    chapter_id: 'ch-11',
    front: 'What can happen if shampoo water is too hot?',
    back: 'It can burn or blister the skin and cause the scalp to flake or become dry.',
    category: 'Safety & Technique',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-11-013',
    chapter_id: 'ch-11',
    front: 'Why should you always test water temperature before applying it to the client\'s head?',
    back: 'To prevent scalding or discomfort — water that feels fine to your hand may be too hot for the client\'s scalp.',
    category: 'Safety & Technique',
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-11-014',
    chapter_id: 'ch-11',
    front: 'What are common client complaints about shampoo services?',
    back: 'Improper product selection, insufficient scalp massage, extreme water temperatures, water running onto face/eyes, soiled clothing, fingernail scratching, improper blotting, and insufficient rinsing.',
    category: 'Safety & Technique',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY: Product Selection
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-11-015',
    chapter_id: 'ch-11',
    front: 'What six characteristics should be analyzed before choosing shampoo and conditioner products?',
    back: 'Scalp condition, hair condition, hair density, hair texture, hair porosity, and hair elasticity.',
    category: 'Product Selection',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-11-016',
    chapter_id: 'ch-11',
    front: 'What type of shampoo is recommended for fine straight hair?',
    back: 'Volumizing shampoo, fine-hair shampoo, and protein treatments.',
    category: 'Product Selection',
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-11-017',
    chapter_id: 'ch-11',
    front: 'What type of shampoo is recommended for coarse dry hair?',
    back: 'Moisturizing shampoo, leave-in conditioner, and moisturizing treatments.',
    category: 'Product Selection',
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-11-018',
    chapter_id: 'ch-11',
    front: 'What products are recommended for dry, damaged, chemically treated hair?',
    back: 'Gentle cleansing shampoo, moisturizing conditioner, protein and moisturizing repair treatments, and spray-on thermal protection.',
    category: 'Product Selection',
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-11-019',
    chapter_id: 'ch-11',
    front: 'Why should barbers read product labels and manufacturer directions?',
    back: 'To understand how products affect hair and scalp, enabling proper selection and recommendation for each client\'s needs.',
    category: 'Product Selection',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-11-020',
    chapter_id: 'ch-11',
    front: 'What is a scalp conditioner?',
    back: 'A cream or ointment used for overall scalp maintenance or to treat conditions requiring a medicinal product.',
    category: 'Product Selection',
    difficulty: 'easy',
    order_index: 20,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY: Scalp Massage Techniques
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-11-021',
    chapter_id: 'ch-11',
    front: 'What are the three main scalp massage manipulations?',
    back: 'Rotary movement, sliding movement, and back-and-forth movement.',
    category: 'Massage Techniques',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-11-022',
    chapter_id: 'ch-11',
    front: 'Describe the rotary massage movement.',
    back: 'Using thumbs and/or fingertips to produce overlapping circular movements with moderate to firm pressure throughout the scalp area.',
    category: 'Massage Techniques',
    difficulty: 'easy',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-11-023',
    chapter_id: 'ch-11',
    front: 'Describe the sliding massage movement.',
    back: 'Using thumbs and fingertips to produce sliding strokes with moderate to firm pressure; hands often overlap as they meet over a section of the head.',
    category: 'Massage Techniques',
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-11-024',
    chapter_id: 'ch-11',
    front: 'Describe the back-and-forth massage movement.',
    back: 'Using thumbs and/or fingertips to produce a brisk back-and-forth movement with moderate to firm pressure.',
    category: 'Massage Techniques',
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-11-025',
    chapter_id: 'ch-11',
    front: 'What four physiological effects does scalp massage achieve?',
    back: 'Increased blood and lymph flow, soothed nerves, stimulated scalp muscles and glands, and a more flexible scalp.',
    category: 'Massage Techniques',
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-11-026',
    chapter_id: 'ch-11',
    front: 'Where should massage manipulations start on the scalp?',
    back: 'At the hairline, working with even pressure and continuous synchronized movements.',
    category: 'Massage Techniques',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-11-027',
    chapter_id: 'ch-11',
    front: 'What pressure is recommended for scalp massage movements?',
    back: 'Moderate to firm pressure — firm enough to stimulate circulation but not so hard as to cause discomfort.',
    category: 'Massage Techniques',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-11-028',
    chapter_id: 'ch-11',
    front: 'What should be avoided during scalp massage?',
    back: 'Pulling the hair in any way — keep fingertips on the scalp, not grasping hair strands.',
    category: 'Massage Techniques',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-11-029',
    chapter_id: 'ch-11',
    front: 'Which massage movements are typically used during a shampoo service?',
    back: 'A combination of rotary/circular movements and back-and-forth scrubbing-type movements.',
    category: 'Massage Techniques',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-11-030',
    chapter_id: 'ch-11',
    front: 'Which massage movements are typically used during a scalp treatment?',
    back: 'Rotary and sliding movements.',
    category: 'Massage Techniques',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY: Scalp & Hair Treatments
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-11-031',
    chapter_id: 'ch-11',
    front: 'What is the purpose of scalp and hair treatments?',
    back: 'To preserve the health and appearance of hair and scalp, and help prevent or combat disorders like dandruff, dryness, and oiliness.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-11-032',
    chapter_id: 'ch-11',
    front: 'What are the two essential requirements for healthy hair and scalp?',
    back: 'Cleanliness and stimulation.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-11-033',
    chapter_id: 'ch-11',
    front: 'What causes dry scalp and hair?',
    back: 'Inactivity of oil glands, poor blood circulation, and excessive removal of natural oils by harsh products.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-11-034',
    chapter_id: 'ch-11',
    front: 'What products should be avoided for dry scalp conditions?',
    back: 'Strong soaps, greasy preparations, and lotions with high alcohol content.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-11-035',
    chapter_id: 'ch-11',
    front: 'What causes oily scalp and hair?',
    back: 'Overactive sebaceous glands, improper diet, or lack of hygienic practices.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-11-036',
    chapter_id: 'ch-11',
    front: 'How can regular shampooing help oily scalp conditions?',
    back: 'It minimizes oil buildup and keeps the scalp clean.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-11-037',
    chapter_id: 'ch-11',
    front: 'What is the technical term for dandruff?',
    back: 'Pityriasis.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-11-038',
    chapter_id: 'ch-11',
    front: 'What causes dandruff?',
    back: 'The fungus Malassezia growing out of control on the scalp.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-11-039',
    chapter_id: 'ch-11',
    front: 'What are common antifungal ingredients in antidandruff shampoos?',
    back: 'Pyrithione zinc, selenium sulfide, and ketoconazole.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-11-040',
    chapter_id: 'ch-11',
    front: 'What is pityriasis capitis simplex?',
    back: 'The technical term for common dandruff — characterized by scalp irritation, large flakes, and itching.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-11-041',
    chapter_id: 'ch-11',
    front: 'What is pityriasis steatoides?',
    back: 'A more severe form of dandruff with greasy or waxy scales mixed with sebum that adhere to the scalp in patches.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-11-042',
    chapter_id: 'ch-11',
    front: 'What is seborrheic dermatitis?',
    back: 'A condition where severe dandruff (pityriasis steatoides) is accompanied by redness and inflammation; may also appear on eyebrows and beard.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-11-043',
    chapter_id: 'ch-11',
    front: 'What should a barber do if a client has prescribed topical medication for a scalp condition?',
    back: 'Do not apply it without prescription directions, and save a copy with the client\'s record card.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-11-044',
    chapter_id: 'ch-11',
    front: 'What services may be included in a hair or scalp treatment?',
    back: 'Cleansing with shampoo, scalp steaming, massage with hands or electric appliance, infrared/ultraviolet lamps, high-frequency current, and application of tonics, astringents, antiseptics, or ointments.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY: Scalp Steam & Equipment
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-11-045',
    chapter_id: 'ch-11',
    front: 'What is the purpose of scalp steam?',
    back: 'To relax pores, soften the scalp and hair, and increase blood circulation before massage and treatments.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-11-046',
    chapter_id: 'ch-11',
    front: 'What can be used as an alternative to a scalp steamer?',
    back: 'Hot towels — prepared in a hot-towel cabinet or soaked in hot water, wrung out, and applied to the head.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-11-047',
    chapter_id: 'ch-11',
    front: 'How many hot towel applications are usually sufficient for a scalp steam?',
    back: 'Two or three towels, replacing each as it cools.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-11-048',
    chapter_id: 'ch-11',
    front: 'What is an electric massager (vibrator) used for in barbering?',
    back: 'To perform stimulating scalp massage by transmitting vibrations through the fingertips to the scalp.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-11-049',
    chapter_id: 'ch-11',
    front: 'How should an electric massager be positioned on the hand?',
    back: 'On the back of the hand, leaving the thumb and fingers free to move over the scalp.',
    category: 'Equipment',
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-11-050',
    chapter_id: 'ch-11',
    front: 'What three variables must be controlled when using an electric massager?',
    back: 'Intensity, duration of vibrations, and pressure applied.',
    category: 'Equipment',
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },
  {
    id: 'fc-11-051',
    chapter_id: 'ch-11',
    front: 'How often should scalp massage be performed for normal scalp maintenance?',
    back: 'Once a week — more frequently for scalp disorders only under a dermatologist\'s direction.',
    category: 'Equipment',
    difficulty: 'medium',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-11-052',
    chapter_id: 'ch-11',
    front: 'What are the five steps of a hair tonic treatment?',
    back: '1) Apply hair tonic, 2) Massage scalp, 3) Apply scalp steam, 4) Massage again with hands or vibrator, 5) Comb into desired style.',
    category: 'Equipment',
    difficulty: 'medium',
    order_index: 52,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY: Contraindications & Safety
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-11-053',
    chapter_id: 'ch-11',
    front: 'What scalp conditions prohibit a barber from performing services?',
    back: 'Parasitic infestations (head lice, scabies), fungal infections (tinea), staphylococcus infections, open abrasions, or signs of irritation and inflammation.',
    category: 'Safety & Contraindications',
    difficulty: 'medium',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-11-054',
    chapter_id: 'ch-11',
    front: 'What should a barber do if parasites are found during scalp analysis?',
    back: 'Do not begin any service — refer the client to a physician or pharmacist.',
    category: 'Safety & Contraindications',
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-11-055',
    chapter_id: 'ch-11',
    front: 'Should chemical services be performed on irritated or abraded scalps?',
    back: 'No — do not proceed with chemical services if there are signs of irritation or abrasions.',
    category: 'Safety & Contraindications',
    difficulty: 'easy',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-11-056',
    chapter_id: 'ch-11',
    front: 'Why is it important to check the scalp before every service?',
    back: 'To identify disorders or conditions that could prohibit the service and to detect early signs of skin cancer or other medical concerns.',
    category: 'Safety & Contraindications',
    difficulty: 'medium',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-11-057',
    chapter_id: 'ch-11',
    front: 'What is a hypertrophy and why does it require care during combing?',
    back: 'An abnormal skin growth such as a mole or wart — the comb can catch on these growths and cause injury.',
    category: 'Safety & Contraindications',
    difficulty: 'medium',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-11-058',
    chapter_id: 'ch-11',
    front: 'When should a barber suggest a client see a physician regarding a scalp growth?',
    back: 'If changes are observed in a hypertrophy from one visit to another, or if any unusual pigmentation or growth is noticed.',
    category: 'Safety & Contraindications',
    difficulty: 'medium',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-11-059',
    chapter_id: 'ch-11',
    front: 'Is dandruff contagious?',
    back: 'No — current research has determined dandruff is not contagious, though barbers must still disinfect tools between clients.',
    category: 'Safety & Contraindications',
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-11-060',
    chapter_id: 'ch-11',
    front: 'Is tinea (ringworm) contagious?',
    back: 'Yes — tinea is highly contagious and spreads through infected skin scales, hair, unclean combs, brushes, and contact with contaminated surfaces.',
    category: 'Safety & Contraindications',
    difficulty: 'easy',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-11-061',
    chapter_id: 'ch-11',
    front: 'What should a barber do if a client has suspected or confirmed tinea?',
    back: 'Refer to a physician for medical treatment and do not perform services until the condition has cleared.',
    category: 'Safety & Contraindications',
    difficulty: 'easy',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-11-062',
    chapter_id: 'ch-11',
    front: 'Should gloves be worn when shampooing a client with dandruff?',
    back: 'Yes — it is advisable to wear gloves as a precautionary measure.',
    category: 'Safety & Contraindications',
    difficulty: 'easy',
    order_index: 62,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY: Hair Analysis
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-11-063',
    chapter_id: 'ch-11',
    front: 'What are the five senses used during hair and scalp analysis?',
    back: 'Sight, hearing, smell, touch, and consultation with the client.',
    category: 'Hair Analysis',
    difficulty: 'medium',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-11-064',
    chapter_id: 'ch-11',
    front: 'Why is touch considered the key sense for analyzing hair condition?',
    back: 'It reveals texture, thickness, elasticity, and porosity that cannot be determined by sight alone.',
    category: 'Hair Analysis',
    difficulty: 'medium',
    order_index: 64,
    is_active: true,
  },
  {
    id: 'fc-11-065',
    chapter_id: 'ch-11',
    front: 'How is hair texture determined?',
    back: 'By feeling a single strand of dry hair between the fingers and rolling it to assess diameter — classified as coarse, medium, or fine.',
    category: 'Hair Analysis',
    difficulty: 'medium',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-11-066',
    chapter_id: 'ch-11',
    front: 'How is hair porosity tested?',
    back: 'Slide thumb and forefinger up and down dry hair strands toward the scalp — smooth hair indicates low porosity; roughness or raised scales indicate high porosity.',
    category: 'Hair Analysis',
    difficulty: 'medium',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-11-067',
    chapter_id: 'ch-11',
    front: 'How is hair elasticity tested?',
    back: 'Gently tug a few strands of clean, wet hair — normal hair stretches and returns to original length; low elasticity breaks or fails to return.',
    category: 'Hair Analysis',
    difficulty: 'medium',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-11-068',
    chapter_id: 'ch-11',
    front: 'What does low hair elasticity indicate?',
    back: 'Brittle hair that breaks easily — may result from overprocessing, poor nutrition, or internal disorders.',
    category: 'Hair Analysis',
    difficulty: 'medium',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-11-069',
    chapter_id: 'ch-11',
    front: 'What is the average number of hairs on a human head?',
    back: 'Approximately 100,000 individual strands, with about 2,200 strands per square inch.',
    category: 'Hair Analysis',
    difficulty: 'medium',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-11-070',
    chapter_id: 'ch-11',
    front: 'Which hair color typically has the highest density?',
    back: 'Blond hair — averaging about 140,000 strands.',
    category: 'Hair Analysis',
    difficulty: 'medium',
    order_index: 70,
    is_active: true,
  },
  {
    id: 'fc-11-071',
    chapter_id: 'ch-11',
    front: 'Which hair color typically has the lowest density?',
    back: 'Red hair — averaging about 80,000 strands.',
    category: 'Hair Analysis',
    difficulty: 'medium',
    order_index: 71,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY: Board Exam Alerts & Professional Practice
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-11-072',
    chapter_id: 'ch-11',
    front: 'Why is proper draping required before any barbering service?',
    back: 'To maintain compliance with state barber laws and infection control standards, protecting the client\'s skin and clothing.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 72,
    is_active: true,
  },
  {
    id: 'fc-11-073',
    chapter_id: 'ch-11',
    front: 'What documentation is required for out-of-shop services?',
    back: 'The client\'s name, times, and destination must be recorded in the appointment book.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 73,
    is_active: true,
  },
  {
    id: 'fc-11-074',
    chapter_id: 'ch-11',
    front: 'What posture guidelines prevent back strain during shampooing?',
    back: 'Stand close to the client\'s head, flex knees slightly, keep chin parallel to floor, chest up, abdomen flat, and shoulders relaxed.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 74,
    is_active: true,
  },
  {
    id: 'fc-11-075',
    chapter_id: 'ch-11',
    front: 'What should a barber do when a disabled or wheelchair-bound client needs shampooing?',
    back: 'Ask the client how they would like to be shampooed and prioritize their comfort and safety.',
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 75,
    is_active: true,
  },
  {
    id: 'fc-11-076',
    chapter_id: 'ch-11',
    front: 'Why should retail products be displayed and used at the workstation?',
    back: 'To promote product sales and demonstrate the barber\'s endorsement of the products.',
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 76,
    is_active: true,
  },
  {
    id: 'fc-11-077',
    chapter_id: 'ch-11',
    front: 'What are liquid-dry or powder shampoos used for?',
    back: 'To freshen hair and scalp when a wet shampoo is not feasible, such as for bedridden clients.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 77,
    is_active: true,
  },
  {
    id: 'fc-11-078',
    chapter_id: 'ch-11',
    front: 'What is the difference between shampoo massage and scalp treatment massage movements?',
    back: 'Shampoo massage uses rotary/circular plus back-and-forth scrubbing movements; scalp treatment massage uses rotary plus sliding movements.',
    category: 'Board Exam Alert',
    difficulty: 'hard',
    order_index: 78,
    is_active: true,
  },
  {
    id: 'fc-11-079',
    chapter_id: 'ch-11',
    front: 'What muscles and nerves are affected by massage on the sides to top of the head?',
    back: 'Muscles: auricularis superior, temporalis, frontalis. Nerves: fifth and seventh cranial nerves.',
    category: 'Board Exam Alert',
    difficulty: 'hard',
    order_index: 79,
    is_active: true,
  },
  {
    id: 'fc-11-080',
    chapter_id: 'ch-11',
    front: 'What is the professional scope of practice for barbers regarding scalp disorders?',
    back: 'Barbers may perform general scalp maintenance and corrective treatments for non-medical conditions, but must refer clients with parasitic infestations, staphylococcus infections, or abnormal scalp conditions to a physician.',
    category: 'Board Exam Alert',
    difficulty: 'hard',
    order_index: 80,
    is_active: true,
  },
]

export default chapter11PremiumFlashcards
