// Chapter 9 Premium Flashcards — The Skin Safety Academy
// 50 cards derived from Chapter 9 V2 immersive content
// Categories: Skin Structure, Epidermis Layers, Dermis & Subcutaneous, Glands & Functions,
//             Primary Lesions, Secondary Lesions, Sebaceous Disorders, Sudoriferous & Inflammations,
//             Pigment & Hypertrophies, Skin Cancer & Safety

import { Flashcard } from '@/types'

export const chapter9PremiumFlashcards: Flashcard[] = [
  // ═══════════════════════════════════════════════════
  // CATEGORY 1: SKIN STRUCTURE & BASICS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-001',
    chapter_id: 'ch-9',
    front: 'What is the largest organ of the human body?',
    back: 'The SKIN. It is the body\'s first line of defense against disease and the environment, and it protects internal organs while regulating temperature and providing sensory information.',
    category: 'Skin Structure & Basics',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-9-002',
    chapter_id: 'ch-9',
    front: 'How does Chapter 9 describe the pH of healthy skin, and why does that matter?',
    back: 'Healthy skin is described as SLIGHTLY ACIDIC. That surface condition supports the skin\'s protective barrier. The chapter does not require memorizing one exact pH number as the main learning target.',
    category: 'Skin Structure & Basics',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-9-003',
    chapter_id: 'ch-9',
    front: 'Where is the THINNEST skin on the body? Where is the THICKEST?',
    back: 'THINNEST: Eyelids. THICKEST: Palms and soles. Skin thickness varies across the body, which affects absorption rates and service sensitivity.',
    category: 'Skin Structure & Basics',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-9-004',
    chapter_id: 'ch-9',
    front: 'How do blood and lymph support the skin?',
    back: 'BLOOD supplies oxygen and nutrients that support skin growth, nourishment, and repair. LYMPH helps carry away waste and excess fluid. Dermal circulation also supports temperature regulation. The durable study target is what these systems DO for the skin — not memorizing a single blood-supply percentage.',
    category: 'Skin Structure & Basics',
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-9-005',
    chapter_id: 'ch-9',
    front: 'What are the two main divisions of the skin?',
    back: '1. EPIDERMIS — outermost protective layer (no blood vessels)\n2. DERMIS — underlying thicker layer containing glands, vessels, follicles, and nerves.\n\nThe subcutaneous tissue (hypodermis/adipose) is below the dermis but is not technically a division of the skin itself.',
    category: 'Skin Structure & Basics',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 2: EPIDERMIS LAYERS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-006',
    chapter_id: 'ch-9',
    front: 'What are the five layers of the epidermis, from deepest to surface?',
    back: '1. Stratum GERMINATIVUM (basal cell layer)\n2. Stratum SPINOSUM (spiny layer)\n3. Stratum GRANULOSUM (granular layer)\n4. Stratum LUCIDUM (clear layer)\n5. Stratum CORNEUM (horny layer)\n\nMnemonic: "Go Somewhere Good, Life Continues."',
    category: 'Epidermis Layers',
    difficulty: 'medium',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-9-007',
    chapter_id: 'ch-9',
    front: 'Which epidermis layer contains melanocytes, and what do they produce?',
    back: 'The STRATUM GERMINATIVUM (basal cell layer) contains MELANOCYTES, which produce MELANIN — the pigment that gives skin its color and protects against UV damage.',
    category: 'Epidermis Layers',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-9-008',
    chapter_id: 'ch-9',
    front: 'Does the epidermis contain blood vessels?',
    back: 'NO. The epidermis is AVASCULAR — it contains no blood vessels. It receives nourishment from the dermis below.',
    category: 'Epidermis Layers',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-9-009',
    chapter_id: 'ch-9',
    front: 'What is the function of the stratum corneum, and what waterproofs it?',
    back: 'The STRATUM CORNEUM is the outermost layer of tightly packed, scale-like cells that are continually shed and replaced. It is waterproofed by SEBUM from sebaceous glands, which prevents moisture loss and microbial entry.',
    category: 'Epidermis Layers',
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-9-010',
    chapter_id: 'ch-9',
    front: 'In which layer of the epidermis are cells filled with keratin and becoming almost dead?',
    back: 'The STRATUM GRANULOSUM (granular layer). Keratin is the protein that makes skin waterproof and durable. By the time cells reach this layer, they are transitioning from living to dead.',
    category: 'Epidermis Layers',
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 3: DERMIS, SUBCUTANEOUS & NERVES (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-011',
    chapter_id: 'ch-9',
    front: 'How does Chapter 9 compare the thickness of the dermis with the epidermis?',
    back: 'Chapter 9 describes the DERMIS as approximately 25× THICKER than the epidermis. It contains many key structures, including blood vessels, glands, hair follicles, nerves, lymph structures, and arrector pili muscles.',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-9-012',
    chapter_id: 'ch-9',
    front: 'What are the two layers of the dermis, and what does each contain?',
    back: '1. PAPILLARY LAYER (superficial): Contains papillae (conical projections), tactile corpuscles for touch, looped capillaries, and some melanin.\n2. RETICULAR LAYER (deeper): Supplies oxygen and nutrients. Contains fat cells, sweat glands, blood vessels, hair follicles, lymph glands, arrector pili muscles, and oil glands.',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-9-013',
    chapter_id: 'ch-9',
    front: 'What are the three types of nerve fibers in the skin, and what does each control?',
    back: '1. MOTOR nerve fibers — control arrector pili muscles (goose bumps) and stimulate glandular activity.\n2. SENSORY nerve fibers — react to heat, cold, touch, pressure, and pain.\n3. SECRETORY nerve fibers — regulate sweat and oil gland secretion.',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-9-014',
    chapter_id: 'ch-9',
    front: 'What roles do collagen and elastin play in the skin?',
    back: 'COLLAGEN provides strength and structural support. ELASTIN provides elasticity and flexibility, allowing tissue to stretch and return toward its original shape. With age, reduced support and elasticity contribute to sagging and wrinkles.',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-9-015',
    chapter_id: 'ch-9',
    front: 'What is the subcutaneous tissue also called, and what are its four functions?',
    back: 'Also called HYPODERMIS or ADIPOSE TISSUE. Its four functions are:\n1. SMOOTHNESS — provides smoothness and contour\n2. ENERGY STORAGE — stores fat as an energy reserve\n3. CUSHIONING — protects underlying organs from impact\n4. INSULATION — helps regulate body temperature',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 4: GLANDS & SKIN FUNCTIONS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-016',
    chapter_id: 'ch-9',
    front: 'What does the SHAPES mnemonic stand for — the six functions of the skin?',
    back: 'S — SENSATION (touch, pressure, pain, heat, cold)\nH — HEAT REGULATION (maintains ~98.6°F via blood flow and sweat)\nA — ABSORPTION (limited; topical medications)\nP — PROTECTION (barrier against pathogens, injury, chemicals)\nE — EXCRETION (perspiration removes waste)\nS — SECRETION (sebum lubricates skin and hair)',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-9-017',
    chapter_id: 'ch-9',
    front: 'What is the difference between sebaceous glands and sudoriferous glands?',
    back: 'SEBACEOUS (oil) glands: Connected to hair follicles, produce SEBUM to lubricate skin and hair, most active on face and scalp.\nSUDORIFEROUS (sweat) glands: Coiled base with duct to surface, produce SWEAT to regulate body temperature and eliminate waste.\n\nMnemonic: SEBACEOUS = SEbum. SUDORIFEROUS = SWeat.',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-9-018',
    chapter_id: 'ch-9',
    front: 'What happens when sebum and debris block a hair follicle?',
    back: 'Blocked material can form COMEDONES. An OPEN COMEDO (blackhead) is exposed to air, causing the sebum to oxidize and darken; it is not simply dirt. A CLOSED COMEDO (whitehead) remains covered by skin and appears as a small white bump.',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-9-019',
    chapter_id: 'ch-9',
    front: 'Where are sudoriferous (sweat) glands especially numerous, and what is their major function?',
    back: 'They are especially numerous on the PALMS, SOLES, FOREHEAD, and ARMPITS. Their major function is producing perspiration that helps regulate body temperature.',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-9-020',
    chapter_id: 'ch-9',
    front: 'What is melanin, where is it produced, and what does Chapter 9 say it does?',
    back: 'MELANIN is pigment produced by MELANOCYTES in the STRATUM GERMINATIVUM (basal layer). It contributes to skin color and helps screen/protect the skin from the sun\'s rays.',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 20,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 5: PRIMARY LESIONS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-021',
    chapter_id: 'ch-9',
    front: 'How do a BULLA and a VESICLE differ?',
    back: 'Both are fluid-filled primary lesions. A BULLA is a LARGE blister containing watery fluid, while a VESICLE is a SMALL blister containing clear fluid. Size is the key practical distinction emphasized in Chapter 9.',
    category: 'Primary Lesions',
    difficulty: 'medium',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-9-022',
    chapter_id: 'ch-9',
    front: 'What is a PUSTULE, and what service-safety decision should a barber make around one?',
    back: 'A PUSTULE is an inflamed, raised lesion containing PUS. Acne, impetigo, and folliculitis may produce pustules. A pustule does not by itself prove a specific diagnosis. For service safety, do not work directly over an open, draining, or potentially infectious lesion. Pause the affected service and follow school/state sanitation and referral guidance when the condition is unfamiliar or concerning.',
    category: 'Primary Lesions',
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-9-023',
    chapter_id: 'ch-9',
    front: 'What is a MACULE, and how is it distinguished from a raised lesion?',
    back: 'A MACULE is a flat spot or discoloration with no change in skin texture. Examples include freckles, liver spots, and birthmarks. The key distinction is that it is FLAT rather than raised.',
    category: 'Primary Lesions',
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-9-024',
    chapter_id: 'ch-9',
    front: 'What is a WHEAL, and what commonly causes it?',
    back: 'A WHEAL is an itchy, swollen lesion caused by fluid accumulation in the skin. Examples include hives, insect bites, and allergic reactions. Wheals often resolve on their own, but persistent or worsening lesions may warrant medical evaluation.',
    category: 'Primary Lesions',
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-9-025',
    chapter_id: 'ch-9',
    front: 'What is the difference between a PAPULE and a NODULE?',
    back: 'Both are solid, raised lesions:\n• PAPULE — small elevation of the skin with no pus (e.g., early acne, warts)\n• NODULE — solid bump LARGER than 0.4 inch, extending DEEPER into the skin (e.g., swollen lymph nodes, cystic acne)\n\nA papule becomes a pustule when it fills with pus.',
    category: 'Primary Lesions',
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 6: SECONDARY LESIONS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-026',
    chapter_id: 'ch-9',
    front: 'What is the difference between PRIMARY and SECONDARY skin lesions?',
    back: 'PRIMARY lesions are the ORIGINAL lesions — they appear first, directly from a disease process or injury. They are typically different in color and may be raised.\n\nSECONDARY lesions EVOLVE from primary lesions through accumulation, infection, or healing. Example: a vesicle that breaks open and dries becomes a CRUST.',
    category: 'Secondary Lesions',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-9-027',
    chapter_id: 'ch-9',
    front: 'What is a KELOID?',
    back: 'A KELOID is a thick scar caused by excessive growth of fibrous tissue. It develops as part of an abnormal scar response after skin injury.',
    category: 'Secondary Lesions',
    difficulty: 'medium',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-9-028',
    chapter_id: 'ch-9',
    front: 'What is a FISSURE?',
    back: 'A FISSURE is a crack in the skin that penetrates into the dermis. Severely chapped or cracked hands and lips are examples.',
    category: 'Secondary Lesions',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-9-029',
    chapter_id: 'ch-9',
    front: 'What is an ULCER, and what is the barbering safety boundary?',
    back: 'An ULCER is an open lesion with loss of skin depth. Herpes lesions and other open sores may ulcerate. Do not work directly over an open or compromised lesion. Pause the affected service and recommend medical evaluation when appropriate, especially when an underlying condition may be involved.',
    category: 'Secondary Lesions',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-9-030',
    chapter_id: 'ch-9',
    front: 'What is a SCALE, and what conditions may produce scaling?',
    back: 'A SCALE is a thin, dry, or oily flake of dead skin cells. Dandruff, psoriasis, and seborrheic dermatitis may produce scaling. Use gentle service judgment and refer when the condition is unknown, inflamed, contagious, or outside barbering scope.',
    category: 'Secondary Lesions',
    difficulty: 'easy',
    order_index: 30,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 7: SEBACEOUS GLAND DISORDERS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-031',
    chapter_id: 'ch-9',
    front: 'What causes acne (acne vulgaris), and what are the four grades?',
    back: 'CAUSE: Bacteria (Propionibacterium acnes) multiply in clogged follicles, causing inflammation and infection. Hormonal changes and excess sebum contribute.\n\nGRADES:\nI — Mild: minor breakouts, mostly blackheads\nII — Moderate: more blackheads, papules, some pustules\nIII — Severe: numerous papules and pustules, inflammation spreading\nIV — Very severe: cystic acne with deep, painful lesions',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-9-032',
    chapter_id: 'ch-9',
    front: 'What is ROSACEA, and what service approach is appropriate?',
    back: 'ROSACEA is a chronic condition associated with flushing, redness, visible blood vessels, and sometimes papules or pustules on the face. Common triggers discussed in Chapter 9 include sun exposure, spicy foods, alcohol, stress, hot beverages, and temperature extremes. Use gentle service judgment on irritated skin and avoid diagnosing or treating the condition; medical management belongs to qualified professionals.',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-9-033',
    chapter_id: 'ch-9',
    front: 'How does Chapter 9 describe SEBORRHEIC DERMATITIS?',
    back: 'SEBORRHEIC DERMATITIS may appear as red, dry or oily, scaly, crusty patches, often on the scalp. A barber should recognize the appearance, handle irritated skin gently, and stay within service scope rather than presenting a medical diagnosis or treatment plan.',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-9-034',
    chapter_id: 'ch-9',
    front: 'How does Chapter 9 distinguish a SEBACEOUS CYST from a STEATOMA?',
    back: 'SEBACEOUS CYST: a pocket-like lesion associated with sebum. STEATOMA: a subcutaneous tumor of fatty tissue, sometimes called a wen. Do not treat the terms as interchangeable — Chapter 9 presents them as different conditions.',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-9-035',
    chapter_id: 'ch-9',
    front: 'What is ASTEATOSIS, and what factors does Chapter 9 associate with it?',
    back: 'ASTEATOSIS is dry, scaly skin associated with a deficiency of sebum. Chapter 9 connects it with aging, exposure to cold or alkalies, and certain bodily disorders. The barbering role is observation and gentle service judgment, not diagnosis or medical treatment.',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 8: SUDORIFEROUS DISORDERS & INFLAMMATIONS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-036',
    chapter_id: 'ch-9',
    front: 'What is ANHIDROSIS, and why does it require caution?',
    back: 'ANHIDROSIS is a deficiency or absence of perspiration. Severe inability to sweat can interfere with normal heat regulation and may require medical attention. In barbering, treat heat-related service decisions as a safety application and avoid making a medical diagnosis.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-9-037',
    chapter_id: 'ch-9',
    front: 'How do DERMATITIS and ECZEMA differ in Chapter 9?',
    back: 'DERMATITIS is a general term for inflammation of the skin. ECZEMA is an inflammatory skin disease that may be acute or chronic and is described as noncontagious. Chapter 9 indicates eczema cases should be referred to a physician for treatment; barbers should recognize irritation without diagnosing it.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-9-038',
    chapter_id: 'ch-9',
    front: 'What is PSORIASIS, and how should a barber approach affected skin?',
    back: 'PSORIASIS is a chronic, noncontagious condition characterized by red patches covered with coarse, silvery scales. A barber should handle affected areas gently, avoid unnecessary irritation, and stay within barbering scope rather than trying to diagnose or medically treat the condition.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'easy',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-9-039',
    chapter_id: 'ch-9',
    front: 'What is the barbering safety response to active HERPES SIMPLEX lesions?',
    back: 'Herpes simplex is a recurrent viral infection and is contagious during active outbreaks. Pause services that would contact active lesions, follow school/state sanitation requirements, and recommend appropriate medical evaluation. Do not diagnose or prescribe treatment.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-9-040',
    chapter_id: 'ch-9',
    front: 'What is MILIARIA RUBRA (prickly heat), and how does heat relate to it?',
    back: 'MILIARIA RUBRA is an acute inflammatory condition with small red vesicles and intense itching associated with excessive heat. Avoid adding unnecessary heat to an already irritated area as an ASCYN service-safety application, while recognizing that diagnosis and treatment are outside barbering scope.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'medium',
    order_index: 40,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 9: PIGMENT DISORDERS & HYPERTROPHIES (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-041',
    chapter_id: 'ch-9',
    front: 'What is the difference between HYPERPIGMENTATION and HYPOPIGMENTATION?',
    back: 'HYPERPIGMENTATION means areas of skin are darker than normal because of increased pigment. HYPOPIGMENTATION means areas are lighter because of decreased pigment. Chapter 9 examples include chloasma, freckles, liver spots, vitiligo, and leukoderma. These terms describe pigment changes; they do not by themselves determine whether a service is appropriate.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-9-042',
    chapter_id: 'ch-9',
    front: 'What is ALBINISM, and what characteristics does Chapter 9 describe?',
    back: 'ALBINISM is a congenital form of hypopigmentation caused by an absence or marked lack of normal melanin production. Chapter 9 describes very light skin and hair and increased light sensitivity. A barber should recognize the condition without diagnosing or prescribing individualized medical care.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'medium',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-9-043',
    chapter_id: 'ch-9',
    front: 'What is a VERRUCA (wart), and what is the barbering safety concern?',
    back: 'A VERRUCA is a viral, infectious growth that can spread through contact or scratching. Avoid traumatizing or working directly over an active wart, use appropriate sanitation precautions, and recommend qualified medical evaluation when removal or treatment is needed.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'medium',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-9-044',
    chapter_id: 'ch-9',
    front: 'What is a KERATOMA, and how does Chapter 9 describe calluses and corns?',
    back: 'A KERATOMA is a thickened area of skin caused by continued pressure or friction. Calluses and corns are examples. Chapter 9 describes calluses as a natural protective response and notes that removing them does not solve the pressure that caused them.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'easy',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-9-045',
    chapter_id: 'ch-9',
    front: 'What is a NEVUS (mole), and what change should prompt referral?',
    back: 'A NEVUS is a small pigmented spot or growth. Many are benign, but changes in asymmetry, border, color, diameter, or evolution should be described to the client without diagnosing and may warrant medical evaluation.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'medium',
    order_index: 45,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 10: SKIN CANCER & SAFETY (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-046',
    chapter_id: 'ch-9',
    front: 'How does Chapter 9 distinguish the three skin cancers it discusses?',
    back: 'BASAL CELL CARCINOMA — the most common and least severe of the three discussed; may appear as pearly or waxy lesions and rarely spreads. SQUAMOUS CELL CARCINOMA — more serious and can spread to other parts of the body. MALIGNANT MELANOMA — the least common but most dangerous of the three. Barbers observe concerning changes and refer; diagnosis belongs to qualified medical professionals.',
    category: 'Skin Cancer & Safety',
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-9-047',
    chapter_id: 'ch-9',
    front: 'What does the ABCDE melanoma observation guide stand for?',
    back: 'A — ASYMMETRY; B — BORDER irregularity; C — COLOR variation; D — DIAMETER greater than about 6 mm; E — EVOLUTION or change. This is an observation framework for noticing concerning changes and recommending medical evaluation — not a tool for diagnosing melanoma.',
    category: 'Skin Cancer & Safety',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-9-048',
    chapter_id: 'ch-9',
    front: 'Why is earlier medical evaluation important when melanoma is suspected?',
    back: 'Chapter 9 teaches that outcomes are better when malignant melanoma is identified and treated earlier, while prognosis worsens after the cancer spreads. The durable learning target is EARLY RECOGNITION AND REFERRAL — not memorizing survival percentages that can vary by source and over time.',
    category: 'Skin Cancer & Safety',
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-9-049',
    chapter_id: 'ch-9',
    front: 'What should a barber do when a client has a suspected contagious or infectious skin condition in the service area?',
    back: 'Do not perform a service directly over suspected contagious or infectious conditions such as pediculosis, scabies, impetigo, active herpes lesions, or infectious warts. Pause the affected service, follow school/state sanitation requirements, and refer for appropriate medical evaluation when needed.',
    category: 'Skin Cancer & Safety',
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-9-050',
    chapter_id: 'ch-9',
    front: 'What is a barber\'s professional responsibility when noticing a suspicious or unfamiliar skin condition?',
    back: 'OBSERVE and describe what you see without diagnosing. PAUSE any service that could contact or worsen the affected area. REFER the client for qualified medical evaluation when appropriate. DOCUMENT the observation only when required by school, shop, or applicable policy. The goal is safe service within barbering scope.',
    category: 'Skin Cancer & Safety',
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },
]
