import { QuizQuestion } from '@/types'

// Chapter 17: Chemical Texture Services — PREMIUM MCQ QUIZ
// 30 chapter-assessment questions + 16 learning questions
// Original content; no textbook or exam questions copied.

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER-ASSESSMENT QUESTION BANK (30 questions)
// Cognitive distribution: 14 Recall / 11 Application / 5 Analysis
// ═══════════════════════════════════════════════════════════════════════════════
export const chapter17PremiumQuizQuestions: QuizQuestion[] = [
  // === CONSULTATION & ANALYSIS (5 questions) ===
  {
    id: 'qq-17-001',
    standardId: 'CH17-Q001',
    quiz_id: 'quiz-17',
    question: 'Which factor helps indicate how readily hair may accept a chemical texture product?',
    answer_a: 'Density',
    answer_b: 'Porosity',
    answer_c: 'Texture',
    answer_d: 'Elasticity',
    correct_answer: 'b',
    explanation: 'Porosity helps indicate how readily hair may accept product, but processing decisions must use the complete hair analysis and manufacturer directions rather than porosity alone.',
    difficulty: 'easy',
    competency_id: 'CH17-C01',
    order_index: 1,
  },
  {
    id: 'qq-17-002',
    standardId: 'CH17-Q002',
    quiz_id: 'quiz-17',
    question: 'A client has fine, highlighted hair and requests a permanent wave. What is the most appropriate first action?',
    answer_a: 'Use a standard alkaline perm for faster results',
    answer_b: 'Analyze the hair, complete required testing, and verify which product system—if any—the manufacturer directions support',
    answer_c: 'Refuse every perm service on highlighted hair automatically',
    answer_d: 'Double the processing time to ensure the wave takes hold',
    correct_answer: 'b',
    explanation: 'Previously lightened hair may be more porous or fragile. The correct decision comes from hair analysis, required testing, and the selected product system’s directions—not a generic milder-formula prescription.',
    difficulty: 'medium',
    competency_id: 'CH17-C01',
    order_index: 2,
  },
  {
    id: 'qq-17-003',
    standardId: 'CH17-Q003',
    quiz_id: 'quiz-17',
    question: 'Which finding is a reason to postpone a chemical texture service and follow product safety guidance?',
    answer_a: 'Normal elasticity and medium porosity',
    answer_b: 'A service-ready scalp with no visible compromise',
    answer_c: 'Visible open, abraded, or otherwise compromised scalp tissue',
    answer_d: 'Hair with no recent chemical service history',
    correct_answer: 'c',
    explanation: 'Do not perform a chemical service over visibly open, abraded, irritated, or otherwise compromised scalp tissue. Postpone the service and refer medical concerns appropriately rather than diagnosing the condition.',
    difficulty: 'hard',
    competency_id: 'CH17-C06',
    order_index: 3,
  },
  {
    id: 'qq-17-004',
    standardId: 'CH17-Q004',
    quiz_id: 'quiz-17',
    question: 'How many characteristics of the hair and scalp are typically analyzed before a chemical texture service?',
    answer_a: 'Three',
    answer_b: 'Four',
    answer_c: 'Six',
    answer_d: 'Eight',
    correct_answer: 'c',
    explanation: 'The standard analysis covers texture, porosity, elasticity, density, scalp condition, and service history.',
    difficulty: 'easy',
    competency_id: 'CH17-C01',
    order_index: 4,
  },
  {
    id: 'qq-17-005',
    standardId: 'CH17-Q005',
    quiz_id: 'quiz-17',
    question: 'During the consultation, a client reveals they had a hydroxide relaxer six months ago. Why does this matter for future texture services?',
    answer_a: 'Hydroxide only affects the cuticle and does not influence other services',
    answer_b: 'Hydroxide-treated hair may be incompatible with thio-based perms or relaxers',
    answer_c: 'Any new chemical service is automatically safe after six months',
    answer_d: 'Hydroxide improves curl retention so perms process faster',
    correct_answer: 'b',
    explanation: 'Hydroxide and thio product families use different chemical pathways and are treated as incompatible on the same previously treated hair unless verified product-system guidance explicitly supports the planned service. A strand test does not override a known incompatibility.',
    difficulty: 'medium',
    competency_id: 'CH17-C01',
    order_index: 5,
  },

  // === CHEMISTRY (5 questions) ===
  {
    id: 'qq-17-006',
    standardId: 'CH17-Q006',
    quiz_id: 'quiz-17',
    question: 'Which bond is central to the chemistry of many chemical texture services in the cortex?',
    answer_a: 'Hydrogen bond',
    answer_b: 'Salt bond',
    answer_c: 'Disulfide bond',
    answer_d: 'Peptide bond',
    correct_answer: 'c',
    explanation: 'Disulfide bonds are strong side bonds in the cortex that influence hair shape. Thio systems reduce and later oxidize them, while hydroxide relaxers alter sulfur-containing bonds through lanthionization rather than the same break-and-rebuild cycle.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 6,
  },
  {
    id: 'qq-17-007',
    standardId: 'CH17-Q007',
    quiz_id: 'quiz-17',
    question: 'What happens during the reduction phase of a permanent wave?',
    answer_a: 'Disulfide bonds are rebuilt into their new shape',
    answer_b: 'Disulfide bonds are broken so hair can be reshaped',
    answer_c: 'The cuticle is sealed to lock in moisture',
    answer_d: 'Hair color molecules are oxidized',
    correct_answer: 'b',
    explanation: 'In a thio/permanent-wave system, reduction breaks selected disulfide bonds so the hair can be reshaped. This description should not be applied to hydroxide relaxers, which use different chemistry.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 7,
  },
  {
    id: 'qq-17-008',
    standardId: 'CH17-Q008',
    quiz_id: 'quiz-17',
    question: 'What is the purpose of neutralization in a permanent wave?',
    answer_a: 'To remove product from the hair',
    answer_b: 'To rebuild disulfide bonds in the new shape',
    answer_c: 'To soften the cuticle before wrapping',
    answer_d: 'To increase the pH of the hair',
    correct_answer: 'b',
    explanation: 'In a compatible permanent-wave system, the oxidizing neutralizer helps reform disulfide bonds in the new shape. Hydroxide relaxers require a different post-service finishing process.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 8,
  },
  {
    id: 'qq-17-009',
    standardId: 'CH17-Q009',
    quiz_id: 'quiz-17',
    question: 'Which statement best describes alkaline versus acid or acid-balanced permanent-wave systems?',
    answer_a: 'Alkaline systems generally operate at a higher pH; heat use and timing depend on the specific product directions',
    answer_b: 'Acid systems always require heat and alkaline systems never do',
    answer_c: 'Alkaline systems rebuild bonds while acid systems only break them',
    answer_d: 'Alkaline systems are always for damaged hair and acid systems only for healthy hair',
    correct_answer: 'a',
    explanation: 'Alkaline waving systems generally operate at a higher pH than acid or acid-balanced systems. Added heat, timing, and client suitability are product-specific and should follow manufacturer directions.',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 9,
  },
  {
    id: 'qq-17-010',
    standardId: 'CH17-Q010',
    quiz_id: 'quiz-17',
    question: 'An exothermic perm solution works by:',
    answer_a: 'Lowering the pH of the hair',
    answer_b: 'Generating its own heat when mixed',
    answer_c: 'Removing oil from the scalp',
    answer_d: 'Sealing the cuticle before processing',
    correct_answer: 'b',
    explanation: 'Exothermic waving systems generate heat through a product reaction after mixing. Activation, timing, and client suitability must follow the specific product directions.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 10,
  },

  // === PERMANENT WAVES (7 questions) ===
  {
    id: 'qq-17-011',
    standardId: 'CH17-Q011',
    quiz_id: 'quiz-17',
    question: 'Which rod placement generally creates the most base lift compared with half off-base and off-base placement?',
    answer_a: 'Off-base',
    answer_b: 'Half off-base',
    answer_c: 'On-base',
    answer_d: 'Spiral',
    correct_answer: 'c',
    explanation: 'On-base placement positions the rod over the base area and generally creates more base lift. Exact elevation and tension should follow the wrapping method being taught.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 11,
  },
  {
    id: 'qq-17-012',
    standardId: 'CH17-Q012',
    quiz_id: 'quiz-17',
    question: 'Which wrapping technique is best for creating a corkscrew curl pattern?',
    answer_a: 'Croquignole',
    answer_b: 'Piggyback',
    answer_c: 'Spiral',
    answer_d: 'On-base',
    correct_answer: 'c',
    explanation: 'Spiral wrapping winds hair vertically down the rod, producing a long, corkscrew-shaped curl.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 12,
  },
  {
    id: 'qq-17-013',
    standardId: 'CH17-Q013',
    quiz_id: 'quiz-17',
    question: 'What effect does using a smaller-diameter perm rod have?',
    answer_a: 'Looser wave pattern',
    answer_b: 'Tighter curl pattern',
    answer_c: 'Straighter result',
    answer_d: 'No effect on curl size',
    correct_answer: 'b',
    explanation: 'Rod diameter controls curl size. Smaller rods produce tighter curls; larger rods produce looser waves.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 13,
  },
  {
    id: 'qq-17-014',
    standardId: 'CH17-Q014',
    quiz_id: 'quiz-17',
    question: 'A client wants a perm but has very long, dense hair. Which wrap would you most likely use?',
    answer_a: 'Croquignole',
    answer_b: 'Spiral',
    answer_c: 'Piggyback',
    answer_d: 'On-base only',
    correct_answer: 'c',
    explanation: 'Piggyback wrapping uses two rods per section to manage long or dense hair and produce an even curl from scalp to ends.',
    difficulty: 'medium',
    competency_id: 'CH17-C03',
    order_index: 14,
  },
  {
    id: 'qq-17-015',
    standardId: 'CH17-Q015',
    quiz_id: 'quiz-17',
    question: 'What is the most likely result of underprocessing a permanent wave?',
    answer_a: 'Frizzy, damaged hair',
    answer_b: 'A weak or limp wave that does not hold',
    answer_c: 'Overly tight curls',
    answer_d: 'Scalp burns',
    correct_answer: 'b',
    explanation: 'Inadequate processing for the selected hair/product system can produce a weak or poorly formed result. Timing and readiness should follow the hair analysis, representative test curls, and product directions.',
    difficulty: 'medium',
    competency_id: 'CH17-C03',
    order_index: 15,
  },
  {
    id: 'qq-17-016',
    standardId: 'CH17-Q016',
    quiz_id: 'quiz-17',
    question: 'What is the most likely result of overprocessing a permanent wave?',
    answer_a: 'A firm, well-defined curl',
    answer_b: 'Hair that is frizzy, weak, or damaged',
    answer_c: 'Hair that remains completely straight',
    answer_d: 'A darker hair color',
    correct_answer: 'b',
    explanation: 'Excessive processing for the selected hair/product system can weaken the fiber and increase frizz, breakage, or an unwanted result.',
    difficulty: 'medium',
    competency_id: 'CH17-C03',
    order_index: 16,
  },
  {
    id: 'qq-17-017',
    standardId: 'CH17-Q017',
    quiz_id: 'quiz-17',
    question: 'How should representative test curls be checked before rinsing a permanent wave?',
    answer_a: 'Use one universal crown check for every product',
    answer_b: 'Check only after the maximum processing time has elapsed',
    answer_c: 'Check at the intervals and locations directed by the product instructions and service plan',
    answer_d: 'Skip test curls whenever a timer is used',
    correct_answer: 'c',
    explanation: 'Representative test curls should be evaluated according to the selected system’s timing, directions, and service plan rather than a universal fixed number of locations.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 17,
  },

  // === CHEMICAL RELAXERS (7 questions) ===
  {
    id: 'qq-17-018',
    standardId: 'CH17-Q018',
    quiz_id: 'quiz-17',
    question: 'Which relaxer type uses highly alkaline chemistry and lanthionization?',
    answer_a: 'Thio relaxer',
    answer_b: 'Hydroxide relaxer',
    answer_c: 'Acid-balanced permanent wave',
    answer_d: 'Exothermic permanent wave',
    correct_answer: 'b',
    explanation: 'Hydroxide relaxers include lye and no-lye systems and straighten through highly alkaline chemistry and lanthionization rather than the same reduction/oxidation cycle used by thio systems.',
    difficulty: 'easy',
    competency_id: 'CH17-C04',
    order_index: 18,
  },
  {
    id: 'qq-17-019',
    standardId: 'CH17-Q019',
    quiz_id: 'quiz-17',
    question: 'What is the main difference between base and no-base relaxer application?',
    answer_a: 'Base systems are always lye and no-base systems are always no-lye',
    answer_b: 'Base systems use a protective barrier as directed; no-base systems do not require the same full scalp-base step but still follow product-specific protection directions',
    answer_c: 'No-base systems are always stronger than base systems',
    answer_d: 'Base systems are only for men and no-base systems only for women',
    correct_answer: 'b',
    explanation: 'A base relaxer system uses a protective barrier according to its directions. A no-base system does not require the same full scalp-base application, but that does not mean the product should be intentionally placed on the scalp.',
    difficulty: 'medium',
    competency_id: 'CH17-C04',
    order_index: 19,
  },
  {
    id: 'qq-17-020',
    standardId: 'CH17-Q020',
    quiz_id: 'quiz-17',
    question: 'Which pre-service assessment helps indicate how readily hair may absorb a chemical product?',
    answer_a: 'Elasticity test',
    answer_b: 'Texture test',
    answer_c: 'Porosity test',
    answer_d: 'pH test',
    correct_answer: 'c',
    explanation: 'Porosity assessment helps indicate how readily the hair may accept product, but timing and suitability must still be determined from the full analysis and manufacturer directions.',
    difficulty: 'hard',
    competency_id: 'CH17-C04',
    order_index: 20,
  },
  {
    id: 'qq-17-021',
    standardId: 'CH17-Q021',
    quiz_id: 'quiz-17',
    question: 'Which pre-service assessment helps evaluate whether the hair shows weakness before chemical processing?',
    answer_a: 'Porosity assessment',
    answer_b: 'Elasticity assessment',
    answer_c: 'Texture/diameter assessment',
    answer_d: 'Density assessment',
    correct_answer: 'b',
    explanation: 'Elasticity assessment helps evaluate fiber condition and whether the hair stretches and returns appropriately. It is one part of the complete pre-service analysis.',
    difficulty: 'hard',
    competency_id: 'CH17-C04',
    order_index: 21,
  },
  {
    id: 'qq-17-022',
    standardId: 'CH17-Q022',
    quiz_id: 'quiz-17',
    question: 'Why is it unsafe to apply a thio perm over hair that was relaxed with hydroxide?',
    answer_a: 'The hair will process too slowly',
    answer_b: 'The two chemistries are incompatible and can cause severe damage',
    answer_c: 'The hydroxide will make the hair too curly',
    answer_d: 'Thio perms only work on natural gray hair',
    correct_answer: 'b',
    explanation: 'Hydroxide- and thio-treated hair are handled as chemically incompatible on the same previously treated hair unless verified product-system guidance explicitly supports the planned service. Combining incompatible chemistries can cause severe weakening or breakage.',
    difficulty: 'medium',
    competency_id: 'CH17-C04',
    order_index: 22,
  },
  {
    id: 'qq-17-023',
    standardId: 'CH17-Q023',
    quiz_id: 'quiz-17',
    question: 'A relaxer is applied and the client reports burning or pain. What is the best immediate response?',
    answer_a: 'Continue processing to finish the straightening',
    answer_b: 'Stop the service and remove the product according to the product’s safety directions',
    answer_c: 'Add more base cream and continue',
    answer_d: 'Switch to a different relaxer brand mid-service',
    correct_answer: 'b',
    explanation: 'Burning or pain requires immediate attention. Stop the service and remove the product according to the safety directions rather than diagnosing the cause or continuing exposure.',
    difficulty: 'hard',
    competency_id: 'CH17-C06',
    order_index: 23,
  },
  {
    id: 'qq-17-024',
    standardId: 'CH17-Q024',
    quiz_id: 'quiz-17',
    question: 'What is the safest rule when considering a thio permanent-wave service after a previous chemical relaxer?',
    answer_a: 'Any lye hydroxide history is automatically safe after six months',
    answer_b: 'Any no-lye hydroxide history is automatically safe after six months',
    answer_c: 'Do not assume compatibility from the chemical-family name alone; verify prior chemistry, hair condition, and product-system guidance before proceeding',
    answer_d: 'Every exothermic wave is compatible with every relaxer',
    correct_answer: 'c',
    explanation: 'A shared thio family does not by itself guarantee that a follow-up service is appropriate. Verify the exact prior service, hair condition, and manufacturer compatibility guidance. Hydroxide-treated hair remains a known incompatibility unless verified guidance explicitly supports the planned service.',
    difficulty: 'medium',
    competency_id: 'CH17-C04',
    order_index: 24,
  },

  // === CURL REFORMATION, TEXTURIZERS, BLOWOUTS (3 questions) ===
  {
    id: 'qq-17-025',
    standardId: 'CH17-Q025',
    quiz_id: 'quiz-17',
    question: 'What is the first step of a curl reformation service?',
    answer_a: 'Wrap the hair on rods',
    answer_b: 'Straighten the hair with a thio-based relaxer',
    answer_c: 'Apply neutralizer',
    answer_d: 'Perform a final rinse',
    correct_answer: 'b',
    explanation: 'Curl reformation begins by straightening the existing curl pattern with a thio-based relaxer before wrapping and neutralizing.',
    difficulty: 'medium',
    competency_id: 'CH17-C05',
    order_index: 25,
  },
  {
    id: 'qq-17-026',
    standardId: 'CH17-Q026',
    quiz_id: 'quiz-17',
    question: 'Why is curl reformation considered a higher-risk service?',
    answer_a: 'It uses only one chemical process',
    answer_b: 'It requires two chemical processes on the same hair',
    answer_c: 'It never needs strand testing',
    answer_d: 'It only works on very short hair',
    correct_answer: 'b',
    explanation: 'Curl reformation chemically restructures the hair through multiple service stages, so compatibility, fiber condition, product directions, and controlled processing are especially important.',
    difficulty: 'medium',
    competency_id: 'CH17-C05',
    order_index: 26,
  },
  {
    id: 'qq-17-027',
    standardId: 'CH17-Q027',
    quiz_id: 'quiz-17',
    question: 'What best distinguishes a texturizing goal from a full-relaxing goal?',
    answer_a: 'Texturizers are always hydroxide and full relaxers are always thio',
    answer_b: 'Texturizing aims to loosen or soften curl rather than maximize straightening',
    answer_c: 'Texturizers always require heat and relaxers never do',
    answer_d: 'Texturizers only work on fine hair',
    correct_answer: 'b',
    explanation: 'The intended outcome distinguishes the service goal. Do not define texturizing only by a mild formula or shorter processing time; use the selected product system and its directions.',
    difficulty: 'easy',
    competency_id: 'CH17-C07',
    order_index: 27,
  },

  // === SAFETY & NEUTRALIZATION (3 questions) ===
  {
    id: 'qq-17-028',
    standardId: 'CH17-Q028',
    quiz_id: 'quiz-17',
    question: 'Why is thorough rinsing important before applying neutralizer in a permanent-wave system?',
    answer_a: 'It lightens the hair color',
    answer_b: 'It removes the waving solution as directed before the compatible neutralizer is applied',
    answer_c: 'It opens the cuticle so every neutralizer works faster',
    answer_d: 'It removes the client\'s natural oils',
    correct_answer: 'b',
    explanation: 'The waving solution must be rinsed out thoroughly according to the product directions before applying the compatible oxidizing neutralizer.',
    difficulty: 'easy',
    competency_id: 'CH17-C06',
    order_index: 28,
  },
  {
    id: 'qq-17-029',
    standardId: 'CH17-Q029',
    quiz_id: 'quiz-17',
    question: 'What can happen if the neutralization step in a permanent-wave system is incomplete?',
    answer_a: 'The curl will always become tighter',
    answer_b: 'The intended result may not stabilize properly and the hair can remain weakened',
    answer_c: 'The hair will darken permanently',
    answer_d: 'The scalp will become oily',
    correct_answer: 'b',
    explanation: 'Incomplete or incorrect neutralization can compromise stabilization of the new bond arrangement and the intended result.',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 29,
  },
  {
    id: 'qq-17-030',
    standardId: 'CH17-Q030',
    quiz_id: 'quiz-17',
    question: 'Which safety practice protects the stylist during chemical texture services?',
    answer_a: 'Wearing gloves',
    answer_b: 'Using bare hands to feel product saturation',
    answer_c: 'Skipping the strand test on regular clients',
    answer_d: 'Applying relaxer directly to the scalp without base',
    correct_answer: 'a',
    explanation: 'Gloves reduce direct skin exposure to chemical products and should be used as required by product directions and professional safety procedures.',
    difficulty: 'hard',
    competency_id: 'CH17-C06',
    order_index: 30,
  },
]

// ═══════════════════════════════════════════════════════════════════════════════
// LEARNING QUESTION BANK (15 questions)
// Focus: concept mastery and practical understanding
// ═══════════════════════════════════════════════════════════════════════════════
export const chapter17LearningQuestions: QuizQuestion[] = [
  {
    id: 'lq-17-001',
    standardId: 'CH17-Q031',
    quiz_id: 'quiz-17-learning',
    question: 'In your own words, why does porosity matter more than texture for processing time?',
    answer_a: 'Texture determines curl size; porosity determines how fast the product works',
    answer_b: 'Porosity controls how quickly solution enters the hair; texture only affects strand thickness',
    answer_c: 'Texture and porosity are the same thing',
    answer_d: 'Porosity only matters for color services',
    correct_answer: 'b',
    explanation: 'Porosity controls absorption speed, which directly affects timing and risk of overprocessing. Texture affects strength and resistance but not absorption rate.',
    difficulty: 'medium',
    competency_id: 'CH17-C01',
    order_index: 1,
  },
  {
    id: 'lq-17-002',
    standardId: 'CH17-Q032',
    quiz_id: 'quiz-17-learning',
    question: 'How does the reduction → reshape → oxidation cycle explain why a perm is permanent?',
    answer_a: 'It coats the outside of the hair with a protective layer',
    answer_b: 'It physically bends the hair without chemistry',
    answer_c: 'It breaks internal bonds, shapes the hair, then rebuilds bonds in the new shape',
    answer_d: 'It only changes the cuticle layer',
    correct_answer: 'c',
    explanation: 'The internal structure of the hair is permanently changed when disulfide bonds are broken, reshaped, and rebuilt.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 2,
  },
  {
    id: 'lq-17-003',
    standardId: 'CH17-Q033',
    quiz_id: 'quiz-17-learning',
    question: 'When would you choose on-base placement instead of off-base placement?',
    answer_a: 'When the client wants maximum volume and tight curl',
    answer_b: 'When the client wants a natural, low-volume result',
    answer_c: 'When the hair is too damaged to hold tension',
    answer_d: 'When using very large rods',
    correct_answer: 'a',
    explanation: 'On-base placement uses high tension to create fullness and tight curl at the scalp. Off-base creates a softer look.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 3,
  },
  {
    id: 'lq-17-004',
    standardId: 'CH17-Q034',
    quiz_id: 'quiz-17-learning',
    question: 'Why is a spiral wrap different from a croquignole wrap?',
    answer_a: 'Spiral wraps overlap hair from ends to scalp; croquignole wraps vertically',
    answer_b: 'Croquignole wraps overlap from ends to scalp; spiral wraps vertically down the rod',
    answer_c: 'They are the same technique with different names',
    answer_d: 'Spiral wraps are only used on short hair',
    correct_answer: 'b',
    explanation: 'Croquignole wraps overlap horizontally toward the scalp, while spiral wraps wind vertically down the rod for a corkscrew curl.',
    difficulty: 'medium',
    competency_id: 'CH17-C03',
    order_index: 4,
  },
  {
    id: 'lq-17-005',
    standardId: 'CH17-Q035',
    quiz_id: 'quiz-17-learning',
    question: 'What should you do if a strand test shows poor elasticity before a relaxer?',
    answer_a: 'Proceed with a stronger relaxer',
    answer_b: 'Postpone the service and recommend conditioning treatments',
    answer_c: 'Double the processing time',
    answer_d: 'Apply relaxer only to the ends',
    correct_answer: 'b',
    explanation: 'Poor elasticity means the hair is weak. Processing it can cause breakage; conditioning and postponement are the safest choices.',
    difficulty: 'medium',
    competency_id: 'CH17-C06',
    order_index: 5,
  },
  {
    id: 'lq-17-006',
    standardId: 'CH17-Q036',
    quiz_id: 'quiz-17-learning',
    question: 'Why is it important to record every chemical texture service in the client file?',
    answer_a: 'To track progress and protect both client and stylist if a future reaction occurs',
    answer_b: 'Because the law requires a written essay for each service',
    answer_c: 'To make the file heavier',
    answer_d: 'Only salon chains need records',
    correct_answer: 'a',
    explanation: 'Records document products, strengths, timing, and results, which helps plan future services and resolve concerns.',
    difficulty: 'easy',
    competency_id: 'CH17-C01',
    order_index: 6,
  },
  {
    id: 'lq-17-007',
    standardId: 'CH17-Q037',
    quiz_id: 'quiz-17-learning',
    question: 'How do you explain a strand test to a client in simple terms?',
    answer_a: 'It is a way to guess the final color',
    answer_b: 'It is a small test on a hidden section to see how the hair reacts before the full service',
    answer_c: 'It measures the exact length of the hair',
    answer_d: 'It is only needed for haircuts',
    correct_answer: 'b',
    explanation: 'A strand test lets you observe how a small amount of hair responds to the product, reducing risk for the whole head.',
    difficulty: 'easy',
    competency_id: 'CH17-C06',
    order_index: 7,
  },
  {
    id: 'lq-17-008',
    standardId: 'CH17-Q038',
    quiz_id: 'quiz-17-learning',
    question: 'What is the relationship between rod size and the final curl size?',
    answer_a: 'Larger rods make tighter curls',
    answer_b: 'Smaller rods make tighter curls',
    answer_c: 'Rod size does not affect curl size',
    answer_d: 'Rod size only affects processing time',
    correct_answer: 'b',
    explanation: 'The hair wraps more tightly around a smaller rod, producing a smaller, tighter curl. Larger rods produce looser waves.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 8,
  },
  {
    id: 'lq-17-009',
    standardId: 'CH17-Q039',
    quiz_id: 'quiz-17-learning',
    question: 'Why is a no-base relaxer called "no-base"?',
    answer_a: 'It is applied only to the ends of the hair',
    answer_b: 'It already contains protective ingredients so a separate scalp cream is not needed',
    answer_c: 'It does not touch the scalp at all',
    answer_d: 'It is always a thio relaxer',
    correct_answer: 'b',
    explanation: 'No-base relaxers include protective ingredients in the formula, eliminating the need for a separate base cream.',
    difficulty: 'easy',
    competency_id: 'CH17-C04',
    order_index: 9,
  },
  {
    id: 'lq-17-010',
    standardId: 'CH17-Q040',
    quiz_id: 'quiz-17-learning',
    question: 'What makes a chemical blowout different from a full relaxer?',
    answer_a: 'It permanently colors the hair',
    answer_b: 'It uses heat instead of chemicals',
    answer_c: 'It loosens curl enough to make blow-drying easier but does not fully straighten',
    answer_d: 'It only works on straight hair',
    correct_answer: 'c',
    explanation: 'A chemical blowout is a mild relaxing service that reduces curl for easier styling without complete straightening.',
    difficulty: 'easy',
    competency_id: 'CH17-C07',
    order_index: 10,
  },
  {
    id: 'lq-17-011',
    standardId: 'CH17-Q041',
    quiz_id: 'quiz-17-learning',
    question: 'Why should a client avoid shampooing for 48 hours after a perm?',
    answer_a: 'Shampoo will make the hair grow faster',
    answer_b: 'The bonds need time to fully stabilize after neutralization',
    answer_c: 'Shampoo removes the stylist\'s signature scent',
    answer_d: 'The hair is already clean enough',
    correct_answer: 'b',
    explanation: 'Waiting allows disulfide bonds to fully stabilize in their new shape, helping the curl last and resist relaxing.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 11,
  },
  {
    id: 'lq-17-012',
    standardId: 'CH17-Q042',
    quiz_id: 'quiz-17-learning',
    question: 'What does it mean if hair "does not take" a perm?',
    answer_a: 'The hair is too healthy',
    answer_b: 'The solution is too strong',
    answer_c: 'The disulfide bonds were not sufficiently broken and reshaped',
    answer_d: 'The rods were too small',
    correct_answer: 'c',
    explanation: 'When a perm does not take, the reduction or processing was insufficient to reshape and lock the bonds into curls.',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 12,
  },
  {
    id: 'lq-17-013',
    standardId: 'CH17-Q043',
    quiz_id: 'quiz-17-learning',
    question: 'How can you tell the difference between underprocessed and overprocessed permed hair?',
    answer_a: 'Underprocessed is limp; overprocessed is frizzy or damaged',
    answer_b: 'Underprocessed is frizzy; overprocessed is limp',
    answer_c: 'Both look exactly the same',
    answer_d: 'Underprocessed hair is darker',
    correct_answer: 'a',
    explanation: 'Underprocessing leaves a weak wave; overprocessing breaks too many bonds and causes frizz, weakness, and damage.',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 13,
  },
  {
    id: 'lq-17-014',
    standardId: 'CH17-Q044',
    quiz_id: 'quiz-17-learning',
    question: 'Why is density important when sectioning for a relaxer?',
    answer_a: 'Dense hair needs smaller sections for full saturation',
    answer_b: 'Thin hair needs smaller sections to look thicker',
    answer_c: 'Density does not affect sectioning',
    answer_d: 'Dense hair should never be relaxed',
    correct_answer: 'a',
    explanation: 'Thicker, denser hair requires smaller subsections so the relaxer reaches every strand evenly and avoids patchy results.',
    difficulty: 'easy',
    competency_id: 'CH17-C04',
    order_index: 14,
  },
  {
    id: 'lq-17-015',
    standardId: 'CH17-Q045',
    quiz_id: 'quiz-17-learning',
    question: 'What is the best way to protect a client\'s scalp during a base relaxer service?',
    answer_a: 'Apply a protective base cream to the scalp before the relaxer',
    answer_b: 'Rinse the scalp with hot water first',
    answer_c: 'Apply relaxer directly without protection',
    answer_d: 'Use a higher-pH relaxer',
    correct_answer: 'a',
    explanation: 'A base cream creates a barrier between the scalp and the high-pH relaxer, reducing irritation and burn risk.',
    difficulty: 'easy',
    competency_id: 'CH17-C06',
    order_index: 15,
  },
  {
    id: 'lq-17-016',
    standardId: 'CH17-Q046',
    quiz_id: 'quiz-17-learning',
    question: 'How are permanent waves, relaxers, and curl reformation chemically similar — and how do they differ?',
    answer_a: 'They all use hydroxide to break bonds; only the wrapping technique differs',
    answer_b: 'They all reduce, reshape, and oxidize disulfide bonds, but they use different products and tools to create different outcomes',
    answer_c: 'They only change the cuticle layer and do not affect disulfide bonds',
    answer_d: 'Perms add curl, relaxers remove curl, and reformation does nothing to bonds',
    correct_answer: 'b',
    explanation: 'All three services follow the same three-stage chemistry on disulfide bonds. The differences are the desired shape (curl, straight, or reset curl), the tools used (rods vs. comb vs. both), and the product families (alkaline/acid vs. hydroxide/thio).',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 16,
  },
]
