// Chapter 10: Properties and Disorders of the Hair and Scalp — PREMIUM MCQ QUIZ
// 70 questions generated STRICTLY from Chapter 10 premium flashcards
// Randomized question selection and answer order per attempt
// Chapter 10 assessment bank

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 10: FULL QUESTION BANK (75 questions)
// Generated from chapter-10-premium-flashcards.ts
// Deterministically balanced answer positions; source and distractor hardening audited in C10-4
// ───────────────────────────────────────────────
export const chapter10PremiumQuizQuestions: QuizQuestion[] = [
  // HAIR LOSS & ALOPECIA (10 questions)
  {
    id: 'qq-10-001',
    quiz_id: 'quiz-10',
    question: 'What is the definition of alopecia?',
    answer_a: 'Abnormal hair loss that can occur in patches or total body hair loss',
    answer_b: 'A fungal infection of the scalp causing dandruff',
    answer_c: 'Normal daily shedding of 75-100 hairs',
    answer_d: 'A bacterial infection of hair follicles causing boils',
    correct_answer: 'a',
    explanation: 'Alopecia (al-oh-PEE-shah) is abnormal hair loss. It can occur in many forms, from small patches to total body hair loss, and has many causes including genetics, autoimmune disorders, and medical conditions.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-10-002',
    quiz_id: 'quiz-10',
    question: 'Which factors does Chapter 10 associate with androgenic alopecia?',
    answer_a: 'An autoimmune attack on follicles',
    answer_b: 'Heredity, age, and hormonal factors',
    answer_c: 'A fungal scalp infection',
    answer_d: 'Normal telogen shedding',
    correct_answer: 'b',
    explanation: 'Chapter 10 associates androgenic alopecia with heredity, age, and hormonal factors and illustrates follicle miniaturization.',
    difficulty: 'medium',
    order_index: 2,
  },
  {
    id: 'qq-10-003',
    quiz_id: 'quiz-10',
    question: 'Which description best matches alopecia areata?',
    answer_a: 'Pattern hair loss associated with heredity and hormones',
    answer_b: 'Normal shedding during telogen',
    answer_c: 'Autoimmune hair loss with sudden bald patches that may progress to totalis',
    answer_d: 'Complete body hair loss',
    correct_answer: 'c',
    explanation: 'Chapter 10 describes alopecia areata as autoimmune hair loss with sudden bald patches that can progress to alopecia totalis.',
    difficulty: 'medium',
    order_index: 3,
  },
  {
    id: 'qq-10-004',
    quiz_id: 'quiz-10',
    question: 'A barber notices a painful boil associated with a hair follicle. Which Chapter 10 condition best matches this finding?',
    answer_a: 'Pityriasis capitis simplex',
    answer_b: 'Tinea favosa',
    answer_c: 'Pseudofolliculitis barbae',
    answer_d: 'Furuncle',
    correct_answer: 'd',
    explanation: 'Chapter 10 defines a furuncle, or boil, as an acute deep-seated bacterial infection associated with a hair follicle.',
    difficulty: 'hard',
    order_index: 4,
  },
  {
    id: 'qq-10-005',
    quiz_id: 'quiz-10',
    question: 'Which statement correctly distinguishes a furuncle from a carbuncle?',
    answer_a: 'A furuncle is a boil; a carbuncle involves multiple connected boils and is larger',
    answer_b: 'A furuncle is fungal; a carbuncle is parasitic',
    answer_c: 'A furuncle is a growth pattern; a carbuncle is a pigment disorder',
    answer_d: 'A furuncle is normal shedding; a carbuncle is alopecia',
    correct_answer: 'a',
    explanation: 'Chapter 10 describes a furuncle as a boil and a carbuncle as multiple connected boils forming a larger bacterial infection. The source record specifically directs physician referral for a carbuncle.',
    difficulty: 'hard',
    order_index: 5,
  },
  {
    id: 'qq-10-006',
    quiz_id: 'quiz-10',
    question: 'What is alopecia totalis?',
    answer_a: 'Hair loss limited to the beard area',
    answer_b: 'Complete scalp hair loss',
    answer_c: 'Complete body hair loss',
    answer_d: 'Normal daily shedding',
    correct_answer: 'b',
    explanation: 'Chapter 10 defines alopecia totalis as complete scalp hair loss. Alopecia universalis is complete body hair loss.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-10-007',
    quiz_id: 'quiz-10',
    question: 'A client has complete loss of scalp hair but still has body hair. Which Chapter 10 term best matches this pattern?',
    answer_a: 'Androgenic alopecia',
    answer_b: 'Alopecia universalis',
    answer_c: 'Alopecia totalis',
    answer_d: 'Alopecia areata',
    correct_answer: 'c',
    explanation: 'Alopecia totalis means complete scalp hair loss. Alopecia universalis means complete body hair loss.',
    difficulty: 'medium',
    order_index: 7,
  },
  {
    id: 'qq-10-008',
    quiz_id: 'quiz-10',
    question: 'A client develops sudden round bald patches that may progress to complete scalp hair loss. Which condition best matches the source record?',
    answer_a: 'Normal telogen shedding',
    answer_b: 'Androgenic alopecia',
    answer_c: 'Alopecia universalis',
    answer_d: 'Alopecia areata',
    correct_answer: 'd',
    explanation: 'Chapter 10 describes alopecia areata as autoimmune hair loss with sudden bald patches that can progress to alopecia totalis.',
    difficulty: 'hard',
    order_index: 8,
  },
  {
    id: 'qq-10-009',
    quiz_id: 'quiz-10',
    question: 'How many hairs does Chapter 10 describe as normal daily shedding?',
    answer_a: '75 to 100 hairs',
    answer_b: '10 to 25 hairs',
    answer_c: '200 to 300 hairs',
    answer_d: '500 to 1,000 hairs',
    correct_answer: 'a',
    explanation: 'The Chapter 10 source record gives normal shedding as about 75 to 100 hairs per day.',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-10-010',
    quiz_id: 'quiz-10',
    question: 'A client is worried about losing about 80 hairs in one day. Which Chapter 10 fact is most relevant?',
    answer_a: 'Any daily shedding is abnormal alopecia',
    answer_b: 'Normal shedding is about 75–100 hairs per day',
    answer_c: 'Normal shedding is less than 10 hairs per day',
    answer_d: 'Normal shedding occurs only during anagen',
    correct_answer: 'b',
    explanation: 'The Chapter 10 source record gives normal shedding as about 75–100 hairs per day. Alopecia refers to abnormal hair loss, not ordinary daily shedding.',
    difficulty: 'medium',
    order_index: 10,
  },

  // HAIR ANALYSIS — TEXTURE, POROSITY, ELASTICITY, DENSITY (10 questions)
  {
    id: 'qq-10-011',
    quiz_id: 'quiz-10',
    question: 'What is hair elasticity and why does it matter for chemical services?',
    answer_a: 'The natural color of hair; light hair processes faster',
    answer_b: 'The thickness of individual hair strands; thick hair cannot be colored',
    answer_c: 'The ability of hair to stretch and return to original length; low elasticity means no chemical services',
    answer_d: 'The oiliness of the scalp; oily hair resists perms',
    correct_answer: 'c',
    explanation: 'Hair elasticity is the ability of hair to stretch and return to its original length. Normal elasticity means hair holds curls and chemical services well. Low elasticity means hair is brittle and should NOT receive chemical services.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-10-012',
    quiz_id: 'quiz-10',
    question: 'A barber is comparing coarse, medium, and fine hair before a chemical service. Which statement is supported by Chapter 10?',
    answer_a: 'Texture and density mean the same thing',
    answer_b: 'Fine hair has the largest diameter and is hardest to process',
    answer_c: 'Medium hair is always the most fragile texture',
    answer_d: 'Coarse hair has the largest diameter and generally requires more time or product',
    correct_answer: 'd',
    explanation: 'Chapter 10 describes coarse hair as having the largest diameter and generally requiring more time or product; fine hair has the smallest diameter and is more fragile.',
    difficulty: 'hard',
    order_index: 12,
  },
  {
    id: 'qq-10-013',
    quiz_id: 'quiz-10',
    question: 'How do you test for hair texture?',
    answer_a: 'Feel a single strand of dry hair between your fingers and roll it',
    answer_b: 'Wet the hair and stretch it to see if it breaks',
    answer_c: 'Look at the hair under a microscope for scale patterns',
    answer_d: 'Apply a chemical solution and time the reaction',
    correct_answer: 'a',
    explanation: 'To test hair texture, feel a single strand of DRY hair between your fingers. Hold it securely while rolling it between thumb and forefinger. With practice, you can feel the difference between coarse, medium, and fine textures.',
    difficulty: 'easy',
    order_index: 13,
  },
  {
    id: 'qq-10-014',
    quiz_id: 'quiz-10',
    question: 'What is hair density and what is the average number of hairs on the head?',
    answer_a: 'Thickness of each individual strand; about 50,000 total',
    answer_b: 'Number of strands per square inch; about 100,000 total',
    answer_c: 'Length of hair from root to tip; varies by individual',
    answer_d: 'Color intensity of hair pigment; about 75,000 total',
    correct_answer: 'b',
    explanation: 'Hair density is the number of individual hair strands per square inch of scalp. The average head has approximately 2,200 strands per square inch, or about 100,000 individual strands total.',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-10-015',
    quiz_id: 'quiz-10',
    question: 'Which hair color has the highest density and which has the lowest?',
    answer_a: 'Brown has the highest (140,000); black has the lowest (80,000)',
    answer_b: 'Black has the highest (140,000); blond has the lowest (80,000)',
    answer_c: 'Blond has the highest (140,000); red has the lowest (80,000)',
    answer_d: 'Red has the highest (140,000); brown has the lowest (80,000)',
    correct_answer: 'c',
    explanation: 'Blond hair has the highest density (about 140,000 hairs). Red hair has the lowest density (about 80,000 hairs). Brown has about 110,000 and black has about 108,000.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-10-016',
    quiz_id: 'quiz-10',
    question: 'What is hair porosity and what determines it?',
    answer_a: 'The length of the hair growth cycle; determined by age',
    answer_b: 'The thickness of the hair strand; determined by genetics',
    answer_c: 'The natural color of hair; determined by melanin ratio',
    answer_d: 'The ability of hair to absorb moisture; directly related to cuticle condition',
    correct_answer: 'd',
    explanation: 'Hair porosity is the ability of the hair to absorb moisture. It is directly related to the condition of the cuticle layer. A compact cuticle = resistant; a raised/open cuticle = absorbs moisture easily.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-10-017',
    quiz_id: 'quiz-10',
    question: 'Which set correctly orders the three porosity levels from most resistant to most absorbent?',
    answer_a: 'Low/resistant → normal → high/overly porous',
    answer_b: 'Fine → medium → coarse',
    answer_c: 'High density → medium density → low density',
    answer_d: 'Anagen → catagen → telogen',
    correct_answer: 'a',
    explanation: 'Chapter 10 describes resistant or low porosity as compact and moisture-resistant, normal porosity as average absorption, and high or overly porous hair as absorbing moisture too quickly.',
    difficulty: 'hard',
    order_index: 17,
  },
  {
    id: 'qq-10-018',
    quiz_id: 'quiz-10',
    question: 'Why is overly porous hair problematic for chemical services even though it absorbs quickly?',
    answer_a: 'It is too strong and resists chemical breakdown',
    answer_b: 'It cannot retain pigments or hold favorable reactions to chemical services',
    answer_c: 'It has too much melanin and blocks chemical penetration',
    answer_d: 'It is too short to wrap around perm rods',
    correct_answer: 'b',
    explanation: 'Overly porous hair has damaged, open cuticle scales. Although it absorbs liquids quickly, it cannot retain haircolor pigments or hold a favorable reaction to chemical texture services. It requires reconditioning first.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-10-019',
    quiz_id: 'quiz-10',
    question: 'During an elasticity test, wet hair breaks easily instead of stretching and returning. What does this indicate?',
    answer_a: 'Low density',
    answer_b: 'Normal elasticity',
    answer_c: 'Low or poor elasticity',
    answer_d: 'Resistant porosity',
    correct_answer: 'c',
    explanation: 'Low or poor elasticity means the hair is brittle and breaks easily rather than stretching and returning normally.',
    difficulty: 'hard',
    order_index: 19,
  },
  {
    id: 'qq-10-020',
    quiz_id: 'quiz-10',
    question: 'Is hair density the same as hair texture?',
    answer_a: 'No — density refers to color, not amount of hair',
    answer_b: 'Yes — they are interchangeable terms',
    answer_c: 'Yes — fine hair always has low density',
    answer_d: 'No — two people can have the same texture but different densities',
    correct_answer: 'd',
    explanation: 'Hair density and texture are different. Two people can have the same texture (e.g., fine hair) but completely different densities. One may have thick, fine hair while another has thin, fine hair.',
    difficulty: 'easy',
    order_index: 20,
  },

  // HAIR STRUCTURE & CHEMICAL BONDS (10 questions)
  {
    id: 'qq-10-021',
    quiz_id: 'quiz-10',
    question: 'What are the three main layers of the hair shaft from outermost to innermost?',
    answer_a: 'Cuticle, cortex, medulla',
    answer_b: 'Cortex, cuticle, medulla',
    answer_c: 'Medulla, cortex, cuticle',
    answer_d: 'Cuticle, medulla, cortex',
    correct_answer: 'a',
    explanation: 'The three layers are: CUTICLE (outermost — overlapping transparent scales), CORTEX (middle — provides strength, elasticity, and color), and MEDULLA (innermost — may be absent in fine/blond hair).',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-10-022',
    quiz_id: 'quiz-10',
    question: "A chemical service must reach the hair layer responsible for strength, elasticity, natural color, and most chemical change. Which layer is it?",
    answer_a: 'The outermost protective layer controlling shine',
    answer_b: 'The middle layer providing strength, elasticity, and color; chemical changes occur here',
    answer_c: 'The innermost air-filled core providing insulation',
    answer_d: 'The oil-producing gland attached to the follicle',
    correct_answer: 'b',
    explanation: 'The cortex is the middle layer, composed of fibrous protein core. It contains melanin pigment and provides strength, elasticity, and natural color. About 90% of hair weight comes from the cortex. Chemical service changes occur here.',
    difficulty: 'hard',
    order_index: 22,
  },
  {
    id: 'qq-10-023',
    quiz_id: 'quiz-10',
    question: 'What is keratinization?',
    answer_a: 'The natural shedding of 75-100 hairs per day',
    answer_b: 'The chemical process of breaking disulfide bonds during a perm',
    answer_c: 'The process where cells mature, fill with keratin, and die before emerging from the scalp',
    answer_d: 'The production of melanin pigment in the hair bulb',
    correct_answer: 'c',
    explanation: 'Keratinization is the process through which newly formed cells mature in the hair follicle. As cells mature, they fill with fibrous protein (keratin), move upward, lose their nuclei, and die. The hair shaft emerges as a completely keratinized, non-living structure.',
    difficulty: 'medium',
    order_index: 23,
  },
  {
    id: 'qq-10-024',
    quiz_id: 'quiz-10',
    question: 'A client\'s hair changes shape when wet or heated and reforms as it dries. Which side bond best explains this temporary change?',
    answer_a: 'Melanin bond',
    answer_b: 'Disulfide bond',
    answer_c: 'Peptide bond',
    answer_d: 'Hydrogen bond',
    correct_answer: 'd',
    explanation: 'Hydrogen bonds are weak physical side bonds that are broken by water or heat and re-form as the hair dries.',
    difficulty: 'hard',
    order_index: 24,
  },
  {
    id: 'qq-10-025',
    quiz_id: 'quiz-10',
    question: 'A strong pH change affects a weak physical side bond in the cortex. Which bond is involved?',
    answer_a: 'Salt bond',
    answer_b: 'Disulfide bond',
    answer_c: 'Peptide bond',
    answer_d: 'Melanin bond',
    correct_answer: 'a',
    explanation: 'Chapter 10 describes salt bonds as weak physical side bonds affected by changes in pH.',
    difficulty: 'hard',
    order_index: 25,
  },
  {
    id: 'qq-10-026',
    quiz_id: 'quiz-10',
    question: 'Which statement best distinguishes a disulfide bond from hydrogen and salt bonds?',
    answer_a: 'It is a weak physical bond broken by water or heat',
    answer_b: 'It is a strong chemical side bond broken by permanent waves and thio relaxers',
    answer_c: 'It is a weak physical bond affected mainly by pH changes',
    answer_d: 'It joins amino acids end-to-end into a polypeptide chain',
    correct_answer: 'b',
    explanation: 'Chapter 10 identifies disulfide bonds as strong chemical side bonds. Permanent waves and thio relaxers can break them.',
    difficulty: 'hard',
    order_index: 26,
  },
  {
    id: 'qq-10-027',
    quiz_id: 'quiz-10',
    question: 'During a permanent wave, which bond is broken and then re-formed by the neutralizer?',
    answer_a: 'Salt bond',
    answer_b: 'Hydrogen bond',
    answer_c: 'Disulfide bond',
    answer_d: 'Peptide bond',
    correct_answer: 'c',
    explanation: 'The Chapter 10 source record states that permanent waving breaks disulfide bonds and the neutralizer re-forms them.',
    difficulty: 'hard',
    order_index: 27,
  },
  {
    id: 'qq-10-028',
    quiz_id: 'quiz-10',
    question: 'What is the difference between side bonds and peptide (end) bonds?',
    answer_a: 'Side bonds determine color; peptide bonds determine texture',
    answer_b: 'Side bonds are stronger than peptide bonds',
    answer_c: 'Peptide bonds are temporary; side bonds are permanent',
    answer_d: 'Side bonds cross-link chains and can be re-formed; peptide bonds cannot be re-formed once broken',
    correct_answer: 'd',
    explanation: 'Side bonds (hydrogen, salt, disulfide) cross-link polypeptide chains and can be temporarily or chemically broken and re-formed. Peptide bonds join amino acids together. Once broken by chemical depilatories, they cannot be re-formed — the hair dissolves.',
    difficulty: 'medium',
    order_index: 28,
  },
  {
    id: 'qq-10-029',
    quiz_id: 'quiz-10',
    question: 'What are the COHNS elements and what percentage of each is in normal hair?',
    answer_a: 'Carbon 51%, Oxygen 21%, Hydrogen 6%, Nitrogen 17%, Sulfur 5%',
    answer_b: 'Carbon 21%, Oxygen 51%, Hydrogen 17%, Nitrogen 6%, Sulfur 5%',
    answer_c: 'Carbon 17%, Oxygen 5%, Hydrogen 51%, Nitrogen 21%, Sulfur 6%',
    answer_d: 'Carbon 6%, Oxygen 17%, Hydrogen 51%, Nitrogen 5%, Sulfur 21%',
    correct_answer: 'a',
    explanation: 'COHNS elements are Carbon (51%), Oxygen (21%), Hydrogen (6%), Nitrogen (17%), and Sulfur (5%). These essential elements are found in hair, skin, and nails.',
    difficulty: 'medium',
    order_index: 29,
  },
  {
    id: 'qq-10-030',
    quiz_id: 'quiz-10',
    question: 'What is the medulla and in which hair types may it be absent?',
    answer_a: 'The middle layer containing melanin pigment',
    answer_b: 'The innermost layer that may be absent in very fine and naturally blond hair',
    answer_c: 'The outermost protective layer of overlapping scales',
    answer_d: 'The oil-producing gland attached to each follicle',
    correct_answer: 'b',
    explanation: 'The medulla is the innermost layer of the hair, composed of round cells. It may be absent in very fine and naturally blond hair. Mature male beard hair typically does contain a medulla.',
    difficulty: 'easy',
    order_index: 30,
  },

  // SCALP DISORDERS & INFECTIONS (10 questions)
  {
    id: 'qq-10-031',
    quiz_id: 'quiz-10',
    question: 'What is tinea barbae and what causes it?',
    answer_a: 'An autoimmune disorder causing round bald patches in the beard',
    answer_b: 'A bacterial infection causing pustules in the beard area',
    answer_c: 'A superficial fungal infection over the bearded area caused by dermatophytes',
    answer_d: 'A viral infection causing blisters on the face and neck',
    correct_answer: 'c',
    explanation: 'Tinea barbae is a superficial fungal infection caused by dermatophytes occurring chiefly over the bearded area. It begins as small, round, scaly, inflamed patches. It is highly contagious and requires medical treatment.',
    difficulty: 'medium',
    order_index: 31,
  },
  {
    id: 'qq-10-032',
    quiz_id: 'quiz-10',
    question: 'A client has dry sulfur-yellow, honeycomb-like scalp crusts with a musty odor. Which tinea condition best matches Chapter 10?',
    answer_a: 'Pityriasis capitis simplex',
    answer_b: 'Tinea barbae',
    answer_c: 'Tinea capitis',
    answer_d: 'Tinea favosa',
    correct_answer: 'd',
    explanation: 'Chapter 10 describes tinea favosa as honeycomb ringworm with dry sulfur-yellow crusts and a musty odor.',
    difficulty: 'hard',
    order_index: 32,
  },
  {
    id: 'qq-10-033',
    quiz_id: 'quiz-10',
    question: 'A client has severe scalp itching and nits attached to hair strands. Which condition best matches the Chapter 10 source record?',
    answer_a: 'Pediculosis capitis',
    answer_b: 'Tinea favosa',
    answer_c: 'Pseudofolliculitis barbae',
    answer_d: 'Pityriasis capitis simplex',
    correct_answer: 'a',
    explanation: 'Pediculosis capitis is head-lice infestation. Chapter 10 notes severe itching and nits attached to hair strands.',
    difficulty: 'hard',
    order_index: 33,
  },
  {
    id: 'qq-10-034',
    quiz_id: 'quiz-10',
    question: 'During scalp analysis, a barber sees live head lice before the service begins. What should happen next?',
    answer_a: 'Do not begin the service; follow cleaning, disinfection, and referral guidance',
    answer_b: 'Continue the haircut but skip chemical products',
    answer_c: 'Cover the infestation and continue with disposable tools',
    answer_d: 'Perform the service after brushing out visible nits',
    correct_answer: 'b',
    explanation: 'Chapter 10 states that a service should not begin when parasites are present and that proper cleaning and disinfection procedures are required.',
    difficulty: 'hard',
    order_index: 34,
  },
  {
    id: 'qq-10-035',
    quiz_id: 'quiz-10',
    question: 'A client has intense itching and a suspected mite infestation. Which condition best matches Chapter 10?',
    answer_a: 'Canities',
    answer_b: 'Pityriasis',
    answer_c: 'Scabies',
    answer_d: 'Trichoptilosis',
    correct_answer: 'c',
    explanation: 'Scabies is a contagious parasitic condition caused by mites that burrow under the skin and produce intense itching.',
    difficulty: 'hard',
    order_index: 35,
  },
  {
    id: 'qq-10-036',
    quiz_id: 'quiz-10',
    question: 'A beard-area condition involves inflamed hair follicles and may be associated with infection. Which Chapter 10 term best fits?',
    answer_a: 'Canities',
    answer_b: 'Pseudofolliculitis barbae',
    answer_c: 'Tinea favosa',
    answer_d: 'Folliculitis barbae',
    correct_answer: 'd',
    explanation: 'Chapter 10 includes folliculitis barbae among follicular conditions affecting the beard area. Pseudofolliculitis barbae is specifically associated with ingrown hairs.',
    difficulty: 'hard',
    order_index: 36,
  },
  {
    id: 'qq-10-037',
    quiz_id: 'quiz-10',
    question: 'What is pseudofolliculitis barbae (razor bumps) and what causes it?',
    answer_a: 'A chronic inflammatory condition caused by ingrown hairs from improper shaving',
    answer_b: 'A bacterial infection requiring oral antibiotics',
    answer_c: 'A fungal infection treated with antifungal creams',
    answer_d: 'An autoimmune disorder affecting beard hair follicles',
    correct_answer: 'a',
    explanation: 'Pseudofolliculitis barbae (razor bumps) is a chronic inflammatory condition caused by ingrown hairs. It occurs when hair is broken below the skin surface and grows into the side of the follicle, causing irritation and swelling.',
    difficulty: 'medium',
    order_index: 37,
  },
  {
    id: 'qq-10-038',
    quiz_id: 'quiz-10',
    question: 'Which Chapter 10 statement about dandruff is supported by the source record?',
    answer_a: 'Pityriasis is excessive flaking caused only by poor hygiene',
    answer_b: 'Pityriasis is excessive flaking; Malassezia overgrowth is associated with dandruff',
    answer_c: 'Pityriasis is a bacterial infection centered in the follicle',
    answer_d: 'Pityriasis is a parasitic infestation with attached nits',
    correct_answer: 'b',
    explanation: 'Chapter 10 identifies pityriasis as excessive shedding of flaky scalp skin and describes Malassezia as a naturally occurring fungus associated with dandruff when it overgrows.',
    difficulty: 'hard',
    order_index: 38,
  },
  {
    id: 'qq-10-039',
    quiz_id: 'quiz-10',
    question: 'What is the difference between folliculitis barbae and pseudofolliculitis barbae?',
    answer_a: 'Folliculitis is fungal; pseudofolliculitis is bacterial',
    answer_b: 'Folliculitis affects the scalp; pseudofolliculitis affects the beard',
    answer_c: 'Folliculitis is caused by infection; pseudofolliculitis is caused by mechanical shaving issues',
    answer_d: 'Folliculitis is contagious; pseudofolliculitis is not',
    correct_answer: 'c',
    explanation: 'Folliculitis barbae is caused by bacterial or viral infection, irritation, or ingrown hairs. Pseudofolliculitis barbae is triggered by mechanical causes: improper shaving, friction, blockages, dull blades, or shaving against the grain.',
    difficulty: 'medium',
    order_index: 39,
  },
  {
    id: 'qq-10-040',
    quiz_id: 'quiz-10',
    question: 'A barber suspects tinea during scalp analysis. Which response best matches Chapter 10?',
    answer_a: 'Do not provide the affected service and refer the client to a physician',
    answer_b: 'Apply an antifungal product in the shop',
    answer_c: 'Shave the affected area and disinfect afterward',
    answer_d: 'Continue if the client has no pain',
    correct_answer: 'd',
    explanation: 'Chapter 10 describes tinea as contagious and states that tinea conditions require physician referral.',
    difficulty: 'hard',
    order_index: 40,
  },

  // HAIR DISORDERS (8 questions)
  {
    id: 'qq-10-041',
    quiz_id: 'quiz-10',
    question: 'A client has splitting at the ends of the hair shaft. Which Chapter 10 disorder best matches this finding?',
    answer_a: 'Trichoptilosis',
    answer_b: 'Monilethrix',
    answer_c: 'Ringed hair',
    answer_d: 'Hypertrichosis',
    correct_answer: 'a',
    explanation: 'Chapter 10 identifies trichoptilosis as split ends, a hair-shaft disorder.',
    difficulty: 'medium',
    order_index: 41,
  },
  {
    id: 'qq-10-042',
    quiz_id: 'quiz-10',
    question: 'What is trichorrhexis nodosa?',
    answer_a: 'Split ends caused by overprocessing',
    answer_b: 'Knotted hair characterized by brittleness and nodular swellings along the shaft',
    answer_c: 'Beaded hair that breaks easily between nodes',
    answer_d: 'A fungal infection causing hair breakage',
    correct_answer: 'b',
    explanation: 'Trichorrhexis nodosa is the technical term for knotted hair. It is characterized by brittleness and nodular swellings along the hair shaft.',
    difficulty: 'medium',
    order_index: 42,
  },
  {
    id: 'qq-10-043',
    quiz_id: 'quiz-10',
    question: 'What is monilethrix?',
    answer_a: 'Brittle hair that splits at any point along the length',
    answer_b: 'Split ends that can only be removed by cutting',
    answer_c: 'Beaded hair that breaks easily between the beads or nodes',
    answer_d: 'Knotted hair with nodular swellings along the shaft',
    correct_answer: 'c',
    explanation: 'Monilethrix is the technical term for beaded hair. The hair shaft has regular nodes (beads) and internodes. The hair breaks easily BETWEEN the beads or nodes. Treatment includes hair and scalp conditioning.',
    difficulty: 'medium',
    order_index: 43,
  },
  {
    id: 'qq-10-044',
    quiz_id: 'quiz-10',
    question: 'A hair strand shows a beaded appearance and breaks easily. Which hair-shaft disorder best matches Chapter 10?',
    answer_a: 'Canities',
    answer_b: 'Trichoptilosis',
    answer_c: 'Ringed hair',
    answer_d: 'Monilethrix',
    correct_answer: 'd',
    explanation: 'Chapter 10 describes monilethrix as beaded hair that breaks easily.',
    difficulty: 'hard',
    order_index: 44,
  },
  {
    id: 'qq-10-045',
    quiz_id: 'quiz-10',
    question: 'What is canities?',
    answer_a: 'The technical term for gray hair',
    answer_b: 'A fungal infection causing white patches on the scalp',
    answer_c: 'A bacterial infection causing hair loss',
    answer_d: 'The medical term for split ends',
    correct_answer: 'a',
    explanation: 'Canities is the technical term for gray hair. There are two types: congenital canities (exists at or before birth, associated with albinism) and acquired canities (develops with age due to genetics).',
    difficulty: 'easy',
    order_index: 45,
  },
  {
    id: 'qq-10-046',
    quiz_id: 'quiz-10',
    question: 'What is hypertrichosis?',
    answer_a: 'Excessive production of dandruff on the scalp',
    answer_b: 'Abnormal growth of terminal hair on areas normally covered with vellus hair',
    answer_c: 'A fungal infection causing hair to turn white',
    answer_d: 'The technical term for male pattern baldness',
    correct_answer: 'b',
    explanation: 'Hypertrichosis (also called hirsuties) is a condition of abnormal growth of hair characterized by growth of terminal hair on areas of the body normally covered with vellus hair.',
    difficulty: 'medium',
    order_index: 46,
  },
  {
    id: 'qq-10-047',
    quiz_id: 'quiz-10',
    question: 'What is ringed hair?',
    answer_a: 'Hair with split ends that look like rings',
    answer_b: 'Hair that grows in a circular pattern at the crown',
    answer_c: 'Alternating bands of gray and pigmented hair throughout the strand',
    answer_d: 'Hair that has been permanently waved in a ringlet pattern',
    correct_answer: 'c',
    explanation: 'Ringed hair is a variation of canities characterized by alternating bands of gray and pigmented hair throughout the length of the hair strand.',
    difficulty: 'easy',
    order_index: 47,
  },
  {
    id: 'qq-10-048',
    quiz_id: 'quiz-10',
    question: 'Is gray hair structurally different from pigmented hair?',
    answer_a: 'Yes — gray hair lacks a medulla',
    answer_b: 'Yes — gray hair is coarser and more resistant',
    answer_c: 'Yes — gray hair has a thicker cuticle layer',
    answer_d: 'No — other than lacking pigment, gray hair is exactly the same',
    correct_answer: 'd',
    explanation: 'Other than the lack of pigment, gray hair is exactly the same as pigmented hair. Gray hair may be resistant, but pigmented hair on the same person\'s head is just as resistant. Gray hair is simply more noticeable.',
    difficulty: 'easy',
    order_index: 48,
  },

  // HAIR TYPES & GROWTH CYCLES (7 questions)
  {
    id: 'qq-10-049',
    quiz_id: 'quiz-10',
    question: 'Which phase of the hair-growth cycle is the active growth phase lasting about 2–10 years?',
    answer_a: 'Anagen',
    answer_b: 'Catagen',
    answer_c: 'Telogen',
    answer_d: 'Pityriasis',
    correct_answer: 'a',
    explanation: 'Chapter 10 identifies anagen as the active growth phase and gives a duration of about 2–10 years.',
    difficulty: 'medium',
    order_index: 49,
  },
  {
    id: 'qq-10-050',
    quiz_id: 'quiz-10',
    question: 'Which phase follows anagen as the follicle shrinks and active growth stops?',
    answer_a: 'Telogen',
    answer_b: 'Catagen',
    answer_c: 'Anagen',
    answer_d: 'Canities',
    correct_answer: 'b',
    explanation: 'Catagen is the transition phase in which the follicle shrinks and active growth stops before telogen.',
    difficulty: 'medium',
    order_index: 50,
  },
  {
    id: 'qq-10-051',
    quiz_id: 'quiz-10',
    question: 'What is the average rate of hair growth on the scalp?',
    answer_a: 'About 1/4 inch per year',
    answer_b: 'About 1 inch per week',
    answer_c: 'About 1/2 inch per month',
    answer_d: 'About 2 inches per month',
    correct_answer: 'c',
    explanation: 'The Chapter 10 source record gives average scalp-hair growth as about 1/2 (0.5) inch per month.',
    difficulty: 'easy',
    order_index: 51,
  },
  {
    id: 'qq-10-052',
    quiz_id: 'quiz-10',
    question: 'What are the three phases of the hair growth cycle in correct order?',
    answer_a: 'Anagen, telogen, catagen',
    answer_b: 'Telogen, anagen, catagen',
    answer_c: 'Catagen, telogen, anagen',
    answer_d: 'Anagen, catagen, telogen',
    correct_answer: 'd',
    explanation: 'The three phases are: ANAGEN (active growth), CATAGEN (transitional phase where growth stops), and TELOGEN (resting phase where hair sheds and is replaced). Think "A-C-T like a play."',
    difficulty: 'easy',
    order_index: 52,
  },
  {
    id: 'qq-10-053',
    quiz_id: 'quiz-10',
    question: 'About how long does the anagen phase last according to Chapter 10?',
    answer_a: '2–10 years',
    answer_b: '3–6 months',
    answer_c: '1–2 weeks',
    answer_d: '75–100 days',
    correct_answer: 'a',
    explanation: 'The Chapter 10 source record gives anagen a duration of about 2–10 years.',
    difficulty: 'medium',
    order_index: 53,
  },
  {
    id: 'qq-10-054',
    quiz_id: 'quiz-10',
    question: 'Which statement about telogen is supported by Chapter 10?',
    answer_a: 'It is the active growth phase lasting 2–10 years',
    answer_b: 'It is the resting/shedding phase, lasts about 3–6 months, and includes less than 10% of scalp hair',
    answer_c: 'It is the transition phase where new cells are rapidly manufactured',
    answer_d: 'It is the phase in which permanent waving breaks disulfide bonds',
    correct_answer: 'b',
    explanation: 'Chapter 10 describes telogen as the resting/shedding phase lasting about 3–6 months, with less than 10% of scalp hair in that phase.',
    difficulty: 'hard',
    order_index: 54,
  },
  {
    id: 'qq-10-055',
    quiz_id: 'quiz-10',
    question: 'Which statement correctly contrasts anagen and telogen?',
    answer_a: 'Anagen = pigment production; telogen = porosity testing',
    answer_b: 'Anagen = 3–6 months resting/shedding; telogen = 2–10 years active growth',
    answer_c: 'Anagen = 2–10 years active growth; telogen = 3–6 months resting/shedding',
    answer_d: 'Anagen and telogen are two names for the catagen transition phase',
    correct_answer: 'c',
    explanation: 'Chapter 10 describes anagen as the active growth phase lasting about 2–10 years and telogen as the resting/shedding phase lasting about 3–6 months.',
    difficulty: 'hard',
    order_index: 55,
  },

  // WAVE PATTERNS & CROSS SECTIONS (5 questions)
  {
    id: 'qq-10-056',
    quiz_id: 'quiz-10',
    question: 'A strand has an elliptical cross section. Which wave pattern does Chapter 10 associate with that shape?',
    answer_a: 'No natural wave pattern',
    answer_b: 'Straight',
    answer_c: 'Wavy only',
    answer_d: 'Extremely curly',
    correct_answer: 'd',
    explanation: 'Chapter 10 associates an elliptical cross section with extremely curly hair. Round is associated with straight hair, while oval-to-round is associated with wavy or curly hair.',
    difficulty: 'hard',
    order_index: 56,
  },
  {
    id: 'qq-10-057',
    quiz_id: 'quiz-10',
    question: 'What cross section shape produces extremely curly hair?',
    answer_a: 'Elliptical (flattened) cross section',
    answer_b: 'Round cross section',
    answer_c: 'Square cross section',
    answer_d: 'Triangular cross section',
    correct_answer: 'a',
    explanation: 'Hair with an elliptical (flattened) cross section is extremely curly. Round cross section = straight; oval = wavy/curly.',
    difficulty: 'easy',
    order_index: 57,
  },
  {
    id: 'qq-10-058',
    quiz_id: 'quiz-10',
    question: 'Is it true that only certain races can have extremely curly or extremely straight hair?',
    answer_a: 'Yes — only African Americans have extremely curly hair',
    answer_b: 'No — all races can have any wave pattern',
    answer_c: 'Yes — only Asians have extremely straight hair',
    answer_d: 'Yes — only Caucasians have wavy hair',
    correct_answer: 'b',
    explanation: 'Straight, wavy, curly, and extremely curly hair occurs in ALL races. Anyone of any race or mixed race can have hair with varying degrees of curl.',
    difficulty: 'easy',
    order_index: 58,
  },
  {
    id: 'qq-10-059',
    quiz_id: 'quiz-10',
    question: 'What is a hair stream?',
    answer_a: 'A tuft of hair that stands straight up at the hairline',
    answer_b: 'Hair that grows in a circular pattern at the crown',
    answer_c: 'Hair that flows in the same direction, forming a natural part when two streams slope oppositely',
    answer_d: 'Hair that has been parted with a comb during styling',
    correct_answer: 'c',
    explanation: 'A hair stream is hair that flows in the same direction, resulting from follicles being arranged and sloping in a uniform manner. When two streams slope in opposite directions, they form a natural part.',
    difficulty: 'easy',
    order_index: 59,
  },
  {
    id: 'qq-10-060',
    quiz_id: 'quiz-10',
    question: 'What is a cowlick?',
    answer_a: 'A section of hair that grows faster than surrounding hair',
    answer_b: 'Hair that grows in a circular or swirl pattern at the crown',
    answer_c: 'A natural part formed by two hair streams flowing together',
    answer_d: 'A tuft of hair that stands straight up, usually at the front hairline',
    correct_answer: 'd',
    explanation: 'A cowlick is a tuft of hair that stands straight up, usually more noticeable at the front hairline but may be located anywhere on the scalp. Styles should be chosen to minimize the upright effects.',
    difficulty: 'easy',
    order_index: 60,
  },

  // HAIR PIGMENT & COLOR (5 questions)
  {
    id: 'qq-10-061',
    quiz_id: 'quiz-10',
    question: 'What are the two types of melanin and what colors do they produce?',
    answer_a: 'Eumelanin (brown/black) and pheomelanin (red/yellow/blond)',
    answer_b: 'Eumelanin (red/blond) and pheomelanin (brown/black)',
    answer_c: 'Eumelanin (gray/white) and pheomelanin (black/brown)',
    answer_d: 'Eumelanin (blue/green) and pheomelanin (purple/pink)',
    correct_answer: 'a',
    explanation: 'Eumelanin provides brown and black color. Pheomelanin provides red, ginger, yellow, and light blond tones. All natural hair color depends on the ratio of these two melanins.',
    difficulty: 'easy',
    order_index: 61,
  },
  {
    id: 'qq-10-062',
    quiz_id: 'quiz-10',
    question: 'As hair turns gray, which pigment-related change does Chapter 10 describe?',
    answer_a: 'Eumelanin increases until the hair becomes gray',
    answer_b: 'Melanin decreases or is absent and air spaces replace pigment',
    answer_c: 'Pheomelanin converts directly into keratin',
    answer_d: 'The cuticle begins producing new pigment',
    correct_answer: 'b',
    explanation: 'Chapter 10 describes gray hair as lacking pigment, with air spaces replacing melanin.',
    difficulty: 'medium',
    order_index: 62,
  },
  {
    id: 'qq-10-063',
    quiz_id: 'quiz-10',
    question: 'Which pigment pairing is correct for natural hair color?',
    answer_a: 'Melanin—gray only; keratin—black only',
    answer_b: 'Eumelanin—red/yellow; pheomelanin—brown/black',
    answer_c: 'Eumelanin—brown/black; pheomelanin—red/ginger/yellow',
    answer_d: 'Cuticle—brown/black; medulla—red/yellow',
    correct_answer: 'c',
    explanation: 'Chapter 10 states that eumelanin produces brown/black tones and pheomelanin produces red, ginger, and yellow tones.',
    difficulty: 'medium',
    order_index: 63,
  },
  {
    id: 'qq-10-064',
    quiz_id: 'quiz-10',
    question: 'Does shaving or cutting hair make it grow back faster, darker, or coarser?',
    answer_a: 'Only if you shave against the grain',
    answer_b: 'Yes — shaving stimulates follicles to produce thicker hair',
    answer_c: 'Yes — cutting hair signals the body to grow it faster',
    answer_d: 'No — shaving or cutting has no effect on growth rate, color, or texture',
    correct_answer: 'd',
    explanation: 'Shaving or cutting hair has NO effect on hair growth rate, color, or texture. When hair is blunt cut to the same length, it may grow back more evenly, but the hair itself is unchanged.',
    difficulty: 'easy',
    order_index: 64,
  },
  {
    id: 'qq-10-065',
    quiz_id: 'quiz-10',
    question: 'Which root structure provides the blood and nerve supply associated with hair growth?',
    answer_a: 'Dermal papilla',
    answer_b: 'Cuticle',
    answer_c: 'Medulla',
    answer_d: 'Hair shaft',
    correct_answer: 'a',
    explanation: 'The dermal papilla is located at the base of the follicle and provides blood and nerve supply associated with hair growth.',
    difficulty: 'medium',
    order_index: 65,
  },

  // ── ENHANCEMENT QUESTIONS — GAPS FROM CONTENT REVIEW ──
  {
    id: 'qq-10-066',
    quiz_id: 'quiz-10',
    question: 'Which scalp-analysis finding clearly means the barber should not begin the service?',
    answer_a: 'Hair density is low',
    answer_b: 'Parasites are present',
    answer_c: 'The client has a cowlick',
    answer_d: 'The hair is naturally wavy',
    correct_answer: 'b',
    explanation: 'Chapter 10 states that the service should not begin when parasites are present.',
    difficulty: 'hard',
    order_index: 66,
  },
  {
    id: 'qq-10-071',
    quiz_id: 'quiz-10',
    question: 'What is the sebaceous gland and what does it produce?',
    answer_a: 'The innermost layer of the hair shaft',
    answer_b: 'A muscle that causes goose bumps when contracted',
    answer_c: 'A small oil-producing gland connected to each follicle that produces sebum',
    answer_d: 'A blood vessel that nourishes the dermal papilla',
    correct_answer: 'c',
    explanation: 'The sebaceous gland is a small oil-producing gland connected to EACH hair follicle. It produces sebum — a natural oil that lubricates the hair and skin. Overproduction = oily scalp. Underproduction = dryness and brittleness.',
    difficulty: 'easy',
    order_index: 71,
  },
  {
    id: 'qq-10-072',
    quiz_id: 'quiz-10',
    question: 'Which statement correctly distinguishes peptide bonds from side bonds?',
    answer_a: 'Peptide bonds form the medulla; side bonds form the cuticle',
    answer_b: 'Peptide bonds determine pigment; side bonds determine density',
    answer_c: 'Peptide bonds are scalp structures; side bonds are follicle glands',
    answer_d: 'Peptide bonds join amino acids into polypeptide chains; side bonds cross-link those chains',
    correct_answer: 'd',
    explanation: 'Chapter 10 describes peptide bonds as joining amino acids into polypeptide chains and side bonds as cross-links between those chains.',
    difficulty: 'hard',
    order_index: 72,
  },
  {
    id: 'qq-10-073',
    quiz_id: 'quiz-10',
    question: 'During hair analysis, a barber sees alternating gray and pigmented bands along the same strands. Which condition best matches this finding?',
    answer_a: 'Ringed hair',
    answer_b: 'Canities without banding',
    answer_c: 'Trichoptilosis',
    answer_d: 'Monilethrix',
    correct_answer: 'a',
    explanation: 'Chapter 10 describes ringed hair as alternating bands of gray and pigmented hair along the strand.',
    difficulty: 'hard',
    order_index: 73,
  },
  {
    id: 'qq-10-074',
    quiz_id: 'quiz-10',
    question: "A barber sees one section flowing in a single direction, a crown area growing in a circular pattern, and a front tuft standing upright. How should these three growth patterns be identified?",
    answer_a: 'Stream is at the crown; whorl is at the hairline; cowlick is in the back',
    answer_b: 'Stream flows one direction; whorl is circular; cowlick stands straight up',
    answer_c: 'Stream is genetic; whorl is caused by styling; cowlick is a disorder',
    answer_d: 'They are all different names for the same growth pattern',
    correct_answer: 'b',
    explanation: 'A hair stream flows in one direction (two opposing streams form a natural part). A whorl grows in a circular/swirl pattern, usually at the crown. A cowlick is a tuft that stands straight up, usually at the front hairline.',
    difficulty: 'hard',
    order_index: 74,
  },
  {
    id: 'qq-10-075',
    quiz_id: 'quiz-10',
    question: 'Which tinea condition is ringworm of the scalp?',
    answer_a: 'Tinea favosa',
    answer_b: 'Tinea barbae',
    answer_c: 'Tinea capitis',
    answer_d: 'Pityriasis steatoides',
    correct_answer: 'c',
    explanation: 'Chapter 10 identifies tinea capitis as ringworm of the scalp. Tinea barbae affects the beard area, while tinea favosa has dry sulfur-yellow honeycomb-like crusts.',
    difficulty: 'hard',
    order_index: 75,
  },
  {
    id: 'qq-10-067',
    quiz_id: 'quiz-10',
    question: 'Which finding means a chemical service should not proceed according to Chapter 10?',
    answer_a: 'The hair has medium density',
    answer_b: 'The hair has a natural cowlick',
    answer_c: 'Irritation or abrasions are present',
    answer_d: 'The client has a round hair cross section',
    correct_answer: 'c',
    explanation: 'Chapter 10 states that chemical services should not proceed when irritation or abrasions are present.',
    difficulty: 'hard',
    order_index: 67,
  },
  {
    id: 'qq-10-068',
    quiz_id: 'quiz-10',
    question: 'How much can curly or wavy hair stretch during an elasticity test and still be considered normal?',
    answer_a: 'Curly hair cannot stretch without breaking',
    answer_b: 'Up to 10 percent of its original length',
    answer_c: 'Up to 100 percent (double its length)',
    answer_d: 'Up to 50 percent of its original length',
    correct_answer: 'd',
    explanation: 'Curly or wavy hair may stretch up to 50 percent of its original length and return to that length without breaking. This is normal elasticity. Low elasticity means hair breaks easily or fails to return to normal length.',
    difficulty: 'medium',
    order_index: 68,
  },
  {
    id: 'qq-10-069',
    quiz_id: 'quiz-10',
    question: 'Which element in the COHNS composition is directly associated with strong disulfide side bonds?',
    answer_a: 'Sulfur',
    answer_b: 'Oxygen',
    answer_c: 'Carbon',
    answer_d: 'Hydrogen',
    correct_answer: 'a',
    explanation: 'Sulfur makes up 5% of the COHNS elements listed for hair and is associated with strong disulfide side bonds.',
    difficulty: 'hard',
    order_index: 69,
  },
  {
    id: 'qq-10-070',
    quiz_id: 'quiz-10',
    question: 'Which statement best distinguishes folliculitis barbae from pseudofolliculitis barbae?',
    answer_a: 'They are two names for the same fungal infection',
    answer_b: 'Folliculitis involves inflamed follicles; pseudofolliculitis is associated with ingrown hairs',
    answer_c: 'Folliculitis affects only the scalp while pseudofolliculitis affects only eyebrows',
    answer_d: 'Both are normal hair-growth patterns',
    correct_answer: 'b',
    explanation: 'Chapter 10 distinguishes folliculitis/folliculitis barbae from pseudofolliculitis barbae, which is associated with ingrown hairs and chronic inflammation.',
    difficulty: 'hard',
    order_index: 70,
  },
]
