import type { QuizQuestion } from '@/types'
import type { ConceptId } from './chapter-2-concepts/types'
type A='a'|'b'|'c'|'d'; type D='easy'|'medium'|'hard'
interface S{conceptId:ConceptId;sourceBlockIds:readonly string[];sourceBasis:string;items:readonly {question:string;answer_a:string;answer_b:string;answer_c:string;answer_d:string;correct_answer:A;explanation:string;difficulty:D}[]}
const seeds:readonly S[]=[
{conceptId:'C-2-06',sourceBlockIds:['goal-setting','smart-goals','short-vs-long','action-steps','goal-levels'],sourceBasis:'ASCYN Chapter 2 lesson: goals become actionable when they are specific, measurable, achievable, relevant, time-bound, and broken into steps.',items:[
{question:'Which goal best fits the SMART framework used in Chapter 2?',answer_a:'Complete five fade practices each week for eight weeks and log every session.',answer_b:'Get much better at fades as soon as possible.',answer_c:'Become the best barber in the city someday.',answer_d:'Practice whenever there is extra time.',correct_answer:'a',explanation:'The first goal is specific, measurable, time-bound, and structured for action; the others are vague or lack a clear tracking method.',difficulty:'medium'},
{question:'A student says, “I want more clients.” Which revision best improves the goal?',answer_a:'Keep the wording broad so there is flexibility.',answer_b:'Set a measurable target and a deadline, such as adding ten regular clients in three months.',answer_c:'Remove the deadline so pressure does not interfere.',answer_d:'Replace the goal with a general mission statement.',correct_answer:'b',explanation:'Chapter 2 teaches that measurable targets and deadlines convert broad intentions into goals that can be planned and tracked.',difficulty:'medium'},
{question:'A long-term goal feels overwhelming. What should the student do first?',answer_a:'Drop the goal and choose one that can be finished this week.',answer_b:'Work only on the easiest part until motivation returns.',answer_c:'Break the goal into milestones and smaller scheduled actions.',answer_d:'Wait until all resources are available before starting.',correct_answer:'c',explanation:'Breaking a large goal into milestones and concrete actions is the Chapter 2 method for turning a distant outcome into manageable work.',difficulty:'application'},
{question:'Why is “relevant” important in a SMART goal?',answer_a:'It guarantees the goal can be completed quickly.',answer_b:'It makes every goal financially profitable.',answer_c:'It removes the need for measurement.',answer_d:'It connects the goal to the person’s larger priorities and career direction.',correct_answer:'d',explanation:'Relevance keeps effort connected to the larger career vision instead of spending time on targets that do not meaningfully support the person’s direction.',difficulty:'medium'}]},
{conceptId:'C-2-07',sourceBlockIds:['track-progress','goal-challenges'],sourceBasis:'ASCYN Chapter 2 lesson: progress journals, visual trackers, milestones, and accountability help a learner compare actual progress with the plan and adjust.',items:[
{question:'What is the main purpose of tracking a goal after it has been set?',answer_a:'To compare actual progress with the plan and identify needed adjustments.',answer_b:'To make the goal harder every week.',answer_c:'To avoid changing any original milestone.',answer_d:'To replace action with daily reflection.',correct_answer:'a',explanation:'Tracking gives the learner evidence about whether the plan is working and where behavior or milestones need adjustment.',difficulty:'medium'},
{question:'A student misses two weekly milestones. What response best fits Chapter 2 goal tracking?',answer_a:'Ignore the misses and keep the exact same plan.',answer_b:'Review why the milestones were missed and adjust the next actions without abandoning the larger goal.',answer_c:'Restart the entire goal from zero.',answer_d:'Stop tracking until motivation improves.',correct_answer:'b',explanation:'Tracking is useful because it supports informed adjustment; missing a milestone is feedback, not a reason to erase the larger goal.',difficulty:'application'},
{question:'Which tool gives the clearest evidence that a student is consistently following a practice goal?',answer_a:'A vague memory of how busy the week felt.',answer_b:'A social media post about the goal.',answer_c:'A journal or tracker recording completed practice sessions and milestones.',answer_d:'A one-time conversation about motivation.',correct_answer:'c',explanation:'A written or visual tracker records actual behavior and milestones, making progress more visible and easier to review accurately.',difficulty:'medium'},
{question:'How can an accountability partner strengthen goal achievement?',answer_a:'By completing missed tasks for the student.',answer_b:'By choosing all future goals for the student.',answer_c:'By eliminating the need for self-monitoring.',answer_d:'By checking in on agreed actions and helping the student stay responsible for follow-through.',correct_answer:'d',explanation:'Accountability adds an external check on commitments while the student remains responsible for completing and adjusting their own actions.',difficulty:'medium'}]},
{conceptId:'C-2-08',sourceBlockIds:['time-challenge','time-traps','time-tools','time-scenarios','time-actions'],sourceBasis:'ASCYN Chapter 2 lesson: time management uses priorities, planning, protected blocks, and control of common time traps.',items:[
{question:'A student says they never have time to practice, but spends unplanned time scrolling each evening. What is the best first correction?',answer_a:'Identify the time trap and protect a specific practice block before the evening begins.',answer_b:'Wait for a week with fewer responsibilities.',answer_c:'Practice only when motivation is especially high.',answer_d:'Schedule every minute of the day without breaks.',correct_answer:'a',explanation:'Chapter 2 treats unplanned distractions as time traps and recommends deliberate blocks for important work instead of waiting for leftover time.',difficulty:'application'},
{question:'What is the main advantage of time blocking?',answer_a:'It makes every task take exactly the planned amount of time.',answer_b:'It assigns protected periods to priorities so competing demands do not automatically take over.',answer_c:'It eliminates the need to adjust a schedule.',answer_d:'It works only for school and not for work or family responsibilities.',correct_answer:'b',explanation:'Time blocking protects priorities by deciding in advance when important activities happen, while still allowing realistic schedule adjustments.',difficulty:'medium'},
{question:'A barber is already behind when another request is added. Which action best demonstrates time-management judgment?',answer_a:'Accept every request and hope to catch up later.',answer_b:'Shorten each service without telling clients.',answer_c:'Communicate realistic timing and protect the quality of existing commitments.',answer_d:'Ignore the schedule until the rush is over.',correct_answer:'c',explanation:'Good time management includes realistic capacity decisions and clear communication instead of overcommitting and degrading service quality.',difficulty:'hard'},
{question:'Which habit most directly prevents small tasks from consuming attention all day?',answer_a:'Saving every small task for the end of the month.',answer_b:'Switching priorities whenever a new message appears.',answer_c:'Avoiding written plans to stay flexible.',answer_d:'Using a simple rule for quick tasks while keeping major work inside protected blocks.',correct_answer:'d',explanation:'Chapter 2 teaches simple tools such as the 2-Minute Rule alongside time blocks so minor tasks are handled without taking over major priorities.',difficulty:'medium'}]},
{conceptId:'C-2-09',sourceBlockIds:['sample-schedule'],sourceBasis:'ASCYN Chapter 2 lesson: a balanced schedule intentionally protects school, practice, study, family, and rest while remaining adaptable.',items:[
{question:'Which weekly plan best matches the Chapter 2 sample-schedule principle?',answer_a:'Protect recurring school, practice, study, family, and rest blocks, then adjust them to real commitments.',answer_b:'Schedule only work and fit everything else into leftover time.',answer_c:'Use a different plan every day so no routine forms.',answer_d:'Avoid rest blocks because they reduce productivity.',correct_answer:'a',explanation:'The sample schedule intentionally balances major responsibilities and protects practice and study instead of leaving them to chance.',difficulty:'medium'},
{question:'A student works evenings three days a week. How should the sample schedule be used?',answer_a:'Copy the example exactly even if it conflicts with work.',answer_b:'Adapt the blocks to the student’s real schedule while still protecting practice, study, family, and rest.',answer_c:'Remove all study blocks on workdays.',answer_d:'Use the sample only after graduation.',correct_answer:'b',explanation:'Chapter 2 presents the schedule as a framework to adapt, not a rigid template; the important part is intentionally protecting priorities.',difficulty:'application'},
{question:'Why does the lesson compare protected practice blocks to paid appointments?',answer_a:'Because students should charge themselves for missed practice.',answer_b:'Because every practice session must last as long as a client service.',answer_c:'Because treating the block as a real commitment makes it less likely to be displaced by low-priority activity.',answer_d:'Because practice is more important than family or rest.',correct_answer:'c',explanation:'The comparison emphasizes commitment: scheduled development time should be respected rather than treated as optional leftover time.',difficulty:'medium'},
{question:'A schedule is balanced on paper but consistently fails by Wednesday. What is the best response?',answer_a:'Add more activities to build discipline.',answer_b:'Stop scheduling and rely on memory.',answer_c:'Keep the plan unchanged for several months.',answer_d:'Review where the plan is unrealistic and revise the blocks while preserving the key priorities.',correct_answer:'d',explanation:'A useful schedule is adjustable. Repeated failure signals that timing or workload needs revision, not that planning should be abandoned.',difficulty:'hard'}]},
{conceptId:'C-2-10',sourceBlockIds:['study-habits'],sourceBasis:'ASCYN Chapter 2 lesson: active learning, spaced repetition, practice, teaching, and repeated retrieval support durable learning.',items:[
{question:'Which study activity is most active?',answer_a:'Explaining a concept from memory to a classmate and checking what was missed.',answer_b:'Rereading the same page several times without testing recall.',answer_c:'Highlighting nearly every sentence in a chapter.',answer_d:'Listening to a recording while doing unrelated tasks.',correct_answer:'a',explanation:'Active learning requires the learner to retrieve, explain, practice, or apply information rather than only re-expose themselves to it.',difficulty:'medium'},
{question:'Why does spaced repetition improve study efficiency?',answer_a:'It removes the need for practice questions.',answer_b:'It revisits material across time instead of relying on one massed review session.',answer_c:'It works only for definitions and not procedures.',answer_d:'It guarantees perfect memory after one week.',correct_answer:'b',explanation:'Chapter 2 recommends repeated review over days and weeks because distributed exposure strengthens recall more effectively than a single cram session.',difficulty:'medium'},
{question:'A student can recognize a term when reading it but cannot explain it without notes. What study change is most appropriate?',answer_a:'Read the definition more slowly.',answer_b:'Highlight the term in another color.',answer_c:'Use retrieval practice by trying to explain the term before checking the notes.',answer_d:'Skip the term until the next chapter.',correct_answer:'c',explanation:'Recognition is weaker than retrieval. Attempting an explanation from memory reveals the real gap and gives the student a chance to strengthen recall.',difficulty:'application'},
{question:'Which plan best combines Chapter 2 study principles?',answer_a:'One long review the night before the exam.',answer_b:'Passive reading followed by no self-testing.',answer_c:'Studying only material that already feels familiar.',answer_d:'Short focused sessions, active recall, repeated review, and targeted practice on missed material.',correct_answer:'d',explanation:'The Chapter 2 study system combines focus, retrieval, spaced review, and correction of weak areas instead of depending on passive or last-minute study.',difficulty:'hard'}]}
]
export const chapter2G5ReassessmentQuestionsP3:QuizQuestion[]=seeds.flatMap((s,si)=>s.items.map((x,qi)=>({id:`qq-2-${String(96+si*4+qi).padStart(3,'0')}`,quiz_id:'quiz-2',...x,order_index:96+si*4+qi})))
export const chapter2G5ReassessmentMappingsP3=chapter2G5ReassessmentQuestionsP3.map((q,i)=>({questionId:q.id as `qq-2-${string}`,conceptId:seeds[Math.floor(i/4)].conceptId}))
export const chapter2G5ReassessmentAuditP3=chapter2G5ReassessmentQuestionsP3.map((q,i)=>{const s=seeds[Math.floor(i/4)];return{questionId:q.id,conceptId:s.conceptId,sourceBlockIds:s.sourceBlockIds,sourceBasis:s.sourceBasis}})
