/**
 * Chapter 4 Reassessment Reserve (C4-3)
 *
 * 90 original ASCYN PRO knowledge-check questions for Chapter 4 remediation
 * cycles — completely separate from the locked 30-question initial quiz
 * (chapter-4-premium-quiz.ts). IDs continue the sequence at qq-4-031; no
 * initial-quiz ID is reused, and no reserve question ever enters the initial
 * quiz serving path.
 *
 * Every question maps to exactly one of the six locked concept families:
 *   ch4-pathogens-transmission      — qq-4-031..045 (15)
 *   ch4-disinfection-sterilization  — qq-4-046..060 (15)
 *   ch4-cross-contamination         — qq-4-061..075 (15)
 *   ch4-blood-exposure-ppe          — qq-4-076..090 (15)
 *   ch4-regulatory-chemical-safety  — qq-4-091..105 (15)
 *   ch4-safe-practice-compliance    — qq-4-106..120 (15)
 *
 * Capacity rationale: a Knowledge Check consumes 5 unseen questions from one
 * family's pool per cycle; cycles are DB-capped at 3 per user/concept, so 15
 * per family guarantees the pool can never legitimately exhaust in the
 * designed flow. Pool exhaustion remains an explicit, recorded state.
 *
 * Difficulty per family: 6 easy / 6 medium / 3 hard (40/40/20), totaling
 * 36 easy / 36 medium / 18 hard across the bank.
 * Correct-answer positions are globally balanced A=23, B=23, C=22, D=22, and
 * option lengths are varied so neither position nor length carries a signal.
 * All wording is original ASCYN PRO. No publisher prose. No board-exam, law,
 * or licensure claims.
 *
 * Question → concept mapping lives in chapter-4-concepts/mappings.ts
 * (chapter4ReassessmentQuestionConceptMappings).
 */

import { QuizQuestion } from '@/types'

export const chapter4ReassessmentQuestions: QuizQuestion[] = [
  // ═══════════════════════════════════════════════════════════════
  // PATHOGENS, INFECTION & TRANSMISSION (15) — qq-4-031..045
  // Positions A4 B4 C4 D3 · 6 easy / 6 medium / 3 hard
  // ═══════════════════════════════════════════════════════════════
  { id:'qq-4-031',quiz_id:'quiz-4',question:'Bacteria are classified by shape. Which set lists the three basic bacterial shapes?',answer_a:'Cocci, bacilli, and spirilla',answer_b:'Viruses, fungi, and parasites',answer_c:'Flagella, spores, and capsules',answer_d:'Pathogens, antigens, and antibodies',correct_answer:'a',explanation:'Cocci are spherical, bacilli are rod-shaped, and spirilla are spiral or corkscrew-shaped bacteria.',difficulty:'easy',order_index:31 },
  { id:'qq-4-032',quiz_id:'quiz-4',question:'Which statement best describes nonpathogenic microorganisms?',answer_a:'They always cause disease in humans whenever they are present on skin or surfaces',answer_b:'They are generally harmless, and many are beneficial or necessary',answer_c:'They multiply only inside living host cells',answer_d:'They are destroyed by ordinary handwashing alone',correct_answer:'b',explanation:'Most microorganisms are nonpathogenic — they do not cause disease under ordinary conditions, and many perform useful functions.',difficulty:'easy',order_index:32 },
  { id:'qq-4-033',quiz_id:'quiz-4',question:'How do viruses multiply?',answer_a:'By dividing on moist surfaces like sink drains and shower floors',answer_b:'By forming spores in warm air',answer_c:'By entering a living host cell and using it to reproduce',answer_d:'By absorbing nutrients from hair products',correct_answer:'c',explanation:'Viruses are not complete cells; they must invade a living host cell and use its machinery to replicate.',difficulty:'easy',order_index:33 },
  { id:'qq-4-034',quiz_id:'quiz-4',question:'Why is hepatitis B specifically relevant to barbering?',answer_a:'It spreads mainly through contaminated hair products used at the station every single day',answer_b:'It is carried on dirty floors and enters through shoes',answer_c:'It is an airborne fungus common in salons',answer_d:'It is a bloodborne virus that can spread through nicks and sharps contact',correct_answer:'d',explanation:'Hepatitis B is a bloodborne pathogen; razor nicks, lancets, and sharps create potential exposure routes in barbering.',difficulty:'medium',order_index:34 },
  { id:'qq-4-035',quiz_id:'quiz-4',question:'A client has a circular, scaly, reddened patch on the scalp. Conditions caused by tinea are classified as:',answer_a:'Fungal infections',answer_b:'Viral infections',answer_c:'Bacterial infections',answer_d:'Parasitic infestations',correct_answer:'a',explanation:'Tinea refers to fungal infections such as ringworm; barbers recognize but never diagnose such conditions.',difficulty:'medium',order_index:35 },
  { id:'qq-4-036',quiz_id:'quiz-4',question:'Pediculosis, a condition barbers must recognize, is caused by:',answer_a:'A virus transmitted through sneezing',answer_b:'Parasites such as head lice',answer_c:'A bacterium found in standing water',answer_d:'A fungus that lives in clipper oil',correct_answer:'b',explanation:'Pediculosis is infestation by parasitic lice; services are declined and tools must never contact the affected area.',difficulty:'easy',order_index:36 },
  { id:'qq-4-037',quiz_id:'quiz-4',question:'What is the difference between active and passive immunity?',answer_a:'Active immunity is always temporary protection, while passive immunity provides permanent lifelong protection against every disease at all times',answer_b:'There is no practical difference between them',answer_c:'Active immunity develops after exposure or vaccination; passive immunity is borrowed protection such as antibodies from another source',answer_d:'Passive immunity requires a series of injections over months',correct_answer:'c',explanation:'Active immunity is produced by the body after infection or vaccination; passive immunity comes from receiving pre-formed antibodies.',difficulty:'easy',order_index:37 },
  { id:'qq-4-038',quiz_id:'quiz-4',question:'Why are biofilms a concern when disinfecting implements?',answer_a:'Their protective matrix can shield microorganisms, so physical cleaning must break them up before disinfection',answer_b:'They make disinfectants evaporate much faster from surfaces during the required labeled contact time period every time',answer_c:'They only form on living skin, never on tools',answer_d:'They are destroyed instantly by any contact with water',correct_answer:'a',explanation:'Biofilms shelter microorganisms inside a protective matrix; cleaning disrupts the film so the disinfectant can reach the organisms.',difficulty:'medium',order_index:38 },
  { id:'qq-4-039',quiz_id:'quiz-4',question:'Staphylococci are significant to barbers because they:',answer_a:'Are the viruses directly responsible for the common cold and for seasonal influenza outbreaks',answer_b:'Are common bacteria often carried on skin that can cause infection if they enter broken skin',answer_c:'Are airborne fungi found in damp towels',answer_d:'Only exist inside sterilization equipment',correct_answer:'b',explanation:'Staphylococci commonly live on skin and can cause infections — including pustules and boils — when they enter broken skin.',difficulty:'medium',order_index:39 },
  { id:'qq-4-040',quiz_id:'quiz-4',question:'A client sits down with several pus-filled bumps on the back of the head. What is the safest professional response?',answer_a:'Shave carefully around the bumps and continue with the full haircut service as planned without any concerns at all',answer_b:'Lance the largest bump and clean the area',answer_c:'Decline the service on that area without diagnosing, and suggest the client see a healthcare provider',answer_d:'Apply antiseptic and proceed with the haircut',correct_answer:'c',explanation:'Possible infection signs mean the service is declined on the affected area; barbers never diagnose or treat.',difficulty:'hard',order_index:40 },
  { id:'qq-4-041',quiz_id:'quiz-4',question:'Which situation best illustrates indirect transmission in a barbershop?',answer_a:'A client sneezes directly toward the barber during the middle of a haircut service appointment',answer_b:'A barber touches a client\'s broken skin with bare hands',answer_c:'A barber hugs a client who has a cold',answer_d:'A shared, improperly disinfected comb carries organisms from one client to the next',correct_answer:'d',explanation:'Indirect transmission passes organisms through an intermediate object or surface rather than direct person-to-person contact.',difficulty:'medium',order_index:41 },
  { id:'qq-4-042',quiz_id:'quiz-4',question:'What does it mean for a disease to be contagious?',answer_a:'It can be spread from one person to another',answer_b:'It can only be inherited from parents through their genetic material',answer_c:'It always produces visible symptoms',answer_d:'It cannot survive outside the body',correct_answer:'a',explanation:'A contagious (communicable) disease is capable of spreading between people by direct or indirect means.',difficulty:'easy',order_index:42 },
  { id:'qq-4-043',quiz_id:'quiz-4',question:'A coworker has an active cold sore on the lip and wants to keep working "because it is small." What is the correct understanding?',answer_a:'Cold sores stop being contagious in every possible way as soon as they begin to crust over and dry out completely',answer_b:'Active herpes lesions are contagious, and client-contact services should be avoided until the lesion resolves',answer_c:'Only shaving clients are at risk',answer_d:'Wearing a mask makes client contact safe',correct_answer:'b',explanation:'Active herpes simplex lesions shed virus and are highly contagious; client contact should wait until the lesion resolves.',difficulty:'hard',order_index:43 },
  { id:'qq-4-044',quiz_id:'quiz-4',question:'Why do health authorities recommend hepatitis B vaccination for barbers and cosmetologists?',answer_a:'It prevents all fungal infections acquired at work in the barbershop environment',answer_b:'It is required to sterilize tools correctly',answer_c:'Their work involves potential blood exposure from nicks and sharps',answer_d:'It eliminates the need for Standard Precautions',correct_answer:'c',explanation:'Because barbering involves potential blood exposure, vaccination adds a layer of protection — it never replaces precautions.',difficulty:'medium',order_index:44 },
  { id:'qq-4-045',quiz_id:'quiz-4',question:'A barber nicks a client who appears perfectly healthy. Which principle explains why the full blood-exposure procedure is still required?',answer_a:'Only clients who look visibly ill are able to transmit any infectious disease to others',answer_b:'Infections cannot pass through small nicks',answer_c:'Cleanup is only needed for large amounts of blood',answer_d:'People can carry and transmit bloodborne pathogens without showing symptoms',correct_answer:'d',explanation:'Asymptomatic carriers exist for serious bloodborne diseases, which is exactly why precautions apply to every client.',difficulty:'hard',order_index:45 },

  // ═══════════════════════════════════════════════════════════════
  // CLEANING, DISINFECTION & STERILIZATION (15) — qq-4-046..060
  // Positions A4 B4 C3 D4 · 6 easy / 6 medium / 3 hard
  // ═══════════════════════════════════════════════════════════════
  { id:'qq-4-046',quiz_id:'quiz-4',question:'What must always happen BEFORE an implement is disinfected?',answer_a:'It must be cleaned of visible debris and residue',answer_b:'It must be placed in a sealed drawer overnight before any use',answer_c:'It must be rinsed in hot oil',answer_d:'It must be dried with a client towel',correct_answer:'a',explanation:'Cleaning removes hair, oils, and debris that would shield microorganisms and interfere with disinfectant contact.',difficulty:'easy',order_index:46 },
  { id:'qq-4-047',quiz_id:'quiz-4',question:'Where does a barber find a disinfectant\'s approved uses, required dilution, and contact time?',answer_a:'On the shop\'s appointment board',answer_b:'On the product\'s label',answer_c:'From another barber\'s memory',answer_d:'On the client\'s intake form',correct_answer:'b',explanation:'The label is the authoritative source for approved uses, dilution, contact time, and precautions.',difficulty:'easy',order_index:47 },
  { id:'qq-4-048',quiz_id:'quiz-4',question:'What does a "hospital-grade" (hospital) disinfectant indicate for shop use?',answer_a:'It may be applied directly on open wounds during blood-exposure cleanup events in the shop whenever it is considered necessary',answer_b:'It is intended only for floors',answer_c:'It meets a recognized level of broad-spectrum kill claims appropriate for professional environments when used as labeled',answer_d:'It requires no contact time',correct_answer:'c',explanation:'Hospital-grade disinfectants carry broad-spectrum kill claims suitable for professional settings — always used exactly as labeled.',difficulty:'medium',order_index:48 },
  { id:'qq-4-049',quiz_id:'quiz-4',question:'A tuberculocidal disinfectant is distinguished by:',answer_a:'Its pleasant fragrance, its distinctive blue color, its thick texture, and its well-known national brand name',answer_b:'Being safe to use on skin',answer_c:'Requiring no dilution measurement',answer_d:'A labeled kill claim against Mycobacterium tuberculosis, indicating a higher level of disinfectant strength',correct_answer:'d',explanation:'A tuberculocidal claim indicates the product kills a hard-to-destroy organism class and is appropriate where higher-level claims are required.',difficulty:'medium',order_index:49 },
  { id:'qq-4-050',quiz_id:'quiz-4',question:'An autoclave sterilizes implements by using:',answer_a:'Pressurized steam',answer_b:'Ultraviolet room light',answer_c:'Dry refrigeration',answer_d:'Scented disinfectant vapor',correct_answer:'a',explanation:'Autoclaves use pressurized steam to destroy all forms of microbial life, including spores.',difficulty:'easy',order_index:50 },
  { id:'qq-4-051',quiz_id:'quiz-4',question:'Why should implements be cleaned and rinsed before being placed in disinfectant solution?',answer_a:'To make the handles shine brightly so the next client notices the clean tools',answer_b:'So debris does not interfere with the solution or contaminate the batch',answer_c:'To warm the solution to working temperature',answer_d:'To avoid reading the label each time',correct_answer:'b',explanation:'Debris both blocks disinfectant contact and contaminates the solution for every implement that follows.',difficulty:'easy',order_index:51 },
  { id:'qq-4-052',quiz_id:'quiz-4',question:'When mixing a concentrated disinfectant, the barber should:',answer_a:'Estimate the correct strength by judging its color and smell',answer_b:'Add concentrate until the smell is strong',answer_c:'Use hot tap water only',answer_d:'Measure exactly according to the label directions',correct_answer:'d',explanation:'Dilution is product-specific; guessing produces a solution that is either ineffective or unsafe.',difficulty:'medium',order_index:52 },
  { id:'qq-4-053',quiz_id:'quiz-4',question:'A barber sprays a clipper blade with disinfectant and immediately uses it on the next client. What is wrong?',answer_a:'The labeled contact time was not observed, and proper cleaning may have been skipped',answer_b:'The clipper should have been sprayed at least twice for full disinfecting effect each time',answer_c:'Nothing, if the client did not object',answer_d:'Spray should never be used on metal',correct_answer:'a',explanation:'Disinfectants require the full labeled wet contact time; spraying and immediately wiping or using defeats the kill claim.',difficulty:'hard',order_index:53 },
  { id:'qq-4-054',quiz_id:'quiz-4',question:'After proper disinfection, implements should be stored:',answer_a:'In the same tray as the used tools so that everything stays within easy reach',answer_b:'In a clean, covered container or drawer protected from contamination',answer_c:'Wrapped in a used cape',answer_d:'Standing in open air on the station',correct_answer:'b',explanation:'Protected storage keeps processed implements clean until use; open or mixed storage recontaminates them.',difficulty:'medium',order_index:54 },
  { id:'qq-4-055',quiz_id:'quiz-4',question:'A disinfectant solution looks cloudy and has visible debris. What should the barber do?',answer_a:'Keep using it until the end of the week at the very least',answer_b:'Add fresh concentrate to strengthen it',answer_c:'Replace it, preparing a fresh batch per the label',answer_d:'Strain it through a paper towel and reuse',correct_answer:'c',explanation:'Cloudiness and debris mean the solution is spent or contaminated; it is replaced and prepared fresh per the label.',difficulty:'easy',order_index:55 },
  { id:'qq-4-056',quiz_id:'quiz-4',question:'How do antiseptics and disinfectants differ in intended use?',answer_a:'They are fully interchangeable products that can be used for the exact same purposes in every possible situation without exception',answer_b:'Antiseptics are for floors, disinfectants for skin',answer_c:'Disinfectants are weaker than antiseptics',answer_d:'Antiseptics are formulated for use on living tissue as directed; disinfectants are for appropriate inanimate items and surfaces',correct_answer:'d',explanation:'Antiseptics are for living tissue as directed; disinfectants target inanimate implements and surfaces as labeled.',difficulty:'medium',order_index:56 },
  { id:'qq-4-057',quiz_id:'quiz-4',question:'A straight razor is contaminated with blood during a service. What level of processing applies?',answer_a:'Clean it, then disinfect with a product whose label covers bloodborne-pathogen contamination, following all labeled directions',answer_b:'Wipe it thoroughly with a dry, freshly laundered towel and then immediately continue with the shaving service right away as normal',answer_c:'Rinse with cold water only',answer_d:'Spray with fragrance and store it',correct_answer:'a',explanation:'Blood contamination demands cleaning followed by disinfection with an appropriately labeled product — never a quick wipe.',difficulty:'hard',order_index:57 },
  { id:'qq-4-058',quiz_id:'quiz-4',question:'What does observing the labeled contact time accomplish?',answer_a:'It makes the implement smell clean and pleasant for the waiting clients',answer_b:'It allows the product to achieve the kill claims stated on its label',answer_c:'It prevents the solution from staining handles',answer_d:'It shortens the appointment length',correct_answer:'b',explanation:'Kill claims are validated only when the product stays in contact with the surface for the full labeled time.',difficulty:'medium',order_index:58 },
  { id:'qq-4-059',quiz_id:'quiz-4',question:'When preparing or handling disinfectant solutions, the barber should:',answer_a:'Taste-test the dilution strength carefully with a clean dropper first',answer_b:'Work in a sealed unventilated closet',answer_c:'Hold the bottle near the face to read small print',answer_d:'Follow label precautions such as gloves and ventilation as directed',correct_answer:'d',explanation:'Chemical products are handled per label precautions — appropriate PPE and ventilation protect the worker.',difficulty:'easy',order_index:59 },
  { id:'qq-4-060',quiz_id:'quiz-4',question:'An ultrasonic cleaner is used in the shop. Where does it fit in proper decontamination?',answer_a:'It completely replaces the need for any chemical disinfection when used on a weekly basis without fail',answer_b:'It is used after disinfection to polish tools',answer_c:'It can assist the cleaning step before rinsing and disinfecting according to label directions',answer_d:'It sterilizes implements for blood exposure',correct_answer:'c',explanation:'Ultrasonic units support the cleaning step by loosening debris; disinfection per the label still follows.',difficulty:'hard',order_index:60 },

  // ═══════════════════════════════════════════════════════════════
  // CONTAMINATION & CROSS-CONTAMINATION (15) — qq-4-061..075
  // Positions A4 B3 C4 D4 · 6 easy / 6 medium / 3 hard
  // ═══════════════════════════════════════════════════════════════
  { id:'qq-4-061',quiz_id:'quiz-4',question:'Why must disinfected implements be kept separate from used ones?',answer_a:'Contact with used items can recontaminate them',answer_b:'It keeps the drawer looking organized and professional',answer_c:'It helps count inventory',answer_d:'It speeds up appointments',correct_answer:'a',explanation:'Mixing processed and used items allows transfer of contaminants, undoing the disinfection work.',difficulty:'easy',order_index:61 },
  { id:'qq-4-062',quiz_id:'quiz-4',question:'Why is a fresh neck strip used for each client?',answer_a:'It keeps the cape from wrinkling during longer haircut and styling appointments',answer_b:'It creates a clean barrier and prevents transferring material between clients',answer_c:'It is required for billing purposes',answer_d:'It improves the haircut\'s style',correct_answer:'b',explanation:'A new neck strip per client is a single-use barrier that blocks cross-client transfer at the neck line.',difficulty:'easy',order_index:62 },
  { id:'qq-4-063',quiz_id:'quiz-4',question:'A barber answers a phone during a service and immediately picks up a clean clipper. What is the concern?',answer_a:'The phone may scratch the clipper housing or even damage the blade surface',answer_b:'There is no concern if the call was short',answer_c:'The phone can transfer contaminants to hands and then to the clean tool',answer_d:'The client may become impatient',correct_answer:'c',explanation:'Phones are high-touch contaminated objects; hand hygiene belongs between the phone and the clean tool.',difficulty:'medium',order_index:63 },
  { id:'qq-4-064',quiz_id:'quiz-4',question:'Why should each client receive a freshly laundered cape?',answer_a:'Laundering makes capes look brighter and much fresher for the shop\'s photos every time',answer_b:'It is only about comfort',answer_c:'Capes shrink after one use',answer_d:'A used cape can carry hair, skin, and microorganisms from the previous client',correct_answer:'d',explanation:'Capes directly contact each client; reuse without laundering transfers material between clients.',difficulty:'medium',order_index:64 },
  { id:'qq-4-065',quiz_id:'quiz-4',question:'What is the most direct way hand hygiene between clients controls cross-contamination?',answer_a:'It removes or reduces organisms picked up during the previous service before they reach the next client',answer_b:'It warms the hands for better, more comfortable, and much more precise cutting control during services every day',answer_c:'It is only a courtesy ritual',answer_d:'It replaces the need to disinfect tools',correct_answer:'a',explanation:'Hands are the main transfer vehicle; cleaning them between clients breaks the chain.',difficulty:'medium',order_index:65 },
  { id:'qq-4-066',quiz_id:'quiz-4',question:'Why should used implements NOT be dropped directly into the disinfectant jar?',answer_a:'The jar may tip over and spill disinfectant solution all over the station surface',answer_b:'They will become too slippery to hold',answer_c:'The solution evaporates too fast',answer_d:'Debris from used items contaminates the solution for every item that follows',correct_answer:'d',explanation:'Uncleaned implements load the solution with debris, degrading it for the whole batch.',difficulty:'easy',order_index:66 },
  { id:'qq-4-067',quiz_id:'quiz-4',question:'What is the purpose of processing workstation surfaces between clients?',answer_a:'To break the transfer of material and organisms from one service to the next',answer_b:'To make the shop smell pleasant and inviting for every client who visits each day',answer_c:'To polish the chair\'s finish',answer_d:'To give the barber a break between clients',correct_answer:'a',explanation:'Contact surfaces are part of the transmission pathway; processing them between clients keeps each client\'s environment clean.',difficulty:'easy',order_index:67 },
  { id:'qq-4-068',quiz_id:'quiz-4',question:'A comb falls on the shop floor. The barber rinses it under water and uses it. What is the error?',answer_a:'The comb should have been dried completely and thoroughly first before touching any client hair at all',answer_b:'Rinsing with water is not decontamination — it must be properly cleaned and disinfected or replaced',answer_c:'Floor contact is harmless indoors',answer_d:'The client should have been warned first',correct_answer:'b',explanation:'A water rinse removes neither the contamination nor the need for the full clean-then-disinfect process.',difficulty:'hard',order_index:68 },
  { id:'qq-4-069',quiz_id:'quiz-4',question:'How should soiled towels and capes be handled before laundering?',answer_a:'Shaken out in the cutting area to remove the loose hair',answer_b:'Left draped over stations all day',answer_c:'Placed in a closed container away from clean items',answer_d:'Rinsed in the shampoo bowl between clients',correct_answer:'c',explanation:'Soiled linens go into a closed container, separated from clean items; shaking them spreads contaminants.',difficulty:'easy',order_index:69 },
  { id:'qq-4-070',quiz_id:'quiz-4',question:'Clipper guards are used on one client. What happens before the next client?',answer_a:'They are cleaned and disinfected like the other contact implements',answer_b:'They are blown off with compressed air only between each and every use',answer_c:'They are rotated to a different clipper',answer_d:'Nothing — guards do not contact skin',correct_answer:'a',explanation:'Guards contact hair and skin and receive the same clean-then-disinfect processing as other implements.',difficulty:'medium',order_index:70 },
  { id:'qq-4-071',quiz_id:'quiz-4',question:'During a service a barber touches their own face and hair, then continues on the client. What should happen first?',answer_a:'Nothing, this is completely normal and acceptable shop behavior',answer_b:'Apply cologne to the hands',answer_c:'Perform hand hygiene before resuming client contact',answer_d:'Put on a hat',correct_answer:'c',explanation:'Touching your own face or hair transfers organisms to the hands; hand hygiene comes before client contact resumes.',difficulty:'easy',order_index:71 },
  { id:'qq-4-072',quiz_id:'quiz-4',question:'A barber finishes a blood-exposure cleanup at the station and immediately seats the next client. What step was skipped?',answer_a:'Turning off the clippers and unplugging them from the wall before seating anyone else in the chair',answer_b:'Washing the cape',answer_c:'Charging the client extra',answer_d:'Processing the affected surfaces and items so the next client contacts a clean environment',correct_answer:'d',explanation:'After any exposure or contamination event, the environment must be processed before the next service begins.',difficulty:'hard',order_index:72 },
  { id:'qq-4-073',quiz_id:'quiz-4',question:'Why should product be removed from jars with a clean spatula or single-use applicator?',answer_a:'It keeps the jar from tipping over on the counter and spilling the product everywhere on the floor',answer_b:'Dipping fingers or used tools back into a jar contaminates the product for later clients',answer_c:'It measures the correct price',answer_d:'It warms the product',correct_answer:'b',explanation:'Re-dipping fingers or used tools seeds the container with contaminants that reach every later client.',difficulty:'medium',order_index:73 },
  { id:'qq-4-074',quiz_id:'quiz-4',question:'A disinfected razor is laid on the same tray where used tools rest. What is the result?',answer_a:'The razor stays disinfected and remains fully safe to use on skin',answer_b:'The tray becomes sterile',answer_c:'The razor is considered recontaminated and must be reprocessed',answer_d:'Nothing changes if the tools look clean',correct_answer:'c',explanation:'Contact with a contaminated surface or item negates the disinfection; the item is reprocessed.',difficulty:'medium',order_index:74 },
  { id:'qq-4-075',quiz_id:'quiz-4',question:'Several clients develop the same scalp condition after visiting a shop. Investigators find tools were cleaned but never disinfected, capes were reused, and one barber had poor hand hygiene. What does this illustrate?',answer_a:'A coincidence that is entirely and completely unrelated to the shop\'s daily work practices at all',answer_b:'That only disinfectant choice matters',answer_c:'That laundering capes alone would have prevented it',answer_d:'A chain of cross-contamination failures where each skipped control increases transmission risk',correct_answer:'d',explanation:'Transmission events usually involve multiple failed controls; every layer of the process matters.',difficulty:'hard',order_index:75 },

  // ═══════════════════════════════════════════════════════════════
  // BLOOD EXPOSURE, PPE & STANDARD PRECAUTIONS (15) — qq-4-076..090
  // Positions A3 B4 C4 D4 · 6 easy / 6 medium / 3 hard
  // ═══════════════════════════════════════════════════════════════
  { id:'qq-4-076',quiz_id:'quiz-4',question:'What do Standard Precautions require of a barber?',answer_a:'Treat all human blood and certain body fluids as potentially infectious, for every client',answer_b:'Use precautions only with clients who report feeling ill, unwell, or feverish that particular day',answer_c:'Wear gloves for every haircut regardless of exposure risk',answer_d:'Ask clients for test results before service',correct_answer:'a',explanation:'Standard Precautions apply to every client because infection status cannot be known by appearance or report.',difficulty:'easy',order_index:76 },
  { id:'qq-4-077',quiz_id:'quiz-4',question:'A client is nicked during a shave and begins to bleed. What should the barber do FIRST?',answer_a:'Finish the outline quickly and then help the client with the bleeding afterward right away',answer_b:'Pause the service and begin the blood-exposure procedure using appropriate precautions',answer_c:'Hand the client a towel and continue',answer_d:'Wipe the blade on the cape',correct_answer:'b',explanation:'The service pauses immediately and the exposure procedure begins with appropriate protection.',difficulty:'easy',order_index:77 },
  { id:'qq-4-078',quiz_id:'quiz-4',question:'Why are gloves worn during blood-exposure cleanup?',answer_a:'To keep fingerprints and smudges off all of the chair and station surfaces completely',answer_b:'To satisfy client curiosity',answer_c:'To protect the barber\'s hands from contact with potentially infectious material',answer_d:'To keep the gloves from getting dusty',correct_answer:'c',explanation:'Gloves are a barrier between the worker\'s skin and potentially infectious blood or fluids.',difficulty:'medium',order_index:78 },
  { id:'qq-4-079',quiz_id:'quiz-4',question:'How should a used lancet or razor blade be discarded?',answer_a:'Wrapped carefully in tissue before going into the regular trash',answer_b:'Dropped loose in the station drawer',answer_c:'Flushed down the shampoo bowl',answer_d:'Placed in a rigid, puncture-resistant sharps container',correct_answer:'d',explanation:'Sharps go into puncture-resistant containers so no one downstream is cut or exposed.',difficulty:'medium',order_index:79 },
  { id:'qq-4-080',quiz_id:'quiz-4',question:'What should happen immediately after removing contaminated gloves?',answer_a:'Perform hand hygiene before touching anything clean',answer_b:'Put the same gloves back on to continue the current task',answer_c:'Wipe hands on the work apron',answer_d:'Blow on the hands to dry them',correct_answer:'a',explanation:'Hand hygiene after glove removal clears any contamination transferred during removal or through glove defects.',difficulty:'easy',order_index:80 },
  { id:'qq-4-081',quiz_id:'quiz-4',question:'Which items count as personal protective equipment in barbering?',answer_a:'Aprons and the embroidered name tags that carry the shop\'s logo',answer_b:'Gloves and, where splashing is possible, eye protection',answer_c:'Watches and rings',answer_d:'Hats and sunglasses',correct_answer:'b',explanation:'PPE means barrier equipment chosen for the exposure risk — gloves, and eye protection where splashes are possible.',difficulty:'easy',order_index:81 },
  { id:'qq-4-082',quiz_id:'quiz-4',question:'Which sequence correctly orders a blood-exposure response?',answer_a:'Disinfect first, then clean, then put on gloves',answer_b:'Clean without gloves, then document',answer_c:'Pause service, apply gloves, manage the exposure, clean and disinfect affected items and surfaces, dispose properly, perform hand hygiene',answer_d:'Continue the cut, then clean and disinfect everything thoroughly at the very end of the day when the shop finally closes for the night shift',correct_answer:'c',explanation:'Protection comes first, then managed cleanup and disinfection, proper disposal, and hand hygiene at the end.',difficulty:'medium',order_index:82 },
  { id:'qq-4-083',quiz_id:'quiz-4',question:'A barber has a small open cut on a finger. What is the correct practice before client services?',answer_a:'Work only on adult clients for the remainder of that particular working day',answer_b:'Soak the finger in disinfectant between clients',answer_c:'Ignore it if it is small',answer_d:'Cover the cut with an appropriate bandage and wear gloves during services',correct_answer:'d',explanation:'Broken skin on the worker is covered and gloved — it protects both the worker and the client.',difficulty:'hard',order_index:83 },
  { id:'qq-4-084',quiz_id:'quiz-4',question:'How should blood-contaminated gauze or cotton be handled?',answer_a:'Disposed of properly without contacting clean items or surfaces',answer_b:'Rinsed out and reused again on the same client during the same visit',answer_c:'Placed in the product cabinet',answer_d:'Left on the station for the end of the day',correct_answer:'a',explanation:'Contaminated disposables are bagged and discarded properly, never reused or left in contact areas.',difficulty:'medium',order_index:84 },
  { id:'qq-4-085',quiz_id:'quiz-4',question:'Why must single-use gloves never be reused between tasks or clients?',answer_a:'They lose their original color and elasticity after the very first use',answer_b:'They can carry contamination forward and may have invisible damage',answer_c:'Clients prefer new gloves for appearance',answer_d:'They become uncomfortable',correct_answer:'b',explanation:'Used gloves can be contaminated and can develop invisible micro-tears; they are single-use by design.',difficulty:'easy',order_index:85 },
  { id:'qq-4-086',quiz_id:'quiz-4',question:'Why should a barber avoid touching their eyes, nose, or mouth with contaminated gloves?',answer_a:'It smears carefully applied makeup, foundation, concealer, and powder',answer_b:'It fogs safety glasses',answer_c:'Those membranes provide an entry route for infectious material',answer_d:'It looks unprofessional',correct_answer:'c',explanation:'Mucous membranes are portals of entry; contaminated gloves must stay away from them.',difficulty:'easy',order_index:86 },
  { id:'qq-4-087',quiz_id:'quiz-4',question:'Blood contacts a client\'s cape and the chair\'s armrest during a service. What is the correct response?',answer_a:'Cover the spots and finish the cut',answer_b:'Only the cape needs attention',answer_c:'Continue the service normally and then clean and disinfect everything thoroughly at closing when the shop is quiet and finally empty for the night',answer_d:'Pause the service, manage the exposure with gloves, remove and bag the contaminated cape, and clean then disinfect the armrest before reuse',correct_answer:'d',explanation:'Every contaminated item and surface is addressed with protection on before the service environment is reused.',difficulty:'hard',order_index:87 },
  { id:'qq-4-088',quiz_id:'quiz-4',question:'After a significant blood-exposure incident, what should the barber do according to workplace rules?',answer_a:'Forget about the incident completely once the affected area is clean and tidy again',answer_b:'Record and report the incident as required by shop policy and applicable rules',answer_c:'Tell only other clients',answer_d:'Post about it online',correct_answer:'b',explanation:'Exposure incidents are documented and reported per workplace policy and applicable requirements.',difficulty:'medium',order_index:88 },
  { id:'qq-4-089',quiz_id:'quiz-4',question:'Why do gloves NOT replace hand hygiene?',answer_a:'Gloves are simply far too expensive to rely on for every single daily task in the shop',answer_b:'Hand hygiene is only for show',answer_c:'Gloves can have invisible defects and hands can be contaminated during removal',answer_d:'Regulations require soap specifically',correct_answer:'c',explanation:'Gloves supplement but never replace hand hygiene — defects and removal contamination are real risks.',difficulty:'medium',order_index:89 },
  { id:'qq-4-090',quiz_id:'quiz-4',question:'A barber realizes they managed a blood exposure with bare hands. What should they do?',answer_a:'Nothing needs to be done at all if the client was a personal friend and appeared completely healthy and clean that day at all',answer_b:'Wipe hands on a towel and continue',answer_c:'Only wash at the next break',answer_d:'Immediately perform thorough hand hygiene and follow the shop\'s exposure procedures, then resume with proper precautions',correct_answer:'d',explanation:'Unprotected contact with blood triggers immediate hygiene and the shop\'s exposure follow-up, then proper PPE use.',difficulty:'hard',order_index:90 },

  // ═══════════════════════════════════════════════════════════════
  // REGULATORY & CHEMICAL SAFETY (15) — qq-4-091..105
  // Positions A4 B4 C3 D4 · 6 easy / 6 medium / 3 hard
  // ═══════════════════════════════════════════════════════════════
  { id:'qq-4-091',quiz_id:'quiz-4',question:'Which federal agency sets and enforces workplace safety and health standards?',answer_a:'OSHA',answer_b:'The EPA',answer_c:'FDA',answer_d:'CDC',correct_answer:'a',explanation:'OSHA establishes and enforces workplace safety and health standards for employees.',difficulty:'easy',order_index:91 },
  { id:'qq-4-092',quiz_id:'quiz-4',question:'Which agency registers disinfectant products for their labeled antimicrobial uses?',answer_a:'OSHA',answer_b:'EPA',answer_c:'The state barber board',answer_d:'The local fire department',correct_answer:'b',explanation:'The EPA registers antimicrobial pesticide products, including disinfectants, for their labeled uses.',difficulty:'easy',order_index:92 },
  { id:'qq-4-093',quiz_id:'quiz-4',question:'What information does a Safety Data Sheet (SDS) provide about a chemical product?',answer_a:'Only its current purchase price, its supplier\'s name, and the reorder contact code',answer_b:'Its marketing slogans',answer_c:'Its hazards and instructions for safe handling, storage, PPE, and emergencies',answer_d:'Its fragrance notes',correct_answer:'c',explanation:'The SDS is the detailed safety reference: hazards, handling, storage, protective equipment, and emergency measures.',difficulty:'medium',order_index:93 },
  { id:'qq-4-094',quiz_id:'quiz-4',question:'What is the purpose of GHS hazard pictograms on product labels?',answer_a:'Pure decoration for the bottle and for better shelf appeal in the shop\'s retail area',answer_b:'To indicate the product\'s country of origin',answer_c:'To show the price category',answer_d:'To communicate specific hazard types at a glance through standardized symbols',correct_answer:'d',explanation:'GHS pictograms are standardized symbols that communicate hazard classes instantly.',difficulty:'medium',order_index:94 },
  { id:'qq-4-095',quiz_id:'quiz-4',question:'Why does OSHA\'s Bloodborne Pathogens Standard matter to barbershops?',answer_a:'Nicks and sharps can expose workers to blood, so exposure-control practices apply',answer_b:'It regulates haircut pricing, tipping, and booth rental across all fifty states every year',answer_c:'It applies only to hospitals',answer_d:'It only covers laundry workers',correct_answer:'a',explanation:'The standard addresses occupational blood exposure; barbering involves realistic nick and sharps risk.',difficulty:'medium',order_index:95 },
  { id:'qq-4-096',quiz_id:'quiz-4',question:'Where must Safety Data Sheets be kept in the workplace?',answer_a:'Locked away safely in the owner\'s home office filing cabinet',answer_b:'Readily accessible to employees during work hours',answer_c:'Only on a company website nobody checks',answer_d:'In each employee\'s car',correct_answer:'b',explanation:'SDSs must be accessible to employees whenever they work — they are useless if locked away.',difficulty:'easy',order_index:96 },
  { id:'qq-4-097',quiz_id:'quiz-4',question:'How do a product label and its SDS relate?',answer_a:'The SDS completely and totally replaces the product label in every possible situation and case',answer_b:'The label replaces the SDS',answer_c:'They are unrelated documents',answer_d:'Both are required parts of hazard communication; the SDS gives more detailed information',correct_answer:'d',explanation:'Labels give immediate hazard information; SDSs carry the full detail. Both are part of hazard communication.',difficulty:'medium',order_index:97 },
  { id:'qq-4-098',quiz_id:'quiz-4',question:'A barber pours concentrated disinfectant into an unmarked spray bottle for daily use. What is required?',answer_a:'The secondary container must be properly labeled with the product identity and hazard information',answer_b:'Nothing at all is required, as long as the spray bottle itself is brand new and freshly cleaned out',answer_c:'Only a shake before use',answer_d:'A ribbon to identify it',correct_answer:'a',explanation:'Secondary containers must be labeled so no one mistakes or mishandles the contents.',difficulty:'hard',order_index:98 },
  { id:'qq-4-099',quiz_id:'quiz-4',question:'Why is ventilation important when working with chemical products?',answer_a:'It keeps the shop pleasantly cool and comfortable during the long, hot summer months',answer_b:'It removes dust from hair',answer_c:'It reduces inhalation exposure to chemical vapors as directed by product information',answer_d:'It helps towels dry faster',correct_answer:'c',explanation:'Ventilation limits vapor buildup and inhalation exposure, per product safety information.',difficulty:'easy',order_index:99 },
  { id:'qq-4-100',quiz_id:'quiz-4',question:'What does the state barber or cosmetology board primarily do regarding sanitation?',answer_a:'Sells disinfectants directly to licensed shops at a discounted wholesale price',answer_b:'Sets and enforces licensing and sanitation rules for the profession',answer_c:'Writes the SDS for every product',answer_d:'Insures shops against lawsuits',correct_answer:'b',explanation:'State boards license practitioners and set/enforce the sanitation rules shops must follow.',difficulty:'medium',order_index:100 },
  { id:'qq-4-101',quiz_id:'quiz-4',question:'Which body can inspect a workplace for compliance with chemical-safety and worker-protection standards?',answer_a:'OSHA',answer_b:'The product manufacturer',answer_c:'The local chamber of commerce',answer_d:'The client council',correct_answer:'a',explanation:'OSHA has inspection and enforcement authority over workplace safety and health standards.',difficulty:'easy',order_index:101 },
  { id:'qq-4-102',quiz_id:'quiz-4',question:'A new employee is handed chemicals to use but never told about the SDS or product hazards. What employer duty was missed?',answer_a:'The duty to provide free haircuts and free styling products to all new employees',answer_b:'The duty to assign lockers',answer_c:'The duty to provide parking',answer_d:'Hazard communication training so employees can work with chemicals safely',correct_answer:'d',explanation:'Employers must train employees on chemical hazards and the hazard-communication program before they work with chemicals.',difficulty:'hard',order_index:102 },
  { id:'qq-4-103',quiz_id:'quiz-4',question:'How should chemical products be stored in the shop?',answer_a:'In direct sunlight on the front windowsill where every staff member can easily access them quickly each day',answer_b:'According to their label and SDS directions, properly identified and away from incompatible conditions',answer_c:'Mixed together to save space',answer_d:'In the break-room refrigerator',correct_answer:'b',explanation:'Storage follows the product\'s own directions — correct identification, temperature, and separation from incompatible materials.',difficulty:'medium',order_index:103 },
  { id:'qq-4-104',quiz_id:'quiz-4',question:'What is the rule about mixing chemical products?',answer_a:'Mix any products together that look reasonably similar in color, texture, and smell at all',answer_b:'Always add bleach to boost strength',answer_c:'Never mix products unless the label directions say to — dangerous reactions can occur',answer_d:'Mixing is encouraged to save money',correct_answer:'c',explanation:'Unlisted combinations can release hazardous gases or neutralize the products; only label-directed mixing is allowed.',difficulty:'easy',order_index:104 },
  { id:'qq-4-105',quiz_id:'quiz-4',question:'How should leftover chemical product and empty containers be discarded?',answer_a:'Poured directly into the storm drain just outside the shop door',answer_b:'Burned in the alley',answer_c:'Buried behind the shop',answer_d:'According to the product label, SDS, and applicable local rules',correct_answer:'d',explanation:'Chemical disposal follows the label, the SDS, and local requirements — never drains, burning, or dumping.',difficulty:'hard',order_index:105 },

  // ═══════════════════════════════════════════════════════════════
  // SAFE BARBERING PRACTICE & COMPLIANCE (15) — qq-4-106..120
  // Positions A4 B4 C4 D3 · 6 easy / 6 medium / 3 hard
  // ═══════════════════════════════════════════════════════════════
  { id:'qq-4-106',quiz_id:'quiz-4',question:'A client appears to have a contagious scalp condition. What should the barber do?',answer_a:'Politely decline the service without diagnosing and suggest a healthcare provider',answer_b:'Shave the area first and then carefully evaluate how the bumps look afterward before proceeding',answer_c:'Apply powder to hide it',answer_d:'Charge extra and proceed',correct_answer:'a',explanation:'Suspected contagious conditions mean declining the service without diagnosing; treatment is outside barbering scope.',difficulty:'easy',order_index:106 },
  { id:'qq-4-107',quiz_id:'quiz-4',question:'Which set of actions belongs to a proper between-client station reset?',answer_a:'Sweep only when the hair piles up visibly high around the base of the cutting chair area',answer_b:'Remove debris, process reusable tools, address contact surfaces, and set out clean items',answer_c:'Just fold the cape',answer_d:'Spray air freshener only',correct_answer:'b',explanation:'A reset clears debris, processes tools and surfaces, and stages clean items for the next client.',difficulty:'easy',order_index:107 },
  { id:'qq-4-108',quiz_id:'quiz-4',question:'When should hand hygiene be performed during the workday?',answer_a:'Only at clock-in when arriving in the morning and at clock-out when leaving at night',answer_b:'Only when hands look dirty',answer_c:'Before and after each client, and whenever contamination may have occurred',answer_d:'Once per hour on a timer',correct_answer:'c',explanation:'Hand hygiene brackets every client and follows any possible contamination event.',difficulty:'medium',order_index:108 },
  { id:'qq-4-109',quiz_id:'quiz-4',question:'Why does a proper client consultation include looking at the service area\'s condition?',answer_a:'To judge the client\'s style preferences, favorite cuts, and usual barber of choice',answer_b:'To estimate the tip',answer_c:'To make small talk',answer_d:'To identify visible conditions that may require declining or modifying the service',correct_answer:'d',explanation:'Consultation includes screening the service area for visible conditions that change whether or how a service proceeds.',difficulty:'medium',order_index:109 },
  { id:'qq-4-110',quiz_id:'quiz-4',question:'What keeps a shop inspection-ready every day?',answer_a:'Consistently following sanitation procedures rather than scrambling before inspections',answer_b:'Posting the license on the wall inside a glass frame where every single client can see it',answer_c:'Keeping the front window clean',answer_d:'Playing calm music',correct_answer:'a',explanation:'Inspection readiness is the byproduct of procedures followed every day, not special preparation.',difficulty:'medium',order_index:110 },
  { id:'qq-4-111',quiz_id:'quiz-4',question:'How does a barber\'s own cleanliness contribute to infection control?',answer_a:'It has no real effect on client safety or infection control at all in the barbershop setting',answer_b:'Clean work clothes and personal hygiene reduce the transfer of microorganisms to clients',answer_c:'It only affects appearance',answer_d:'It replaces tool disinfection',correct_answer:'b',explanation:'The worker is part of the transmission pathway; personal hygiene and clean attire reduce transfer.',difficulty:'easy',order_index:111 },
  { id:'qq-4-112',quiz_id:'quiz-4',question:'Why should barbers avoid working directly on inflamed, broken, or infected-looking skin?',answer_a:'It is hard to cut hair cleanly and evenly in those exact areas of the client\'s head safely',answer_b:'Clients dislike it',answer_c:'It raises the risk of transmitting or worsening infection and is outside safe practice',answer_d:'It dulls the blades faster',correct_answer:'c',explanation:'Compromised skin raises transmission and injury risk; such areas are avoided and may require declining service.',difficulty:'medium',order_index:112 },
  { id:'qq-4-113',quiz_id:'quiz-4',question:'During a rush, a coworker suggests skipping disinfection "just this once" to catch up. What is the correct response?',answer_a:'Decline — safety procedures are not optional regardless of schedule pressure',answer_b:'Agree, but only for the regular clients we already know very well and personally',answer_c:'Skip it for the next two clients only',answer_d:'Let the coworker decide for both of you',correct_answer:'a',explanation:'Infection-control procedures are never waived for convenience or volume.',difficulty:'hard',order_index:113 },
  { id:'qq-4-114',quiz_id:'quiz-4',question:'What should happen after a workplace blood-exposure incident is managed?',answer_a:'Nothing further at all is required after the cleanup is completely done and finished',answer_b:'It is documented and reported according to shop policy and applicable rules',answer_c:'The client is banned forever',answer_d:'The tools are thrown away secretly',correct_answer:'b',explanation:'Exposure incidents carry documentation and reporting obligations per workplace policy and applicable rules.',difficulty:'medium',order_index:114 },
  { id:'qq-4-115',quiz_id:'quiz-4',question:'Which opening routine supports infection control?',answer_a:'Reusing yesterday\'s disinfectant solution and topping it off to save a little bit of money each week',answer_b:'Leaving used razors in the jar overnight',answer_c:'Preparing fresh solutions per label, checking clean storage, and setting up disinfected tools',answer_d:'Turning on music and lights only',correct_answer:'c',explanation:'The day starts with fresh labeled solutions, protected storage checks, and properly processed tools.',difficulty:'easy',order_index:115 },
  { id:'qq-4-116',quiz_id:'quiz-4',question:'Which items are single-use in the barbershop?',answer_a:'Clipper blades, combs, scissors, and hand mirrors',answer_b:'Scissors and guards',answer_c:'Chairs and mirrors',answer_d:'Neck strips, lancets, and cotton or gauze',correct_answer:'d',explanation:'Single-use items are discarded after one client; durable implements are cleaned and disinfected instead.',difficulty:'easy',order_index:116 },
  { id:'qq-4-117',quiz_id:'quiz-4',question:'A state inspector observes the shop. Which observation demonstrates compliance?',answer_a:'Disinfected tools stored covered, fresh solution per label, linens separated, SDS accessible',answer_b:'Tools soaking in a cloudy, week-old solution that has visible debris and hair floating in it',answer_c:'Capes piled mixed clean and dirty',answer_d:'Unlabeled spray bottles everywhere',correct_answer:'a',explanation:'Covered clean storage, current labeled solutions, separated linens, and accessible SDSs are visible markers of compliance.',difficulty:'hard',order_index:117 },
  { id:'qq-4-118',quiz_id:'quiz-4',question:'Why should every team member be trained on the shop\'s infection-control procedures?',answer_a:'So everyone cuts hair in exactly the same way on every single client visit always',answer_b:'Consistent practice by every worker keeps the whole shop safe and compliant',answer_c:'So the owner can take vacations',answer_d:'It is only a formality',correct_answer:'b',explanation:'Infection control fails at its weakest link; uniform training keeps every worker\'s practice consistent.',difficulty:'easy',order_index:118 },
  { id:'qq-4-119',quiz_id:'quiz-4',question:'Why do full precautions apply even to long-time regular clients?',answer_a:'Regular clients are statistically far more dangerous than brand-new clients who just arrived',answer_b:'It is the law only for regulars',answer_c:'Infection status cannot be known from familiarity — Standard Precautions apply to everyone',answer_d:'Regulars tip less if procedures are skipped',correct_answer:'c',explanation:'Familiarity reveals nothing about infection status; precautions are universal by design.',difficulty:'medium',order_index:119 },
  { id:'qq-4-120',quiz_id:'quiz-4',question:'Which sequence shows a fully compliant transition between two clients?',answer_a:'Seat next client, then clean if time allows',answer_b:'Swap tools without processing for speed',answer_c:'Ask the previous client to clean, tidy, and disinfect the entire station themselves before they leave the chair and exit the shop area completely and fully on their own',answer_d:'Clear debris, send tools for cleaning and disinfection, process contact surfaces, set out clean items and fresh linens, perform hand hygiene, then seat the next client',correct_answer:'d',explanation:'A compliant transition completes every processing step before the next client is seated.',difficulty:'hard',order_index:120 },
]
