// Chapter 5: Implements, Tools, and Equipment — PREMIUM FLASHCARDS
// The Barber's Forge - precision, steel, mastery
// Categories: Combs & Brushes, Shears, Clippers & Trimmers, Razors, Thermal Tools, Station & Safety, Exam-Relevant Review

import { Flashcard } from '@/types'

export const chapter5PremiumFlashcards: Flashcard[] = [
  // ==========================================
  // CATEGORY 1: COMBS & BRUSHES (8 cards)
  // ==========================================
  {
    id: 'fc-5-001',
    chapter_id: 'ch-5',
    front: "How do common comb materials differ in the Chapter 5 source?",
    back: "Hard rubber is flexible/durable but can deteriorate in disinfectant; carbon is antistatic and heat/chemical resistant; graphite is less rigid; metal retains heat and may corrode.",
    category: "Combs & Brushes",
    difficulty: 'medium',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-5-002',
    chapter_id: 'ch-5',
    front: 'What is the standard length of an all-purpose cutting comb?',
    back: '7-8 inches. It features fine teeth on one end and medium teeth on the other for versatility in sectioning, scissor-over-comb, and general cutting.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-5-003',
    chapter_id: 'ch-5',
    front: "What is a taper comb used for compared with an all-purpose comb?",
    back: "A taper comb is used for blending and detail around areas such as necklines, mustaches, and ears; an all-purpose/styling comb supports general cutting and styling.",
    category: "Combs & Brushes",
    difficulty: 'medium',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-5-004',
    chapter_id: 'ch-5',
    front: "What is the role of clipper guards or attachment combs?",
    back: "They extend cutting length beyond the bare blade. They are cutting-length aids, not substitutes for required cleaning or disinfection.",
    category: "Clippers & Trimmers",
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-5-005',
    chapter_id: 'ch-5',
    front: 'What brush type creates volume and curl during blow-drying?',
    back: 'Round brush. Barrel size matters — larger barrels create bigger curls and more volume. Paddle brushes smooth and straighten; vent brushes speed drying time.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-5-006',
    chapter_id: 'ch-5',
    front: 'When should you replace a comb?',
    back: 'Replace combs with worn, broken, or missing teeth. Damaged teeth snag hair, damage the cuticle, and create uneven sections. A worn comb is a liability.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-5-007',
    chapter_id: 'ch-5',
    front: "What is a pick comb used for?",
    back: "It is used to lift and work with textured or tightly curled hair.",
    category: "Combs & Brushes",
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-5-008',
    chapter_id: 'ch-5',
    front: 'Why should you clean styling brushes daily?',
    back: 'Hair and product buildup transfers between clients. Brushes collect oils, dead skin, and styling product residue. Daily cleaning prevents cross-contamination and maintains brush performance.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 2: SHEARS & SCISSORS (12 cards)
  // ==========================================
  {
    id: 'fc-5-009',
    chapter_id: 'ch-5',
    front: "How do convex and beveled shear edges differ?",
    back: "A convex edge is designed for a very sharp, smooth cutting action; a beveled edge is more durable and grips hair differently.",
    category: "Shears & Scissors",
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-5-010',
    chapter_id: 'ch-5',
    front: "How should shear size be selected?",
    back: "Choose a shear size that fits the barber's hand, technique, and service instead of assuming one universal best length.",
    category: "Shears & Scissors",
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-5-011',
    chapter_id: 'ch-5',
    front: "What does the shear tension screw control?",
    back: "It adjusts pressure between the blades. Tension should allow controlled blade movement rather than being excessively loose or tight.",
    category: "Shears & Scissors",
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-5-012',
    chapter_id: 'ch-5',
    front: "What does overly loose shear tension indicate?",
    back: "The blades open too freely and do not maintain the intended contact. Adjust tension according to the shear design and manufacturer guidance.",
    category: "Shears & Scissors",
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-5-013',
    chapter_id: 'ch-5',
    front: 'What happens if shear tension is too tight?',
    back: 'The blades do not move freely. This causes hand fatigue, premature wear on the pivot screw, and can damage the blade edges over time.',
    category: 'Shears & Scissors',
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-5-014',
    chapter_id: 'ch-5',
    front: "What is the source-book benefit of offset and crane shear handles?",
    back: "Offset and crane designs change hand and wrist position to reduce stress compared with a traditional opposing handle.",
    category: "Shears & Scissors",
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-5-015',
    chapter_id: 'ch-5',
    front: 'What is the purpose of thinning/texturizing shears?',
    back: 'Texturizing/thinning shear designs use toothed blades to remove a portion of hair and create texture or reduce bulk. Tooth count, tooth geometry, and percentage of hair removed vary by manufacturer and model.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-5-016',
    chapter_id: 'ch-5',
    front: 'What is the difference between thinning shears and blending shears?',
    back: 'Thinning, texturizing, and blending shears use different tooth patterns and cutting ratios for different effects. Do not identify them by a universal tooth-count range; verify the tool design and manufacturer specifications.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-5-017',
    chapter_id: 'ch-5',
    front: "Why are left- and right-handed shears assembled differently?",
    back: "Their blade orientation is reversed so the cutting action matches the user's hand and intended shear mechanics.",
    category: "Shears & Scissors",
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-5-018',
    chapter_id: 'ch-5',
    front: "What is shear palming?",
    back: "It is transferring the shears into the palm so the fingers can work with the comb while the tool remains controlled.",
    category: "Shears & Scissors",
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-5-019',
    chapter_id: 'ch-5',
    front: "What maintenance does Chapter 5 emphasize for shears?",
    back: "Clean and disinfect after use, check and adjust tension, protect the shears from drops and harsh handling, and store them safely for transport.",
    category: "Shears & Scissors",
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-5-020',
    chapter_id: 'ch-5',
    front: 'What should you NEVER cut with professional shears?',
    back: 'NEVER cut paper, plastic, wire, or anything other than clean hair. Cutting materials the shear was not designed for can dull, nick, or otherwise damage the cutting edge. A nick from dropping requires professional repair — do not attempt to fix it yourself.',
    category: 'Shears & Scissors',
    difficulty: 'easy',
    order_index: 20,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 3: CLIPPERS & TRIMMERS (10 cards)
  // ==========================================
  {
    id: 'fc-5-021',
    chapter_id: 'ch-5',
    front: 'What is the difference between clippers and trimmers?',
    back: 'Clippers are larger, more powerful, designed for bulk removal, fades, and tapers. Trimmers are smaller, precise tools for outlining, edging, beard lines, and detail work. They serve completely different purposes.',
    category: 'Clippers & Trimmers',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-5-022',
    chapter_id: 'ch-5',
    front: "What three clipper motor types does the Chapter 5 source identify?",
    back: "Rotary, pivot, and magnetic.",
    category: "Clippers & Trimmers",
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-5-023',
    chapter_id: 'ch-5',
    front: "How do rotary, pivot, and magnetic clipper motors differ in the source?",
    back: "The source distinguishes them by operating characteristics such as power, speed, noise, and suitability for different cutting demands.",
    category: "Clippers & Trimmers",
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-5-024',
    chapter_id: 'ch-5',
    front: "What is the difference between adjustable-blade and detachable-blade clippers?",
    back: "Adjustable-blade clippers change blade position with a lever; detachable-blade clippers change cutting length by removing and replacing blade units.",
    category: "Clippers & Trimmers",
    difficulty: 'medium',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-5-025',
    chapter_id: 'ch-5',
    front: "What adjustment caution does the source give for outliner blades?",
    back: "Do not set outliner blades flush simply to make them cut closer; follow manufacturer guidance and maintain safe blade alignment.",
    category: "Clippers & Trimmers",
    difficulty: 'hard',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-5-026',
    chapter_id: 'ch-5',
    front: 'What is the proper clipper blade maintenance routine?',
    back: '1) Remove hair/debris after use. 2) Oil according to the clipper manufacturer directions; quantity and placement vary by model. 3) Between clients, clean and disinfect removable blades/guards as required by current rules and the disinfectant label. 4) Address pulling or snagging by cleaning, oiling, checking alignment/condition, and replacing or servicing the blade when needed.',
    category: 'Clippers & Trimmers',
    difficulty: 'medium',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-5-027',
    chapter_id: 'ch-5',
    front: 'Why should you start with the longest guard and work down?',
    back: 'You can always cut more hair off — you cannot put it back. Starting long prevents mistakes and allows gradual refinement. This is fundamental fade and taper technique.',
    category: 'Clippers & Trimmers',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-5-028',
    chapter_id: 'ch-5',
    front: "If clippers begin pulling or snagging, what should you check?",
    back: "Stop and inspect blade condition, cleanliness, lubrication, and alignment; service or replace the blade as needed instead of assuming one cause.",
    category: "Clippers & Trimmers",
    difficulty: 'medium',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-5-029',
    chapter_id: 'ch-5',
    front: 'What is the T-blade design on trimmers used for?',
    back: 'The T-blade allows for extremely close, clean lines around necklines, beards, and hairlines. The extended blade shape reaches tight corners and creates sharp edge-ups and designs.',
    category: 'Clippers & Trimmers',
    difficulty: 'easy',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-5-030',
    chapter_id: 'ch-5',
    front: "What is the source-book advantage and limitation of cordless clippers?",
    back: "They are convenient and portable, but the source notes that cordless models may have less power than corded models.",
    category: "Clippers & Trimmers",
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 4: STRAIGHT RAZORS (10 cards)
  // ==========================================
  {
    id: 'fc-5-031',
    chapter_id: 'ch-5',
    front: "What are the two straight-razor types in the Chapter 5 source?",
    back: "Changeable-blade razors use replaceable blades; conventional straight razors have a permanent blade that requires honing and stropping.",
    category: "Straight Razors",
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-5-032',
    chapter_id: 'ch-5',
    front: 'What is stropping and how often should it be done?',
    back: 'Stropping refines and aligns a traditional straight-razor edge between honings. Technique and frequency depend on the razor, strop, edge condition, and manufacturer or training guidance.',
    category: 'Straight Razors',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-5-033',
    chapter_id: 'ch-5',
    front: "What is honing a conventional straight razor?",
    back: "Honing uses an abrasive hone to sharpen the cutting edge with controlled, even strokes on both sides of the blade.",
    category: "Straight Razors",
    difficulty: 'medium',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-5-034',
    chapter_id: 'ch-5',
    front: "How does straight-razor holding change by task?",
    back: "The source uses different holding positions for shaving, honing/stropping, haircutting, and palming with a comb.",
    category: "Straight Razors",
    difficulty: 'hard',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-5-035',
    chapter_id: 'ch-5',
    front: "What is the key holding principle when shaving with a straight razor?",
    back: "Control the razor from the shank/tang area with a secure taught grip and maintain deliberate blade control for the shaving procedure.",
    category: "Straight Razors",
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-5-036',
    chapter_id: 'ch-5',
    front: "How should a conventional razor be held for honing or stropping?",
    back: "Control it from the shank so the blade can lie flat against the hone or strop during the taught procedure.",
    category: "Straight Razors",
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-5-037',
    chapter_id: 'ch-5',
    front: 'What is the difference between hollow-ground and wedge grind razors?',
    back: 'Hollow-ground blades have concave faces and are generally more flexible; wedge or near-wedge profiles retain more material and are generally more rigid. Actual shaving feel and suitability depend on the complete blade geometry, edge condition, and user technique.',
    category: 'Straight Razors',
    difficulty: 'hard',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-5-038',
    chapter_id: 'ch-5',
    front: "What safety principle applies across straight-razor use?",
    back: "Maintain deliberate blade control, use the taught hold for the task, and protect the client while handling, shaving, honing, stropping, or transferring the razor.",
    category: "Straight Razors",
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-5-039',
    chapter_id: 'ch-5',
    front: 'What should you do if you drop a straight razor?',
    back: 'STEP BACK and let it fall. NEVER attempt to catch a falling razor. A reflexive grab can cause a severe cut. Let it fall, then pick it up carefully and inspect for damage.',
    category: 'Straight Razors',
    difficulty: 'easy',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-5-040',
    chapter_id: 'ch-5',
    front: "What is crocus finish in the source's razor-quality framework?",
    back: "Crocus finish is a highly polished razor finish. It is one quality factor considered along with balance, temper, grind, size, and style.",
    category: "Straight Razors",
    difficulty: 'hard',
    order_index: 40,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 5: THERMAL TOOLS (8 cards)
  // ==========================================
  {
    id: 'fc-5-041',
    chapter_id: 'ch-5',
    front: 'What is a Marcel iron and how is it controlled?',
    back: 'A manual thermal iron with a rotating handle for precise temperature and winding control. No spring — the barber controls clamp pressure and rotation. Provides infinite control for professional curls and waves.',
    category: 'Thermal Tools',
    difficulty: 'medium',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-5-042',
    chapter_id: 'ch-5',
    front: 'What is the tissue test for thermal tools?',
    back: 'Drag the heated tool across tissue paper before client contact. A clean pass means the tool is ready. Scorching or burning means it is too hot — let it cool and retest.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-5-043',
    chapter_id: 'ch-5',
    front: 'Why should you NEVER use a metal pressing comb directly on the scalp?',
    back: 'Metal on scalp causes serious burns. Always maintain safe distance from skin. The pressing comb is designed to straighten hair sections, not touch the scalp directly.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-5-044',
    chapter_id: 'ch-5',
    front: 'What are the three main blowdryer nozzle types and their uses?',
    back: '1) Concentrator — precision airflow for straightening and detailing. 2) Diffuser — disperses air for textured and curly hair to reduce frizz. 3) Pick — lifts roots and adds volume.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-5-045',
    chapter_id: 'ch-5',
    front: 'Why must you keep thermal tools moving during use?',
    back: 'Stationary heat burns hair and scalp. Keep the tool in constant motion to distribute heat evenly. A burn from a thermal tool can end your career.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-5-046',
    chapter_id: 'ch-5',
    front: 'When should heat-protection products be used with thermal tools?',
    back: 'Use an appropriate heat-protection product when indicated by the service, hair condition, product directions, and thermal-tool guidance. Also select a safe temperature and avoid excessive heat exposure.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-5-047',
    chapter_id: 'ch-5',
    front: "What is the first temperature-control step before thermal-iron manipulation?",
    back: "Establish and verify a safe working temperature before client contact, then maintain controlled movement while keeping the hot tool off the scalp.",
    category: "Thermal Tools",
    difficulty: 'medium',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-5-048',
    chapter_id: 'ch-5',
    front: 'Why should you never use a blowdryer near water?',
    back: 'Electrocution risk. Water and electricity are a deadly combination. Keep blowdryers away from sinks, wet floors, and damp hands. This is basic electrical safety.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 6: STATION & SAFETY (8 cards)
  // ==========================================
  {
    id: 'fc-5-049',
    chapter_id: 'ch-5',
    front: 'How should reusable towels and linens be laundered and stored?',
    back: 'Follow current state rules and laundry-product directions. Use the required wash/dry process, dry linens completely, and store clean linens in a clean, closed or covered location as required. Do not assume one universal wash temperature applies everywhere.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-5-050',
    chapter_id: 'ch-5',
    front: 'What is the purpose of a neck strip?',
    back: 'A neck strip is a barrier placed around the client\'s neck before the cape. It prevents hair from touching the skin and clothing. One client, one strip — dispose after every service.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 50,
    is_active: true,
  },
  {
    id: 'fc-5-051',
    chapter_id: 'ch-5',
    front: 'What is the key safety rule before applying a hot towel to a client?',
    back: 'Use the towel warmer according to its manufacturer instructions and verify the towel is at a safe, comfortable temperature before client contact. Avoid relying on one universal cabinet-temperature rule.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-5-052',
    chapter_id: 'ch-5',
    front: "What is an electric massager used for in Chapter 5 equipment?",
    back: "It is vibrating equipment used for facial, scalp, or shoulder massage where permitted and taught.",
    category: "Station & Safety",
    difficulty: 'medium',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-5-053',
    chapter_id: 'ch-5',
    front: 'What type of disinfectant is required for barbering tools?',
    back: 'Use an EPA-registered disinfectant that is appropriate for the implement and meets current state-board requirements. Follow the product label for organisms, dilution, contact time, compatibility, and safe use.',
    category: 'Station & Safety',
    difficulty: 'medium',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-5-054',
    chapter_id: 'ch-5',
    front: 'How long is the minimum contact time for disinfectant immersion?',
    back: 'Use the full contact time stated on the EPA-registered disinfectant label. Contact time varies by product; keep the implement visibly wet or immersed for the labeled time and follow the manufacturer directions.',
    category: 'Station & Safety',
    difficulty: 'medium',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-5-055',
    chapter_id: 'ch-5',
    front: 'What should you do if a tool falls on the floor during service?',
    back: 'Replace with a clean tool or STOP and fully disinfect before continuing. Tools that touch the floor are contaminated. Never wipe on your apron and reuse. Never use on the next client without full disinfection.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-5-056',
    chapter_id: 'ch-5',
    front: 'What is the proper way to store clean, disinfected tools?',
    back: 'Store in a CLEAN, COVERED container labeled "DISINFECTED." Never store clean tools in open containers where they can be recontaminated. Keep clean and dirty tools physically separated at all times.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 56,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 7: EXAM-RELEVANT REVIEW (8 cards)
  // ==========================================
  {
    id: 'fc-5-057',
    chapter_id: 'ch-5',
    front: 'EXAM-RELEVANT: How should you determine a clipper guard\'s cutting length?',
    back: 'Use the cutting length stated for the specific guard and clipper system. Number-to-length mappings are not universal across all manufacturers, so verify the manufacturer\'s markings or instructions rather than relying on a memorized universal chart.',
    category: 'Exam-Relevant Review',
    difficulty: 'medium',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-5-058',
    chapter_id: 'ch-5',
    front: 'EXAM-RELEVANT: What are the three shear handle types and which reduces RSI risk?',
    back: '1) Opposing — traditional straight design. 2) Offset — thumb hole set back, most ergonomic. 3) Crane — extreme offset with downward angle, maximum ergonomic benefit. Offset and crane reduce repetitive strain injury (RSI) risk.',
    category: 'Exam-Relevant Review',
    difficulty: 'medium',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-5-059',
    chapter_id: 'ch-5',
    front: "How does the Chapter 5 source contrast forged and cast shears?",
    back: "It describes forging as compressed or hammered construction associated with denser, more durable shears, while casting is a different manufacturing method with a more porous structure.",
    category: "Exam-Relevant Review",
    difficulty: 'hard',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-5-060',
    chapter_id: 'ch-5',
    front: 'EXAM-RELEVANT: What are the three types of shears and their primary uses?',
    back: '1) Straight shears — general cutting. 2) Thinning/texturizing shears — remove bulk or create texture. 3) Blending shears — soften or blend transitions. Tooth patterns and cutting effects vary by model.',
    category: 'Exam-Relevant Review',
    difficulty: 'medium',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-5-061',
    chapter_id: 'ch-5',
    front: 'EXAM-RELEVANT: What are the four steps of clipper blade maintenance?',
    back: '1) Remove hair and debris after use. 2) Oil according to manufacturer directions. 3) Between clients, clean and disinfect removable blades/guards as required by current rules and the disinfectant label. 4) If a blade pulls or snags, clean, oil, inspect alignment/condition, and service or replace it as needed.',
    category: 'Exam-Relevant Review',
    difficulty: 'medium',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-5-062',
    chapter_id: 'ch-5',
    front: 'EXAM-RELEVANT: What is the proper straight razor shaving sequence?',
    back: '1) Stretch skin taut. 2) Use minimal pressure — let razor weight do the work. 3) Shave WITH the grain first. 4) Then across the grain. 5) Then against the grain ONLY if needed and skin tolerates it.',
    category: 'Exam-Relevant Review',
    difficulty: 'medium',
    order_index: 62,
    is_active: true,
  },
  {
    id: 'fc-5-063',
    chapter_id: 'ch-5',
    front: "EXAM-RELEVANT: Name the three clipper motor types in the Chapter 5 source.",
    back: "Rotary, pivot, and magnetic.",
    category: "Exam-Relevant Review",
    difficulty: 'medium',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-5-064',
    chapter_id: 'ch-5',
    front: "EXAM-RELEVANT: What equipment categories does Chapter 5 expect a barber to recognize?",
    back: "Barber chair, capes and towels, neck strips, hot-towel equipment, lather equipment, blowdryers, massage equipment, thermal tools, electro/light equipment, and service accessories.",
    category: "Exam-Relevant Review",
    difficulty: 'medium',
    order_index: 64,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 8: SCENARIO CARDS (6 cards)
  // ==========================================
  {
    id: 'fc-5-065',
    chapter_id: 'ch-5',
    front: "SCENARIO: Clippers begin pulling during a service. What is the safest first response?",
    back: "Stop using the tool, protect client comfort, and check blade cleanliness, lubrication, alignment, and condition before resuming with a properly functioning clipper.",
    category: "Scenario Card",
    difficulty: 'medium',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-5-066',
    chapter_id: 'ch-5',
    front: 'SCENARIO: A client wants a skin fade with sharp lines and a beard trim. Which tools are REQUIRED?',
    back: 'Clippers with guards (for the fade), trimmer (for sharp lineup), straight razor (for final edge and neck shave), and comb (for sectioning and clipper-over-comb work). Shears alone cannot create a skin fade.',
    category: 'Scenario Card',
    difficulty: 'medium',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-5-067',
    chapter_id: 'ch-5',
    front: 'SCENARIO: Your Marcel iron starts smoking slightly while prepping for a press-and-curl. What do you do?',
    back: 'Test on tissue paper immediately. Adjust temperature down if needed. Explain to the client briefly and professionally. NEVER use a smoking iron — it is overheating and risks burning hair and scalp.',
    category: 'Scenario Card',
    difficulty: 'medium',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-5-068',
    chapter_id: 'ch-5',
    front: "TRAINING SCENARIO: You switch from shaving to stropping a conventional razor. What changes?",
    back: "The holding method changes: control the razor from the shank so the blade can lie flat and move correctly on the strop.",
    category: "Scenario Card",
    difficulty: 'hard',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-5-069',
    chapter_id: 'ch-5',
    front: 'SCENARIO: A tool falls on the floor during a haircut. Can you wipe it on your apron and continue?',
    back: 'NO. Tools that touch the floor are contaminated. Replace with a clean tool or stop and fully disinfect before continuing. Wiping on an apron does NOT disinfect. Using contaminated tools spreads infection.',
    category: 'Scenario Card',
    difficulty: 'easy',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-5-070',
    chapter_id: 'ch-5',
    front: "SCENARIO: Before using shears, what condition check matters most?",
    back: "Confirm the shears are clean, undamaged, and properly tensioned so the blades move with controlled contact.",
    category: "Scenario Card",
    difficulty: 'medium',
    order_index: 70,
    is_active: true,
  },

  // ==========================================
  // C5 BOOK-ALIGNMENT EXPANSION (20 cards)
  // ==========================================
  {
    id: 'fc-5-071',
    chapter_id: 'ch-5',
    front: "How do graphite, carbon, hard-rubber, and metal combs differ?",
    back: "Graphite is less rigid; carbon is antistatic and heat/chemical resistant; hard rubber is flexible/durable but can deteriorate in disinfectant; metal retains heat and may corrode.",
    category: "Combs & Brushes",
    difficulty: 'hard',
    order_index: 71,
    is_active: true,
  },
  {
    id: 'fc-5-072',
    chapter_id: 'ch-5',
    front: "Which comb best matches each use: tail, wide-tooth, or pick?",
    back: "Tail comb: sectioning/parting; wide-tooth: detangling and product distribution; pick comb: textured or tightly curled hair.",
    category: "Combs & Brushes",
    difficulty: 'medium',
    order_index: 72,
    is_active: true,
  },
  {
    id: 'fc-5-073',
    chapter_id: 'ch-5',
    front: "How do natural and synthetic brush types differ in Chapter 5?",
    back: "Natural bristle brushes polish hair and distribute sebum; synthetic and other designs are selected for specific brushing, detangling, smoothing, volume, or drying needs.",
    category: "Combs & Brushes",
    difficulty: 'medium',
    order_index: 73,
    is_active: true,
  },
  {
    id: 'fc-5-074',
    chapter_id: 'ch-5',
    front: "What is the difference between French- and German-style shears?",
    back: "French style includes a finger rest/tang; German style is described without that tang.",
    category: "Shears & Scissors",
    difficulty: 'medium',
    order_index: 74,
    is_active: true,
  },
  {
    id: 'fc-5-075',
    chapter_id: 'ch-5',
    front: "What are the basic parts of haircutting shears?",
    back: "Moving blade, still blade, points, cutting edges, shanks, bumper, finger grip, thumb grip, tension/pivot screw, and finger rest/tang.",
    category: "Shears & Scissors",
    difficulty: 'hard',
    order_index: 75,
    is_active: true,
  },
  {
    id: 'fc-5-076',
    chapter_id: 'ch-5',
    front: "What finger positions does the source emphasize when holding shears?",
    back: "Ring finger in the finger grip, little finger on the brace, and thumb in the thumb grip without pushing the thumb too deeply through the opening.",
    category: "Shears & Scissors",
    difficulty: 'hard',
    order_index: 76,
    is_active: true,
  },
  {
    id: 'fc-5-077',
    chapter_id: 'ch-5',
    front: "What distinguishes adjustable-blade from detachable-blade clippers?",
    back: "Adjustable clippers use a lever to change blade position; detachable clippers use removable blade units for different cutting lengths.",
    category: "Clippers & Trimmers",
    difficulty: 'hard',
    order_index: 77,
    is_active: true,
  },
  {
    id: 'fc-5-078',
    chapter_id: 'ch-5',
    front: "How should an outliner or trimmer be handled?",
    back: "Use light pressure and controlled movement. Straight or T-shaped blades are used for precision/detail work; cordless models add portability.",
    category: "Clippers & Trimmers",
    difficulty: 'medium',
    order_index: 78,
    is_active: true,
  },
  {
    id: 'fc-5-079',
    chapter_id: 'ch-5',
    front: "What blade materials and close-cutting size example appear in Chapter 5?",
    back: "The source identifies carbon-steel and ceramic blades and includes very close-cutting sizes such as 00000.",
    category: "Clippers & Trimmers",
    difficulty: 'hard',
    order_index: 79,
    is_active: true,
  },
  {
    id: 'fc-5-080',
    chapter_id: 'ch-5',
    front: "What three rules matter when using guards and outliners?",
    back: "Guards extend cutting length; use a free wrist/light hand; do not set outliner blades flush—follow manufacturer guidance.",
    category: "Clippers & Trimmers",
    difficulty: 'hard',
    order_index: 80,
    is_active: true,
  },
  {
    id: 'fc-5-081',
    chapter_id: 'ch-5',
    front: "What are the principal parts of a straight razor?",
    back: "Head, back, shoulder, tang, handle, point, edge, blade, heel, shank, and pivot.",
    category: "Straight Razors",
    difficulty: 'hard',
    order_index: 81,
    is_active: true,
  },
  {
    id: 'fc-5-082',
    chapter_id: 'ch-5',
    front: "How is a razor shaper or hair razor different from a shaving razor?",
    back: "A razor shaper/hair razor is a lightweight cutting tool for texturizing or shaping hair, not the same service purpose as a straight razor used on skin.",
    category: "Straight Razors",
    difficulty: 'medium',
    order_index: 82,
    is_active: true,
  },
  {
    id: 'fc-5-083',
    chapter_id: 'ch-5',
    front: "What six quality factors does the source list for a conventional straight razor?",
    back: "Balance, temper, grind, finish, size, and style. Common blade widths are expressed as fractions such as 5/8 inch or 7/8 inch.",
    category: "Straight Razors",
    difficulty: 'hard',
    order_index: 83,
    is_active: true,
  },
  {
    id: 'fc-5-084',
    chapter_id: 'ch-5',
    front: "What is the source sequence for honing a conventional straight razor?",
    back: "Use even diagonal strokes, work both sides equally, gradually lighten pressure, and finish with the taught edge check.",
    category: "Straight Razors",
    difficulty: 'hard',
    order_index: 84,
    is_active: true,
  },
  {
    id: 'fc-5-085',
    chapter_id: 'ch-5',
    front: "What is the source sequence for stropping a conventional straight razor?",
    back: "Secure the strop, use even diagonal strokes, reverse direction by rolling the razor on its back, work both sides evenly, then perform the taught edge check.",
    category: "Straight Razors",
    difficulty: 'hard',
    order_index: 85,
    is_active: true,
  },
  {
    id: 'fc-5-086',
    chapter_id: 'ch-5',
    front: "What are the service roles of the barber chair, capes, towels, and neck strips?",
    back: "The chair supports positioning; capes protect during services; towels/linens absorb or protect; neck strips form a barrier between the client and cape.",
    category: "Station & Safety",
    difficulty: 'medium',
    order_index: 86,
    is_active: true,
  },
  {
    id: 'fc-5-087',
    chapter_id: 'ch-5',
    front: "What are the roles of a hot-towel cabinet, latherizer, blowdryer, and electric massager?",
    back: "They warm towels, prepare shaving lather, dry/style hair, and provide taught facial/scalp/shoulder massage respectively.",
    category: "Station & Safety",
    difficulty: 'medium',
    order_index: 87,
    is_active: true,
  },
  {
    id: 'fc-5-088',
    chapter_id: 'ch-5',
    front: "What does Chapter 5 say about electro/light equipment and small service accessories?",
    back: "High-frequency and galvanic equipment require training and scope compliance; accessories such as comedone extractors and tweezers must be used only where permitted and taught.",
    category: "Station & Safety",
    difficulty: 'hard',
    order_index: 88,
    is_active: true,
  },
  {
    id: 'fc-5-089',
    chapter_id: 'ch-5',
    front: "How can loose hair clippings be removed safely, and what is the towel-hand-wrap principle?",
    back: "Use a clean folded towel, disposable paper neck strip, or maintained vacuum method; towel wrapping should cover the working hand while preserving control and using clean material.",
    category: "Station & Safety",
    difficulty: 'hard',
    order_index: 89,
    is_active: true,
  },
  {
    id: 'fc-5-090',
    chapter_id: 'ch-5',
    front: "What is the safe sequence for thermal-iron manipulation?",
    back: "Prepare and section the hair, verify heat, control the iron, protect the scalp from contact, and move the tool consistently to create the intended result.",
    category: "Thermal Tools",
    difficulty: 'hard',
    order_index: 90,
    is_active: true,
  },
]

// Stats
export const chapter5FlashcardStats = {
  total: chapter5PremiumFlashcards.length,
  categories: [...new Set(chapter5PremiumFlashcards.map((f) => f.category))],
  byDifficulty: {
    easy: chapter5PremiumFlashcards.filter((f) => f.difficulty === 'easy').length,
    medium: chapter5PremiumFlashcards.filter((f) => f.difficulty === 'medium').length,
    hard: chapter5PremiumFlashcards.filter((f) => f.difficulty === 'hard').length,
  },
}


