// Chapter 4: Infection Control — PREMIUM FLASHCARDS
// Created from immersive safety lab content
// Categories: Pathogens, Disinfection, OSHA, PPE, Blood Exposure, Chemical Safety, State Board

import { Flashcard } from '@/types'

export const chapter4PremiumFlashcards: Flashcard[] = [
  // CATEGORY 1: PATHOGENS & MICROBIOLOGY (8 cards)
  {
    id: 'fc-4-001',
    chapter_id: 'ch-4',
    front: 'What are the four main types of pathogens that can cause infection?',
    back: 'Bacteria, viruses, fungi, and parasites. Each requires different disinfection approaches. Bacteria reproduce by binary fission (splitting in two) and can double every 20 minutes under ideal conditions.',
    category: 'Pathogens & Microbiology',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-4-002',
    chapter_id: 'ch-4',
    front: 'What is MRSA and why is it dangerous in barbering?',
    back: 'MRSA (Methicillin-Resistant Staphylococcus Aureus) is an antibiotic-resistant staph infection. It survives on surfaces for days and can cause life-threatening infections. Killed by proper disinfection — but NOT by sanitizing alone.',
    category: 'Pathogens & Microbiology',
    difficulty: 'medium',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-4-003',
    chapter_id: 'ch-4',
    front: 'How long can Hepatitis B survive outside the body?',
    back: 'Hepatitis B can survive 7+ days outside the body. It is 100x more contagious than HIV. Vaccine is available — GET IT. Transmitted through blood and bodily fluids.',
    category: 'Pathogens & Microbiology',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-4-004',
    chapter_id: 'ch-4',
    front: 'What are bacterial spores and how do you kill them?',
    back: 'Bacterial spores are dormant, protected forms that resist heat, cold, and standard disinfectants. ONLY STERILIZATION kills spores. Standard disinfection is NOT sufficient for spore-forming bacteria like tetanus and tuberculosis.',
    category: 'Pathogens & Microbiology',
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-4-005',
    chapter_id: 'ch-4',
    front: 'What is ringworm (tinea) and how does it spread in barbershops?',
    back: 'Ringworm is a highly contagious fungal infection. Spores survive MONTHS on surfaces. Spreads through direct contact and contaminated tools. Requires fungicidal disinfectant. Standard disinfectants may NOT kill fungal spores.',
    category: 'Pathogens & Microbiology',
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-4-006',
    chapter_id: 'ch-4',
    front: 'What should you do if you discover head lice or scabies on a client?',
    back: 'STOP SERVICE IMMEDIATELY. This is outside your scope of practice — refer to a physician. After discovery: disinfect ALL tools, wash linens in hot water, vacuum the station, and notify the shop manager. NEVER treat parasitic infestations yourself.',
    category: 'Pathogens & Microbiology',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-4-007',
    chapter_id: 'ch-4',
    front: 'Why is Hepatitis C particularly dangerous?',
    back: 'Hepatitis C has no vaccine. It is often asymptomatic for years. Leading cause of liver transplants. Transmitted through blood contact. Can survive on surfaces for days. Many infected people do not know they have it.',
    category: 'Pathogens & Microbiology',
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-4-008',
    chapter_id: 'ch-4',
    front: 'What is the "Universal Precautions" principle?',
    back: 'Treat EVERY client as if they are infectious. You CANNOT tell by looking if someone has HIV, Hep B, or Hep C. Assume EVERY client is infectious and use proper PPE and disinfection for EVERY service.',
    category: 'Pathogens & Microbiology',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },

  // CATEGORY 2: DISINFECTION & STERILIZATION (10 cards)
  {
    id: 'fc-4-009',
    chapter_id: 'ch-4',
    front: 'What is the difference between cleaning, sanitizing, and disinfecting?',
    back: 'CLEANING removes visible debris and dirt. SANITIZING reduces bacteria to safe levels (99.9%). DISINFECTING kills or inactivates pathogens on surfaces and tools. You MUST clean BEFORE disinfecting — disinfectants cannot penetrate organic matter.',
    category: 'Disinfection & Sterilization',
    difficulty: 'easy',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-4-010',
    chapter_id: 'ch-4',
    front: 'What are the 8 steps of the disinfection protocol?',
    back: '1. REMOVE debris, 2. WASH with soap and water, 3. RINSE thoroughly, 4. DRY completely, 5. IMMERSE in EPA-registered disinfectant, 6. WAIT the full contact time (typically 10 minutes), 7. REMOVE with gloves/tongs, 8. STORE in clean, covered container labeled "DISINFECTED".',
    category: 'Disinfection & Sterilization',
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-4-011',
    chapter_id: 'ch-4',
    front: 'Why is contact time critical when disinfecting tools?',
    back: 'At 5 minutes, you kill roughly 50% of pathogens. At 10 minutes, you kill 99.9%. That 5-minute difference is the difference between safety and an outbreak. Most barbers rush this step — SET A TIMER. EVERY TIME.',
    category: 'Disinfection & Sterilization',
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-4-012',
    chapter_id: 'ch-4',
    front: 'What type of disinfectant is required for barbering tools?',
    back: 'EPA-registered hospital-grade disinfectant. Must be proven effective against bacteria, viruses, AND fungi. Check the EPA registration number on the label. Never use household bleach or unregistered products on tools.',
    category: 'Disinfection & Sterilization',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-4-013',
    chapter_id: 'ch-4',
    front: 'What is an autoclave and when is it used?',
    back: 'An autoclave is a sterilization device that uses steam under pressure to kill ALL microorganisms including bacterial spores. Required for tools that penetrate skin (razors, needles). Standard disinfection is NOT sufficient for invasive tools.',
    category: 'Disinfection & Sterilization',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-4-014',
    chapter_id: 'ch-4',
    front: 'How should you store clean, disinfected tools?',
    back: 'Store in a CLEAN, COVERED container labeled "DISINFECTED." Never store clean tools in open containers where they can be recontaminated by airborne particles or contact. Keep clean and dirty tools physically separated.',
    category: 'Disinfection & Sterilization',
    difficulty: 'easy',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-4-015',
    chapter_id: 'ch-4',
    front: 'What should you do if disinfectant solution becomes visibly dirty?',
    back: 'REPLACE IT IMMEDIATELY. Dirty disinfectant is ineffective. Follow manufacturer guidelines for replacement schedule. Never add fresh disinfectant to old solution — this dilutes concentration and reduces effectiveness.',
    category: 'Disinfection & Sterilization',
    difficulty: 'easy',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-4-016',
    chapter_id: 'ch-4',
    front: 'Why must you clean tools BEFORE disinfecting them?',
    back: 'Disinfectants cannot penetrate dirt, hair, oils, and organic matter. If you skip cleaning, the disinfectant sits on top of debris and never reaches the pathogens underneath. CLEANING must happen BEFORE disinfecting — every time.',
    category: 'Disinfection & Sterilization',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-4-017',
    chapter_id: 'ch-4',
    front: 'How should you handle tools that fall on the floor during service?',
    back: 'Replace with clean tools or STOP and fully disinfect before continuing. Tools that touch the floor are contaminated. Never wipe on apron and reuse. Never use on next client without full disinfection protocol.',
    category: 'Disinfection & Sterilization',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-4-018',
    chapter_id: 'ch-4',
    front: 'What is the proper way to dispose of single-use items?',
    back: 'Discard after EVERY client. Single-use items include neck strips, cape tissues, some gloves, and disposable blades. Never reuse single-use items — even if they "look clean." Place in lined trash bin.',
    category: 'Disinfection & Sterilization',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },

  // CATEGORY 3: OSHA & REGULATIONS (8 cards)
  {
    id: 'fc-4-019',
    chapter_id: 'ch-4',
    front: 'What does OSHA stand for and what do they regulate?',
    back: 'OSHA = Occupational Safety and Health Administration. Federal agency that sets and enforces workplace safety standards. In barbering: exposure control plans, PPE, Hep B vaccine, sharps disposal, chemical safety, and training requirements.',
    category: 'OSHA & Regulations',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-4-020',
    chapter_id: 'ch-4',
    front: 'What must an Exposure Control Plan include?',
    back: 'Job classifications with exposure risk, procedures for different tasks, schedule for PPE and training, method of compliance evaluation, Hep B vaccine procedures, post-exposure follow-up, and record-keeping. OSHA inspectors ask for this FIRST.',
    category: 'OSHA & Regulations',
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-4-021',
    chapter_id: 'ch-4',
    front: 'When must employers offer the Hepatitis B vaccine?',
    back: 'Employers MUST offer the Hep B vaccine series (3 shots over 6 months) to all employees with potential exposure. Must be offered WITHIN 10 DAYS of assignment. Employees can decline but must sign a waiver.',
    category: 'OSHA & Regulations',
    difficulty: 'medium',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-4-022',
    chapter_id: 'ch-4',
    front: 'What are the requirements for sharps disposal containers?',
    back: 'Must be: puncture-resistant, upright, easily accessible, labeled with biohazard symbol, replaced at 3/4 full (never overfilled), and disposed of per local regulations. Never throw loose blades in regular trash.',
    category: 'OSHA & Regulations',
    difficulty: 'easy',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-4-023',
    chapter_id: 'ch-4',
    front: 'How many sections are in a Safety Data Sheet (SDS)?',
    back: '16 sections. Board exam alert: This is the most common SDS question. Sections include: Identification, Hazard Classification, Composition, First Aid, Firefighting, Accidental Release, Handling & Storage, Exposure Controls, Physical Properties, Stability, Toxicology, Ecology, Disposal, Transport, Regulations, and Other Information.',
    category: 'OSHA & Regulations',
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-4-024',
    chapter_id: 'ch-4',
    front: 'What are GHS pictograms and why are they important?',
    back: 'GHS (Globally Harmonized System) pictograms are hazard symbols on chemical containers. They identify dangers at a glance: flame (flammable), skull (toxic), exclamation mark (irritant), corrosion (burns), health hazard (cancer), gas cylinder (explosive), oxidizer (intensifies fire), environment (aquatic toxicity). NEVER remove or cover GHS labels.',
    category: 'OSHA & Regulations',
    difficulty: 'medium',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-4-025',
    chapter_id: 'ch-4',
    front: 'What is the difference between an SDS and an MSDS?',
    back: 'MSDS (Material Safety Data Sheet) was the old format. SDS (Safety Data Sheet) is the current format under GHS with 16 standardized sections. If you see "MSDS" on old documents, it refers to the same information in an older format.',
    category: 'OSHA & Regulations',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-4-026',
    chapter_id: 'ch-4',
    front: 'What are an employer\'s obligations regarding PPE?',
    back: 'Employers MUST provide: gloves, eye protection, gowns/aprons at NO COST to employees. PPE must be appropriate for the task, properly sized, and readily accessible. Never make employees buy their own safety equipment.',
    category: 'OSHA & Regulations',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },

  // CATEGORY 4: PPE & SAFETY EQUIPMENT (6 cards)
  {
    id: 'fc-4-027',
    chapter_id: 'ch-4',
    front: 'What PPE should barbers wear and when?',
    back: 'Gloves when handling chemicals, cleaning disinfectants, or potential blood contact. Eye protection for high-risk services. Apron/gown for blood exposure situations. Gloves must be changed between clients and when torn or contaminated.',
    category: 'PPE & Safety Equipment',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-4-028',
    chapter_id: 'ch-4',
    front: 'What is the proper handwashing technique for barbers?',
    back: 'Wet hands, apply liquid soap, lather and scrub ALL surfaces for at least 20 seconds (sing "Happy Birthday" twice), rinse thoroughly, dry with clean paper towel, use paper towel to turn off faucet and open door. Hand sanitizer is NOT a substitute for handwashing.',
    category: 'PPE & Safety Equipment',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-4-029',
    chapter_id: 'ch-4',
    front: 'What is the proper way to remove contaminated gloves?',
    back: 'Remove one glove by pinching at the wrist (outside), peel away from hand turning glove inside out. Hold removed glove in gloved hand. Slide fingers of bare hand under remaining glove at wrist, peel off turning inside out over first glove. Dispose immediately. Never touch outside of gloves with bare skin.',
    category: 'PPE & Safety Equipment',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-4-030',
    chapter_id: 'ch-4',
    front: 'What should be on your PPE mastery checklist before every client?',
    back: 'Fresh disposable gloves, clean cape and neck strip, all tools cleaned and disinfected from previous client, disinfectant solution is CLEAR and FRESH, sharps container accessible and not overfilled, hand washing station stocked, trash bin empty with fresh liner, first aid kit accessible, eye protection available, apron/gown available for blood exposure.',
    category: 'PPE & Safety Equipment',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-4-031',
    chapter_id: 'ch-4',
    front: 'When should you change gloves during a service?',
    back: 'Change gloves: between EVERY client, when gloves are torn or punctured, when gloves become visibly contaminated, when switching from dirty to clean tasks, after handling chemicals, after touching face or hair. Never wash and reuse disposable gloves.',
    category: 'PPE & Safety Equipment',
    difficulty: 'easy',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-4-032',
    chapter_id: 'ch-4',
    front: 'Why is hand sanitizer NOT a substitute for handwashing?',
    back: 'Hand sanitizer kills some germs but does NOT remove dirt, oils, hair, or organic matter. It is less effective against certain pathogens including C. difficile spores and some viruses. Handwashing with soap and water physically removes debris AND kills pathogens. Always wash hands — use sanitizer only when soap and water are unavailable.',
    category: 'PPE & Safety Equipment',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },

  // CATEGORY 5: BLOOD EXPOSURE & EMERGENCY (6 cards)
  {
    id: 'fc-4-033',
    chapter_id: 'ch-4',
    front: 'What is the FIRST thing you should do after accidentally cutting a client?',
    back: 'STOP SERVICE IMMEDIATELY. Apply pressure with clean gauze or cotton. Put on fresh gloves. Clean the wound with antiseptic. Apply bandage. Clean and disinfect everything the blood touched. Document the incident in exposure log. NEVER continue service after blood exposure.',
    category: 'Blood Exposure & Emergency',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-4-034',
    chapter_id: 'ch-4',
    front: 'What is the proper response to a blood spill on your station?',
    back: '1. Put on gloves and eye protection, 2. Cover spill with absorbent material, 3. Spray with EPA-registered disinfectant, 4. Wait 10 minutes contact time, 5. Wipe up with disposable towels, 6. Dispose of towels in biohazard bag, 7. Disinfect the area again, 8. Remove PPE and wash hands thoroughly, 9. Document the incident.',
    category: 'Blood Exposure & Emergency',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-4-035',
    chapter_id: 'ch-4',
    front: 'What should you do BEFORE removing gloves after an exposure incident?',
    back: 'Clean and disinfect ALL tools that came into contact with blood BEFORE removing gloves. This prevents spreading bloodborne pathogens to your bare hands when you remove gloves. After tools are disinfected, remove gloves properly and wash hands thoroughly.',
    category: 'Blood Exposure & Emergency',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-4-036',
    chapter_id: 'ch-4',
    front: 'How do you stop bleeding from a minor cut on a client?',
    back: 'Apply SLIGHT PRESSURE with a clean, moistened cotton round or gauze pad. Hold for 1-2 minutes until bleeding stops. Apply antiseptic and bandage if needed. For severe bleeding or deep cuts, seek medical attention. Never use hair products or chemicals on an open wound.',
    category: 'Blood Exposure & Emergency',
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-4-037',
    chapter_id: 'ch-4',
    front: 'What information must be documented after an exposure incident?',
    back: 'Date and time of incident, description of what happened, name of exposed individual, route of exposure (cut, splash, etc.), source of exposure if known, actions taken immediately, follow-up procedures, signatures of involved parties. OSHA requires this documentation for 30 years.',
    category: 'Blood Exposure & Emergency',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-4-038',
    chapter_id: 'ch-4',
    front: 'When should you refuse service to a client due to health concerns?',
    back: 'Refuse service for: suspected contagious conditions (ringworm, impetigo, active herpes, lice, scabies), open wounds or sores on scalp/face, severe skin infections, unexplained rashes with pus or drainage. POLITELY explain you cannot proceed, refer to a physician, and DOCUMENT the refusal. Waivers do NOT protect you from negligence.',
    category: 'Blood Exposure & Emergency',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },

  // CATEGORY 6: CHEMICAL SAFETY (6 cards)
  {
    id: 'fc-4-039',
    chapter_id: 'ch-4',
    front: 'What happens when you mix bleach with ammonia?',
    back: 'Produces CHLORAMINE GAS — causes chest pain, coughing, fluid in lungs, and potentially DEATH. Common in cleaning products. IF MIXED: evacuate immediately, ventilate area, call Poison Control: 1-800-222-1222. NEVER mix bleach with ammonia or acids.',
    category: 'Chemical Safety',
    difficulty: 'easy',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-4-040',
    chapter_id: 'ch-4',
    front: 'What are the most dangerous chemical combinations to avoid?',
    back: 'BLEACH + AMMONIA = chloramine gas (deadly). BLEACH + ACIDS = chlorine gas (deadly). HYDROGEN PEROXIDE + VINEGAR = peracetic acid (corrosive). RUBBING ALCOHOL + BLEACH = chloroform and toxic compounds (liver/kidney damage). When in doubt, do NOT mix. Use one product at a time.',
    category: 'Chemical Safety',
    difficulty: 'medium',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-4-041',
    chapter_id: 'ch-4',
    front: 'What is the maximum safe water temperature for shampooing?',
    back: '130°F (54°C). Water above 130°F can cause serious burns. Always test water temperature before applying to client\'s scalp. Use a thermometer or test on your inner wrist — if it feels hot to you, it is too hot for the client.',
    category: 'Chemical Safety',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-4-042',
    chapter_id: 'ch-4',
    front: 'What type of electrical outlets should be near water sources?',
    back: 'GFCI (Ground Fault Circuit Interrupter) outlets. GFCI outlets shut off power instantly if they detect a ground fault, preventing electrocution near water. Required by electrical code near sinks, shampoo bowls, and any water source. Test monthly using the TEST and RESET buttons.',
    category: 'Chemical Safety',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-4-043',
    chapter_id: 'ch-4',
    front: 'What should you wear when handling caustic materials?',
    back: 'Full PPE: goggles, lab apron, and chemical-resistant gloves. Caustic materials can burn skin and eyes. Never handle strong chemicals with bare hands or regular clothing. Have an eyewash station accessible and know its location.',
    category: 'Chemical Safety',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-4-044',
    chapter_id: 'ch-4',
    front: 'How should you dispose of leftover chemicals?',
    back: 'Dispose according to manufacturer instructions and local regulations. NEVER pour chemicals down drains, into regular trash, or mix them together. Some chemicals require hazardous waste disposal. Contact local waste management for guidance. Never stockpile unused chemicals.',
    category: 'Chemical Safety',
    difficulty: 'easy',
    order_index: 44,
    is_active: true,
  },

  // CATEGORY 7: STATE BOARD & INSPECTION (6 cards)
  {
    id: 'fc-4-045',
    chapter_id: 'ch-4',
    front: 'What are the 10 most critical concepts for the state board exam on infection control?',
    back: '1. Clean BEFORE disinfecting. 2. Contact time is 10 minutes. 3. Spores require STERILIZATION. 4. OSHA requires Exposure Control Plan, Hep B vaccine, PPE, sharps disposal, annual training. 5. Treat EVERY client as infectious. 6. Use ONLY EPA-registered disinfectants. 7. SDS has 16 sections. 8. Refuse service for contagious conditions — document it. 9. Never mix bleach with ammonia or acids. 10. GFCI outlets required near water; max water temp 130°F.',
    category: 'State Board & Inspection',
    difficulty: 'medium',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-4-046',
    chapter_id: 'ch-4',
    front: 'What will a state board inspector look for first?',
    back: '1. Valid licenses displayed. 2. Cleanliness of shop and stations. 3. Proper disinfection of tools. 4. Fresh disinfectant solution. 5. Sharps disposal container. 6. SDS binder accessible. 7. PPE available. 8. Hand washing station stocked. 9. Clean towels and capes. 10. Proper tool storage. Fail any of these = citation or closure.',
    category: 'State Board & Inspection',
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-4-047',
    chapter_id: 'ch-4',
    front: 'What is cross-contamination and how do you prevent it?',
    back: 'Cross-contamination is transfer of pathogens from one person, object, or surface to another. Prevention: disinfect tools between EVERY client, use clean towels and capes, never place clean tools on contaminated surfaces, wash hands between clients, store clean and dirty items separately, disinfect work surfaces between clients.',
    category: 'State Board & Inspection',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-4-048',
    chapter_id: 'ch-4',
    front: 'Why is proper ventilation important in a barbershop?',
    back: 'Proper ventilation removes chemical fumes, dust, and airborne particles that can cause respiratory issues and allergic reactions. Required for health and safety. Prevents buildup of disinfectant vapors, hair product chemicals, and airborne pathogens. Essential for both client and barber health.',
    category: 'State Board & Inspection',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-4-049',
    chapter_id: 'ch-4',
    front: 'What should you check for on plastic chemical bottles?',
    back: 'Check for DENTS or BULGES that indicate pressure buildup or chemical degradation. These can lead to leaks or explosions. Also check expiration dates, proper labeling, and GHS pictograms. Damaged or expired chemicals must be disposed of properly.',
    category: 'State Board & Inspection',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-4-050',
    chapter_id: 'ch-4',
    front: 'What documentation protects you if a client claims they got an infection at your shop?',
    back: 'Document EVERYTHING: disinfection logs with dates/times, PPE usage, refusal of service for contagious conditions, exposure incidents, training certificates, SDS records, and disinfectant purchase/usage records. Good documentation is your best defense against false claims and negligence lawsuits.',
    category: 'State Board & Inspection',
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },
]

// Stats
export const chapter4FlashcardStats = {
  total: chapter4PremiumFlashcards.length,
  categories: [...new Set(chapter4PremiumFlashcards.map((f) => f.category))],
  byDifficulty: {
    easy: chapter4PremiumFlashcards.filter((f) => f.difficulty === 'easy').length,
    medium: chapter4PremiumFlashcards.filter((f) => f.difficulty === 'medium').length,
    hard: chapter4PremiumFlashcards.filter((f) => f.difficulty === 'hard').length,
  },
}

console.log(`Chapter 4 Premium Flashcards: ${chapter4FlashcardStats.total} cards created`)
console.log(`Categories: ${chapter4FlashcardStats.categories.join(', ')}`)
console.log(`Difficulty: ${chapter4FlashcardStats.byDifficulty.easy} easy, ${chapter4FlashcardStats.byDifficulty.medium} medium, ${chapter4FlashcardStats.byDifficulty.hard} hard`)
