import { QuizQuestion } from '@/types'

// Chapter 18: Haircoloring and Lightening — 15 premium quiz questions
export const chapter18PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-18-01',
    standardId: 'CH18-Q01',
    quiz_id: 'quiz-18',
    question: "Which group of observations gives the strongest foundation for planning a haircolor or lightening service?",
    answer_a: "Length, haircut shape, styling preference, and product fragrance",
    answer_b: "Hair integrity/elasticity, texture, density, porosity, natural level/tone, and contributing pigment",
    answer_c: "Only the client’s desired shade and the formula used at the last visit",
    answer_d: "Only scalp oiliness and the amount of gray hair",
    correct_answer: 'b',
    explanation: "Haircolor planning should start with a broad hair and scalp analysis. Integrity/elasticity, texture, density, porosity, natural level/tone, and contributing pigment all influence service planning. No single trait should automatically determine developer strength or processing time; the product system and hair condition still control those choices.",
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-18-02',
    standardId: 'CH18-Q02',
    quiz_id: 'quiz-18',
    question: "Which natural pigment is associated mainly with brown-to-black hair color?",
    answer_a: "Pheomelanin",
    answer_b: "Eumelanin",
    answer_c: "Keratin",
    answer_d: "Melatonin",
    correct_answer: 'b',
    explanation: "Eumelanin is associated mainly with brown-to-black natural pigment, while pheomelanin contributes red-to-yellow pigment. Understanding the natural pigment helps the professional anticipate underlying warmth as hair is lightened.",
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-18-03',
    standardId: 'CH18-Q03',
    quiz_id: 'quiz-18',
    question: "Which statement about professional haircolor level systems is most accurate?",
    answer_a: "Every manufacturer must use exactly 1 for black and 10 for the lightest blond",
    answer_b: "Level describes how light or dark a color is, but exact numbering and shade names can vary by manufacturer",
    answer_c: "Level describes only whether a tone is warm or cool",
    answer_d: "Level numbers are interchangeable with developer volumes",
    correct_answer: 'b',
    explanation: "Level describes relative lightness or darkness. Many professional lines use numbered scales, but the exact numbering, endpoints, and shade names can vary. Use the specific manufacturer’s swatch book or technical chart rather than treating one numbering system as universal.",
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-18-04',
    standardId: 'CH18-Q04',
    quiz_id: 'quiz-18',
    question: "Which description best fits temporary haircolor as a product category?",
    answer_a: "A short-duration color effect that primarily deposits color near the hair surface, with longevity that varies by formula and hair condition",
    answer_b: "A permanent oxidative system that always lifts natural pigment",
    answer_c: "A lightener that removes natural melanin before a toner is applied",
    answer_d: "A demipermanent system that must always be mixed with 20-volume developer",
    correct_answer: 'a',
    explanation: "Temporary haircolor is intended for short-duration color effects and generally deposits color near the hair surface. How quickly it shampoos out depends on the specific product, hair condition, and use, so a universal one-shampoo rule should not be promised.",
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-18-05',
    standardId: 'CH18-Q05',
    quiz_id: 'quiz-18',
    question: "Which principle should guide developer selection for a permanent color or lightener service?",
    answer_a: "Use 20-volume for every permanent color and every gray-coverage service",
    answer_b: "Use the highest volume available whenever more lift is desired",
    answer_c: "Use only the developer strengths and mixing ratios permitted by the specific product system, because lift and gray-coverage capability are system-dependent",
    answer_d: "Choose developer strength from hair texture alone",
    correct_answer: 'c',
    explanation: "Developer volume expresses peroxide strength, but the amount of lift, gray-coverage use, mixing ratio, scalp/off-scalp limits, and timing depend on the complete color or lightener system. Professional manufacturer instructions therefore control developer selection.",
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-18-06',
    standardId: 'CH18-Q06',
    quiz_id: 'quiz-18',
    question: "A client has unwanted orange warmth at a level where blue is the appropriate complementary relationship. Which tonal direction is used to reduce the orange?",
    answer_a: "Gold",
    answer_b: "Red-orange",
    answer_c: "Blue",
    answer_d: "Yellow",
    correct_answer: 'c',
    explanation: "Complementary color relationships are used to reduce unwanted tonal influence. Blue is complementary to orange in traditional haircolor theory. The final formula still has to match the client’s level, underlying pigment, target tone, and the professional color system being used.",
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-18-07',
    standardId: 'CH18-Q07',
    quiz_id: 'quiz-18',
    question: "Very porous lengths are expected to take color differently from the less-porous regrowth. What is the most appropriate planning step before choosing a darker formula?",
    answer_a: "Automatically choose a formula one to two levels lighter for every porous client",
    answer_b: "Use a stronger developer so all areas absorb color equally",
    answer_c: "Assess the porosity difference, use a strand test when appropriate, and follow the color system’s porosity/equalization guidance",
    answer_d: "Ignore porosity because it does not affect color uptake",
    correct_answer: 'c',
    explanation: "Porous hair can take up color unevenly, but there is no universal rule to compensate by automatically choosing a fixed number of levels lighter or by increasing developer strength. Analyze the hair, use a strand test when appropriate, and use the manufacturer-supported porosity or equalization strategy.",
    difficulty: 'medium',
    order_index: 7,
  },
  {
    id: 'qq-18-08',
    standardId: 'CH18-Q08',
    quiz_id: 'quiz-18',
    question: "A client wants maximum gray coverage and durability. Which product-selection approach is most appropriate?",
    answer_a: "Choose any temporary rinse because all temporary colors fully cover gray",
    answer_b: "Choose any demipermanent color because all demipermanent products provide complete gray coverage",
    answer_c: "Choose a permanent or other color system that specifically states it is designed for the desired gray-coverage result, and follow that system’s formulation guidance",
    answer_d: "Select developer volume alone and ignore the color line’s gray-coverage directions",
    correct_answer: 'c',
    explanation: "Gray-coverage capability varies by product line and formula. Permanent color is commonly used for durable gray coverage, but the professional should rely on the manufacturer’s stated gray-coverage capability, shade family, developer, ratio, and timing rather than a fixed percentage rule.",
    difficulty: 'medium',
    order_index: 8,
  },
  {
    id: 'qq-18-09',
    standardId: 'CH18-Q09',
    quiz_id: 'quiz-18',
    question: "During a lightener retouch, what is the safest general placement principle?",
    answer_a: "Apply lightener from scalp to ends on every retouch",
    answer_b: "Target the new growth and avoid unapproved overlap onto previously lightened or sensitized hair",
    answer_c: "Pull lightener through all previously lightened lengths during the final minutes",
    answer_d: "Apply only to the ends because regrowth lifts on its own",
    correct_answer: 'b',
    explanation: "Previously lightened hair can be more vulnerable to damage. A retouch generally targets new growth while avoiding unapproved overlap onto previously lightened or sensitized hair. The specific product’s overlap, scalp, developer, and timing directions remain controlling.",
    difficulty: 'medium',
    order_index: 9,
  },
  {
    id: 'qq-18-10',
    standardId: 'CH18-Q10',
    quiz_id: 'quiz-18',
    question: "A service plan intentionally lightens the hair first and then applies a separate toner or color to refine the final tone. What is this two-step structure called?",
    answer_a: "Single-process haircoloring",
    answer_b: "Double-process haircoloring",
    answer_c: "Temporary color application",
    answer_d: "Retouch-only color",
    correct_answer: 'b',
    explanation: "Double-process haircoloring uses a separate lightening step followed by a separate toning or color step. Whether that approach is suitable for a particular client depends on the target result, starting level, hair integrity, and the product systems being used.",
    difficulty: 'medium',
    order_index: 10,
  },
  {
    id: 'qq-18-11',
    standardId: 'CH18-Q11',
    quiz_id: 'quiz-18',
    question: "What most clearly distinguishes many demipermanent systems from many semipermanent/direct-dye systems?",
    answer_a: "Demipermanent color is used only on pre-lightened hair",
    answer_b: "Demipermanent color commonly uses oxidative chemistry with a dedicated low-strength developer or activator",
    answer_c: "Demipermanent color always lifts natural pigment several levels",
    answer_d: "Demipermanent color never requires an allergy-alert or skin-test procedure",
    correct_answer: 'b',
    explanation: "Many demipermanent systems use oxidative dye chemistry with a dedicated low-strength developer or activator, while many semipermanent products are direct-dye deposit systems used without oxidative developer. Exact chemistry, testing, longevity, and use still depend on the specific product.",
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-18-12',
    standardId: 'CH18-Q12',
    quiz_id: 'quiz-18',
    question: "Which statement best reflects current FDA guidance and federal hair-dye requirements about allergy/skin testing?",
    answer_a: "Federal law creates one universal 24–48-hour timing rule for every haircolor product",
    answer_b: "A skin test is unnecessary if the client has used the same color before",
    answer_c: "Follow the product’s exact allergy-alert or skin-test directions; FDA advises a skin test before each hair-dye use, while qualifying coal-tar hair dyes have specific caution-label and preliminary-test requirements",
    answer_d: "Only permanent color products can cause allergic reactions",
    correct_answer: 'c',
    explanation: "FDA advises users and salons to perform a skin test before each hair-dye use and to follow package directions. Federal law separately gives qualifying coal-tar hair dyes special treatment when required caution labeling and adequate preliminary-test directions are provided. Do not replace those product-specific directions with one invented universal timing rule.",
    difficulty: 'hard',
    order_index: 12,
  },
  {
    id: 'qq-18-13',
    standardId: 'CH18-Q13',
    quiz_id: 'quiz-18',
    question: "Which rule should govern coloring a client’s beard or mustache?",
    answer_a: "Any scalp haircolor is acceptable if petroleum jelly is applied first",
    answer_b: "Any off-scalp powder lightener is acceptable on facial hair",
    answer_c: "Use only a product whose manufacturer expressly permits the intended beard or mustache application, and follow its allergy-alert, skin, timing, rinsing, and eye-area precautions",
    answer_d: "Metallic or progressive dyes are always the safest facial-hair option",
    correct_answer: 'c',
    explanation: "Do not transfer scalp-hair directions to facial hair by assumption. A beard or mustache color service should use a product expressly permitted for that intended facial-hair application and should follow that product’s warnings and application procedure exactly.",
    difficulty: 'hard',
    order_index: 13,
  },
  {
    id: 'qq-18-14',
    standardId: 'CH18-Q14',
    quiz_id: 'quiz-18',
    question: "A developer or color-product container appears damaged, swollen, leaking, or otherwise compromised. What is the appropriate action?",
    answer_a: "Open it carefully and use it immediately so the product is not wasted",
    answer_b: "Transfer the product to an unlabeled metal container",
    answer_c: "Do not use the compromised product; secure it and follow the manufacturer or workplace safety directions for handling and disposal",
    answer_d: "Add water to reduce the product strength before use",
    correct_answer: 'c',
    explanation: "Damaged or compromised chemical packaging should not be treated as usable product. Do not open, transfer, dilute, or improvise with it. Follow the manufacturer’s storage, handling, and disposal instructions and the workplace’s chemical-safety procedures.",
    difficulty: 'hard',
    order_index: 14,
  },
  {
    id: 'qq-18-15',
    standardId: 'CH18-Q15',
    quiz_id: 'quiz-18',
    question: "Previously lightened, highly porous lengths are being tinted back darker and are likely to take color differently from the regrowth. What is the best first planning step?",
    answer_a: "Automatically apply 40-volume developer to the porous lengths",
    answer_b: "Ignore the porosity difference and apply one formula everywhere",
    answer_c: "Assess the hair, use a strand test when appropriate, and choose a manufacturer-supported tint-back, filler, or equalization strategy for the target result",
    answer_d: "Skip allergy-alert testing because the hair has already been chemically processed",
    correct_answer: 'c',
    explanation: "Tint-back work on porous hair may require replacement of missing underlying tone, a filler, or another equalization strategy, but there is no single universal formula. Analyze the hair, consider a strand test, and use the product system’s supported tint-back or filler guidance.",
    difficulty: 'hard',
    order_index: 15,
  },
]