// Chapter 8 Premium Quiz — Hardened Assessment
// 30 questions, original ASCYN PRO wording
// C8-5 target: 3 easy / 12 medium / 15 hard
// Emphasis: application, scenario reasoning, client protection, device/scope boundaries

import { QuizQuestion } from '@/types'

const strategy =
  'Strategy: Read carefully, identify the keyword, eliminate wrong answers, apply safety/procedure logic, then choose the best remaining answer.'

export const chapter8PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-8-001',
    quiz_id: 'quiz-8',
    question: 'Electricity is classified as energy rather than matter. What does this mean?',
    answer_a: 'It does not occupy space or have mass',
    answer_b: 'It cannot be measured or controlled',
    answer_c: 'It only works in complete darkness',
    answer_d: 'It requires a vacuum to function',
    correct_answer: 'a',
    explanation: `Electricity is treated as energy rather than matter because it does not occupy space or have mass. ${strategy}`,
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-8-002',
    quiz_id: 'quiz-8',
    question: 'A barber is deciding which object creates the greatest electrical-conduction concern near a powered tool. Which choice should receive the MOST caution?',
    answer_a: 'A dry plastic comb on a dry counter',
    answer_b: 'A metal clip resting beside a wet towel',
    answer_c: 'A dry rubber mat under a chair',
    answer_d: 'A glass jar stored away from the station',
    correct_answer: 'b',
    explanation: `Metal readily conducts electricity, and nearby moisture increases the hazard context. The other choices are comparatively poor conductors in the stated dry conditions. ${strategy}`,
    difficulty: 'medium',
    order_index: 2,
  },
  {
    id: 'qq-8-003',
    quiz_id: 'quiz-8',
    question: 'A clipper stops running immediately after its internal switch opens the circuit. Which explanation BEST describes why current stopped?',
    answer_a: 'The open circuit interrupted the complete path needed for current flow',
    answer_b: 'The open circuit doubled resistance until voltage disappeared',
    answer_c: 'The open circuit converted alternating current into direct current',
    answer_d: 'The open circuit increased wattage beyond the tool rating',
    correct_answer: 'a',
    explanation: `Current requires a complete path. Opening the circuit breaks that path, so current cannot continue through the intended circuit. ${strategy}`,
    difficulty: 'hard',
    order_index: 3,
  },
  {
    id: 'qq-8-004',
    quiz_id: 'quiz-8',
    question: 'Direct current (DC) flows in how many directions?',
    answer_a: 'Two directions, alternating',
    answer_b: 'One direction only',
    answer_c: 'Three directions simultaneously',
    answer_d: 'No direction because it is static',
    correct_answer: 'b',
    explanation: `Direct current flows in one direction. Batteries are a common source of DC. ${strategy}`,
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-8-005',
    quiz_id: 'quiz-8',
    question: 'A cordless clipper battery requires DC, but the charging cord connects to an AC wall supply. Which component function is MOST directly required for charging?',
    answer_a: 'A rectifying function that changes AC into DC',
    answer_b: 'A grounding function that changes DC into AC',
    answer_c: 'A fuse that changes voltage into resistance',
    answer_d: 'A rheostat that stores AC inside the battery',
    correct_answer: 'a',
    explanation: `Charging a DC battery from an AC supply requires AC-to-DC conversion, which is the rectifying function. A converter is classically DC-to-AC in the source terminology. ${strategy}`,
    difficulty: 'hard',
    order_index: 5,
  },
  {
    id: 'qq-8-006',
    quiz_id: 'quiz-8',
    question: 'A barber reads the voltage rating on a new electrical tool before plugging it in. What is the BEST reason for checking that rating?',
    answer_a: 'To confirm the tool is compatible with the available electrical supply',
    answer_b: 'To determine whether the tool is automatically grounded',
    answer_c: 'To calculate how often the tool must be disinfected',
    answer_d: 'To determine whether the tool produces direct or alternating current internally',
    correct_answer: 'a',
    explanation: `Voltage describes electrical potential or pressure. Matching the tool rating to the available supply is the relevant equipment-use decision. ${strategy}`,
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-8-007',
    quiz_id: 'quiz-8',
    question: 'A tool is rated at 1,200 watts and 120 volts. Approximately how much current does it draw?',
    answer_a: '5 amps',
    answer_b: '10 amps',
    answer_c: '12 amps',
    answer_d: '100 amps',
    correct_answer: 'b',
    explanation: `Use amps = watts ÷ volts: 1,200 ÷ 120 = 10 amps. The calculation describes equipment demand, not a universal statement about circuit capacity. ${strategy}`,
    difficulty: 'medium',
    order_index: 7,
  },
  {
    id: 'qq-8-008',
    quiz_id: 'quiz-8',
    question: 'A 1,800-watt dryer is connected to a 120-volt supply. What is the MOST accurate conclusion?',
    answer_a: 'It draws about 15 amps, but safe loading still depends on the actual circuit and other connected equipment',
    answer_b: 'It draws about 15 amps, so any 20-amp circuit can always support a second dryer',
    answer_c: 'It draws about 150 amps, so it must use direct current',
    answer_d: 'It draws about 6.7 amps, so circuit loading is never a concern',
    correct_answer: 'a',
    explanation: `1,800 ÷ 120 = 15 amps. That calculation alone does not establish what additional load a specific circuit can safely support. ${strategy}`,
    difficulty: 'hard',
    order_index: 8,
  },
  {
    id: 'qq-8-009',
    quiz_id: 'quiz-8',
    question: 'A school is purchasing new electrical tools. Which choice BEST reflects safe equipment-selection reasoning?',
    answer_a: 'Choose equipment that meets applicable workplace requirements and carries recognized safety certification or listing when required',
    answer_b: 'Choose any tool with the highest wattage because higher power always means greater safety',
    answer_c: 'Choose equipment without a grounding feature because two-prong plugs are easier to use',
    answer_d: 'Choose the least expensive tool because electrical testing is the manufacturer\'s responsibility only',
    correct_answer: 'a',
    explanation: `Recognized certification/listing and applicable workplace requirements are relevant safety indicators. Price or wattage alone does not establish safe suitability. ${strategy}`,
    difficulty: 'medium',
    order_index: 9,
  },
  {
    id: 'qq-8-010',
    quiz_id: 'quiz-8',
    question: 'An electrical device is being used near a shampoo area. Which decision BEST reflects ground-fault protection principles?',
    answer_a: 'Use the protection required by the applicable electrical code, facility policy, and equipment instructions for that location',
    answer_b: 'Assume every outlet is safe because the tool has a plastic handle',
    answer_c: 'Remove the grounding pin so the device fits any receptacle',
    answer_d: 'Use an extension cord to move the connection closer to the water source',
    correct_answer: 'a',
    explanation: `Ground-fault protection is especially important where water exposure is possible, but the exact legal requirement depends on the applicable code and facility. ${strategy}`,
    difficulty: 'medium',
    order_index: 10,
  },
  {
    id: 'qq-8-011',
    quiz_id: 'quiz-8',
    question: 'A clipper cord has exposed insulation near the plug, but the clipper still operates normally. What is the BEST action?',
    answer_a: 'Continue using it until the tool stops working',
    answer_b: 'Cover the damage with tape and use it only on dry clients',
    answer_c: 'Remove it from service and have it properly repaired or replaced',
    answer_d: 'Hold the cord away from the client and complete the service',
    correct_answer: 'c',
    explanation: `Visible cord damage is a stop-use condition even when the tool still operates. Temporary wrapping is not a permanent electrical repair. ${strategy}`,
    difficulty: 'hard',
    order_index: 11,
  },
  {
    id: 'qq-8-012',
    quiz_id: 'quiz-8',
    question: 'A circuit breaker trips twice while the same group of tools is operating. What is the BEST professional response?',
    answer_a: 'Reset it repeatedly until the service is finished',
    answer_b: 'Stop and have the load or equipment condition evaluated before continuing the same setup',
    answer_c: 'Replace the breaker with one that has a higher rating',
    answer_d: 'Remove grounding pins from the highest-wattage tools',
    correct_answer: 'b',
    explanation: `Repeated tripping is a warning condition. A barber should not defeat protective devices or alter the electrical system to keep working. ${strategy}`,
    difficulty: 'hard',
    order_index: 12,
  },
  {
    id: 'qq-8-013',
    quiz_id: 'quiz-8',
    question: 'A grounded appliance has a three-prong plug, but the only available receptacle accepts two prongs. What is the BEST decision?',
    answer_a: 'Remove the grounding pin so the plug fits',
    answer_b: 'Use the equipment only with a compatible, properly configured connection allowed by the manufacturer and facility',
    answer_c: 'Bend the grounding pin flat and plug it in',
    answer_d: 'Use the appliance only at low power so grounding is unnecessary',
    correct_answer: 'b',
    explanation: `Do not defeat a grounding feature to make equipment fit an incompatible receptacle. Use a proper connection that preserves the required protective design. ${strategy}`,
    difficulty: 'hard',
    order_index: 13,
  },
  {
    id: 'qq-8-014',
    quiz_id: 'quiz-8',
    question: 'What is the formula for calculating watts?',
    answer_a: 'Watts = Volts ÷ Amps',
    answer_b: 'Watts = Amps × Volts',
    answer_c: 'Watts = Ohms × Volts',
    answer_d: 'Watts = Amps ÷ Ohms',
    correct_answer: 'b',
    explanation: `Electrical power in watts can be calculated as volts multiplied by amps. ${strategy}`,
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-8-015',
    quiz_id: 'quiz-8',
    question: 'After an overload, one protective device must be replaced while another can usually be reset after the cause is addressed. Which pairing is correct?',
    answer_a: 'Fuse must be replaced; circuit breaker can usually be reset',
    answer_b: 'Circuit breaker must be replaced; fuse can usually be reset',
    answer_c: 'Grounding pin must be replaced; GFCI can never be reset',
    answer_d: 'Rheostat must be replaced; rectifier can always be reset',
    correct_answer: 'a',
    explanation: `A fuse opens by melting and must be replaced with the correct type/rating. A circuit breaker trips and can usually be reset after the cause is addressed. ${strategy}`,
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-8-016',
    quiz_id: 'quiz-8',
    question: 'During setup for a permitted electrotherapy service, the barber sees one terminal marked red and one marked black. Which identification matches the source terminology?',
    answer_a: 'Red is usually the anode; black is usually the cathode',
    answer_b: 'Red is usually the cathode; black is usually the anode',
    answer_c: 'Both colors identify alternating-current terminals only',
    answer_d: 'Color alone proves the service is safe for every client',
    correct_answer: 'a',
    explanation: `The source commonly associates red with the positive anode and black with the negative cathode. Color identification does not replace device instructions or client screening. ${strategy}`,
    difficulty: 'medium',
    order_index: 16,
  },
  {
    id: 'qq-8-017',
    quiz_id: 'quiz-8',
    question: 'A client requests an electrical facial service that the barber has read about but has never been trained to perform. What is the BEST next step?',
    answer_a: 'Proceed at the lowest setting because low intensity removes the training requirement',
    answer_b: 'Proceed if the client signs consent',
    answer_c: 'Do not perform it until scope, training, client screening, and device requirements are satisfied',
    answer_d: 'Use only the positive pole because it is always the safer pole',
    correct_answer: 'c',
    explanation: `Knowing terminology does not authorize performance. Scope, training, client suitability, and device instructions all matter before service. ${strategy}`,
    difficulty: 'hard',
    order_index: 17,
  },
  {
    id: 'qq-8-018',
    quiz_id: 'quiz-8',
    question: 'Which source-described electrotherapy association is correct?',
    answer_a: 'Cataphoresis is associated with the positive pole (anode)',
    answer_b: 'Cataphoresis is associated only with ultraviolet light',
    answer_c: 'Cataphoresis always requires alternating current from a wall outlet',
    answer_d: 'Cataphoresis eliminates the need for device-specific procedures',
    correct_answer: 'a',
    explanation: `The source associates cataphoresis with the positive pole/anode. That academic association should not be turned into a universal treatment promise. ${strategy}`,
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-8-019',
    quiz_id: 'quiz-8',
    question: 'A permitted galvanic cleansing procedure calls for desincrustation. Which statement BEST describes the concept without overstating the result?',
    answer_a: 'It is a source-described alkaline galvanic cleansing process intended to help emulsify sebum and debris',
    answer_b: 'It sterilizes pores and guarantees removal of all bacteria',
    answer_c: 'It is a light-therapy process that converts UV energy into heat',
    answer_d: 'It is a universal pre-service step for every client regardless of device instructions',
    correct_answer: 'a',
    explanation: `Desincrustation is described as a galvanic cleansing process involving an alkaline reaction. It is not a guaranteed sterilizing treatment or a universal service step. ${strategy}`,
    difficulty: 'hard',
    order_index: 19,
  },
  {
    id: 'qq-8-020',
    quiz_id: 'quiz-8',
    question: 'A product/device protocol for iontophoresis specifies a particular electrode. What should determine the barber\'s electrode choice?',
    answer_a: 'The specific professional procedure, product directions, device instructions, and training',
    answer_b: 'A universal rule that every acidic product always uses one pole in every device',
    answer_c: 'Whichever pole produces the strongest sensation',
    answer_d: 'The client\'s preferred color of electrode',
    correct_answer: 'a',
    explanation: `Iontophoresis is source-covered, but electrode/product selection should follow the actual procedure and device rather than a universal shortcut. ${strategy}`,
    difficulty: 'hard',
    order_index: 20,
  },
  {
    id: 'qq-8-021',
    quiz_id: 'quiz-8',
    question: 'Which statement BEST distinguishes microcurrent from Tesla high-frequency current?',
    answer_a: 'Microcurrent uses very low current levels; Tesla high-frequency is associated with high oscillation and source-described heat/violet-ray effects',
    answer_b: 'Microcurrent is ultraviolet light; Tesla high-frequency is direct sunlight',
    answer_c: 'Microcurrent always causes strong muscle contractions; Tesla high-frequency always causes none because it has no current',
    answer_d: 'They are identical modalities with different brand names',
    correct_answer: 'a',
    explanation: `The source treats microcurrent and Tesla high-frequency as different modalities with different current characteristics. Actual use remains device- and scope-dependent. ${strategy}`,
    difficulty: 'medium',
    order_index: 21,
  },
  {
    id: 'qq-8-022',
    quiz_id: 'quiz-8',
    question: 'A client requests microcurrent after hearing broad cosmetic claims online. What is the BEST professional response before service?',
    answer_a: 'Verify scope, training, client history, device contraindications, and manufacturer instructions',
    answer_b: 'Proceed because very low current means contraindications do not apply',
    answer_c: 'Proceed if the client says they have used a similar device before',
    answer_d: 'Increase intensity until the client can clearly feel the current',
    correct_answer: 'a',
    explanation: `Low-level current does not remove the need for scope, training, screening, and device-specific safety requirements. ${strategy}`,
    difficulty: 'hard',
    order_index: 22,
  },
  {
    id: 'qq-8-023',
    quiz_id: 'quiz-8',
    question: 'During a permitted high-frequency service, the client reports unexpected burning. What is the BEST immediate response?',
    answer_a: 'Lower the intensity slightly and continue without interruption',
    answer_b: 'Stop the service, turn off the device according to its safety procedure, and reassess before any further use',
    answer_c: 'Switch polarity because burning proves the wrong pole was selected',
    answer_d: 'Continue because heat is always expected with high-frequency devices',
    correct_answer: 'b',
    explanation: `Unexpected burning or sharp discomfort is a stop-service signal. Do not assume the sensation is normal or solve it by improvising settings. ${strategy}`,
    difficulty: 'hard',
    order_index: 23,
  },
  {
    id: 'qq-8-024',
    quiz_id: 'quiz-8',
    question: 'Across the electromagnetic spectrum, which relationship is generally correct?',
    answer_a: 'As wavelength decreases, frequency generally increases',
    answer_b: 'As wavelength decreases, frequency also decreases',
    answer_c: 'Wavelength and frequency are unrelated',
    answer_d: 'All electromagnetic radiation has the same wavelength',
    correct_answer: 'a',
    explanation: `Wavelength and frequency are inversely related in the spectrum. Avoid turning that relationship into a universal tissue-penetration rule. ${strategy}`,
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-8-025',
    quiz_id: 'quiz-8',
    question: 'Which statement BEST distinguishes UVA, UVB, and UVC for Chapter 8 study?',
    answer_a: 'UVA is associated with tanning/photoaging, UVB with sunburn/skin damage, and UVC with germicidal applications',
    answer_b: 'UVA is germicidal, UVB is visible red light, and UVC is infrared heat',
    answer_c: 'UVA, UVB, and UVC are three names for the same wavelength',
    answer_d: 'Only UVC can affect skin or eyes',
    correct_answer: 'a',
    explanation: `The source distinguishes the UV bands by wavelength and associated effects/applications. UV exposure can injure skin and eyes. ${strategy}`,
    difficulty: 'hard',
    order_index: 25,
  },
  {
    id: 'qq-8-026',
    quiz_id: 'quiz-8',
    question: 'A barber sees a cabinet advertised with ultraviolet germicidal light. Which conclusion is SAFEST?',
    answer_a: 'The UV feature does not automatically replace cleaning and disinfection procedures required by applicable rules',
    answer_b: 'Any UV cabinet automatically sterilizes every tool placed inside it',
    answer_c: 'UVC is harmless to skin and eyes because it is used for germicidal applications',
    answer_d: 'Using UV equipment removes the need to follow manufacturer instructions',
    correct_answer: 'a',
    explanation: `Germicidal UV applications exist, but a UV cabinet should not be assumed to substitute for required barbering infection-control procedures unless applicable rules specifically recognize it. ${strategy}`,
    difficulty: 'hard',
    order_index: 26,
  },
  {
    id: 'qq-8-027',
    quiz_id: 'quiz-8',
    question: 'A device uses colored LEDs for a cosmetic service. How should the barber interpret color-based treatment claims?',
    answer_a: 'As device-dependent indications that still require scope, client suitability, and manufacturer verification',
    answer_b: 'As guaranteed medical outcomes that apply to every client',
    answer_c: 'As proof that eye protection is never required',
    answer_d: 'As a reason to ignore medication or photosensitivity screening',
    correct_answer: 'a',
    explanation: `The source associates LED colors with different purposes, but actual indications and safe use depend on the device, client, and permitted scope. ${strategy}`,
    difficulty: 'medium',
    order_index: 27,
  },
  {
    id: 'qq-8-028',
    quiz_id: 'quiz-8',
    question: 'What is selective photothermolysis, and what additional issue must a barber recognize?',
    answer_a: 'It is targeted conversion of light to heat, and laser operation may require authorization beyond ordinary barber licensure',
    answer_b: 'It is the conversion of AC to DC, and any barber may use it without additional training',
    answer_c: 'It is a grounding method, and it replaces GFCI protection',
    answer_d: 'It is a UV disinfection method, and it replaces required infection-control procedures',
    correct_answer: 'a',
    explanation: `Selective photothermolysis is a light-to-heat targeting concept used with lasers. Knowing the concept does not establish legal authority to operate a laser. ${strategy}`,
    difficulty: 'hard',
    order_index: 28,
  },
  {
    id: 'qq-8-029',
    quiz_id: 'quiz-8',
    question: 'Before a permitted light-based service, a client reports taking a medication that may increase photosensitivity. What is the BEST next action?',
    answer_a: 'Proceed with half the normal exposure time',
    answer_b: 'Screen against the device contraindications and do not proceed unless the procedure is clearly appropriate',
    answer_c: 'Use a different LED color without reviewing the medication',
    answer_d: 'Proceed if the client signs consent',
    correct_answer: 'b',
    explanation: `Possible photosensitivity is a screening issue. Do not improvise a reduced exposure as a substitute for device-specific contraindication review and professional judgment. ${strategy}`,
    difficulty: 'hard',
    order_index: 29,
  },
  {
    id: 'qq-8-030',
    quiz_id: 'quiz-8',
    question: 'Two professional light devices specify different exposure times, distances, and eye-protection requirements. Which rule should guide the barber?',
    answer_a: 'Use one universal five-minute and 30-inch rule for both devices',
    answer_b: 'Use the operating parameters and protection required for each specific device and procedure while supervising the client continuously',
    answer_c: 'Use the longest exposure from either device so both treatments are effective',
    answer_d: 'Let the client choose the distance and exposure based on comfort alone',
    correct_answer: 'b',
    explanation: `Different light devices can require different operating parameters. Device-specific instructions, required protection, client screening, and continuous supervision take priority over memorized universal numbers. ${strategy}`,
    difficulty: 'hard',
    order_index: 30,
  },
]

export const chapter8QuizMeta = {
  id: 'quiz-8',
  chapter_id: 'ch-8',
  title: 'Basics of Electricity — Premium Quiz',
  description: '30 difficult application and safety questions aligned to the Chapter 8 mastery framework. Passing score: 80%.',
  question_count: 30,
  passing_score: 80,
  time_limit_minutes: 45,
}

export default chapter8PremiumQuizQuestions
