// Chapter 7: Basics of Chemistry — PREMIUM FLASHCARDS
// The Barber's Laboratory — Master the Formulas Behind Every Product
// Categories: Matter & Properties, Redox Reactions, Solutions & Emulsions, pH & Water, Shampoos & Conditioners, Product Chemistry, Safety & USP, Board Exam Alerts
// Source: Chapter 7 textbook images (textbook-images/chapter-7/)

import { Flashcard } from '@/types'

export const chapter7PremiumFlashcards: Flashcard[] = [
  // ==========================================
  // CATEGORY 1: MATTER & PROPERTIES (10 cards)
  // ==========================================
  {
    id: 'fc-7-001',
    chapter_id: 'ch-7',
    front: 'What is the definition of chemistry?',
    back: 'The science of the composition, structure, and properties of matter and how it changes. Understanding chemistry is essential for safe product use in barbering.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-7-002',
    chapter_id: 'ch-7',
    front: "How should you distinguish organic chemistry from inorganic chemistry?",
    back: "Organic chemistry focuses on carbon-containing substances and compounds. Inorganic chemistry covers substances such as water, minerals, metals, ammonia, and other materials generally studied outside organic carbon chemistry. Do not use a living-versus-nonliving shortcut.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-7-003',
    chapter_id: 'ch-7',
    front: "Can organic or inorganic classification tell you whether a chemical is safe or flammable?",
    back: "No. Organic versus inorganic describes chemical composition, not hazard level. Safety depends on the specific product, concentration, pH, ingredients, exposure route, and directions for use.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-7-004',
    chapter_id: 'ch-7',
    front: 'What is matter?',
    back: 'Anything that occupies space (has volume) and has mass (weight). Matter exists in three states: solid, liquid, and gas.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-7-005',
    chapter_id: 'ch-7',
    front: 'What is the difference between a physical property and a chemical property?',
    back: 'Physical properties can be observed without a chemical reaction (color, odor, density, melting point, solubility). Chemical properties are observed only through chemical reactions that change the substance (rusting, burning, oxidation).',
    category: 'Matter & Properties',
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-7-006',
    chapter_id: 'ch-7',
    front: "How do you tell a physical change from a chemical change?",
    back: "A physical change alters form, state, or another physical characteristic without creating a new chemical substance. A chemical change involves a reaction that changes chemical composition and produces substances with different chemical properties.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-7-007',
    chapter_id: 'ch-7',
    front: 'What is an element?',
    back: 'The simplest form of matter. An element contains only one type of atom. There are 118 known elements, with 98 occurring naturally. Examples: hydrogen, oxygen, carbon, nitrogen.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-7-008',
    chapter_id: 'ch-7',
    front: 'What are the three subatomic particles and their charges?',
    back: 'Protons (+ positive charge), neutrons (neutral/no charge), and electrons (– negative charge). These particles make up atoms and determine chemical behavior.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-7-009',
    chapter_id: 'ch-7',
    front: 'What is the difference between a molecule and a compound?',
    back: 'A molecule is two or more atoms joined by chemical bonds (can be the same element: O₂, or different: H₂O). A compound is a molecule containing DIFFERENT elements chemically united in fixed proportions (H₂O, CO₂, NaCl). All compounds are molecules, but not all molecules are compounds.',
    category: 'Matter & Properties',
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-7-010',
    chapter_id: 'ch-7',
    front: 'What is the difference between a pure substance and a physical mixture?',
    back: 'Pure substance: fixed composition and definite proportions (elements or compounds). Physical mixture: blended without fixed composition, can be uniform (homogeneous like saltwater) or nonuniform (heterogeneous like salad).',
    category: 'Matter & Properties',
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 2: REDOX REACTIONS (8 cards)
  // ==========================================
  {
    id: 'fc-7-011',
    chapter_id: 'ch-7',
    front: 'What is oxidation?',
    back: 'The addition of oxygen OR the loss of hydrogen. When a substance is oxidized, it gains oxygen or loses hydrogen atoms. Example: haircolor gains oxygen from hydrogen peroxide during development.',
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-7-012',
    chapter_id: 'ch-7',
    front: 'What is reduction?',
    back: 'The loss of oxygen OR the gain of hydrogen. When a substance is reduced, it loses oxygen or gains hydrogen atoms. Example: hydrogen peroxide loses oxygen when it develops haircolor.',
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-7-013',
    chapter_id: 'ch-7',
    front: "Why are oxidation and reduction treated as a pair?",
    back: "They occur together in a redox reaction. One substance is oxidized while another is reduced. In Chapter 7, track the oxygen or hydrogen change to identify which process is occurring.",
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-7-014',
    chapter_id: 'ch-7',
    front: 'What chemical reaction occurs during permanent waving?',
    back: 'REDUCTION breaks disulfide bonds in the hair using a reducing lotion (gains hydrogen/loses oxygen). Then OXIDATION (neutralizer) reforms the bonds in the new curled shape. The process requires both reduction AND oxidation.',
    category: 'Redox Reactions',
    difficulty: 'hard',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-7-015',
    chapter_id: 'ch-7',
    front: 'What is the role of hydrogen peroxide in haircolor?',
    back: 'Hydrogen peroxide (H₂O₂) is the oxidizing agent. It releases oxygen that oxidizes the haircolor molecules, allowing them to develop and bond to the hair. The H₂O₂ itself is REDUCED (loses oxygen) in the process.',
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-7-016',
    chapter_id: 'ch-7',
    front: "What is an exothermic reaction?",
    back: "An exothermic reaction releases heat to its surroundings. During a chemical service, unexpected or excessive heat is a safety signal to stop and follow the product directions rather than assuming all warmth is normal.",
    category: 'Redox Reactions',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-7-017',
    chapter_id: 'ch-7',
    front: "What is an endothermic reaction?",
    back: "An endothermic reaction absorbs heat from its surroundings. In barbering chemistry, some reactions may require an external heat source rather than producing heat on their own.",
    category: 'Redox Reactions',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-7-018',
    chapter_id: 'ch-7',
    front: 'What happens during the neutralization step of a permanent wave?',
    back: 'The neutralizer (oxidizing agent) reforms the disulfide bonds that were broken during the reduction phase. This "locks" the hair into its new curled shape. Skipping or shortening neutralization causes weak, frizzy curls.',
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 3: SOLUTIONS, SUSPENSIONS & EMULSIONS (8 cards)
  // ==========================================
  {
    id: 'fc-7-019',
    chapter_id: 'ch-7',
    front: "What makes a mixture a solution?",
    back: "A solution is a stable, uniform mixture in which the dissolved substance is distributed throughout the solvent and does not settle out. Stability and uniform distribution are more reliable clues than appearance alone.",
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-7-020',
    chapter_id: 'ch-7',
    front: "What makes a mixture a suspension?",
    back: "A suspension contains dispersed particles large enough to settle over time. If the product label directs you to shake or redistribute the product, follow that instruction before use.",
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-7-021',
    chapter_id: 'ch-7',
    front: 'What is an emulsion?',
    back: 'A mixture of two immiscible liquids (like oil and water) held together by an emulsifier or surfactant. Emulsions are milky or creamy and can separate over time. Most shampoos and conditioners are emulsions.',
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-7-022',
    chapter_id: 'ch-7',
    front: "What is the difference between oil-in-water and water-in-oil emulsions?",
    back: "In an oil-in-water emulsion, oil droplets are dispersed through a continuous water phase. In a water-in-oil emulsion, water droplets are dispersed through a continuous oil phase.",
    category: 'Solutions & Emulsions',
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-7-023',
    chapter_id: 'ch-7',
    front: 'What is a surfactant and what is its molecular structure?',
    back: 'A surfactant reduces surface tension between oil and water, allowing them to mix. Its structure has a hydrophilic (water-loving) HEAD and a lipophilic (oil-loving) TAIL. This dual nature makes cleansing possible.',
    category: 'Solutions & Emulsions',
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-7-024',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What are the four types of surfactants and their charges?',
    back: '1. ANIONIC: negative charge — strong cleansing (primary shampoo surfactant). 2. CATIONIC: positive charge — conditioning (adheres to hair). 3. NONIONIC: no charge — mild cleansing. 4. AMPHOTERIC: both charges — very gentle, pH-dependent behavior.',
    category: 'Solutions & Emulsions',
    difficulty: 'hard',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-7-025',
    chapter_id: 'ch-7',
    front: "Why might a product label tell you to shake before use?",
    back: "Some mixtures can separate or allow dispersed particles to settle while standing. Shaking redistributes the contents. The label instruction matters more than trying to identify the product type from the words “shake well” alone.",
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-7-026',
    chapter_id: 'ch-7',
    front: "Can shampoos and conditioners be emulsions?",
    back: "Yes. Chapter 7 uses shampoos and conditioners as examples of emulsions. The exact type and ingredient balance depend on the individual formula.",
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 4: pH & WATER (12 cards)
  // ==========================================
  {
    id: 'fc-7-027',
    chapter_id: 'ch-7',
    front: "What does pH tell you?",
    back: "pH reflects hydrogen-ion conditions in a water-based solution. On the standard scale, values below 7 are acidic, 7 is neutral, and values above 7 are alkaline.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-7-028',
    chapter_id: 'ch-7',
    front: "What pH range is commonly associated with hair and skin?",
    back: "Hair and skin are commonly around pH 4.5–5.5, which is slightly acidic. Product effects still depend on concentration, ingredients, hair or skin condition, and correct use.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-7-029',
    chapter_id: 'ch-7',
    front: "How can acidic conditions affect hair?",
    back: "Milder acidic conditions can contract and harden hair and help tighten the cuticle. Very strong acid can damage or dissolve hair. Always consider strength and concentration instead of treating every acidic product the same.",
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-7-030',
    chapter_id: 'ch-7',
    front: "How can alkaline conditions affect hair?",
    back: "As alkalinity increases, hair can swell and become more porous as the cuticle opens. Strong alkalis can damage or dissolve hair, so product strength and manufacturer directions are critical.",
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-7-031',
    chapter_id: 'ch-7',
    front: "What is acid-alkali neutralization, and what should you not confuse it with?",
    back: "Acid-alkali neutralization occurs when an acid and alkali react to form water and a salt. Do not confuse that reaction with oxidation neutralization in permanent waving; they are different chemical processes.",
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-7-032',
    chapter_id: 'ch-7',
    front: 'What is the difference between soft water and hard water?',
    back: 'Soft water: low mineral content, lathers easily with soap/shampoo, rinses clean. Hard water: high mineral content (calcium, magnesium), does NOT lather well, leaves mineral buildup on hair and tools. Hard water can make hair feel dry and look dull.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-7-033',
    chapter_id: 'ch-7',
    front: "How can water affect the size of the hair fiber?",
    back: "Water can penetrate the hair and cause it to swell. This helps explain why water and pH are important when evaluating how products and chemical services affect the hair.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-7-034',
    chapter_id: 'ch-7',
    front: "What happens to hair at extreme pH levels?",
    back: "Very strong acids and very strong alkalis can severely damage or dissolve hair. The safe takeaway is to follow the labeled product strength, timing, and application directions rather than memorize a single danger cutoff for every formula.",
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-7-035',
    chapter_id: 'ch-7',
    front: 'Why is water called the "universal solvent"?',
    back: 'Water dissolves more substances than any other liquid. This makes it essential for cleansing, mixing products, and chemical reactions. However, water alone cannot dissolve oils — surfactants are needed for that.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-7-036',
    chapter_id: 'ch-7',
    front: 'What are the three methods of water purification?',
    back: '1. Boiling: kills bacteria and pathogens. 2. Filtration: removes particles and some contaminants. 3. Distillation: boils water and condenses steam, removing minerals and impurities — produces the purest water.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-7-037',
    chapter_id: 'ch-7',
    front: 'Why does hard water affect shampoo performance?',
    back: 'Hard water contains calcium and magnesium minerals that react with shampoo surfactants, forming soap scum instead of lather. This reduces cleansing effectiveness and leaves mineral buildup on hair, making it feel dry and look dull.',
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-7-038',
    chapter_id: 'ch-7',
    front: "Why are many conditioners formulated on the acidic side?",
    back: "Acidic conditioner formulas can help contract and smooth the hair surface and improve manageability. The exact formula and pH vary by product, so use the product’s intended purpose and directions.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 38,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 5: SHAMPOOS & CONDITIONERS (12 cards)
  // ==========================================
  {
    id: 'fc-7-039',
    chapter_id: 'ch-7',
    front: 'What is the primary function of shampoo?',
    back: 'To cleanse the hair and scalp by removing oil, dirt, debris, and product buildup. Shampoos are mostly oil-in-water emulsions containing surfactants that allow oil and water to mix so dirt can be rinsed away.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-7-040',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What are the four surfactant classifications used in shampoo?',
    back: '1. ANIONIC: negative charge, strong cleansing, primary shampoo surfactant. 2. CATIONIC: positive charge, conditioning, antibacterial. 3. NONIONIC: no charge, mild cleansing, gentle formulas. 4. AMPHOTERIC: both charges, very gentle, pH-adjusting behavior.',
    category: 'Shampoos & Conditioners',
    difficulty: 'hard',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-7-041',
    chapter_id: 'ch-7',
    front: "How does a clarifying shampoo differ from a moisturizing or conditioning shampoo?",
    back: "Clarifying shampoos target product or mineral buildup with stronger cleansing or chelating action. Moisturizing or conditioning shampoos are designed to cleanse while supporting dry or compromised hair. Frequency should match the client’s condition and product directions.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-7-042',
    chapter_id: 'ch-7',
    front: "When is a neutralizing or balancing shampoo appropriate?",
    back: "Use it when a specific chemical service or product system directs you to remove or counter unwanted alkaline residue. It does not replace permanent-wave oxidation neutralization, and it is not a universal step after every chemical service.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-7-043',
    chapter_id: 'ch-7',
    front: 'What is a medicated shampoo and when is it used?',
    back: 'Contains active ingredients to treat scalp conditions like dandruff, seborrheic dermatitis, or psoriasis. Follow label directions carefully. Some require a doctor\'s recommendation. Do not use on healthy scalps.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-7-044',
    chapter_id: 'ch-7',
    front: 'What is the purpose of sulfate-free shampoo?',
    back: 'Sulfate-free shampoos use gentler cleansing agents that produce less lather but are less stripping. Ideal for sensitive scalps, color-treated hair, and chemically processed hair that needs moisture retention.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-7-045',
    chapter_id: 'ch-7',
    front: 'What are the main types of conditioners?',
    back: '1. INSTANT/RINSE-OUT: applied after shampoo, left briefly, rinsed — daily use. 2. TREATMENT/REPAIR: deep conditioning with higher protein/moisture — left on longer for damaged hair. 3. LEAVE-IN: not rinsed — provides ongoing protection.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-7-046',
    chapter_id: 'ch-7',
    front: 'What are common ingredients in conditioners and what do they do?',
    back: 'Proteins: strengthen and repair. Fatty materials/oils: soften and smooth. Humectants: draw moisture into hair. Moisturizers: hydrate. Silicones: add shine, reduce frizz, protect from heat.',
    category: 'Shampoos & Conditioners',
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-7-047',
    chapter_id: 'ch-7',
    front: "When might a dry or powder shampoo be used?",
    back: "A dry or powder shampoo can be used when a wet shampoo is not appropriate or practical for the client’s hair condition. Follow the product directions for application and removal.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-7-048',
    chapter_id: 'ch-7',
    front: 'What is a balancing shampoo and who should use it?',
    back: 'Designed for oily scalps. Balancing shampoo regulates sebum (oil) production without over-drying the hair shaft. Different from clarifying shampoo — it balances rather than strips.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-7-049',
    chapter_id: 'ch-7',
    front: "What is the purpose of a color-enhancing shampoo?",
    back: "Color-enhancing shampoos combine cleansing with color-supporting ingredients that can help refresh or enhance selected tones. Choose the product to match the intended color result and follow its directions.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-7-050',
    chapter_id: 'ch-7',
    front: "How should you choose a shampoo for a client?",
    back: "Match the shampoo’s purpose to the client’s hair and scalp condition, chemical history, buildup level, and service goal. Product labels and manufacturer directions are more reliable than a rigid one-shampoo-per-hair-type rule.",
    category: 'Shampoos & Conditioners',
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 6: PRODUCT CHEMISTRY & INGREDIENTS (12 cards)
  // ==========================================
  {
    id: 'fc-7-051',
    chapter_id: 'ch-7',
    front: 'What does USP stand for and why does it matter in barbering?',
    back: 'United States Pharmacopeia — an official body that sets standards for the strength, quality, and purity of ingredients used in hair and skin products. USP-standard ingredients ensure consistency and safety in professional products.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-7-052',
    chapter_id: 'ch-7',
    front: "What role does hydrogen peroxide play in hair chemistry?",
    back: "Hydrogen peroxide acts as an oxidizing agent in services such as oxidation haircolor and lightening. Its concentration and use must match the specific professional product and manufacturer directions.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-7-053',
    chapter_id: 'ch-7',
    front: 'What is glycerin and why is it in hair products?',
    back: 'A humectant — it draws moisture from the air into hair and skin. Common in conditioners and lotions. Helps maintain hydration, especially in dry climates.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-7-054',
    chapter_id: 'ch-7',
    front: "What is petrolatum used for in barbering preparations?",
    back: "Petrolatum is an oily, protective ingredient used in some creams, ointments, pomades, and barrier-type preparations. Its purpose depends on the product formulation.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-7-055',
    chapter_id: 'ch-7',
    front: 'What is ammonia and why is it in hair products?',
    back: 'A strong alkali that raises pH to open the cuticle, allowing chemicals to penetrate the cortex. Used in permanent haircolor, lighteners, and some perms. Has a strong, recognizable odor. Modern products often use less-odorous alternatives like MEA.',
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-7-056',
    chapter_id: 'ch-7',
    front: "What are alkanolamines used for in cosmetic products?",
    back: "Alkanolamines are alkaline ingredients used to adjust pH or neutralize acids in some cosmetic formulations. Their exact role depends on the product.",
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-7-057',
    chapter_id: 'ch-7',
    front: "What is alum used for in barbering products?",
    back: "Alum is an astringent or styptic ingredient associated with helping control minor surface bleeding. Its use should follow the product directions and applicable infection-control rules.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-7-058',
    chapter_id: 'ch-7',
    front: "What are quaternary ammonium compounds?",
    back: "Quaternary ammonium compounds are a class of ingredients used in some professional formulations. Their function and safe use depend on the specific product, concentration, label, and manufacturer directions.",
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-7-059',
    chapter_id: 'ch-7',
    front: "How are alcohols used in cosmetic preparations?",
    back: "Alcohols may be used as solvents and in products such as astringents or other cosmetic preparations. Different alcohols and concentrations behave differently, so follow the product label rather than relying on one universal concentration rule.",
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-7-060',
    chapter_id: 'ch-7',
    front: "Why should ingredients with significant inhalation or exposure hazards be handled cautiously?",
    back: "Some cosmetic ingredients can present meaningful exposure risks. Use the product label, SDS when applicable, ventilation guidance, and manufacturer directions to control exposure rather than relying on memory alone.",
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-7-061',
    chapter_id: 'ch-7',
    front: 'What are silicones in hair products and what do they do?',
    back: 'Breathable film-formers that coat the hair shaft. Add shine, reduce frizz, detangle, and protect from heat. Common in conditioners and serums. Can build up over time, requiring occasional clarifying shampoo use.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-7-062',
    chapter_id: 'ch-7',
    front: 'What is witch hazel and how is it used in barbering?',
    back: 'A natural astringent and skin freshener derived from a shrub. Tightens pores, soothes skin, and reduces inflammation. Common in aftershaves, toners, and skin fresheners. Gentler than alcohol-based astringents.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 62,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 7: SAFETY & SDS (8 cards)
  // ==========================================
  {
    id: 'fc-7-063',
    chapter_id: 'ch-7',
    front: "What is the purpose of a Safety Data Sheet (SDS)?",
    back: "An SDS provides standardized hazard, handling, storage, exposure-control, first-aid, and emergency information for a chemical product. Use it when a product is covered by workplace hazard-communication requirements.",
    category: 'Safety & SDS',
    difficulty: 'medium',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-7-064',
    chapter_id: 'ch-7',
    front: "What kind of information is organized in an SDS?",
    back: "An SDS organizes information such as product identification, hazards, composition, first aid, fire response, accidental release, handling and storage, exposure controls, physical and chemical properties, stability, and toxicology.",
    category: 'Safety & SDS',
    difficulty: 'hard',
    order_index: 64,
    is_active: true,
  },
  {
    id: 'fc-7-065',
    chapter_id: 'ch-7',
    front: 'Why should you NEVER mix bleach and ammonia?',
    back: 'Mixing bleach (sodium hypochlorite) with ammonia creates toxic CHLORAMINE GAS. This gas causes severe respiratory damage, eye irritation, coughing, and can be fatal. Never mix cleaning chemicals. Read labels before combining any products.',
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-7-066',
    chapter_id: 'ch-7',
    front: "How should a barber handle pre-service testing for a chemical product?",
    back: "Check the product label, manufacturer directions, and applicable rules for the required test and timing. Predisposition, strand, or other pre-service tests are product- and service-specific, so do not use one universal method for every chemical service.",
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-7-067',
    chapter_id: 'ch-7',
    front: 'What PPE should be worn when handling chemicals in a barbershop?',
    back: 'Gloves (nitrile, not latex for chemicals), protective eyewear when mixing powders/liquids, apron or cape to protect clothing, and proper ventilation. Some services require a mask if fumes are strong.',
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-7-068',
    chapter_id: 'ch-7',
    front: 'What should you do if a chemical gets in a client\'s eye?',
    back: 'Immediately flush with lukewarm water for at least 15 minutes. Hold eyelids open to ensure water reaches all surfaces. Do NOT try to neutralize with another chemical. Seek medical attention after flushing. Document the incident.',
    category: 'Safety & SDS',
    difficulty: 'medium',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-7-069',
    chapter_id: 'ch-7',
    front: 'Why is proper ventilation important when using chemical products?',
    back: 'Many barbering chemicals release fumes that can cause respiratory irritation, headaches, and long-term health problems. Proper ventilation (exhaust fans, open windows, air purifiers) removes airborne chemicals and protects both barber and client.',
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-7-070',
    chapter_id: 'ch-7',
    front: "What should you check on a professional product label before use?",
    back: "Confirm the product identity, intended use, directions, warnings or precautions, and any required preparation or testing information. Do not assume every professional product must display the same optional details such as pH or an expiration date.",
    category: 'Safety & SDS',
    difficulty: 'medium',
    order_index: 70,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 8: BOARD EXAM ALERTS (10 cards)
  // ==========================================
  {
    id: 'fc-7-071',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What are the three states of matter?',
    back: 'Solid, liquid, and gas. Changes between states are PHYSICAL changes (no new substance formed). Temperature and pressure determine the state.',
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 71,
    is_active: true,
  },
  {
    id: 'fc-7-072',
    chapter_id: 'ch-7',
    front: "How can chemical compounds be grouped in basic chemistry?",
    back: "Chapter 7 discusses compound groups such as oxides, acids, alkalis or bases, and salts. The important skill is recognizing how each group behaves rather than memorizing the list without context.",
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 72,
    is_active: true,
  },
  {
    id: 'fc-7-073',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What is the chemical formula for water and what does it mean?',
    back: 'H₂O — two hydrogen atoms bonded to one oxygen atom. Water is an inorganic compound, a universal solvent, and neutral on the pH scale (pH 7).',
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 73,
    is_active: true,
  },
  {
    id: 'fc-7-074',
    chapter_id: 'ch-7',
    front: "What happens in acid-alkali neutralization?",
    back: "An acid and alkali react to form water and a salt. This chemistry is different from permanent-wave oxidation neutralization, so identify the actual reaction used by the service before choosing a neutralizing step.",
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 74,
    is_active: true,
  },
  {
    id: 'fc-7-075',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: Why do permanent waves and relaxers use alkaline products?',
    back: 'Alkaline pH (above 7) opens the cuticle and swells the cortex, allowing the reducing/relaxing chemicals to penetrate and break or rearrange disulfide bonds. Without alkalinity, the chemicals cannot reach the inner structure of the hair.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 75,
    is_active: true,
  },
  {
    id: 'fc-7-076',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What is the difference between temporary and permanent hair color in terms of chemistry?',
    back: 'Temporary color: physical change — large color molecules coat the outside of the hair shaft and wash out. Permanent color: chemical change — small molecules enter the cortex and oxidize (expand) to become trapped inside. Requires oxidation.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 76,
    is_active: true,
  },
  {
    id: 'fc-7-077',
    chapter_id: 'ch-7',
    front: "Is one exact pH range ideal for every shampoo?",
    back: "No. Shampoo formulas are selected by purpose, hair or scalp condition, and manufacturer design. pH matters because acidic and alkaline conditions affect hair differently, but one universal “ideal” number should not replace product-specific guidance.",
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 77,
    is_active: true,
  },
  {
    id: 'fc-7-078',
    chapter_id: 'ch-7',
    front: "What does a chelating ingredient do in a cleansing product?",
    back: "A chelating ingredient binds certain metal or mineral ions so they can be removed more effectively. Chelating or clarifying products may be useful when mineral buildup is actually present.",
    category: 'Board Exam Alert',
    difficulty: 'hard',
    order_index: 78,
    is_active: true,
  },
  {
    id: 'fc-7-079',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What is the difference between an elemental molecule and a compound molecule?',
    back: 'Elemental molecule: two or more atoms of the SAME element (O₂ oxygen gas, O₃ ozone). Compound molecule: atoms of DIFFERENT elements chemically united (H₂O water, CO₂ carbon dioxide, NaCl salt).',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 79,
    is_active: true,
  },
  {
    id: 'fc-7-080',
    chapter_id: 'ch-7',
    front: "What principles should guide chemical storage in a barbershop?",
    back: "Keep products in properly identified containers, follow label and SDS storage directions, protect them from incompatible conditions, and separate incompatible chemicals when required. Storage rules should come from the actual product information.",
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 80,
    is_active: true,
  },
]
