import { Flashcard } from '@/types'

// Chapter 20: Working Behind the Chair — 60 premium flashcards
export const chapter20PremiumFlashcards: Flashcard[] = [
  // ───────────────────────────────────────────────
  // Category: Transition from School to Work (001–010)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch20-001',
    standardId: 'CH20-F001',
    chapter_id: 'ch-20',
    front: "What is the biggest change when moving from barbering school to a professional barbershop?",
    back: "You must put the needs of the shop and your clients ahead of your own personal schedule and preferences.",
    category: "Transition from School to Work",
    difficulty: 'medium',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch20-002',
    standardId: 'CH20-F002',
    chapter_id: 'ch-20',
    front: "How does school differ from work in terms of making mistakes?",
    back: "School allows you to repeat procedures until you master them; on the job, clients and coworkers depend on your reliability.",
    category: "Transition from School to Work",
    difficulty: 'medium',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-ch20-003',
    standardId: 'CH20-F003',
    chapter_id: 'ch-20',
    front: "Why is punctuality essential behind the chair?",
    back: "Being on time shows respect for clients and prevents coworkers from having to cover your appointments.",
    category: "Transition from School to Work",
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch20-004',
    standardId: 'CH20-F004',
    chapter_id: 'ch-20',
    front: "What does it mean to prioritize the barbershop over your personal life?",
    back: "You show up prepared for every scheduled shift and perform required services regardless of personal distractions.",
    category: "Transition from School to Work",
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch20-005',
    standardId: 'CH20-F005',
    chapter_id: 'ch-20',
    front: "What is a job description in a barbershop?",
    back: "A written document that outlines the duties, responsibilities, attitudes, and opportunities of a specific position.",
    category: "Transition from School to Work",
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-ch20-006',
    standardId: 'CH20-F006',
    chapter_id: 'ch-20',
    front: "What should you do if the shop does not provide a written job description?",
    back: "Write one yourself and review it with your manager so you both understand expectations.",
    category: "Transition from School to Work",
    difficulty: 'medium',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch20-007',
    standardId: 'CH20-F007',
    chapter_id: 'ch-20',
    front: "Why is continuing education important even after you are licensed and employed?",
    back: "Lifelong learning increases your skills, earning potential, and career opportunities.",
    category: "Transition from School to Work",
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-ch20-008',
    standardId: 'CH20-F008',
    chapter_id: 'ch-20',
    front: "What professional conduct is expected of a new barbering employee?",
    back: "Appropriate behavior, performing requested services, and handling all business professionally.",
    category: "Transition from School to Work",
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch20-009',
    standardId: 'CH20-F009',
    chapter_id: 'ch-20',
    front: "How can your fulfillment of a job description affect your career?",
    back: "How well you perform the listed duties influences your future at the shop and your financial rewards.",
    category: "Transition from School to Work",
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-ch20-010',
    standardId: 'CH20-F010',
    chapter_id: 'ch-20',
    front: "What should guide your behavior throughout your barbering career?",
    back: "Personal goals and clear rules of conduct that you commit to from the start.",
    category: "Transition from School to Work",
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Barbershop Teamwork (011–020)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch20-011',
    standardId: 'CH20-F011',
    chapter_id: 'ch-20',
    front: "What is the first reality of working in a service profession such as barbering?",
    back: "Your career revolves around serving your clients and meeting their needs.",
    category: "Barbershop Teamwork",
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch20-012',
    standardId: 'CH20-F012',
    chapter_id: 'ch-20',
    front: "What does it mean to 'put others first' in a barbershop?",
    back: "You set aside your own feelings and desires to perform what the shop and client need.",
    category: "Barbershop Teamwork",
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-ch20-013',
    standardId: 'CH20-F013',
    chapter_id: 'ch-20',
    front: "Why should a team player be willing to pitch in with tasks such as folding towels or booking appointments?",
    back: "Helping with whatever needs to be done supports the whole team and the smooth operation of the shop.",
    category: "Barbershop Teamwork",
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch20-014',
    standardId: 'CH20-F014',
    chapter_id: 'ch-20',
    front: "How does sharing knowledge strengthen a barbershop team?",
    back: "Teaching coworkers earns respect, while learning from them broadens your skills and perspective.",
    category: "Barbershop Teamwork",
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch20-015',
    standardId: 'CH20-F015',
    chapter_id: 'ch-20',
    front: "How should conflict be handled among barbershop teammates?",
    back: "Discuss it directly with the individual involved and work constructively toward resolution.",
    category: "Barbershop Teamwork",
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch20-016',
    standardId: 'CH20-F016',
    chapter_id: 'ch-20',
    front: "Why is loyalty important in a barbershop?",
    back: "Barbers must be loyal to the shop and management, while management and clients should also show loyalty in return.",
    category: "Barbershop Teamwork",
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch20-017',
    standardId: 'CH20-F017',
    chapter_id: 'ch-20',
    front: "What does it mean to 'be willing to be subordinate' as a new barber?",
    back: "Beginners usually start lower in the shop hierarchy and should respect that everyone has to earn their place.",
    category: "Barbershop Teamwork",
    difficulty: 'hard',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-ch20-018',
    standardId: 'CH20-F018',
    chapter_id: 'ch-20',
    front: "How can you remain a positive influence on your barbershop team?",
    back: "Avoid gossip and maliciousness, and focus on building good working relationships.",
    category: "Barbershop Teamwork",
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch20-019',
    standardId: 'CH20-F019',
    chapter_id: 'ch-20',
    front: "When are employee evaluations commonly scheduled?",
    back: "About 90 days after hiring and then roughly once a year, though you can request feedback anytime.",
    category: "Barbershop Teamwork",
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch20-020',
    standardId: 'CH20-F020',
    chapter_id: 'ch-20',
    front: "What is the value of finding a role model in the barbershop?",
    back: "Observing and learning from a successful barber can guide your own performance, client care, and career growth.",
    category: "Barbershop Teamwork",
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Employment & Compensation (021–030)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch20-021',
    standardId: 'CH20-F021',
    chapter_id: 'ch-20',
    front: "What defines an employee in a barbershop?",
    back: "The shop controls work hours, how the job is performed, and withholds taxes; the worker receives a Form W-2.",
    category: "Employment & Compensation",
    difficulty: 'medium',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch20-022',
    standardId: 'CH20-F022',
    chapter_id: 'ch-20',
    front: "What defines an independent contractor in barbershop work?",
    back: "A self-employed worker with a written contract who handles own taxes, insurance, and receives a Form 1099 when earnings exceed $600.",
    category: "Employment & Compensation",
    difficulty: 'hard',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch20-023',
    standardId: 'CH20-F023',
    chapter_id: 'ch-20',
    front: "What is a booth renter arrangement?",
    back: "You lease space from the shop owner, run your own small business, set your own hours, and keep service revenue after paying rent.",
    category: "Employment & Compensation",
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch20-024',
    standardId: 'CH20-F024',
    chapter_id: 'ch-20',
    front: "How does straight commission compensation work?",
    back: "You earn a percentage of the gross service sales you generate, often after building a loyal clientele.",
    category: "Employment & Compensation",
    difficulty: 'medium',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-ch20-025',
    standardId: 'CH20-F025',
    chapter_id: 'ch-20',
    front: "What is salary-plus-commission, sometimes called a guarantee?",
    back: "A base salary plus a percentage of service revenue above that base, often used to motivate higher productivity.",
    category: "Employment & Compensation",
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch20-026',
    standardId: 'CH20-F026',
    chapter_id: 'ch-20',
    front: "What are the three common employment statuses for barbers?",
    back: "Employee, independent contractor, and booth renter.",
    category: "Employment & Compensation",
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch20-027',
    standardId: 'CH20-F027',
    chapter_id: 'ch-20',
    front: "What tax form does an employer provide to an employee?",
    back: "Form W-2, Wage and Tax Statement.",
    category: "Employment & Compensation",
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch20-028',
    standardId: 'CH20-F028',
    chapter_id: 'ch-20',
    front: "What tax form is provided to an independent contractor who earns over $600 in a year?",
    back: "Form 1099-MISC from the shop owner.",
    category: "Employment & Compensation",
    difficulty: 'medium',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-ch20-029',
    standardId: 'CH20-F029',
    chapter_id: 'ch-20',
    front: "Why must tips be tracked and reported as income?",
    back: "Tips are taxable income, and accurate reporting supports loan applications, Social Security benefits, and legal compliance.",
    category: "Employment & Compensation",
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-ch20-030',
    standardId: 'CH20-F030',
    chapter_id: 'ch-20',
    front: "What is a key difference between an employee and a booth renter?",
    back: "An employee has set hours and the shop schedules appointments, while a booth renter sets own hours, schedules own clients, and collects own revenue.",
    category: "Employment & Compensation",
    difficulty: 'hard',
    order_index: 30,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Financial Responsibility (031–040)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch20-031',
    standardId: 'CH20-F031',
    chapter_id: 'ch-20',
    front: "What income beyond your paycheck should be reported at tax time?",
    back: "Cash tips and any additional income from outside work, such as weddings or private appointments.",
    category: "Financial Responsibility",
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch20-032',
    standardId: 'CH20-F032',
    chapter_id: 'ch-20',
    front: "What is the best way to record tips and extra income?",
    back: "Keep a daily log, total it weekly and monthly, and keep a single annual summary page for tax reporting.",
    category: "Financial Responsibility",
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch20-033',
    standardId: 'CH20-F033',
    chapter_id: 'ch-20',
    front: "What are four serious consequences of not reporting income?",
    back: "Fines or legal action, reduced borrowing power, lower Social Security benefits, and damage to your professional reputation.",
    category: "Financial Responsibility",
    difficulty: 'hard',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch20-034',
    standardId: 'CH20-F034',
    chapter_id: 'ch-20',
    front: "What is the purpose of a personal monthly budget worksheet?",
    back: "It lists monthly expenses and income so you can see your balance and plan for savings, debt, and retirement.",
    category: "Financial Responsibility",
    difficulty: 'easy',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-ch20-035',
    standardId: 'CH20-F035',
    chapter_id: 'ch-20',
    front: "Why is sticking to a budget considered good lifelong practice?",
    back: "It helps ensure you always have enough money and lets you save for larger goals such as a home or your own business.",
    category: "Financial Responsibility",
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-ch20-036',
    standardId: 'CH20-F036',
    chapter_id: 'ch-20',
    front: "What is one non-obvious way to give yourself a raise?",
    back: "Reduce spending so more money remains after bills, which can be saved, invested, or used to pay down debt.",
    category: "Financial Responsibility",
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch20-037',
    standardId: 'CH20-F037',
    chapter_id: 'ch-20',
    front: "How can working more hours increase income in a barbershop?",
    back: "Choose busy times, come early, stay late, and work peak days like Saturday to accommodate more clients.",
    category: "Financial Responsibility",
    difficulty: 'easy',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch20-038',
    standardId: 'CH20-F038',
    chapter_id: 'ch-20',
    front: "When is it appropriate to increase your service prices?",
    back: "Once you have a loyal client base and have fully mastered your services, raising prices by a reasonable amount is acceptable.",
    category: "Financial Responsibility",
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch20-039',
    standardId: 'CH20-F039',
    chapter_id: 'ch-20',
    front: "How can retailing more products increase your income?",
    back: "Most shops pay commission on retail sales, so recommending and selling products adds to your earnings.",
    category: "Financial Responsibility",
    difficulty: 'easy',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-ch20-040',
    standardId: 'CH20-F040',
    chapter_id: 'ch-20',
    front: "How can barbershop technology help with financial management?",
    back: "Software can handle cash flow, inventory, payroll, appointments, and performance tracking, making record keeping easier.",
    category: "Financial Responsibility",
    difficulty: 'medium',
    order_index: 40,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Retailing & Upselling (041–050)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch20-041',
    standardId: 'CH20-F041',
    chapter_id: 'ch-20',
    front: "What is ticket upgrading, also called upselling?",
    back: "Recommending and selling additional services to a client during a visit.",
    category: "Retailing & Upselling",
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch20-042',
    standardId: 'CH20-F042',
    chapter_id: 'ch-20',
    front: "What is retailing in a barbershop?",
    back: "Recommending and selling products to clients for at-home use.",
    category: "Retailing & Upselling",
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-ch20-043',
    standardId: 'CH20-F043',
    chapter_id: 'ch-20',
    front: "What is the first step in successfully selling barbering products or services?",
    back: "Sell yourself by building client trust and identifying the client's needs before recommending anything.",
    category: "Retailing & Upselling",
    difficulty: 'medium',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch20-044',
    standardId: 'CH20-F044',
    chapter_id: 'ch-20',
    front: "How do soft-sell and hard-sell approaches differ?",
    back: "A soft sell informs the client without pressure; a hard sell emphatically focuses on why they should buy.",
    category: "Retailing & Upselling",
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch20-045',
    standardId: 'CH20-F045',
    chapter_id: 'ch-20',
    front: "What is the psychology of selling based on?",
    back: "Understanding the motives that drive a client to buy, such as looking better, feeling better, or solving a problem.",
    category: "Retailing & Upselling",
    difficulty: 'medium',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch20-046',
    standardId: 'CH20-F046',
    chapter_id: 'ch-20',
    front: "How should you overcome a client's price objection?",
    back: "Acknowledge the price, reiterate the product's benefits, and if appropriate offer a free sample.",
    category: "Retailing & Upselling",
    difficulty: 'hard',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch20-047',
    standardId: 'CH20-F047',
    chapter_id: 'ch-20',
    front: "What are the five points to remember when retailing?",
    back: "Establish rapport, determine needs, recommend based on those needs, emphasize benefits, and close the sale.",
    category: "Retailing & Upselling",
    difficulty: 'hard',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch20-048',
    standardId: 'CH20-F048',
    chapter_id: 'ch-20',
    front: "Why is it helpful to demonstrate a product when selling it?",
    back: "Demonstrating builds confidence, shows how to use the product, and makes the benefits tangible to the client.",
    category: "Retailing & Upselling",
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-ch20-049',
    standardId: 'CH20-F049',
    chapter_id: 'ch-20',
    front: "What should you avoid when recommending products or services?",
    back: "Never misrepresent or make unrealistic claims; honesty preserves trust and future sales.",
    category: "Retailing & Upselling",
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch20-050',
    standardId: 'CH20-F050',
    chapter_id: 'ch-20',
    front: "What should you do once a client agrees to buy a product or service?",
    back: "Stop selling, praise the decision, and assure the client they will be happy with the purchase.",
    category: "Retailing & Upselling",
    difficulty: 'easy',
    order_index: 50,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Client Base & Marketing (051–060)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch20-051',
    standardId: 'CH20-F051',
    chapter_id: 'ch-20',
    front: "How can birthday cards help build a client base?",
    back: "Send a card with a special birthday-month offer to encourage clients to return to the shop.",
    category: "Client Base & Marketing",
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-ch20-052',
    standardId: 'CH20-F052',
    chapter_id: 'ch-20',
    front: "What is the foundation of keeping current clients?",
    back: "Providing consistently good service every visit; rushing or cutting corners drives clients away.",
    category: "Client Base & Marketing",
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-ch20-053',
    standardId: 'CH20-F053',
    chapter_id: 'ch-20',
    front: "What behaviors make a barber reliable and worthy of respect?",
    back: "Being courteous, professional, on time, keeping promises, avoiding gossip, and maintaining a positive attitude.",
    category: "Client Base & Marketing",
    difficulty: 'medium',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-ch20-054',
    standardId: 'CH20-F054',
    chapter_id: 'ch-20',
    front: "How can social media help build your barbering clientele?",
    back: "Platforms like Facebook and Yelp let you showcase work, share tips, and gather client reviews with permission.",
    category: "Client Base & Marketing",
    difficulty: 'medium',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-ch20-055',
    standardId: 'CH20-F055',
    chapter_id: 'ch-20',
    front: "How do business-card referrals reward loyal clients?",
    back: "Give clients cards to share with friends; offer a discount or complimentary add-on when a new client brings one in.",
    category: "Client Base & Marketing",
    difficulty: 'medium',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-ch20-056',
    standardId: 'CH20-F056',
    chapter_id: 'ch-20',
    front: "What is a local business referral partnership?",
    back: "Swapping referrals with nearby businesses such as gyms, tailors, or cigar shops to build community and reach new clients.",
    category: "Client Base & Marketing",
    difficulty: 'medium',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-ch20-057',
    standardId: 'CH20-F057',
    chapter_id: 'ch-20',
    front: "How can public speaking help grow your client base?",
    back: "Offering short grooming or professional-appearance talks to local groups puts you in front of potential clients.",
    category: "Client Base & Marketing",
    difficulty: 'medium',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-ch20-058',
    standardId: 'CH20-F058',
    chapter_id: 'ch-20',
    front: "When is the best time to rebook a client?",
    back: "While the client is still in the shop, discussing their hair needs and the benefits of regular maintenance.",
    category: "Client Base & Marketing",
    difficulty: 'easy',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-ch20-059',
    standardId: 'CH20-F059',
    chapter_id: 'ch-20',
    front: "How does efficiency increase your income in a barbershop?",
    back: "As skill grows, services take less time, reducing client wait times and allowing more appointments per day.",
    category: "Client Base & Marketing",
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-ch20-060',
    standardId: 'CH20-F060',
    chapter_id: 'ch-20',
    front: "What attitude should a new barber maintain when starting out?",
    back: "Be patient, practice consistently, seek advice from experienced professionals, and always be willing to learn.",
    category: "Client Base & Marketing",
    difficulty: 'easy',
    order_index: 60,
    is_active: true,
  },
]
