import { QuizQuestion } from '@/types'

// Chapter 20: Working Behind the Chair — 17 premium quiz questions
export const chapter20PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-20-01',
    standardId: 'CH20-Q01',
    quiz_id: 'quiz-20',
    question: "What is the biggest adjustment a new barber must make when transitioning from school to work?",
    answer_a: "Learning to work faster without regard for quality",
    answer_b: "Putting the needs of the barbershop and its clients ahead of personal convenience",
    answer_c: "Switching from practical training to purely theoretical study",
    answer_d: "Working without any supervision or feedback",
    correct_answer: 'b',
    explanation: "Common mistake: Thinking the main change is simply working faster or independently. Correct understanding: In school, mistakes are accepted and schedules can be flexible, but at work the barber must put the shop and clients first, arriving on time and prepared regardless of personal circumstances. Why it matters: Clients who are inconvenienced may not return, and coworkers asked to absorb your appointments may resent the added burden. Review: From Student to Professional.",
    difficulty: 'easy',
    learningObjective: 'CH20-LO01',
    order_index: 1,
  },
  {
    id: 'qq-20-02',
    standardId: 'CH20-Q02',
    quiz_id: 'quiz-20',
    question: "A new barber is offered concert tickets for a day she is scheduled to work. According to ASCYN PRO guidance, what is the most professional response?",
    answer_a: "Take the day off; personal enjoyment is part of work-life balance.",
    answer_b: "Trade shifts with a coworker without telling management.",
    answer_c: "Honor the scheduled shift because clients and coworkers depend on her.",
    answer_d: "Call in sick to avoid a direct conflict.",
    correct_answer: 'c',
    explanation: "Common mistake: Believing that occasional personal events justify missing scheduled work. Correct understanding: Taking the day off would inconvenience clients who may decide not to return and burden coworkers who must cover the appointments. Why it matters: Reliability builds trust with clients, the team, and management and is a cornerstone of professional behavior. Review: From Student to Professional.",
    difficulty: 'medium',
    learningObjective: 'CH20-LO01',
    order_index: 2,
  },
  {
    id: 'qq-20-03',
    standardId: 'CH20-Q03',
    quiz_id: 'quiz-20',
    question: "If a barbershop does not provide a written job description, what should a new employee do?",
    answer_a: "Assume duties are whatever the manager says each day.",
    answer_b: "Write one for herself and present it to the manager for review.",
    answer_c: "Wait several months and then formally request one.",
    answer_d: "Refuse to perform any task not listed in writing.",
    correct_answer: 'b',
    explanation: "Common mistake: Waiting passively or treating the absence of a job description as an excuse to avoid tasks. Correct understanding: A job description outlines duties, responsibilities, attitudes, and opportunities; if the shop does not use one, the new employee can draft it and review it with the manager to ensure mutual understanding. Why it matters: Clear expectations reduce conflict, protect both parties, and influence future opportunities and financial rewards. Review: From Student to Professional.",
    difficulty: 'medium',
    learningObjective: 'CH20-LO01',
    order_index: 3,
  },
  {
    id: 'qq-20-04',
    standardId: 'CH20-Q04',
    quiz_id: 'quiz-20',
    question: "Which workplace principle best describes being willing to fold towels, make appointments, or help with tasks when not busy servicing clients?",
    answer_a: "Strive to help",
    answer_b: "Pitch in",
    answer_c: "Share your knowledge",
    answer_d: "Remain positive",
    correct_answer: 'b',
    explanation: "Common mistake: Confusing general helpfulness with the specific habit of doing whatever needs doing around the shop. Correct understanding: 'Pitch in' means being willing to help with whatever needs to be done, from folding towels to booking appointments, when you are not with a client. Why it matters: Team members who pitch in keep the shop running smoothly and demonstrate that the success of the business matters to them. Review: Habits of a Good Barbershop Team Player.",
    difficulty: 'easy',
    learningObjective: 'CH20-LO02',
    order_index: 4,
  },
  {
    id: 'qq-20-05',
    standardId: 'CH20-Q05',
    quiz_id: 'quiz-20',
    question: "When conflict arises with a coworker, what does ASCYN PRO guidance identify as the behavior of a true teammate?",
    answer_a: "Discuss the conflict with others in the shop to gain support.",
    answer_b: "Ignore the conflict until it resolves itself.",
    answer_c: "Address the conflict directly with the individual and work toward resolution.",
    answer_d: "Ask the manager to mediate every disagreement immediately.",
    correct_answer: 'c',
    explanation: "Common mistake: Venting to others or avoiding conflict altogether. Correct understanding: A real teammate knows that conflict and tension harm everyone involved and the shop as a whole, so she discusses the issue with the individual and works constructively toward resolution. Why it matters: Handling conflict professionally preserves working relationships, morale, and the shop's reputation. Review: Habits of a Good Barbershop Team Player.",
    difficulty: 'medium',
    learningObjective: 'CH20-LO02',
    order_index: 5,
  },
  {
    id: 'qq-20-06',
    standardId: 'CH20-Q06',
    quiz_id: 'quiz-20',
    question: "Why is being willing to 'be subordinate' considered an important team-building characteristic?",
    answer_a: "It means never questioning management decisions.",
    answer_b: "It recognizes that beginners usually start lower in the shop hierarchy and must earn their place.",
    answer_c: "It requires accepting lower pay indefinitely.",
    answer_d: "It prevents conflict by suppressing all personal opinions.",
    correct_answer: 'b',
    explanation: "Common mistake: Interpreting subordination as blind obedience or permanent low status. Correct understanding: No one starts at the top; beginners almost always start lower in the pecking order, and accepting this reality helps them learn and grow within the team. Why it matters: A willingness to be subordinate demonstrates humility, respect for experience, and a commitment to earning advancement over time. Review: Habits of a Good Barbershop Team Player.",
    difficulty: 'hard',
    learningObjective: 'CH20-LO02',
    order_index: 6,
  },
  {
    id: 'qq-20-07',
    standardId: 'CH20-Q07',
    quiz_id: 'quiz-20',
    question: "Which statement correctly distinguishes an independent contractor from a booth renter?",
    answer_a: "Independent contractors are employees of the shop; booth renters are self-employed.",
    answer_b: "Independent contractors may work for a percentage of proceeds; booth renters lease space and operate a small business.",
    answer_c: "Both receive Form W-2 from the shop owner.",
    answer_d: "Neither is responsible for their own taxes or insurance.",
    correct_answer: 'b',
    explanation: "Common mistake: Lumping independent contractors and booth renters together as identical self-employed categories. Correct understanding: Independent contractors may rent a chair or work for a percentage of service proceeds, while booth renters lease space and run their own small business with their own clientele, supplies, and accounting. Why it matters: The classification determines tax responsibilities, required contracts, and who controls scheduling and client records. Review: Employment Classifications and Compensation.",
    difficulty: 'medium',
    learningObjective: 'CH20-LO03',
    order_index: 7,
  },
  {
    id: 'qq-20-08',
    standardId: 'CH20-Q08',
    quiz_id: 'quiz-20',
    question: "Under a salary-plus-commission compensation arrangement, how is total pay typically calculated?",
    answer_a: "A flat hourly rate regardless of service sales.",
    answer_b: "A percentage of gross service sales only.",
    answer_c: "A guaranteed base salary plus a percentage of the amount earned over the base.",
    answer_d: "A fixed weekly rent payment deducted from service revenue.",
    correct_answer: 'c',
    explanation: "Common mistake: Confusing salary-plus-commission with straight commission or hourly wage. Correct understanding: Salary-plus-commission, sometimes called a guarantee, provides a minimum base salary plus a percentage of the amount generated over that base. Why it matters: This structure motivates employees to perform more services while still providing income security as they build a clientele. Review: Employment Classifications and Compensation.",
    difficulty: 'medium',
    learningObjective: 'CH20-LO03',
    order_index: 8,
  },
  {
    id: 'qq-20-09',
    standardId: 'CH20-Q09',
    quiz_id: 'quiz-20',
    question: "A barber works as a booth renter. Which responsibility most clearly belongs to her rather than the shop owner?",
    answer_a: "Withholding federal income taxes from her paycheck.",
    answer_b: "Booking her own appointments, collecting service revenue, and maintaining her own accounting.",
    answer_c: "Providing Form W-2 to the shop owner.",
    answer_d: "Setting the shop's operating hours for all barbers.",
    correct_answer: 'b',
    explanation: "Common mistake: Assuming the shop owner still handles scheduling, payments, and taxes for booth renters. Correct understanding: A booth renter leases space and is solely responsible for her own clientele, supplies, record keeping, workstation maintenance, accounting, and tax payments. Why it matters: Misunderstanding booth-renter responsibilities can lead to tax problems, cash-flow issues, and disputes with the shop owner. Review: Employment Classifications and Compensation.",
    difficulty: 'hard',
    learningObjective: 'CH20-LO03',
    order_index: 9,
  },
  {
    id: 'qq-20-10',
    standardId: 'CH20-Q10',
    quiz_id: 'quiz-20',
    question: "Why should barbers accurately report tips and cash income on their tax returns?",
    answer_a: "Tips are not considered taxable income.",
    answer_b: "Reporting income is only required for employees, not booth renters.",
    answer_c: "Accurate reporting strengthens borrowing power and increases Social Security benefits.",
    answer_d: "The IRS does not track small cash payments.",
    correct_answer: 'c',
    explanation: "Common mistake: Believing cash tips are invisible income that does not need to be reported. Correct understanding: Tips are income in addition to regular compensation and must be tracked and reported; failure to report can lead to fines, legal action, reduced borrowing power, and lower Social Security benefits. Why it matters: Accurate reporting protects the barber legally and makes true income visible for loans, retirement, and professional credibility. Review: Manage Your Money.",
    difficulty: 'easy',
    learningObjective: 'CH20-LO04',
    order_index: 10,
  },
  {
    id: 'qq-20-11',
    standardId: 'CH20-Q11',
    quiz_id: 'quiz-20',
    question: "What is the recommended method for tracking tips and additional income?",
    answer_a: "Estimate the amounts at the end of the year.",
    answer_b: "Keep a daily log, weekly totals, monthly summary, and yearly total.",
    answer_c: "Only record income shown on a paycheck.",
    answer_d: "Report only amounts over $100 per transaction.",
    correct_answer: 'b',
    explanation: "Common mistake: Relying on memory or only tracking paycheck income. Correct understanding: The best practice is to keep a daily log of tips and additional income, add weekly totals, maintain a monthly summary on a single page, and use the yearly total for tax reporting. Why it matters: A consistent system makes year-end reporting easy, accurate, and defensible if income is ever questioned. Review: Manage Your Money.",
    difficulty: 'medium',
    learningObjective: 'CH20-LO04',
    order_index: 11,
  },
  {
    id: 'qq-20-12',
    standardId: 'CH20-Q12',
    quiz_id: 'quiz-20',
    question: "Which strategy for 'giving yourself a raise' requires both a loyal client base and mastery of the services performed?",
    answer_a: "Working more hours during peak times.",
    answer_b: "Spending less money on personal expenses.",
    answer_c: "Increasing service prices.",
    answer_d: "Selling more retail products.",
    correct_answer: 'c',
    explanation: "Common mistake: Thinking price increases are available as soon as a barber is licensed. Correct understanding: Raising service prices is appropriate only after a barber has built a loyal client base and fully mastered the services offered; prices should be increased by a reasonable amount every year or two based on competitor research. Why it matters: Raising prices too early or too sharply can drive clients away; doing it at the right time rewards skill and loyalty. Review: Manage Your Money.",
    difficulty: 'hard',
    learningObjective: 'CH20-LO04',
    order_index: 12,
  },
  {
    id: 'qq-20-13',
    standardId: 'CH20-Q13',
    quiz_id: 'quiz-20',
    question: "What is the best first step in successfully selling retail products or services to a client?",
    answer_a: "Memorize a single sales script and use it with every client.",
    answer_b: "Establish rapport and identify the client's specific needs.",
    answer_c: "Recommend the most expensive product to maximize commission.",
    answer_d: "Focus on making the sale before building trust.",
    correct_answer: 'b',
    explanation: "Common mistake: Treating selling as a one-size-fits-all pitch or pushy transaction. Correct understanding: The first step in selling is to sell yourself; clients must like and trust you before they buy. Successful selling begins with rapport, recognizing needs, and recommending only products or services that truly address those needs. Why it matters: Client-centered selling creates repeat business, protects the barber's reputation, and turns retailing into genuine service. Review: Ethical Selling Behind the Chair.",
    difficulty: 'medium',
    learningObjective: 'CH20-LO05',
    order_index: 13,
  },
  {
    id: 'qq-20-14',
    standardId: 'CH20-Q14',
    quiz_id: 'quiz-20',
    question: "A client objects that he already owns shampoo for color-treated hair. Which response best applies ASCYN PRO guidance on selling?",
    answer_a: "Insist the recommended product is superior and refuse to take no for an answer.",
    answer_b: "Acknowledge his product and restate the objection by emphasizing added moisture and shine benefits.",
    answer_c: "Stop discussing products because the client has clearly made up his mind.",
    answer_d: "Offer the product at a steep discount regardless of need.",
    correct_answer: 'b',
    explanation: "Common mistake: Either giving up at the first objection or pressuring the client aggressively. Correct understanding: Overcoming objections involves restating the objection in a way that addresses the client's need—acknowledging what he said and then explaining how the recommended product solves an additional problem, such as added moisture and shine. Why it matters: Handling objections with respect keeps the conversation client-focused and increases the chance of a satisfied purchase. Review: Ethical Selling Behind the Chair.",
    difficulty: 'hard',
    learningObjective: 'CH20-LO05',
    order_index: 14,
  },
  {
    id: 'qq-20-15',
    standardId: 'CH20-Q15',
    quiz_id: 'quiz-20',
    question: "Which technique is most effective for rebooking clients and maintaining a loyal client base?",
    answer_a: "Waiting until clients call to schedule their next appointment.",
    answer_b: "Discussing their next visit while they are still in the chair.",
    answer_c: "Only contacting clients when business is slow.",
    answer_d: "Asking clients to refer friends before providing service.",
    correct_answer: 'b',
    explanation: "Common mistake: Treating rebooking as an afterthought or waiting for the client to take the initiative. Correct understanding: The best time to think about getting clients back into the shop is while they are still in the chair; talking about their hair condition, home care, and the benefits of regular maintenance naturally leads to booking the next appointment. Why it matters: Proactive rebooking keeps the chair full, builds loyalty, and prevents clients from drifting to competitors. Review: Keep Current Clients and Expand Your Client Base.",
    difficulty: 'medium',
    learningObjective: 'CH20-LO06',
    order_index: 15,
  },
  {
    id: 'qq-20-16',
    standardId: 'CH20-Q16',
    quiz_id: 'quiz-20',
    question: "Which strategy helps a barber reach new clients by building mutually beneficial relationships with nearby businesses?",
    answer_a: "Posting daily price lists in the shop window",
    answer_b: "Creating local business referral partnerships",
    answer_c: "Requiring existing clients to bring a friend to every visit",
    answer_d: "Lowering all service prices below competitor rates",
    correct_answer: 'b',
    explanation: "Common mistake: Thinking client growth depends only on advertising or discounting. Correct understanding: Local business referral partnerships—such as swapping referrals with gyms, tailors, diners, or cigar shops—introduce your services to people who already trust another business in the community. Why it matters: Cross-promotion builds credibility, strengthens community ties, and creates a steady stream of referrals without heavy advertising costs. Review: Keep Current Clients and Expand Your Client Base.",
    difficulty: 'medium',
    learningObjective: 'CH20-LO06',
    order_index: 16,
  },
  {
    id: 'qq-20-17',
    standardId: 'CH20-Q17',
    quiz_id: 'quiz-20',
    question: "When posting client photos on social media to market barbering services, what is the most important rule?",
    answer_a: "Use flattering lighting and professional filters.",
    answer_b: "Tag the client so their network sees the post.",
    answer_c: "Get the client's permission before posting.",
    answer_d: "Include as many trending hashtags as possible.",
    correct_answer: 'c',
    explanation: "Common mistake: Treating social media visibility as more important than client trust. Correct understanding: Client privacy and consent come first. Always get permission—preferably written—before posting any photo that shows a client's face or identifiable features. Why it matters: Respecting consent protects the client's privacy, builds trust, and prevents legal or ethical problems that could damage your reputation. Review: Keep Current Clients and Expand Your Client Base.",
    difficulty: 'easy',
    learningObjective: 'CH20-LO06',
    order_index: 17,
  },
]
