import { Flashcard } from '@/types'

// Chapter 12: Men's Facial Massage and Treatments
// Created strictly from Chapter 12 textbook images
// All content sourced from: textbook-images/chapter-12/

export const chapter12PremiumFlashcards: Flashcard[] = [
  // === LEARNING OBJECTIVES & INTRODUCTION ===
  {
    id: 'fc-ch12-001',
    chapter_id: 'ch-12',
    front: 'Why should barbers study men\'s facial massage and treatments?',
    back: 'Barbers need to be competent in all licensed services. Men increasingly want facial massage benefits. Regular facials improve skin tone, texture, and appearance, leading to repeat clients and referrals. Facials are also finishing steps after a shave.',
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch12-002',
    chapter_id: 'ch-12',
    front: 'What percentage of skin care clientele in spas and salons are male?',
    back: 'About 20 percent, and this percentage is expected to grow.',
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },

  // === SUBDERMAL SYSTEMS ===
  {
    id: 'fc-ch12-003',
    chapter_id: 'ch-12',
    front: 'What are the three subdermal systems associated with facial treatments?',
    back: 'Muscles, nerves, and arteries. Muscles produce movement, nerves carry messages, and arteries transport blood under high pressure.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch12-004',
    chapter_id: 'ch-12',
    front: 'What is the definition of a muscle?',
    back: 'Fibrous tissues that have the ability to stretch and contract to produce all body movements.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch12-005',
    chapter_id: 'ch-12',
    front: 'What is the definition of a nerve?',
    back: 'Long, white, fibrous cords that act as message carriers from the brain and spinal column to and from all parts of the body.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-ch12-006',
    chapter_id: 'ch-12',
    front: 'What is the definition of an artery?',
    back: 'Elastic, muscular, thick-walled blood vessels that transport blood under high pressure.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch12-007',
    chapter_id: 'ch-12',
    front: 'What is the definition of a vein?',
    back: 'Thin-walled vessels that contain valves that keep the blood flowing to the heart and prevent it from flowing backward.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },

  // === MUSCLES ===
  {
    id: 'fc-ch12-008',
    chapter_id: 'ch-12',
    front: 'What is the epicranius (occipitofrontalis)?',
    back: 'A broad muscle that covers the top of the skull. It consists of the frontalis at the front and the occipitalis at the back, connected by the epicranial aponeurosis.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch12-009',
    chapter_id: 'ch-12',
    front: 'What does the frontalis muscle do?',
    back: 'Draws the scalp forward and causes wrinkles across the forehead.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-ch12-010',
    chapter_id: 'ch-12',
    front: 'What does the occipitalis muscle do?',
    back: 'Draws the scalp backward.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-ch12-011',
    chapter_id: 'ch-12',
    front: 'What is the epicranial aponeurosis?',
    back: 'The tendon that connects the occipitalis and frontalis muscles.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch12-012',
    chapter_id: 'ch-12',
    front: 'What does the orbicularis oculi muscle do?',
    back: 'Surrounds the eye socket and closes the eyelid.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-ch12-013',
    chapter_id: 'ch-12',
    front: 'What does the corrugator muscle do?',
    back: 'Draws the eyebrows down and in, and wrinkles the forehead vertically.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch12-014',
    chapter_id: 'ch-12',
    front: 'What does the procerus muscle do?',
    back: 'Covers the top of the nose, depresses the eyebrow, and causes wrinkles across the bridge of the nose.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch12-015',
    chapter_id: 'ch-12',
    front: 'What does the buccinator muscle do?',
    back: 'A thin, flat muscle between the upper and lower jaws that compresses the cheeks and expels air between the lips.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch12-016',
    chapter_id: 'ch-12',
    front: 'What does the orbicularis oris muscle do?',
    back: 'A flat band of muscle around the upper and lower lips that compresses, contracts, puckers, and wrinkles the lips.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch12-017',
    chapter_id: 'ch-12',
    front: 'What does the masseter muscle do?',
    back: 'Coordinates opening and closing of the mouth; a chewing muscle.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-ch12-018',
    chapter_id: 'ch-12',
    front: 'What does the temporalis muscle do?',
    back: 'Coordinates opening and closing of the mouth; a chewing muscle that works with the masseter.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch12-019',
    chapter_id: 'ch-12',
    front: 'What does the platysma muscle do?',
    back: 'A broad muscle extending from the chest and shoulder muscles to the side of the chin; responsible for depressing the lower jaw and lip.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch12-020',
    chapter_id: 'ch-12',
    front: 'What does the sternocleidomastoideus muscle do?',
    back: 'Extends from the collar and chest bones to the temporal bone behind the ear; bends and rotates the head.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-ch12-021',
    chapter_id: 'ch-12',
    front: 'What does the trapezius muscle do?',
    back: 'Covers the back of the neck, allowing movement of the shoulders.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch12-022',
    chapter_id: 'ch-12',
    front: 'What does the zygomaticus major muscle do?',
    back: 'Pulls the mouth upward and backward, as when laughing or smiling.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch12-023',
    chapter_id: 'ch-12',
    front: 'What does the mentalis muscle do?',
    back: 'Elevates the lower lip and raises and wrinkles the skin of the chin.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch12-024',
    chapter_id: 'ch-12',
    front: 'What does the risorius muscle do?',
    back: 'Draws the corner of the mouth out and back, as when grinning.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 24,
    is_active: true,
  },

  // === CRANIAL NERVES ===
  {
    id: 'fc-ch12-025',
    chapter_id: 'ch-12',
    front: 'How many pairs of cranial nerves are there?',
    back: '12 pairs, all connected to a part of the brain surface.',
    category: 'Nerves',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch12-026',
    chapter_id: 'ch-12',
    front: 'What is the fifth cranial nerve (trigeminal nerve)?',
    back: 'The chief sensory nerve of the face that also serves as the motor nerve that controls chewing.',
    category: 'Nerves',
    difficulty: 'medium',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch12-027',
    chapter_id: 'ch-12',
    front: 'What is the seventh cranial nerve (facial nerve)?',
    back: 'The sensory-motor nerve that controls motions of the face, scalp, and neck and sections of the palate and tongue.',
    category: 'Nerves',
    difficulty: 'medium',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch12-028',
    chapter_id: 'ch-12',
    front: 'What is the eleventh cranial nerve (accessory nerve)?',
    back: 'The motor nerve that controls motions of the neck muscles.',
    category: 'Nerves',
    difficulty: 'medium',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-ch12-029',
    chapter_id: 'ch-12',
    front: 'What are cervical nerves?',
    back: 'Spinal nerves that originate at the spinal cord; their branches supply the muscles and scalp at the back of the head and neck.',
    category: 'Nerves',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },

  // === ARTERIES & VEINS ===
  {
    id: 'fc-ch12-030',
    chapter_id: 'ch-12',
    front: 'What are the common carotid arteries?',
    back: 'The main sources of blood supply to the head, face, and neck; located at the sides of the neck.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-ch12-031',
    chapter_id: 'ch-12',
    front: 'What does the external maxillary (facial) artery supply?',
    back: 'The lower region of the face, mouth, and nose.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch12-032',
    chapter_id: 'ch-12',
    front: 'What does the superficial temporal artery supply?',
    back: 'Muscles, skin, and scalp on the front, side, and top of the head.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch12-033',
    chapter_id: 'ch-12',
    front: 'What does the occipital artery supply?',
    back: 'The scalp and back of the head up to the crown.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch12-034',
    chapter_id: 'ch-12',
    front: 'What does the posterior auricular artery supply?',
    back: 'The scalp behind and above the ear.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-ch12-035',
    chapter_id: 'ch-12',
    front: 'How does deoxygenated blood from the head, face, and neck return to the heart?',
    back: 'Through the internal jugular and external jugular veins located on each side of the neck.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },

  // === PHYSIOLOGICAL EFFECTS OF MASSAGE ===
  {
    id: 'fc-ch12-036',
    chapter_id: 'ch-12',
    front: 'What are the beneficial results of proper massage?',
    back: 'Nourishes skin structures, stimulates and strengthens muscle fiber, soothes and rests nerves, reduces fat cells, increases blood circulation, stimulates gland activity, softens skin, and sometimes relieves pain.',
    category: 'Massage Theory',
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch12-037',
    chapter_id: 'ch-12',
    front: 'What factors determine the benefits of a massage manipulation?',
    back: 'The type of massage movement used, the amount of pressure used, the direction of the movement, and the duration of the manipulation.',
    category: 'Massage Theory',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch12-038',
    chapter_id: 'ch-12',
    front: 'What is a motor point?',
    back: 'A point on the skin where nerves that control the underlying muscle are located. When electrical stimulation is applied, the muscle responds by contracting.',
    category: 'Massage Theory',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch12-039',
    chapter_id: 'ch-12',
    front: 'What is a trigger point?',
    back: 'A tender area in a muscle caused by a localized knot or spasm in the muscle fiber that can radiate pain to other locations. It is hypersensitive to electrical stimulation and pressure.',
    category: 'Massage Theory',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },

  // === MASSAGE MANIPULATIONS ===
  {
    id: 'fc-ch12-040',
    chapter_id: 'ch-12',
    front: 'What is effleurage?',
    back: 'A light, continuous stroking movement applied slowly and rhythmically over the skin with no pressure. Palms are used over large surfaces; fingertips work small surfaces like around the eyes.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-ch12-041',
    chapter_id: 'ch-12',
    front: 'What is petrissage?',
    back: 'A kneading movement performed with light, firm pressure. The skin and flesh are grasped between the thumb and fingers, then gently squeezed, rolled, or pinched. Provides deeper stimulation to muscles, nerves, and skin glands.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch12-042',
    chapter_id: 'ch-12',
    front: 'What is friction?',
    back: 'A deep rubbing movement in which pressure is applied on the skin with the fingers or palms while moving over an underlying structure. Light circular friction is used on the face and neck.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-ch12-043',
    chapter_id: 'ch-12',
    front: 'What is percussion (tapotement)?',
    back: 'Short, quick tapping, slapping, or hacking movements used to stimulate nerves, tone muscles, and impart a healthy glow. The most stimulating form of massage.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch12-044',
    chapter_id: 'ch-12',
    front: 'What are the three forms of tapotement?',
    back: 'Tapping (gentlest, fingertips down), slapping (lower to mid-fingers strike lightly), and hacking/chopping (outer edges of hands, used only on back and shoulders).',
    category: 'Massage Movements',
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch12-045',
    chapter_id: 'ch-12',
    front: 'What is vibration?',
    back: 'A rapid shaking movement over the skin section with the fingertips or an electric massager. Used to transmit a trembling movement to the skin and underlying structures.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch12-046',
    chapter_id: 'ch-12',
    front: 'How long should vibration be used on any one area?',
    back: 'Not more than a few seconds to avoid overstimulation.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch12-047',
    chapter_id: 'ch-12',
    front: 'What direction should massage pressure be applied on the face?',
    back: 'In an upward direction to avoid loss of skin resiliency. When facial hair is present, direct movements in the direction of beard growth.',
    category: 'Massage Guidelines',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch12-048',
    chapter_id: 'ch-12',
    front: 'What is the correct direction for massage movements relative to muscle attachment?',
    back: 'From the insertion (attachment to movable bone) toward the origin (attachment to immovable bone).',
    category: 'Massage Guidelines',
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-ch12-049',
    chapter_id: 'ch-12',
    front: 'What is feathering-off?',
    back: 'Gradually reducing pressure when removing hands from the client\'s face to gently lift from the skin surface.',
    category: 'Massage Guidelines',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch12-050',
    chapter_id: 'ch-12',
    front: 'What conditions contraindicate massage?',
    back: 'Acute inflammation of the skin, severe skin lesions, pus-containing pimples, high blood pressure, and skin infections.',
    category: 'Massage Guidelines',
    difficulty: 'easy',
    order_index: 50,
    is_active: true,
  },
  {
    id: 'fc-ch12-051',
    chapter_id: 'ch-12',
    front: 'How often can normal skin or scalp be kept in good condition with treatments?',
    back: 'Weekly treatments with proper home care.',
    category: 'Massage Guidelines',
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },

  // === FACIAL EQUIPMENT ===
  {
    id: 'fc-ch12-052',
    chapter_id: 'ch-12',
    front: 'What is an electric massager?',
    back: 'A handheld unit that transmits vibrations through the barber\'s hand and fingertips to the client\'s skin and muscles. Used over heavy muscle tissue like the scalp and shoulders.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-ch12-053',
    chapter_id: 'ch-12',
    front: 'What are the effects of an electric massager?',
    back: 'Invigorates muscle tissue, increases blood supply, soothes nerves, increases glandular activity, and stimulates skin and scalp.',
    category: 'Equipment',
    difficulty: 'medium',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-ch12-054',
    chapter_id: 'ch-12',
    front: 'When should an electric massager NOT be used?',
    back: 'When the client has a known weakness of the heart, fever, abscesses, or skin inflammations.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-ch12-055',
    chapter_id: 'ch-12',
    front: 'What is a brush machine?',
    back: 'An electrical appliance with interchangeable brushes that attach to a rotating head. Used for mechanical exfoliation to stimulate, cleanse, and remove dead cells.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-ch12-056',
    chapter_id: 'ch-12',
    front: 'When should brushing NOT be performed?',
    back: 'On skin that has been treated with Retin-A or other drugs that thin or exfoliate the skin.',
    category: 'Equipment',
    difficulty: 'medium',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-ch12-057',
    chapter_id: 'ch-12',
    front: 'What is a facial steamer?',
    back: 'An electrical appliance that produces and projects moist, uniform steam to soften and cleanse the skin. Warms skin, stimulates circulation, induces sebum and sweat flow, and has an antiseptic effect.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-ch12-058',
    chapter_id: 'ch-12',
    front: 'What type of water should be used in a facial steamer?',
    back: 'Only distilled or filtered water to avoid mineral and calcium deposits that can damage the unit.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-ch12-059',
    chapter_id: 'ch-12',
    front: 'What is a hot-towel cabinet used for?',
    back: 'Ensures a ready supply of warm towels for facial services. Towels are folded, dampened with hot water, wrung out, and placed in the cabinet.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 59,
    is_active: true,
  },

  // === ELECTROTHERAPY ===
  {
    id: 'fc-ch12-060',
    chapter_id: 'ch-12',
    front: 'What are the two electrotherapy modalities most often used in facial treatments?',
    back: 'High-frequency current and galvanic current.',
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-ch12-061',
    chapter_id: 'ch-12',
    front: 'What is an electrode?',
    back: 'A device used to apply and direct electrical current to the client\'s skin. High-frequency uses one electrode; galvanic uses two (positive anode and negative cathode).',
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-ch12-062',
    chapter_id: 'ch-12',
    front: 'What is high-frequency current (tesla current)?',
    back: 'A current characterized by a high rate of oscillation used for scalp and facial treatments. Primary actions are thermal and antiseptic.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 62,
    is_active: true,
  },
  {
    id: 'fc-ch12-063',
    chapter_id: 'ch-12',
    front: 'What are the benefits of high-frequency current on the skin?',
    back: 'Stimulates blood circulation, helps oxygenate skin, increases glandular activity, aids elimination and absorption, increases cell metabolism, promotes antiseptic action, and generates warmth.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-ch12-064',
    chapter_id: 'ch-12',
    front: 'How long should a general high-frequency facial or scalp treatment last?',
    back: 'No more than 5 minutes.',
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 64,
    is_active: true,
  },
  {
    id: 'fc-ch12-065',
    chapter_id: 'ch-12',
    front: 'What are the two primary methods of high-frequency application?',
    back: 'Direct surface application (most common in barbershops, calming and germicidal) and indirect application (client holds electrode, toning and stimulating).',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-ch12-066',
    chapter_id: 'ch-12',
    front: 'What are the contraindications for high-frequency current?',
    back: 'Pregnancy, seizures/epilepsy, asthma, high blood pressure, acne, sinus blockage, pacemaker, and metal implants.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-ch12-067',
    chapter_id: 'ch-12',
    front: 'How should high-frequency electrodes be cleaned?',
    back: 'Wipe glass with soap and water (do not immerse). Place only the end in disinfectant for 20 minutes. Rinse with cool water without wetting metal parts. Dry and store in a clean, covered container.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-ch12-068',
    chapter_id: 'ch-12',
    front: 'What does a galvanic machine do?',
    back: 'Converts alternating current from an outlet into direct current. Produces chemical (desincrustation) and ionic (iontophoresis) reactions in the skin. Beneficial for oily skin and acne.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-ch12-069',
    chapter_id: 'ch-12',
    front: 'What is desincrustation?',
    back: 'A galvanic treatment to facilitate deep pore cleansing. An acid-based solution is applied; a chemical reaction emulsifies sebum and waste for easy extraction.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-ch12-070',
    chapter_id: 'ch-12',
    front: 'What is iontophoresis?',
    back: 'Using galvanic current to enable ion-containing water-soluble solutions to penetrate the skin. Negative current allows negative ions to penetrate; positive current allows positive ions to penetrate.',
    category: 'Electrotherapy',
    difficulty: 'hard',
    order_index: 70,
    is_active: true,
  },
  {
    id: 'fc-ch12-071',
    chapter_id: 'ch-12',
    front: 'What is cataphoresis?',
    back: 'Use of the positive pole (anode) to introduce acid-pH products into the skin. May also close follicles, decrease redness, prevent inflammation, soothe nerves, and harden tissues.',
    category: 'Electrotherapy',
    difficulty: 'hard',
    order_index: 71,
    is_active: true,
  },
  {
    id: 'fc-ch12-072',
    chapter_id: 'ch-12',
    front: 'What is anaphoresis?',
    back: 'Use of the negative pole (cathode) to force alkaline-pH products into the skin. May stimulate circulation, stimulate nerves, and soften tissues.',
    category: 'Electrotherapy',
    difficulty: 'hard',
    order_index: 72,
    is_active: true,
  },
  {
    id: 'fc-ch12-073',
    chapter_id: 'ch-12',
    front: 'What is microcurrent?',
    back: 'A type of galvanic treatment using very low-level electrical current. Best known for toning skin and producing a lifting effect on aging skin lacking elasticity.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 73,
    is_active: true,
  },
  {
    id: 'fc-ch12-074',
    chapter_id: 'ch-12',
    front: 'What is microdermabrasion?',
    back: 'A form of mechanical exfoliation that sprays aluminum oxide or other microcrystals across the skin to exfoliate dead cells, which are then vacuumed off.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 74,
    is_active: true,
  },
  {
    id: 'fc-ch12-075',
    chapter_id: 'ch-12',
    front: 'What is light therapy?',
    back: 'Using light exposure to treat skin and scalp conditions. Includes ultraviolet rays, infrared rays, and LEDs.',
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 75,
    is_active: true,
  },
  {
    id: 'fc-ch12-076',
    chapter_id: 'ch-12',
    front: 'What are the three types of ultraviolet rays and their effects?',
    back: 'UVA = tonic rays, UVB = therapeutic rays, UVC = germicidal rays.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 76,
    is_active: true,
  },
  {
    id: 'fc-ch12-077',
    chapter_id: 'ch-12',
    front: 'What distance should ultraviolet and infrared lamps be positioned from the skin?',
    back: 'Ultraviolet: 30 to 36 inches. Infrared: 30 inches.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 77,
    is_active: true,
  },
  {
    id: 'fc-ch12-078',
    chapter_id: 'ch-12',
    front: 'What is the maximum exposure time for infrared rays?',
    back: 'Total exposure should not exceed 5 minutes. Move your hand back and forth to break constant exposure.',
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 78,
    is_active: true,
  },
  {
    id: 'fc-ch12-079',
    chapter_id: 'ch-12',
    front: 'What are the general contraindications for electrotherapy?',
    back: 'Seizures/epilepsy, heart conditions, nerve disorders, fever or infection, asthma, pregnancy, high blood pressure, open or broken skin, sinus blockages, pacemakers, and metal implants.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 79,
    is_active: true,
  },

  // === SAFETY PRECAUTIONS ===
  {
    id: 'fc-ch12-080',
    chapter_id: 'ch-12',
    front: 'What are key safety precautions when using electrical equipment in the barbershop?',
    back: 'Disconnect when not in use, study instructions first, keep wires/plugs safe, inspect frequently, avoid wet cords, clean/disinfect electrodes, protect the client, avoid touching metal during treatments, do not leave the room when client is attached to a device.',
    category: 'Safety',
    difficulty: 'medium',
    order_index: 80,
    is_active: true,
  },
  {
    id: 'fc-ch12-081',
    chapter_id: 'ch-12',
    front: 'Why should you not use alcohol-based lotion before high-frequency treatment?',
    back: 'Alcohol can cause adverse reactions with the electrical current.',
    category: 'Safety',
    difficulty: 'medium',
    order_index: 81,
    is_active: true,
  },

  // === SKIN TYPES ===
  {
    id: 'fc-ch12-082',
    chapter_id: 'ch-12',
    front: 'What are the four basic skin types?',
    back: 'Dry (alipidic), normal, combination, and oily.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 82,
    is_active: true,
  },
  {
    id: 'fc-ch12-083',
    chapter_id: 'ch-12',
    front: 'What characterizes dry (alipidic) skin?',
    back: 'Does not produce enough sebum, leaving skin dehydrated. May appear flaky with small fine lines and wrinkles. Goal is to stimulate oil production.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 83,
    is_active: true,
  },
  {
    id: 'fc-ch12-084',
    chapter_id: 'ch-12',
    front: 'What characterizes normal skin?',
    back: 'Good water-oil balance, normal pore size, free of blemishes. Needs maintenance and preservative care.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 84,
    is_active: true,
  },
  {
    id: 'fc-ch12-085',
    chapter_id: 'ch-12',
    front: 'What characterizes oily skin?',
    back: 'Excess sebum production, shiny or greasy appearance, larger follicles with more oil. Requires more cleansing and exfoliation.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 85,
    is_active: true,
  },
  {
    id: 'fc-ch12-086',
    chapter_id: 'ch-12',
    front: 'What characterizes combination skin?',
    back: 'Both oily and dry in different areas. The T-zone (forehead, nose, chin) tends to be oily; cheeks and outer areas tend to be dry.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 86,
    is_active: true,
  },
  {
    id: 'fc-ch12-087',
    chapter_id: 'ch-12',
    front: 'What is the T-zone?',
    back: 'The section of the face incorporating the forehead, nose, and chin area. These areas tend to have more sebaceous glands and larger pores.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 87,
    is_active: true,
  },
  {
    id: 'fc-ch12-088',
    chapter_id: 'ch-12',
    front: 'What causes wrinkles?',
    back: 'Repetitious muscle action moving in the same direction, loosening of elastic fibers, shrinking skin tissue from aging, excessive dryness, and improper facial care.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 88,
    is_active: true,
  },

  // === SKIN ANALYSIS ===
  {
    id: 'fc-ch12-089',
    chapter_id: 'ch-12',
    front: 'What tool is preferable for analyzing skin?',
    back: 'A magnifying lamp or light. If unavailable, a close inspection will suffice.',
    category: 'Skin Analysis',
    difficulty: 'easy',
    order_index: 89,
    is_active: true,
  },
  {
    id: 'fc-ch12-090',
    chapter_id: 'ch-12',
    front: 'What are the five steps for performing a skin analysis and client consultation?',
    back: '1. Observe skin type, condition, and appearance; feel texture. 2. Ask about appearance and home care. 3. Discuss procedure, products, and why. 4. Encourage questions and determine action together. 5. Record information for next visit.',
    category: 'Skin Analysis',
    difficulty: 'medium',
    order_index: 90,
    is_active: true,
  },

  // === SKIN CARE PRODUCTS ===
  {
    id: 'fc-ch12-091',
    chapter_id: 'ch-12',
    front: 'What are the five categories of skin care products?',
    back: 'Cleansers, exfoliants, skin tonics, masks, and moisturizers.',
    category: 'Products',
    difficulty: 'easy',
    order_index: 91,
    is_active: true,
  },
  {
    id: 'fc-ch12-092',
    chapter_id: 'ch-12',
    front: 'What is the difference between face washes, cleansing lotions, and cleansing creams?',
    back: 'Face washes are water-based with neutral/slightly acidic pH for oily/combination skin. Cleansing lotions are water-based emulsions with emollients for normal/combination skin. Cleansing creams are heavier oil-based emulsions for dissolving dirt and makeup.',
    category: 'Products',
    difficulty: 'medium',
    order_index: 92,
    is_active: true,
  },
  {
    id: 'fc-ch12-093',
    chapter_id: 'ch-12',
    front: 'What are the three types of skin tonics and their alcohol content?',
    back: 'Fresheners (0-4% alcohol, for dry/mature/sensitive skin), toners (4-15% alcohol, for normal/combination skin), and astringents (up to 35% alcohol, for oily/acne-prone skin).',
    category: 'Products',
    difficulty: 'medium',
    order_index: 93,
    is_active: true,
  },
  {
    id: 'fc-ch12-094',
    chapter_id: 'ch-12',
    front: 'What is witch hazel used for in facial treatments?',
    back: 'Works as an astringent and can be used as a toning tonic in facial treatments and shave services.',
    category: 'Products',
    difficulty: 'easy',
    order_index: 94,
    is_active: true,
  },
  {
    id: 'fc-ch12-095',
    chapter_id: 'ch-12',
    front: 'What do moisturizers contain?',
    back: 'Moisture-attracting humectants and emollients that prevent moisture from evaporating from the skin.',
    category: 'Products',
    difficulty: 'easy',
    order_index: 95,
    is_active: true,
  },
  {
    id: 'fc-ch12-096',
    chapter_id: 'ch-12',
    front: 'What is rolling cream?',
    back: 'A thick, smooth, nongranular exfoliating cream, usually pink. Applied in a thin layer and rolled off with firm stroking motions to lift dead cells and impurities.',
    category: 'Products',
    difficulty: 'medium',
    order_index: 96,
    is_active: true,
  },
  {
    id: 'fc-ch12-097',
    chapter_id: 'ch-12',
    front: 'On which skin types should rolling cream NOT be used?',
    back: 'Not recommended on dry, acne-prone, sensitive, or thin-textured skin. Only for normal, oily, or thick skin.',
    category: 'Products',
    difficulty: 'medium',
    order_index: 97,
    is_active: true,
  },
  {
    id: 'fc-ch12-098',
    chapter_id: 'ch-12',
    front: 'What are chemical exfoliants?',
    back: 'Products such as alpha hydroxy acids or enzyme peels that loosen or dissolve dead-cell buildup. Require advanced training and sometimes certification.',
    category: 'Products',
    difficulty: 'medium',
    order_index: 98,
    is_active: true,
  },
  {
    id: 'fc-ch12-099',
    chapter_id: 'ch-12',
    front: 'What are the four types of masks?',
    back: 'Clay masks (oily/combination, absorb sebum), cream masks (dry skin, moisturizing), gel masks (sensitive/dehydrated), and paraffin wax masks (pack method).',
    category: 'Products',
    difficulty: 'medium',
    order_index: 99,
    is_active: true,
  },
  {
    id: 'fc-ch12-100',
    chapter_id: 'ch-12',
    front: 'What is the general order of product application during a basic facial?',
    back: '1. Cleansing cream/lotion, 2. Exfoliant, 3. Massage cream, 4. Cleansing cream/lotion, 5. Freshener, 6. Mask/pack, 7. Toner/astringent, 8. Moisturizer.',
    category: 'Products',
    difficulty: 'medium',
    order_index: 100,
    is_active: true,
  },

  // === FACIAL TREATMENTS ===
  {
    id: 'fc-ch12-101',
    chapter_id: 'ch-12',
    front: 'What is the difference between preservative and corrective facial treatments?',
    back: 'Preservative treatments maintain skin health through cleansing, toning, and massage. Corrective treatments correct conditions such as dryness, oiliness, blackheads, aging lines, and minor acne.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 101,
    is_active: true,
  },
  {
    id: 'fc-ch12-102',
    chapter_id: 'ch-12',
    front: 'What is a basic facial (scientific rest facial)?',
    back: 'The foundation for all facial treatments. Includes cleansing, exfoliating, massage manipulations, toning, a mask or pack, and moisturizing.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 102,
    is_active: true,
  },
  {
    id: 'fc-ch12-103',
    chapter_id: 'ch-12',
    front: 'What is a vibratory facial?',
    back: 'Performed using a combination of hand massage and an electric massager. Uses direct application (massager on skin) or indirect application (massager on barber\'s hand over client\'s skin).',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 103,
    is_active: true,
  },
  {
    id: 'fc-ch12-104',
    chapter_id: 'ch-12',
    front: 'What is the difference between direct and indirect vibratory application?',
    back: 'Direct: massager attached to dominant hand, vibrations travel through fingertips/palms to skin (for jaw, forehead). Indirect: nondominant hand on skin, massager on top of that hand (for delicate areas like nose and upper cheek).',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 104,
    is_active: true,
  },
  {
    id: 'fc-ch12-105',
    chapter_id: 'ch-12',
    front: 'What is the objective of a facial for dry skin?',
    back: 'To help moisturize it. Can be supplemented with infrared rays, galvanic current, or high-frequency current to stimulate sebum production.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 105,
    is_active: true,
  },
  {
    id: 'fc-ch12-106',
    chapter_id: 'ch-12',
    front: 'What causes blackheads (comedones)?',
    back: 'Hardened masses of sebum formed inside a follicle. The sebaceous material darkens when exposed to oxygen.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 106,
    is_active: true,
  },
  {
    id: 'fc-ch12-107',
    chapter_id: 'ch-12',
    front: 'What massage movement should be used on acne-prone skin?',
    back: 'Only effleurage movements to apply gentle massage or products, to avoid spreading infectious matter.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 107,
    is_active: true,
  },
  {
    id: 'fc-ch12-108',
    chapter_id: 'ch-12',
    front: 'What are three guidelines for successful facial treatments?',
    back: 'Help the client relax, explain benefits during consultation, provide a quiet atmosphere, work efficiently, maintain clean conditions, analyze skin systematically, protect eyes, keep nails smooth and short, warm cold hands, test hot towels, avoid rough massage, avoid excess product, avoid excessive conversation.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 108,
    is_active: true,
  },

  // === MODALITIES ===
  {
    id: 'fc-ch12-109',
    chapter_id: 'ch-12',
    front: 'What modalities can affect muscle action during facial treatments?',
    back: 'Massage (hand and electric), electric currents (high frequency, galvanic, microcurrent), light rays (infrared, ultraviolet, LLLT, LED), heat, moist heat, nerve impulses, and chemicals.',
    category: 'Modalities',
    difficulty: 'medium',
    order_index: 109,
    is_active: true,
  },
  {
    id: 'fc-ch12-110',
    chapter_id: 'ch-12',
    front: 'What effect does heat have on nerves?',
    back: 'Heat and moist heat cause relaxation; cold causes contraction.',
    category: 'Modalities',
    difficulty: 'easy',
    order_index: 110,
    is_active: true,
  },

  // === MEN\'S PRODUCT PREFERENCES ===
  {
    id: 'fc-ch12-111',
    chapter_id: 'ch-12',
    front: 'What product characteristics appeal to male clients?',
    back: 'Simple, non-fragranced, absorbent creams with a matte finish. Men prefer simpler routines and multipurpose products (e.g., a skin tonic that also serves as aftershave).',
    category: 'Men\'s Products',
    difficulty: 'easy',
    order_index: 111,
    is_active: true,
  },
  {
    id: 'fc-ch12-112',
    chapter_id: 'ch-12',
    front: 'What packaging do men typically prefer for skin care products?',
    back: 'Tube packaging over jars. Smaller sizes for travel, larger for home use.',
    category: 'Men\'s Products',
    difficulty: 'easy',
    order_index: 112,
    is_active: true,
  },

  // === ADDITIONAL SAFETY ===
  {
    id: 'fc-ch12-113',
    chapter_id: 'ch-12',
    front: 'Why should products be removed from containers with a spatula?',
    back: 'To prevent contamination. Do not dip fingers into containers.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 113,
    is_active: true,
  },
  {
    id: 'fc-ch12-114',
    chapter_id: 'ch-12',
    front: 'Why should latex-free gloves and supplies be available?',
    back: 'Some clients are sensitive to latex and may have a negative reaction.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 114,
    is_active: true,
  },

  // === HISTORICAL CONTEXT ===
  {
    id: 'fc-ch12-115',
    chapter_id: 'ch-12',
    front: 'What were standard facial services historically performed by barbers?',
    back: 'Hot towels and rolling cream facials were standard customer services.',
    category: 'History',
    difficulty: 'easy',
    order_index: 115,
    is_active: true,
  },
]

export default chapter12PremiumFlashcards
