import { QuizQuestion } from '@/types'

// Chapter 17: Chemical Texture Services — PREMIUM MCQ QUIZ
// 30 board-style questions + 16 learning questions
// Original content; no textbook or exam questions copied.

// ═══════════════════════════════════════════════════════════════════════════════
// BOARD-STYLE QUESTION BANK (30 questions)
// Cognitive distribution: 14 Recall / 11 Application / 5 Analysis
// ═══════════════════════════════════════════════════════════════════════════════
export const chapter17PremiumQuizQuestions: QuizQuestion[] = [
  // === CONSULTATION & ANALYSIS (5 questions) ===
  {
    id: 'qq-17-001',
    standardId: 'CH17-Q001',
    quiz_id: 'quiz-17',
    question: 'Which hair characteristic is the most important factor when determining processing time for a chemical texture service?',
    answer_a: 'Density',
    answer_b: 'Porosity',
    answer_c: 'Texture',
    answer_d: 'Elasticity',
    correct_answer: 'b',
    explanation: 'Porosity determines how quickly the chemical solution penetrates the cuticle. Resistant hair processes slowly; porous hair processes quickly and can overprocess.',
    difficulty: 'easy',
    competency_id: 'CH17-C01',
    order_index: 1,
  },
  {
    id: 'qq-17-002',
    standardId: 'CH17-Q002',
    quiz_id: 'quiz-17',
    question: 'A client has fine, highlighted hair and requests a permanent wave. What is the most appropriate first action?',
    answer_a: 'Use a standard alkaline perm for faster results',
    answer_b: 'Perform strand tests and choose a milder acid formula',
    answer_c: 'Refuse the service because perms are unsafe on highlighted hair',
    answer_d: 'Double the processing time to ensure the wave takes hold',
    correct_answer: 'b',
    explanation: 'Highlighted hair is often porous and fragile. Strand testing and a milder acid formula reduce the risk of overprocessing while still creating a wave.',
    difficulty: 'medium',
    competency_id: 'CH17-C01',
    order_index: 2,
  },
  {
    id: 'qq-17-003',
    standardId: 'CH17-Q003',
    quiz_id: 'quiz-17',
    question: 'Which of the following is a contraindication for a chemical texture service?',
    answer_a: 'Normal elasticity and medium porosity',
    answer_b: 'Healthy scalp with no abrasions',
    answer_c: 'Open cuts or infection on the scalp',
    answer_d: 'Hair that has not been chemically treated in over a year',
    correct_answer: 'c',
    explanation: 'Open cuts, infections, or scalp disease can allow chemicals to enter tissue and cause burns or further injury. The service must be postponed.',
    difficulty: 'easy',
    competency_id: 'CH17-C06',
    order_index: 3,
  },
  {
    id: 'qq-17-004',
    standardId: 'CH17-Q004',
    quiz_id: 'quiz-17',
    question: 'How many characteristics of the hair and scalp are typically analyzed before a chemical texture service?',
    answer_a: 'Three',
    answer_b: 'Four',
    answer_c: 'Six',
    answer_d: 'Eight',
    correct_answer: 'c',
    explanation: 'The standard analysis covers texture, porosity, elasticity, density, scalp condition, and service history.',
    difficulty: 'easy',
    competency_id: 'CH17-C01',
    order_index: 4,
  },
  {
    id: 'qq-17-005',
    standardId: 'CH17-Q005',
    quiz_id: 'quiz-17',
    question: 'During the consultation, a client reveals they had a hydroxide relaxer six months ago. Why does this matter for future texture services?',
    answer_a: 'Hydroxide only affects the cuticle and does not influence other services',
    answer_b: 'Hydroxide-treated hair may be incompatible with thio-based perms or relaxers',
    answer_c: 'Any new chemical service is automatically safe after six months',
    answer_d: 'Hydroxide improves curl retention so perms process faster',
    correct_answer: 'b',
    explanation: 'Hydroxide relaxers restructure hair with a different chemistry than thio products. Combining them can cause severe damage; a compatibility test is needed.',
    difficulty: 'medium',
    competency_id: 'CH17-C01',
    order_index: 5,
  },

  // === CHEMISTRY (5 questions) ===
  {
    id: 'qq-17-006',
    standardId: 'CH17-Q006',
    quiz_id: 'quiz-17',
    question: 'What type of bond is permanently altered by all chemical texture services?',
    answer_a: 'Hydrogen bond',
    answer_b: 'Salt bond',
    answer_c: 'Disulfide bond',
    answer_d: 'Peptide bond',
    correct_answer: 'c',
    explanation: 'Disulfide bonds are the strong side bonds in the cortex that determine hair shape. Chemical texture services break and rebuild them.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 6,
  },
  {
    id: 'qq-17-007',
    standardId: 'CH17-Q007',
    quiz_id: 'quiz-17',
    question: 'What happens during the reduction phase of a permanent wave?',
    answer_a: 'Disulfide bonds are rebuilt into their new shape',
    answer_b: 'Disulfide bonds are broken so hair can be reshaped',
    answer_c: 'The cuticle is sealed to lock in moisture',
    answer_d: 'Hair color molecules are oxidized',
    correct_answer: 'b',
    explanation: 'Reduction breaks disulfide bonds (cystine to cysteine), allowing the hair to be wrapped into a new curl pattern.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 7,
  },
  {
    id: 'qq-17-008',
    standardId: 'CH17-Q008',
    quiz_id: 'quiz-17',
    question: 'What is the purpose of neutralization in a permanent wave?',
    answer_a: 'To remove product from the hair',
    answer_b: 'To rebuild disulfide bonds in the new shape',
    answer_c: 'To soften the cuticle before wrapping',
    answer_d: 'To increase the pH of the hair',
    correct_answer: 'b',
    explanation: 'Neutralizer oxidizes cysteine back to cystine, rebuilding disulfide bonds and locking the hair into its new shape.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 8,
  },
  {
    id: 'qq-17-009',
    standardId: 'CH17-Q009',
    quiz_id: 'quiz-17',
    question: 'Which statement best describes the difference between alkaline and true acid perms?',
    answer_a: 'Alkaline perms are gentler and require heat; acid perms are stronger and process at room temperature',
    answer_b: 'Alkaline perms have a higher pH and process faster at room temperature; acid perms are gentler and usually require heat',
    answer_c: 'Alkaline perms rebuild bonds; acid perms only break bonds',
    answer_d: 'Alkaline perms are always used on damaged hair; acid perms are only for healthy hair',
    correct_answer: 'b',
    explanation: 'Alkaline perms have a pH around 9.0–9.6 and process quickly without heat. True acid perms have a lower pH and use heat for gentler processing.',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 9,
  },
  {
    id: 'qq-17-010',
    standardId: 'CH17-Q010',
    quiz_id: 'quiz-17',
    question: 'An exothermic perm solution works by:',
    answer_a: 'Lowering the pH of the hair',
    answer_b: 'Generating its own heat when mixed',
    answer_c: 'Removing oil from the scalp',
    answer_d: 'Sealing the cuticle before processing',
    correct_answer: 'b',
    explanation: 'Exothermic perm solutions create heat through a chemical reaction when mixed, which increases processing activity.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 10,
  },

  // === PERMANENT WAVES (7 questions) ===
  {
    id: 'qq-17-011',
    standardId: 'CH17-Q011',
    quiz_id: 'quiz-17',
    question: 'Which rod placement creates the tightest curl and fullest volume at the base?',
    answer_a: 'Off-base',
    answer_b: 'Half off-base',
    answer_c: 'On-base',
    answer_d: 'Spiral',
    correct_answer: 'c',
    explanation: 'On-base placement stretches hair 135° from the scalp, producing maximum tension, a tight curl, and strong fullness.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 11,
  },
  {
    id: 'qq-17-012',
    standardId: 'CH17-Q012',
    quiz_id: 'quiz-17',
    question: 'Which wrapping technique is best for creating a corkscrew curl pattern?',
    answer_a: 'Croquignole',
    answer_b: 'Piggyback',
    answer_c: 'Spiral',
    answer_d: 'On-base',
    correct_answer: 'c',
    explanation: 'Spiral wrapping winds hair vertically down the rod, producing a long, corkscrew-shaped curl.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 12,
  },
  {
    id: 'qq-17-013',
    standardId: 'CH17-Q013',
    quiz_id: 'quiz-17',
    question: 'What effect does using a smaller-diameter perm rod have?',
    answer_a: 'Looser wave pattern',
    answer_b: 'Tighter curl pattern',
    answer_c: 'Straighter result',
    answer_d: 'No effect on curl size',
    correct_answer: 'b',
    explanation: 'Rod diameter controls curl size. Smaller rods produce tighter curls; larger rods produce looser waves.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 13,
  },
  {
    id: 'qq-17-014',
    standardId: 'CH17-Q014',
    quiz_id: 'quiz-17',
    question: 'A client wants a perm but has very long, dense hair. Which wrap would you most likely use?',
    answer_a: 'Croquignole',
    answer_b: 'Spiral',
    answer_c: 'Piggyback',
    answer_d: 'On-base only',
    correct_answer: 'c',
    explanation: 'Piggyback wrapping uses two rods per section to manage long or dense hair and produce an even curl from scalp to ends.',
    difficulty: 'medium',
    competency_id: 'CH17-C03',
    order_index: 14,
  },
  {
    id: 'qq-17-015',
    standardId: 'CH17-Q015',
    quiz_id: 'quiz-17',
    question: 'What is the most likely result of underprocessing a permanent wave?',
    answer_a: 'Frizzy, damaged hair',
    answer_b: 'A weak or limp wave that does not hold',
    answer_c: 'Overly tight curls',
    answer_d: 'Scalp burns',
    correct_answer: 'b',
    explanation: 'Underprocessing means the disulfide bonds were not broken and rebuilt enough to create a firm curl, leaving the wave weak.',
    difficulty: 'medium',
    competency_id: 'CH17-C03',
    order_index: 15,
  },
  {
    id: 'qq-17-016',
    standardId: 'CH17-Q016',
    quiz_id: 'quiz-17',
    question: 'What is the most likely result of overprocessing a permanent wave?',
    answer_a: 'A firm, well-defined curl',
    answer_b: 'Hair that is frizzy, weak, or damaged',
    answer_c: 'Hair that remains completely straight',
    answer_d: 'A darker hair color',
    correct_answer: 'b',
    explanation: 'Overprocessing breaks too many bonds for too long, leaving the cortex fragile and the cuticle lifted, which causes frizz and breakage.',
    difficulty: 'medium',
    competency_id: 'CH17-C03',
    order_index: 16,
  },
  {
    id: 'qq-17-017',
    standardId: 'CH17-Q017',
    quiz_id: 'quiz-17',
    question: 'Before rinsing a perm, how many test curls should be checked?',
    answer_a: 'One, at the crown',
    answer_b: 'Two, on opposite sides',
    answer_c: 'Three, in different areas',
    answer_d: 'None, as long as the timer is followed',
    correct_answer: 'c',
    explanation: 'Checking test curls in at least three areas ensures the wave has developed evenly across the entire head before neutralizing.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 17,
  },

  // === CHEMICAL RELAXERS (7 questions) ===
  {
    id: 'qq-17-018',
    standardId: 'CH17-Q018',
    quiz_id: 'quiz-17',
    question: 'Which type of relaxer contains a high pH and is very effective at straightening?',
    answer_a: 'Thio relaxer',
    answer_b: 'Hydroxide relaxer',
    answer_c: 'Acid perm',
    answer_d: 'Exothermic perm',
    correct_answer: 'b',
    explanation: 'Hydroxide relaxers, including lye and no-lye formulas, have a high pH and straighten hair by breaking disulfide bonds.',
    difficulty: 'easy',
    competency_id: 'CH17-C04',
    order_index: 18,
  },
  {
    id: 'qq-17-019',
    standardId: 'CH17-Q019',
    quiz_id: 'quiz-17',
    question: 'What is the main difference between a base relaxer and a no-base relaxer?',
    answer_a: 'Base relaxers are always lye; no-base relaxers are always no-lye',
    answer_b: 'Base relaxers require a protective scalp cream; no-base relaxers do not',
    answer_c: 'No-base relaxers are always stronger than base relaxers',
    answer_d: 'Base relaxers are used only for men; no-base relaxers are used only for women',
    correct_answer: 'b',
    explanation: 'Base relaxers need a separate protective base cream applied to the scalp before the relaxer. No-base formulas contain protective ingredients.',
    difficulty: 'medium',
    competency_id: 'CH17-C04',
    order_index: 19,
  },
  {
    id: 'qq-17-020',
    standardId: 'CH17-Q020',
    quiz_id: 'quiz-17',
    question: 'Which strand test determines how quickly hair will absorb a relaxer?',
    answer_a: 'Elasticity test',
    answer_b: 'Texture test',
    answer_c: 'Porosity test',
    answer_d: 'pH test',
    correct_answer: 'c',
    explanation: 'The porosity test shows how readily the hair absorbs product, which helps predict processing time and possible overprocessing.',
    difficulty: 'easy',
    competency_id: 'CH17-C04',
    order_index: 20,
  },
  {
    id: 'qq-17-021',
    standardId: 'CH17-Q021',
    quiz_id: 'quiz-17',
    question: 'Which strand test checks whether hair can withstand chemical processing?',
    answer_a: 'Porosity test',
    answer_b: 'Elasticity test',
    answer_c: 'Texture test',
    answer_d: 'Density test',
    correct_answer: 'b',
    explanation: 'The elasticity test measures whether hair stretches and returns to its length. Poor elasticity means the hair may be too weak to process.',
    difficulty: 'easy',
    competency_id: 'CH17-C04',
    order_index: 21,
  },
  {
    id: 'qq-17-022',
    standardId: 'CH17-Q022',
    quiz_id: 'quiz-17',
    question: 'Why is it unsafe to apply a thio perm over hair that was relaxed with hydroxide?',
    answer_a: 'The hair will process too slowly',
    answer_b: 'The two chemistries are incompatible and can cause severe damage',
    answer_c: 'The hydroxide will make the hair too curly',
    answer_d: 'Thio perms only work on natural gray hair',
    correct_answer: 'b',
    explanation: 'Hydroxide relaxers leave hair in a chemically different state than thio products. Combining them can cause breakage, melting, or severe damage.',
    difficulty: 'medium',
    competency_id: 'CH17-C04',
    order_index: 22,
  },
  {
    id: 'qq-17-023',
    standardId: 'CH17-Q023',
    quiz_id: 'quiz-17',
    question: 'A relaxer is applied and the client complains of burning. What is the best immediate action?',
    answer_a: 'Continue processing to finish the straightening',
    answer_b: 'Rinse the product off immediately and assess the scalp',
    answer_c: 'Add more base cream and continue',
    answer_d: 'Switch to a different relaxer brand mid-service',
    correct_answer: 'b',
    explanation: 'Burning is a sign of irritation or chemical injury. The product must be removed immediately to prevent further damage.',
    difficulty: 'easy',
    competency_id: 'CH17-C06',
    order_index: 23,
  },
  {
    id: 'qq-17-024',
    standardId: 'CH17-Q024',
    quiz_id: 'quiz-17',
    question: 'Which relaxer type is generally compatible with a follow-up thio perm?',
    answer_a: 'Lye hydroxide relaxer',
    answer_b: 'No-lye hydroxide relaxer',
    answer_c: 'Thio relaxer',
    answer_d: 'Exothermic perm',
    correct_answer: 'c',
    explanation: 'Thio relaxers use ammonium thioglycolate, the same chemistry as thio perms, making them compatible when hair is healthy.',
    difficulty: 'medium',
    competency_id: 'CH17-C04',
    order_index: 24,
  },

  // === CURL REFORMATION, TEXTURIZERS, BLOWOUTS (3 questions) ===
  {
    id: 'qq-17-025',
    standardId: 'CH17-Q025',
    quiz_id: 'quiz-17',
    question: 'What is the first step of a curl reformation service?',
    answer_a: 'Wrap the hair on rods',
    answer_b: 'Straighten the hair with a thio-based relaxer',
    answer_c: 'Apply neutralizer',
    answer_d: 'Perform a final rinse',
    correct_answer: 'b',
    explanation: 'Curl reformation begins by straightening the existing curl pattern with a thio-based relaxer before wrapping and neutralizing.',
    difficulty: 'medium',
    competency_id: 'CH17-C05',
    order_index: 25,
  },
  {
    id: 'qq-17-026',
    standardId: 'CH17-Q026',
    quiz_id: 'quiz-17',
    question: 'Why is curl reformation considered a higher-risk service?',
    answer_a: 'It uses only one chemical process',
    answer_b: 'It requires two chemical processes on the same hair',
    answer_c: 'It never needs strand testing',
    answer_d: 'It only works on very short hair',
    correct_answer: 'b',
    explanation: 'Curl reformation relaxes the hair and then reforms it, applying two chemical services. The hair must be healthy enough to withstand both.',
    difficulty: 'medium',
    competency_id: 'CH17-C05',
    order_index: 26,
  },
  {
    id: 'qq-17-027',
    standardId: 'CH17-Q027',
    quiz_id: 'quiz-17',
    question: 'What is the main difference between a texturizer and a full relaxer?',
    answer_a: 'Texturizers are always hydroxide; relaxers are always thio',
    answer_b: 'Texturizers loosen curl; relaxers fully straighten',
    answer_c: 'Texturizers require heat; relaxers do not',
    answer_d: 'Texturizers only work on fine hair',
    correct_answer: 'b',
    explanation: 'A texturizer uses a mild relaxer formula and shorter processing to loosen curl pattern. A relaxer is designed to fully straighten.',
    difficulty: 'easy',
    competency_id: 'CH17-C07',
    order_index: 27,
  },

  // === SAFETY & NEUTRALIZATION (3 questions) ===
  {
    id: 'qq-17-028',
    standardId: 'CH17-Q028',
    quiz_id: 'quiz-17',
    question: 'Why is thorough rinsing important before applying neutralizer?',
    answer_a: 'It lightens the hair color',
    answer_b: 'It stops the action of the waving or relaxing solution',
    answer_c: 'It opens the cuticle for better neutralizer absorption',
    answer_d: 'It removes the client\'s natural oils',
    correct_answer: 'b',
    explanation: 'Rinsing removes the alkaline or reducing solution so it stops processing before the neutralizer rebuilds bonds.',
    difficulty: 'easy',
    competency_id: 'CH17-C06',
    order_index: 28,
  },
  {
    id: 'qq-17-029',
    standardId: 'CH17-Q029',
    quiz_id: 'quiz-17',
    question: 'What can happen if neutralization is incomplete?',
    answer_a: 'The curl will be too tight',
    answer_b: 'The new shape may not hold and the hair can be left weakened',
    answer_c: 'The hair will darken permanently',
    answer_d: 'The scalp will become oily',
    correct_answer: 'b',
    explanation: 'Incomplete neutralization leaves disulfide bonds unstable, which can cause the curl to relax and the hair to remain fragile.',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 29,
  },
  {
    id: 'qq-17-030',
    standardId: 'CH17-Q030',
    quiz_id: 'quiz-17',
    question: 'Which safety practice protects the stylist during chemical texture services?',
    answer_a: 'Wearing gloves',
    answer_b: 'Using bare hands to feel product saturation',
    answer_c: 'Skipping the strand test on regular clients',
    answer_d: 'Applying relaxer directly to the scalp without base',
    correct_answer: 'a',
    explanation: 'Gloves protect the stylist\'s skin from alkaline, acidic, or reducing solutions that can cause irritation or burns.',
    difficulty: 'easy',
    competency_id: 'CH17-C06',
    order_index: 30,
  },
]

// ═══════════════════════════════════════════════════════════════════════════════
// LEARNING QUESTION BANK (15 questions)
// Focus: concept mastery and practical understanding
// ═══════════════════════════════════════════════════════════════════════════════
export const chapter17LearningQuestions: QuizQuestion[] = [
  {
    id: 'lq-17-001',
    standardId: 'CH17-Q031',
    quiz_id: 'quiz-17-learning',
    question: 'In your own words, why does porosity matter more than texture for processing time?',
    answer_a: 'Texture determines curl size; porosity determines how fast the product works',
    answer_b: 'Porosity controls how quickly solution enters the hair; texture only affects strand thickness',
    answer_c: 'Texture and porosity are the same thing',
    answer_d: 'Porosity only matters for color services',
    correct_answer: 'b',
    explanation: 'Porosity controls absorption speed, which directly affects timing and risk of overprocessing. Texture affects strength and resistance but not absorption rate.',
    difficulty: 'medium',
    competency_id: 'CH17-C01',
    order_index: 1,
  },
  {
    id: 'lq-17-002',
    standardId: 'CH17-Q032',
    quiz_id: 'quiz-17-learning',
    question: 'How does the reduction → reshape → oxidation cycle explain why a perm is permanent?',
    answer_a: 'It coats the outside of the hair with a protective layer',
    answer_b: 'It physically bends the hair without chemistry',
    answer_c: 'It breaks internal bonds, shapes the hair, then rebuilds bonds in the new shape',
    answer_d: 'It only changes the cuticle layer',
    correct_answer: 'c',
    explanation: 'The internal structure of the hair is permanently changed when disulfide bonds are broken, reshaped, and rebuilt.',
    difficulty: 'easy',
    competency_id: 'CH17-C02',
    order_index: 2,
  },
  {
    id: 'lq-17-003',
    standardId: 'CH17-Q033',
    quiz_id: 'quiz-17-learning',
    question: 'When would you choose on-base placement instead of off-base placement?',
    answer_a: 'When the client wants maximum volume and tight curl',
    answer_b: 'When the client wants a natural, low-volume result',
    answer_c: 'When the hair is too damaged to hold tension',
    answer_d: 'When using very large rods',
    correct_answer: 'a',
    explanation: 'On-base placement uses high tension to create fullness and tight curl at the scalp. Off-base creates a softer look.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 3,
  },
  {
    id: 'lq-17-004',
    standardId: 'CH17-Q034',
    quiz_id: 'quiz-17-learning',
    question: 'Why is a spiral wrap different from a croquignole wrap?',
    answer_a: 'Spiral wraps overlap hair from ends to scalp; croquignole wraps vertically',
    answer_b: 'Croquignole wraps overlap from ends to scalp; spiral wraps vertically down the rod',
    answer_c: 'They are the same technique with different names',
    answer_d: 'Spiral wraps are only used on short hair',
    correct_answer: 'b',
    explanation: 'Croquignole wraps overlap horizontally toward the scalp, while spiral wraps wind vertically down the rod for a corkscrew curl.',
    difficulty: 'medium',
    competency_id: 'CH17-C03',
    order_index: 4,
  },
  {
    id: 'lq-17-005',
    standardId: 'CH17-Q035',
    quiz_id: 'quiz-17-learning',
    question: 'What should you do if a strand test shows poor elasticity before a relaxer?',
    answer_a: 'Proceed with a stronger relaxer',
    answer_b: 'Postpone the service and recommend conditioning treatments',
    answer_c: 'Double the processing time',
    answer_d: 'Apply relaxer only to the ends',
    correct_answer: 'b',
    explanation: 'Poor elasticity means the hair is weak. Processing it can cause breakage; conditioning and postponement are the safest choices.',
    difficulty: 'medium',
    competency_id: 'CH17-C06',
    order_index: 5,
  },
  {
    id: 'lq-17-006',
    standardId: 'CH17-Q036',
    quiz_id: 'quiz-17-learning',
    question: 'Why is it important to record every chemical texture service in the client file?',
    answer_a: 'To track progress and protect both client and stylist if a future reaction occurs',
    answer_b: 'Because the law requires a written essay for each service',
    answer_c: 'To make the file heavier',
    answer_d: 'Only salon chains need records',
    correct_answer: 'a',
    explanation: 'Records document products, strengths, timing, and results, which helps plan future services and resolve concerns.',
    difficulty: 'easy',
    competency_id: 'CH17-C01',
    order_index: 6,
  },
  {
    id: 'lq-17-007',
    standardId: 'CH17-Q037',
    quiz_id: 'quiz-17-learning',
    question: 'How do you explain a strand test to a client in simple terms?',
    answer_a: 'It is a way to guess the final color',
    answer_b: 'It is a small test on a hidden section to see how the hair reacts before the full service',
    answer_c: 'It measures the exact length of the hair',
    answer_d: 'It is only needed for haircuts',
    correct_answer: 'b',
    explanation: 'A strand test lets you observe how a small amount of hair responds to the product, reducing risk for the whole head.',
    difficulty: 'easy',
    competency_id: 'CH17-C06',
    order_index: 7,
  },
  {
    id: 'lq-17-008',
    standardId: 'CH17-Q038',
    quiz_id: 'quiz-17-learning',
    question: 'What is the relationship between rod size and the final curl size?',
    answer_a: 'Larger rods make tighter curls',
    answer_b: 'Smaller rods make tighter curls',
    answer_c: 'Rod size does not affect curl size',
    answer_d: 'Rod size only affects processing time',
    correct_answer: 'b',
    explanation: 'The hair wraps more tightly around a smaller rod, producing a smaller, tighter curl. Larger rods produce looser waves.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 8,
  },
  {
    id: 'lq-17-009',
    standardId: 'CH17-Q039',
    quiz_id: 'quiz-17-learning',
    question: 'Why is a no-base relaxer called "no-base"?',
    answer_a: 'It is applied only to the ends of the hair',
    answer_b: 'It already contains protective ingredients so a separate scalp cream is not needed',
    answer_c: 'It does not touch the scalp at all',
    answer_d: 'It is always a thio relaxer',
    correct_answer: 'b',
    explanation: 'No-base relaxers include protective ingredients in the formula, eliminating the need for a separate base cream.',
    difficulty: 'easy',
    competency_id: 'CH17-C04',
    order_index: 9,
  },
  {
    id: 'lq-17-010',
    standardId: 'CH17-Q040',
    quiz_id: 'quiz-17-learning',
    question: 'What makes a chemical blowout different from a full relaxer?',
    answer_a: 'It permanently colors the hair',
    answer_b: 'It uses heat instead of chemicals',
    answer_c: 'It loosens curl enough to make blow-drying easier but does not fully straighten',
    answer_d: 'It only works on straight hair',
    correct_answer: 'c',
    explanation: 'A chemical blowout is a mild relaxing service that reduces curl for easier styling without complete straightening.',
    difficulty: 'easy',
    competency_id: 'CH17-C07',
    order_index: 10,
  },
  {
    id: 'lq-17-011',
    standardId: 'CH17-Q041',
    quiz_id: 'quiz-17-learning',
    question: 'Why should a client avoid shampooing for 48 hours after a perm?',
    answer_a: 'Shampoo will make the hair grow faster',
    answer_b: 'The bonds need time to fully stabilize after neutralization',
    answer_c: 'Shampoo removes the stylist\'s signature scent',
    answer_d: 'The hair is already clean enough',
    correct_answer: 'b',
    explanation: 'Waiting allows disulfide bonds to fully stabilize in their new shape, helping the curl last and resist relaxing.',
    difficulty: 'easy',
    competency_id: 'CH17-C03',
    order_index: 11,
  },
  {
    id: 'lq-17-012',
    standardId: 'CH17-Q042',
    quiz_id: 'quiz-17-learning',
    question: 'What does it mean if hair "does not take" a perm?',
    answer_a: 'The hair is too healthy',
    answer_b: 'The solution is too strong',
    answer_c: 'The disulfide bonds were not sufficiently broken and reshaped',
    answer_d: 'The rods were too small',
    correct_answer: 'c',
    explanation: 'When a perm does not take, the reduction or processing was insufficient to reshape and lock the bonds into curls.',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 12,
  },
  {
    id: 'lq-17-013',
    standardId: 'CH17-Q043',
    quiz_id: 'quiz-17-learning',
    question: 'How can you tell the difference between underprocessed and overprocessed permed hair?',
    answer_a: 'Underprocessed is limp; overprocessed is frizzy or damaged',
    answer_b: 'Underprocessed is frizzy; overprocessed is limp',
    answer_c: 'Both look exactly the same',
    answer_d: 'Underprocessed hair is darker',
    correct_answer: 'a',
    explanation: 'Underprocessing leaves a weak wave; overprocessing breaks too many bonds and causes frizz, weakness, and damage.',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 13,
  },
  {
    id: 'lq-17-014',
    standardId: 'CH17-Q044',
    quiz_id: 'quiz-17-learning',
    question: 'Why is density important when sectioning for a relaxer?',
    answer_a: 'Dense hair needs smaller sections for full saturation',
    answer_b: 'Thin hair needs smaller sections to look thicker',
    answer_c: 'Density does not affect sectioning',
    answer_d: 'Dense hair should never be relaxed',
    correct_answer: 'a',
    explanation: 'Thicker, denser hair requires smaller subsections so the relaxer reaches every strand evenly and avoids patchy results.',
    difficulty: 'easy',
    competency_id: 'CH17-C04',
    order_index: 14,
  },
  {
    id: 'lq-17-015',
    standardId: 'CH17-Q045',
    quiz_id: 'quiz-17-learning',
    question: 'What is the best way to protect a client\'s scalp during a base relaxer service?',
    answer_a: 'Apply a protective base cream to the scalp before the relaxer',
    answer_b: 'Rinse the scalp with hot water first',
    answer_c: 'Apply relaxer directly without protection',
    answer_d: 'Use a higher-pH relaxer',
    correct_answer: 'a',
    explanation: 'A base cream creates a barrier between the scalp and the high-pH relaxer, reducing irritation and burn risk.',
    difficulty: 'easy',
    competency_id: 'CH17-C06',
    order_index: 15,
  },
  {
    id: 'lq-17-016',
    standardId: 'CH17-Q046',
    quiz_id: 'quiz-17-learning',
    question: 'How are permanent waves, relaxers, and curl reformation chemically similar — and how do they differ?',
    answer_a: 'They all use hydroxide to break bonds; only the wrapping technique differs',
    answer_b: 'They all reduce, reshape, and oxidize disulfide bonds, but they use different products and tools to create different outcomes',
    answer_c: 'They only change the cuticle layer and do not affect disulfide bonds',
    answer_d: 'Perms add curl, relaxers remove curl, and reformation does nothing to bonds',
    correct_answer: 'b',
    explanation: 'All three services follow the same three-stage chemistry on disulfide bonds. The differences are the desired shape (curl, straight, or reset curl), the tools used (rods vs. comb vs. both), and the product families (alkaline/acid vs. hydroxide/thio).',
    difficulty: 'medium',
    competency_id: 'CH17-C02',
    order_index: 16,
  },
]
