// Chapter 1 Premium Quiz — Flashcard-Driven Multiple Choice System
// 30 questions generated from Chapter 1 flashcard curriculum
// Randomized order, randomized answers, board-exam style

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 1 QUIZ: History of Barbering (30 Questions)
// Difficulty mix: 10 easy, 10 medium, 10 hard
// Sources: Foundation, Visual ID, Board Exam, Scenarios, Memory, Deep History
// ───────────────────────────────────────────────

export const chapter1PremiumQuizQuestions: QuizQuestion[] = [
  // ═══════════════════════════════════════════════════════════
  // EASY QUESTIONS (10)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-1-001',
    quiz_id: 'quiz-1',
    question: 'The word "barber" originates from the Latin word "barba." What does "barba" mean?',
    answer_a: 'Beard',
    answer_b: 'Hair',
    answer_c: 'Blade',
    answer_d: 'Style',
    correct_answer: 'a',
    explanation: '"Barba" means BEARD. The profession is literally named after the facial hair it was originally trusted to maintain and style.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-1-002',
    quiz_id: 'quiz-1',
    question: 'Archaeological evidence supports barbering as one of the oldest professions. Which of the following is NOT mentioned as evidence?',
    answer_a: 'Painted pottery',
    answer_b: 'Burial mound artifacts',
    answer_c: 'Ancient coins',
    answer_d: 'Tomb excavations',
    correct_answer: 'c',
    explanation: 'Evidence includes painted pottery, early sculptures, burial mound artifacts, written records, and tomb excavations. Ancient coins are not mentioned as barbering evidence.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-1-003',
    quiz_id: 'quiz-1',
    question: 'What were the earliest known implements used for cutting and styling hair during the Glacial Age?',
    answer_a: 'Metal blades and bronze knives',
    answer_b: 'Glass shards and leather strips',
    answer_c: 'Sharpened flints, oyster shells, bone fragments, and animal sinew',
    answer_d: 'Wooden picks and stone hammers',
    correct_answer: 'c',
    explanation: 'Early humans fashioned rudimentary tools from sharpened flints, oyster shells, bone fragments, and animal sinew for cutting and styling hair.',
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-1-004',
    quiz_id: 'quiz-1',
    question: 'What do the three colors of the traditional barber pole represent?',
    answer_a: 'Red for fire, white for purity, blue for water',
    answer_b: 'Red for courage, white for peace, blue for loyalty',
    answer_c: 'Red for blood, white for bandages, blue for veins',
    answer_d: 'Red, white, and blue for the American flag',
    correct_answer: 'c',
    explanation: 'Red represents blood, white represents bandages, and blue represents veins — all originating from bloodletting practices.',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-1-005',
    quiz_id: 'quiz-1',
    question: 'Which state passed the FIRST barber licensing law, and in what year?',
    answer_a: 'New York, 1905',
    answer_b: 'California, 1910',
    answer_c: 'Minnesota, 1897',
    answer_d: 'Illinois, 1885',
    correct_answer: 'c',
    explanation: 'Minnesota passed the first barber-licensing law in 1897, establishing standards for sanitation, education, and disinfection.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-1-006',
    quiz_id: 'quiz-1',
    question: 'Who invented the first practical electric hair clippers, and in what year?',
    answer_a: 'Matthew Andis in 1921',
    answer_b: 'John Oster in 1928',
    answer_c: 'Thomas Edison in 1905',
    answer_d: 'Leo J. Wahl in 1919',
    correct_answer: 'd',
    explanation: 'Leo J. Wahl invented the first practical electric hair clippers in 1919, transforming the barbering industry.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-1-007',
    quiz_id: 'quiz-1',
    question: 'The Roman Catholic Church abolished the practice of tonsure in what year?',
    answer_a: '1450',
    answer_b: '1745',
    answer_c: '1897',
    answer_d: '1972',
    correct_answer: 'd',
    explanation: '1972. The circular tonsure of St. Peter — a slight fringe of hair around the head — was officially abolished, ending a tradition that had lasted over a thousand years.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-1-008',
    quiz_id: 'quiz-1',
    question: 'What does NABBA stand for?',
    answer_a: 'National Association of Barbers and Beauticians',
    answer_b: 'North American Barber Brotherhood Alliance',
    answer_c: 'National Academy of Barbering and Beauty Arts',
    answer_d: 'National Association of State Boards of Barber Examiners',
    correct_answer: 'd',
    explanation: 'National Association of State Boards of Barber Examiners (founded 1929). NABBA promotes information exchange, establishes licensing standards, sets curriculum requirements, supports continuing education, and protects consumers.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-1-009',
    quiz_id: 'quiz-1',
    question: 'When did surgeons officially separate from barbers, ending the barber-surgeon era?',
    answer_a: '1540',
    answer_b: '1605',
    answer_c: '1897',
    answer_d: '1745',
    correct_answer: 'd',
    explanation: 'The complete separation occurred in 1745, when surgeons formally split from barbers to establish independent medical practice.',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-1-010',
    quiz_id: 'quiz-1',
    question: 'In ancient Egypt, what was the term for barbers?',
    answer_a: 'Scribes',
    answer_b: 'Priests',
    answer_c: 'Meryma\'at',
    answer_d: 'Servants',
    correct_answer: 'c',
    explanation: 'Egyptian barbers were called "Meryma\'at" (pronounced means-a-mot). They held high social standing and were highly esteemed members of society.',
    difficulty: 'easy',
    order_index: 10,
  },

  // ═══════════════════════════════════════════════════════════
  // MEDIUM QUESTIONS (10)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-1-011',
    quiz_id: 'quiz-1',
    question: 'Why did Alexander the Great order his soldiers to shave their beards?',
    answer_a: 'To improve hygiene in desert campaigns',
    answer_b: 'To distinguish his army from Persian forces',
    answer_c: 'Beards could be grabbed by enemies in hand-to-hand combat',
    answer_d: 'Religious conversion requirements',
    correct_answer: 'c',
    explanation: 'Beards could be grabbed by enemies during hand-to-hand combat, creating a tactical disadvantage in battle.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-1-012',
    quiz_id: 'quiz-1',
    question: 'What happened at the Council of Tours in 1163 that affected barbers?',
    answer_a: 'Barbers were granted medical licenses',
    answer_b: 'The first barber school was established',
    answer_c: 'The Pope forbade clergy from practicing medicine, transferring duties to barbers',
    answer_d: 'Barbers were banned from performing surgery',
    correct_answer: 'c',
    explanation: 'The Pope forbade clergy from practicing medicine or surgery, transferring those duties to barbers who already handled blades.',
    difficulty: 'medium',
    order_index: 12,
  },
  {
    id: 'qq-1-013',
    quiz_id: 'quiz-1',
    question: 'What did the Chinese queue hairstyle represent under Manchu rule?',
    answer_a: 'Religious devotion to Buddhism',
    answer_b: 'Membership in the imperial guard',
    answer_c: 'Political submission and obedience to the ruling government',
    answer_d: 'Wealth and merchant status',
    correct_answer: 'c',
    explanation: 'The forced queue hairstyle symbolized political submission and obedience to the ruling Manchu government.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-1-014',
    quiz_id: 'quiz-1',
    question: 'Which three companies dominated early electric clipper manufacturing?',
    answer_a: 'Gillette, Remington, and Philips',
    answer_b: 'Sears, Montgomery Ward, and Woolworth',
    answer_c: 'Wahl, Andis, and Oster',
    answer_d: 'General Electric, Westinghouse, and IBM',
    correct_answer: 'c',
    explanation: 'Wahl Clipper Corporation (1921), Andis (developed by Matthew Andis), and Oster (John Oster marketed motorized clippers in 1928) dominated early manufacturing.',
    difficulty: 'medium',
    order_index: 14,
  },
  {
    id: 'qq-1-015',
    quiz_id: 'quiz-1',
    question: 'In some states, who is legally permitted to display a barber pole?',
    answer_a: 'Only licensed barbershops employing licensed barbers',
    answer_b: 'Any business that offers hair services',
    answer_c: 'Any shop with a barber on staff, regardless of license',
    answer_d: 'Only shops that have been open for more than 5 years',
    correct_answer: 'a',
    explanation: 'Only LICENSED barbershops employing LICENSED barbers may display a barber pole. Some states prohibit non-licensed establishments from using this protected professional symbol.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-1-016',
    quiz_id: 'quiz-1',
    question: 'What spiritual significance did hair hold in many primitive and ancient cultures?',
    answer_a: 'Hair contained magical healing powers',
    answer_b: 'Long hair brought bad luck',
    answer_c: 'Hair was believed to be the gateway for spirits entering and leaving the body',
    answer_d: 'Hair should never be cut after age 30',
    correct_answer: 'c',
    explanation: 'Many ancient cultures believed hair was the gateway for spirits entering and leaving the body, giving it profound spiritual significance.',
    difficulty: 'medium',
    order_index: 16,
  },
  {
    id: 'qq-1-017',
    quiz_id: 'quiz-1',
    question: 'Why did Egyptian priests shave their entire bodies every third day?',
    answer_a: 'To prevent lice infestation',
    answer_b: 'To show allegiance to the pharaoh',
    answer_c: 'As a religious purification practice before rituals',
    answer_d: 'Because hair was considered unclean',
    correct_answer: 'c',
    explanation: 'Daily full-body shaving was a religious purification practice to maintain spiritual cleanliness before performing rituals.',
    difficulty: 'medium',
    order_index: 17,
  },
  {
    id: 'qq-1-018',
    quiz_id: 'quiz-1',
    question: 'What factors caused the decline of barbershops in the 1980s–1990s?',
    answer_a: 'Economic recession and high unemployment',
    answer_b: 'Government bans on barbering',
    answer_c: 'Unisex salons, full-service spas, long hair trends, and cosmetology licensing shifts',
    answer_d: 'Lack of interest among young people',
    correct_answer: 'c',
    explanation: 'Unisex salons, full-service spas, long hair fashion trends, and shifts toward cosmetology licensing reduced traditional barbershop demand.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-1-019',
    quiz_id: 'quiz-1',
    question: 'When and where were the earliest scissors developed?',
    answer_a: 'Ancient Rome, 500 BC',
    answer_b: 'China, during the Han Dynasty',
    answer_c: 'The Middle East, between 3000 and 2000 BC',
    answer_d: 'Medieval Europe, 1200 AD',
    correct_answer: 'c',
    explanation: 'The Middle East produced the earliest scissors between 3000 and 2000 BC, revolutionizing hair cutting precision.',
    difficulty: 'medium',
    order_index: 19,
  },
  {
    id: 'qq-1-020',
    quiz_id: 'quiz-1',
    question: 'What did Pythagoras believe about the relationship between hair and the brain?',
    answer_a: 'Hair blocked spiritual energy',
    answer_b: 'Hair prevented proper breathing',
    answer_c: 'Hair was the source of the brain\'s inspiration',
    answer_d: 'Hair had no significance',
    correct_answer: 'c',
    explanation: 'Pythagoras believed hair was the source of the brain\'s inspiration and that cutting it reduced intellectual capacity.',
    difficulty: 'medium',
    order_index: 20,
  },

  // ═══════════════════════════════════════════════════════════
  // HARD QUESTIONS (10)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-1-021',
    quiz_id: 'quiz-1',
    question: 'What event in 1096 led to the formation of the first barber guild in France?',
    answer_a: 'A royal decree requiring all men to be clean-shaven',
    answer_b: 'The Crusades created demand for battlefield barbers',
    answer_c: 'A plague outbreak required regular shaving',
    answer_d: 'The Archbishop of Rouen prohibited clergy from wearing beards',
    correct_answer: 'd',
    explanation: 'The Archbishop of Rouen prohibited clergy from wearing beards, which spurred the organization of barbers into a formal guild.',
    difficulty: 'hard',
    order_index: 21,
  },
  {
    id: 'qq-1-022',
    quiz_id: 'quiz-1',
    question: 'When barbers and surgeons merged in 1450 England, what procedures were barbers RESTRICTED to performing?',
    answer_a: 'Only haircuts and shaves',
    answer_b: 'Major operations and autopsies',
    answer_c: 'Bloodletting, tooth pulling, cauterization, and tonsorial services',
    answer_d: 'Childbirth assistance and midwifery',
    correct_answer: 'c',
    explanation: 'Barbers were restricted to bloodletting, tooth pulling, cauterization, and tonsorial services. Surgeons retained more complex procedures. This division created the professional boundaries that shaped modern barbering.',
    difficulty: 'hard',
    order_index: 22,
  },
  {
    id: 'qq-1-023',
    quiz_id: 'quiz-1',
    question: 'Which Russian ruler famously taxed bearded men?',
    answer_a: 'Catherine the Great',
    answer_b: 'Ivan the Terrible',
    answer_c: 'Peter the Great',
    answer_d: 'Nicholas II',
    correct_answer: 'c',
    explanation: 'Peter the Great imposed a beard tax as part of his modernization efforts to align Russian fashion with Western Europe.',
    difficulty: 'hard',
    order_index: 23,
  },
  {
    id: 'qq-1-024',
    quiz_id: 'quiz-1',
    question: 'What are the five main objectives of NABBA?',
    answer_a: 'Profit, expansion, marketing, sales, and recruitment',
    answer_b: 'Political lobbying, union organization, strike coordination, wage negotiation, and benefits management',
    answer_c: 'Promote information exchange, establish exam/licensing standards, set curriculum standards, support continuing education, and protect consumers',
    answer_d: 'Product development, tool manufacturing, school accreditation, advertising, and trade shows',
    correct_answer: 'c',
    explanation: 'NABBA promotes information exchange, establishes exam/licensing standards, sets curriculum standards, supports continuing education, and protects consumers.',
    difficulty: 'hard',
    order_index: 24,
  },
  {
    id: 'qq-1-025',
    quiz_id: 'quiz-1',
    question: 'Henry VIII reunified barbers and surgeons in 1540. How long did this reunification last?',
    answer_a: '50 years',
    answer_b: '100 years',
    answer_c: 'Over 200 years',
    answer_d: 'Until 1897',
    correct_answer: 'c',
    explanation: 'Henry VIII sought to strengthen the profession\'s political and economic power through unified representation. This reunification created the Company of Barbers and Surgeons of London, which lasted until the final separation of 1745 — over 200 years.',
    difficulty: 'hard',
    order_index: 25,
  },
  {
    id: 'qq-1-026',
    quiz_id: 'quiz-1',
    question: 'What is the alternative explanation for the red, white, and blue colors on American barber poles?',
    answer_a: 'They represent fire, purity, and water',
    answer_b: 'They represent courage, peace, and loyalty',
    answer_c: 'They represent patriotism and deference to the national flag',
    answer_d: 'They were chosen by the first barber school in 1893',
    correct_answer: 'c',
    explanation: 'While the traditional explanation ties colors to bloodletting (blood, bandages, veins), some historians suggest the red, white, and blue scheme in America represents patriotism and deference to the national flag.',
    difficulty: 'hard',
    order_index: 26,
  },
  {
    id: 'qq-1-027',
    quiz_id: 'quiz-1',
    question: 'In ancient Rome, how did hair color indicate social class during certain periods?',
    answer_a: 'Only noblewomen were permitted to color their hair',
    answer_b: 'Noblewomen tinted hair red, middle-class used blond, poor women dyed hair black',
    answer_c: 'Hair color was randomly assigned by the emperor',
    answer_d: 'Social class had no connection to hair color',
    correct_answer: 'b',
    explanation: 'Noblewomen tinted hair red, middle-class women used blond, and poor women dyed hair black. This color-coding system made social status immediately visible.',
    difficulty: 'hard',
    order_index: 27,
  },
  {
    id: 'qq-1-028',
    quiz_id: 'quiz-1',
    question: 'What is tonsure, and when was the circular tonsure abolished?',
    answer_a: 'A full-head shave, abolished in 1450',
    answer_b: 'A ceremonial beard trim, abolished in 1800',
    answer_c: 'Shaving a patch on the crown, abolished in 1972',
    answer_d: 'A side-lock hairstyle, still practiced today',
    correct_answer: 'c',
    explanation: 'Tonsure is the practice of shaving a patch on the crown of the head. The circular tonsure of St. Peter was abolished in 1972.',
    difficulty: 'hard',
    order_index: 28,
  },
  {
    id: 'qq-1-029',
    quiz_id: 'quiz-1',
    question: 'What medical procedures did barber-surgeons perform during the Middle Ages?',
    answer_a: 'Only haircuts and shaves',
    answer_b: 'Major operations and autopsies',
    answer_c: 'Bloodletting, minor surgery, herbal remedies, and tooth extractions',
    answer_d: 'Childbirth assistance and midwifery',
    correct_answer: 'c',
    explanation: 'Beyond grooming, barber-surgeons performed bloodletting, minor surgical procedures, herbal remedies, and tooth extractions.',
    difficulty: 'hard',
    order_index: 29,
  },
  {
    id: 'qq-1-030',
    quiz_id: 'quiz-1',
    question: 'What percentage of barber students were reported to be female by 1985?',
    answer_a: 'Approximately 10%',
    answer_b: 'Approximately 30%',
    answer_c: 'Over 50%',
    answer_d: 'Less than 5%',
    correct_answer: 'c',
    explanation: 'Over 50% of barber students were female by 1985. This statistic reveals barbering\'s transformation from an exclusively male profession to an inclusive field welcoming diverse practitioners.',
    difficulty: 'hard',
    order_index: 30,
  },
]

// ───────────────────────────────────────────────
// Quiz metadata
// ───────────────────────────────────────────────
export const chapter1QuizMeta = {
  id: 'quiz-1',
  chapter_id: 'ch-1',
  title: 'History of Barbering — Premium Quiz',
  description: '30 board-exam style questions derived from Chapter 1 flashcard curriculum. Passing score: 80%.',
  question_count: 30,
  passing_score: 80,
  time_limit_minutes: 45,
}

export default chapter1PremiumQuizQuestions
