// Chapter 9 Premium Quiz — The Skin: Structure, Disorders, and Diseases
// 30 questions generated STRICTLY from chapter-9-premium-flashcards.ts
// Randomized order + randomized answer positions per attempt

import { QuizQuestion } from '@/types'

export const chapter9PremiumQuizQuestions: QuizQuestion[] = [
  // ═══════════════════════════════════════════════════
  // CATEGORY 1: SKIN STRUCTURE & BASICS (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-001',
    quiz_id: 'quiz-9',
    question: 'What is the largest organ of the human body?',
    answer_a: 'The liver',
    answer_b: 'The skin',
    answer_c: 'The heart',
    answer_d: 'The brain',
    correct_answer: 'b',
    explanation: 'The SKIN is the body\'s largest organ. It serves as the first line of defense against disease and the environment, protects internal organs, regulates temperature, and provides sensory information.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'q9-002',
    quiz_id: 'quiz-9',
    question: 'What is the normal pH of healthy human skin?',
    answer_a: 'Highly alkaline (pH 9–10)',
    answer_b: 'Neutral (pH 7.0)',
    answer_c: 'Slightly acidic (approximately pH 5.5)',
    answer_d: 'Highly acidic (pH 2–3)',
    correct_answer: 'c',
    explanation: 'Healthy skin maintains a SLIGHTLY ACIDIC pH of approximately 5.5. This acidity creates a protective barrier against microorganisms, inhibiting bacterial growth.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'q9-003',
    quiz_id: 'quiz-9',
    question: 'Approximately what percentage of the body\'s blood supply goes to the skin?',
    answer_a: 'About 10%',
    answer_b: 'About 25%',
    answer_c: 'About 50%',
    answer_d: 'About 75%',
    correct_answer: 'c',
    explanation: 'About HALF (50%) of the body\'s blood supply flows through the skin. This massive blood flow is why the skin is considered an organ, not just a covering, and why it plays a critical role in temperature regulation.',
    difficulty: 'medium',
    order_index: 3,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 2: EPIDERMIS LAYERS (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-004',
    quiz_id: 'quiz-9',
    question: 'BOARD EXAM ALERT: Does the epidermis contain blood vessels?',
    answer_a: 'Yes, the epidermis has a rich blood supply',
    answer_b: 'No, the epidermis contains NO blood vessels',
    answer_c: 'Only in the deepest layer (stratum germinativum)',
    answer_d: 'Only in damaged or inflamed skin',
    correct_answer: 'b',
    explanation: 'NO — the epidermis contains NO blood vessels. It receives nutrients entirely by diffusion from the dermis below. This is one of the most commonly tested facts on state board exams.',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'q9-005',
    quiz_id: 'quiz-9',
    question: 'Which epidermis layer contains melanocytes that produce melanin?',
    answer_a: 'Stratum corneum',
    answer_b: 'Stratum granulosum',
    answer_c: 'Stratum germinativum (basal cell layer)',
    answer_d: 'Stratum lucidum',
    correct_answer: 'c',
    explanation: 'The STRATUM GERMINATIVUM (basal cell layer) contains MELANOCYTES, which produce MELANIN — the pigment that gives skin its color and protects against UV damage.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'q9-006',
    quiz_id: 'quiz-9',
    question: 'In which layer of the epidermis are cells filled with keratin and becoming almost dead?',
    answer_a: 'Stratum spinosum',
    answer_b: 'Stratum granulosum',
    answer_c: 'Stratum lucidum',
    answer_d: 'Stratum corneum',
    correct_answer: 'b',
    explanation: 'The STRATUM GRANULOSUM (granular layer). Keratin is the protein that makes skin waterproof and durable. By the time cells reach this layer, they are transitioning from living to dead.',
    difficulty: 'medium',
    order_index: 6,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 3: DERMIS, SUBCUTANEOUS & NERVES (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-007',
    quiz_id: 'quiz-9',
    question: 'How much thicker is the dermis than the epidermis?',
    answer_a: 'About 5× thicker',
    answer_b: 'About 10× thicker',
    answer_c: 'About 25× thicker',
    answer_d: 'About 50× thicker',
    correct_answer: 'c',
    explanation: 'The dermis is approximately 25× THICKER than the epidermis. It contains all the skin\'s functional structures: glands, blood vessels, hair follicles, lymph glands, arrector pili muscles, and oil glands.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'q9-008',
    quiz_id: 'quiz-9',
    question: 'Which nerve fiber type controls arrector pili muscles (goose bumps) and stimulates glandular activity?',
    answer_a: 'Sensory nerve fibers',
    answer_b: 'Motor nerve fibers',
    answer_c: 'Secretory nerve fibers',
    answer_d: 'Autonomic nerve fibers',
    correct_answer: 'b',
    explanation: 'MOTOR nerve fibers control arrector pili muscles (goose bumps) and stimulate glandular activity. SENSORY fibers react to heat, cold, touch, pressure, and pain. SECRETORY fibers regulate sweat and oil gland secretion.',
    difficulty: 'medium',
    order_index: 8,
  },
  {
    id: 'q9-009',
    quiz_id: 'quiz-9',
    question: 'What two substances provide skin strength and elasticity, and what happens when they decrease?',
    answer_a: 'Keratin and melanin — skin becomes dry and discolored',
    answer_b: 'Collagen and elastin — skin sags and wrinkles form',
    answer_c: 'Sebum and sweat — skin becomes oily or dehydrated',
    answer_d: 'Melanin and hemoglobin — skin loses color and warmth',
    correct_answer: 'b',
    explanation: 'COLLAGEN provides strength and structural support. ELASTIN provides elasticity — the ability to stretch and return to shape. When production decreases with age, skin sags and wrinkles form.',
    difficulty: 'medium',
    order_index: 9,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 4: GLANDS & SKIN FUNCTIONS (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-010',
    quiz_id: 'quiz-9',
    question: 'In the SHAPES mnemonic for skin functions, what does the "S" stand for?',
    answer_a: 'Secretion',
    answer_b: 'Sensation',
    answer_c: 'Sun protection',
    answer_d: 'Structure',
    correct_answer: 'b',
    explanation: 'S — SENSATION (touch, pressure, pain, heat, cold). The full SHAPES mnemonic: Sensation, Heat regulation, Absorption, Protection, Excretion, Secretion.',
    difficulty: 'easy',
    order_index: 10,
  },
  {
    id: 'q9-011',
    quiz_id: 'quiz-9',
    question: 'What is the difference between sebaceous glands and sudoriferous glands?',
    answer_a: 'Sebaceous glands produce sweat; sudoriferous glands produce oil',
    answer_b: 'Sebaceous glands produce oil (sebum); sudoriferous glands produce sweat',
    answer_c: 'Sebaceous glands are only on the scalp; sudoriferous glands are only on the palms',
    answer_d: 'There is no difference — they are the same gland with two names',
    correct_answer: 'b',
    explanation: 'SEBACEOUS (oil) glands produce SEBUM to lubricate skin and hair. SUDORIFEROUS (sweat) glands produce SWEAT to regulate body temperature and eliminate waste. Mnemonic: SEBACEOUS = SEbum. SUDORIFEROUS = SWeat.',
    difficulty: 'easy',
    order_index: 11,
  },
  {
    id: 'q9-012',
    quiz_id: 'quiz-9',
    question: 'What causes the dark color of a blackhead (open comedo)?',
    answer_a: 'Dirt and grime trapped in the pore',
    answer_b: 'Oxidation of sebum and melanin when exposed to air',
    answer_c: 'Bacterial infection causing discoloration',
    answer_d: 'Excess melanin production in the follicle',
    correct_answer: 'b',
    explanation: 'The dark color comes from OXIDATION of sebum and melanin when the plugged follicle is open to air — NOT dirt. This is why cleansing alone cannot remove blackheads.',
    difficulty: 'medium',
    order_index: 12,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 5: PRIMARY LESIONS (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-013',
    quiz_id: 'quiz-9',
    question: 'What is the key difference between a BULLA and a VESICLE?',
    answer_a: 'A bulla contains pus; a vesicle contains clear fluid',
    answer_b: 'A bulla is large; a vesicle is small',
    answer_c: 'A bulla is infected; a vesicle is not infected',
    answer_d: 'A bulla is deep in the dermis; a vesicle is superficial',
    correct_answer: 'b',
    explanation: 'Both are fluid-filled blisters, but SIZE is the distinguishing factor: BULLA = LARGE blister with watery fluid. VESICLE = SMALL blister with clear fluid. BOARD EXAM ALERT: Size is the only difference — know this distinction cold.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'q9-014',
    quiz_id: 'quiz-9',
    question: 'What is a MACULE, and how can you identify one?',
    answer_a: 'A raised, pus-filled lesion that is palpable',
    answer_b: 'A flat spot or discoloration with NO change in skin texture — non-palpable',
    answer_c: 'A deep, solid bump extending into the dermis',
    answer_d: 'A cracked lesion that penetrates into the dermis',
    correct_answer: 'b',
    explanation: 'A MACULE is a flat spot or discoloration with NO change in skin texture. Key identifier: Macules are NON-PALPABLE — you cannot feel them by touch. Examples: freckle, liver spot, birthmark.',
    difficulty: 'medium',
    order_index: 14,
  },
  {
    id: 'q9-015',
    quiz_id: 'quiz-9',
    question: 'What is a PUSTULE, and why is it important for barbers to recognize?',
    answer_a: 'A flat discoloration with no texture change',
    answer_b: 'A raised, inflamed lesion containing PUS — indicates active infection',
    answer_c: 'A fluid-filled blister caused by burns or allergic reactions',
    answer_d: 'A thick scar extending beyond wound boundaries',
    correct_answer: 'b',
    explanation: 'A PUSTULE is a raised, inflamed papule containing PUS. Examples: acne, impetigo, folliculitis. BARBER IMPACT: Never perform services on skin with pustules — the risk of infection spread is high.',
    difficulty: 'easy',
    order_index: 15,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 6: SECONDARY LESIONS (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-016',
    quiz_id: 'quiz-9',
    question: 'What is the difference between PRIMARY and SECONDARY skin lesions?',
    answer_a: 'Primary lesions are infected; secondary lesions are not infected',
    answer_b: 'Primary lesions appear first from disease/injury; secondary lesions evolve from primary lesions',
    answer_c: 'Primary lesions are flat; secondary lesions are raised',
    answer_d: 'Primary lesions are contagious; secondary lesions are not contagious',
    correct_answer: 'b',
    explanation: 'PRIMARY lesions are the ORIGINAL lesions — they appear first, directly from a disease process or injury. SECONDARY lesions EVOLVE from primary lesions through accumulation, infection, or healing. Example: a vesicle that breaks open and dries becomes a CRUST.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'q9-017',
    quiz_id: 'quiz-9',
    question: 'What is a KELOID, and who is more prone to developing them?',
    answer_a: 'A flat discoloration caused by sun damage; more common in fair skin',
    answer_b: 'A thick scar from excessive fibrous tissue growth; more common in darker skin types',
    answer_c: 'A fluid-filled blister from burns; more common in elderly clients',
    answer_d: 'A cracked lesion from dry skin; more common in cold climates',
    correct_answer: 'b',
    explanation: 'A KELOID is a thick scar resulting from EXCESSIVE fibrous tissue growth. It extends beyond the original wound boundaries. More common in DARKER SKIN TYPES. Can form after piercings, cuts, or any skin injury.',
    difficulty: 'medium',
    order_index: 17,
  },
  {
    id: 'q9-018',
    quiz_id: 'quiz-9',
    question: 'Why must a barber NEVER shave over an ULCER?',
    answer_a: 'Ulcers are contagious and can spread to other clients',
    answer_b: 'Ulcers indicate compromised skin integrity; shaving could cause bleeding, infection, and delayed healing',
    answer_c: 'Ulcers are always cancerous and require immediate medical attention',
    answer_d: 'Ulcers produce excess oil that clogs razors',
    correct_answer: 'b',
    explanation: 'An ULCER is an open lesion with LOSS OF SKIN DEPTH. BARBER SAFETY: Never shave over ulcers — they indicate compromised skin integrity. Shaving could cause bleeding, infection, and delayed healing. Always refer clients with open ulcers to a physician.',
    difficulty: 'easy',
    order_index: 18,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 7: SEBACEOUS GLAND DISORDERS (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-019',
    quiz_id: 'quiz-9',
    question: 'What bacteria causes acne (acne vulgaris)?',
    answer_a: 'Staphylococcus aureus',
    answer_b: 'Propionibacterium acnes',
    answer_c: 'Streptococcus pyogenes',
    answer_d: 'Candida albicans',
    correct_answer: 'b',
    explanation: 'Propionibacterium acnes multiplies in clogged follicles, causing inflammation and infection. Hormonal changes and excess sebum also contribute. Grades range from I (mild) to IV (very severe/cystic).',
    difficulty: 'medium',
    order_index: 19,
  },
  {
    id: 'q9-020',
    quiz_id: 'quiz-9',
    question: 'BOARD EXAM ALERT: What is the relationship between a sebaceous cyst and a steatoma?',
    answer_a: 'They are completely different conditions',
    answer_b: 'A steatoma is a type of sebaceous cyst that only appears on the scalp',
    answer_c: 'They are the SAME CONDITION with different names',
    answer_d: 'A sebaceous cyst is infected; a steatoma is not infected',
    correct_answer: 'c',
    explanation: 'They are the SAME CONDITION with different names. Both refer to a large pocket filled with SEBUM. A sebaceous cyst may also be called a steatoma or wen. Know BOTH terms for the exam.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'q9-021',
    quiz_id: 'quiz-9',
    question: 'What is ROSACEA, and what should a barber do when serving a client with rosacea?',
    answer_a: 'Treat it with hot towels and vigorous massage to increase blood flow',
    answer_b: 'Handle gently, avoid hot towels and harsh products, and refer to a dermatologist',
    answer_c: 'Apply acne medications to reduce inflammation',
    answer_d: 'Shave carefully over red patches to remove surface irritation',
    correct_answer: 'b',
    explanation: 'ROSACEA is a chronic condition causing flushing, redness, dilated blood vessels, and papules/pustules. BARBER IMPACT: Handle rosacea clients gently. Avoid hot towels, harsh products, and friction. Do not attempt to treat — refer to a dermatologist.',
    difficulty: 'medium',
    order_index: 21,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 8: SUDORIFEROUS DISORDERS & INFLAMMATIONS (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-022',
    quiz_id: 'quiz-9',
    question: 'What is ANHIDROSIS, and why is it life-threatening?',
    answer_a: 'Excessive sweating that causes dehydration',
    answer_b: 'Inability to sweat, which prevents the body from cooling itself',
    answer_c: 'A contagious fungal infection of the sweat glands',
    answer_d: 'An allergic reaction causing hives and fluid accumulation',
    correct_answer: 'b',
    explanation: 'ANHIDROSIS is the deficiency or complete INABILITY TO SWEAT. It is life-threatening because the body cannot cool itself through evaporation. BARBER IMPACT: Clients with anhidrosis may overheat during services under warm towels or steam.',
    difficulty: 'medium',
    order_index: 22,
  },
  {
    id: 'q9-023',
    quiz_id: 'quiz-9',
    question: 'Is PSORIASIS contagious, and how should a barber handle a client who has it?',
    answer_a: 'Yes, it is contagious — wear gloves and disinfect all tools immediately',
    answer_b: 'No, it is NOT contagious — handle gently and avoid irritating the skin',
    answer_c: 'Only scalp psoriasis is contagious; body psoriasis is not',
    answer_d: 'It is contagious only during flare-ups with visible scales',
    correct_answer: 'b',
    explanation: 'PSORIASIS is autoimmune-related and NOT contagious. BARBER HANDLING: Clients with scalp psoriasis may have flakes resembling severe dandruff. Handle GENTLY. Avoid irritating the skin with harsh products, hot water, or vigorous brushing. Do not attempt to remove scales.',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'q9-024',
    quiz_id: 'quiz-9',
    question: 'Why should a barber NEVER shave over active HERPES SIMPLEX (cold sore) lesions?',
    answer_a: 'The virus is only contagious after the blisters have dried',
    answer_b: 'Herpes simplex is highly contagious during active outbreaks; shaving spreads the virus',
    answer_c: 'Shaving causes permanent scarring over herpes lesions',
    answer_d: 'Herpes lesions bleed excessively when shaved',
    correct_answer: 'b',
    explanation: 'Herpes simplex is HIGHLY CONTAGIOUS during active outbreaks. The virus spreads by contact with fluid from blisters. Shaving over active lesions spreads the virus to other areas of the face and can infect the barber. ALWAYS postpone facial services until lesions are completely healed.',
    difficulty: 'easy',
    order_index: 24,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 9: PIGMENT DISORDERS & HYPERTROPHIES (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-025',
    quiz_id: 'quiz-9',
    question: 'What is the difference between HYPERPIGMENTATION and HYPOPIGMENTATION?',
    answer_a: 'Hyperpigmentation is lighter skin; hypopigmentation is darker skin',
    answer_b: 'Hyperpigmentation is darker than normal skin; hypopigmentation is lighter or white patches',
    answer_c: 'Hyperpigmentation is contagious; hypopigmentation is not contagious',
    answer_d: 'Hyperpigmentation affects only the scalp; hypopigmentation affects the face',
    correct_answer: 'b',
    explanation: 'HYPERPIGMENTATION = darker than normal skin patches (e.g., freckles, liver spots). HYPOPIGMENTATION = lighter or white patches (e.g., vitiligo). Both are changes in melanin production. Neither is contagious.',
    difficulty: 'easy',
    order_index: 25,
  },
  {
    id: 'q9-026',
    quiz_id: 'quiz-9',
    question: 'What is a VERRUCA (wart), and why is it a barber safety concern?',
    answer_a: 'A benign mole that requires no special precautions',
    answer_b: 'A contagious growth caused by HPV that can spread by contact — never shave over warts',
    answer_c: 'A type of skin cancer that requires immediate referral',
    answer_d: 'A dry, scaly patch caused by sebum deficiency',
    correct_answer: 'b',
    explanation: 'A VERRUCA is caused by HUMAN PAPILLOMAVIRUS (HPV). It is CONTAGIOUS and can spread by scratching or contact. BARBER SAFETY: NEVER shave over warts. The virus can spread to other areas and to you. Refer clients with warts for medical treatment.',
    difficulty: 'easy',
    order_index: 26,
  },
  {
    id: 'q9-027',
    quiz_id: 'quiz-9',
    question: 'What is a KERATOMA (callus), and should a barber remove it?',
    answer_a: 'Yes, remove it to improve the client\'s appearance',
    answer_b: 'No — calluses are the skin\'s natural defense; do NOT remove them',
    answer_c: 'Only remove small calluses; leave large ones alone',
    answer_d: 'Remove them only with proper medical training',
    correct_answer: 'b',
    explanation: 'A KERATOMA is a thickened patch of skin caused by friction or pressure. Calluses and corns are types of keratomas. BARBER RULE: Do NOT remove calluses or corns. They are the skin\'s NATURAL DEFENSE against continued pressure. Removing them exposes underlying tissue to injury and infection.',
    difficulty: 'easy',
    order_index: 27,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 10: SKIN CANCER & SAFETY (3 questions)
  // ═══════════════════════════════════════════════════
  {
    id: 'q9-028',
    quiz_id: 'quiz-9',
    question: 'What are the three types of skin cancer, ranked from most common/least severe to least common/most dangerous?',
    answer_a: 'Melanoma, squamous cell, basal cell',
    answer_b: 'Basal cell carcinoma, squamous cell carcinoma, malignant melanoma',
    answer_c: 'Squamous cell, basal cell, melanoma',
    answer_d: 'Melanoma, basal cell, squamous cell',
    correct_answer: 'b',
    explanation: '1. BASAL CELL CARCINOMA — most common (80% of cases), least severe, pearly nodules, rarely metastasizes. 2. SQUAMOUS CELL CARCINOMA — more serious (20% of cases), scaly red papules, can metastasize. 3. MALIGNANT MELANOMA — least common but MOST DANGEROUS, 100% fatal if untreated. Mnemonic: "Basal = Best outcome. Melanoma = Most deadly."',
    difficulty: 'medium',
    order_index: 28,
  },
  {
    id: 'q9-029',
    quiz_id: 'quiz-9',
    question: 'What does the "C" in the ABCDE melanoma detection rule stand for?',
    answer_a: 'Circumference (size around the lesion)',
    answer_b: 'Color variation (multiple colors present)',
    answer_c: 'Contour (raised vs. flat)',
    answer_d: 'Consistency (hard vs. soft texture)',
    correct_answer: 'b',
    explanation: 'C — COLOR variation (multiple colors: brown, black, tan, red, white, blue). Full ABCDE rule: A = Asymmetry, B = Border irregularity, C = Color variation, D = Diameter (>6mm), E = Evolution (changing). This appears on EVERY board exam.',
    difficulty: 'easy',
    order_index: 29,
  },
  {
    id: 'q9-030',
    quiz_id: 'quiz-9',
    question: 'What is a barber\'s professional obligation when they see a suspicious skin condition on a client?',
    answer_a: 'Diagnose the condition and recommend over-the-counter treatments',
    answer_b: 'Ignore it unless the client complains about symptoms',
    answer_c: 'Recognize (do not diagnose), refer to a physician, document, and protect the client',
    answer_d: 'Perform the service carefully to avoid aggravating the area',
    correct_answer: 'c',
    explanation: 'RECOGNIZE — Do not diagnose. You are a barber, not a doctor. REFER — Suggest a dermatologist or physician visit. DOCUMENT — Note your observation and the conversation. PROTECT — Do not perform services that could worsen the condition or spread infection. Your license and your client\'s health matter more than one appointment.',
    difficulty: 'medium',
    order_index: 30,
  },
]
