// Chapter 3: Professional Image — CANONICAL FLASHCARD BANK (C3-1)
//
// Rebuilt around the locked curriculum: four concept families mapped 1:1 to
// the textbook learning objectives (local Milady Ch3 source, pp. 40–50).
//   ch3-healthful-habits   (LO1) — 12 cards
//   ch3-professional-image (LO2) — 12 cards
//   ch3-ergonomics         (LO3) — 12 cards
//   ch3-human-relations    (LO4) — 12 cards
//
// All wording is original ASCYN PRO. No publisher prose.
// Card → concept mapping lives in chapter-3-concepts/mappings.ts.
//
// ID discipline: retained/revised cards keep their original fc-3 IDs.
// New cards continue the sequence (fc-3-041+). Cards removed from the core
// bank are preserved in chapter3EnrichmentFlashcards /
// chapter3RetiredFlashcards below — never silently repurposed.

import { Flashcard } from '@/types'

// ═══════════════════════════════════════════════════════════════
// CORE BANK — 48 active cards (served to students)
// ═══════════════════════════════════════════════════════════════

export const chapter3PremiumFlashcards: Flashcard[] = [
  // ── LO1 · HEALTHFUL HABITS (12) ──
  {
    id: 'fc-3-001',
    chapter_id: 'ch-3',
    front: 'Why is daily bathing essential for a professional barber?',
    back: 'Daily bathing prevents body odor, removes bacteria, and ensures personal cleanliness. Barbers work in close proximity to clients, so freshness builds trust before you even pick up a tool.',
    category: 'Healthful Habits',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-3-002',
    chapter_id: 'ch-3',
    front: 'How often should a barber wash their hands during the workday?',
    back: 'Wash hands throughout the day, including at the beginning of each service, after eating, after using the restroom, and anytime hands become contaminated. It is a fundamental healthful habit for anyone working close to clients.',
    category: 'Healthful Habits',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-3-004',
    chapter_id: 'ch-3',
    front: 'What is the proper way to maintain oral hygiene as a barber?',
    back: 'Brush and floss daily, use mouthwash, and keep breath mints available. You work face-to-face with clients — bad breath undermines an otherwise professional image.',
    category: 'Healthful Habits',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-3-040',
    chapter_id: 'ch-3',
    front: 'Why is it important for barbers to maintain their own physical fitness?',
    back: 'Regular physical activity improves circulation, oxygen supply, and organ function while developing the muscles and stamina barbering demands. A fit body supports a long, injury-resistant career.',
    category: 'Healthful Habits',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-3-041',
    chapter_id: 'ch-3',
    front: 'What are the four important personal hygiene habits every barber should practice daily?',
    back: '1) Wash hands throughout the day, including at the start of each service. 2) Do self-checks and freshen up (including underarms) as needed. 3) Brush and floss teeth, using mouthwash or breath mints. 4) Do not smoke during work hours.',
    category: 'Healthful Habits',
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-3-042',
    chapter_id: 'ch-3',
    front: 'Why is adequate sleep part of a barber\'s healthful daily routine?',
    back: 'Adequate sleep — an average of seven to eight hours — lets the body recover from fatigue. Rested barbers look healthier, think clearly, and perform better through long days on their feet.',
    category: 'Healthful Habits',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-3-043',
    chapter_id: 'ch-3',
    front: 'What role does relaxation play in a healthful daily routine?',
    back: 'Relaxation means a change of pace — a movie, reading, sports, or any activity that helps you unwind. Building it into your routine lets you return to work refreshed instead of running on empty.',
    category: 'Healthful Habits',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-3-044',
    chapter_id: 'ch-3',
    front: 'How does nutrition affect a barber\'s work?',
    back: 'What you eat affects your health, appearance, personality, and job performance. A balanced diet with vitamins and minerals fuels long days; excess sugar, salt, caffeine, and fatty or highly processed foods work against you.',
    category: 'Healthful Habits',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-3-045',
    chapter_id: 'ch-3',
    front: 'Why should barbers drink plenty of water during the workday?',
    back: 'Hydration supports energy, concentration, and overall health. Dehydration causes fatigue, headaches, and poor focus — all of which show up in the quality of your work.',
    category: 'Healthful Habits',
    difficulty: 'easy',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-3-046',
    chapter_id: 'ch-3',
    front: 'What is stress, and how should barbers manage it?',
    back: 'Stress is the inability to cope with a real or imagined threat, producing mental and physical responses. Manage it through rest, relaxation, exercise, and daily routines that give your body and mind time to recover — a life of moderation and balance creates harmony.',
    category: 'Healthful Habits',
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-3-047',
    chapter_id: 'ch-3',
    front: 'Why should barbers avoid smoking during work hours, and what should they do if they smoke on a break?',
    back: 'Smoke odor lingers on hair, clothes, and hands and is offensive to clients in close contact. If you smoke on a lunch break, brush your teeth, use mouthwash, and wash your hands before returning to clients.',
    category: 'Healthful Habits',
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-3-048',
    chapter_id: 'ch-3',
    front: 'Why do healthful habits matter beyond personal comfort?',
    back: 'Clients notice a barber\'s health and physical appearance immediately. Hygiene weaknesses — like coffee breath right before a service or stale clothing — may never be mentioned, but clients simply do not return, and they may tell others.',
    category: 'Healthful Habits',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },

  // ── LO2 · PROFESSIONAL IMAGE & GROOMING (12) ──
  {
    id: 'fc-3-003',
    chapter_id: 'ch-3',
    front: 'How should a barber maintain their nails for client services?',
    back: 'Keep nails clean and well maintained, at a length that suits your style while staying safe for client contact. Manicures keep hands and nails client-ready; broken nails and chipped polish happen occasionally but should not be a regular occurrence.',
    category: 'Professional Image & Grooming',
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-3-005',
    chapter_id: 'ch-3',
    front: 'Why should barbers avoid wearing strong fragrances at work?',
    back: 'Perfume oils and strong scents can trigger allergies and overwhelm clients in close quarters. Many shops adopt no-fragrance policies — skip cologne and perfume at work.',
    category: 'Professional Image & Grooming',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-3-006',
    chapter_id: 'ch-3',
    front: 'How often should a barber\'s uniform or work clothes be cleaned?',
    back: 'Daily or after every shift. Hair clippings, product residue, and sweat accumulate quickly. Keep backup uniforms ready so you are never forced to rewear a soiled one.',
    category: 'Professional Image & Grooming',
    difficulty: 'easy',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-3-007',
    chapter_id: 'ch-3',
    front: 'What type of footwear is most appropriate for barbers?',
    back: 'Supportive, polished, closed-toe shoes in good repair. They keep you comfortable through long hours of standing and protect your feet around electrical tools and sharp implements — flip-flops and open-toed shoes are unsafe at the station.',
    category: 'Professional Image & Grooming',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-3-008',
    chapter_id: 'ch-3',
    front: 'Why is it important for barbers to wear a clean uniform or apron?',
    back: 'A clean, pressed uniform protects your clothing and presents a professional image. Keep it stain-free, not just dirt-free — be mindful of spills and splashes when working with chemicals.',
    category: 'Professional Image & Grooming',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-3-009',
    chapter_id: 'ch-3',
    front: 'What jewelry is considered appropriate for barbers to wear while working?',
    back: 'Accessorize carefully: nothing that makes noise, dangles into a client\'s face, or can catch in equipment. A waterproof wristwatch is a practical choice for staying on schedule.',
    category: 'Professional Image & Grooming',
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-3-010',
    chapter_id: 'ch-3',
    front: 'Why should barbers avoid wearing revealing or inappropriate clothing?',
    back: 'Revealing clothing looks unprofessional and may make clients uncomfortable. Barbering is a professional service — dress modestly and appropriately for a workplace setting.',
    category: 'Professional Image & Grooming',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-3-011',
    chapter_id: 'ch-3',
    front: 'What hairstyle standard should a barber maintain?',
    back: 'Keep your own hair up-to-date, freshly cut, and well groomed — you are a representative of the profession and your style advertises your skills. Schedule your own hair appointments, or barter services with other barbers, so your look never gets neglected.',
    category: 'Professional Image & Grooming',
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-3-012',
    chapter_id: 'ch-3',
    front: 'Why is it important for barbers to maintain well-groomed facial hair?',
    back: 'A neat, trimmed beard or mustache testifies to your grooming skills — especially in an era when facial hair is popular. If you prefer clean-shaven, shave daily to avoid undue stubble.',
    category: 'Professional Image & Grooming',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-3-033',
    chapter_id: 'ch-3',
    front: 'What does the term "professional image" mean in barbering?',
    back: 'Professional image is the impression you project through both your outward appearance and your conduct in the workplace. It combines how you look with how you behave.',
    category: 'Professional Image & Grooming',
    difficulty: 'easy',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-3-049',
    chapter_id: 'ch-3',
    front: 'What is personal grooming, and why do employers value it?',
    back: 'Personal grooming is the process of caring for the parts of your body and maintaining an overall polished look. Owners and managers often view appearance and personality as important as technical knowledge and skills.',
    category: 'Professional Image & Grooming',
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-3-050',
    chapter_id: 'ch-3',
    front: 'What skin care and makeup guidance supports a professional image?',
    back: 'Follow a skin care regimen suited to your skin type, use protective products like sunscreen, and seek professional advice for skin problems. If you wear makeup, apply it before arriving at work — applying it at your station looks unprofessional and advertises poor time management.',
    category: 'Professional Image & Grooming',
    difficulty: 'medium',
    order_index: 24,
    is_active: true,
  },

  // ── LO3 · ERGONOMICS & BODY MECHANICS (12) ──
  {
    id: 'fc-3-014',
    chapter_id: 'ch-3',
    front: 'Why is good posture important when working as a barber?',
    back: 'Good posture conveys confidence, prevents fatigue, and protects against the chronic neck, shoulder, back, and leg problems that develop from standing and working improperly all day.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-3-028',
    chapter_id: 'ch-3',
    front: 'What is the purpose of an anti-fatigue mat at a barber station?',
    back: 'Anti-fatigue mats provide cushioned flooring that reduces leg and back strain from standing for long periods. They are a simple ergonomic upgrade for any station.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-3-037',
    chapter_id: 'ch-3',
    front: 'What is carpal tunnel syndrome and how can barbers prevent it?',
    back: 'Carpal tunnel syndrome is a wrist injury associated with repetitive hand movements — a common musculoskeletal disorder in barbering. Prevent it with ergonomically designed tools, neutral wrist positions, stretching, and regular breaks.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'medium',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-3-038',
    chapter_id: 'ch-3',
    front: 'Why should barbers stretch and walk around at intervals during the day?',
    back: 'Repetitive motions and long periods in one position have a cumulative effect on muscles and joints. Counteract them by stretching and walking at intervals — prevention is easier than recovery.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-3-039',
    chapter_id: 'ch-3',
    front: 'How should a barber position the client and chair for comfortable, safe work?',
    back: 'Adjust the chair height so the client\'s head is at a comfortable working level, and tilt the client\'s head as needed for better access. Good positioning lets you work without bending forward or twisting your body.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-3-051',
    chapter_id: 'ch-3',
    front: 'What is ergonomics?',
    back: 'Ergonomics is the science of designing the workplace — along with its equipment and tools — to make specific body movements more comfortable, efficient, and safe. Hydraulic chairs and hand-friendly shears are everyday examples.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-3-052',
    chapter_id: 'ch-3',
    front: 'What is physical presentation, and why does it matter?',
    back: 'Physical presentation is your posture and the way you walk and move. It conveys an image of confidence and can prevent fatigue and other physical problems throughout your career.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'easy',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-3-053',
    chapter_id: 'ch-3',
    front: 'What does correct standing posture look like for a barber?',
    back: 'Head up with chin parallel to the floor; neck elongated and balanced above the shoulders; chest lifted without slouching; shoulders level and relaxed; spine straight.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-3-054',
    chapter_id: 'ch-3',
    front: 'What does correct sitting posture look like?',
    back: 'Hips level, knees flexed slightly over the feet, soles flat on the floor under the knees with about a 90-degree angle at the knees, torso weight resting on the thighbones rather than the end of the spine, and the back kept erect.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'medium',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-3-055',
    chapter_id: 'ch-3',
    front: 'What posture problems should barbers learn to recognize?',
    back: 'Common problems include hunchback (rounded upper back), swayback (exaggerated lower-back curve), and combined hunchback-swayback. Recognizing these patterns early — and correcting them through awareness, exercise, and movement therapies when needed — keeps your body aligned for a long career.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-3-056',
    chapter_id: 'ch-3',
    front: 'A barber keeps bending forward and twisting to reach the client. What ergonomic corrections apply?',
    back: 'Adjust the chair so the client\'s head sits at a comfortable working level, tilt the client\'s head for access, keep your arms below about a 60-degree angle from your body, and keep your back and neck straight instead of leaning in.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'hard',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-3-057',
    chapter_id: 'ch-3',
    front: 'How should a barber position their wrists, grip, and stance while cutting?',
    back: 'Keep wrists in a straight, neutral position; avoid gripping tools tightly and avoid constantly bending the wrist up or down. Stand with legs hip-width apart, knees slightly bent, and pelvic area aligned with the abdomen.',
    category: 'Ergonomics & Body Mechanics',
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },

  // ── LO4 · HUMAN RELATIONS & COMMUNICATION (12) ──
  {
    id: 'fc-3-016',
    chapter_id: 'ch-3',
    front: 'What does "talking less, listening more" look like behind the chair?',
    back: 'Practice good listening skills: stay fully attentive to what the client is saying, and if something is unclear, ask questions to gain understanding. Clients notice when you genuinely hear them.',
    category: 'Human Relations & Communication',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-3-018',
    chapter_id: 'ch-3',
    front: 'What should a barber do if they are running late for an appointment?',
    back: 'Call the client as soon as possible to inform them. Apologize sincerely, offer a revised time, and thank them for their patience. Never leave a client waiting without notice.',
    category: 'Human Relations & Communication',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-3-019',
    chapter_id: 'ch-3',
    front: 'How should a barber handle a client who is unhappy with their haircut?',
    back: 'Stay calm, listen without defending, apologize sincerely, and offer to fix it promptly and to the client\'s satisfaction. Say: "I\'m sorry you\'re not happy. Let me fix this for you right now."',
    category: 'Human Relations & Communication',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-3-021',
    chapter_id: 'ch-3',
    front: 'Why should barbers avoid gossiping about clients or coworkers?',
    back: 'Gossip damages trust, creates a toxic work environment, and violates the ethical standard of confidentiality. Professional barbers never discuss other clients or coworkers.',
    category: 'Human Relations & Communication',
    difficulty: 'medium',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-3-022',
    chapter_id: 'ch-3',
    front: 'What is client confidentiality and why does it matter?',
    back: 'Client confidentiality means keeping personal information, conversations, and details private. It also means never discussing your own wages, tips, rent, or tax information at work. Violating that trust is hard to repair.',
    category: 'Human Relations & Communication',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-3-031',
    chapter_id: 'ch-3',
    front: 'Why should barbers maintain a positive approach even on difficult days?',
    back: 'Be pleasant and gracious — ready with a smile of greeting and a word of welcome for each client and coworker. A good sense of humor helps sustain a positive attitude, and clients feel the difference.',
    category: 'Human Relations & Communication',
    difficulty: 'medium',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-3-034',
    chapter_id: 'ch-3',
    front: 'Why is punctuality considered a critical professional trait for barbers?',
    back: 'Punctuality shows respect for clients\' time and keeps the day running smoothly. Arrive on time, keep appointments on schedule, and plan your day so you still get breaks and a healthy lunch.',
    category: 'Human Relations & Communication',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-3-035',
    chapter_id: 'ch-3',
    front: 'What are the core do\'s and don\'ts of professional social-media behavior for barbers?',
    back: 'DO manage your pages, communicate with peers and clients, and post helpful content. DON\'T use profane language, entertain online arguments, post embarrassing photographs, or forward spam. Your online image is a daily investment in your business.',
    category: 'Human Relations & Communication',
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-3-058',
    chapter_id: 'ch-3',
    front: 'What are human relations and rapport, and why do they matter in the barbershop?',
    back: 'Human relations are the interactions and relationships between two or more people. Rapport is a close, empathetic relationship that fosters agreement and harmony. Together they are the foundation of client loyalty and a healthy shop culture.',
    category: 'Human Relations & Communication',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-3-059',
    chapter_id: 'ch-3',
    front: 'What is effective communication, and what three-step process supports it?',
    back: 'Effective communication is successfully sharing information so it is understood. Before cutting: 1) Organize your thoughts — decide what you need to know. 2) Clarify — pin down what the client\'s words actually mean. 3) Repeat — restate your interpretation so the client can confirm or correct it.',
    category: 'Human Relations & Communication',
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-3-060',
    chapter_id: 'ch-3',
    front: 'What is emotional control, and how does a professional barber practice it?',
    back: 'Emotional control means responding rather than reacting. Do not reveal negative emotions — anger, envy, dislike — through gestures, facial expressions, or conversation. Even-tempered professionals earn respect.',
    category: 'Human Relations & Communication',
    difficulty: 'medium',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-3-061',
    chapter_id: 'ch-3',
    front: 'Which mannerisms strengthen — or undermine — a barber\'s professional image?',
    back: 'Good manners reflect thoughtfulness: courtesy, care for others\' property, tolerance. Avoid gum chewing, nervous habits like foot-tapping or hair-playing, and conceal yawns, coughs, and sneezes with a hand in front of your mouth.',
    category: 'Human Relations & Communication',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },
]

// ═══════════════════════════════════════════════════════════════
// ENRICHMENT SET — ASCYN-original, beyond the textbook scope.
// NOT wired into student serving (flashcards-data.ts imports only the
// core bank). is_active: false documents that these are not part of the
// core curriculum. Nothing here is represented as textbook-required or
// board-tested.
// ═══════════════════════════════════════════════════════════════

export const chapter3EnrichmentFlashcards: Flashcard[] = [
  {
    id: 'fc-3-013',
    chapter_id: 'ch-3',
    front: 'What should a barber do if they have a visible tattoo?',
    back: 'Follow shop policy — cover it if required, or choose employers with flexible policies. Some shops require tattoos to be covered for a more traditional professional appearance. (ASCYN enrichment: shop-culture guidance, not a textbook rule.)',
    category: 'ASCYN Enrichment',
    difficulty: 'medium',
    order_index: 13,
    is_active: false,
  },
  {
    id: 'fc-3-017',
    chapter_id: 'ch-3',
    front: 'Why should barbers avoid using their phone during client services?',
    back: 'Using a phone during a service pulls your attention away from the client and makes them feel undervalued. Give every client your undivided attention; keep the phone stored away. (ASCYN enrichment: modern etiquette extension.)',
    category: 'ASCYN Enrichment',
    difficulty: 'easy',
    order_index: 17,
    is_active: false,
  },
  {
    id: 'fc-3-020',
    chapter_id: 'ch-3',
    front: 'Why should a barber ask permission before posting a client\'s photo on social media?',
    back: 'Asking first respects the client\'s privacy and protects the trust you have built — a client who feels respected is a client who refers. Treat consent as standard professional practice, not an afterthought. (ASCYN enrichment: best practice, not a universal legal rule — specific requirements vary by jurisdiction.)',
    category: 'ASCYN Enrichment',
    difficulty: 'medium',
    order_index: 20,
    is_active: false,
  },
  {
    id: 'fc-3-024',
    chapter_id: 'ch-3',
    front: 'What should a barber do if a client offers a large tip?',
    back: 'Accept it graciously with a sincere thank you. Large tips reflect excellent service. Never demand tips or make clients feel obligated to tip. (ASCYN enrichment: service etiquette.)',
    category: 'ASCYN Enrichment',
    difficulty: 'easy',
    order_index: 24,
    is_active: false,
  },
  {
    id: 'fc-3-029',
    chapter_id: 'ch-3',
    front: 'Why is continuing education valuable for barbers?',
    back: 'Continuing education keeps skills current, introduces new techniques, and shows clients you are committed to excellence. The industry constantly evolves. (ASCYN enrichment: professional development. Licensing requirements vary by state — check your own state board.)',
    category: 'ASCYN Enrichment',
    difficulty: 'medium',
    order_index: 29,
    is_active: false,
  },
  {
    id: 'fc-3-062',
    chapter_id: 'ch-3',
    front: 'What distinguishes luxury-level professionalism from baseline professionalism?',
    back: 'Luxury-level professionals control details others ignore: documented client preferences, identical setup rituals, proactive schedule communication, and immediate ownership of mistakes. Consistency in small things is what clients describe as "elite." (ASCYN enrichment: brand-standard content.)',
    category: 'ASCYN Enrichment',
    difficulty: 'medium',
    order_index: 62,
    is_active: false,
  },
]

// ═══════════════════════════════════════════════════════════════
// RETIRED / RE-HOMED — removed from Chapter 3 core serving.
// Preserved for history with original IDs; never repurposed.
// Re-home destinations are recommendations only — C3-1 does not
// authorize modifying the destination chapters.
// ═══════════════════════════════════════════════════════════════

export const chapter3RetiredFlashcards: Flashcard[] = [
  {
    // RETIRED: "7 seconds" first-impression claim had no source support
    // (defect C3-C001). First-impression concept now taught via fc-3-033
    // and the lesson intro with textbook-supported framing.
    id: 'fc-3-015',
    chapter_id: 'ch-3',
    front: 'How long do clients typically take to form a first impression of their barber?',
    back: 'Within the first 7 seconds. A clean, professional appearance signals competence and attention to detail before you even speak.',
    category: 'Retired',
    difficulty: 'easy',
    order_index: 15,
    is_active: false,
  },
  {
    // RE-HOME → Chapter 9 bridge (scope-of-practice / no-diagnosis)
    id: 'fc-3-023',
    chapter_id: 'ch-3',
    front: 'Why should a barber not diagnose skin or scalp conditions?',
    back: 'Barbers are not medical professionals. Diagnosing conditions is outside your scope of practice. Recognize abnormalities and refer clients to a dermatologist or doctor.',
    category: 'Re-home → Ch9',
    difficulty: 'medium',
    order_index: 23,
    is_active: false,
  },
  {
    // RE-HOME → Chapter 4 (infection control / station sanitation)
    id: 'fc-3-025',
    chapter_id: 'ch-3',
    front: 'Why is it important to keep your barber station clean and organized?',
    back: 'A clean station shows professionalism, prevents cross-contamination, helps you work efficiently, and makes clients feel comfortable. Messy stations suggest sloppy work.',
    category: 'Re-home → Ch4',
    difficulty: 'easy',
    order_index: 25,
    is_active: false,
  },
  {
    // RE-HOME → Chapter 4 (infection control / dropped tools)
    id: 'fc-3-026',
    chapter_id: 'ch-3',
    front: 'What is the proper way to handle tools that fall on the floor during a service?',
    back: 'Replace them with clean tools or stop and disinfect them thoroughly before reuse. Tools that touch the floor are contaminated and must be sanitized.',
    category: 'Re-home → Ch4',
    difficulty: 'easy',
    order_index: 26,
    is_active: false,
  },
  {
    // RE-HOME → Chapter 4 (infection control / hair sweeping)
    id: 'fc-3-027',
    chapter_id: 'ch-3',
    front: 'Why should barbers sweep up hair clippings immediately after each client?',
    back: 'Immediate cleanup maintains hygiene, prevents slipping hazards, shows respect for the next client, and keeps the shop looking professional.',
    category: 'Re-home → Ch4',
    difficulty: 'easy',
    order_index: 27,
    is_active: false,
  },
  {
    // RE-HOME → career/business chapter (portfolio development)
    id: 'fc-3-030',
    chapter_id: 'ch-3',
    front: 'What is the purpose of a professional portfolio for a barber?',
    back: 'A portfolio showcases your best work, demonstrates your range of skills, helps attract new clients, and can be used for job applications or shop promotions.',
    category: 'Re-home → Ch19',
    difficulty: 'easy',
    order_index: 30,
    is_active: false,
  },
  {
    // RE-HOME → business chapter (client-base development)
    id: 'fc-3-032',
    chapter_id: 'ch-3',
    front: 'What is the most important factor in building a loyal client base?',
    back: 'Consistently delivering excellent service and building genuine relationships. Clients return because of trust, quality, and how you make them feel — not just price.',
    category: 'Re-home → Ch17/20',
    difficulty: 'medium',
    order_index: 32,
    is_active: false,
  },
  {
    // RE-HOME → licensure chapter (state regulation overview)
    id: 'fc-3-036',
    chapter_id: 'ch-3',
    front: 'Why is it important for barbers to understand and follow state regulations?',
    back: 'State regulations protect public health, ensure safety standards, and maintain professional credibility. Violations can result in fines, license suspension, or shop closure.',
    category: 'Re-home → Ch19',
    difficulty: 'medium',
    order_index: 36,
    is_active: false,
  },
]

export default chapter3PremiumFlashcards
