// Chapter 8 Premium Quiz — Flashcard-Driven Multiple Choice System
// 30 questions generated from Chapter 8 flashcard curriculum
// Randomized order, randomized answers, board-exam style

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 8 QUIZ: Basics of Electricity (30 Questions)
// Difficulty mix: 10 easy, 10 medium, 10 hard
// Sources: Electricity Fundamentals, DC vs AC, Measurements, Safety Devices,
//          Safety Rules, Electrotherapy, Light & Spectrum, Light Therapy, Common Confusions
// ───────────────────────────────────────────────

export const chapter8PremiumQuizQuestions: QuizQuestion[] = [
  // ═══════════════════════════════════════════════════════════
  // EASY QUESTIONS (10)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-8-001',
    quiz_id: 'quiz-8',
    question: 'Electricity is classified as energy rather than matter. What does this mean?',
    answer_a: 'It does not occupy space or have mass',
    answer_b: 'It cannot be measured or controlled',
    answer_c: 'It only works in complete darkness',
    answer_d: 'It requires a vacuum to function',
    correct_answer: 'a',
    explanation: 'Electricity is a form of energy produced by the flow of electrons. It does not occupy space or have mass like matter does.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-8-002',
    quiz_id: 'quiz-8',
    question: 'Which of the following is a conductor of electricity?',
    answer_a: 'Rubber glove',
    answer_b: 'Plastic comb',
    answer_c: 'Copper wire',
    answer_d: 'Dry wooden stick',
    correct_answer: 'c',
    explanation: 'Copper is a metal and easily transmits electricity. Rubber, plastic, and dry wood are insulators that block electrical flow.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-8-003',
    quiz_id: 'quiz-8',
    question: 'What happens when an electric circuit is "open"?',
    answer_a: 'Electricity flows faster',
    answer_b: 'Electricity cannot flow',
    answer_c: 'The voltage doubles',
    answer_d: 'The circuit overheats',
    correct_answer: 'b',
    explanation: 'An open circuit has a break in the path, so electricity cannot flow — like a switched-off light.',
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-8-004',
    quiz_id: 'quiz-8',
    question: 'Direct Current (DC) flows in how many directions?',
    answer_a: 'Two directions, alternating',
    answer_b: 'One direction only',
    answer_c: 'Three directions simultaneously',
    answer_d: 'No direction — it is static',
    correct_answer: 'b',
    explanation: 'DC flows in ONE DIRECTION only. This is the type of current produced by batteries and used in cordless tools.',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-8-005',
    quiz_id: 'quiz-8',
    question: 'What does a VOLT measure?',
    answer_a: 'The strength of electrical current',
    answer_b: 'The resistance to electrical flow',
    answer_c: 'The electrical pressure that pushes electrons',
    answer_d: 'The total power consumed',
    correct_answer: 'c',
    explanation: 'A volt measures ELECTRICAL PRESSURE — the push that moves electrons through a conductor.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-8-006',
    quiz_id: 'quiz-8',
    question: 'What is the standard US voltage for wall outlets?',
    answer_a: '220–240 volts',
    answer_b: '50–60 volts',
    answer_c: '110–120 volts',
    answer_d: '360–400 volts',
    correct_answer: 'c',
    explanation: 'Standard US voltage is 110–120V. Some countries use 220–240V.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-8-007',
    quiz_id: 'quiz-8',
    question: 'What does the UL mark on electrical equipment indicate?',
    answer_a: 'It was made in the United Kingdom',
    answer_b: 'It has been tested and meets safety standards',
    answer_c: 'It uses universal voltage',
    answer_d: 'It is guaranteed for life',
    correct_answer: 'b',
    explanation: 'UL = Underwriters Laboratories. The mark indicates the equipment has been tested and meets safety standards.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-8-008',
    quiz_id: 'quiz-8',
    question: 'Where is a GFCI REQUIRED in a barbershop?',
    answer_a: 'Only behind the front desk',
    answer_b: 'Only in the break room',
    answer_c: 'Near sinks and all water sources',
    answer_d: 'Only in the storage closet',
    correct_answer: 'c',
    explanation: 'GFCI (Ground Fault Circuit Interrupter) is REQUIRED near sinks and all water sources to prevent electrical shock.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-8-009',
    quiz_id: 'quiz-8',
    question: 'What percentage of natural sunlight is visible light?',
    answer_a: '10%',
    answer_b: '35%',
    answer_c: '65%',
    answer_d: '100%',
    correct_answer: 'b',
    explanation: 'Visible light makes up 35% of natural sunlight. The remaining 65% is invisible light (UV and infrared).',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-8-010',
    quiz_id: 'quiz-8',
    question: 'What is the maximum recommended exposure time for light therapy?',
    answer_a: '15 minutes',
    answer_b: '10 minutes',
    answer_c: '5 minutes or less',
    answer_d: '30 minutes',
    correct_answer: 'c',
    explanation: 'Light therapy exposure is usually 5 MINUTES or less per area. Never leave a client unattended during treatment.',
    difficulty: 'easy',
    order_index: 10,
  },

  // ═══════════════════════════════════════════════════════════
  // MEDIUM QUESTIONS (10)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-8-011',
    quiz_id: 'quiz-8',
    question: 'Why is the human body considered a conductor of electricity?',
    answer_a: 'Because skin is naturally magnetic',
    answer_b: 'Because the body contains water and electrolytes',
    answer_c: 'Because bones are made of metal',
    answer_d: 'Because hair attracts electrons',
    correct_answer: 'b',
    explanation: 'The human body contains water and electrolytes, making it a conductor. This is why wet hands increase shock risk.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-8-012',
    quiz_id: 'quiz-8',
    question: 'A short circuit is dangerous because it:',
    answer_a: 'Reduces voltage to zero',
    answer_b: 'Causes overheating and fire risk',
    answer_c: 'Makes tools run slower',
    answer_d: 'Improves energy efficiency',
    correct_answer: 'b',
    explanation: 'A short circuit occurs when electricity takes an unintended shortcut, causing overheating and creating a fire risk.',
    difficulty: 'medium',
    order_index: 12,
  },
  {
    id: 'qq-8-013',
    quiz_id: 'quiz-8',
    question: 'Your cordless clipper uses a battery. The charger plugs into a wall outlet. What type of current does the CHARGER use?',
    answer_a: 'DC only',
    answer_b: 'AC only',
    answer_c: 'Both DC and AC simultaneously',
    answer_d: 'Neither — it uses solar power',
    correct_answer: 'b',
    explanation: 'The charger plugs into the wall and uses AC. It contains a converter/rectifier to change AC to DC for charging the battery.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-8-014',
    quiz_id: 'quiz-8',
    question: 'What is the formula for calculating watts?',
    answer_a: 'Watts = Volts ÷ Amps',
    answer_b: 'Watts = Amps × Volts',
    answer_c: 'Watts = Ohms × Volts',
    answer_d: 'Watts = Amps ÷ Ohms',
    correct_answer: 'b',
    explanation: 'Watts = Amps × Volts. A watt measures electrical power — the rate of energy used per second.',
    difficulty: 'medium',
    order_index: 14,
  },
  {
    id: 'qq-8-015',
    quiz_id: 'quiz-8',
    question: 'What is the main difference between a fuse and a circuit breaker?',
    answer_a: 'A fuse is reusable; a breaker must be replaced',
    answer_b: 'A fuse melts and must be replaced; a breaker trips and can be reset',
    answer_c: 'A fuse is used for DC; a breaker is used for AC',
    answer_d: 'There is no difference — they are the same device',
    correct_answer: 'b',
    explanation: 'A fuse melts when overloaded and must be replaced. A circuit breaker trips and can be reset.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-8-016',
    quiz_id: 'quiz-8',
    question: 'Why should you NEVER remove the third prong from a plug?',
    answer_a: 'It makes the cord too short',
    answer_b: 'It voids the warranty',
    answer_c: 'It eliminates the grounding safety path',
    answer_d: 'It changes the voltage',
    correct_answer: 'c',
    explanation: 'The third prong is the grounding pin. Removing it eliminates the safe escape path for electricity in case of malfunction.',
    difficulty: 'medium',
    order_index: 16,
  },
  {
    id: 'qq-8-017',
    quiz_id: 'quiz-8',
    question: 'The anode (positive pole) in electrotherapy is usually what color?',
    answer_a: 'Black',
    answer_b: 'Blue',
    answer_c: 'Red',
    answer_d: 'Green',
    correct_answer: 'c',
    explanation: 'The anode (+) is usually RED. The cathode (–) is usually BLACK.',
    difficulty: 'medium',
    order_index: 17,
  },
  {
    id: 'qq-8-018',
    quiz_id: 'quiz-8',
    question: 'Which pole produces cataphoresis?',
    answer_a: 'The negative pole (cathode)',
    answer_b: 'The positive pole (anode)',
    answer_c: 'Both poles simultaneously',
    answer_d: 'Neither pole — cataphoresis uses light',
    correct_answer: 'b',
    explanation: 'Cataphoresis is the process of introducing positive ions into the skin using the positive pole (anode).',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-8-019',
    quiz_id: 'quiz-8',
    question: 'What is the key principle about wavelength and energy in the electromagnetic spectrum?',
    answer_a: 'Long wavelengths carry more energy and penetrate less',
    answer_b: 'Short wavelengths carry more energy and penetrate less',
    answer_c: 'All wavelengths carry the same energy',
    answer_d: 'Wavelength has no effect on energy or penetration',
    correct_answer: 'b',
    explanation: 'Short wavelengths carry MORE energy but penetrate LESS. Long wavelengths carry LESS energy but penetrate MORE deeply.',
    difficulty: 'medium',
    order_index: 19,
  },
  {
    id: 'qq-8-020',
    quiz_id: 'quiz-8',
    question: 'Which LED color is used to reduce acne and kill bacteria?',
    answer_a: 'Red',
    answer_b: 'Yellow',
    answer_c: 'Blue',
    answer_d: 'Green',
    correct_answer: 'c',
    explanation: 'BLUE LED reduces acne and kills bacteria. RED increases circulation. YELLOW reduces swelling. GREEN reduces hyperpigmentation.',
    difficulty: 'medium',
    order_index: 20,
  },

  // ═══════════════════════════════════════════════════════════
  // HARD QUESTIONS (10)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-8-021',
    quiz_id: 'quiz-8',
    question: 'Your hair dryer is rated 1,800 watts at 120 volts. How many amps does it draw?',
    answer_a: '10 amps',
    answer_b: '15 amps',
    answer_c: '20 amps',
    answer_d: '25 amps',
    correct_answer: 'b',
    explanation: '1,800W ÷ 120V = 15 amps. A 20-amp circuit can handle one dryer plus small tools, but two dryers would trip the breaker.',
    difficulty: 'hard',
    order_index: 21,
  },
  {
    id: 'qq-8-022',
    quiz_id: 'quiz-8',
    question: 'A converter/rectifier in a cordless clipper charger performs what function?',
    answer_a: 'It increases voltage for faster charging',
    answer_b: 'It changes AC to DC for battery charging',
    answer_c: 'It stores electricity for power outages',
    answer_d: 'It reduces amperage to protect the battery',
    correct_answer: 'b',
    explanation: 'A converter/rectifier changes AC (wall outlet) to DC (battery). This allows battery-powered tools to charge from standard outlets.',
    difficulty: 'hard',
    order_index: 22,
  },
  {
    id: 'qq-8-023',
    quiz_id: 'quiz-8',
    question: 'You notice a frayed cord on your clipper. What is the CORRECT professional response?',
    answer_a: 'Wrap it with electrical tape and continue using it',
    answer_b: 'Use it carefully and avoid touching the frayed area',
    answer_c: 'Stop using it immediately and replace or professionally repair it',
    answer_d: 'Cut off the damaged plug and install a replacement yourself',
    correct_answer: 'c',
    explanation: 'STOP using the tool immediately. Label it unsafe. Use a backup. Replace or professionally repair the cord. Tape is not a permanent fix.',
    difficulty: 'hard',
    order_index: 23,
  },
  {
    id: 'qq-8-024',
    quiz_id: 'quiz-8',
    question: 'Which of the following is NOT a contraindication for galvanic current treatment?',
    answer_a: 'Broken capillaries',
    answer_b: 'High blood pressure',
    answer_c: 'Oily skin',
    answer_d: 'Metal implants',
    correct_answer: 'c',
    explanation: 'Oily skin is not a contraindication. Avoid galvanic current on broken capillaries, high blood pressure, metal implants, and pregnancy.',
    difficulty: 'hard',
    order_index: 24,
  },
  {
    id: 'qq-8-025',
    quiz_id: 'quiz-8',
    question: 'What is iontophoresis, and how do you select the correct pole?',
    answer_a: 'Use the positive pole for alkaline substances and the negative pole for acidic substances',
    answer_b: 'Use the positive pole for acidic substances and the negative pole for alkaline substances',
    answer_c: 'Always use both poles simultaneously',
    answer_d: 'The pole selection does not matter',
    correct_answer: 'b',
    explanation: 'Iontophoresis introduces water-soluble products into the skin. Use the POSITIVE pole for acidic substances and the NEGATIVE pole for alkaline substances.',
    difficulty: 'hard',
    order_index: 25,
  },
  {
    id: 'qq-8-026',
    quiz_id: 'quiz-8',
    question: 'Tesla high-frequency current is characterized by:',
    answer_a: 'Low oscillation rate and muscular contractions',
    answer_b: 'High oscillation rate, heat, violet ray, and no muscular contractions',
    answer_c: 'Direct current and chemical changes in the skin',
    answer_d: 'Sub-sensory levels that the client cannot feel',
    correct_answer: 'b',
    explanation: 'Tesla high-frequency current has a high rate of oscillation producing heat and a violet ray. No muscular contractions occur.',
    difficulty: 'hard',
    order_index: 26,
  },
  {
    id: 'qq-8-027',
    quiz_id: 'quiz-8',
    question: 'Which UV ray is absorbed by Earth\'s atmosphere and used in germicidal lamps?',
    answer_a: 'UVA',
    answer_b: 'UVB',
    answer_c: 'UVC',
    answer_d: 'All three types equally',
    correct_answer: 'c',
    explanation: 'UVC is absorbed by Earth\'s atmosphere but is used in germicidal lamps for sterilization purposes.',
    difficulty: 'hard',
    order_index: 27,
  },
  {
    id: 'qq-8-028',
    quiz_id: 'quiz-8',
    question: 'A client with a pacemaker requests a galvanic facial. What is the correct response?',
    answer_a: 'Proceed with lower intensity to be safe',
    answer_b: 'Use only the positive pole, which is safer',
    answer_c: 'Cancel the electrotherapy and suggest non-electrical alternatives',
    answer_d: 'Have them sign a waiver and proceed',
    correct_answer: 'c',
    explanation: 'Pacemakers and metal implants are ABSOLUTE contraindications for galvanic current. A waiver does not protect you from liability.',
    difficulty: 'hard',
    order_index: 28,
  },
  {
    id: 'qq-8-029',
    quiz_id: 'quiz-8',
    question: 'Selective photothermolysis is the principle behind:',
    answer_a: 'GFCI protection systems',
    answer_b: 'Medical lasers for hair removal and skin treatments',
    answer_c: 'Circuit breaker technology',
    answer_d: 'Battery charging systems',
    correct_answer: 'b',
    explanation: 'Selective photothermolysis is where light energy converts to heat, targeting specific structures. It is the principle behind medical lasers.',
    difficulty: 'hard',
    order_index: 29,
  },
  {
    id: 'qq-8-030',
    quiz_id: 'quiz-8',
    question: 'Which of the following therapeutic lamp colors treats acne, seborrhea, and dandruff?',
    answer_a: 'White',
    answer_b: 'Blue',
    answer_c: 'Red',
    answer_d: 'Ultraviolet',
    correct_answer: 'd',
    explanation: 'Ultraviolet light therapy treats acne, seborrhea, and dandruff due to its germicidal action. Use at 30–36 inches with short exposure.',
    difficulty: 'hard',
    order_index: 30,
  },
]

// ───────────────────────────────────────────────
// Quiz metadata
// ───────────────────────────────────────────────
export const chapter8QuizMeta = {
  id: 'quiz-8',
  chapter_id: 'ch-8',
  title: 'Basics of Electricity — Premium Quiz',
  description: '30 board-exam style questions derived from Chapter 8 flashcard curriculum. Passing score: 75%.',
  question_count: 30,
  passing_score: 75,
  time_limit_minutes: 45,
}

export default chapter8PremiumQuizQuestions
