// Chapter 5: Implements, Tools, and Equipment — PREMIUM FLASHCARDS
// The Barber's Forge - precision, steel, mastery
// Categories: Combs & Brushes, Shears, Clippers & Trimmers, Razors, Thermal Tools, Station & Safety, Board Exam Alerts

import { Flashcard } from '@/types'

export const chapter5PremiumFlashcards: Flashcard[] = [
  // ==========================================
  // CATEGORY 1: COMBS & BRUSHES (8 cards)
  // ==========================================
  {
    id: 'fc-5-001',
    chapter_id: 'ch-5',
    front: 'What are the two most durable and heat-resistant comb materials?',
    back: 'Carbon fiber and hard rubber. These materials resist heat from thermal tools and last longer than plastic combs. Board exam favorite question.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-5-002',
    chapter_id: 'ch-5',
    front: 'What is the standard length of an all-purpose cutting comb?',
    back: '7-8 inches. It features fine teeth on one end and medium teeth on the other for versatility in sectioning, scissor-over-comb, and general cutting.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-5-003',
    chapter_id: 'ch-5',
    front: 'What is the difference between a taper comb and an all-purpose comb?',
    back: 'Taper combs are shorter, sturdier, with teeth spaced to grip hair firmly for clipper-over-comb and scissor-over-comb tapering. All-purpose combs are longer and more versatile for general work.',
    category: 'Combs & Brushes',
    difficulty: 'medium',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-5-004',
    chapter_id: 'ch-5',
    front: 'CLIPPER GUARD SIZES: What length does a #2 guard cut?',
    back: '1/4 inch (6mm). This is the most common guard for basic cuts. Memorize: #0=1/16in, #1=1/8in, #2=1/4in, #3=3/8in, #4=1/2in.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-5-005',
    chapter_id: 'ch-5',
    front: 'What brush type creates volume and curl during blow-drying?',
    back: 'Round brush. Barrel size matters — larger barrels create bigger curls and more volume. Paddle brushes smooth and straighten; vent brushes speed drying time.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-5-006',
    chapter_id: 'ch-5',
    front: 'When should you replace a comb?',
    back: 'Replace combs with worn, broken, or missing teeth. Damaged teeth snag hair, damage the cuticle, and create uneven sections. A worn comb is a liability.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-5-007',
    chapter_id: 'ch-5',
    front: 'What brush is best for lifting and adding volume to textured and curly hair?',
    back: 'Pick or comb. Designed specifically to lift roots and add volume without disrupting curl pattern. Essential for textured hair finishing work.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-5-008',
    chapter_id: 'ch-5',
    front: 'Why should you clean styling brushes daily?',
    back: 'Hair and product buildup transfers between clients. Brushes collect oils, dead skin, and styling product residue. Daily cleaning prevents cross-contamination and maintains brush performance.',
    category: 'Combs & Brushes',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 2: SHEARS & SCISSORS (12 cards)
  // ==========================================
  {
    id: 'fc-5-009',
    chapter_id: 'ch-5',
    front: 'What is the difference between a convex edge and a beveled edge on shears?',
    back: 'Convex edge (hollow ground) is sharper and cuts more smoothly but is more fragile. Beveled edge is more durable and lasts longer but cuts less smoothly. Board exam alert.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-5-010',
    chapter_id: 'ch-5',
    front: 'What is the most versatile shear length for barbering?',
    back: '5.5 to 6 inches. This length handles 90% of haircutting work. Shears range from 5" to 7", but 5.5"-6" offers the best balance of control and reach.',
    category: 'Shears & Scissors',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-5-011',
    chapter_id: 'ch-5',
    front: 'How do you perform the shear tension test?',
    back: 'Hold the shear tips pointing up. Lift one handle. The blades should open partially — not fall completely open (too loose) and not stay closed (too tight). Do this before EVERY haircut.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-5-012',
    chapter_id: 'ch-5',
    front: 'What happens if shear tension is too loose?',
    back: 'The blades fall completely open. Hair bends between the blades instead of cutting cleanly. This creates split ends, uneven lines, and frustrated clients.',
    category: 'Shears & Scissors',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-5-013',
    chapter_id: 'ch-5',
    front: 'What happens if shear tension is too tight?',
    back: 'The blades do not move freely. This causes hand fatigue, premature wear on the pivot screw, and can damage the blade edges over time.',
    category: 'Shears & Scissors',
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-5-014',
    chapter_id: 'ch-5',
    front: 'What is an offset handle and why is it preferred?',
    back: 'The thumb hole is set back from the finger hole. This is the most ergonomic design, reducing wrist strain and repetitive strain injury (RSI) risk. Preferred by professionals.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-5-015',
    chapter_id: 'ch-5',
    front: 'What is the purpose of thinning/texturizing shears?',
    back: 'One blade has teeth (20-40 count) while the other is solid. They remove bulk and create texture WITHOUT changing the overall length of the hair. More teeth = softer texture.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-5-016',
    chapter_id: 'ch-5',
    front: 'What is the difference between thinning shears and blending shears?',
    back: 'Thinning shears have MORE teeth (20-40) for removing bulk and creating texture. Blending shears have FEWER, WIDER teeth designed to blend lines between clipper and shear work.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-5-017',
    chapter_id: 'ch-5',
    front: 'Why should left-handed barbers use left-handed shears?',
    back: 'Left-handed shears have reversed blades. Using right-handed shears in the left hand crushes the cutting edge and ruins the blade. The shear is designed for the natural cutting motion of each hand.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-5-018',
    chapter_id: 'ch-5',
    front: 'What is shear palming and why does it matter?',
    back: 'Palming is transferring shears to your palm mid-cut to free your fingers for comb work. Open shears slightly, rest the still blade against your palm, secure with your thumb. Never set shears down mid-cut.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-5-019',
    chapter_id: 'ch-5',
    front: 'What is the daily shear maintenance protocol?',
    back: '1) Wipe blades clean after EVERY haircut. 2) Oil pivot point daily — 1 drop, open/close to distribute. 3) Check tension before each use. 4) Store in protective case. 5) Sharpen every 6-12 months. 6) Cut ONLY clean hair.',
    category: 'Shears & Scissors',
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-5-020',
    chapter_id: 'ch-5',
    front: 'What should you NEVER cut with professional shears?',
    back: 'NEVER cut paper, plastic, wire, or anything other than clean hair. These materials instantly damage the edge. A nick from dropping requires professional repair — do not attempt to fix it yourself.',
    category: 'Shears & Scissors',
    difficulty: 'easy',
    order_index: 20,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 3: CLIPPERS & TRIMMERS (10 cards)
  // ==========================================
  {
    id: 'fc-5-021',
    chapter_id: 'ch-5',
    front: 'What is the difference between clippers and trimmers?',
    back: 'Clippers are larger, more powerful, designed for bulk removal, fades, and tapers. Trimmers are smaller, precise tools for outlining, edging, beard lines, and detail work. They serve completely different purposes.',
    category: 'Clippers & Trimmers',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-5-022',
    chapter_id: 'ch-5',
    front: 'What are the three main clipper motor types?',
    back: '1) Magnetic/Pivot — fast blade speed, quieter, lighter, best for fine to medium hair. 2) Rotary — most powerful, handles ALL hair types, professional standard. 3) Cordless/Lithium — maximum mobility, consistent power until depleted.',
    category: 'Clippers & Trimmers',
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-5-023',
    chapter_id: 'ch-5',
    front: 'Which motor type is the professional standard for handling all hair types?',
    back: 'Rotary motor. It runs cooler, lasts longer, and has the power to cut through thick, coarse, and wet hair. Magnetic motors struggle with very thick or coarse hair.',
    category: 'Clippers & Trimmers',
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-5-024',
    chapter_id: 'ch-5',
    front: 'What is the difference between adjustable and fixed clipper blades?',
    back: 'Adjustable blades use a taper lever to change length from #000 to #1 without changing blades. Fixed blades are single-length and more powerful — you change length by swapping blades or using guards.',
    category: 'Clippers & Trimmers',
    difficulty: 'medium',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-5-025',
    chapter_id: 'ch-5',
    front: 'What is zero-gap on a trimmer and what is the risk?',
    back: 'Zero-gap means the trimmer blades are adjusted to cut extremely close. This creates razor-sharp lines but can cause razor burn and skin irritation if used improperly. Master the technique before using on clients.',
    category: 'Clippers & Trimmers',
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-5-026',
    chapter_id: 'ch-5',
    front: 'What is the proper clipper blade maintenance routine?',
    back: '1) Brush out hair debris after EVERY use. 2) Oil before EACH use — 3 drops (center, left, right). 3) Spray disinfectant between EVERY client. 4) Replace blades when they pull or snag hair. 5) Use coolant spray during heavy use.',
    category: 'Clippers & Trimmers',
    difficulty: 'medium',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-5-027',
    chapter_id: 'ch-5',
    front: 'Why should you start with the longest guard and work down?',
    back: 'You can always cut more hair off — you cannot put it back. Starting long prevents mistakes and allows gradual refinement. This is fundamental fade and taper technique.',
    category: 'Clippers & Trimmers',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-5-028',
    chapter_id: 'ch-5',
    front: 'What does it mean when clippers start pulling hair instead of cutting?',
    back: 'The blades are DULL. Dull blades pull hair, cause pain, create uneven cuts, and damage your reputation. Replace or sharpen immediately. Never continue with dull blades.',
    category: 'Clippers & Trimmers',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-5-029',
    chapter_id: 'ch-5',
    front: 'What is the T-blade design on trimmers used for?',
    back: 'The T-blade allows for extremely close, clean lines around necklines, beards, and hairlines. The extended blade shape reaches tight corners and creates sharp edge-ups and designs.',
    category: 'Clippers & Trimmers',
    difficulty: 'easy',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-5-030',
    chapter_id: 'ch-5',
    front: 'Why is lithium-ion battery technology preferred for cordless clippers?',
    back: 'Lithium-ion batteries provide consistent power until depleted — no gradual weakening like older NiCad batteries. They charge faster, last longer, and maintain full cutting power throughout the charge.',
    category: 'Clippers & Trimmers',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 4: STRAIGHT RAZORS (10 cards)
  // ==========================================
  {
    id: 'fc-5-031',
    chapter_id: 'ch-5',
    front: 'What is the difference between a traditional cut-throat razor and a shavette?',
    back: 'Traditional cut-throat has a permanent blade that requires honing and stropping. Shavette uses replaceable single-edge blades — no honing needed, more sanitary (new blade per client), lower maintenance.',
    category: 'Straight Razors',
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-5-032',
    chapter_id: 'ch-5',
    front: 'What is stropping and how often should it be done?',
    back: 'Stropping polishes and aligns the razor edge on leather. It does NOT remove metal. Done BEFORE every shave — 20-30 passes on canvas side, then 20-30 on leather side. Maintains edge between honings.',
    category: 'Straight Razors',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-5-033',
    chapter_id: 'ch-5',
    front: 'What is honing and how often should it be done?',
    back: 'Honing sharpens the blade by removing metal with whetstones (1000 -> 4000 -> 8000 grit). Done every 2-3 months depending on use. Many barbers send blades out for professional honing.',
    category: 'Straight Razors',
    difficulty: 'medium',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-5-034',
    chapter_id: 'ch-5',
    front: 'What are the four straight razor grips and their primary uses?',
    back: '1) Freehand — general face shaving, cheeks, broad areas. 2) Backhand — broader areas, more leverage for coarse beard. 3) Reverse freehand — upper lip and chin (precision areas). 4) Reverse backhand — SIDES OF NECK ONLY.',
    category: 'Straight Razors',
    difficulty: 'hard',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-5-035',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: Which razor grip is used for the upper lip and chin?',
    back: 'Reverse freehand. Hand turned toward you, edge facing up, semi-curved strokes toward you. NEVER use reverse backhand on the face — it is restricted to sides of neck only.',
    category: 'Straight Razors',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-5-036',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: Which razor grip is RESTRICTED to sides of neck only?',
    back: 'Reverse backhand. Palm up, elbow down, downward gliding strokes. Using this grip on the face is a critical safety error that will fail the practical exam and risks serious injury.',
    category: 'Straight Razors',
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-5-037',
    chapter_id: 'ch-5',
    front: 'What is the difference between hollow-ground and wedge grind razors?',
    back: 'Hollow-ground has a concave profile that creates a "singing" edge — detects resistance during honing, preferred for fine beards and precision. Wedge grind has a sharp angle that powers through coarse, thick beards.',
    category: 'Straight Razors',
    difficulty: 'hard',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-5-038',
    chapter_id: 'ch-5',
    front: 'What are the five critical straight razor safety rules?',
    back: '1) Stretch skin taut before every stroke. 2) Use minimal pressure — let the razor weight do the work. 3) Shave WITH the grain first. 4) Never pass razor hand-to-hand. 5) Dispose used blades in a sharps container.',
    category: 'Straight Razors',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-5-039',
    chapter_id: 'ch-5',
    front: 'What should you do if you drop a straight razor?',
    back: 'STEP BACK and let it fall. NEVER attempt to catch a falling razor. A reflexive grab can cause a severe cut. Let it fall, then pick it up carefully and inspect for damage.',
    category: 'Straight Razors',
    difficulty: 'easy',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-5-040',
    chapter_id: 'ch-5',
    front: 'What is a crocus finish on a razor?',
    back: 'The finest polish on razor steel — a mirror-like smoothness that indicates superior edge retention. A crocus-finished blade is the mark of master craftsmanship and premium quality.',
    category: 'Straight Razors',
    difficulty: 'hard',
    order_index: 40,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 5: THERMAL TOOLS (8 cards)
  // ==========================================
  {
    id: 'fc-5-041',
    chapter_id: 'ch-5',
    front: 'What is a Marcel iron and why is it the professional standard?',
    back: 'A manual thermal iron with a rotating handle for precise temperature and winding control. No spring — the barber controls clamp pressure and rotation. Provides infinite control for professional curls and waves.',
    category: 'Thermal Tools',
    difficulty: 'medium',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-5-042',
    chapter_id: 'ch-5',
    front: 'What is the tissue test for thermal tools?',
    back: 'Drag the heated tool across tissue paper before client contact. A clean pass means the tool is ready. Scorching or burning means it is too hot — let it cool and retest.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-5-043',
    chapter_id: 'ch-5',
    front: 'Why should you NEVER use a metal pressing comb directly on the scalp?',
    back: 'Metal on scalp causes serious burns. Always maintain safe distance from skin. The pressing comb is designed to straighten hair sections, not touch the scalp directly.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-5-044',
    chapter_id: 'ch-5',
    front: 'What are the three main blowdryer nozzle types and their uses?',
    back: '1) Concentrator — precision airflow for straightening and detailing. 2) Diffuser — disperses air for textured and curly hair to reduce frizz. 3) Pick — lifts roots and adds volume.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-5-045',
    chapter_id: 'ch-5',
    front: 'Why must you keep thermal tools moving during use?',
    back: 'Stationary heat burns hair and scalp. Keep the tool in constant motion to distribute heat evenly. A burn from a thermal tool can end your career.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-5-046',
    chapter_id: 'ch-5',
    front: 'Is heat protectant mandatory before using thermal tools?',
    back: 'YES. Heat protectant is mandatory — no exceptions. It creates a barrier between the hair and thermal tool, preventing damage, breakage, and moisture loss. Apply to EVERY client before thermal contact.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-5-047',
    chapter_id: 'ch-5',
    front: 'What blowdryer heat setting should you use for fine or damaged hair?',
    back: 'Cool or low heat. High heat damages fine and compromised hair. Use high for coarse/thick, medium for normal, and cool for fine/damaged hair types.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-5-048',
    chapter_id: 'ch-5',
    front: 'Why should you never use a blowdryer near water?',
    back: 'Electrocution risk. Water and electricity are a deadly combination. Keep blowdryers away from sinks, wet floors, and damp hands. This is basic electrical safety.',
    category: 'Thermal Tools',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 6: STATION & SAFETY (8 cards)
  // ==========================================
  {
    id: 'fc-5-049',
    chapter_id: 'ch-5',
    front: 'What temperature should towels be washed at to meet sanitation standards?',
    back: '160°F+ (71°C+). Hot water washing kills bacteria and pathogens. Towels must also be completely dry before use and stored in a closed cabinet. Damp towels breed bacteria.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-5-050',
    chapter_id: 'ch-5',
    front: 'What is the purpose of a neck strip?',
    back: 'A neck strip is a barrier placed around the client\'s neck before the cape. It prevents hair from touching the skin and clothing. One client, one strip — dispose after every service.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 50,
    is_active: true,
  },
  {
    id: 'fc-5-051',
    chapter_id: 'ch-5',
    front: 'What temperature should a hot towel cabinet maintain?',
    back: '160°F+ (71°C+). This temperature ensures towels are hot enough to soften beard hair and open pores for shaves. Always test on your wrist before applying to the client.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-5-052',
    chapter_id: 'ch-5',
    front: 'What is styptic powder or pencil used for?',
    back: 'Stops bleeding from minor nicks and cuts instantly. Every barber station must have styptic available. Apply directly to the small wound — it contracts blood vessels and seals the cut.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-5-053',
    chapter_id: 'ch-5',
    front: 'What type of disinfectant is required for barbering tools?',
    back: 'EPA-registered hospital-grade disinfectant. Must be proven effective against bacteria, viruses, AND fungi. Check the EPA registration number on the label. Household bleach is NOT sufficient.',
    category: 'Station & Safety',
    difficulty: 'medium',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-5-054',
    chapter_id: 'ch-5',
    front: 'How long is the minimum contact time for disinfectant immersion?',
    back: '10 minutes. At 5 minutes you kill roughly 50% of pathogens. At 10 minutes you kill 99.9%. That 5-minute difference is the difference between safety and an outbreak. SET A TIMER.',
    category: 'Station & Safety',
    difficulty: 'medium',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-5-055',
    chapter_id: 'ch-5',
    front: 'What should you do if a tool falls on the floor during service?',
    back: 'Replace with a clean tool or STOP and fully disinfect before continuing. Tools that touch the floor are contaminated. Never wipe on your apron and reuse. Never use on the next client without full disinfection.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-5-056',
    chapter_id: 'ch-5',
    front: 'What is the proper way to store clean, disinfected tools?',
    back: 'Store in a CLEAN, COVERED container labeled "DISINFECTED." Never store clean tools in open containers where they can be recontaminated. Keep clean and dirty tools physically separated at all times.',
    category: 'Station & Safety',
    difficulty: 'easy',
    order_index: 56,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 7: BOARD EXAM ALERTS (8 cards)
  // ==========================================
  {
    id: 'fc-5-057',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: List clipper guard sizes and their inch equivalents.',
    back: '#0 = 1/16in (1.5mm), #1 = 1/8in (3mm), #2 = 1/4in (6mm), #3 = 3/8in (10mm), #4 = 1/2in (13mm), #5-8 = 5/8in to 1in. Memorize these — they appear on every exam.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-5-058',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: What are the three shear handle types and which reduces RSI risk?',
    back: '1) Opposing — traditional straight design. 2) Offset — thumb hole set back, most ergonomic. 3) Crane — extreme offset with downward angle, maximum ergonomic benefit. Offset and crane reduce repetitive strain injury (RSI) risk.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-5-059',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: What is the difference between forged and cast shears?',
    back: 'Forged shears are denser, stronger, and more durable than cast shears. Look for the weld line — it proves forged construction. Forged shears cost more but last significantly longer.',
    category: 'Board Exam Alert',
    difficulty: 'hard',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-5-060',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: What are the three types of shears and their primary uses?',
    back: '1) Straight shears — standard cutting, 90% of haircutting work. 2) Thinning/texturizing shears — remove bulk without changing length. 3) Blending shears — blend lines between clipper and shear work.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-5-061',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: What are the four steps of clipper blade maintenance?',
    back: '1) CLEAN after every use — brush out hair debris. 2) OIL before each use — 3 drops across blade. 3) SPRAY disinfectant between every client. 4) REPLACE when dull — pulling or snagging means replacement time.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-5-062',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: What is the proper straight razor shaving sequence?',
    back: '1) Stretch skin taut. 2) Use minimal pressure — let razor weight do the work. 3) Shave WITH the grain first. 4) Then across the grain. 5) Then against the grain ONLY if needed and skin tolerates it.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 62,
    is_active: true,
  },
  {
    id: 'fc-5-063',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: What are the three motor types and their best uses?',
    back: 'Magnetic/Pivot — quiet, light, best for fine to medium hair. Rotary — powerful, handles all hair types, professional standard. Cordless/Lithium — mobile, consistent power, most popular modern choice.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-5-064',
    chapter_id: 'ch-5',
    front: 'BOARD EXAM ALERT: What are the five essential supplies every barber station must have?',
    back: '1) Neck strips — barrier protection. 2) EPA-registered disinfectant — tool sanitation. 3) Barbicide jar — immersion disinfection. 4) Styptic powder/pencil — stops bleeding. 5) Sharps container — safe blade disposal.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 64,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 8: SCENARIO CARDS (6 cards)
  // ==========================================
  {
    id: 'fc-5-065',
    chapter_id: 'ch-5',
    front: 'SCENARIO: Your clippers start pulling hair mid-fade. The client winces. What is your FIRST action?',
    back: 'STOP immediately. Apologize professionally. Switch to backup clippers to finish the service. Replace the dull blade before your next client. NEVER continue with dull blades — pulling hair causes pain and damages your reputation.',
    category: 'Scenario Card',
    difficulty: 'medium',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-5-066',
    chapter_id: 'ch-5',
    front: 'SCENARIO: A client wants a skin fade with sharp lines and a beard trim. Which tools are REQUIRED?',
    back: 'Clippers with guards (for the fade), trimmer (for sharp lineup), straight razor (for final edge and neck shave), and comb (for sectioning and clipper-over-comb work). Shears alone cannot create a skin fade.',
    category: 'Scenario Card',
    difficulty: 'medium',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-5-067',
    chapter_id: 'ch-5',
    front: 'SCENARIO: Your Marcel iron starts smoking slightly while prepping for a press-and-curl. What do you do?',
    back: 'Test on tissue paper immediately. Adjust temperature down if needed. Explain to the client briefly and professionally. NEVER use a smoking iron — it is overheating and risks burning hair and scalp.',
    category: 'Scenario Card',
    difficulty: 'medium',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-5-068',
    chapter_id: 'ch-5',
    front: 'SCENARIO: The practical exam examiner asks you to demonstrate the proper razor grip for the upper lip. Which grip do you use?',
    back: 'Reverse freehand. Hand turned toward you, edge facing up, semi-curved strokes toward you. Freehand is for general face shaving. Reverse backhand is for NECK ONLY — using it on the face fails the exam.',
    category: 'Scenario Card',
    difficulty: 'hard',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-5-069',
    chapter_id: 'ch-5',
    front: 'SCENARIO: A tool falls on the floor during a haircut. Can you wipe it on your apron and continue?',
    back: 'NO. Tools that touch the floor are contaminated. Replace with a clean tool or stop and fully disinfect before continuing. Wiping on an apron does NOT disinfect. Using contaminated tools spreads infection.',
    category: 'Scenario Card',
    difficulty: 'easy',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-5-070',
    chapter_id: 'ch-5',
    front: 'SCENARIO: You are setting up your station for the day. What is the ONE maintenance task you must do before using your shears on the first client?',
    back: 'Check the tension. Hold tips up, lift one handle. Blades should open partially. This 5-second test prevents bad cuts and extends shear life. Do it every morning before your first client.',
    category: 'Scenario Card',
    difficulty: 'easy',
    order_index: 70,
    is_active: true,
  },
]

// Stats
export const chapter5FlashcardStats = {
  total: chapter5PremiumFlashcards.length,
  categories: [...new Set(chapter5PremiumFlashcards.map((f) => f.category))],
  byDifficulty: {
    easy: chapter5PremiumFlashcards.filter((f) => f.difficulty === 'easy').length,
    medium: chapter5PremiumFlashcards.filter((f) => f.difficulty === 'medium').length,
    hard: chapter5PremiumFlashcards.filter((f) => f.difficulty === 'hard').length,
  },
}

console.log(`Chapter 5 Premium Flashcards: ${chapter5FlashcardStats.total} cards created`)
console.log(`Categories: ${chapter5FlashcardStats.categories.join(', ')}`)
console.log(`Difficulty: ${chapter5FlashcardStats.byDifficulty.easy} easy, ${chapter5FlashcardStats.byDifficulty.medium} medium, ${chapter5FlashcardStats.byDifficulty.hard} hard`)
