// Chapter 5: Implements, Tools, and Equipment — PREMIUM MCQ QUIZ
// 50 questions generated STRICTLY from Chapter 5 flashcards
// Randomized question selection and answer order per attempt
// The Barber's Forge Certification Exam

import { QuizQuestion } from '@/types'

const strategyExplanation = (keyword: string, eliminate: string, logic: string, best: string) =>
  `Read carefully. Identify the keyword: ${keyword}. Eliminate wrong answers: ${eliminate}. Apply safety/procedure logic: ${logic}. Make the best remaining choice: ${best}.`

// ───────────────────────────────────────────────
// CHAPTER 5: FULL QUESTION BANK (50 questions)
// Generated from chapter-5-premium-flashcards.ts
// NATURAL answer distribution (NOT forced balanced)
// ───────────────────────────────────────────────
export const chapter5PremiumQuizQuestions: QuizQuestion[] = [
  // COMBS & BRUSHES (6 questions)
  {
    id: 'qq-5-001',
    quiz_id: 'quiz-5',
    question: "A barber needs a comb material that is antistatic and resistant to heat and many chemicals. Which material BEST matches the Chapter 5 source?",
    answer_a: "Hard rubber",
    answer_b: "Carbon",
    answer_c: "Graphite",
    answer_d: "Metal",
    correct_answer: 'b',
    explanation: strategyExplanation("material performance", "hard rubber is flexible but can deteriorate in disinfectant; graphite is less rigid; metal retains heat and may corrode", "match the service need to the source material characteristics", "carbon"),
    difficulty: 'hard',
    order_index: 1,
  },
  {
    id: 'qq-5-002',
    quiz_id: 'quiz-5',
    question: 'What is the standard length of an all-purpose cutting comb?',
    answer_a: '5-6 inches',
    answer_b: '7-8 inches',
    answer_c: '9-10 inches',
    answer_d: '3-4 inches',
    correct_answer: 'b',
    explanation: 'All-purpose cutting combs are 7-8 inches with fine teeth on one end and medium teeth on the other for versatility.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-5-003',
    quiz_id: 'quiz-5',
    question: 'What is the primary purpose of a taper comb?',
    answer_a: 'Detangling wet hair after washing',
    answer_b: 'Blow-drying and styling long hair',
    answer_c: 'Clipper-over-comb and scissor-over-comb tapering with firm grip',
    answer_d: 'Sectioning hair for color applications',
    correct_answer: 'c',
    explanation: 'Taper combs are shorter, sturdier, with teeth spaced to grip hair firmly for clipper-over-comb and scissor-over-comb tapering.',
    difficulty: 'medium',
    order_index: 3,
  },
  {
    id: 'qq-5-004',
    quiz_id: 'quiz-5',
    question: "A barber wants to increase clipper cutting length without changing the bare blade. Which choice BEST matches the source?",
    answer_a: "Use an attachment comb or guard",
    answer_b: "Adjust an outliner blade flush",
    answer_c: "Switch to a razor shaper",
    answer_d: "Increase motor speed",
    correct_answer: 'a',
    explanation: strategyExplanation("increase cutting length", "flush blade adjustment is a safety concern; razor shapers texturize hair; motor speed does not define the cutting length", "guards extend length beyond the bare blade and are not infection-control devices", "use an attachment comb or guard"),
    difficulty: 'hard',
    order_index: 4,
  },
  {
    id: 'qq-5-005',
    quiz_id: 'quiz-5',
    question: 'Which brush type creates volume and curl during blow-drying?',
    answer_a: 'Paddle brush',
    answer_b: 'Vent brush',
    answer_c: 'Round brush',
    answer_d: 'Pick comb',
    correct_answer: 'c',
    explanation: 'Round brush creates volume and curl. Barrel size matters — larger barrels create bigger curls. Paddle brushes smooth; vent brushes speed drying.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-5-006',
    quiz_id: 'quiz-5',
    question: 'When should you replace a comb?',
    answer_a: 'Only when it breaks completely in half',
    answer_b: 'When teeth become worn, broken, or missing',
    answer_c: 'Every 6 months regardless of condition',
    answer_d: 'Only when the color fades',
    correct_answer: 'b',
    explanation: 'Replace combs with worn, broken, or missing teeth. Damaged teeth snag hair, damage the cuticle, and create uneven sections.',
    difficulty: 'easy',
    order_index: 6,
  },

  // SHEARS & SCISSORS (8 questions)
  {
    id: 'qq-5-007',
    quiz_id: 'quiz-5',
    question: "A barber wants the shear edge that glides smoothly and is suited to slide cutting. Which edge is the BEST choice?",
    answer_a: "Convex edge",
    answer_b: "Beveled edge",
    answer_c: "Wedge grind",
    answer_d: "Crocus finish",
    correct_answer: 'a',
    explanation: strategyExplanation("slide cutting", "wedge grind and crocus finish describe straight razors; beveled edges grip hair and are not the source choice for slide cutting", "match the shear-edge design to the cutting action", "convex edge"),
    difficulty: 'hard',
    order_index: 7,
  },
  {
    id: 'qq-5-008',
    quiz_id: 'quiz-5',
    question: "According to the Chapter 5 source, which shear-size statement is MOST accurate?",
    answer_a: "Most barbers prefer about 6½–7½ inches, but fit and service still matter",
    answer_b: "5½–6 inches is always the universal professional standard",
    answer_c: "Only 4-inch shears should be used for barbering",
    answer_d: "Shear size has no relationship to fit or technique",
    correct_answer: 'a',
    explanation: strategyExplanation("source preference versus universal rule", "the distractors turn a preference into an absolute or deny fit and technique", "use source wording while avoiding manufacturer-independent absolutes", "6½–7½ inches is the source preference, with fit and service still considered"),
    difficulty: 'hard',
    order_index: 8,
  },
  {
    id: 'qq-5-009',
    quiz_id: 'quiz-5',
    question: "A shear drops far more than intended during a tension check. Which interpretation is BEST?",
    answer_a: "The tension is likely too loose and should be adjusted",
    answer_b: "The shear must be forged",
    answer_c: "The finger tang is too long",
    answer_d: "The beveled edge needs stropping",
    correct_answer: 'a',
    explanation: strategyExplanation("tension check", "forging, tang length, and stropping do not explain blade pressure", "the tension screw controls pressure between the blades; the source teaches a controlled partial-drop check", "the tension is too loose"),
    difficulty: 'hard',
    order_index: 9,
  },
  {
    id: 'qq-5-010',
    quiz_id: 'quiz-5',
    question: "Which shear part directly adjusts pressure between the moving and still blades?",
    answer_a: "Tension/pivot screw",
    answer_b: "Finger rest/tang",
    answer_c: "Bumper",
    answer_d: "Shank",
    correct_answer: 'a',
    explanation: strategyExplanation("adjusts blade pressure", "the tang supports the little finger, the bumper limits handle closure, and the shank connects blade to handle", "identify the part whose job is to control blade pressure", "tension/pivot screw"),
    difficulty: 'hard',
    order_index: 10,
  },
  {
    id: 'qq-5-011',
    quiz_id: 'quiz-5',
    question: "Which handle design BEST matches the source description of reducing hand and wrist stress through a greater offset?",
    answer_a: "Crane",
    answer_b: "Opposing",
    answer_c: "German",
    answer_d: "French",
    correct_answer: 'a',
    explanation: strategyExplanation("greater offset and reduced stress", "German and French describe shear styles, not handle designs; opposing is the traditional layout", "match the ergonomic handle geometry to the source description", "crane"),
    difficulty: 'hard',
    order_index: 11,
  },
  {
    id: 'qq-5-012',
    quiz_id: 'quiz-5',
    question: 'What is the primary purpose of thinning/texturizing shears?',
    answer_a: 'To create blunt, straight lines in the haircut',
    answer_b: 'To remove bulk and create texture without changing overall length',
    answer_c: 'To shave the neckline clean',
    answer_d: 'To disinfect tools between clients',
    correct_answer: 'b',
    explanation: 'Texturizing/thinning shears use toothed blade designs to remove a portion of hair and create texture or reduce bulk. Tooth count and cutting ratio vary by model.',
    difficulty: 'medium',
    order_index: 12,
  },
  {
    id: 'qq-5-013',
    quiz_id: 'quiz-5',
    question: "Why are left-handed shears assembled differently from right-handed shears?",
    answer_a: "The blade orientation is reversed to match the intended hand and cutting mechanics",
    answer_b: "Left-handed shears use a different metal",
    answer_c: "State boards require a different blade length",
    answer_d: "They are designed only for thinning",
    correct_answer: 'a',
    explanation: strategyExplanation("reversed assembly", "metal type, blade length, and thinning purpose do not define handedness", "match blade orientation to the user's hand and shear mechanics", "reversed blade assembly supports left-handed cutting"),
    difficulty: 'hard',
    order_index: 13,
  },
  {
    id: 'qq-5-014',
    quiz_id: 'quiz-5',
    question: 'What should you NEVER cut with professional shears?',
    answer_a: 'Wet hair',
    answer_b: 'Paper, plastic, wire, or anything other than clean hair',
    answer_c: 'Synthetic hair extensions',
    answer_d: 'Curly hair',
    correct_answer: 'b',
    explanation: 'NEVER cut paper, plastic, wire, or anything other than clean hair. Cutting materials the shear was not designed for can dull, nick, or otherwise damage the edge.',
    difficulty: 'easy',
    order_index: 14,
  },

  // CLIPPERS & TRIMMERS (7 questions)
  {
    id: 'qq-5-015',
    quiz_id: 'quiz-5',
    question: 'What is the main difference between clippers and trimmers?',
    answer_a: 'Clippers are for bulk removal and fades; trimmers are for precision outlining and detail',
    answer_b: 'Clippers are battery-powered; trimmers are corded',
    answer_c: 'Clippers are more expensive; trimmers are disposable',
    answer_d: 'There is no difference — they are interchangeable',
    correct_answer: 'a',
    explanation: 'Clippers are larger, more powerful, for bulk removal, fades, and tapers. Trimmers are smaller, precise tools for outlining, edging, and detail work.',
    difficulty: 'easy',
    order_index: 15,
  },
  {
    id: 'qq-5-016',
    quiz_id: 'quiz-5',
    question: "Which set names the three clipper motor types identified in the Chapter 5 source?",
    answer_a: "Rotary, pivot, magnetic",
    answer_b: "Rotary, hydraulic, lithium",
    answer_c: "Pivot, ceramic, detachable",
    answer_d: "Magnetic, carbon, adjustable",
    correct_answer: 'a',
    explanation: strategyExplanation("motor types", "ceramic/carbon are blade materials; detachable/adjustable are clipper systems; lithium describes a battery chemistry", "separate motor categories from blade, power, and clipper-type terms", "rotary, pivot, and magnetic"),
    difficulty: 'hard',
    order_index: 16,
  },
  {
    id: 'qq-5-017',
    quiz_id: 'quiz-5',
    question: "A barber wants an outliner to cut closer. Which action is SAFEST according to the source?",
    answer_a: "Keep safe blade alignment and follow manufacturer guidance rather than setting the blades flush",
    answer_b: "Set the moving blade flush with the still blade",
    answer_c: "Increase hand pressure at the hairline",
    answer_d: "Remove the still blade",
    correct_answer: 'a',
    explanation: strategyExplanation("SAFEST outliner adjustment", "flush alignment, excess pressure, and removing a blade increase risk or defeat the tool design", "the source specifically cautions against flush outliner adjustment and teaches light pressure", "maintain safe alignment and follow manufacturer guidance"),
    difficulty: 'hard',
    order_index: 17,
  },
  {
    id: 'qq-5-018',
    quiz_id: 'quiz-5',
    question: "Clippers begin pulling and snagging during a service. What should the barber do FIRST?",
    answer_a: "Stop and inspect cleanliness, lubrication, alignment, and blade condition",
    answer_b: "Assume the client has unusually coarse hair and continue",
    answer_c: "Immediately replace the motor",
    answer_d: "Press harder so the blade catches the hair",
    correct_answer: 'a',
    explanation: strategyExplanation("FIRST response to pulling", "continuing, replacing the motor without diagnosis, and adding pressure ignore basic troubleshooting", "stop the irritating action and check the source-supported maintenance factors before resuming", "inspect cleanliness, lubrication, alignment, and condition"),
    difficulty: 'hard',
    order_index: 18,
  },
  {
    id: 'qq-5-019',
    quiz_id: 'quiz-5',
    question: 'What is the T-blade design on trimmers used for?',
    answer_a: 'Cutting bulk hair on the top of the head',
    answer_b: 'Extremely close, clean lines around necklines, beards, and hairlines',
    answer_c: 'Shaving the entire head bald',
    answer_d: 'Applying hair products evenly',
    correct_answer: 'b',
    explanation: 'T-blade allows for extremely close, clean lines around necklines, beards, and hairlines. The extended blade reaches tight corners.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-5-020',
    quiz_id: 'quiz-5',
    question: "Which statement BEST reflects the source's treatment of cordless clippers?",
    answer_a: "They offer portability and convenience, but some may have less power than corded models",
    answer_b: "Lithium-ion models are always stronger than corded clippers",
    answer_c: "Cordless models never lose cutting power",
    answer_d: "Battery chemistry alone determines professional quality",
    correct_answer: 'a',
    explanation: strategyExplanation("source treatment of cordless clippers", "the distractors turn convenience into unsupported battery or power absolutes", "judge the tool by service needs and manufacturer specifications rather than battery marketing", "portable and convenient, with possible power tradeoffs"),
    difficulty: 'hard',
    order_index: 20,
  },
  {
    id: 'qq-5-021',
    quiz_id: 'quiz-5',
    question: 'Why should you start with the longest guard and work down when fading?',
    answer_a: 'It is faster than starting short',
    answer_b: 'Long guards are sharper than short guards',
    answer_c: 'You can always cut more off — you cannot put it back',
    answer_d: 'State boards require this method',
    correct_answer: 'c',
    explanation: 'Starting long prevents mistakes and allows gradual refinement. You can always cut more off — you cannot put it back.',
    difficulty: 'easy',
    order_index: 21,
  },

  // STRAIGHT RAZORS (7 questions)
  {
    id: 'qq-5-022',
    quiz_id: 'quiz-5',
    question: "Which comparison between straight-razor types is MOST accurate?",
    answer_a: "Changeable-blade razors use replaceable blades; conventional straight razors require honing and stropping",
    answer_b: "Conventional razors use disposable guards; changeable-blade razors require honing",
    answer_c: "Both types require the same honing schedule",
    answer_d: "Razor shapers are the same as conventional shaving razors",
    correct_answer: 'a',
    explanation: strategyExplanation("razor type distinction", "the distractors reverse the systems or confuse hair razors with shaving razors", "identify whether the edge is replaced or maintained as a permanent blade", "changeable-blade versus conventional straight razor"),
    difficulty: 'hard',
    order_index: 22,
  },
  {
    id: 'qq-5-023',
    quiz_id: 'quiz-5',
    question: 'What is stropping and how often should it be done?',
    answer_a: 'Sharpening the blade with a stone — done monthly',
    answer_b: 'Refining and aligning the edge on a strop between honings',
    answer_c: 'Cleaning the blade with alcohol — done after every client',
    answer_d: 'Replacing the blade — done weekly',
    correct_answer: 'b',
    explanation: 'Stropping refines and aligns a traditional straight-razor edge between honings. Technique and frequency depend on the razor, strop, edge condition, and manufacturer or training guidance.',
    difficulty: 'medium',
    order_index: 23,
  },
  {
    id: 'qq-5-024',
    quiz_id: 'quiz-5',
    question: "When holding a straight razor for shaving, which principle BEST matches the source?",
    answer_a: "Control the shank/tang area with the taught shaving grip and deliberate blade control",
    answer_b: "Hold only the cutting edge for maximum precision",
    answer_c: "Use the same hold as stropping regardless of task",
    answer_d: "Grip the handle with both hands",
    correct_answer: 'a',
    explanation: strategyExplanation("holding for shaving", "the edge must never be grasped; stropping uses a different task-based hold; two-hand gripping is not the source procedure", "the source changes the hold according to the service", "use the taught shaving hold at the shank/tang area"),
    difficulty: 'hard',
    order_index: 24,
  },
  {
    id: 'qq-5-025',
    quiz_id: 'quiz-5',
    question: "Why is the straight razor controlled from the shank during honing or stropping?",
    answer_a: "So the blade can lie flat and travel correctly on the hone or strop",
    answer_b: "So the cutting edge can be pinched safely",
    answer_c: "So the handle can remain closed",
    answer_d: "So only one side of the blade is worked",
    correct_answer: 'a',
    explanation: strategyExplanation("honing or stropping hold", "pinching the edge is unsafe; closing the handle or working one side defeats the procedure", "task-based holding keeps the blade flat and allows balanced work on both sides", "control the shank so the blade lies flat"),
    difficulty: 'hard',
    order_index: 25,
  },
  {
    id: 'qq-5-026',
    quiz_id: 'quiz-5',
    question: 'What is the difference between hollow-ground and wedge grind razors?',
    answer_a: 'Hollow-ground has a concave profile for precision; wedge has a sharp angle for power',
    answer_b: 'Hollow-ground is for coarse beards; wedge is for fine beards',
    answer_c: 'Hollow-ground is heavier; wedge is lighter',
    answer_d: 'They are the same grind with different names',
    correct_answer: 'a',
    explanation: 'Hollow-ground: concave profile, "singing" edge, preferred for fine beards and precision. Wedge: sharp angle, powers through coarse, thick beards.',
    difficulty: 'hard',
    order_index: 26,
  },
  {
    id: 'qq-5-027',
    quiz_id: 'quiz-5',
    question: "Which list contains only principal straight-razor parts from the Chapter 5 source?",
    answer_a: "Head, back, shoulder, tang, point, edge, heel, shank, pivot",
    answer_b: "Guard, taper lever, motor, heel, cord",
    answer_c: "Finger rest, bumper, shank, tension screw, thumb grip",
    answer_d: "Barrel, clamp, swivel, nozzle, diffuser",
    correct_answer: 'a',
    explanation: strategyExplanation("straight-razor parts", "the other lists describe clippers, shears, or thermal tools", "match the named parts to the razor anatomy taught in LO10", "head/back/shoulder/tang/point/edge/heel/shank/pivot"),
    difficulty: 'hard',
    order_index: 27,
  },
  {
    id: 'qq-5-028',
    quiz_id: 'quiz-5',
    question: 'What does a crocus finish describe on a traditional straight razor?',
    answer_a: 'A highly polished surface finish; the finish alone does not prove edge retention or overall blade quality',
    answer_b: 'A type of blade guard',
    answer_c: 'A safety feature that prevents cuts',
    answer_d: 'A type of razor handle material',
    correct_answer: 'a',
    explanation: 'A crocus finish describes a highly polished razor surface. Edge retention and overall quality depend on additional factors such as steel, heat treatment, geometry, edge condition, and maintenance.',
    difficulty: 'hard',
    order_index: 28,
  },

  // THERMAL TOOLS (6 questions)
  {
    id: 'qq-5-029',
    quiz_id: 'quiz-5',
    question: 'What is a Marcel iron and how is it controlled?',
    answer_a: 'An automatic curling iron with a spring-loaded clamp',
    answer_b: 'A heated comb for textured hair',
    answer_c: 'A type of hair straightener',
    answer_d: 'A manual thermal iron with rotating handle for precise control',
    correct_answer: 'd',
    explanation: 'Marcel iron has a rotating handle for precise temperature and winding control. No spring — the barber controls clamp pressure and rotation.',
    difficulty: 'medium',
    order_index: 29,
  },
  {
    id: 'qq-5-030',
    quiz_id: 'quiz-5',
    question: 'What is the tissue test for thermal tools?',
    answer_a: 'Wiping the tool with a tissue to clean it',
    answer_b: 'Wrapping tissue around the client\'s neck',
    answer_c: 'Dragging the heated tool across tissue to check temperature',
    answer_d: 'Testing the tissue for moisture content',
    correct_answer: 'c',
    explanation: 'Drag the heated tool across tissue paper before client contact. Clean pass = ready. Scorching = too hot. Let cool and retest.',
    difficulty: 'easy',
    order_index: 30,
  },
  {
    id: 'qq-5-031',
    quiz_id: 'quiz-5',
    question: 'Why should you NEVER use a metal pressing comb directly on the scalp?',
    answer_a: 'It will tangle in the hair',
    answer_b: 'Metal on scalp causes serious burns',
    answer_c: 'It damages the comb',
    answer_d: 'It is against manufacturer warranty',
    correct_answer: 'b',
    explanation: 'Metal on scalp causes serious burns. Always maintain safe distance from skin. Pressing combs straighten hair sections, not touch scalp.',
    difficulty: 'easy',
    order_index: 31,
  },
  {
    id: 'qq-5-032',
    quiz_id: 'quiz-5',
    question: 'What blowdryer nozzle type disperses air for textured and curly hair to reduce frizz?',
    answer_a: 'Diffuser',
    answer_b: 'Concentrator',
    answer_c: 'Pick',
    answer_d: 'Vent',
    correct_answer: 'a',
    explanation: 'Diffuser disperses air for textured and curly hair to reduce frizz. Concentrator = precision. Pick = lifts roots and adds volume.',
    difficulty: 'easy',
    order_index: 32,
  },
  {
    id: 'qq-5-033',
    quiz_id: 'quiz-5',
    question: 'What is the best approach to heat protection when using thermal tools?',
    answer_a: 'Use appropriate heat protection, safe temperature selection, and follow product and tool directions',
    answer_b: 'Heat protection matters only for fine hair',
    answer_c: 'Use the highest temperature so the service finishes faster',
    answer_d: 'Heat protection is never useful',
    correct_answer: 'a',
    explanation: 'Thermal-tool safety depends on the hair condition, service, temperature, product directions, and tool guidance. Use appropriate heat protection and avoid excessive heat exposure.',
    difficulty: 'easy',
    order_index: 33,
  },
  {
    id: 'qq-5-034',
    quiz_id: 'quiz-5',
    question: 'Why should you never use a blowdryer near water?',
    answer_a: 'Water makes the hair too heavy to dry',
    answer_b: 'Electrocution risk — water and electricity are deadly',
    answer_c: 'It voids the warranty',
    answer_d: 'Water damages the motor over time',
    correct_answer: 'b',
    explanation: 'Electrocution risk. Water and electricity are a deadly combination. Keep blowdryers away from sinks, wet floors, and damp hands.',
    difficulty: 'easy',
    order_index: 34,
  },

  // STATION & SAFETY (6 questions)
  {
    id: 'qq-5-035',
    quiz_id: 'quiz-5',
    question: "Which equipment-role pairing is MOST accurate?",
    answer_a: "Haircutting cape — protects the client during cutting; neck strip — barrier between cape and skin",
    answer_b: "Barber chair — disinfects implements; towel — powers clippers",
    answer_c: "Neck strip — sharpens razors; shampoo cape — adjusts shear tension",
    answer_d: "Towel — changes clipper length; cape — hones razors",
    correct_answer: 'a',
    explanation: strategyExplanation("equipment role", "the distractors assign tools functions they cannot perform", "match each item to its actual service-support function", "haircutting cape for protection and neck strip as a barrier"),
    difficulty: 'hard',
    order_index: 35,
  },
  {
    id: 'qq-5-036',
    quiz_id: 'quiz-5',
    question: 'What is the purpose of a neck strip?',
    answer_a: 'To hold the cape closed',
    answer_b: 'A barrier preventing hair from touching skin and clothing',
    answer_c: 'To measure hair length',
    answer_d: 'To apply styling products',
    correct_answer: 'b',
    explanation: 'Neck strip is a barrier placed around the neck before the cape. Prevents hair from touching skin and clothing. One client, one strip.',
    difficulty: 'easy',
    order_index: 36,
  },
  {
    id: 'qq-5-037',
    quiz_id: 'quiz-5',
    question: "Which sequence BEST reflects the source procedure for honing a conventional straight razor?",
    answer_a: "Use even diagonal strokes, work both sides equally, gradually lighten pressure, then perform the taught edge check",
    answer_b: "Use heavy pressure on one side until the edge feels rough",
    answer_c: "Roll the razor on its cutting edge after every stroke",
    answer_d: "Strop first, then grind only the heel",
    correct_answer: 'a',
    explanation: strategyExplanation("honing sequence", "one-sided heavy pressure and edge-rolling are incorrect; stropping is a different procedure", "honing uses controlled abrasive strokes on both sides with pressure reduced as the edge is refined", "even diagonal strokes, equal sides, lighter pressure, edge check"),
    difficulty: 'hard',
    order_index: 37,
  },
  {
    id: 'qq-5-038',
    quiz_id: 'quiz-5',
    question: "During stropping, how should the barber reverse the razor's direction?",
    answer_a: "Roll the razor on its back, then continue even diagonal strokes on the other side",
    answer_b: "Roll it over the cutting edge",
    answer_c: "Lift it and strike the strop vertically",
    answer_d: "Keep the same side against the strop for every pass",
    correct_answer: 'a',
    explanation: strategyExplanation("reverse direction during stropping", "rolling on the cutting edge risks damage; vertical strikes and one-sided work do not follow the source procedure", "the source distinguishes stropping by reversing on the razor back and working both sides evenly", "roll on the back"),
    difficulty: 'hard',
    order_index: 38,
  },
  {
    id: 'qq-5-039',
    quiz_id: 'quiz-5',
    question: "Which group consists of Chapter 5 equipment used directly to support shaving or comfort services?",
    answer_a: "Hot-towel cabinet, latherizer, electric massager",
    answer_b: "Tension screw, finger tang, bumper",
    answer_c: "Detachable blade, taper lever, guard",
    answer_d: "Hone, strop, shear case",
    correct_answer: 'a',
    explanation: strategyExplanation("equipment supporting service comfort/shaving", "the other sets are shear, clipper, or blade-maintenance components", "match equipment to its service role rather than its material or location", "hot-towel cabinet, latherizer, electric massager"),
    difficulty: 'hard',
    order_index: 39,
  },
  {
    id: 'qq-5-040',
    quiz_id: 'quiz-5',
    question: "Loose hair clippings remain on a client's neck after a haircut. Which removal method BEST matches the source?",
    answer_a: "Use a clean folded towel, disposable paper neck strip, or maintained vacuum method",
    answer_b: "Use an unclean traditional neck duster because it is faster",
    answer_c: "Brush them off with a used cape",
    answer_d: "Blow them away with compressed air",
    correct_answer: 'a',
    explanation: strategyExplanation("safe clipping removal", "used or unclean tools can recontaminate the client and compressed air is not the source method", "choose a clean, maintainable method the source specifically identifies", "folded towel, paper neck strip, or maintained vacuum"),
    difficulty: 'hard',
    order_index: 40,
  },

  // EXAM-RELEVANT REVIEW (6 questions)
  {
    id: 'qq-5-041',
    quiz_id: 'quiz-5',
    question: "Which statement about clipper blades and guards is MOST accurate?",
    answer_a: "Carbon-steel and ceramic are blade materials; 00000 is a very close blade size; guards extend cutting length",
    answer_b: "00000 is the longest guard and guards replace disinfection",
    answer_c: "Ceramic is a motor type and carbon steel is a battery type",
    answer_d: "Guards make outliner blades safe to set flush",
    correct_answer: 'a',
    explanation: strategyExplanation("blade material, size, and guard role", "the distractors mix blade, motor, battery, and sanitation concepts", "separate blade material, blade size, and cutting-length aids", "carbon-steel/ceramic materials, 00000 close size, guards extend length"),
    difficulty: 'hard',
    order_index: 41,
  },
  {
    id: 'qq-5-042',
    quiz_id: 'quiz-5',
    question: "Which comparison of shear handle designs is MOST accurate?",
    answer_a: "Opposing is traditional; offset changes thumb position; crane creates a greater offset to reduce hand/wrist stress",
    answer_b: "Opposing and crane are blade grinds",
    answer_c: "Offset means the shear has no thumb grip",
    answer_d: "Crane is another name for German-style shears",
    correct_answer: 'a',
    explanation: strategyExplanation("handle design", "blade grinds and shear styles are separate concepts; all professional handles still require controlled finger/thumb placement", "match the geometry to the source's handle categories", "opposing, offset, and crane have progressively different hand positioning"),
    difficulty: 'hard',
    order_index: 42,
  },
  {
    id: 'qq-5-043',
    quiz_id: 'quiz-5',
    question: "Which comparison between cast and forged shears BEST matches the Chapter 5 source?",
    answer_a: "Forged shears are compressed/hammered and described as denser and more durable; cast shears are described as more porous and less durable",
    answer_b: "Cast shears are always denser because they are poured",
    answer_c: "Forged and cast refer only to handle shape",
    answer_d: "Casting and forging are two names for blade sharpening",
    correct_answer: 'a',
    explanation: strategyExplanation("construction method", "handle shape and sharpening are different features; the source does not describe cast as denser", "use the source's construction comparison without turning one feature into a universal quality guarantee", "forged is denser/more durable in the source comparison"),
    difficulty: 'hard',
    order_index: 43,
  },
  {
    id: 'qq-5-044',
    quiz_id: 'quiz-5',
    question: "A barber wants to remove bulk without creating a blunt line. Which shear type is the BEST fit?",
    answer_a: "Thinning/blending shear with narrow teeth",
    answer_b: "Straight shear used as a razor",
    answer_c: "German-style shear because it has no tang",
    answer_d: "Crane-handle shear regardless of blade type",
    correct_answer: 'a',
    explanation: strategyExplanation("remove bulk without a blunt line", "handle style and tang style do not define the texturizing effect; straight shears are for standard cutting", "choose the toothed shear design built to remove a portion of hair", "thinning/blending shear"),
    difficulty: 'hard',
    order_index: 44,
  },
  {
    id: 'qq-5-045',
    quiz_id: 'quiz-5',
    question: "Which clipper motor description BEST matches the source?",
    answer_a: "Rotary — high power/speed; pivot — quieter and suited to thick/coarse hair; magnetic — reliable for fine textures",
    answer_b: "Rotary — blade material; pivot — guard size; magnetic — battery chemistry",
    answer_c: "Pivot and magnetic are the same motor type",
    answer_d: "Hydraulic, lithium, and ceramic are the three motor types",
    correct_answer: 'a',
    explanation: strategyExplanation("motor characteristics", "blade material, guard size, and battery chemistry are different categories; pivot and magnetic are separate source types", "compare the three named motors by the source characteristics", "rotary, pivot, and magnetic remain distinct"),
    difficulty: 'hard',
    order_index: 45,
  },
  {
    id: 'qq-5-046',
    quiz_id: 'quiz-5',
    question: "What is a razor shaper or hair razor used for?",
    answer_a: "Texturizing and shaping hair",
    answer_b: "Honing a conventional straight razor",
    answer_c: "Disinfecting clipper guards",
    answer_d: "Applying shaving lather",
    correct_answer: 'a',
    explanation: strategyExplanation("razor shaper purpose", "honing, disinfection, and lather application use different tools", "first decide whether the tool is for hair cutting or skin shaving", "texturizing and shaping hair"),
    difficulty: 'hard',
    order_index: 46,
  },

  // SCENARIO CARDS (4 questions)
  {
    id: 'qq-5-047',
    quiz_id: 'quiz-5',
    question: "A barber is detailing a hairline with an outliner. Which technique BEST matches the source?",
    answer_a: "Use a light hand/free wrist and maintain safe blade alignment",
    answer_b: "Set the blades flush and press firmly",
    answer_c: "Hold the tool rigidly and increase pressure at curves",
    answer_d: "Use a guard to replace the need for blade sanitation",
    correct_answer: 'a',
    explanation: strategyExplanation("outliner detailing", "flush adjustment, rigid heavy pressure, and treating guards as sanitation devices conflict with source safety", "precision tools require light pressure and safe alignment", "light hand/free wrist with safe blade alignment"),
    difficulty: 'hard',
    order_index: 47,
  },
  {
    id: 'qq-5-048',
    quiz_id: 'quiz-5',
    question: 'SCENARIO: A client wants a skin fade with sharp lines and a beard trim. Which tools are REQUIRED?',
    answer_a: 'Shears and comb only',
    answer_b: 'Just clippers with a #1 guard',
    answer_c: 'Clippers with guards, trimmer, straight razor, and comb',
    answer_d: 'Trimmer and straight razor only',
    correct_answer: 'c',
    explanation: 'Clippers with guards for fade, trimmer for sharp lineup, straight razor for final edge and neck shave, comb for sectioning. Shears alone cannot create a skin fade.',
    difficulty: 'medium',
    order_index: 48,
  },
  {
    id: 'qq-5-049',
    quiz_id: 'quiz-5',
    question: "A barber finishes honing and begins stropping a conventional razor. What procedural change is MOST important?",
    answer_a: "Use the strop and reverse direction by rolling the razor on its back while working both sides evenly",
    answer_b: "Increase pressure and roll on the cutting edge",
    answer_c: "Work only one side because honing already balanced the edge",
    answer_d: "Hold the razor by the point",
    correct_answer: 'a',
    explanation: strategyExplanation("transition from honing to stropping", "rolling on the edge, one-sided work, and holding the point are unsafe or incorrect", "stropping smooths/refines and uses the source's back-roll reversal with even work on both sides", "roll on the back and strop evenly"),
    difficulty: 'hard',
    order_index: 49,
  },
  {
    id: 'qq-5-050',
    quiz_id: 'quiz-5',
    question: "A barber is preparing to manipulate a thermal iron. Which sequence is BEST?",
    answer_a: "Prepare and section the hair, verify safe heat, control the iron, protect the scalp, and move consistently",
    answer_b: "Heat to maximum temperature, touch the scalp briefly, then section",
    answer_c: "Clamp one section in place until it smokes",
    answer_d: "Skip heat testing if the iron was used earlier",
    correct_answer: 'a',
    explanation: strategyExplanation("safe thermal-iron sequence", "maximum heat, scalp contact, stationary overheating, and skipping temperature verification violate safe procedure", "thermal manipulation begins with preparation and heat control before consistent movement", "section, verify heat, control tool, protect scalp, move consistently"),
    difficulty: 'hard',
    order_index: 50,
  },
]

// Stats
export const chapter5QuizStats = {
  total: chapter5PremiumQuizQuestions.length,
  byDifficulty: {
    easy: chapter5PremiumQuizQuestions.filter((q) => q.difficulty === 'easy').length,
    medium: chapter5PremiumQuizQuestions.filter((q) => q.difficulty === 'medium').length,
    hard: chapter5PremiumQuizQuestions.filter((q) => q.difficulty === 'hard').length,
  },
}


