import { Flashcard } from '@/types'

// Chapter 15: Men's Hair Replacement
// Created strictly from Chapter 15 textbook images and premium curriculum
// All content sourced from: textbook-images/chapter-15/ and chapter-15-premium.ts

export const chapter15PremiumFlashcards: Flashcard[] = [
  // === INTRODUCTION & MARKET ===
  {
    id: 'fc-ch15-001',
    chapter_id: 'ch-15',
    front: 'Why should barbers study men\'s hair replacement?',
    back: 'The thinning-hair market is the second fastest-growing category in barbering, behind only haircoloring. Specialists command premium pricing, build loyal clientele, and transform lives by restoring confidence and self-image.',
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch15-002',
    chapter_id: 'ch-15',
    front: 'What is the primary psychological benefit clients seek from hair replacement?',
    back: 'Clients are not buying hair — they are buying the man they used to see in the mirror. The barber\'s job is to deliver that reflection with honesty, skill, and care.',
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },

  // === HISTORY & TERMINOLOGY ===
  {
    id: 'fc-ch15-003',
    chapter_id: 'ch-15',
    front: 'What is the historical origin of the term "toupee"?',
    back: 'The foretop — a section of natural hair grown long to blend with a wig — evolved into the toupee of the 18th century. The term originally described the blending section, not the wig itself.',
    category: 'History',
    difficulty: 'medium',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch15-004',
    chapter_id: 'ch-15',
    front: 'What is the modern professional term for a hair replacement system?',
    back: '"Hair replacement system" or "hair solution." These terms are interchangeable on exams and position the service as solving a problem rather than covering a flaw.',
    category: 'Terminology',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch15-005',
    chapter_id: 'ch-15',
    front: 'Why should the term "toupee" be avoided in client consultations?',
    back: 'It carries stigma from outdated technology and obvious appearance. Modern clients may react negatively to a term associated with unnatural, detectable hairpieces.',
    category: 'Terminology',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },

  // === CONSULTATION ===
  {
    id: 'fc-ch15-006',
    chapter_id: 'ch-15',
    front: 'Where should hair replacement consultations take place?',
    back: 'In a private space — an office, quiet room, or at minimum when no other clients are within earshot. Never discuss hair replacement in the open shop.',
    category: 'Consultation',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch15-007',
    chapter_id: 'ch-15',
    front: 'What does the LAB MED framework stand for in hair replacement consultations?',
    back: 'Lifestyle, Age, Budget, Medical history, Expectations, Daily maintenance. These six factors guide every professional consultation.',
    category: 'Consultation',
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-ch15-008',
    chapter_id: 'ch-15',
    front: 'Why is age an important factor in hair replacement consultation?',
    back: 'Younger clients may want gradual transitions; older clients often prefer conservative styles. Dark, opaque colors look artificial on older clients — salt-and-pepper blends look more natural.',
    category: 'Consultation',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch15-009',
    chapter_id: 'ch-15',
    front: 'What is the professional obligation when a client requests an unrealistic style?',
    back: 'Educate with respect and recommend a more appropriate option. Giving an unrealistic system damages your reputation and the client\'s dignity. Never promise what you cannot deliver.',
    category: 'Consultation',
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },

  // === MARKETING & ETHICS ===
  {
    id: 'fc-ch15-010',
    chapter_id: 'ch-15',
    front: 'What are the most effective marketing channels for hair replacement services?',
    back: 'Social media (before-and-after photos with model releases), in-shop displays of sample systems, personal referrals from satisfied clients, and print advertising. A barber who wears a system becomes a walking advertisement.',
    category: 'Marketing',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-ch15-011',
    chapter_id: 'ch-15',
    front: 'Why must model release forms be obtained before using client photos?',
    back: 'Legal protection and professional ethics. Never post photos without explicit written permission. Keep release forms on file for at least three years. Friendship does not replace legal documentation.',
    category: 'Marketing',
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch15-012',
    chapter_id: 'ch-15',
    front: 'How should sample systems be maintained in the shop?',
    back: 'Shampoo after every client who tries it on. Style it fresh. Replace when it shows wear. The sample is a silent salesperson — treat it accordingly.',
    category: 'Marketing',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },

  // === ALTERNATIVE TREATMENTS ===
  {
    id: 'fc-ch15-013',
    chapter_id: 'ch-15',
    front: 'What are the three main nonsurgical alternatives to hair replacement systems?',
    back: 'Cover-up hair fibers (temporary), Minoxidil (topical FDA-approved medication), and Finasteride (oral prescription medication for men only).',
    category: 'Alternatives',
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch15-014',
    chapter_id: 'ch-15',
    front: 'What is the difference between 2% and 5% Minoxidil?',
    back: '2% is regular strength for men and women; 5% is extra-strength for men only. Moderately effective for about 50% of men after 4 months of consistent use.',
    category: 'Alternatives',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch15-015',
    chapter_id: 'ch-15',
    front: 'What are potential side effects of Finasteride?',
    back: 'Weight gain and loss of sexual function. As a prescription medication, barbers can discuss general information but cannot recommend specific dosages — always refer to a physician.',
    category: 'Alternatives',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch15-016',
    chapter_id: 'ch-15',
    front: 'What are the three main surgical hair restoration procedures?',
    back: 'Hair transplantation (follicles moved from donor areas), scalp reduction (bald scalp surgically removed and surrounding scalp pulled together), and flap surgery (hair-bearing skin flap repositioned).',
    category: 'Alternatives',
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch15-017',
    chapter_id: 'ch-15',
    front: 'What is a micrograph in hair transplantation?',
    back: 'A small section of hair follicles used in modern transplantation techniques, replacing the large plugs of older methods. Results can last a lifetime when performed properly.',
    category: 'Alternatives',
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },

  // === SCOPE OF PRACTICE ===
  {
    id: 'fc-ch15-018',
    chapter_id: 'ch-15',
    front: 'What can barbers legally do regarding hair replacement?',
    back: 'Measure, fit, cut, style, clean, and maintain hair replacement systems. Discuss general information about alternatives. Refer clients to physicians for medical advice.',
    category: 'Scope of Practice',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch15-019',
    chapter_id: 'ch-15',
    front: 'What can barbers NOT do regarding hair replacement?',
    back: 'Prescribe medication, diagnose medical conditions, recommend specific dosages, or perform surgical procedures. Crossing these boundaries puts your license at risk.',
    category: 'Scope of Practice',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch15-020',
    chapter_id: 'ch-15',
    front: 'How should a barber respond when asked "Should I use 2% or 5% Minoxidil?"',
    back: 'Explain that both strengths exist and that a physician can determine the right option. Provide factual information and direct the client to the appropriate medical professional.',
    category: 'Scope of Practice',
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },

  // === HAIR MATERIALS ===
  {
    id: 'fc-ch15-021',
    chapter_id: 'ch-15',
    front: 'What are the three main types of hair used in replacement systems?',
    back: 'Human hair, synthetic hair, and mixed hair (human blended with synthetic or animal fibers).',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch15-022',
    chapter_id: 'ch-15',
    front: 'What are the advantages of human hair in replacement systems?',
    back: 'Most natural look and texture; can be permed, colored, and heat-styled; durable with proper care. Best for clients who want the most realistic appearance.',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch15-023',
    chapter_id: 'ch-15',
    front: 'What are the disadvantages of human hair in replacement systems?',
    back: 'Reacts to humidity and temperature; fades with sun exposure; requires regular styling; can become damaged like natural hair.',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch15-024',
    chapter_id: 'ch-15',
    front: 'What is Kanekalon?',
    back: 'The most common synthetic fiber used in ready-to-wear wigs and hair systems. Holds style after washing, costs less than human hair, and does not oxidize or fade.',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-ch15-025',
    chapter_id: 'ch-15',
    front: 'What are the disadvantages of synthetic hair?',
    back: 'High gloss makes it more noticeable; mats and tangles when blended with human hair; limited chemical processing options.',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch15-026',
    chapter_id: 'ch-15',
    front: 'What is mixed hair and what fibers may it contain?',
    back: 'Human hair blended with synthetic or animal fibers — horse, yak, angora, or sheep\'s wool. Angora provides finer texture for natural front hairlines.',
    category: 'Materials',
    difficulty: 'medium',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch15-027',
    chapter_id: 'ch-15',
    front: 'Why should clients with wool allergies avoid certain mixed hair systems?',
    back: 'Some mixed fibers use wool bases that can trigger allergic reactions. Clients with wool allergies need keratin fiber alternatives.',
    category: 'Materials',
    difficulty: 'medium',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch15-028',
    chapter_id: 'ch-15',
    front: 'What is root-turning and why is it important?',
    back: 'Sorting hair so the cuticle points toward the ends in natural growth direction. Root-turned hair prevents tangling and matting because cuticles flow correctly.',
    category: 'Materials',
    difficulty: 'medium',
    order_index: 28,
    is_active: true,
  },

  // === BASE CONSTRUCTION ===
  {
    id: 'fc-ch15-029',
    chapter_id: 'ch-15',
    front: 'What are the five main base materials for hair replacement systems?',
    back: 'Mesh/net (breathable), polyurethane (waterproof), lace (invisible hairline), thin skin/onion skin (undetectable edge), and combination (strategic mix of materials).',
    category: 'Base Construction',
    difficulty: 'easy',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-ch15-030',
    chapter_id: 'ch-15',
    front: 'What is the memory anchor for remembering base materials?',
    back: '"My Nylon Socks Pull Lace Tight" — Mesh, Nylon (polyurethane), Socks (thin skin), Pull (polyurethane), Lace, Tight (thin skin).',
    category: 'Base Construction',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-ch15-031',
    chapter_id: 'ch-15',
    front: 'What is the primary advantage of mesh/net bases?',
    back: 'Most breathable option due to open-weave construction; comfortable for all-day wear. Disadvantage: less durable and can stretch over time.',
    category: 'Base Construction',
    difficulty: 'easy',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch15-032',
    chapter_id: 'ch-15',
    front: 'What is the primary advantage of polyurethane bases?',
    back: 'Waterproof and durable; excellent for adhesive bonding. Disadvantage: less breathable than mesh; can feel warmer on the scalp.',
    category: 'Base Construction',
    difficulty: 'easy',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch15-033',
    chapter_id: 'ch-15',
    front: 'What is the critical rule for lace-front systems?',
    back: 'NEVER apply tape directly to lace — it will tear the delicate material. Apply bonding agent to the skin at the hairline, not to the lace itself.',
    category: 'Base Construction',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch15-034',
    chapter_id: 'ch-15',
    front: 'Why are combination bases considered the industry standard?',
    back: 'They strategically use multiple materials in different zones — lace front for natural hairline, polyurethane perimeter for bonding, mesh center for breathability — optimizing comfort, durability, and appearance.',
    category: 'Base Construction',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },

  // === KNOTTING METHODS ===
  {
    id: 'fc-ch15-035',
    chapter_id: 'ch-15',
    front: 'What are the four main knotting methods for attaching hair to bases?',
    back: 'Single knot (common, may loosen during cleaning), double knot (stays secure through washing), V-loop (most natural root appearance), and single hair injection (hair appears to grow from scalp).',
    category: 'Base Construction',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },

  // === STOCK VS CUSTOM ===
  {
    id: 'fc-ch15-036',
    chapter_id: 'ch-15',
    front: 'What is the difference between stock and custom hair replacement systems?',
    back: 'Stock systems come in standard sizes and colors, cost less, and arrive faster. Custom systems are made from the client\'s template or plaster mold, fit perfectly, look seamless, and cost more with longer timelines.',
    category: 'System Types',
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch15-037',
    chapter_id: 'ch-15',
    front: 'When is a stock system the best choice for a client?',
    back: 'When the client has a common head shape, standard color needs, a limited budget, or needs the system quickly. Stock systems can be customized with cutting and styling.',
    category: 'System Types',
    difficulty: 'easy',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch15-038',
    chapter_id: 'ch-15',
    front: 'What is a plaster mold and why is it used?',
    back: 'A three-dimensional cast of the client\'s head made with plaster of Paris. Creates the most precise fit possible. The manufacturer pours foam into the cast to create a permanent reusable mold for future orders.',
    category: 'System Types',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch15-039',
    chapter_id: 'ch-15',
    front: 'Why should color samples be taken from multiple areas of the client\'s head?',
    back: 'Hair color varies across the scalp. Samples from the crown, temple, side, and back ensure accurate color matching — especially critical for natural-looking gray blending at the system edges.',
    category: 'System Types',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },

  // === SUPPLIES & MEASUREMENT ===
  {
    id: 'fc-ch15-040',
    chapter_id: 'ch-15',
    front: 'How are hair replacement system sizes measured?',
    back: 'In inches — length by width. A 6x4 piece means six inches front-to-back and four inches side-to-side. The larger number typically refers to length unless the manufacturer specifies otherwise.',
    category: 'Measurement',
    difficulty: 'easy',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-ch15-041',
    chapter_id: 'ch-15',
    front: 'What is the purpose of a template in custom system creation?',
    back: 'A pattern of the client\'s bald area created with plastic wrap and tape, marked with a grease pencil. It becomes the manufacturer\'s blueprint for cutting the base to exact specifications.',
    category: 'Measurement',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch15-042',
    chapter_id: 'ch-15',
    front: 'Why should barbers NOT substitute standard barber supplies for hair replacement supplies?',
    back: 'The wrong adhesive damages bases. The wrong solvent ruins hair. Always use manufacturer-recommended products for adhesives, removers, and cleaning solvents.',
    category: 'Supplies',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },

  // === ATTACHMENT METHODS ===
  {
    id: 'fc-ch15-043',
    chapter_id: 'ch-15',
    front: 'What are the five main attachment methods for hair replacement systems?',
    back: 'Full head bonding (copolymer adhesive across entire scalp), tape attachment (double-sided tape at perimeter), lace-front bonding (adhesive to skin, not lace), spirit gum (for facial hair), and full wig with elastic bands.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch15-044',
    chapter_id: 'ch-15',
    front: 'What is the BLF-F memory anchor for attachment methods?',
    back: 'Bonding, Lace-front, Facial, Full wigs — plus Tape. Think "Bluff" with an extra T for Tape.',
    category: 'Attachment',
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch15-045',
    chapter_id: 'ch-15',
    front: 'What is full head bonding and when is it the best choice?',
    back: 'Adhesive copolymer applied across the entire scalp contact area. Most secure, waterproof, and ideal for active clients who swim or exercise and want a permanent-wear solution.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch15-046',
    chapter_id: 'ch-15',
    front: 'What is the critical cure time after full head bonding?',
    back: 'The client must wait 24 to 48 hours before shampooing to allow the adhesive to fully cure. State boards frequently test this timeline.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch15-047',
    chapter_id: 'ch-15',
    front: 'What is the main advantage of tape attachment over full bonding?',
    back: 'Easier to remove and reattach. Good for clients who take their systems off daily. Less secure than full bonding and may lift at edges during heavy activity.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch15-048',
    chapter_id: 'ch-15',
    front: 'How is spirit gum used for facial hair pieces?',
    back: 'Applied to clean, dry facial skin. Wait until tacky, position the piece, and press gently with a lint-free cloth. Remove with spirit gum remover — never pull off dry.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },

  // === CLEANING & MAINTENANCE ===
  {
    id: 'fc-ch15-049',
    chapter_id: 'ch-15',
    front: 'What are the COOL Rules for system care?',
    back: 'C — Clean with recommended solvent or shampoo only. O — Only lukewarm water, never hot. O — Overnight drying on a block is preferred. L — Let the system dry naturally; cool air if rushed.',
    category: 'Maintenance',
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch15-050',
    chapter_id: 'ch-15',
    front: 'Why must synthetic systems be cleaned with lukewarm water only?',
    back: 'Hot water causes shrinkage, matting, and tangling in synthetic hair. Lukewarm water preserves the fiber integrity and style retention.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 50,
    is_active: true,
  },
  {
    id: 'fc-ch15-051',
    chapter_id: 'ch-15',
    front: 'What products should be avoided when cleaning human hair systems?',
    back: 'Harsh solvents, acetone, and alcohol-based cleaners. These damage processed human hair. Use only shampoo and conditioner formulated specifically for hair replacement systems.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-ch15-052',
    chapter_id: 'ch-15',
    front: 'What is the recommended maintenance schedule for hair replacement systems?',
    back: 'First cleaning after one week of wear to remove manufacturing residues. After that, clean every three to four weeks, or more frequently with heavy sweating, product use, or humid climates.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-ch15-053',
    chapter_id: 'ch-15',
    front: 'Why should clients own at least two hair replacement systems?',
    back: 'So one can be worn while the other is being cleaned, dried, and serviced. A system worn daily without rotation will deteriorate months before its expected lifespan.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-ch15-054',
    chapter_id: 'ch-15',
    front: 'How should systems be stored when not in use?',
    back: 'Flat on a styling block or wig block. Never fold the system — folding creases the base and damages the hair. Use T-pins to secure during cleaning and drying.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },

  // === CHEMICAL SERVICES ON SYSTEMS ===
  {
    id: 'fc-ch15-055',
    chapter_id: 'ch-15',
    front: 'What is the floating technique for perming hair systems?',
    back: 'Perm rods must not rest directly on the base — the weight creates indentations and damage. Roller picks are inserted at both ends of each rod so the rod hovers above the base like a bridge.',
    category: 'Chemical Services',
    difficulty: 'medium',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-ch15-056',
    chapter_id: 'ch-15',
    front: 'What types of chemical services are NEVER performed on hair replacement systems?',
    back: 'Lightening (bleach) and cold-waving. These destroy the base material. Use temporary color rinses only if coloring is necessary.',
    category: 'Chemical Services',
    difficulty: 'easy',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-ch15-057',
    chapter_id: 'ch-15',
    front: 'What is the memory anchor for floating perm rods?',
    back: '"Hovering Helicopters" — the rod is the helicopter, the base is the landing pad, and the roller picks are the landing gear. The helicopter hovers above the pad to avoid crushing it.',
    category: 'Chemical Services',
    difficulty: 'medium',
    order_index: 57,
    is_active: true,
  },

  // === CUTTING & BLENDING ===
  {
    id: 'fc-ch15-058',
    chapter_id: 'ch-15',
    front: 'What is the key principle for making a hair replacement system undetectable?',
    back: 'Blending. The transition between system hair and natural hair must be invisible. You are not just cutting hair — you are erasing the boundary between artificial and natural.',
    category: 'Cutting',
    difficulty: 'easy',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-ch15-059',
    chapter_id: 'ch-15',
    front: 'How is the top section of a system cut?',
    back: 'At 90-degree elevation using clipper-over-comb or fingers-and-shear. Work forward from crown to forehead, blending with shears to create seamless transitions.',
    category: 'Cutting',
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-ch15-060',
    chapter_id: 'ch-15',
    front: 'What is slide cutting and why is it essential for blending?',
    back: 'The shear slides through hair at an angle instead of cutting straight across. This creates a feathered, tapered edge that disappears into the client\'s natural hair. Practice until the motion feels automatic.',
    category: 'Cutting',
    difficulty: 'medium',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-ch15-061',
    chapter_id: 'ch-15',
    front: 'What is the golden rule when customizing stock systems?',
    back: 'Be conservative — you can always cut more, but you cannot put hair back. Remove excess length gradually, taper sides to match natural hairlines, and thin heavy areas with narrow partings.',
    category: 'Cutting',
    difficulty: 'easy',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-ch15-062',
    chapter_id: 'ch-15',
    front: 'Why should thinning shears be used with narrow partings near the base?',
    back: 'Wide partings create visible gaps that ruin the finished appearance. Narrow partings allow controlled bulk removal without creating holes in the blend.',
    category: 'Cutting',
    difficulty: 'medium',
    order_index: 62,
    is_active: true,
  },

  // === BOARD EXAM TRAPS ===
  {
    id: 'fc-ch15-063',
    chapter_id: 'ch-15',
    front: 'Board Exam Trap: Can a barber prescribe Minoxidil?',
    back: 'FALSE. Only physicians can prescribe medication. Barbers can discuss general information and refer clients to medical professionals.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-ch15-064',
    chapter_id: 'ch-15',
    front: 'Board Exam Trap: Can synthetic hair be permed with standard solution?',
    back: 'FALSE. Synthetic fiber has limited chemical tolerance. Standard perm solutions will damage or destroy synthetic hair.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 64,
    is_active: true,
  },
  {
    id: 'fc-ch15-065',
    chapter_id: 'ch-15',
    front: 'Board Exam Trap: Does hot water clean synthetic systems better?',
    back: 'FALSE. Hot water causes shrinkage and matting in synthetic hair. Only lukewarm water should be used for cleaning.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-ch15-066',
    chapter_id: 'ch-15',
    front: 'Board Exam Trap: Can tape be applied directly to lace fronts?',
    back: 'FALSE. Tape tears delicate lace material. Adhesive should be applied to the skin at the hairline, never to the lace itself.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-ch15-067',
    chapter_id: 'ch-15',
    front: 'Board Exam Trap: Can a bonded client shampoo immediately after application?',
    back: 'FALSE. The client must wait 24 to 48 hours for the adhesive to fully cure before shampooing or wetting the bonded area.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-ch15-068',
    chapter_id: 'ch-15',
    front: 'Board Exam Trap: Can barbers perform hair transplantation?',
    back: 'FALSE. Surgical procedures are medical only. Barbers discuss, refer, and support — never perform surgery.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-ch15-069',
    chapter_id: 'ch-15',
    front: 'Board Exam Trap: Can human hair systems be lightened with bleach?',
    back: 'FALSE. Lightening damages the base material. Use temporary color rinses only — never lighten or cold-wave a system.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-ch15-070',
    chapter_id: 'ch-15',
    front: 'Board Exam Trap: Is one system enough for daily wear?',
    back: 'FALSE. Clients need at least two systems for rotation — one to wear while the other is being cleaned and serviced.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 70,
    is_active: true,
  },

  // === SCENARIO CARDS ===
  {
    id: 'fc-ch15-071',
    chapter_id: 'ch-15',
    front: 'Scenario: A regular client says "I\'m starting to look like my father." What is your most professional response?',
    back: 'Acknowledge his comment and ask if he would like to discuss options in private. You validated his concern, offered privacy, and invited further conversation without pressure.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 71,
    is_active: true,
  },
  {
    id: 'fc-ch15-072',
    chapter_id: 'ch-15',
    front: 'Scenario: A 68-year-old client wants jet-black hair styled like a 25-year-old celebrity. What is your professional obligation?',
    back: 'Explain why the request will look unnatural and recommend a more appropriate option. Educate with respect. Show samples of age-appropriate colors and styles that restore confidence without looking ridiculous.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 72,
    is_active: true,
  },
  {
    id: 'fc-ch15-073',
    chapter_id: 'ch-15',
    front: 'Scenario: A client needs a system in three days for a wedding. He has a standard oval bald area and a $400 budget. What do you recommend?',
    back: 'A stock system in a close color match, customized with cutting and blending. Stock systems are available immediately, fit the budget, and can be cut and styled to look natural for the event.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 73,
    is_active: true,
  },
  {
    id: 'fc-ch15-074',
    chapter_id: 'ch-15',
    front: 'Scenario: A competitive swimmer wants a system he never has to remove. Which attachment method do you recommend?',
    back: 'Full head bonding with a waterproof copolymer adhesive. Full bonding is waterproof, secure, and designed for clients who want a permanent-wear solution during swimming and exercise.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 74,
    is_active: true,
  },
  {
    id: 'fc-ch15-075',
    chapter_id: 'ch-15',
    front: 'Scenario: A client asks which Minoxidil strength to use and how often. How do you respond?',
    back: 'Explain that both 2% and 5% strengths exist and that a physician can determine the right option. Provide factual information and direct the client to the appropriate medical professional.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 75,
    is_active: true,
  },

  // === COMPARISON CARDS ===
  {
    id: 'fc-ch15-076',
    chapter_id: 'ch-15',
    front: 'Compare human hair vs synthetic hair for replacement systems.',
    back: 'Human: most natural, can be chemically processed, reacts to climate, fades in light, high maintenance. Synthetic: holds style, lower cost, resists oxidation, limited chemical options, can look glossy.',
    category: 'Comparisons',
    difficulty: 'easy',
    order_index: 76,
    is_active: true,
  },
  {
    id: 'fc-ch15-077',
    chapter_id: 'ch-15',
    front: 'Compare stock vs custom hair replacement systems.',
    back: 'Stock: standard sizes/colors, lower cost, immediate availability, can be cut to fit. Custom: made from template/plaster mold, perfect fit, higher cost, longer timeline, most natural result.',
    category: 'Comparisons',
    difficulty: 'easy',
    order_index: 77,
    is_active: true,
  },
  {
    id: 'fc-ch15-078',
    chapter_id: 'ch-15',
    front: 'Compare full head bonding vs tape attachment.',
    back: 'Bonding: most secure, waterproof, 24-48 hour cure time, harder to remove. Tape: easier to remove/reattach, less secure, may lift during activity, good for daily removal.',
    category: 'Comparisons',
    difficulty: 'easy',
    order_index: 78,
    is_active: true,
  },
  {
    id: 'fc-ch15-079',
    chapter_id: 'ch-15',
    front: 'Compare mesh vs polyurethane base materials.',
    back: 'Mesh: breathable, comfortable, less durable, can stretch. Polyurethane: waterproof, durable, excellent for bonding, less breathable, feels warmer.',
    category: 'Comparisons',
    difficulty: 'easy',
    order_index: 79,
    is_active: true,
  },

  // === PROCEDURE CARDS ===
  {
    id: 'fc-ch15-080',
    chapter_id: 'ch-15',
    front: 'What are the steps for creating a template for a custom system?',
    back: '1. Cover bald area with plastic wrap, smoothing flat. 2. Apply transparent tape over the wrap to create rigidity. 3. Mark front hairline, sides, and nape with grease pencil. 4. Remove carefully and transfer to pattern paper.',
    category: 'Procedures',
    difficulty: 'medium',
    order_index: 80,
    is_active: true,
  },
  {
    id: 'fc-ch15-081',
    chapter_id: 'ch-15',
    front: 'What is the proper procedure for cleaning a synthetic hair system?',
    back: 'Attach to foam block with T-pins. Immerse in manufacturer-recommended solvent. Swish gently. Rinse with clean lukewarm water. Dry naturally on the block overnight. Use cool air only if rushed — never hot.',
    category: 'Procedures',
    difficulty: 'medium',
    order_index: 81,
    is_active: true,
  },
  {
    id: 'fc-ch15-082',
    chapter_id: 'ch-15',
    front: 'What is the proper procedure for applying a facial hair piece with spirit gum?',
    back: 'Apply spirit gum to clean, dry facial skin. Wait until tacky. Position the piece. Press gently with lint-free cloth. Remove with spirit gum remover — never pull off dry.',
    category: 'Procedures',
    difficulty: 'easy',
    order_index: 82,
    is_active: true,
  },
  {
    id: 'fc-ch15-083',
    chapter_id: 'ch-15',
    front: 'What is the cutting and blending procedure for a new system?',
    back: 'Top: cut at 90° elevation, work crown to forehead. Sides: comb down, blend to natural hairline, taper with slide cutting. Back: cut excess, blend with thinning shears. Final check from all angles under different lighting.',
    category: 'Procedures',
    difficulty: 'medium',
    order_index: 83,
    is_active: true,
  },

  // === SAFETY CARDS ===
  {
    id: 'fc-ch15-084',
    chapter_id: 'ch-15',
    front: 'What is the number one regret barbers have when customizing stock systems?',
    back: 'Cutting too much during initial customization. Be conservative — remove length gradually. You can always cut more, but you cannot put hair back.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 84,
    is_active: true,
  },
  {
    id: 'fc-ch15-085',
    chapter_id: 'ch-15',
    front: 'Why should systems never be folded for storage?',
    back: 'Folding creases the base material and damages the hair. Always store flat on a block or in a proper storage container.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 85,
    is_active: true,
  },
  {
    id: 'fc-ch15-086',
    chapter_id: 'ch-15',
    front: 'Why must dull blades be replaced during system customization?',
    back: 'Dull blades pull hair, causing damage to the system and creating uneven cuts. Sharp tools are essential for clean, precise work on expensive systems.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 86,
    is_active: true,
  },

  // === KEY TAKEAWAYS ===
  {
    id: 'fc-ch15-087',
    chapter_id: 'ch-15',
    front: 'What is the most important principle of men\'s hair replacement?',
    back: 'You are not selling hair. You are restoring the reflection your client wants to see every morning. Technical skill, ethical practice, and emotional intelligence are all required.',
    category: 'Key Takeaways',
    difficulty: 'easy',
    order_index: 87,
    is_active: true,
  },
  {
    id: 'fc-ch15-088',
    chapter_id: 'ch-15',
    front: 'What makes the difference between an obvious hairpiece and an undetectable system?',
    back: 'Blending. The transition between system hair and natural hair must be invisible. Slide cutting, proper thinning, and careful tapering create the illusion that all hair is natural.',
    category: 'Key Takeaways',
    difficulty: 'easy',
    order_index: 88,
    is_active: true,
  },
  {
    id: 'fc-ch15-089',
    chapter_id: 'ch-15',
    front: 'Why is scope of practice knowledge critical for hair replacement barbers?',
    back: 'State boards frequently test boundaries. Knowing what barbers can do (fit, cut, maintain) versus cannot do (prescribe, diagnose, perform surgery) protects your license and your client\'s health.',
    category: 'Key Takeaways',
    difficulty: 'easy',
    order_index: 89,
    is_active: true,
  },
  {
    id: 'fc-ch15-090',
    chapter_id: 'ch-15',
    front: 'What is the 24-48 hour rule and why does it matter?',
    back: 'After full head bonding, the client must wait 24 to 48 hours before shampooing. This allows adhesive to fully cure. It is one of the most frequently tested facts on state board exams.',
    category: 'Key Takeaways',
    difficulty: 'easy',
    order_index: 90,
    is_active: true,
  },
]

export default chapter15PremiumFlashcards
