// Chapter 7: Basics of Chemistry — PREMIUM FLASHCARDS
// The Barber's Laboratory — Master the Formulas Behind Every Product
// Categories: Matter & Properties, Redox Reactions, Solutions & Emulsions, pH & Water, Shampoos & Conditioners, Product Chemistry, Safety & USP, Board Exam Alerts
// Source: Chapter 7 textbook images (textbook-images/chapter-7/)

import { Flashcard } from '@/types'

export const chapter7PremiumFlashcards: Flashcard[] = [
  // ==========================================
  // CATEGORY 1: MATTER & PROPERTIES (10 cards)
  // ==========================================
  {
    id: 'fc-7-001',
    chapter_id: 'ch-7',
    front: 'What is the definition of chemistry?',
    back: 'The science of the composition, structure, and properties of matter and how it changes. Understanding chemistry is essential for safe product use in barbering.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-7-002',
    chapter_id: 'ch-7',
    front: 'What is the difference between organic and inorganic chemistry?',
    back: 'Organic chemistry studies carbon-containing substances (living or once-living things) like gasoline, plastics, and proteins. Inorganic chemistry studies substances without carbon like metals, minerals, water, and ammonia.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-7-003',
    chapter_id: 'ch-7',
    front: 'Do organic substances burn? Do inorganic substances burn?',
    back: 'Organic substances burn (they contain carbon). Inorganic substances do NOT burn (no carbon). This distinction is critical for chemical safety in the barbershop.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-7-004',
    chapter_id: 'ch-7',
    front: 'What is matter?',
    back: 'Anything that occupies space (has volume) and has mass (weight). Matter exists in three states: solid, liquid, and gas.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-7-005',
    chapter_id: 'ch-7',
    front: 'What is the difference between a physical property and a chemical property?',
    back: 'Physical properties can be observed without a chemical reaction (color, odor, density, melting point, solubility). Chemical properties are observed only through chemical reactions that change the substance (rusting, burning, oxidation).',
    category: 'Matter & Properties',
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-7-006',
    chapter_id: 'ch-7',
    front: 'What is the difference between a physical change and a chemical change?',
    back: 'Physical change: form changes but no new substance is created (ice melting, temporary hair color). Chemical change: new substances are formed (haircolor oxidation, rusting, burning). Chemical changes are permanent.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-7-007',
    chapter_id: 'ch-7',
    front: 'What is an element?',
    back: 'The simplest form of matter. An element contains only one type of atom. There are 118 known elements, with 98 occurring naturally. Examples: hydrogen, oxygen, carbon, nitrogen.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-7-008',
    chapter_id: 'ch-7',
    front: 'What are the three subatomic particles and their charges?',
    back: 'Protons (+ positive charge), neutrons (neutral/no charge), and electrons (– negative charge). These particles make up atoms and determine chemical behavior.',
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-7-009',
    chapter_id: 'ch-7',
    front: 'What is the difference between a molecule and a compound?',
    back: 'A molecule is two or more atoms joined by chemical bonds (can be the same element: O₂, or different: H₂O). A compound is a molecule containing DIFFERENT elements chemically united in fixed proportions (H₂O, CO₂, NaCl). All compounds are molecules, but not all molecules are compounds.',
    category: 'Matter & Properties',
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-7-010',
    chapter_id: 'ch-7',
    front: 'What is the difference between a pure substance and a physical mixture?',
    back: 'Pure substance: fixed composition and definite proportions (elements or compounds). Physical mixture: blended without fixed composition, can be uniform (homogeneous like saltwater) or nonuniform (heterogeneous like salad).',
    category: 'Matter & Properties',
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 2: REDOX REACTIONS (8 cards)
  // ==========================================
  {
    id: 'fc-7-011',
    chapter_id: 'ch-7',
    front: 'What is oxidation?',
    back: 'The addition of oxygen OR the loss of hydrogen. When a substance is oxidized, it gains oxygen or loses hydrogen atoms. Example: haircolor gains oxygen from hydrogen peroxide during development.',
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-7-012',
    chapter_id: 'ch-7',
    front: 'What is reduction?',
    back: 'The loss of oxygen OR the gain of hydrogen. When a substance is reduced, it loses oxygen or gains hydrogen atoms. Example: hydrogen peroxide loses oxygen when it develops haircolor.',
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-7-013',
    chapter_id: 'ch-7',
    front: 'Why do oxidation and reduction always occur together?',
    back: 'They are paired processes called REDOX reactions. One substance cannot be oxidized without another being reduced. The electrons lost in oxidation are gained in reduction. This pairing is fundamental to all chemical services.',
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-7-014',
    chapter_id: 'ch-7',
    front: 'What chemical reaction occurs during permanent waving?',
    back: 'REDUCTION breaks disulfide bonds in the hair using a reducing lotion (gains hydrogen/loses oxygen). Then OXIDATION (neutralizer) reforms the bonds in the new curled shape. The process requires both reduction AND oxidation.',
    category: 'Redox Reactions',
    difficulty: 'hard',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-7-015',
    chapter_id: 'ch-7',
    front: 'What is the role of hydrogen peroxide in haircolor?',
    back: 'Hydrogen peroxide (H₂O₂) is the oxidizing agent. It releases oxygen that oxidizes the haircolor molecules, allowing them to develop and bond to the hair. The H₂O₂ itself is REDUCED (loses oxygen) in the process.',
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-7-016',
    chapter_id: 'ch-7',
    front: 'What is an exothermic reaction? Give a barbering example.',
    back: 'A reaction that RELEASES heat. Example: mixing permanent wave activator with waving lotion creates heat. The container may feel warm — this is normal and expected.',
    category: 'Redox Reactions',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-7-017',
    chapter_id: 'ch-7',
    front: 'What is an endothermic reaction? Give a barbering example.',
    back: 'A reaction that ABSORBS heat from its surroundings. Example: some waving lotions require external heat (like a dryer) to process because the chemical reaction absorbs heat rather than generating it.',
    category: 'Redox Reactions',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-7-018',
    chapter_id: 'ch-7',
    front: 'What happens during the neutralization step of a permanent wave?',
    back: 'The neutralizer (oxidizing agent) reforms the disulfide bonds that were broken during the reduction phase. This "locks" the hair into its new curled shape. Skipping or shortening neutralization causes weak, frizzy curls.',
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 3: SOLUTIONS, SUSPENSIONS & EMULSIONS (8 cards)
  // ==========================================
  {
    id: 'fc-7-019',
    chapter_id: 'ch-7',
    front: 'What is a solution?',
    back: 'A stable, uniform physical mixture where one substance (the solute) is completely dissolved in another (the solvent). Solutions are clear and do NOT separate over time. Example: salt dissolved in water.',
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-7-020',
    chapter_id: 'ch-7',
    front: 'What is a suspension?',
    back: 'An unstable physical mixture with visible particles that settle over time. Suspensions must be shaken before use. Example: calamine lotion, some hair tonics, and certain medicated shampoos.',
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-7-021',
    chapter_id: 'ch-7',
    front: 'What is an emulsion?',
    back: 'A mixture of two immiscible liquids (like oil and water) held together by an emulsifier or surfactant. Emulsions are milky or creamy and can separate over time. Most shampoos and conditioners are emulsions.',
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-7-022',
    chapter_id: 'ch-7',
    front: 'What is the difference between an oil-in-water (O/W) and water-in-oil (W/O) emulsion?',
    back: 'Oil-in-water (O/W): water is the main ingredient (continuous phase), oil is dispersed. Most barbering products are O/W. Water-in-oil (W/O): oil is the main ingredient, water is dispersed. Heavier, more moisturizing, used for very dry skin/hair.',
    category: 'Solutions & Emulsions',
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-7-023',
    chapter_id: 'ch-7',
    front: 'What is a surfactant and what is its molecular structure?',
    back: 'A surfactant reduces surface tension between oil and water, allowing them to mix. Its structure has a hydrophilic (water-loving) HEAD and a lipophilic (oil-loving) TAIL. This dual nature makes cleansing possible.',
    category: 'Solutions & Emulsions',
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-7-024',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What are the four types of surfactants and their charges?',
    back: '1. ANIONIC: negative charge — strong cleansing (primary shampoo surfactant). 2. CATIONIC: positive charge — conditioning (adheres to hair). 3. NONIONIC: no charge — mild cleansing. 4. AMPHOTERIC: both charges — very gentle, pH-dependent behavior.',
    category: 'Solutions & Emulsions',
    difficulty: 'hard',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-7-025',
    chapter_id: 'ch-7',
    front: 'Why do some products say "Shake Well Before Use"?',
    back: 'They are suspensions — unstable mixtures where particles settle over time. Shaking redistributes the active ingredients evenly. If not shaken, the first use may be too weak and the last use too concentrated.',
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-7-026',
    chapter_id: 'ch-7',
    front: 'What type of emulsion are most shampoos and conditioners?',
    back: 'Oil-in-water (O/W) emulsions. Water is the continuous phase (main ingredient), with oil droplets dispersed throughout. This makes them easy to spread and rinse out.',
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 4: pH & WATER (12 cards)
  // ==========================================
  {
    id: 'fc-7-027',
    chapter_id: 'ch-7',
    front: 'What does pH measure?',
    back: 'pH measures the acidity or alkalinity of a substance — specifically, the concentration of hydrogen ions (H⁺). The scale runs from 0 (most acidic) to 14 (most alkaline), with 7 being neutral.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-7-028',
    chapter_id: 'ch-7',
    front: 'What is the natural pH range of healthy hair and skin?',
    back: '4.5 to 5.5 — slightly acidic. This acidity keeps the cuticle closed, maintains moisture balance, and protects against bacteria and fungi. Products outside this range can damage hair over time.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-7-029',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What effect does ACID (pH 0–6.9) have on hair?',
    back: 'Acids CLOSE the cuticle, HARDEN the hair shaft, improve SHEEN, and remove residue. Very strong acids (pH 0–1) can DISSOLVE hair. Acidic products make hair smoother and shinier.',
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-7-030',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What effect does ALKALI (pH 7.1–14) have on hair?',
    back: 'Alkalis OPEN the cuticle, SWELL the hair shaft, and SOFTEN the hair. Mild alkalis (pH 5.5–10) are used in tints, bleaches, and cold waves. Strong alkalis (pH 10–14) can DISSOLVE hair and must never touch the scalp.',
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-7-031',
    chapter_id: 'ch-7',
    front: 'What is acid-alkali neutralization and why is it important in barbering?',
    back: 'When equal proportions of acid and alkali combine, they form WATER + SALT, returning to neutral pH. In barbering, neutralizing shampoo is used AFTER chemical services (perms, relaxers) to restore the hair\'s acidic pH and close the cuticle.',
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-7-032',
    chapter_id: 'ch-7',
    front: 'What is the difference between soft water and hard water?',
    back: 'Soft water: low mineral content, lathers easily with soap/shampoo, rinses clean. Hard water: high mineral content (calcium, magnesium), does NOT lather well, leaves mineral buildup on hair and tools. Hard water can make hair feel dry and look dull.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-7-033',
    chapter_id: 'ch-7',
    front: 'How much can pure water swell hair?',
    back: 'Up to 20%. This is why wet hair is more fragile than dry hair — the cuticle opens and the cortex swells with water. Handle wet hair gently to prevent breakage.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-7-034',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: At what pH does hair get dissolved?',
    back: 'pH 0–1 (very strong acid) AND pH 10–14 (strong alkali). Both extremes destroy hair. Relaxers and depilatories use strong alkali and must NEVER contact the scalp.',
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-7-035',
    chapter_id: 'ch-7',
    front: 'Why is water called the "universal solvent"?',
    back: 'Water dissolves more substances than any other liquid. This makes it essential for cleansing, mixing products, and chemical reactions. However, water alone cannot dissolve oils — surfactants are needed for that.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-7-036',
    chapter_id: 'ch-7',
    front: 'What are the three methods of water purification?',
    back: '1. Boiling: kills bacteria and pathogens. 2. Filtration: removes particles and some contaminants. 3. Distillation: boils water and condenses steam, removing minerals and impurities — produces the purest water.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-7-037',
    chapter_id: 'ch-7',
    front: 'Why does hard water affect shampoo performance?',
    back: 'Hard water contains calcium and magnesium minerals that react with shampoo surfactants, forming soap scum instead of lather. This reduces cleansing effectiveness and leaves mineral buildup on hair, making it feel dry and look dull.',
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-7-038',
    chapter_id: 'ch-7',
    front: 'What pH range should conditioner have and why?',
    back: 'pH 3.0–5.5 — acidic. This acidity closes the cuticle, smooths the hair surface, locks in moisture, and restores the hair\'s natural pH after alkaline shampooing.',
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 38,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 5: SHAMPOOS & CONDITIONERS (12 cards)
  // ==========================================
  {
    id: 'fc-7-039',
    chapter_id: 'ch-7',
    front: 'What is the primary function of shampoo?',
    back: 'To cleanse the hair and scalp by removing oil, dirt, debris, and product buildup. Shampoos are mostly oil-in-water emulsions containing surfactants that allow oil and water to mix so dirt can be rinsed away.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-7-040',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What are the four surfactant classifications used in shampoo?',
    back: '1. ANIONIC: negative charge, strong cleansing, primary shampoo surfactant. 2. CATIONIC: positive charge, conditioning, antibacterial. 3. NONIONIC: no charge, mild cleansing, gentle formulas. 4. AMPHOTERIC: both charges, very gentle, pH-adjusting behavior.',
    category: 'Shampoos & Conditioners',
    difficulty: 'hard',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-7-041',
    chapter_id: 'ch-7',
    front: 'What is the difference between clarifying shampoo and moisturizing shampoo?',
    back: 'Clarifying shampoo: removes heavy buildup, minerals, and residue. Use weekly, not daily — can be drying. Moisturizing/conditioning shampoo: contains oils and proteins to restore moisture to dry or damaged hair.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-7-042',
    chapter_id: 'ch-7',
    front: 'When should neutralizing shampoo be used?',
    back: 'After chemical services like perms, relaxers, and haircolor. Neutralizing shampoo restores the hair\'s acidic pH (closes the cuticle) and stops the chemical reaction. Skipping neutralization leaves hair damaged and porous.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-7-043',
    chapter_id: 'ch-7',
    front: 'What is a medicated shampoo and when is it used?',
    back: 'Contains active ingredients to treat scalp conditions like dandruff, seborrheic dermatitis, or psoriasis. Follow label directions carefully. Some require a doctor\'s recommendation. Do not use on healthy scalps.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-7-044',
    chapter_id: 'ch-7',
    front: 'What is the purpose of sulfate-free shampoo?',
    back: 'Sulfate-free shampoos use gentler cleansing agents that produce less lather but are less stripping. Ideal for sensitive scalps, color-treated hair, and chemically processed hair that needs moisture retention.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-7-045',
    chapter_id: 'ch-7',
    front: 'What are the main types of conditioners?',
    back: '1. INSTANT/RINSE-OUT: applied after shampoo, left briefly, rinsed — daily use. 2. TREATMENT/REPAIR: deep conditioning with higher protein/moisture — left on longer for damaged hair. 3. LEAVE-IN: not rinsed — provides ongoing protection.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-7-046',
    chapter_id: 'ch-7',
    front: 'What are common ingredients in conditioners and what do they do?',
    back: 'Proteins: strengthen and repair. Fatty materials/oils: soften and smooth. Humectants: draw moisture into hair. Moisturizers: hydrate. Silicones: add shine, reduce frizz, protect from heat.',
    category: 'Shampoos & Conditioners',
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-7-047',
    chapter_id: 'ch-7',
    front: 'What is a dry/powder shampoo and when is it useful?',
    back: 'A waterless cleansing product that absorbs oil and refreshes hair between washes. Useful for clients who cannot wash daily, have oily scalps, or need quick refreshment. Apply to roots, massage, brush out.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-7-048',
    chapter_id: 'ch-7',
    front: 'What is a balancing shampoo and who should use it?',
    back: 'Designed for oily scalps. Balancing shampoo regulates sebum (oil) production without over-drying the hair shaft. Different from clarifying shampoo — it balances rather than strips.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-7-049',
    chapter_id: 'ch-7',
    front: 'What is color-enhancing shampoo?',
    back: 'Contains color-depositing pigments that maintain and extend hair color between salon visits. May also include UV protection to prevent color fading from sun exposure. Not a replacement for professional color.',
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-7-050',
    chapter_id: 'ch-7',
    front: 'Why should you match shampoo to hair type?',
    back: 'Different hair types have different needs. Fine hair needs volumizing (lightweight) shampoo. Coarse/dry hair needs moisturizing. Oily scalps need balancing. Color-treated hair needs sulfate-free. Chemically processed hair needs conditioning. Using the wrong shampoo causes damage or poor results.',
    category: 'Shampoos & Conditioners',
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 6: PRODUCT CHEMISTRY & INGREDIENTS (12 cards)
  // ==========================================
  {
    id: 'fc-7-051',
    chapter_id: 'ch-7',
    front: 'What does USP stand for and why does it matter in barbering?',
    back: 'United States Pharmacopeia — an official body that sets standards for the strength, quality, and purity of ingredients used in hair and skin products. USP-standard ingredients ensure consistency and safety in professional products.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-7-052',
    chapter_id: 'ch-7',
    front: 'What is the function of hydrogen peroxide in barbering products?',
    back: 'An oxidizing and bleaching agent. 3–5% concentration is used as an antiseptic. 20–40 volume (6–12%) is used for hair lightening and color development. It releases oxygen to develop color molecules.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-7-053',
    chapter_id: 'ch-7',
    front: 'What is glycerin and why is it in hair products?',
    back: 'A humectant — it draws moisture from the air into hair and skin. Common in conditioners and lotions. Helps maintain hydration, especially in dry climates.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-7-054',
    chapter_id: 'ch-7',
    front: 'What is petrolatum (Vaseline) used for in barbering?',
    back: 'A protective emollient that creates a barrier on skin. Used to protect the hairline and ears during chemical services (color, relaxer) to prevent staining and irritation. Also used in pomades for shine and hold.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-7-055',
    chapter_id: 'ch-7',
    front: 'What is ammonia and why is it in hair products?',
    back: 'A strong alkali that raises pH to open the cuticle, allowing chemicals to penetrate the cortex. Used in permanent haircolor, lighteners, and some perms. Has a strong, recognizable odor. Modern products often use less-odorous alternatives like MEA.',
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-7-056',
    chapter_id: 'ch-7',
    front: 'What are alkanolamines and how do they differ from ammonia?',
    back: 'Alkanolamines raise pH and neutralize acids in hair products, similar to ammonia, but with LESS odor. Common in hair color and permanent wave solutions. Preferred by clients sensitive to ammonia smell.',
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-7-057',
    chapter_id: 'ch-7',
    front: 'What is alum and why should every barber have it?',
    back: 'A natural styptic powder that stops minor bleeding from nicks and cuts. Every barber should have alum at their station. It contracts blood vessels and tissue to seal small wounds quickly.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-7-058',
    chapter_id: 'ch-7',
    front: 'What are quats (quaternary ammonium compounds)?',
    back: 'Antiseptic and preservative compounds. The active ingredient in Barbicide and many disinfectants. Effective against bacteria and fungi. Quats work by disrupting microbial cell membranes.',
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-7-059',
    chapter_id: 'ch-7',
    front: 'What is the difference between isopropyl alcohol and ethyl alcohol in barbering?',
    back: 'Isopropyl alcohol (rubbing alcohol): 50–60% effective as skin antiseptic. Higher concentrations evaporate too quickly to disinfect properly. Ethyl alcohol (grain alcohol): used in some tonics and astringents. Both are solvents and antiseptics.',
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-7-060',
    chapter_id: 'ch-7',
    front: 'What is formaldehyde and why should barbers be cautious with it?',
    back: 'A preservative and disinfectant. Toxic and classified as carcinogenic. Found in some keratin treatments and preservatives. Use with extreme caution, ensure proper ventilation, and consider formaldehyde-free alternatives. OSHA regulates workplace exposure.',
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-7-061',
    chapter_id: 'ch-7',
    front: 'What are silicones in hair products and what do they do?',
    back: 'Breathable film-formers that coat the hair shaft. Add shine, reduce frizz, detangle, and protect from heat. Common in conditioners and serums. Can build up over time, requiring occasional clarifying shampoo use.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-7-062',
    chapter_id: 'ch-7',
    front: 'What is witch hazel and how is it used in barbering?',
    back: 'A natural astringent and skin freshener derived from a shrub. Tightens pores, soothes skin, and reduces inflammation. Common in aftershaves, toners, and skin fresheners. Gentler than alcohol-based astringents.',
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 62,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 7: SAFETY & SDS (8 cards)
  // ==========================================
  {
    id: 'fc-7-063',
    chapter_id: 'ch-7',
    front: 'What is an SDS (Safety Data Sheet) and why is it required?',
    back: 'A document that provides detailed information about a chemical product: hazards, handling, storage, first aid, firefighting, accidental release, and disposal. OSHA requires SDS sheets for all hazardous chemicals in the workplace. Every barbershop must have them accessible.',
    category: 'Safety & SDS',
    difficulty: 'medium',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-7-064',
    chapter_id: 'ch-7',
    front: 'What are the 16 sections of an SDS sheet?',
    back: '1. Identification, 2. Hazard(s), 3. Composition, 4. First-aid, 5. Fire-fighting, 6. Accidental release, 7. Handling/storage, 8. Exposure controls/PPE, 9. Physical/chemical properties, 10. Stability/reactivity, 11. Toxicology, 12. Ecology, 13. Disposal, 14. Transport, 15. Regulatory, 16. Other info.',
    category: 'Safety & SDS',
    difficulty: 'hard',
    order_index: 64,
    is_active: true,
  },
  {
    id: 'fc-7-065',
    chapter_id: 'ch-7',
    front: 'Why should you NEVER mix bleach and ammonia?',
    back: 'Mixing bleach (sodium hypochlorite) with ammonia creates toxic CHLORAMINE GAS. This gas causes severe respiratory damage, eye irritation, coughing, and can be fatal. Never mix cleaning chemicals. Read labels before combining any products.',
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-7-066',
    chapter_id: 'ch-7',
    front: 'What is a patch test and when is it required?',
    back: 'A test to check for allergic reactions before chemical services. Apply a small amount of product behind the ear or on the inner arm. Wait 24–48 hours. If no redness, swelling, or irritation occurs, proceed. Required before haircolor, relaxers, perms, and depilatories.',
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-7-067',
    chapter_id: 'ch-7',
    front: 'What PPE should be worn when handling chemicals in a barbershop?',
    back: 'Gloves (nitrile, not latex for chemicals), protective eyewear when mixing powders/liquids, apron or cape to protect clothing, and proper ventilation. Some services require a mask if fumes are strong.',
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-7-068',
    chapter_id: 'ch-7',
    front: 'What should you do if a chemical gets in a client\'s eye?',
    back: 'Immediately flush with lukewarm water for at least 15 minutes. Hold eyelids open to ensure water reaches all surfaces. Do NOT try to neutralize with another chemical. Seek medical attention after flushing. Document the incident.',
    category: 'Safety & SDS',
    difficulty: 'medium',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-7-069',
    chapter_id: 'ch-7',
    front: 'Why is proper ventilation important when using chemical products?',
    back: 'Many barbering chemicals release fumes that can cause respiratory irritation, headaches, and long-term health problems. Proper ventilation (exhaust fans, open windows, air purifiers) removes airborne chemicals and protects both barber and client.',
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-7-070',
    chapter_id: 'ch-7',
    front: 'What information must be on every professional product label?',
    back: 'Product name, manufacturer contact, ingredients (INCI names), directions for use, warnings/precautions, net contents, batch/lot number, and expiration date. Professional products should also list pH when relevant.',
    category: 'Safety & SDS',
    difficulty: 'medium',
    order_index: 70,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 8: BOARD EXAM ALERTS (10 cards)
  // ==========================================
  {
    id: 'fc-7-071',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What are the three states of matter?',
    back: 'Solid, liquid, and gas. Changes between states are PHYSICAL changes (no new substance formed). Temperature and pressure determine the state.',
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 71,
    is_active: true,
  },
  {
    id: 'fc-7-072',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What are the four types of chemical compounds?',
    back: '1. OXIDES: contain oxygen (rust, water). 2. ACIDS: release H⁺ ions, pH below 7 (vinegar, citric acid). 3. BASES (ALKALIS): release OH⁻ ions, pH above 7 (ammonia, lye). 4. SALTS: formed when acid + base neutralize (sodium chloride).',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 72,
    is_active: true,
  },
  {
    id: 'fc-7-073',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What is the chemical formula for water and what does it mean?',
    back: 'H₂O — two hydrogen atoms bonded to one oxygen atom. Water is an inorganic compound, a universal solvent, and neutral on the pH scale (pH 7).',
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 73,
    is_active: true,
  },
  {
    id: 'fc-7-074',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What happens during acid-alkali neutralization?',
    back: 'Equal proportions of acid and alkali combine to form WATER + SALT. The pH returns toward neutral. This is why neutralizing shampoo is used after alkaline chemical services — it restores acidic pH to hair.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 74,
    is_active: true,
  },
  {
    id: 'fc-7-075',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: Why do permanent waves and relaxers use alkaline products?',
    back: 'Alkaline pH (above 7) opens the cuticle and swells the cortex, allowing the reducing/relaxing chemicals to penetrate and break or rearrange disulfide bonds. Without alkalinity, the chemicals cannot reach the inner structure of the hair.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 75,
    is_active: true,
  },
  {
    id: 'fc-7-076',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What is the difference between temporary and permanent hair color in terms of chemistry?',
    back: 'Temporary color: physical change — large color molecules coat the outside of the hair shaft and wash out. Permanent color: chemical change — small molecules enter the cortex and oxidize (expand) to become trapped inside. Requires oxidation.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 76,
    is_active: true,
  },
  {
    id: 'fc-7-077',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What is the ideal pH for shampoo and why?',
    back: 'pH-balanced shampoos are around 4.5–5.5 — matching the hair\'s natural pH. This maintains the cuticle in a closed, healthy position. Alkaline shampoos (above 7) open the cuticle and can cause dryness and damage over time.',
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 77,
    is_active: true,
  },
  {
    id: 'fc-7-078',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What is a chelating agent and when is it used?',
    back: 'A chemical that binds to metal ions (like calcium, magnesium, iron) and removes them. Used in clarifying/chelating shampoos to remove mineral buildup from hard water, well water, or swimming pools. Essential before chemical services on mineral-coated hair.',
    category: 'Board Exam Alert',
    difficulty: 'hard',
    order_index: 78,
    is_active: true,
  },
  {
    id: 'fc-7-079',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What is the difference between an elemental molecule and a compound molecule?',
    back: 'Elemental molecule: two or more atoms of the SAME element (O₂ oxygen gas, O₃ ozone). Compound molecule: atoms of DIFFERENT elements chemically united (H₂O water, CO₂ carbon dioxide, NaCl salt).',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 79,
    is_active: true,
  },
  {
    id: 'fc-7-080',
    chapter_id: 'ch-7',
    front: 'BOARD EXAM: What are the key safety rules for chemical storage in a barbershop?',
    back: '1. Store in original labeled containers. 2. Keep away from heat and direct sunlight. 3. Ensure proper ventilation. 4. Separate incompatible chemicals. 5. Lock storage when unattended. 6. Check expiration dates regularly. 7. Keep SDS sheets accessible. 8. Never store food/drinks near chemicals.',
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 80,
    is_active: true,
  },
]
