import { Flashcard } from '@/types'

// Chapter 21: The Business of Barbering — 60 premium flashcards
export const chapter21PremiumFlashcards: Flashcard[] = [
  // ───────────────────────────────────────────────
  // Category: Paths Into Business and Opening Considerations (001–010)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-001',
    standardId: 'CH21-F001',
    chapter_id: 'ch-21',
    front: "What are the two main options for going into business for yourself as a barber?",
    back: "Open or acquire your own barbershop, or rent a booth/chair inside an existing shop.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch21-002',
    standardId: 'CH21-F002',
    chapter_id: 'ch-21',
    front: "What is the biggest advantage of opening your own barbershop?",
    back: "Full control over branding, pricing, culture, staff, and operations.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-ch21-003',
    standardId: 'CH21-F003',
    chapter_id: 'ch-21',
    front: "What is the biggest risk of opening your own barbershop?",
    back: "You carry all financial liability for rent, build-out, payroll, equipment, and slow periods.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch21-004',
    standardId: 'CH21-F004',
    chapter_id: 'ch-21',
    front: "Why is booth rental considered lower risk than shop ownership?",
    back: "You pay a flat rental fee and avoid the large overhead and long-term obligations of owning the entire business.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch21-005',
    standardId: 'CH21-F005',
    chapter_id: 'ch-21',
    front: "What trade-off comes with booth rental?",
    back: "You gain independence but lose control over the shop environment, brand, and some operational decisions.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-ch21-006',
    standardId: 'CH21-F006',
    chapter_id: 'ch-21',
    front: "List three factors to consider when choosing a barbershop location.",
    back: "Visibility, parking, foot traffic, target client proximity, and rent affordability.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch21-007',
    standardId: 'CH21-F007',
    chapter_id: 'ch-21',
    front: "Why should startup capital include money for operating expenses after opening?",
    back: "Most new shops take months to become profitable; reserves cover rent, payroll, and bills during slow ramp-up periods.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-ch21-008',
    standardId: 'CH21-F008',
    chapter_id: 'ch-21',
    front: "What is a staffing model?",
    back: "The way a shop structures its workers, such as employees, booth renters, or a hybrid of both.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch21-009',
    standardId: 'CH21-F009',
    chapter_id: 'ch-21',
    front: "Why does shop culture matter when opening a barbershop?",
    back: "Culture attracts the right clients, keeps barbers engaged, and shapes the daily experience inside the shop.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-ch21-010',
    standardId: 'CH21-F010',
    chapter_id: 'ch-21',
    front: "What should a barber have before moving from booth renter to shop owner?",
    back: "Capital, experience, a loyal client base, and tolerance for long-term planning and risk.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'hard',
    order_index: 10,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Types of Barbershop Ownership (011–020)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-011',
    standardId: 'CH21-F011',
    chapter_id: 'ch-21',
    front: "What is a sole proprietorship?",
    back: "A business owned by one person with no legal separation between the owner and the business.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch21-012',
    standardId: 'CH21-F012',
    chapter_id: 'ch-21',
    front: "What is the main disadvantage of a sole proprietorship?",
    back: "The owner is personally liable for all business debts and legal claims.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-ch21-013',
    standardId: 'CH21-F013',
    chapter_id: 'ch-21',
    front: "What is a partnership?",
    back: "A business owned by two or more people who share profits, responsibilities, and risks.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch21-014',
    standardId: 'CH21-F014',
    chapter_id: 'ch-21',
    front: "Why do partners need a written operating or partnership agreement?",
    back: "It defines contributions, roles, profit splits, decision-making, and exit plans to prevent disputes.",
    category: "Types of Barbershop Ownership",
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch21-015',
    standardId: 'CH21-F015',
    chapter_id: 'ch-21',
    front: "What does LLC stand for?",
    back: "Limited Liability Company.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch21-016',
    standardId: 'CH21-F016',
    chapter_id: 'ch-21',
    front: "Why is an LLC popular for independent barbershop owners?",
    back: "It protects personal assets from business liabilities while keeping paperwork manageable.",
    category: "Types of Barbershop Ownership",
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch21-017',
    standardId: 'CH21-F017',
    chapter_id: 'ch-21',
    front: "How is a corporation different from an LLC?",
    back: "A corporation is a separate legal entity owned by shareholders and involves more paperwork and stricter record-keeping requirements.",
    category: "Types of Barbershop Ownership",
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-ch21-018',
    standardId: 'CH21-F018',
    chapter_id: 'ch-21',
    front: "What is double taxation?",
    back: "Corporate profits are taxed at the business level and again as shareholder dividends unless structured to avoid it.",
    category: "Types of Barbershop Ownership",
    difficulty: 'hard',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch21-019',
    standardId: 'CH21-F019',
    chapter_id: 'ch-21',
    front: "What is a franchise?",
    back: "A licensed operation that uses an established brand name and business system in exchange for fees and royalties.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch21-020',
    standardId: 'CH21-F020',
    chapter_id: 'ch-21',
    front: "What is the main trade-off of a franchise?",
    back: "You gain brand recognition and support but sacrifice creative control and pay ongoing fees.",
    category: "Types of Barbershop Ownership",
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Business Plan Components (021–030)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-021',
    standardId: 'CH21-F021',
    chapter_id: 'ch-21',
    front: "What is a business plan?",
    back: "A written document that describes the business, market, operations, and financial projections.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch21-022',
    standardId: 'CH21-F022',
    chapter_id: 'ch-21',
    front: "Why is a business plan important even if you do not need a loan?",
    back: "It forces you to answer hard questions and think through location, costs, clients, and operations before spending money.",
    category: "Business Plan Components",
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch21-023',
    standardId: 'CH21-F023',
    chapter_id: 'ch-21',
    front: "What is the purpose of the executive summary?",
    back: "To provide a one-page overview of the business concept, market, ownership, and goals.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch21-024',
    standardId: 'CH21-F024',
    chapter_id: 'ch-21',
    front: "What should the business description include?",
    back: "Services offered, what makes the shop different, mission, vision, and guiding values.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-ch21-025',
    standardId: 'CH21-F025',
    chapter_id: 'ch-21',
    front: "What is market analysis?",
    back: "Research on competitors, target clients, pricing, and gaps the business can fill in the local market.",
    category: "Business Plan Components",
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch21-026',
    standardId: 'CH21-F026',
    chapter_id: 'ch-21',
    front: "What belongs in the organization and management section?",
    back: "Ownership structure, key people, their roles, experience, and the staffing plan.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch21-027',
    standardId: 'CH21-F027',
    chapter_id: 'ch-21',
    front: "What should the services and pricing section explain?",
    back: "The menu of services, prices, and the pricing strategy compared to competitors.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch21-028',
    standardId: 'CH21-F028',
    chapter_id: 'ch-21',
    front: "What belongs in the marketing and sales strategy?",
    back: "Target client, brand identity, advertising channels, referral programs, and grand-opening plans.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-ch21-029',
    standardId: 'CH21-F029',
    chapter_id: 'ch-21',
    front: "What are financial projections?",
    back: "Startup budget, projected income, cash-flow forecast, and break-even analysis.",
    category: "Business Plan Components",
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-ch21-030',
    standardId: 'CH21-F030',
    chapter_id: 'ch-21',
    front: "Why should financial projections be realistic rather than optimistic?",
    back: "Overly optimistic projections lead to undercapitalized shops that cannot survive slow months.",
    category: "Business Plan Components",
    difficulty: 'hard',
    order_index: 30,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Record Keeping and Booth Rental (031–040)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-031',
    standardId: 'CH21-F031',
    chapter_id: 'ch-21',
    front: "Why is record keeping important for a barber?",
    back: "It protects income, supports tax compliance, helps secure loans, and guides business decisions.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch21-032',
    standardId: 'CH21-F032',
    chapter_id: 'ch-21',
    front: "What financial records should a barber keep?",
    back: "Service revenue, tips, product sales, rent, supplies, utilities, insurance, and taxes.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch21-033',
    standardId: 'CH21-F033',
    chapter_id: 'ch-21',
    front: "What client records help improve service and protect the barber?",
    back: "Contact information, service history, product preferences, allergies, formulas, and appointment notes.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch21-034',
    standardId: 'CH21-F034',
    chapter_id: 'ch-21',
    front: "Why must income be reported even if it is paid in cash?",
    back: "Cash income is still taxable, and accurate reporting supports legal compliance and future borrowing power.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-ch21-035',
    standardId: 'CH21-F035',
    chapter_id: 'ch-21',
    front: "What business performance metrics can records reveal?",
    back: "Average ticket, client retention, retail sales per service, no-show rate, and profit margin.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-ch21-036',
    standardId: 'CH21-F036',
    chapter_id: 'ch-21',
    front: "Who is responsible for paying taxes when a barber is a booth renter?",
    back: "The booth renter is responsible for reporting income and paying self-employment taxes.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch21-037',
    standardId: 'CH21-F037',
    chapter_id: 'ch-21',
    front: "What percentage of income should a booth renter typically set aside for taxes?",
    back: "Approximately 25–30% of every dollar earned.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch21-038',
    standardId: 'CH21-F038',
    chapter_id: 'ch-21',
    front: "List three expenses a booth renter usually pays out of pocket.",
    back: "Liability insurance, tools, products, towels, sanitation supplies, and booth rent.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch21-039',
    standardId: 'CH21-F039',
    chapter_id: 'ch-21',
    front: "Why should a booth renter read the rental agreement carefully?",
    back: "It defines who provides insurance, supplies, utilities, hours, and what rules must be followed.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-ch21-040',
    standardId: 'CH21-F040',
    chapter_id: 'ch-21',
    front: "Why is building a personal client base especially important for booth renters?",
    back: "They often do not receive walk-ins from the shop and must generate their own revenue to cover rent and expenses.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 40,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Successful Barbershop Operations (041–050)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-041',
    standardId: 'CH21-F041',
    chapter_id: 'ch-21',
    front: "What is one sign of a well-run barbershop schedule?",
    back: "Clients can book easily, receive reminders, and experience minimal wait times or no-shows.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch21-042',
    standardId: 'CH21-F042',
    chapter_id: 'ch-21',
    front: "Why does cleanliness affect business success?",
    back: "A clean shop signals professionalism, safety, and respect for clients from the moment they enter.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-ch21-043',
    standardId: 'CH21-F043',
    chapter_id: 'ch-21',
    front: "How does strong customer service build a successful shop?",
    back: "It turns one-time clients into regulars who return, spend more, and refer others.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch21-044',
    standardId: 'CH21-F044',
    chapter_id: 'ch-21',
    front: "Why should roles and accountability be clearly defined in a shop?",
    back: "Ambiguity leads to missed tasks, conflict, and inconsistent client experiences.",
    category: "Successful Barbershop Operations",
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch21-045',
    standardId: 'CH21-F045',
    chapter_id: 'ch-21',
    front: "How can retail and add-on services increase shop revenue?",
    back: "They raise the average ticket per client without requiring a higher base haircut price.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch21-046',
    standardId: 'CH21-F046',
    chapter_id: 'ch-21',
    front: "What does financial discipline mean for a shop owner?",
    back: "Watching key numbers such as rent-to-revenue ratio, labor costs, retail margins, and cash flow rather than spending based on how busy the shop feels.",
    category: "Successful Barbershop Operations",
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch21-047',
    standardId: 'CH21-F047',
    chapter_id: 'ch-21',
    front: "Why is positive shop culture important?",
    back: "Clients feel the energy; drama and negativity drive away both clients and talented barbers.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch21-048',
    standardId: 'CH21-F048',
    chapter_id: 'ch-21',
    front: "What is the relationship between operations and client retention?",
    back: "Smooth operations create reliable, pleasant experiences that make clients want to return.",
    category: "Successful Barbershop Operations",
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-ch21-049',
    standardId: 'CH21-F049',
    chapter_id: 'ch-21',
    front: "What should a shop owner do when the schedule is consistently slow on certain days?",
    back: "Use targeted promotions, rebooking reminders, and incentives to fill off-peak appointments instead of cutting prices across the board.",
    category: "Successful Barbershop Operations",
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch21-050',
    standardId: 'CH21-F050',
    chapter_id: 'ch-21',
    front: "Why is it risky to spend money just because the shop appears busy?",
    back: "Busy days do not always equal profit; cash flow, expenses, and margins determine actual financial health.",
    category: "Successful Barbershop Operations",
    difficulty: 'hard',
    order_index: 50,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Advertising and Business Growth (051–060)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-051',
    standardId: 'CH21-F051',
    chapter_id: 'ch-21',
    front: "Why is advertising vital for a barbershop?",
    back: "It builds awareness, attracts ideal clients, reminds current clients to return, and differentiates the shop from competitors.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-ch21-052',
    standardId: 'CH21-F052',
    chapter_id: 'ch-21',
    front: "What happens if a skilled barber does not advertise?",
    back: "Potential clients may never know the barber exists, no matter how talented they are.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-ch21-053',
    standardId: 'CH21-F053',
    chapter_id: 'ch-21',
    front: "What is a target market?",
    back: "The specific group of clients a business aims to attract through its services, pricing, and messaging.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-ch21-054',
    standardId: 'CH21-F054',
    chapter_id: 'ch-21',
    front: "List three common advertising channels for barbershops.",
    back: "Social media, Google Business Profile, local flyers, referral cards, email or text reminders, and community partnerships.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-ch21-055',
    standardId: 'CH21-F055',
    chapter_id: 'ch-21',
    front: "Why is consistency more important than perfection in advertising?",
    back: "A small, active presence keeps the business visible; an inactive or scattered presence is quickly forgotten.",
    category: "Advertising and Business Growth",
    difficulty: 'medium',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-ch21-056',
    standardId: 'CH21-F056',
    chapter_id: 'ch-21',
    front: "Why are client reviews and referrals powerful advertising?",
    back: "They come from trust and carry more weight than paid ads because they are based on real experiences.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-ch21-057',
    standardId: 'CH21-F057',
    chapter_id: 'ch-21',
    front: "What must a barber do before posting a client photo on social media?",
    back: "Get the client's permission, preferably in writing.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-ch21-058',
    standardId: 'CH21-F058',
    chapter_id: 'ch-21',
    front: "How can partnerships with nearby businesses help advertising?",
    back: "Cross-promotion introduces the barbershop to people who already trust another local business.",
    category: "Advertising and Business Growth",
    difficulty: 'medium',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-ch21-059',
    standardId: 'CH21-F059',
    chapter_id: 'ch-21',
    front: "What is a good first step for a new barber who wants to advertise online?",
    back: "Choose one platform that matches the target client and post consistently rather than trying to be everywhere at once.",
    category: "Advertising and Business Growth",
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-ch21-060',
    standardId: 'CH21-F060',
    chapter_id: 'ch-21',
    front: "How does rebooking during a visit support business growth?",
    back: "It keeps the schedule full, increases client retention, and reduces the need for constant new-client advertising.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 60,
    is_active: true,
  },
]
