import { QuizQuestion } from '@/types'

// Chapter 19: Preparing for Licensure and Employment — 15 hardened assessment questions
// C19-4 preserves stable IDs while aligning wording and LO metadata to the
// certified seven-family Chapter 19 architecture.
export const chapter19PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-19-01',
    standardId: 'CH19-Q01',
    quiz_id: 'quiz-19',
    question: "Before scheduling a licensing exam or performing work that requires a barber license, what is the strongest first step?",
    answer_a: "Use another student's recent experience as the rule for your jurisdiction",
    answer_b: "Verify the current requirements with the applicable official licensing agency and authorized exam provider",
    answer_c: "Assume the same license and exam rules apply in every state",
    answer_d: "Begin paid services first and confirm licensing requirements later",
    correct_answer: 'b',
    explanation: "Requirements can differ by jurisdiction and can change. Verify the specific license, eligibility, application, examination, identification, and documentation requirements through the applicable official licensing agency and authorized examination provider rather than relying on informal or outdated information.",
    difficulty: 'easy',
    learningObjective: 'LO-19-01',
    order_index: 1,
  },
  {
    id: 'qq-19-02',
    standardId: 'CH19-Q02',
    quiz_id: 'quiz-19',
    question: "Which approach provides the strongest foundation for a written or theory licensing examination?",
    answer_a: "Relying mainly on test-taking tricks",
    answer_b: "Memorizing isolated answer choices without understanding the concepts",
    answer_c: "Building subject-matter understanding and using practice to identify weak areas",
    answer_d: "Choosing the longest answer when unsure",
    correct_answer: 'c',
    explanation: "Test-taking strategy can help a prepared student manage questions and time, but it does not replace understanding the material. Strong preparation uses repeated study, practice questions, and review of the underlying concepts behind missed items.",
    difficulty: 'easy',
    learningObjective: 'LO-19-02',
    order_index: 2,
  },
  {
    id: 'qq-19-03',
    standardId: 'CH19-Q03',
    quiz_id: 'quiz-19',
    question: "How should a student determine which procedures, safety steps, supplies, timing, and scoring rules apply to a practical or skills examination?",
    answer_a: "Use the procedure list from any neighboring state",
    answer_b: "Use whichever kit the student practiced with in school",
    answer_c: "Copy the format another barber remembers from a past exam",
    answer_d: "Follow the current instructions from the applicable licensing agency and authorized examination provider",
    correct_answer: 'd',
    explanation: "Practical-exam requirements are not universal. Current official instructions control the required procedures, permitted or required supplies, timing, model or mannequin rules, scoring, infection-control expectations, and other safety requirements for that jurisdiction and provider.",
    difficulty: 'medium',
    learningObjective: 'LO-19-03',
    order_index: 3,
  },
  {
    id: 'qq-19-04',
    standardId: 'CH19-Q04',
    quiz_id: 'quiz-19',
    question: "Which behavior best demonstrates professional integrity while preparing for employment?",
    answer_a: "Claiming a credential before it has been earned",
    answer_b: "Exaggerating technical ability to make the résumé stronger",
    answer_c: "Representing current skills, training, and credentials accurately",
    answer_d: "Hiding areas that still need development from every instructor",
    correct_answer: 'c',
    explanation: "Professional integrity includes being accurate about what you can do, what you are still developing, and which credentials you have actually earned. Honest self-presentation supports trust with instructors, employers, coworkers, and clients.",
    difficulty: 'easy',
    learningObjective: 'LO-19-04',
    order_index: 4,
  },
  {
    id: 'qq-19-05',
    standardId: 'CH19-Q05',
    quiz_id: 'quiz-19',
    question: "Which example best reflects a strong work ethic in barbering?",
    answer_a: "Working the longest hours possible regardless of quality",
    answer_b: "Being dependable, prepared, respectful, consistent, and accountable for the quality of your work",
    answer_c: "Accepting every service even when it exceeds your current competence or legal scope",
    answer_d: "Focusing only on technical speed and ignoring communication",
    correct_answer: 'b',
    explanation: "A strong work ethic is not simply working more hours. Dependability, preparation, respect, consistency, accountability, and quality are stronger indicators of professional work habits.",
    difficulty: 'easy',
    learningObjective: 'LO-19-04',
    order_index: 5,
  },
  {
    id: 'qq-19-06',
    standardId: 'CH19-Q06',
    quiz_id: 'quiz-19',
    question: "What is the best definition of a transferable skill?",
    answer_a: "A skill that can be transferred from one client to another during a service",
    answer_b: "A relevant skill from previous school, work, military, volunteer, or other experience that can apply to a new role",
    answer_c: "A skill that automatically appears on a barber license",
    answer_d: "A skill that is useful only inside a barbershop",
    correct_answer: 'b',
    explanation: "Transferable skills are capabilities developed in another setting that remain useful in a new role. Customer service, teamwork, scheduling, sales, communication, leadership, and cash handling can all be relevant when they truthfully describe the applicant's experience.",
    difficulty: 'easy',
    learningObjective: 'LO-19-04',
    order_index: 6,
  },
  {
    id: 'qq-19-07',
    standardId: 'CH19-Q07',
    quiz_id: 'quiz-19',
    question: "Which résumé approach best supports a quick, accurate review by a potential employer?",
    answer_a: "Use clear organization and emphasize relevant, accurate qualifications and accomplishments",
    answer_b: "Fill every available space with unrelated details",
    answer_c: "Include credentials that are still planned but not yet earned",
    answer_d: "Use vague claims instead of specific responsibilities or results",
    correct_answer: 'a',
    explanation: "There is no universal number of seconds that every employer spends on a résumé. A clear, concise structure helps relevant education, experience, current credentials, skills, and accomplishments be understood efficiently without exaggeration.",
    difficulty: 'medium',
    learningObjective: 'LO-19-05',
    order_index: 7,
  },
  {
    id: 'qq-19-08',
    standardId: 'CH19-Q08',
    quiz_id: 'quiz-19',
    question: "What is a strong purpose of a cover letter when applying for a barbering position?",
    answer_a: "To replace the résumé with a complete employment history",
    answer_b: "To identify the opportunity and connect relevant qualifications to the employer's needs",
    answer_c: "To demand a compensation amount before learning about the role",
    answer_d: "To include every detail that did not fit on the résumé",
    correct_answer: 'b',
    explanation: "A cover letter should briefly identify the opportunity, explain why the applicant is relevant to it, and invite further discussion. It should support the résumé rather than simply duplicate it.",
    difficulty: 'medium',
    learningObjective: 'LO-19-05',
    order_index: 8,
  },
  {
    id: 'qq-19-09',
    standardId: 'CH19-Q09',
    quiz_id: 'quiz-19',
    question: "Which portfolio choice best demonstrates skill while respecting professional boundaries?",
    answer_a: "Posting client photographs without permission because they show strong work",
    answer_b: "Using appropriate work samples, certificates, awards, or projects and obtaining permission before using client images",
    answer_c: "Including private client information to prove service history",
    answer_d: "Using only celebrity photos as examples of the style you hope to perform",
    correct_answer: 'b',
    explanation: "A portfolio should present appropriate evidence of skill and professional growth. Work photos, certificates, awards, and documented projects can be useful, but client images should be used only with permission and in accordance with applicable school or shop policies.",
    difficulty: 'medium',
    learningObjective: 'LO-19-05',
    order_index: 9,
  },
  {
    id: 'qq-19-10',
    standardId: 'CH19-Q10',
    quiz_id: 'quiz-19',
    question: "Which job-search approach gives a student time to compare opportunities without misrepresenting current status?",
    answer_a: "Wait until one year after licensure before researching any employer",
    answer_b: "Accept the first opening without researching the shop",
    answer_c: "Begin researching and comparing shops before graduation while accurately stating current training and licensure status",
    answer_d: "Present yourself as already licensed so employers will take the application seriously",
    correct_answer: 'c',
    explanation: "Job research can begin before graduation. Starting early can provide time to compare services, culture, expectations, compensation structure, and learning opportunities while the student remains accurate about current training and licensure status.",
    difficulty: 'medium',
    learningObjective: 'LO-19-06',
    order_index: 10,
  },
  {
    id: 'qq-19-11',
    standardId: 'CH19-Q11',
    quiz_id: 'quiz-19',
    question: "After a professional shop visit or interview, which follow-up is generally the strongest approach?",
    answer_a: "Contact the employer repeatedly until a decision is made",
    answer_b: "Use a courteous follow-up that thanks the person and respects any communication instructions they provided",
    answer_c: "Post publicly about the visit before the employer responds",
    answer_d: "Avoid all follow-up because any message appears desperate",
    correct_answer: 'b',
    explanation: "Professional follow-up can show appreciation and maintain clear communication. The exact timing and method should respect the employer's instructions and the circumstances rather than relying on one universal deadline.",
    difficulty: 'medium',
    learningObjective: 'LO-19-06',
    order_index: 11,
  },
  {
    id: 'qq-19-12',
    standardId: 'CH19-Q12',
    quiz_id: 'quiz-19',
    question: "What is the strongest way to reduce avoidable arrival problems before an interview?",
    answer_a: "Wait until the appointment time to look up the address",
    answer_b: "Confirm the date, time, location, contact person, and route in advance and allow for normal delays",
    answer_c: "Arrive extremely early without checking whether the shop is open",
    answer_d: "Assume GPS information is always current and needs no verification",
    correct_answer: 'b',
    explanation: "Interview preparation includes confirming the logistics in advance. Knowing the date, time, address, contact person, route, and realistic travel time reduces preventable delays and supports a professional arrival.",
    difficulty: 'medium',
    learningObjective: 'LO-19-06',
    order_index: 12,
  },
  {
    id: 'qq-19-13',
    standardId: 'CH19-Q13',
    quiz_id: 'quiz-19',
    question: "Which approach to interview attire and grooming is most professional?",
    answer_a: "Choose the most attention-grabbing outfit regardless of the workplace",
    answer_b: "Choose clean, professional attire and grooming appropriate to the workplace while presenting yourself comfortably and confidently",
    answer_c: "Ignore grooming because only technical skill matters",
    answer_d: "Copy another applicant's style even if it does not fit you or the setting",
    correct_answer: 'b',
    explanation: "Professional presentation should support the interview rather than distract from it. Clean attire, appropriate grooming, and awareness of the workplace help the applicant present themselves professionally without relying on one universal fashion formula.",
    difficulty: 'hard',
    learningObjective: 'LO-19-06',
    order_index: 13,
  },
  {
    id: 'qq-19-14',
    standardId: 'CH19-Q14',
    quiz_id: 'quiz-19',
    question: "If an interview question raises a concern about discrimination or a protected characteristic, what is the strongest general principle?",
    answer_a: "Assume every question about personal background is illegal everywhere",
    answer_b: "Assume an employer may ask anything during an interview",
    answer_c: "Stay professional and verify the applicable rule through an appropriate official, workforce, or qualified legal resource",
    answer_d: "Use a generic internet list as final legal authority for every jurisdiction",
    correct_answer: 'c',
    explanation: "Interview-question rules and protected categories can vary by jurisdiction and situation. A generic list should not be treated as universal law. When a question raises concern, stay professional and verify the applicable legal rule through an appropriate official, workforce, or qualified legal resource.",
    difficulty: 'hard',
    learningObjective: 'LO-19-07',
    order_index: 14,
  },
  {
    id: 'qq-19-15',
    standardId: 'CH19-Q15',
    quiz_id: 'quiz-19',
    question: "When presented with an employment, booth-rental, confidentiality, non-solicitation, or noncompete agreement, what is the most prudent action?",
    answer_a: "Sign immediately because every written provision is enforceable",
    answer_b: "Read the entire agreement, ask about unclear terms, keep a copy, and seek qualified legal advice when the consequences are significant",
    answer_c: "Ignore the written terms because verbal statements always control",
    answer_d: "Assume a restrictive clause is automatically invalid everywhere",
    correct_answer: 'b',
    explanation: "The meaning and enforceability of an agreement depend on its wording, the facts of the working relationship, and applicable law. Read the entire document, clarify unclear terms, retain a copy, and seek qualified legal advice when the consequences matter rather than assuming a clause is always valid or always invalid.",
    difficulty: 'hard',
    learningObjective: 'LO-19-07',
    order_index: 15,
  },
]
