// Chapter 16: Women's Haircutting & Styling — PREMIUM MCQ QUIZ
// 72 questions generated STRICTLY from Chapter 16 premium flashcards and curriculum
// Randomized question selection and answer order per attempt
// The Restoration Studio Certification Exam

import { QuizQuestion } from '@/types'

// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// CHAPTER 15: FULL QUESTION BANK (72 questions)
// Generated from chapter-15-premium-flashcards.ts
// NOTE: The app randomizes answer order per attempt; correct_answer tracks the text
// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const chapter16PremiumQuizQuestions: QuizQuestion[] = [
  // === TERMINOLOGY & HISTORY (4 questions) ===
  {
    id: 'qq-16-001',
    quiz_id: 'quiz-16',
    question: "What is the modern professional term for a non-surgical hair replacement product?",
    answer_a: 'Hair replacement system or hair solution',
    answer_b: 'Toupee',
    answer_c: 'Wig cap',
    answer_d: 'Hair graft',
    correct_answer: 'a',
    explanation: '"Hair replacement system" and "hair solution" are the modern professional terms. They position the service as solving a problem rather than covering a flaw, and are interchangeable on exams.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-16-002',
    quiz_id: 'quiz-16',
    question: "Why should the term 'toupee' be avoided in modern client consultations?",
    answer_a: 'It carries stigma from outdated technology and obvious appearance',
    answer_b: 'It is a trademarked term requiring licensing fees',
    answer_c: "It is only used for women's hairpieces",
    answer_d: 'It is the correct medical term for surgical implants',
    correct_answer: 'a',
    explanation: '"Toupee" carries stigma from outdated technology. Modern clients may react negatively to a term associated with unnatural, detectable hairpieces.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-16-003',
    quiz_id: 'quiz-16',
    question: "What was the original meaning of the term 'toupee'?",
    answer_a: 'The foretop — a section of natural hair grown long to blend with a wig',
    answer_b: 'A full wig covering the entire scalp',
    answer_c: 'A surgical hair implant procedure',
    answer_d: 'A type of adhesive used for attachment',
    correct_answer: 'a',
    explanation: 'The foretop was a section of natural hair grown long to blend with a wig. It evolved into the toupee of the 18th century. The term originally described the blending section, not the wig itself.',
    difficulty: 'medium',
    order_index: 3,
  },
  {
    id: 'qq-16-004',
    quiz_id: 'quiz-16',
    question: "Men's hair replacement is the second fastest-growing category in barbering. What is the first?",
    answer_a: 'Haircoloring',
    answer_b: 'Facial treatments',
    answer_c: 'Beard design',
    answer_d: 'Chemical relaxing',
    correct_answer: 'a',
    explanation: 'The thinning-hair market is the second fastest-growing category in barbering, behind only haircoloring. Specialists command premium pricing and build loyal clientele.',
    difficulty: 'easy',
    order_index: 4,
  },

  // === CONSULTATION (5 questions) ===
  {
    id: 'qq-16-005',
    quiz_id: 'quiz-16',
    question: "Where should hair replacement consultations take place?",
    answer_a: 'In a private space away from other clients',
    answer_b: 'At the front desk during check-in',
    answer_c: 'In the open shop where other barbers can advise',
    answer_d: 'Over the phone before the appointment',
    correct_answer: 'a',
    explanation: 'Consultations should take place in a private space — an office, quiet room, or at minimum when no other clients are within earshot. Never discuss hair replacement in the open shop.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-16-006',
    quiz_id: 'quiz-16',
    question: "What does the LAB MED framework stand for in hair replacement consultations?",
    answer_a: 'Lifestyle, Age, Budget, Medical history, Expectations, Daily maintenance',
    answer_b: 'Length, Angle, Base, Material, Edge, Density',
    answer_c: 'Look, Appearance, Blend, Match, Evaluate, Design',
    answer_d: 'License, Accreditation, Bonding, Measurement, Evaluation, Delivery',
    correct_answer: 'a',
    explanation: 'LAB MED stands for Lifestyle, Age, Budget, Medical history, Expectations, and Daily maintenance. These six factors guide every professional consultation.',
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-16-007',
    quiz_id: 'quiz-16',
    question: "A 68-year-old client wants jet-black hair styled like a 25-year-old celebrity. What is your professional obligation?",
    answer_a: 'Explain why the request will look unnatural and recommend a more appropriate option',
    answer_b: 'Give him exactly what he wants to keep the sale',
    answer_c: 'Refuse service and ask him to leave',
    answer_d: 'Tell him his age makes him unsuitable for any system',
    correct_answer: 'a',
    explanation: 'Giving an unrealistic system damages your reputation and the client\'s dignity. Educate with respect and recommend a more appropriate option. Never promise what you cannot deliver.',
    difficulty: 'medium',
    order_index: 7,
  },
  {
    id: 'qq-16-008',
    quiz_id: 'quiz-16',
    question: "Why is age an important factor in hair replacement consultation?",
    answer_a: 'Younger clients may want gradual transitions; older clients often prefer conservative, age-appropriate styles',
    answer_b: 'Only clients over 40 are eligible for hair replacement',
    answer_c: 'Age determines the price of the system',
    answer_d: 'Younger clients are not allowed to purchase systems',
    correct_answer: 'a',
    explanation: 'Younger clients may want gradual transitions; older clients often prefer conservative styles. Dark, opaque colors look artificial on older clients — salt-and-pepper blends look more natural.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-16-009',
    quiz_id: 'quiz-16',
    question: "A regular client says, 'I\'m starting to look like my father.' What is the most professional response?",
    answer_a: 'Acknowledge his comment and ask if he would like to discuss options in private',
    answer_b: 'Laugh and agree that baldness runs in families',
    answer_c: 'Immediately show him sample systems and pricing',
    answer_d: 'Tell him hair replacement is too expensive for his situation',
    correct_answer: 'a',
    explanation: 'You validated his concern, offered privacy, and invited further conversation without pressure. This respects his dignity while opening the door to a professional consultation.',
    difficulty: 'medium',
    order_index: 9,
  },

  // === ETHICS & MARKETING (3 questions) ===
  {
    id: 'qq-16-010',
    quiz_id: 'quiz-16',
    question: "Why must model release forms be obtained before using client photos for marketing?",
    answer_a: 'For legal protection and professional ethics; written permission is required',
    answer_b: 'It is only required for photos posted on Instagram',
    answer_c: 'Verbal permission from a friend is sufficient',
    answer_d: 'Model releases are only needed for paid advertising',
    correct_answer: 'a',
    explanation: 'Never post photos without explicit written permission. Keep release forms on file for at least three years. Friendship does not replace legal documentation.',
    difficulty: 'easy',
    order_index: 10,
  },
  {
    id: 'qq-16-011',
    quiz_id: 'quiz-16',
    question: "How should sample systems be maintained in the shop?",
    answer_a: 'Shampoo after every client who tries it on, style fresh, and replace when worn',
    answer_b: 'Leave them on a shelf for clients to examine on their own',
    answer_c: 'Only clean them once per month regardless of use',
    answer_d: 'Let clients take them home for overnight trials',
    correct_answer: 'a',
    explanation: 'The sample is a silent salesperson. Shampoo after every client who tries it on, style it fresh, and replace when it shows wear.',
    difficulty: 'easy',
    order_index: 11,
  },
  {
    id: 'qq-16-012',
    quiz_id: 'quiz-16',
    question: "Which marketing channel turns a barber who wears a hair system into a walking advertisement?",
    answer_a: 'Personal experience and word-of-mouth',
    answer_b: 'Television commercials',
    answer_c: 'Billboard advertising',
    answer_d: 'Direct mail campaigns',
    correct_answer: 'a',
    explanation: 'A barber who wears a system becomes a walking advertisement. Personal experience, social media, in-shop displays, and referrals are the most effective marketing channels.',
    difficulty: 'easy',
    order_index: 12,
  },

  // === SCOPE OF PRACTICE (4 questions) ===
  {
    id: 'qq-16-013',
    quiz_id: 'quiz-16',
    question: "Which of the following is within a barber's scope of practice regarding hair replacement?",
    answer_a: 'Measuring, fitting, cutting, styling, cleaning, and maintaining systems',
    answer_b: 'Prescribing Minoxidil for hair growth',
    answer_c: 'Diagnosing the cause of a client\'s hair loss',
    answer_d: 'Performing hair transplantation surgery',
    correct_answer: 'a',
    explanation: 'Barbers can measure, fit, cut, style, clean, and maintain hair replacement systems. They can discuss general information but must refer clients to physicians for medical advice.',
    difficulty: 'easy',
    order_index: 13,
  },
  {
    id: 'qq-16-014',
    quiz_id: 'quiz-16',
    question: "A client asks, 'Should I use 2% or 5% Minoxidil?' How should a barber respond?",
    answer_a: 'Explain that both strengths exist and refer the client to a physician',
    answer_b: 'Recommend 5% because it is stronger and works faster',
    answer_c: 'Tell him to start with 2% and increase if needed',
    answer_d: 'Say that barbers are not allowed to discuss Minoxidil at all',
    correct_answer: 'a',
    explanation: 'Barbers can provide factual information about both strengths but cannot recommend specific dosages. Always direct the client to the appropriate medical professional.',
    difficulty: 'medium',
    order_index: 14,
  },
  {
    id: 'qq-16-015',
    quiz_id: 'quiz-16',
    question: "Which action would put a barber's license at risk?",
    answer_a: 'Recommending a specific dosage of Finasteride to a client',
    answer_b: 'Cleaning a client\'s hair replacement system',
    answer_c: 'Cutting and blending a stock system',
    answer_d: 'Referring a client to a physician for medical advice',
    correct_answer: 'a',
    explanation: 'Recommending specific medication dosages crosses scope-of-practice boundaries. Barbers can discuss general information but cannot prescribe, diagnose, or recommend dosages.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-16-016',
    quiz_id: 'quiz-16',
    question: "What is the professional boundary when discussing surgical hair restoration with clients?",
    answer_a: 'Barbers can explain general options but must refer clients to physicians for surgical procedures',
    answer_b: 'Barbers can schedule surgery appointments for clients',
    answer_c: 'Barbers should discourage all surgical options as unsafe',
    answer_d: 'Barbers can perform minor scalp reduction procedures',
    correct_answer: 'a',
    explanation: 'Surgical procedures are medical only. Barbers discuss, refer, and support — never perform surgery. Crossing these boundaries puts your license at risk.',
    difficulty: 'easy',
    order_index: 16,
  },

  // === ALTERNATIVE TREATMENTS (4 questions) ===
  {
    id: 'qq-16-017',
    quiz_id: 'quiz-16',
    question: "What are the three main nonsurgical alternatives to hair replacement systems?",
    answer_a: 'Cover-up hair fibers, Minoxidil, and Finasteride',
    answer_b: 'Hair transplantation, scalp reduction, and flap surgery',
    answer_c: 'Bonding, tape attachment, and spirit gum',
    answer_d: 'Human hair, synthetic hair, and mixed hair',
    correct_answer: 'a',
    explanation: 'The three main nonsurgical alternatives are cover-up hair fibers (temporary), Minoxidil (topical FDA-approved medication), and Finasteride (oral prescription for men only).',
    difficulty: 'easy',
    order_index: 17,
  },
  {
    id: 'qq-16-018',
    quiz_id: 'quiz-16',
    question: "What is the difference between 2% and 5% Minoxidil?",
    answer_a: '2% is regular strength for men and women; 5% is extra-strength for men only',
    answer_b: '2% is for women only; 5% is for men only',
    answer_c: '2% is prescription-only; 5% is over-the-counter',
    answer_d: 'There is no difference; they are the same formula',
    correct_answer: 'a',
    explanation: '2% Minoxidil is regular strength for men and women. 5% is extra-strength for men only. It is moderately effective for about 50% of men after 4 months of consistent use.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-16-019',
    quiz_id: 'quiz-16',
    question: "What is a potential side effect of Finasteride that barbers should be aware of?",
    answer_a: 'Weight gain and loss of sexual function',
    answer_b: 'Increased hair growth on the back and shoulders',
    answer_c: 'Permanent hair color changes',
    answer_d: 'Improved eyesight and hearing',
    correct_answer: 'a',
    explanation: 'Finasteride can cause weight gain and loss of sexual function. As a prescription medication, barbers can discuss general information but must refer clients to physicians.',
    difficulty: 'medium',
    order_index: 19,
  },
  {
    id: 'qq-16-020',
    quiz_id: 'quiz-16',
    question: "What is a micrograph in modern hair transplantation?",
    answer_a: 'A small section of hair follicles used to replace large plugs',
    answer_b: 'A photograph of the scalp taken before surgery',
    answer_c: 'A type of adhesive used to attach transplanted hair',
    answer_d: 'A surgical tool for cutting the scalp',
    correct_answer: 'a',
    explanation: 'A micrograph is a small section of hair follicles used in modern transplantation techniques, replacing the large plugs of older methods. Results can last a lifetime when performed properly.',
    difficulty: 'medium',
    order_index: 20,
  },

  // === HAIR MATERIALS (5 questions) ===
  {
    id: 'qq-16-021',
    quiz_id: 'quiz-16',
    question: "What are the three main types of hair used in replacement systems?",
    answer_a: 'Human hair, synthetic hair, and mixed hair',
    answer_b: 'Straight, wavy, and curly hair',
    answer_c: 'Blonde, brunette, and red hair',
    answer_d: 'Long, medium, and short hair',
    correct_answer: 'a',
    explanation: 'The three main types are human hair, synthetic hair, and mixed hair (human blended with synthetic or animal fibers).',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-16-022',
    quiz_id: 'quiz-16',
    question: "What is Kanekalon?",
    answer_a: 'The most common synthetic fiber used in ready-to-wear wigs and hair systems',
    answer_b: 'A type of human hair sourced from Asia',
    answer_c: 'A medical adhesive for bonding systems',
    answer_d: 'A brand of hair transplantation equipment',
    correct_answer: 'a',
    explanation: 'Kanekalon is the most common synthetic fiber used in ready-to-wear wigs and hair systems. It holds style after washing, costs less than human hair, and does not oxidize or fade.',
    difficulty: 'easy',
    order_index: 22,
  },
  {
    id: 'qq-16-023',
    quiz_id: 'quiz-16',
    question: "Which is an advantage of human hair over synthetic hair in replacement systems?",
    answer_a: 'It can be permed, colored, and heat-styled for the most natural look',
    answer_b: 'It is always less expensive than synthetic hair',
    answer_c: 'It never fades or reacts to sunlight',
    answer_d: 'It requires no maintenance or styling',
    correct_answer: 'a',
    explanation: 'Human hair offers the most natural look and texture and can be permed, colored, and heat-styled. However, it reacts to humidity, fades in sunlight, and requires regular maintenance.',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'qq-16-024',
    quiz_id: 'quiz-16',
    question: "What is a disadvantage of synthetic hair in replacement systems?",
    answer_a: 'High gloss makes it more noticeable; limited chemical processing options',
    answer_b: 'It oxidizes and fades quickly in sunlight',
    answer_c: 'It cannot hold a style after washing',
    answer_d: 'It is always more expensive than human hair',
    correct_answer: 'a',
    explanation: 'Synthetic hair has high gloss that makes it more noticeable, mats and tangles when blended with human hair, and has limited chemical processing options. It does not oxidize or fade.',
    difficulty: 'easy',
    order_index: 24,
  },
  {
    id: 'qq-16-025',
    quiz_id: 'quiz-16',
    question: "What is root-turning and why is it important?",
    answer_a: 'Sorting hair so cuticles point toward the ends to prevent tangling',
    answer_b: 'Turning the hair system inside out for cleaning',
    answer_c: 'Rotating the system 180 degrees for even wear',
    answer_d: 'A technique for attaching hair to the base',
    correct_answer: 'a',
    explanation: 'Root-turning sorts hair so the cuticle points toward the ends in natural growth direction. This prevents tangling and matting because cuticles flow correctly.',
    difficulty: 'medium',
    order_index: 25,
  },

  // === BASE CONSTRUCTION (5 questions) ===
  {
    id: 'qq-16-026',
    quiz_id: 'quiz-16',
    question: "What are the five main base materials for hair replacement systems?",
    answer_a: 'Mesh/net, polyurethane, lace, thin skin, and combination',
    answer_b: 'Cotton, silk, wool, nylon, and polyester',
    answer_c: 'Metal, plastic, rubber, foam, and fabric',
    answer_d: 'Leather, suede, canvas, mesh, and vinyl',
    correct_answer: 'a',
    explanation: 'The five main base materials are mesh/net (breathable), polyurethane (waterproof), lace (invisible hairline), thin skin/onion skin (undetectable edge), and combination (strategic mix).',
    difficulty: 'easy',
    order_index: 26,
  },
  {
    id: 'qq-16-027',
    quiz_id: 'quiz-16',
    question: "What is the primary advantage of mesh or net bases?",
    answer_a: 'They are the most breathable option for all-day comfort',
    answer_b: 'They are completely waterproof for swimming',
    answer_c: 'They provide the strongest adhesive bond',
    answer_d: 'They are invisible at the hairline',
    correct_answer: 'a',
    explanation: 'Mesh/net bases are the most breathable due to open-weave construction, making them comfortable for all-day wear. Their disadvantage is that they are less durable and can stretch over time.',
    difficulty: 'easy',
    order_index: 27,
  },
  {
    id: 'qq-16-028',
    quiz_id: 'quiz-16',
    question: "What is the critical rule when working with lace-front systems?",
    answer_a: 'Never apply tape directly to lace — it will tear the delicate material',
    answer_b: 'Always use hot water when cleaning lace fronts',
    answer_c: 'Lace fronts should be trimmed with regular scissors before attachment',
    answer_d: 'Tape is the only recommended attachment method for lace',
    correct_answer: 'a',
    explanation: 'Tape tears delicate lace material. Apply bonding agent to the skin at the hairline, not to the lace itself. This is one of the most important safety rules for lace-front systems.',
    difficulty: 'easy',
    order_index: 28,
  },
  {
    id: 'qq-16-029',
    quiz_id: 'quiz-16',
    question: "Why are combination bases considered the industry standard?",
    answer_a: 'They strategically use multiple materials in different zones for optimal comfort, durability, and appearance',
    answer_b: 'They are always the least expensive option',
    answer_c: 'They require no maintenance or cleaning',
    answer_d: 'They are only available as custom-made systems',
    correct_answer: 'a',
    explanation: 'Combination bases use lace front for natural hairline, polyurethane perimeter for bonding, and mesh center for breathability — optimizing comfort, durability, and appearance.',
    difficulty: 'medium',
    order_index: 29,
  },
  {
    id: 'qq-16-030',
    quiz_id: 'quiz-16',
    question: "Which knotting method creates the most natural root appearance?",
    answer_a: 'V-loop',
    answer_b: 'Single knot',
    answer_c: 'Double knot',
    answer_d: 'Cross-stitch',
    correct_answer: 'a',
    explanation: 'V-looping creates the most natural root appearance. Single knotting is common but may loosen during cleaning. Double knotting stays secure through washing. Single hair injection makes hair appear to grow from the scalp.',
    difficulty: 'medium',
    order_index: 30,
  },

  // === STOCK VS CUSTOM (3 questions) ===
  {
    id: 'qq-16-031',
    quiz_id: 'quiz-16',
    question: "What is the main advantage of a stock hair replacement system?",
    answer_a: 'Lower cost and immediate availability',
    answer_b: 'Perfect fit from a plaster mold',
    answer_c: 'Unlimited color and style customization',
    answer_d: 'Lifetime durability guarantee',
    correct_answer: 'a',
    explanation: 'Stock systems come in standard sizes and colors, cost less, and arrive faster. They are best for clients with common head shapes, standard color needs, limited budgets, or urgent timelines.',
    difficulty: 'easy',
    order_index: 31,
  },
  {
    id: 'qq-16-032',
    quiz_id: 'quiz-16',
    question: "What is a plaster mold used for in custom system creation?",
    answer_a: 'A three-dimensional cast of the client\'s head for the most precise fit possible',
    answer_b: 'A decorative display piece for the barbershop',
    answer_c: 'A tool for mixing hair coloring products',
    answer_d: 'A weight to hold the system during cleaning',
    correct_answer: 'a',
    explanation: 'A plaster mold is a 3D cast of the client\'s head made with plaster of Paris. The manufacturer pours foam into the cast to create a permanent reusable mold for future orders.',
    difficulty: 'medium',
    order_index: 32,
  },
  {
    id: 'qq-16-033',
    quiz_id: 'quiz-16',
    question: "A client needs a system in three days for a wedding. He has a standard oval bald area and a $400 budget. What do you recommend?",
    answer_a: 'A stock system in a close color match, customized with cutting and blending',
    answer_b: 'A custom system made from a plaster mold',
    answer_c: 'Surgical hair transplantation',
    answer_d: 'Wait until after the wedding to begin the process',
    correct_answer: 'a',
    explanation: 'Stock systems are available immediately, fit the budget, and can be cut and styled to look natural for the event. Custom systems and surgery require timelines and budgets he does not have.',
    difficulty: 'medium',
    order_index: 33,
  },

  // === MEASUREMENT & TEMPLATES (3 questions) ===
  {
    id: 'qq-16-034',
    quiz_id: 'quiz-16',
    question: "How are hair replacement system sizes measured?",
    answer_a: 'In inches — length by width (e.g., 6x4 means six inches front-to-back)',
    answer_b: 'In centimeters — diameter of the bald area',
    answer_c: 'By cup size like bras (A, B, C, D)',
    answer_d: 'By weight in ounces',
    correct_answer: 'a',
    explanation: 'System sizes are measured in inches — length by width. A 6x4 piece means six inches front-to-back and four inches side-to-side. The larger number typically refers to length.',
    difficulty: 'easy',
    order_index: 34,
  },
  {
    id: 'qq-16-035',
    quiz_id: 'quiz-16',
    question: "What is the purpose of a template in custom system creation?",
    answer_a: 'A pattern of the client\'s bald area that becomes the manufacturer\'s blueprint',
    answer_b: 'A decorative stencil for applying adhesive',
    answer_c: 'A marketing brochure showing before-and-after photos',
    answer_d: 'A legal document for the client to sign',
    correct_answer: 'a',
    explanation: 'A template is created with plastic wrap and tape, marked with a grease pencil, and transferred to pattern paper. It becomes the manufacturer\'s blueprint for cutting the base to exact specifications.',
    difficulty: 'easy',
    order_index: 35,
  },
  {
    id: 'qq-16-036',
    quiz_id: 'quiz-16',
    question: "Why should barbers NOT substitute standard barber supplies for hair replacement supplies?",
    answer_a: 'The wrong adhesive damages bases and the wrong solvent ruins hair',
    answer_b: 'Standard supplies are always more expensive',
    answer_c: 'Manufacturer-recommended products are never available locally',
    answer_d: 'Clients prefer the smell of standard barber products',
    correct_answer: 'a',
    explanation: 'Always use manufacturer-recommended products for adhesives, removers, and cleaning solvents. The wrong adhesive damages bases; the wrong solvent ruins hair.',
    difficulty: 'easy',
    order_index: 36,
  },

  // === ATTACHMENT METHODS (5 questions) ===
  {
    id: 'qq-16-037',
    quiz_id: 'quiz-16',
    question: "What is full head bonding?",
    answer_a: 'Adhesive copolymer applied across the entire scalp contact area for maximum security',
    answer_b: 'Using tape only at the front hairline',
    answer_c: 'Sewing the system to the client\'s natural hair',
    answer_d: 'Clipping the system with metal barrettes',
    correct_answer: 'a',
    explanation: 'Full head bonding applies adhesive copolymer across the entire scalp contact area. It is the most secure, waterproof method — ideal for active clients who swim or exercise.',
    difficulty: 'easy',
    order_index: 37,
  },
  {
    id: 'qq-16-038',
    quiz_id: 'quiz-16',
    question: "What is the critical cure time after full head bonding?",
    answer_a: '24 to 48 hours before shampooing',
    answer_b: 'Immediately — no waiting required',
    answer_c: 'One full week',
    answer_d: 'Only 2 hours for quick-dry adhesive',
    correct_answer: 'a',
    explanation: 'The client must wait 24 to 48 hours before shampooing to allow the adhesive to fully cure. State boards frequently test this timeline.',
    difficulty: 'easy',
    order_index: 38,
  },
  {
    id: 'qq-16-039',
    quiz_id: 'quiz-16',
    question: "What is the main advantage of tape attachment over full bonding?",
    answer_a: 'Easier to remove and reattach for clients who take systems off daily',
    answer_b: 'More secure for swimming and heavy exercise',
    answer_c: 'Completely invisible at all hairlines',
    answer_d: 'Requires no maintenance or replacement',
    correct_answer: 'a',
    explanation: 'Tape attachment is easier to remove and reattach, making it good for clients who take their systems off daily. It is less secure than full bonding and may lift at edges during heavy activity.',
    difficulty: 'easy',
    order_index: 39,
  },
  {
    id: 'qq-16-040',
    quiz_id: 'quiz-16',
    question: "A competitive swimmer wants a system he never has to remove. Which attachment method do you recommend?",
    answer_a: 'Full head bonding with waterproof copolymer adhesive',
    answer_b: 'Double-sided tape at the perimeter',
    answer_c: 'Spirit gum applied daily',
    answer_d: 'Elastic bands on a full wig',
    correct_answer: 'a',
    explanation: 'Full head bonding is waterproof, secure, and designed for clients who want a permanent-wear solution during swimming and exercise.',
    difficulty: 'medium',
    order_index: 40,
  },
  {
    id: 'qq-16-041',
    quiz_id: 'quiz-16',
    question: "How is spirit gum used for facial hair pieces?",
    answer_a: 'Applied to clean, dry skin; wait until tacky; position and press gently',
    answer_b: 'Mixed with shampoo and applied to the hair',
    answer_c: 'Injected under the skin for permanent attachment',
    answer_d: 'Sprayed on as an aerosol adhesive',
    correct_answer: 'a',
    explanation: 'Spirit gum is applied to clean, dry facial skin. Wait until tacky, position the piece, and press gently with a lint-free cloth. Remove with spirit gum remover — never pull off dry.',
    difficulty: 'easy',
    order_index: 41,
  },

  // === MAINTENANCE & CLEANING (5 questions) ===
  {
    id: 'qq-16-042',
    quiz_id: 'quiz-16',
    question: "What temperature water should be used when cleaning synthetic hair systems?",
    answer_a: 'Lukewarm water only',
    answer_b: 'Hot water for deep cleaning',
    answer_c: 'Boiling water to sterilize the system',
    answer_d: 'Ice water to preserve the fibers',
    correct_answer: 'a',
    explanation: 'Hot water causes shrinkage, matting, and tangling in synthetic hair. Only lukewarm water preserves fiber integrity and style retention.',
    difficulty: 'easy',
    order_index: 42,
  },
  {
    id: 'qq-16-043',
    quiz_id: 'quiz-16',
    question: "What is the recommended maintenance schedule for hair replacement systems after the first week?",
    answer_a: 'Every three to four weeks',
    answer_b: 'Daily cleaning after each wear',
    answer_c: 'Once per year regardless of use',
    answer_d: 'Only when the system becomes visibly dirty',
    correct_answer: 'a',
    explanation: 'First cleaning after one week removes manufacturing residues. After that, clean every three to four weeks, or more frequently with heavy sweating, product use, or humid climates.',
    difficulty: 'easy',
    order_index: 43,
  },
  {
    id: 'qq-16-044',
    quiz_id: 'quiz-16',
    question: "Why should clients own at least two hair replacement systems?",
    answer_a: 'So one can be worn while the other is cleaned, dried, and serviced',
    answer_b: 'Because systems are sold only in pairs',
    answer_c: 'Two systems last twice as long when worn together',
    answer_d: 'Insurance requires a backup system',
    correct_answer: 'a',
    explanation: 'A system worn daily without rotation will deteriorate months before its expected lifespan. Two systems allow rotation so one is always available while the other is serviced.',
    difficulty: 'easy',
    order_index: 44,
  },
  {
    id: 'qq-16-045',
    quiz_id: 'quiz-16',
    question: "What does the 'O' in the COOL Rules for system care stand for?",
    answer_a: 'Only lukewarm water, never hot',
    answer_b: 'Open the windows during drying',
    answer_c: 'Oil the base after every cleaning',
    answer_d: 'Overlap the system edges when storing',
    correct_answer: 'a',
    explanation: 'COOL Rules: C — Clean with recommended solvent. O — Only lukewarm water. O — Overnight drying on a block. L — Let it dry naturally.',
    difficulty: 'medium',
    order_index: 45,
  },
  {
    id: 'qq-16-046',
    quiz_id: 'quiz-16',
    question: "How should systems be stored when not in use?",
    answer_a: 'Flat on a styling block or wig block; never folded',
    answer_b: 'Folded in half and placed in a drawer',
    answer_c: 'Hung by the hair from a hook',
    answer_d: 'Rolled up like a yoga mat',
    correct_answer: 'a',
    explanation: 'Folding creases the base and damages the hair. Always store flat on a block. Use T-pins to secure during cleaning and drying.',
    difficulty: 'easy',
    order_index: 46,
  },

  // === CHEMICAL SERVICES (3 questions) ===
  {
    id: 'qq-16-047',
    quiz_id: 'quiz-16',
    question: "What is the floating technique when perming hair systems?",
    answer_a: 'Perm rods hover above the base on roller picks to prevent indentations',
    answer_b: 'The system floats in a chemical bath during processing',
    answer_c: 'The client floats in a pool while the perm processes',
    answer_d: 'The system is suspended from the ceiling during drying',
    correct_answer: 'a',
    explanation: 'Perm rods must not rest directly on the base — the weight creates indentations. Roller picks are inserted at both ends so the rod hovers above the base like a bridge.',
    difficulty: 'medium',
    order_index: 47,
  },
  {
    id: 'qq-16-048',
    quiz_id: 'quiz-16',
    question: "Which chemical services are NEVER performed on hair replacement systems?",
    answer_a: 'Lightening (bleach) and cold-waving',
    answer_b: 'Temporary color rinses and conditioning treatments',
    answer_c: 'Shampooing and basic styling',
    answer_d: 'Bonding and tape attachment',
    correct_answer: 'a',
    explanation: 'Lightening and cold-waving destroy the base material. Use temporary color rinses only if coloring is necessary.',
    difficulty: 'easy',
    order_index: 48,
  },
  {
    id: 'qq-16-049',
    quiz_id: 'quiz-16',
    question: "What type of color product is safe to use on hair replacement systems?",
    answer_a: 'Temporary color rinses only',
    answer_b: 'Permanent haircolor with ammonia',
    answer_c: 'Bleach and lightening powder',
    answer_d: 'Any salon-quality haircolor',
    correct_answer: 'a',
    explanation: 'Temporary color rinses are the only safe coloring option. Lightening (bleach) and cold-waving destroy the base material.',
    difficulty: 'easy',
    order_index: 49,
  },

  // === CUTTING & BLENDING (4 questions) ===
  {
    id: 'qq-16-050',
    quiz_id: 'quiz-16',
    question: "At what elevation is the top section of a hair system cut?",
    answer_a: '90 degrees using clipper-over-comb or fingers-and-shear',
    answer_b: '45 degrees for maximum layering',
    answer_c: '180 degrees for extreme volume',
    answer_d: '0 degrees for a blunt cut',
    correct_answer: 'a',
    explanation: 'The top section is cut at 90-degree elevation using clipper-over-comb or fingers-and-shear, working forward from crown to forehead for seamless transitions.',
    difficulty: 'medium',
    order_index: 50,
  },
  {
    id: 'qq-16-051',
    quiz_id: 'quiz-16',
    question: "What is slide cutting and why is it essential for blending?",
    answer_a: 'The shear slides through hair at an angle to create a feathered, tapered edge',
    answer_b: 'Cutting the hair while sliding the system across the client\'s head',
    answer_c: 'Using a sliding scale to determine the price of the cut',
    answer_d: 'A technique for sliding the system onto the scalp',
    correct_answer: 'a',
    explanation: 'Slide cutting creates a feathered, tapered edge that disappears into natural hair. It is essential for making the transition between system and natural hair invisible.',
    difficulty: 'medium',
    order_index: 51,
  },
  {
    id: 'qq-16-052',
    quiz_id: 'quiz-16',
    question: "What is the golden rule when customizing stock systems?",
    answer_a: 'Be conservative — you can always cut more, but you cannot put hair back',
    answer_b: 'Remove as much hair as possible for a lightweight feel',
    answer_c: 'Always cut the system to the shortest requested length immediately',
    answer_d: 'Use thinning shears on the entire system for uniform density',
    correct_answer: 'a',
    explanation: 'Cutting too much is the number one regret. Remove excess length gradually, taper sides to match natural hairlines, and thin heavy areas with narrow partings.',
    difficulty: 'easy',
    order_index: 52,
  },
  {
    id: 'qq-16-053',
    quiz_id: 'quiz-16',
    question: "Why should thinning shears be used with narrow partings near the base?",
    answer_a: 'Wide partings create visible gaps that ruin the finished appearance',
    answer_b: 'Narrow partings speed up the cutting process',
    answer_c: 'Wide partings are only for experienced barbers',
    answer_d: 'Narrow partings prevent the client from feeling the shears',
    correct_answer: 'a',
    explanation: 'Wide partings create visible gaps that ruin the blend. Narrow partings allow controlled bulk removal without creating holes in the finished appearance.',
    difficulty: 'medium',
    order_index: 53,
  },

  // === SAFETY (2 questions) ===
  {
    id: 'qq-16-054',
    quiz_id: 'quiz-16',
    question: "Why must dull blades be replaced during system customization?",
    answer_a: 'Dull blades pull hair, causing damage and uneven cuts on expensive systems',
    answer_b: 'Sharp blades are required by state law for all haircuts',
    answer_c: 'Dull blades make the cutting process faster',
    answer_d: 'Clients can hear the difference between sharp and dull blades',
    correct_answer: 'a',
    explanation: 'Dull blades pull hair, causing damage to the system and creating uneven cuts. Sharp tools are essential for clean, precise work on expensive systems.',
    difficulty: 'easy',
    order_index: 54,
  },
  {
    id: 'qq-16-055',
    quiz_id: 'quiz-16',
    question: "What is the number one regret barbers have when customizing stock systems?",
    answer_a: 'Cutting too much during initial customization',
    answer_b: 'Not cutting enough and leaving the system too heavy',
    answer_c: 'Using the wrong type of adhesive',
    answer_d: 'Failing to obtain a model release',
    correct_answer: 'a',
    explanation: 'Be conservative — remove length gradually. You can always cut more, but you cannot put hair back.',
    difficulty: 'easy',
    order_index: 55,
  },

  // === BOARD EXAM TRAPS (5 questions) ===
  {
    id: 'qq-16-056',
    quiz_id: 'quiz-16',
    question: "Board Exam Trap: A barber can recommend a specific dosage of Minoxidil to a client.",
    answer_a: 'False — only physicians can recommend dosages',
    answer_b: 'True — barbers are trained in pharmacology',
    answer_c: 'True — but only for the 2% formula',
    answer_d: 'False — barbers cannot discuss Minoxidil at all',
    correct_answer: 'a',
    explanation: 'Only physicians can recommend medication dosages. Barbers can discuss general information and refer clients to medical professionals.',
    difficulty: 'easy',
    order_index: 56,
  },
  {
    id: 'qq-16-057',
    quiz_id: 'quiz-16',
    question: "Board Exam Trap: Hot water cleans synthetic hair systems more effectively than lukewarm water.",
    answer_a: 'False — hot water causes shrinkage and matting in synthetic hair',
    answer_b: 'True — hot water dissolves oils better',
    answer_c: 'True — but only for Kanekalon fiber',
    answer_d: 'False — cold water is required for all cleaning',
    correct_answer: 'a',
    explanation: 'Hot water causes shrinkage, matting, and tangling in synthetic hair. Only lukewarm water should be used for cleaning.',
    difficulty: 'easy',
    order_index: 57,
  },
  {
    id: 'qq-16-058',
    quiz_id: 'quiz-16',
    question: "Board Exam Trap: Double-sided tape can be applied directly to lace-front systems.",
    answer_a: 'False — tape tears delicate lace material',
    answer_b: 'True — tape is the recommended method for lace fronts',
    answer_c: 'True — but only medical-grade tape',
    answer_d: 'False — tape is never used on any system type',
    correct_answer: 'a',
    explanation: 'Tape tears delicate lace material. Adhesive should be applied to the skin at the hairline, never to the lace itself.',
    difficulty: 'easy',
    order_index: 58,
  },
  {
    id: 'qq-16-059',
    quiz_id: 'quiz-16',
    question: "Board Exam Trap: A client can shampoo immediately after full head bonding.",
    answer_a: 'False — the client must wait 24 to 48 hours for the adhesive to cure',
    answer_b: 'True — modern adhesives cure instantly',
    answer_c: 'True — but only with sulfate-free shampoo',
    answer_d: 'False — the client must wait one full week',
    correct_answer: 'a',
    explanation: 'The client must wait 24 to 48 hours before shampooing to allow the adhesive to fully cure. This is one of the most frequently tested facts on state board exams.',
    difficulty: 'easy',
    order_index: 59,
  },
  {
    id: 'qq-16-060',
    quiz_id: 'quiz-16',
    question: "Board Exam Trap: A barber can perform hair transplantation surgery if certified.",
    answer_a: 'False — surgical procedures are medical only, regardless of certification',
    answer_b: 'True — with a special barbering endorsement',
    answer_c: 'True — but only scalp reduction, not full transplantation',
    answer_d: 'False — but barbers can assist in the operating room',
    correct_answer: 'a',
    explanation: 'Surgical procedures are medical only. No barber certification authorizes surgery. Barbers discuss, refer, and support — never perform surgery.',
    difficulty: 'easy',
    order_index: 60,
  },

  // === SCENARIO-BASED APPLICATION (4 questions) ===
  {
    id: 'qq-16-061',
    quiz_id: 'quiz-16',
    question: "A client with a wool allergy wants a mixed-hair system. What should the barber do?",
    answer_a: 'Recommend a keratin fiber alternative and avoid wool-based systems',
    answer_b: 'Assure him that wool allergies do not affect hair systems',
    answer_c: 'Suggest he take allergy medication before each wear',
    answer_d: 'Tell him mixed hair is his only option',
    correct_answer: 'a',
    explanation: 'Some mixed fibers use wool bases that can trigger allergic reactions. Clients with wool allergies need keratin fiber alternatives.',
    difficulty: 'medium',
    order_index: 61,
  },
  {
    id: 'qq-16-062',
    quiz_id: 'quiz-16',
    question: "A client wants his human hair system lightened to match his summer highlights. What is the correct response?",
    answer_a: 'Explain that lightening destroys the base and recommend temporary color rinses instead',
    answer_b: 'Proceed with bleach using a 20-volume developer',
    answer_c: 'Refer him to a colorist who specializes in system lightening',
    answer_d: 'Tell him human hair systems cannot be colored at all',
    correct_answer: 'a',
    explanation: 'Lightening (bleach) and cold-waving destroy the base material. Use temporary color rinses only if coloring is necessary.',
    difficulty: 'medium',
    order_index: 62,
  },
  {
    id: 'qq-16-063',
    quiz_id: 'quiz-16',
    question: "A client asks why his synthetic system looks shinier than his previous human hair system. How do you explain?",
    answer_a: 'Synthetic fiber has a natural high gloss that makes it more noticeable than human hair',
    answer_b: 'The system was cleaned with the wrong temperature water',
    answer_c: 'He is using too much styling product',
    answer_d: 'The manufacturer applied a protective coating that will wear off',
    correct_answer: 'a',
    explanation: 'Synthetic hair has high gloss that makes it more noticeable. This is a characteristic of the fiber, not a defect or maintenance error.',
    difficulty: 'medium',
    order_index: 63,
  },
  {
    id: 'qq-16-064',
    quiz_id: 'quiz-16',
    question: "A new client wants the most natural-looking, undetectable system possible regardless of cost. What combination of choices best meets his needs?",
    answer_a: 'Custom system with human hair, lace front, and professional blending',
    answer_b: 'Stock system with synthetic hair and tape attachment',
    answer_c: 'Full wig with Kanekalon fiber and elastic bands',
    answer_d: 'Pre-custom system with mixed hair and full bonding only',
    correct_answer: 'a',
    explanation: 'Custom systems fit perfectly, human hair looks most natural, lace front creates an invisible hairline, and professional blending erases the boundary between system and natural hair.',
    difficulty: 'hard',
    order_index: 64,
  },

  // === MEMORY ANCHORS & KEY CONCEPTS (3 questions) ===
  {
    id: 'qq-16-065',
    quiz_id: 'quiz-16',
    question: "What does the memory anchor 'LAB MED' help barbers remember?",
    answer_a: 'The six factors to cover in every hair replacement consultation',
    answer_b: 'The five main base construction materials',
    answer_c: 'The four primary attachment methods',
    answer_d: 'The three types of hair used in systems',
    correct_answer: 'a',
    explanation: 'LAB MED stands for Lifestyle, Age, Budget, Medical history, Expectations, and Daily maintenance — the six factors that guide every professional consultation.',
    difficulty: 'easy',
    order_index: 65,
  },
  {
    id: 'qq-16-066',
    quiz_id: 'quiz-16',
    question: "In the 'Hovering Helicopters' memory anchor for floating perm rods, what represents the landing gear?",
    answer_a: 'Roller picks',
    answer_b: 'Perm rods',
    answer_c: 'The base material',
    answer_d: "The client's head",
    correct_answer: 'a',
    explanation: 'The rod is the helicopter, the base is the landing pad, and the roller picks are the landing gear. The helicopter hovers above the pad to avoid crushing it.',
    difficulty: 'medium',
    order_index: 66,
  },
  {
    id: 'qq-16-067',
    quiz_id: 'quiz-16',
    question: "What is the most important principle that separates an obvious hairpiece from an undetectable system?",
    answer_a: 'Blending — the transition between system hair and natural hair must be invisible',
    answer_b: 'Using only human hair, never synthetic',
    answer_c: 'Applying the most expensive adhesive available',
    answer_d: 'Choosing a stock system over a custom system',
    correct_answer: 'a',
    explanation: 'Blending is what makes a system undetectable. Slide cutting, proper thinning, and careful tapering create the illusion that all hair is natural.',
    difficulty: 'easy',
    order_index: 67,
  },

  // === HARD QUESTIONS — COMPREHENSIVE APPLICATION (3 questions) ===
  {
    id: 'qq-16-068',
    quiz_id: 'quiz-16',
    question: "A client has been wearing a bonded system for two weeks and complains of itching and redness at the hairline. He admits he shampooed the system after 12 hours because he had a date. What is the most likely cause and correct action?",
    answer_a: 'The adhesive did not fully cure; remove the system, clean the scalp, and reapply after the scalp heals',
    answer_b: 'He is allergic to human hair; switch to synthetic fiber immediately',
    answer_c: 'The shampoo was too mild; recommend a stronger clarifying shampoo',
    answer_d: 'This is normal for new wearers; tell him to wait another week',
    correct_answer: 'a',
    explanation: 'Shampooing before the 24-48 hour cure time prevents proper adhesion and can trap moisture against the scalp, causing irritation. The system must be removed, the scalp cleaned and allowed to heal, and the system re-bonded properly.',
    difficulty: 'hard',
    order_index: 68,
  },
  {
    id: 'qq-16-069',
    quiz_id: 'quiz-16',
    question: "A barber is customizing a stock system for a client. The top looks bulky, the sides are too long, and the back extends past the natural hairline. In what order should the barber proceed?",
    answer_a: 'Thin the top with narrow partings, taper the sides with slide cutting, then blend the back with thinning shears',
    answer_b: 'Cut the back first to establish length, then the top, then the sides',
    answer_c: 'Remove all bulk from the top first with clippers at zero guard',
    answer_d: 'Style the system first to see how it falls, then make adjustments',
    correct_answer: 'a',
    explanation: 'The correct order: thin heavy top areas with narrow partings and thinning shears, taper sides to match natural hairlines with slide cutting, then blend the back. Be conservative — you can always cut more.',
    difficulty: 'hard',
    order_index: 69,
  },
  {
    id: 'qq-16-070',
    quiz_id: 'quiz-16',
    question: "A client considering hair replacement asks about all his options. He has early-stage thinning, a limited budget, and is nervous about commitment. Which recommendation sequence best follows professional consultation protocol?",
    answer_a: 'Discuss cover-up fibers and Minoxidil first, then introduce stock systems, and mention custom systems as a future option',
    answer_b: 'Immediately recommend a custom system as the only professional solution',
    answer_c: 'Tell him to wait until his hair loss is more advanced before considering any option',
    answer_d: 'Recommend surgical transplantation as the most cost-effective long-term solution',
    correct_answer: 'a',
    explanation: 'A professional consultation presents ALL options from least to most commitment: temporary fibers, topical medications, stock systems, and eventually custom systems. This follows the LAB MED framework and respects the client\'s budget and nervousness.',
    difficulty: 'hard',
    order_index: 70,
  },

  // === KEY TAKEAWAYS (2 questions) ===
  {
    id: 'qq-16-071',
    quiz_id: 'quiz-16',
    question: "What are barbers actually selling when they provide hair replacement services?",
    answer_a: 'The reflection the client wants to see — confidence and self-image restoration',
    answer_b: 'Hair fibers and base materials at a markup',
    answer_c: 'A medical procedure that requires physician supervision',
    answer_d: 'A temporary cosmetic cover-up',
    correct_answer: 'a',
    explanation: 'Clients are not buying hair — they are buying the man they used to see in the mirror. The barber\'s job is to deliver that reflection with honesty, skill, and care.',
    difficulty: 'easy',
    order_index: 71,
  },
  {
    id: 'qq-16-072',
    quiz_id: 'quiz-16',
    question: "Why is knowledge of scope of practice particularly critical for barbers offering hair replacement?",
    answer_a: 'State boards frequently test boundaries between barber services and medical services',
    answer_b: 'Scope of practice only applies to haircutting, not hair replacement',
    answer_c: 'Barbers have unlimited scope for all hair-related services',
    answer_d: 'Scope violations only result in warnings, not license loss',
    correct_answer: 'a',
    explanation: 'State boards frequently test what barbers can do (fit, cut, maintain) versus cannot do (prescribe, diagnose, perform surgery). Knowing these boundaries protects your license and your client\'s health.',
    difficulty: 'easy',
    order_index: 72,
  },
]

export default chapter16PremiumQuizQuestions
