import { Flashcard } from '@/types'

// Chapter 14: Men's Haircutting and Styling
// Created strictly from Chapter 14 V1 HTML content
// Board-exam focused, clear front/back format

export const chapter14PremiumFlashcards: Flashcard[] = [
  // === INTRODUCTION ===
  {
    id: 'fc-ch14-001',
    chapter_id: 'ch-14',
    front: 'Why is haircutting considered the foundation of barbering?',
    back: 'Haircutting is the core skill that defines a barber. It allows you to create customized haircuts, understand facial shapes, master various techniques and tools, build a loyal client base, and increase revenue through styling and additional services.',
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch14-002',
    chapter_id: 'ch-14',
    front: 'What are the benefits of mastering men\'s haircutting and styling?',
    back: 'Create customized haircuts for each client, understand facial shapes and how to complement them, master various cutting techniques and tools, build a loyal client base through quality work, and increase revenue through styling and additional services.',
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },

  // === CLIENT CONSULTATION ===
  {
    id: 'fc-ch14-003',
    chapter_id: 'ch-14',
    front: 'Why is the client consultation the foundation of a successful haircut?',
    back: 'Understanding what the client wants prevents misunderstandings, builds trust, and ensures the final result meets expectations.',
    category: 'Consultation',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch14-004',
    chapter_id: 'ch-14',
    front: 'What are five key questions to ask during a client consultation?',
    back: '1) What would you like done today? 2) How short do you want it? 3) Do you want a fade, taper, or all one length? 4) How do you usually style your hair? 5) Do you have any cowlicks or growth patterns I should know about?',
    category: 'Consultation',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch14-005',
    chapter_id: 'ch-14',
    front: 'Why should you always clarify when a client says "just a trim"?',
    back: 'A trim means different things to different people. Always show exactly how much hair will be removed, use fingers or a comb to demonstrate length, and confirm before cutting.',
    category: 'Consultation',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },

  // === FACIAL SHAPES ===
  {
    id: 'fc-ch14-006',
    chapter_id: 'ch-14',
    front: 'What are the five basic facial shapes?',
    back: 'Oval, round, square, inverted triangular (heart), and pear-shaped (triangular).',
    category: 'Facial Shapes',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch14-007',
    chapter_id: 'ch-14',
    front: 'Which facial shape is considered the ideal shape?',
    back: 'Oval face — it has balanced proportions with similar width of forehead and jaw, and the face is longer than it is wide.',
    category: 'Facial Shapes',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-ch14-008',
    chapter_id: 'ch-14',
    front: 'What is the design goal for a round face?',
    back: 'Add height and minimize width. Avoid styles that add volume to the sides.',
    category: 'Facial Shapes',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch14-009',
    chapter_id: 'ch-14',
    front: 'What is the design goal for a square face?',
    back: 'Soften angles while maintaining masculine features. Avoid too much volume on top.',
    category: 'Facial Shapes',
    difficulty: 'easy',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-ch14-010',
    chapter_id: 'ch-14',
    front: 'What is the design goal for an inverted triangular (heart) face?',
    back: 'Add width at the jawline and minimize forehead width. Styles with volume on the sides work well.',
    category: 'Facial Shapes',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-ch14-011',
    chapter_id: 'ch-14',
    front: 'What is the design goal for a pear-shaped (triangular) face?',
    back: 'Add width at the temples and minimize jaw width. Styles with volume on top work well.',
    category: 'Facial Shapes',
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch14-012',
    chapter_id: 'ch-14',
    front: 'What are the five design principles in haircutting?',
    back: 'Balance (visual equilibrium), Proportion (pleasing ratio), Emphasis (draw attention to best features), Rhythm (movement and flow), and Harmony (all elements work together).',
    category: 'Design Principles',
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },

  // === BASIC TECHNIQUES ===
  {
    id: 'fc-ch14-013',
    chapter_id: 'ch-14',
    front: 'What is clipper-over-comb?',
    back: 'Using clippers over a comb to create precise, clean lines and gradual fades.',
    category: 'Techniques',
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch14-014',
    chapter_id: 'ch-14',
    front: 'What is shear-over-comb?',
    back: 'Using shears over a comb for softer, more blended results than clippers.',
    category: 'Techniques',
    difficulty: 'easy',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch14-015',
    chapter_id: 'ch-14',
    front: 'What is freehand clipper technique?',
    back: 'Using clippers without a comb for outlining and detail work.',
    category: 'Techniques',
    difficulty: 'easy',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch14-016',
    chapter_id: 'ch-14',
    front: 'What is blending in haircutting?',
    back: 'Creating smooth transitions between different lengths.',
    category: 'Techniques',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch14-017',
    chapter_id: 'ch-14',
    front: 'What is fading in haircutting?',
    back: 'Gradually tapering hair from short to shorter or to skin.',
    category: 'Techniques',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },

  // === PREPARATION ===
  {
    id: 'fc-ch14-018',
    chapter_id: 'ch-14',
    front: 'What are the six preparation steps for all haircuts?',
    back: '1) Wash hands thoroughly. 2) Conduct client consultation. 3) Drape client for wet service. 4) Shampoo and towel dry hair. 5) Remove waterproof cape; replace with neck strip and haircutting cape. 6) Face client toward mirror and lock chair.',
    category: 'Preparation',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },

  // === HAIRCUTTING PROCEDURES ===
  {
    id: 'fc-ch14-019',
    chapter_id: 'ch-14',
    front: 'What is the first step in a basic clipper haircut?',
    back: 'Determine the desired length on top.',
    category: 'Procedures',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch14-020',
    chapter_id: 'ch-14',
    front: 'What tool is used for a shadow fade cut?',
    back: 'An adjustable-blade clipper with and without guards.',
    category: 'Procedures',
    difficulty: 'easy',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-ch14-021',
    chapter_id: 'ch-14',
    front: 'What is the key difference between cutting with the grain and against the grain?',
    back: 'Cutting against the grain achieves a closer cut than cutting with the grain.',
    category: 'Procedures',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch14-022',
    chapter_id: 'ch-14',
    front: 'What is the first step in creating a pompadour fade?',
    back: 'Re-dampen the top section with water if necessary, then part off the top section following the curve of the head at the parietal ridge.',
    category: 'Procedures',
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },

  // === BLOWDRYING ===
  {
    id: 'fc-ch14-023',
    chapter_id: 'ch-14',
    front: 'What are the four blowdrying techniques?',
    back: 'Freeform blowdrying, stylized blowdrying, blow waving, and diffused drying.',
    category: 'Blowdrying',
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch14-024',
    chapter_id: 'ch-14',
    front: 'How far should the dryer be held from the hair during freeform blowdrying?',
    back: '6 to 10 inches from the hair.',
    category: 'Blowdrying',
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-ch14-025',
    chapter_id: 'ch-14',
    front: 'What is the purpose of blow waving?',
    back: 'To create lift or direction in the top section by forming a ridge or bend to set the style.',
    category: 'Blowdrying',
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch14-026',
    chapter_id: 'ch-14',
    front: 'When is diffused drying used?',
    back: 'For curly or textured hair — it dries hair while maintaining natural curl pattern and volume.',
    category: 'Blowdrying',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },

  // === HEAD SHAVE ===
  {
    id: 'fc-ch14-027',
    chapter_id: 'ch-14',
    front: 'What should be examined before performing a head shave?',
    back: 'The scalp should be examined for abrasions, lesions, or disorders.',
    category: 'Head Shave',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch14-028',
    chapter_id: 'ch-14',
    front: 'How many steamed-towel treatments are recommended before shaving the head?',
    back: 'Two or three steamed-towel treatments to soften the hair.',
    category: 'Head Shave',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-ch14-029',
    chapter_id: 'ch-14',
    front: 'In what direction should you shave the head?',
    back: 'With the grain, from crown to nape and from crown to front hairline.',
    category: 'Head Shave',
    difficulty: 'easy',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-ch14-030',
    chapter_id: 'ch-14',
    front: 'What is applied after a head shave to soothe the skin?',
    back: 'Witch hazel or skin toner, followed by a cool-towel application for 2-3 minutes, then moisturizing cream or oil.',
    category: 'Head Shave',
    difficulty: 'easy',
    order_index: 30,
    is_active: true,
  },

  // === CORNROW BRAIDING ===
  {
    id: 'fc-ch14-031',
    chapter_id: 'ch-14',
    front: 'What are cornrows?',
    back: 'Narrow rows of visible braids that lie close to the scalp.',
    category: 'Cornrows',
    difficulty: 'easy',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch14-032',
    chapter_id: 'ch-14',
    front: 'What is the braiding pattern for cornrows?',
    back: 'Cross left strand under center strand, then cross right strand under center strand. With each crossing under, pick up hair from the base of the panel and add to the outer strand before crossing under center.',
    category: 'Cornrows',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch14-033',
    chapter_id: 'ch-14',
    front: 'How are cornrow ends secured?',
    back: 'With small rubber bands.',
    category: 'Cornrows',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },

  // === CLEAN-UP ===
  {
    id: 'fc-ch14-034',
    chapter_id: 'ch-14',
    front: 'What should be done with used blades after a haircut?',
    back: 'Deposit them in a sharps container — never in regular trash or on the counter.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-ch14-035',
    chapter_id: 'ch-14',
    front: 'What are the eight steps of post-service clean-up?',
    back: '1) Clean and disinfect all tools. 2) Clean and disinfect work area. 3) Clean surfaces and chair. 4) Sweep up hair and deposit in closed receptacle. 5) Deposit used blades in sharps container. 6) Dispose of single-use items. 7) Place used linens in laundry. 8) Wash hands thoroughly.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 35,
    is_active: true,
  },

  // === BOARD EXAM FOCUS ===
  {
    id: 'fc-ch14-036',
    chapter_id: 'ch-14',
    front: 'Why is it important to lock the chair during a haircut?',
    back: 'To prevent movement and ensure client safety during the service.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch14-037',
    chapter_id: 'ch-14',
    front: 'What is the purpose of a neck strip?',
    back: 'To provide a sanitary barrier between the client\'s neck and the haircutting cape.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch14-038',
    chapter_id: 'ch-14',
    front: 'Why should you face the client toward the mirror during a haircut?',
    back: 'So the client can see the progress and provide feedback during the consultation and service.',
    category: 'Consultation',
    difficulty: 'easy',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch14-039',
    chapter_id: 'ch-14',
    front: 'What is cross-checking in haircutting?',
    back: 'Checking the haircut from multiple angles and directions to ensure evenness and proper blending.',
    category: 'Techniques',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-ch14-040',
    chapter_id: 'ch-14',
    front: 'What is the parietal ridge?',
    back: 'The curved area of the head where the sides meet the top — an important reference point for sectioning and blending.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-ch14-041',
    chapter_id: 'ch-14',
    front: 'What is the occipital area?',
    back: 'The back and base of the head, below the crown and above the nape.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch14-042',
    chapter_id: 'ch-14',
    front: 'What is the nape?',
    back: 'The lowest part of the neck where the hairline meets the neck.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-ch14-043',
    chapter_id: 'ch-14',
    front: 'What is the crown?',
    back: 'The highest point on the top of the head, where hair growth patterns often radiate outward.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch14-044',
    chapter_id: 'ch-14',
    front: 'What is overdirection in haircutting?',
    back: 'Combing hair away from its natural fall position before cutting to create weight distribution or layering.',
    category: 'Techniques',
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch14-045',
    chapter_id: 'ch-14',
    front: 'What is a guide in haircutting?',
    back: 'A section of hair that is cut to the desired length and used as a reference for cutting subsequent sections.',
    category: 'Techniques',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch14-046',
    chapter_id: 'ch-14',
    front: 'What is the purpose of outlining with a trimmer?',
    back: 'To create clean, sharp lines around the hairline, sideburns, and neck for a polished finish.',
    category: 'Techniques',
    difficulty: 'easy',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch14-047',
    chapter_id: 'ch-14',
    front: 'What is the difference between a fade and a taper?',
    back: 'A fade blends hair from short to skin with no visible lines. A taper gradually changes length but typically leaves more length and may show subtle lines.',
    category: 'Techniques',
    difficulty: 'medium',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch14-048',
    chapter_id: 'ch-14',
    front: 'Why is it important to maintain even tension when braiding cornrows?',
    back: 'Uneven tension can cause discomfort, hair breakage, or an inconsistent appearance.',
    category: 'Cornrows',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-ch14-049',
    chapter_id: 'ch-14',
    front: 'What is the purpose of applying essential oil before cornrow braiding?',
    back: 'To moisturize the scalp, reduce friction, and add shine to the finished braids.',
    category: 'Cornrows',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch14-050',
    chapter_id: 'ch-14',
    front: 'What should be done if a client has a scalp disorder before a head shave?',
    back: 'Do not proceed with the shave. Refer the client to a medical professional.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 50,
    is_active: true,
  },
]
