import { QuizQuestion } from '@/types'

// Chapter 18: Haircoloring and Lightening — 15 premium quiz questions
export const chapter18PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-18-01',
    standardId: 'CH18-Q01',
    quiz_id: 'quiz-18',
    question: "Which six characteristics must be analyzed before performing a haircoloring service?",
    answer_a: "Texture, density, length, curl pattern, oiliness, and scalp condition",
    answer_b: "Elasticity, texture, density, porosity, natural hair color, and contributing pigment",
    answer_c: "Diameter, length, moisture, shine, strength, and growth phase",
    answer_d: "Cuticle health, cortex size, medulla presence, pH, oil level, and hydration",
    correct_answer: 'b',
    explanation: "Common mistake: Picking hair traits that are easy to see, such as length, curl pattern, oiliness, or scalp condition, instead of the six traits that control how color behaves. Correct understanding: Before coloring hair, check these six traits in this order: elasticity, texture, density, porosity, natural hair color, and contributing pigment. These tell you how strong the hair is, how fast it will absorb color, and what undertone may show through. Why it matters: If you skip porosity or elasticity, you may choose the wrong product strength. Porous or weak hair can process too dark, uneven, or even break during the service. Review: Identify the Characteristics and Structure of Hair (pp. 642\u2013644).",
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-18-02',
    standardId: 'CH18-Q02',
    quiz_id: 'quiz-18',
    question: "Which type of melanin is responsible for black and brown pigment in natural hair?",
    answer_a: "Pheomelanin",
    answer_b: "Eumelanin",
    answer_c: "Oxymelanin",
    answer_d: "Keratinin",
    correct_answer: 'b',
    explanation: "Common mistake: Mixing up eumelanin and pheomelanin, often choosing pheomelanin for black and brown hair. Correct understanding: Eumelanin gives hair black and brown pigment. Pheomelanin gives hair yellow, blond, and red pigment. Think 'Eu' for earthy, dark tones. Why it matters: Knowing the natural pigment helps you predict what color will appear when you lighten hair. Dark hair lifts through red and orange stages because of its eumelanin content. Review: Identify the Characteristics and Structure of Hair (pp. 644).",
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-18-03',
    standardId: 'CH18-Q03',
    quiz_id: 'quiz-18',
    question: "On the haircolor level system, which numbers represent the darkest and lightest extremes?",
    answer_a: "0 is black and 12 is lightest blond",
    answer_b: "1 is black and 10 is the lightest blond",
    answer_c: "1 is lightest blond and 10 is black",
    answer_d: "5 is black and 15 is pale yellow",
    correct_answer: 'b',
    explanation: "Common mistake: Reversing the level scale and thinking 1 is lightest and 10 is darkest. Correct understanding: On the level system, 1 is the darkest (black) and 10 is the lightest (blond). Lower numbers mean darker hair; higher numbers mean lighter hair. Why it matters: Reading the scale backward leads to choosing the opposite color level. You could color a client much darker or lighter than they wanted. Review: Understand Color Theory (pp. 646).",
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-18-04',
    standardId: 'CH18-Q04',
    quiz_id: 'quiz-18',
    question: "Temporary haircolor is best described as which of the following?",
    answer_a: "A deposit-only color that penetrates the cortex and lasts six to eight shampoos",
    answer_b: "An oxidation color mixed with developer that lasts until the hair grows out",
    answer_c: "A coating of large color molecules on the outside of the cuticle that shampoos out easily",
    answer_d: "A small-molecule color that stains the cuticle and slightly penetrates the cortex",
    correct_answer: 'c',
    explanation: "Common mistake: Thinking temporary color works like semipermanent color and stains or penetrates the hair shaft. Correct understanding: Temporary haircolor uses large dye molecules that only coat the outside of the cuticle. It does not penetrate the cortex and usually washes out with the next shampoo. Why it matters: If you promise a temporary rinse will last weeks, the client will be upset when it washes out after one shampoo. Match the product to the client's expectations. Review: Identify Haircoloring Products (pp. 649, 651).",
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-18-05',
    standardId: 'CH18-Q05',
    quiz_id: 'quiz-18',
    question: "Which developer volume is considered the standard for many permanent haircolor products and gray coverage?",
    answer_a: "10-volume",
    answer_b: "20-volume",
    answer_c: "30-volume",
    answer_d: "40-volume",
    correct_answer: 'b',
    explanation: "Common mistake: Choosing a stronger developer, such as 40-volume, thinking it is the standard for all permanent color or gray coverage. Correct understanding: 20-volume developer is the standard for many permanent haircolor products and for covering gray. It usually gives one to two levels of lift. Higher volumes are used only when more lift is needed. Why it matters: Using 30- or 40-volume as a default can over-process hair, cause scalp irritation, and create brassy or uneven color. Always choose volume based on the amount of lift needed. Review: Identify Haircoloring Products (pp. 656).",
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-18-06',
    standardId: 'CH18-Q06',
    quiz_id: 'quiz-18',
    question: "A client lightens her hair to level 7 and sees unwanted orange tones. Which base color should be chosen to neutralize the orange?",
    answer_a: "Gold base",
    answer_b: "Red-orange base",
    answer_c: "Blue base",
    answer_d: "Yellow base",
    correct_answer: 'c',
    explanation: "Common mistake: Choosing a warm base color such as gold or red-orange to fix orange tones, which actually makes the warmth stronger. Correct understanding: Colors opposite each other on the color wheel neutralize each other. Blue is opposite orange, so a blue-based color will cancel unwanted orange tones at the correct level. Why it matters: Adding gold to orange hair will make it look even brassier. Choosing the correct complementary base gives the client the cool, clean tone they asked for. Review: Understand Color Theory (pp. 645\u2013647).",
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-18-07',
    standardId: 'CH18-Q07',
    quiz_id: 'quiz-18',
    question: "When tinting very porous hair darker with a single-process permanent color, which formulation choice is most appropriate?",
    answer_a: "Choose a color one to two levels lighter than the desired result",
    answer_b: "Choose a color one to two levels darker than the desired result",
    answer_c: "Use 40-volume developer to ensure even penetration",
    answer_d: "Skip the patch test because porous hair processes quickly",
    correct_answer: 'a',
    explanation: "Common mistake: Choosing a darker color for very porous hair because the ends look faded, thinking the extra darkness will even things out. Correct understanding: Very porous hair grabs color and can look darker than intended. Choose a color one to two levels lighter than the desired result so the final color matches the target shade. Why it matters: If you pick a darker formula, porous ends may turn almost black while the regrowth stays lighter. The client ends up with muddy, uneven color. Review: Understand Product Selection and Application (pp. 668\u2013669).",
    difficulty: 'medium',
    order_index: 7,
  },
  {
    id: 'qq-18-08',
    standardId: 'CH18-Q08',
    quiz_id: 'quiz-18',
    question: "A client with 50 percent gray wants complete, long-lasting gray coverage. Which product classification is generally the best choice?",
    answer_a: "Temporary color rinse",
    answer_b: "Semipermanent color",
    answer_c: "Demipermanent color",
    answer_d: "Permanent haircolor",
    correct_answer: 'd',
    explanation: "Common mistake: Choosing demipermanent color for 50 percent gray because it can blend some gray, thinking it will give full coverage. Correct understanding: Demipermanent color only covers up to about 50 percent gray and fades. Permanent haircolor is generally the best choice for complete, long-lasting gray coverage. Why it matters: If you use demipermanent color on 50 percent gray, the client may see uneven coverage and need frequent touch-ups. Permanent color gives reliable, lasting results. Review: Identify Haircoloring Products (pp. 654).",
    difficulty: 'medium',
    order_index: 8,
  },
  {
    id: 'qq-18-09',
    standardId: 'CH18-Q09',
    quiz_id: 'quiz-18',
    question: "During a lightener retouch service, where should the lightener be applied?",
    answer_a: "From scalp to ends on all hair",
    answer_b: "Only to the new growth, avoiding overlap on previously lightened hair",
    answer_c: "Only to the ends to refresh brightness",
    answer_d: "To the scalp first, then immediately pulled through to the ends",
    correct_answer: 'b',
    explanation: "Common mistake: Applying lightener from scalp to ends on every retouch, or pulling it through the ends to refresh brightness. Correct understanding: During a lightener retouch, apply lightener only to the new growth. Avoid overlapping onto previously lightened hair, which is already fragile and can over-process. Why it matters: Overlap causes breakage, severe dryness, and a visible band of damage. Keeping product on new growth only protects the previously lightened hair and gives an even result. Review: Understand Procedure and Application Terms (pp. 662, 669\u2013670).",
    difficulty: 'medium',
    order_index: 9,
  },
  {
    id: 'qq-18-10',
    standardId: 'CH18-Q10',
    quiz_id: 'quiz-18',
    question: "A client wants dark hair lightened several levels and then finished with a pale ash tone. Which service approach is required?",
    answer_a: "Single-process haircoloring",
    answer_b: "Double-process haircoloring",
    answer_c: "A temporary color rinse",
    answer_d: "A soap cap only",
    correct_answer: 'b',
    explanation: "Common mistake: Trying to lighten dark hair several levels and finish with a pale ash tone in one single-process application. Correct understanding: Lightening dark hair several levels and then adding a pale ash tone takes two steps: first lighten, then apply a toner or tint. This is called double-process haircoloring. Why it matters: A single-process color cannot lift dark hair light enough for a pale ash tone. Attempting it in one step wastes product and leaves the client with brassy or dark results. Review: Understand Procedure and Application Terms (pp. 662\u2013663).",
    difficulty: 'medium',
    order_index: 10,
  },
  {
    id: 'qq-18-11',
    standardId: 'CH18-Q11',
    quiz_id: 'quiz-18',
    question: "A demipermanent color service differs from a semipermanent color service mainly because demipermanent color must be:",
    answer_a: "Applied to pre-lightened hair only",
    answer_b: "Mixed with a low-volume developer right before use",
    answer_c: "Shampooed out after five minutes",
    answer_d: "Used without a patch test",
    correct_answer: 'b',
    explanation: "Common mistake: Thinking demipermanent color can be used without a patch test because it is deposit-only. Correct understanding: Demipermanent color lasts longer than semipermanent color because it must be mixed with a low-volume developer before use. Because it contains aniline derivative, it still requires a patch test. Why it matters: Skipping a required patch test can cause an allergic reaction. Demipermanent color is not risk-free just because it does not lift hair. Review: Identify Haircoloring Products (pp. 653, 668).",
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-18-12',
    standardId: 'CH18-Q12',
    quiz_id: 'quiz-18',
    question: "How far in advance must a patch test be performed before applying a product containing aniline derivative?",
    answer_a: "Immediately before the service",
    answer_b: "15 to 30 minutes before the service",
    answer_c: "24 to 48 hours before the service",
    answer_d: "One week before the service",
    correct_answer: 'c',
    explanation: "Common mistake: Doing the patch test right before the service, or 15 to 30 minutes before, because the client is in a hurry. Correct understanding: A patch test for aniline derivative products must be done 24 to 48 hours before the service. This gives the skin time to show an allergic reaction. Why it matters: An allergic reaction can cause burns, swelling, blistering, or scarring. The law requires the 24- to 48-hour wait to keep clients safe. Never skip or shorten this time. Review: Identify Haircoloring Products (pp. 650, 661).",
    difficulty: 'hard',
    order_index: 12,
  },
  {
    id: 'qq-18-13',
    standardId: 'CH18-Q13',
    quiz_id: 'quiz-18',
    question: "Which statement about coloring mustaches and beards is correct?",
    answer_a: "Aniline derivative tints may be used if the skin is protected with petroleum jelly",
    answer_b: "Only metallic dyes should be used because they are gentle on facial skin",
    answer_c: "Only products made specifically for facial hair coloring should be used, and aniline derivative tints are contraindicated",
    answer_d: "Facial hair can be lightened with any off-the-scalp powder lightener",
    correct_answer: 'c',
    explanation: "Common mistake: Thinking aniline derivative tints are safe for facial hair if the skin is protected with petroleum jelly. Correct understanding: Do not use aniline derivative tints or metallic dyes on mustaches or beards. Use only products made specifically for facial hair coloring. Why it matters: Facial skin is more sensitive than scalp skin. Aniline derivative tints on facial hair can cause serious irritation, chemical burns, or allergic reactions. Review: Procedure 18-8: Coloring Mustaches and Beards (pp. 674, 698).",
    difficulty: 'hard',
    order_index: 13,
  },
  {
    id: 'qq-18-14',
    standardId: 'CH18-Q14',
    quiz_id: 'quiz-18',
    question: "What is the proper action if a plastic bottle of hydrogen peroxide develops a bulge?",
    answer_a: "Open it carefully and use it immediately",
    answer_b: "Transfer it to a metal container for storage",
    answer_c: "Discard it because oxygen pressure has built up inside",
    answer_d: "Dilute it with water to reduce the pressure",
    correct_answer: 'c',
    explanation: "Common mistake: Opening or using a bulging hydrogen peroxide bottle right away to avoid waste. Correct understanding: A bulging plastic bottle means oxygen has escaped and pressure has built up inside. Throw the bottle away. Do not open or use it. Why it matters: Opening a bulging bottle can cause it to burst or spray chemical into your eyes and skin. It also means the peroxide has lost strength and will not process correctly. Review: Identify Haircoloring Products (pp. 656).",
    difficulty: 'hard',
    order_index: 14,
  },
  {
    id: 'qq-18-15',
    standardId: 'CH18-Q15',
    quiz_id: 'quiz-18',
    question: "A client with previously lightened, overporous hair wants to tint back to her natural darker shade. The ends tend to grab color and look darker than the regrowth. What corrective step should be taken first?",
    answer_a: "Apply 40-volume developer to lift the dark ends before tinting",
    answer_b: "Use a temporary color rinse instead of a tint",
    answer_c: "Apply a color filler to equalize porosity and create a uniform color base",
    answer_d: "Skip the patch test because the hair is already processed",
    correct_answer: 'c',
    explanation: "Common mistake: Trying to fix overporous ends by applying more lightener or using a darker color, instead of treating the porosity first. Correct understanding: Apply a color filler first to equalize porosity and create a uniform color base. This prevents the ends from grabbing too much color and turning darker than the regrowth. Why it matters: Without a filler, tinted back hair can look patchy and dark on the ends. In severe cases, overporous hair may also break if it is stressed with more chemicals. Review: Understand Hair Lighteners (pp. 660, 662, 668).",
    difficulty: 'hard',
    order_index: 15,
  },
]