// Chapter 11: Treatment of the Hair and Scalp — source-grounded assessment
// C11-4 preserves stable question IDs/order while hardening source scope,
// distractors, answer positions, explanations, and application difficulty.

import { QuizQuestion } from '@/types'

export const chapter11PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-11-001',
    quiz_id: 'quiz-11',
    question: 'What is the primary purpose of a shampoo service in Chapter 11?',
    answer_a: 'To change the natural wave pattern before cutting',
    answer_b: 'To cleanse the hair and scalp as part of service preparation',
    answer_c: 'To replace the need for hair and scalp analysis',
    answer_d: 'To prepare every client for a chemical service',
    correct_answer: 'b',
    explanation: 'Chapter 11 treats shampooing as cleansing the hair and scalp with a suitable product as part of safe service preparation.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-11-002',
    quiz_id: 'quiz-11',
    question: 'A client is being prepared for a wet service. Which draping choice best matches Chapter 11?',
    answer_a: 'Use a dry haircutting cape because it is lighter',
    answer_b: 'Skip the cape if the service will be brief',
    answer_c: 'Use a waterproof shampoo cape and protect the client from liquids',
    answer_d: 'Use only a towel because capes are for chemical services',
    correct_answer: 'c',
    explanation: 'Chapter 11 distinguishes waterproof shampoo capes for wet or chemical services from haircutting capes used for dry services.',
    difficulty: 'hard',
    order_index: 2,
  },
  {
    id: 'qq-11-003',
    quiz_id: 'quiz-11',
    question: 'What material does Chapter 11 associate with haircutting capes?',
    answer_a: 'Nylon or another synthetic material',
    answer_b: 'Absorbent cotton only',
    answer_c: 'Waterproof vinyl only',
    answer_d: 'Paper only',
    correct_answer: 'a',
    explanation: 'The Chapter 11 source summary describes haircutting capes as nylon or synthetic.',
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-11-004',
    quiz_id: 'quiz-11',
    question: 'Why is correct draping important during wet or chemical services?',
    answer_a: 'It guarantees the service will take less time',
    answer_b: 'It prevents the need for consultation',
    answer_c: 'It allows stronger products to be used',
    answer_d: 'It helps protect the client\'s skin and clothing from liquids or chemicals',
    correct_answer: 'd',
    explanation: 'Chapter 11 identifies protection of the client\'s skin and clothing as a central purpose of draping.',
    difficulty: 'medium',
    order_index: 4,
  },
  {
    id: 'qq-11-005',
    quiz_id: 'quiz-11',
    question: 'What are the two shampooing and rinsing methods described in Chapter 11?',
    answer_a: 'Reclined and inclined',
    answer_b: 'Dry and wet',
    answer_c: 'Cold and warm',
    answer_d: 'Standing and seated',
    correct_answer: 'a',
    explanation: 'The two methods are the reclined method and the inclined method.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-11-006',
    quiz_id: 'quiz-11',
    question: 'Which statement correctly describes the reclined shampoo method?',
    answer_a: 'The client bends forward over the bowl',
    answer_b: 'It is reserved only for clients with disabilities',
    answer_c: 'It is the most common method and is used with a reclining or hydraulic chair',
    answer_d: 'It is performed without a shampoo bowl',
    correct_answer: 'c',
    explanation: 'Chapter 11 identifies the reclined method as the most common shampoo method and associates it with a shampoo bowl and reclining or hydraulic chair.',
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-11-007',
    quiz_id: 'quiz-11',
    question: 'What should the barber do when a wheelchair-bound or disabled client needs shampooing?',
    answer_a: 'Require the reclined method',
    answer_b: 'Ask how the client can be positioned safely and comfortably',
    answer_c: 'Automatically use the inclined method',
    answer_d: 'Skip the shampoo service',
    correct_answer: 'b',
    explanation: 'Chapter 11 emphasizes adapting the shampoo service to the client\'s needs and comfort.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-11-008',
    quiz_id: 'quiz-11',
    question: 'During a shampoo service, water runs onto the client\'s face and the barber scrapes the scalp with the nails. How should this be evaluated?',
    answer_a: 'Both actions are acceptable if the shampoo is mild',
    answer_b: 'Only the face wetting is a service fault',
    answer_c: 'Only the scalp scraping is a service fault',
    answer_d: 'Both are service faults identified in Chapter 11',
    correct_answer: 'd',
    explanation: 'The source lists face wetting and scraping the scalp among common shampoo-service faults.',
    difficulty: 'hard',
    order_index: 8,
  },
  {
    id: 'qq-11-009',
    quiz_id: 'quiz-11',
    question: 'What should happen before shampoo water is applied to the client?',
    answer_a: 'The water should be made as hot as the barber can tolerate',
    answer_b: 'The client should select the water temperature without testing',
    answer_c: 'The water temperature should be tested for client comfort',
    answer_d: 'The water should alternate between hot and cold',
    correct_answer: 'c',
    explanation: 'Chapter 11 specifically includes proper water-temperature testing in shampoo preparation.',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-11-010',
    quiz_id: 'quiz-11',
    question: 'Which body-position guideline is supported for the barber during shampooing?',
    answer_a: 'Keep one foot raised throughout the service',
    answer_b: 'Maintain balanced posture with the feet parallel',
    answer_c: 'Lean across the client to shorten the reach',
    answer_d: 'Keep the knees locked and shoulders elevated',
    correct_answer: 'b',
    explanation: 'The Chapter 11 source summary identifies posture, balance, and parallel feet as barber-positioning considerations.',
    difficulty: 'easy',
    order_index: 10,
  },
  {
    id: 'qq-11-011',
    quiz_id: 'quiz-11',
    question: 'What should occur before product selection and treatment setup?',
    answer_a: 'Consultation and hair/scalp analysis',
    answer_b: 'Scalp steam',
    answer_c: 'Electric massage',
    answer_d: 'Hair tonic application',
    correct_answer: 'a',
    explanation: 'Chapter 11 places consultation and hair/scalp analysis before product and treatment selection.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-11-012',
    quiz_id: 'quiz-11',
    question: 'A client has limited mobility and is uncomfortable in the usual shampoo position. What is the best Chapter 11 response?',
    answer_a: 'Continue the usual method because consistency matters most',
    answer_b: 'Skip all cleansing services',
    answer_c: 'Choose the position that is fastest for the barber',
    answer_d: 'Adapt the shampoo method to the client\'s safe and comfortable positioning needs',
    correct_answer: 'd',
    explanation: 'Chapter 11 includes special-needs shampooing and supports individualized attention, comfort, and safe positioning.',
    difficulty: 'hard',
    order_index: 12,
  },
  {
    id: 'qq-11-013',
    quiz_id: 'quiz-11',
    question: 'Which group contains the analysis factors Chapter 11 uses before product selection?',
    answer_a: 'Hair color, haircut shape, age, height, and service price',
    answer_b: 'Condition, texture, density, porosity, elasticity, and scalp findings',
    answer_c: 'Brand preference, fragrance, package size, price, and season',
    answer_d: 'Face shape, eye color, beard length, and clothing style',
    correct_answer: 'b',
    explanation: 'Chapter 11 directs the barber to analyze hair/scalp condition, texture, density, porosity, elasticity, and relevant abrasions or disorders.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-11-014',
    quiz_id: 'quiz-11',
    question: 'Which product match is supported for fine hair?',
    answer_a: 'Heavy leave-in conditioner as the primary match',
    answer_b: 'Only strong clarifying products',
    answer_c: 'Volumizing shampoo, detangling conditioner, and protein treatments',
    answer_d: 'No conditioner or treatment products',
    correct_answer: 'c',
    explanation: 'The Chapter 11 product table pairs fine hair with volumizing shampoo, detangling conditioner, and protein treatments.',
    difficulty: 'medium',
    order_index: 14,
  },
  {
    id: 'qq-11-015',
    quiz_id: 'quiz-11',
    question: 'Which product direction is supported for medium hair?',
    answer_a: 'pH-balanced products',
    answer_b: 'Only protein treatments',
    answer_c: 'Only leave-in conditioner',
    answer_d: 'Only deep moisturizing treatments',
    correct_answer: 'a',
    explanation: 'The Chapter 11 product table pairs medium hair with pH-balanced products.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-11-016',
    quiz_id: 'quiz-11',
    question: 'Which product match is supported for coarse hair?',
    answer_a: 'Volumizing shampoo only',
    answer_b: 'Protein treatment only',
    answer_c: 'Dry shampoo only',
    answer_d: 'Moisturizing products and leave-in conditioners',
    correct_answer: 'd',
    explanation: 'The Chapter 11 product table pairs coarse hair with moisturizing products and leave-in conditioners.',
    difficulty: 'medium',
    order_index: 16,
  },
  {
    id: 'qq-11-017',
    quiz_id: 'quiz-11',
    question: 'A client has dry, damaged hair. Which product direction best matches Chapter 11?',
    answer_a: 'Use aggressive cleansing and avoid conditioning',
    answer_b: 'Use gentle cleansing with deep moisturizing and protein/moisturizing repair options',
    answer_c: 'Use the same product plan as oily hair',
    answer_d: 'Skip analysis and choose by fragrance',
    correct_answer: 'b',
    explanation: 'The source table pairs dry/damaged hair with gentle cleansing, deep moisturizing, and protein/moisturizing repair treatments.',
    difficulty: 'hard',
    order_index: 17,
  },
  {
    id: 'qq-11-018',
    quiz_id: 'quiz-11',
    question: 'What are the three scalp-massage manipulations identified in Chapter 11?',
    answer_a: 'Tapping, pinching, and pulling',
    answer_b: 'Kneading, percussion, and vibration',
    answer_c: 'Rotary, sliding, and back-and-forth',
    answer_d: 'Pressing, rolling, and stretching',
    correct_answer: 'c',
    explanation: 'Chapter 11 identifies rotary, sliding, and back-and-forth movements.',
    difficulty: 'easy',
    order_index: 18,
  },
  {
    id: 'qq-11-019',
    quiz_id: 'quiz-11',
    question: 'Which description best matches a rotary scalp-massage movement?',
    answer_a: 'Straight downward strokes with the palms',
    answer_b: 'Rapid tapping with the fingertips',
    answer_c: 'Hair pulling followed by release',
    answer_d: 'Overlapping circular movement with thumbs or fingertips',
    correct_answer: 'd',
    explanation: 'The source describes rotary massage as overlapping circular movement performed with the thumbs or fingertips.',
    difficulty: 'medium',
    order_index: 19,
  },
  {
    id: 'qq-11-020',
    quiz_id: 'quiz-11',
    question: 'Which description best matches a sliding scalp-massage movement?',
    answer_a: 'Repeated tapping with the knuckles',
    answer_b: 'Gliding strokes with the thumbs or fingertips',
    answer_c: 'Circular movement without travel',
    answer_d: 'Pulling sections of hair away from the scalp',
    correct_answer: 'b',
    explanation: 'The source describes sliding massage as gliding strokes made with the thumbs or fingertips.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'qq-11-021',
    quiz_id: 'quiz-11',
    question: 'Which description best matches the back-and-forth manipulation?',
    answer_a: 'Brisk back-and-forth movement with moderate to firm pressure',
    answer_b: 'Slow tapping with no pressure',
    answer_c: 'Hair pulling in alternating directions',
    answer_d: 'A single circular movement at the crown',
    correct_answer: 'a',
    explanation: 'Chapter 11 describes back-and-forth massage as a brisk movement with the thumbs or fingertips using moderate to firm pressure.',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-11-022',
    quiz_id: 'quiz-11',
    question: 'Where should Chapter 11 scalp-massage manipulations begin?',
    answer_a: 'At the crown',
    answer_b: 'Behind the ears',
    answer_c: 'At the hairline',
    answer_d: 'At the nape only',
    correct_answer: 'c',
    explanation: 'The source directs the barber to start at the hairline and use even, continuous, synchronized movement.',
    difficulty: 'medium',
    order_index: 22,
  },
  {
    id: 'qq-11-023',
    quiz_id: 'quiz-11',
    question: 'Which technique best follows the Chapter 11 massage guidelines?',
    answer_a: 'Use abrupt movement and pull the hair for leverage',
    answer_b: 'Use slow rhythmic motion, controlled pressure, and avoid pulling the hair',
    answer_c: 'Keep pressure very light regardless of the manipulation',
    answer_d: 'Use only one hand so movement stays isolated',
    correct_answer: 'b',
    explanation: 'Chapter 11 emphasizes slow, rhythmic movement, controlled pressure, hands under the hair, and avoiding pulling.',
    difficulty: 'medium',
    order_index: 23,
  },
  {
    id: 'qq-11-024',
    quiz_id: 'quiz-11',
    question: 'While massaging from behind the ears toward the crown, which movement choice matches the Chapter 11 table?',
    answer_a: 'Back-and-forth only',
    answer_b: 'Sliding only',
    answer_c: 'Tapping followed by pulling',
    answer_d: 'Rotary and sliding movements',
    correct_answer: 'd',
    explanation: 'The Chapter 11 massage table assigns rotary and sliding movements to the area behind the ears toward the crown.',
    difficulty: 'hard',
    order_index: 24,
  },
  {
    id: 'qq-11-025',
    quiz_id: 'quiz-11',
    question: 'What is the general purpose of hair and scalp treatments in Chapter 11?',
    answer_a: 'To preserve the health and appearance of the hair and scalp',
    answer_b: 'To diagnose medical scalp disease',
    answer_c: 'To guarantee new hair growth',
    answer_d: 'To replace consultation and analysis',
    correct_answer: 'a',
    explanation: 'The source describes hair and scalp treatments as helping preserve health and appearance and address routine treatment concerns within barbering scope.',
    difficulty: 'easy',
    order_index: 25,
  },
  {
    id: 'qq-11-026',
    quiz_id: 'quiz-11',
    question: 'What two principles does Chapter 11 identify as essential for hair and scalp treatment?',
    answer_a: 'Heat and chemical action',
    answer_b: 'Cutting and styling',
    answer_c: 'Cleanliness and stimulation',
    answer_d: 'Color and texture change',
    correct_answer: 'c',
    explanation: 'The source identifies cleanliness and stimulation as essential treatment principles.',
    difficulty: 'easy',
    order_index: 26,
  },
  {
    id: 'qq-11-027',
    quiz_id: 'quiz-11',
    question: 'Which condition does Chapter 11 associate with dry scalp?',
    answer_a: 'Overactive sebaceous glands',
    answer_b: 'Reduced activity of the oil glands',
    answer_c: 'Excessive scalp steam',
    answer_d: 'Frequent use of a hot towel',
    correct_answer: 'b',
    explanation: 'The Chapter 11 source summary associates dry scalp with inactivity or reduced activity of the oil glands.',
    difficulty: 'medium',
    order_index: 27,
  },
  {
    id: 'qq-11-028',
    quiz_id: 'quiz-11',
    question: 'Which condition does Chapter 11 associate with oily scalp?',
    answer_a: 'Reduced oil-gland activity',
    answer_b: 'Lack of hair density',
    answer_c: 'Low elasticity',
    answer_d: 'Overactive sebaceous glands',
    correct_answer: 'd',
    explanation: 'The source associates oily scalp with overactive sebaceous glands.',
    difficulty: 'medium',
    order_index: 28,
  },
  {
    id: 'qq-11-029',
    quiz_id: 'quiz-11',
    question: 'Which organism does the Chapter 11 source summary associate with dandruff?',
    answer_a: 'Malassezia',
    answer_b: 'Staphylococcus',
    answer_c: 'A parasitic mite',
    answer_d: 'A bacterial condition unrelated to dandruff',
    correct_answer: 'a',
    explanation: 'The repository Chapter 11 source summary associates dandruff with Malassezia.',
    difficulty: 'easy',
    order_index: 29,
  },
  {
    id: 'qq-11-030',
    quiz_id: 'quiz-11',
    question: 'A client has persistent flaking and irritation. Which response best preserves the Chapter 11 barbering boundary?',
    answer_a: 'Diagnose the exact scalp disorder and prescribe treatment',
    answer_b: 'Promise the condition will resolve after massage',
    answer_c: 'Observe the condition, make only cosmetic service decisions, and refer when the concern is outside scope',
    answer_d: 'Use a stronger product until the symptoms disappear',
    correct_answer: 'c',
    explanation: 'Chapter 11 supports observation and cosmetic service decisions, not medical diagnosis or treatment. Referral is appropriate when the concern falls outside barbering scope.',
    difficulty: 'hard',
    order_index: 30,
  },
  {
    id: 'qq-11-031',
    quiz_id: 'quiz-11',
    question: 'Why should abrasions or disorders be noted during pre-treatment analysis?',
    answer_a: 'They determine the haircut length',
    answer_b: 'They can affect whether the planned cosmetic service is safe or appropriate',
    answer_c: 'They determine which cape color should be used',
    answer_d: 'They eliminate the need for consultation',
    correct_answer: 'b',
    explanation: 'Chapter 11 includes abrasions and disorders in pre-service analysis because they can change the service decision.',
    difficulty: 'medium',
    order_index: 31,
  },
  {
    id: 'qq-11-032',
    quiz_id: 'quiz-11',
    question: 'Which set consists entirely of services or equipment Chapter 11 includes in hair/scalp treatment?',
    answer_a: 'Hair coloring, permanent waving, nail care, and shaving',
    answer_b: 'Surgical removal, prescription medication, scalp injection, and massage',
    answer_c: 'Haircutting, beard design, waxing, and chemical relaxing',
    answer_d: 'Suitable shampooing, scalp steam, hand/electric massage, and source-listed light/current equipment',
    correct_answer: 'd',
    explanation: 'The source includes cleansing with suitable shampoo, scalp steam, hand or electrical massage, infrared/ultraviolet lamps or high-frequency current, and cosmetic antiseptics or ointments.',
    difficulty: 'medium',
    order_index: 32,
  },
  {
    id: 'qq-11-033',
    quiz_id: 'quiz-11',
    question: 'What is a source-supported purpose of scalp steam?',
    answer_a: 'To permanently alter the hair structure',
    answer_b: 'To remove all scalp oil',
    answer_c: 'To prepare the scalp for massage/treatment by softening scalp and hair and increasing circulation',
    answer_d: 'To diagnose scalp disorders',
    correct_answer: 'c',
    explanation: 'Chapter 11 describes scalp steam as preparation for massage and treatment; it softens the scalp and hair and increases circulation.',
    difficulty: 'easy',
    order_index: 33,
  },
  {
    id: 'qq-11-034',
    quiz_id: 'quiz-11',
    question: 'What may be used as a substitute for a scalp steamer?',
    answer_a: 'A hot towel or a series of hot-towel applications',
    answer_b: 'A cold compress only',
    answer_c: 'A dry cape',
    answer_d: 'A blow dryer at maximum heat',
    correct_answer: 'a',
    explanation: 'Chapter 11 states that hot towels prepared in a hot-towel cabinet or hot water may substitute for a scalp steamer.',
    difficulty: 'easy',
    order_index: 34,
  },
  {
    id: 'qq-11-035',
    quiz_id: 'quiz-11',
    question: 'How should an electric massager be positioned before use?',
    answer_a: 'In the palm with the fingers closed around it',
    answer_b: 'On the back of the hand so the thumb and fingers remain free',
    answer_c: 'At the wrist with the fingers immobilized',
    answer_d: 'Against the scalp before the intensity is adjusted',
    correct_answer: 'b',
    explanation: 'The source directs the barber to adjust the electric massager on the back of the hand, leaving the thumb and fingers free.',
    difficulty: 'easy',
    order_index: 35,
  },
  {
    id: 'qq-11-036',
    quiz_id: 'quiz-11',
    question: 'Which variables require control when using an electric massager?',
    answer_a: 'Hair length, hair color, and cape type',
    answer_b: 'Shampoo brand, bowl height, and water pressure',
    answer_c: 'Client age, haircut style, and product scent',
    answer_d: 'Intensity, duration, and pressure',
    correct_answer: 'd',
    explanation: 'Chapter 11 directs the barber to regulate intensity and duration and avoid excessive pressure.',
    difficulty: 'medium',
    order_index: 36,
  },
  {
    id: 'qq-11-037',
    quiz_id: 'quiz-11',
    question: 'Which sequence matches the Chapter 11 hair-tonic treatment?',
    answer_a: 'Steam, shampoo, cut, massage, rinse',
    answer_b: 'Massage, cut, tonic, rinse, steam',
    answer_c: 'Apply tonic, massage, apply steam, massage again, comb into style',
    answer_d: 'Shampoo, color, steam, condition, cut',
    correct_answer: 'c',
    explanation: 'The source sequence is tonic application, scalp massage, scalp steam, another massage by hand or vibrator, then combing into the desired style.',
    difficulty: 'medium',
    order_index: 37,
  },
  {
    id: 'qq-11-038',
    quiz_id: 'quiz-11',
    question: 'Which scalp-disorder categories does Chapter 11 specifically say barbers must not treat?',
    answer_a: 'Dry and oily scalp',
    answer_b: 'Parasitic infestations and staphylococcal infections',
    answer_c: 'Fine and coarse hair',
    answer_d: 'Low density and low elasticity',
    correct_answer: 'b',
    explanation: 'Chapter 11 specifically prohibits barbers from treating scalp disorders caused by parasitic infestations or staphylococcal infections.',
    difficulty: 'easy',
    order_index: 38,
  },
  {
    id: 'qq-11-039',
    quiz_id: 'quiz-11',
    question: 'A parasitic scalp disorder is observed during analysis. What should the barber do?',
    answer_a: 'Do not treat the disorder and refer the client to a physician',
    answer_b: 'Continue after increasing water temperature',
    answer_c: 'Treat the disorder with a stronger shampoo',
    answer_d: 'Use the electric massager before deciding',
    correct_answer: 'a',
    explanation: 'The Chapter 11 source states that parasitic scalp disorders are outside barber treatment and should be referred to a physician.',
    difficulty: 'medium',
    order_index: 39,
  },
  {
    id: 'qq-11-040',
    quiz_id: 'quiz-11',
    question: 'A scalp condition appears consistent with a staphylococcal infection. What is the Chapter 11 service decision?',
    answer_a: 'Perform a short massage only',
    answer_b: 'Apply cosmetic antiseptic and continue',
    answer_c: 'Proceed if the client signs a waiver',
    answer_d: 'Do not treat the disorder as a barber; refer the client to a physician',
    correct_answer: 'd',
    explanation: 'Staphylococcal scalp infections are specifically outside the barber\'s treatment scope in Chapter 11.',
    difficulty: 'medium',
    order_index: 40,
  },
  {
    id: 'qq-11-041',
    quiz_id: 'quiz-11',
    question: 'Which condition is included among the treatment-related scalp/hair concerns in the Chapter 11 source summary?',
    answer_a: 'A fractured bone',
    answer_b: 'Dental caries',
    answer_c: 'Alopecia',
    answer_d: 'Conjunctivitis',
    correct_answer: 'c',
    explanation: 'The Chapter 11 material summary lists alopecia among the hair/scalp concerns considered in treatment discussions, without adding diagnostic detail.',
    difficulty: 'medium',
    order_index: 41,
  },
  {
    id: 'qq-11-042',
    quiz_id: 'quiz-11',
    question: 'A client asks the barber to medically treat a scalp disorder that Chapter 11 places outside barbering scope. What is the best response?',
    answer_a: 'Treat it if the client has had it before',
    answer_b: 'Decline the medical treatment and refer appropriately',
    answer_c: 'Use an electric massager first to see whether it improves',
    answer_d: 'Recommend a prescription-strength product',
    correct_answer: 'b',
    explanation: 'The barber should remain within cosmetic-service scope and refer conditions that require medical treatment.',
    difficulty: 'hard',
    order_index: 42,
  },
  {
    id: 'qq-11-043',
    quiz_id: 'quiz-11',
    question: 'During analysis, the barber cannot determine whether an observed scalp problem is appropriate for routine cosmetic treatment. What is the safest Chapter 11 action?',
    answer_a: 'Diagnose the condition from appearance alone',
    answer_b: 'Perform the treatment and reassess afterward',
    answer_c: 'Ask the client to choose the treatment',
    answer_d: 'Avoid medical diagnosis, pause or modify the service as appropriate, and refer when needed',
    correct_answer: 'd',
    explanation: 'Chapter 11 supports observation and safe service decisions, not medical diagnosis. Uncertain or out-of-scope concerns should be referred appropriately.',
    difficulty: 'hard',
    order_index: 43,
  },
  {
    id: 'qq-11-044',
    quiz_id: 'quiz-11',
    question: 'Which statement best reflects the safety purpose of Chapter 11 draping procedures?',
    answer_a: 'They help protect the client from liquids or chemicals while supporting infection-control and applicable state-law requirements',
    answer_b: 'They replace the need to analyze the scalp',
    answer_c: 'They permit treatment of infectious scalp disorders',
    answer_d: 'They are needed only for haircuts',
    correct_answer: 'a',
    explanation: 'The Chapter 11 source summary ties draping to client protection, infection control, and applicable state-law compliance.',
    difficulty: 'medium',
    order_index: 44,
  },
  {
    id: 'qq-11-045',
    quiz_id: 'quiz-11',
    question: 'Which product direction does Chapter 11 pair with wavy or curly hair?',
    answer_a: 'Heavy oil only',
    answer_b: 'Strong soap only',
    answer_c: 'Light leave-in products and protein treatments',
    answer_d: 'No conditioner or treatment',
    correct_answer: 'c',
    explanation: 'The Chapter 11 product table pairs wavy or curly hair with light leave-in products and protein treatments.',
    difficulty: 'medium',
    order_index: 45,
  },
  {
    id: 'qq-11-046',
    quiz_id: 'quiz-11',
    question: 'A client has fine hair that is easily weighed down. Which product plan best matches Chapter 11?',
    answer_a: 'Volumizing shampoo, detangling conditioner, and protein-treatment options',
    answer_b: 'Coarse-hair moisturizing products only',
    answer_c: 'Heavy leave-in conditioner as the only product',
    answer_d: 'Skip product selection because texture is irrelevant',
    correct_answer: 'a',
    explanation: 'The Chapter 11 product table specifically pairs fine hair with volumizing shampoo, detangling conditioner, and protein treatments.',
    difficulty: 'hard',
    order_index: 46,
  },
  {
    id: 'qq-11-047',
    quiz_id: 'quiz-11',
    question: 'A client has coarse hair and asks which product direction fits the Chapter 11 table. Which answer is best?',
    answer_a: 'Volumizing shampoo and no conditioner',
    answer_b: 'Only pH-balanced products',
    answer_c: 'Light leave-in products only',
    answer_d: 'Moisturizing products and leave-in conditioners',
    correct_answer: 'd',
    explanation: 'Chapter 11 pairs coarse hair with moisturizing products and leave-in conditioners.',
    difficulty: 'hard',
    order_index: 47,
  },
  {
    id: 'qq-11-048',
    quiz_id: 'quiz-11',
    question: 'Why are texture, density, porosity, and elasticity reviewed before product selection?',
    answer_a: 'They determine whether the client needs a haircut',
    answer_b: 'They are analysis factors used to match products and treatment choices to the client',
    answer_c: 'They replace scalp-condition analysis',
    answer_d: 'They are used only to select a cape',
    correct_answer: 'b',
    explanation: 'Chapter 11 includes these characteristics in hair/scalp analysis so product and treatment choices can be matched to the client.',
    difficulty: 'medium',
    order_index: 48,
  },
  {
    id: 'qq-11-049',
    quiz_id: 'quiz-11',
    question: 'A barber notices high porosity and poor elasticity during analysis. What is the most defensible Chapter 11 use of those findings?',
    answer_a: 'Diagnose the medical cause of the hair condition',
    answer_b: 'Ignore them because only scalp condition matters',
    answer_c: 'Use them with the other analysis findings to guide product and treatment selection',
    answer_d: 'Automatically refuse all services',
    correct_answer: 'c',
    explanation: 'Porosity and elasticity are source-listed analysis factors. They inform cosmetic product/treatment selection but do not authorize medical diagnosis.',
    difficulty: 'hard',
    order_index: 49,
  },
  {
    id: 'qq-11-050',
    quiz_id: 'quiz-11',
    question: 'Which statement best describes the Chapter 11 professional boundary for scalp disorders?',
    answer_a: 'Provide cosmetic maintenance within scope, but refer parasitic or staphylococcal disorders for medical care',
    answer_b: 'Diagnose and treat any scalp disorder if the client agrees',
    answer_c: 'Prescribe medication when cosmetic products do not work',
    answer_d: 'Use massage to determine whether an infection is present',
    correct_answer: 'a',
    explanation: 'Chapter 11 permits cosmetic hair/scalp care within scope but specifically excludes treatment of parasitic and staphylococcal scalp disorders and directs referral to a physician.',
    difficulty: 'hard',
    order_index: 50,
  },
]
