// Chapter 14: Men's Haircutting and Styling — PREMIUM IMMERSIVE EXPERIENCE
// THE BARBER'S CHAIR — Master the Art of Men's Haircutting

import type { ChapterTheme, ChapterContent } from './chapter-content'

// ═══════════════════════════════════════════════
// THE BARBER'S CHAIR THEME — Classic Barbershop Craft
// Deep navy / Warm brass / Ivory cream / Charcoal
// Feels like: A modern barbershop where precision meets artistry
// ═══════════════════════════════════════════════

export const chapter14PremiumTheme: ChapterTheme = {
  primary: '#2C3E50',
  primaryLight: '#4A6FA5',
  primaryDark: '#1A252F',
  secondary: '#C9A84C',
  background: 'rgba(20, 24, 32, 0.96)',
  backgroundAlt: 'rgba(32, 38, 48, 0.92)',
  surface: '#141820',
  border: 'rgba(44, 62, 80, 0.25)',
  text: '#F5F0EB',
  textMuted: '#B8A89A',
  highlight: '#C9A84C',
  timeline: {
    line: 'rgba(44, 62, 80, 0.35)',
    iconBg: '#202630',
    iconBorder: '#2C3E50',
  },
  quote: {
    border: 'rgba(44, 62, 80, 0.4)',
    icon: 'rgba(44, 62, 80, 0.3)',
    bg: 'rgba(20, 24, 32, 0.7)',
  },
  tabbed: {
    activeBg: 'rgba(44, 62, 80, 0.15)',
    activeBorder: 'rgba(44, 62, 80, 0.5)',
    activeText: '#4A6FA5',
    inactiveBg: 'rgba(20, 24, 32, 0.7)',
    inactiveBorder: 'rgba(44, 62, 80, 0.12)',
    inactiveText: '#B8A89A',
    panelBg: 'rgba(20, 24, 32, 0.85)',
    panelBorder: 'rgba(44, 62, 80, 0.18)',
  },
  toolCard: {
    headerBg: 'rgba(44, 62, 80, 0.1)',
    headerText: '#4A6FA5',
    dot: 'rgba(44, 62, 80, 0.6)',
    line: 'rgba(44, 62, 80, 0.25)',
  },
  featureGrid: {
    iconBg: 'rgba(44, 62, 80, 0.15)',
    iconColor: '#2C3E50',
    cardBorder: 'rgba(44, 62, 80, 0.2)',
  },
  milestone: {
    yearColor: '#2C3E50',
    border: 'rgba(44, 62, 80, 0.22)',
  },
  checklist: {
    checkBorder: 'rgba(44, 62, 80, 0.4)',
    checkColor: '#2C3E50',
    bg: 'rgba(20, 24, 32, 0.7)',
  },
  contentBlock: {
    bg: 'rgba(20, 24, 32, 0.7)',
    border: 'rgba(44, 62, 80, 0.18)',
    highlightColor: '#C9A84C',
  },
  challengeCard: {
    badgeBg: 'rgba(201, 168, 76, 0.15)',
    badgeText: '#C9A84C',
    cardBorder: 'rgba(44, 62, 80, 0.22)',
    completedBg: 'rgba(0, 230, 118, 0.1)',
    completedBorder: 'rgba(0, 230, 118, 0.3)',
  },
  scenarioBlock: {
    situationBg: 'rgba(201, 168, 76, 0.06)',
    optionBorder: 'rgba(44, 62, 80, 0.18)',
    correctBg: 'rgba(0, 230, 118, 0.1)',
    incorrectBg: 'rgba(255, 82, 82, 0.08)',
  },
  levelUp: {
    levelBadgeBg: 'rgba(44, 62, 80, 0.2)',
    levelBadgeText: '#4A6FA5',
    rewardBg: 'rgba(0, 230, 118, 0.12)',
    rewardText: '#00E676',
  },
  actionPrompt: {
    cardBorder: 'rgba(44, 62, 80, 0.2)',
    completedBorder: 'rgba(0, 230, 118, 0.35)',
    benefitBg: 'rgba(201, 168, 76, 0.1)',
    benefitBorder: 'rgba(201, 168, 76, 0.3)',
  },
}

// ═══════════════════════════════════════════════
// CHAPTER 14: MEN'S HAIRCUTTING AND STYLING
// ═══════════════════════════════════════════════

export const chapter14PremiumContent: ChapterContent = {
  chapterNumber: 14,
  title: "Men's Haircutting and Styling",
  subtitle: 'Master the foundation of barbering — from consultation to clean-up',
  theme: chapter14PremiumTheme,
  sections: [
    // Section 1: Why Study Men's Haircutting
    {
      type: 'infoCards',
      id: 'why-study-haircutting',
      title: 'Why Study Men\'s Haircutting and Styling?',
      cards: [
        {
          icon: 'Scissors',
          title: 'Foundation of Barbering',
          text: 'Haircutting is the core skill that defines a barber. Mastering techniques builds confidence and client loyalty.',
        },
        {
          icon: 'User',
          title: 'Client Customization',
          text: 'Understanding facial shapes and hair types allows you to create customized haircuts that complement each client.',
        },
        {
          icon: 'TrendingUp',
          title: 'Revenue Growth',
          text: 'Quality haircutting and styling services increase client retention and open doors to premium services.',
        },
      ],
    },
    {
      type: 'quote',
      id: 'haircutting-quote',
      quote: 'The consultation is the most important part of any haircut. A thorough consultation prevents misunderstandings and ensures client satisfaction.',
    },

    // Section 2: Client Consultation
    {
      type: 'contentBlock',
      id: 'consultation-fundamentals',
      title: 'The Client Consultation',
      content: 'A thorough consultation is the foundation of a successful haircut. Understanding what the client wants prevents misunderstandings and builds trust. Always clarify vague terms like "just a trim" — what is a trim to one person may be a major cut to another.',
      highlight: 'Always clarify vague terms like "just a trim"',
    },
    {
      type: 'checklist',
      id: 'consultation-questions',
      title: 'Key Consultation Questions',
      items: [
        { text: 'What would you like done today?' },
        { text: 'How short do you want it? (Use fingers to show length)' },
        { text: 'Do you want a fade, taper, or all one length?' },
        { text: 'How do you usually style your hair?' },
        { text: 'Do you have any cowlicks or growth patterns I should know about?' },
      ],
    },
    {
      type: 'contentBlock',
      id: 'trim-warning',
      title: 'Understanding "Just a Trim"',
      content: 'When a client says "just a trim," it can mean different things to different people. Always clarify by showing exactly how much hair will be removed, using fingers or a comb to demonstrate length, and confirming before cutting.',
      highlight: 'Always clarify "just a trim"',
    },

    // Section 3: Facial Shapes and Hair Design
    {
      type: 'contentBlock',
      id: 'facial-shapes-intro',
      title: 'Facial Shapes and Hair Design',
      content: 'Understanding facial shapes helps you recommend styles that complement the client\'s features. The seven facial shapes are oval, round, square, inverted triangular (heart), pear-shaped (triangular), oblong, and diamond. Each shape has specific design goals to create balance and harmony. Use the three-zone method to analyze: divide the face horizontally at the eyebrows, end of nose, and chin.',
      highlight: 'Seven facial shapes analyzed using the three-zone method',
    },
    {
      type: 'tabbed',
      id: 'facial-shapes-tabbed',
      title: 'Five Basic Facial Shapes',
      subtitle: 'Design goals for each face type',
      tabs: [
        {
          id: 'oval',
          label: 'Oval',
          title: 'Oval Face — The Ideal Shape',
          bullets: [
            { label: 'Characteristics', description: 'Balanced proportions; width of forehead and jaw are similar; face is longer than wide' },
            { label: 'Design Goal', description: 'Can wear most styles; maintain balanced proportions' },
            { label: 'Recommendation', description: 'Most versatile face shape — almost any style works well' },
          ],
        },
        {
          id: 'round',
          label: 'Round',
          title: 'Round Face — Add Height, Minimize Width',
          bullets: [
            { label: 'Characteristics', description: 'Width and length are nearly equal; full cheeks; rounded jawline' },
            { label: 'Design Goal', description: 'Add height and minimize width' },
            { label: 'Avoid', description: 'Styles that add volume to the sides' },
          ],
        },
        {
          id: 'square',
          label: 'Square',
          title: 'Square Face — Soften Angles',
          bullets: [
            { label: 'Characteristics', description: 'Strong, angular jawline; forehead and jaw width similar' },
            { label: 'Design Goal', description: 'Soften angles while maintaining masculine features' },
            { label: 'Avoid', description: 'Too much volume on top which exaggerates squareness' },
          ],
        },
        {
          id: 'inverted-triangular',
          label: 'Heart',
          title: 'Inverted Triangular (Heart) — Balance Forehead and Chin',
          bullets: [
            { label: 'Characteristics', description: 'Wider forehead, narrower chin' },
            { label: 'Design Goal', description: 'Add width at jawline, minimize forehead width' },
            { label: 'Recommendation', description: 'Styles with volume on sides work well' },
          ],
        },
        {
          id: 'pear-shaped',
          label: 'Pear',
          title: 'Pear-Shaped (Triangular) — Add Width at Temples',
          bullets: [
            { label: 'Characteristics', description: 'Narrower forehead, wider jawline' },
            { label: 'Design Goal', description: 'Add width at temples, minimize jaw width' },
            { label: 'Recommendation', description: 'Styles with volume on top work well' },
          ],
        },
        {
          id: 'oblong',
          label: 'Oblong',
          title: 'Oblong Face — Visually Shorten',
          bullets: [
            { label: 'Characteristics', description: 'Long, rectangular structure with angular features' },
            { label: 'Design Goal', description: 'Visually shorten the face' },
            { label: 'Techniques', description: 'Layered bangs brushed sideways over temples; mustache adds horizontal line to break length' },
          ],
        },
        {
          id: 'diamond',
          label: 'Diamond',
          title: 'Diamond Face — Balance Mid-Face Width',
          bullets: [
            { label: 'Characteristics', description: 'Narrow temples and chin, widest at cheekbones' },
            { label: 'Design Goal', description: 'Add fullness at temples, keep hair close at widest points' },
            { label: 'Techniques', description: 'Direct bangs off-face into sides; full or square beard balances narrow chin' },
          ],
        },
      ],
    },
    {
      type: 'contentBlock',
      id: 'facial-profiles',
      title: 'Facial Profiles and Design',
      content: 'Facial profile — the side view silhouette — is just as important as face shape. The four profile types are straight (balanced), convex (forehead and chin recede), concave (receding forehead, jutting chin), and angular (sharp, defined lines). Use hairstyle and facial hair to minimize prominent features and add volume to receding ones.',
      highlight: 'The four profile types: straight, convex, concave, angular',
    },
    {
      type: 'tabbed',
      id: 'profile-types',
      title: 'Four Facial Profile Types',
      subtitle: 'Design strategies for each profile',
      tabs: [
        {
          id: 'straight',
          label: 'Straight',
          title: 'Straight Profile — Balanced and Proportioned',
          bullets: [
            { label: 'Characteristics', description: 'Forehead and chin align with slight curvature; most balanced type' },
            { label: 'Design Goal', description: 'Minimal adjustment needed; wide variety of styles work well' },
          ],
        },
        {
          id: 'convex',
          label: 'Convex',
          title: 'Convex Profile — Minimize Forehead Bulge',
          bullets: [
            { label: 'Characteristics', description: 'Forehead and chin recede backward, creating curved-forward appearance' },
            { label: 'Design Goal', description: 'Minimize forehead bulge' },
            { label: 'Technique', description: 'Use close hair arrangement at forehead' },
          ],
        },
        {
          id: 'concave',
          label: 'Concave',
          title: 'Concave Profile — Balance Forehead and Chin',
          bullets: [
            { label: 'Characteristics', description: 'Receding forehead with chin jutting forward' },
            { label: 'Design Goal', description: 'Create balance between forehead and chin' },
            { label: 'Techniques', description: 'Add volume over forehead; use close-cut beard to minimize chin bulk' },
          ],
        },
        {
          id: 'angular',
          label: 'Angular',
          title: 'Angular Profile — Soften Sharp Features',
          bullets: [
            { label: 'Characteristics', description: 'Sharp angles and defined lines' },
            { label: 'Design Goal', description: 'Soften or complement angular features' },
            { label: 'Technique', description: 'Use wavy or textured styles to break harsh lines' },
          ],
        },
      ],
    },
    {
      type: 'featureGrid',
      id: 'design-principles',
      title: 'Five Design Principles',
      features: [
        {
          icon: 'Scale',
          title: 'Balance',
          description: 'Create visual equilibrium between all elements of the haircut.',
        },
        {
          icon: 'Ruler',
          title: 'Proportion',
          description: 'Keep features in pleasing ratio to one another.',
        },
        {
          icon: 'Eye',
          title: 'Emphasis',
          description: 'Draw attention to the client\'s best features.',
        },
        {
          icon: 'Waves',
          title: 'Rhythm',
          description: 'Create movement and flow throughout the design.',
        },
        {
          icon: 'Heart',
          title: 'Harmony',
          description: 'Ensure all elements work together as a cohesive whole.',
        },
      ],
    },

    // Section 4: Basic Haircutting Principles
    {
      type: 'contentBlock',
      id: 'haircutting-fundamentals',
      title: 'Basic Haircutting Principles',
      content: 'Proper preparation and technique are essential for every haircut. Following a systematic approach ensures consistency, safety, and client satisfaction.',
      highlight: 'Proper preparation and technique are essential for every haircut',
    },
    {
      type: 'checklist',
      id: 'preparation-steps',
      title: 'Preparation for All Haircuts',
      items: [
        { text: 'Wash hands thoroughly' },
        { text: 'Conduct client consultation' },
        { text: 'Drape client for wet service' },
        { text: 'Shampoo and towel dry hair' },
        { text: 'Remove waterproof cape; replace with neck strip and haircutting cape' },
        { text: 'Face client toward mirror and lock chair' },
      ],
    },
    {
      type: 'contentBlock',
      id: 'neck-ear-sideburns',
      title: 'Neck Length, Ear Placement, and Sideburn Design',
      content: 'Neck length, ear size, and sideburn design are critical finishing details. For long necks, leave hair fuller at the nape and never cut above the natural hairline. For short necks, taper at the natural hairline to create the illusion of length. Sideburn length is relative to facial features — what looks short on a large face may look long on a small face. Sideburns should appear even from the front, but may need slight asymmetry to account for natural facial differences.',
      highlight: 'Sideburn length is relative to the client\'s individual features',
    },
    {
      type: 'featureGrid',
      id: 'basic-techniques',
      title: 'Basic Haircutting Techniques',
      features: [
        {
          icon: 'Scissors',
          title: 'Clipper-Over-Comb',
          description: 'Using clippers over a comb to create precise, clean lines and gradual fades.',
        },
        {
          icon: 'Cut',
          title: 'Shear-Over-Comb',
          description: 'Using shears over a comb for softer, more blended results than clippers.',
        },
        {
          icon: 'Zap',
          title: 'Freehand Clipper',
          description: 'Using clippers without a comb for outlining and detail work.',
        },
        {
          icon: 'Blend',
          title: 'Blending',
          description: 'Creating smooth transitions between different lengths.',
        },
        {
          icon: 'TrendingDown',
          title: 'Fading',
          description: 'Gradually tapering hair from short to shorter or to skin.',
        },
      ],
    },
    {
      type: 'contentBlock',
      id: 'shear-point-tapering',
      title: 'Shear-Point Tapering',
      content: 'Shear-point tapering uses the tips of the shears to thin or customize difficult areas caused by growth patterns like hollows, whorls, or scalp creases. By cutting only a few strands at a time, this technique minimizes dark or ragged patches and blends them with surrounding hair. It is an advanced skill that shows attention to detail and produces a more natural, polished result.',
      highlight: 'Use shear tips to blend hollows, whorls, and scalp creases',
    },
    {
      type: 'contentBlock',
      id: 'freehand-shear',
      title: 'Freehand Shear Cutting',
      content: 'Freehand shear cutting uses shears without a comb to refine the haircut in its final stages. The open-shear technique — consistently opening and closing shears while moving over the hair surface — removes stray hairs protruding from the design. This is especially effective for shaping and trimming tight curl textures where comb control is difficult.',
      highlight: 'Freehand shear cutting is especially effective for tight curl textures',
    },
    {
      type: 'contentBlock',
      id: 'razor-techniques',
      title: 'Razor Cutting Techniques',
      content: 'Razor cutting produces tapered, soft ends rather than the blunt ends created by shears. Hair must be kept uniformly damp throughout the process — dry cutting causes discomfort and frizz. Three main techniques exist: razor-over-comb (similar to shear-over-comb, rolling the comb out to project hair), razor rotation (a two-part counter-rotation movement for blending and tapering), and fingers-and-razor (holding hair taut between fingers while cutting). Razor cutting is considered the best method for blending and tapering because the blade creates a smoother transition than shears or clippers.',
      highlight: 'Razor cutting creates tapered, soft ends — ideal for blending and tapering',
    },
    {
      type: 'tabbed',
      id: 'razor-taper-methods',
      title: 'Razor Taper-Blending Methods',
      subtitle: 'Three levels of taper intensity',
      tabs: [
        {
          id: 'light',
          label: 'Light',
          title: 'Light Taper-Blending',
          bullets: [
            { label: 'Blade Angle', description: 'Razor held almost flat against the hair surface with slight tilt' },
            { label: 'Pressure', description: 'Minimal pressure removes a small amount of hair' },
            { label: 'Best For', description: 'Fine hair and subtle blending' },
          ],
        },
        {
          id: 'heavier',
          label: 'Heavier',
          title: 'Heavier Taper-Blending',
          bullets: [
            { label: 'Blade Angle', description: 'Razor held up to 45 degrees from the hair strand surface' },
            { label: 'Pressure', description: 'Increased pressure creates deeper cuts and removes more hair' },
            { label: 'Best For', description: 'Medium texture and moderate bulk removal' },
          ],
        },
        {
          id: 'terminal',
          label: 'Terminal',
          title: 'Terminal Blending',
          bullets: [
            { label: 'Blade Angle', description: 'Razor blade angle increased to almost 90 degrees' },
            { label: 'Effect', description: 'Produces minimal tapering at the hair ends' },
            { label: 'Best For', description: 'Final finishing and softening weight lines' },
          ],
        },
      ],
    },
    {
      type: 'contentBlock',
      id: 'thinning-texturizing',
      title: 'Thinning and Texturizing Techniques',
      content: 'Thinning and texturizing reduce bulk or weight without dramatically altering overall length. Slicing glides open shears along the hair surface to remove bulk. Carving elevates hair 45–90 degrees and glides open shears with a curving motion to remove under-portion bulk. Slithering uses an up-and-down sliding motion of shears along a thin section toward the scalp with slight closing action. Point cutting and notching use shear tips at vertical or diagonal angles to reduce weight at the ends — notching is more aggressive and creates chunkier texture. Never cut visible top surfaces where cutting lines can be seen.',
      highlight: 'Never cut visible top surfaces when thinning — creates noticeable lines',
    },
    {
      type: 'contentBlock',
      id: 'guards-vs-blades',
      title: 'Guards vs. Detachable Blades — State Board Critical',
      content: 'Detachable blades and clipper guards are not the same. Detachable blades are metal blades that attach directly to the clipper and determine cutting length. Guards (attachment combs) are plastic combs placed on top of the blade that allow more hair length to remain. Guards are NOT considered freehand clipper cutting and are typically NOT acceptable for state board practical examinations. Students must demonstrate true freehand clipper control without guard attachments for licensing exams.',
      highlight: 'Guards are NOT acceptable for state board practical exams',
    },

    // Section 4b: Design Elements and Lines
    {
      type: 'contentBlock',
      id: 'design-elements',
      title: 'Design Elements in Haircutting',
      content: 'Barbers work with three-dimensional design elements: line, form, space, texture, and color. Understanding how these elements interact helps develop a strong visual eye and the judgment needed to create successful designs. Lines create shape and direction. Form gives width, length, and depth. Space defines positive space (the haircut itself) and negative space (the area surrounding it). Texture affects how light reflects off the hair surface. Color creates illusions of depth and volume — dark colors recede while lighter colors appear to come forward.',
      highlight: 'Line, form, space, texture, and color are the five design elements',
    },
    {
      type: 'tabbed',
      id: 'line-types',
      title: 'Types of Lines in Haircutting',
      subtitle: 'How different lines create different effects',
      tabs: [
        {
          id: 'horizontal',
          label: 'Horizontal',
          title: 'Horizontal Lines — Build Weight',
          bullets: [
            { label: 'Characteristics', description: 'Parallel to the horizon or floor; move from one side to the other' },
            { label: 'Effect', description: 'Build weight and create one-length or low-elevation designs' },
            { label: 'Common Placement', description: 'At the perimeter or occipital area of the haircut' },
            { label: 'Result', description: 'Creates weight lines that add bulk and structure' },
          ],
        },
        {
          id: 'vertical',
          label: 'Vertical',
          title: 'Vertical Lines — Remove Weight',
          bullets: [
            { label: 'Characteristics', description: 'Perpendicular to the floor; described as up and down' },
            { label: 'Effect', description: 'Remove weight and create layers' },
            { label: 'Technique', description: 'Facilitate projecting hair at higher elevations while cutting' },
            { label: 'Result', description: 'Layers may be cut short-to-long, long-to-short, or uniformly' },
          ],
        },
        {
          id: 'diagonal',
          label: 'Diagonal',
          title: 'Diagonal Lines — Create Slope',
          bullets: [
            { label: 'Characteristics', description: 'Slanted direction; referred to as diagonal forward or diagonal back at the perimeter' },
            { label: 'Effect', description: 'Produce increased length at one end, shorter at the opposite' },
            { label: 'Technique', description: 'Diagonal finger placement creates stacked, layered effects' },
            { label: 'Result', description: 'Blends longer layers to shorter layers within the haircut' },
          ],
        },
        {
          id: 'curved',
          label: 'Curved',
          title: 'Curved Lines — Soften Design',
          bullets: [
            { label: 'Characteristics', description: 'Move in semicircular or circular direction; can be shallow or deep' },
            { label: 'Types', description: 'Concave curves inward; convex curves outward' },
            { label: 'Placement', description: 'Often used at the nape perimeter and around the face' },
            { label: 'Result', description: 'Softens the design and creates wave patterns when repeated' },
          ],
        },
      ],
    },
    {
      type: 'contentBlock',
      id: 'elevation-degrees',
      title: 'Elevation and Projection',
      content: 'Elevation is the angle at which a section of hair is held from the head for cutting, relative to where it grows. Projection is the result of lifting hair above zero elevation. These angles determine the final shape and weight distribution of the haircut. Zero elevation produces weight and bulk at the perimeter. Forty-five degree elevation creates graduation or stacking. Ninety-degree elevation produces layering and is the most common projection in men\'s haircutting. One hundred eighty-degree elevation is used for long hair layering.',
      highlight: 'Elevation angles determine weight distribution and final shape',
    },
    {
      type: 'tabbed',
      id: 'elevation-guide',
      title: 'Elevation Degrees and Their Effects',
      subtitle: 'How angle changes the haircut',
      tabs: [
        {
          id: 'zero',
          label: '0°',
          title: 'Zero Elevation — Maximum Weight',
          bullets: [
            { label: 'Method', description: 'Hair combed straight down from where it grows and cut against the skin or between fingers' },
            { label: 'Result', description: 'Produces weight, bulk, and maximum length at the perimeter' },
            { label: 'Use', description: 'Creates the design line that guides all subsequent partings' },
            { label: 'Style', description: 'Standard blunt cut on longer hair; crisp lines on shorter styles' },
          ],
        },
        {
          id: 'forty-five',
          label: '45°',
          title: '45-Degree Elevation — Graduation',
          bullets: [
            { label: 'Classification', description: 'Medium elevation; also called graduation' },
            { label: 'Result', description: 'Creates layered ends or stacking within the parting' },
            { label: 'Technique', description: 'Horizontal parting with stationary guide at the perimeter' },
            { label: 'Effect', description: 'Movement and texture between the zero and forty-five degree positions' },
          ],
        },
        {
          id: 'ninety',
          label: '90°',
          title: '90-Degree Elevation — Layering',
          bullets: [
            { label: 'Classification', description: 'High elevation; most common in men\'s haircutting' },
            { label: 'Result', description: 'Produces layering, tapering, and blended effects' },
            { label: 'Technique', description: 'Hair held straight out from where it grows; requires traveling guide' },
            { label: 'Use', description: 'Uniform layers or tapered effects from nape to top' },
          ],
        },
        {
          id: 'one-eighty',
          label: '180°',
          title: '180-Degree Elevation — Long Hair Layers',
          bullets: [
            { label: 'Classification', description: 'Highest elevation; used for long hair' },
            { label: 'Technique', description: 'Ninety-degree stationary guide in top section; sides and back brought up to it' },
            { label: 'Important', description: 'The hair being cut is at 180 degrees, not the stationary guide' },
            { label: 'Reference', description: 'See Chapter 16: Women\'s Haircutting and Styling' },
          ],
        },
      ],
    },
    {
      type: 'contentBlock',
      id: 'guide-types',
      title: 'Guides: Stationary and Traveling',
      content: 'A guide is a cut section of hair by which subsequent partings are measured and cut. Guides are classified as stationary or traveling. A stationary guide maintains its position while subsequent partings are brought to it — used for one-length designs and maintaining length in a section. A traveling guide moves along the section as each cut is made — the previous cut becomes the guide for the next parting. Most haircuts use a combination of both guide types.',
      highlight: 'Most haircuts use a combination of stationary and traveling guides',
    },
    {
      type: 'contentBlock',
      id: 'cross-checking',
      title: 'Cross-Checking',
      content: 'Cross-checking is the process of parting off subsections opposite from the elevation or direction at which they were cut to check the precision of cutting lines or blending. For example, a vertical subsection cut at a ninety-degree projection can be cross-checked by parting off subsections horizontally at ninety degrees. This essential quality-control step ensures even, balanced results.',
      highlight: 'Cross-checking ensures precision and balanced results',
    },
    {
      type: 'contentBlock',
      id: 'grain-cutting',
      title: 'Cutting With, Against, and Across the Grain',
      content: 'The direction of cutting relative to hair growth affects the final result. Cutting with the grain follows the natural growth direction for a softer, longer appearance. Cutting against the grain goes opposite to growth for a closer, tighter cut — essential for fades and tapers. Cutting across the grain moves in a direction neither with nor against growth. In whorl areas where hair grows unevenly, a circular motion may be required.',
      highlight: 'Cutting against the grain achieves a closer cut than with the grain',
    },
    {
      type: 'contentBlock',
      id: 'tension-control',
      title: 'Tension and Comb Selection',
      content: 'Tension is the amount of pressure applied while combing and holding a section for cutting. It ranges from minimum to maximum based on how much the hair is stretched. Use maximum tension on straight hair for precise lines. Use minimal to moderate tension on curly and wavy hair — maximum tension may cause the hair to dry shorter than intended. Comb tooth spacing affects tension: fine-toothed combs create more tension because the hair has less room to move; wide-toothed combs create less tension.',
      highlight: 'Fine-toothed combs create more tension; wide-toothed combs create less',
    },

    // Section 5: Haircutting Procedures
    {
      type: 'contentBlock',
      id: 'head-sections',
      title: 'Sections of the Head and Reference Points',
      content: 'The head is divided into seven sections for systematic cutting: front, top (apex), temporal (crest/parietal ridge/hatband/horseshoe), crown, sides, sideburns, back, and nape. Key reference points include the parietal ridge (widest part, where the comb leaves the head at the sides), occipital bone (base of skull, where the comb leaves at the nape), apex (highest point), and the four corners (found by crossing diagonal lines at the apex). Tapering is the gradual increase in hair length without visible lines of demarcation. Blending areas are the transition zones between different lengths.',
      highlight: 'Seven head sections and four key reference points guide every haircut',
    },
    {
      type: 'contentBlock',
      id: 'classic-styles',
      title: 'Classic Men\'s Haircut Styles',
      content: 'Understanding classic haircut styles provides a reference framework for client consultations and ensures you can execute the most requested cuts. Styles are cyclical — classic cuts return with modern modifications. Regional naming varies: a temple fade in the Midwest may be called a Philly fade on the East Coast.',
      highlight: 'Classic styles provide the foundation for modern variations',
    },
    {
      type: 'tabbed',
      id: 'classic-cuts',
      title: 'Common Classic Cuts',
      subtitle: 'Characteristics and technique notes',
      tabs: [
        {
          id: 'flat-top',
          label: 'Flat Top',
          title: 'Flat Top — Squared Crest',
          bullets: [
            { label: 'Characteristics', description: 'Very short sides and back with slightly longer hair at upper parietal and front; flat, squared-off top section' },
            { label: 'Technique', description: 'Requires steady hand and consistent horizontal comb placement; both clippers and shears used' },
            { label: 'Variation', description: 'Can be combined with fade elements' },
          ],
        },
        {
          id: 'crew-cut',
          label: 'Crew Cut',
          title: 'Crew Cut — Graduated Length',
          bullets: [
            { label: 'Characteristics', description: 'Short, semi-short, or medium-tapered sides and back; length gradually increases from crown to front' },
            { label: 'Technique', description: 'Back and sides cut high to bottom of crest; tapered and blended to top; wide-toothed comb used for level guide' },
            { label: 'Variation', description: 'Brush cut (combed back to stand up) and butch cut (styled forward or to side)' },
          ],
        },
        {
          id: 'high-tight',
          label: 'High & Tight',
          title: 'High and Tight — Extreme Contrast',
          bullets: [
            { label: 'Characteristics', description: 'Extremely close or shaved sides and back cut to a specific level; short top section no more than ¼ inch' },
            { label: 'Technique', description: 'Line at parietal ridge can be left distinct or blended into top based on client preference' },
          ],
        },
        {
          id: 'fade',
          label: 'Fade',
          title: 'Fade — Gradual to Skin',
          bullets: [
            { label: 'Characteristics', description: 'Hair longer at top, gradually fading to nothing at hairline; back and sides cut extremely close' },
            { label: 'Technique', description: 'Follow natural hair growth pattern to avoid gaps and patches; multiple variations for different textures' },
          ],
        },
        {
          id: 'taper',
          label: 'Taper',
          title: 'Taper Cut — Graduated and Blended',
          bullets: [
            { label: 'Characteristics', description: 'Well-blended, graduated cut conforming to head shape; length increases from hairline to top without visible gaps' },
            { label: 'Technique', description: 'Top left long enough for styling options; also called regular taper, businessman\'s cut, or Ivy League' },
            { label: 'Consultation', description: 'Always ask about natural taper preference versus blocked nape' },
          ],
        },
        {
          id: 'pompadour',
          label: 'Pompadour',
          title: 'Pompadour — Long Top, Volume Front',
          bullets: [
            { label: 'Characteristics', description: 'Medium to long taper with long top section; gradual length increase from hairline through back and sides' },
            { label: 'Technique', description: 'Overdirection from front to crown; diagonal cutting lines shorter at crown, longer toward front' },
            { label: 'Variation', description: 'Pomp fade combines very short sides with extra long top' },
          ],
        },
        {
          id: 'caesar',
          label: 'Caesar',
          title: 'Caesar — Uniform Forward Layers',
          bullets: [
            { label: 'Characteristics', description: 'Short, uniform layered cut (1 to 2 inches) distributed around head form; styled forward over front hairline' },
            { label: 'Technique', description: 'Fingers-and-shear at 90-degree elevations; rounder appearance than angular cuts' },
            { label: 'Variation', description: 'Modern versions may incorporate tapering or fading in side/back areas' },
          ],
        },
        {
          id: 'quo-vadis',
          label: 'Quo Vadis',
          title: 'Quo Vadis — Close, Even All-Over',
          bullets: [
            { label: 'Characteristics', description: 'Close, even all-over length using clippers; conforms to head contours' },
            { label: 'Technique', description: 'Select blade size for desired length; follow natural growth pattern; cutting against grain leaves hair shorter' },
            { label: 'Best For', description: 'Most hair textures; produces most uniform appearance on medium to thick hair' },
          ],
        },
      ],
    },
    {
      type: 'contentBlock',
      id: 'haircutting-procedures',
      title: 'Haircutting Procedures',
      content: 'Mastering specific haircut procedures requires understanding sectioning, guide placement, and blending techniques. Each style has unique steps that must be followed precisely.',
      highlight: 'Mastering specific haircut procedures requires understanding sectioning, guide placement, and blending',
    },
    {
      type: 'tabbed',
      id: 'haircut-procedures',
      title: 'Common Haircut Procedures',
      subtitle: 'Step-by-step guides for popular styles',
      tabs: [
        {
          id: 'basic-clipper',
          label: 'Basic Clipper',
          title: 'Basic Haircut with Clippers',
          bullets: [
            { label: 'Step 1', description: 'Determine desired length on top' },
            { label: 'Step 2', description: 'Establish center guide on top' },
            { label: 'Step 3', description: 'Cut sections right and left of center from front through top' },
            { label: 'Step 4', description: 'Move to back section; cut from crown to nape' },
            { label: 'Step 5', description: 'Cut sections left and right of center through back' },
            { label: 'Step 6', description: 'Move to sides; cut from hairline to top' },
            { label: 'Step 7', description: 'Cut around ears and blend into back section' },
            { label: 'Step 8', description: 'Cross-check and blend as needed' },
            { label: 'Step 9', description: 'Outline and detail with trimmer' },
          ],
        },
        {
          id: 'shadow-fade',
          label: 'Shadow Fade',
          title: 'Shadow Fade Cut',
          bullets: [
            { label: 'Step 1', description: 'Determine length for top section' },
            { label: 'Step 2', description: 'Select appropriate clipper blade or guard' },
            { label: 'Step 3', description: 'Start at front hairline; cut center guide back to crown' },
            { label: 'Step 4', description: 'Cut sections right and left of center' },
            { label: 'Step 5', description: 'Move to back; adjust clippers to open blade position' },
            { label: 'Step 6', description: 'Start at nape; cut against grain to mid-occipital area' },
            { label: 'Step 7', description: 'Cut sections left and right of center panel' },
            { label: 'Step 8', description: 'Move to sides; cut from hairline to desired point' },
            { label: 'Step 9', description: 'Cut around ears and blend' },
            { label: 'Step 10', description: 'Attach guard and close blades halfway; blend at top of parietal ridge' },
            { label: 'Step 11', description: 'Adjust blades to closed position; blend through middle parietal' },
            { label: 'Step 12', description: 'Attach No. 0 guard; blend around parietal ridge' },
            { label: 'Step 13', description: 'Remove guard; taper and blend hairline' },
            { label: 'Step 14', description: 'Finish with trimmer or outline shave' },
          ],
        },
        {
          id: 'pompadour-fade',
          label: 'Pompadour Fade',
          title: 'Pompadour Fade',
          bullets: [
            { label: 'Step 1', description: 'Re-dampen top section with water if necessary' },
            { label: 'Step 2', description: 'Part off top section following curve of head at parietal ridge' },
            { label: 'Step 3', description: 'Secure with clips' },
            { label: 'Step 4', description: 'Select appropriate blade size for back and sides' },
            { label: 'Step 5', description: 'On preferred side, use freehand clipper technique to establish guide' },
            { label: 'Step 6', description: 'Rock clipper out at point where transition will occur' },
            { label: 'Step 7', description: 'Repeat on opposite side' },
            { label: 'Step 8', description: 'Move to back; cut from nape upward' },
            { label: 'Step 9', description: 'Blend transition areas' },
            { label: 'Step 10', description: 'Release top section; comb through' },
            { label: 'Step 11', description: 'Create slight overdirection of parting to center top guide' },
            { label: 'Step 12', description: 'Cut parting to guide' },
            { label: 'Step 13', description: 'Continue cutting from parietal area up to top' },
            { label: 'Step 14', description: 'Move behind client; comb through top sections' },
            { label: 'Step 15', description: 'Check hair horizontally and blend as needed' },
            { label: 'Step 16', description: 'Style as desired' },
          ],
        },
      ],
    },
    {
      type: 'contentBlock',
      id: 'grain-reminder',
      title: 'Key Point: Cutting Against the Grain',
      content: 'Cutting against the grain achieves a closer cut than cutting with the grain. This is essential for fades and tapers but requires careful technique to avoid irritation.',
      highlight: 'Cutting against the grain achieves a closer cut',
    },

    {
      type: 'contentBlock',
      id: 'finish-work',
      title: 'Haircut Finish Work',
      content: 'Professional finishing touches separate a good haircut from a great one. Standard finishing procedures include a neck or outline shave, eyebrow trim, and removal of stray hairs from ears or nostrils. These services demonstrate attention to detail, provide a complete barbershop experience, and help build client loyalty and referrals. Always include finish work as part of your standard service — not as an extra.',
      highlight: 'Finish work builds client loyalty and should be standard — not extra',
    },
    {
      type: 'contentBlock',
      id: 'natural-styling',
      title: 'Natural Drying and Finger Styling',
      content: 'Not every client needs a blowout. Natural drying lets hair air-dry in its natural position — comb into place or arrange with fingers, then apply gel or pomade while damp. Finger styling uses fingers instead of a comb to manipulate hair into place, producing a more natural, tousled look that many clients prefer. Scrunch styling is a form of finger styling for wavy or curly hair: lift and squeeze hair between fingers while applying diffuser heat to enhance natural texture.',
      highlight: 'Finger styling produces a natural, tousled look many clients prefer',
    },
    {
      type: 'contentBlock',
      id: 'locks',
      title: 'Locks (Dreadlocks) — Consultation Essentials',
      content: 'Locks form when natural-textured hair intertwines into a single network. The process takes 6 months to 1 year to fully complete. Once hair locks, removal requires cutting them off entirely — emphasize this permanence during consultation. Cultivated locks are intentionally guided through techniques like double twisting, coiling, palm rolling, braiding, or wrapping with cord. Maintenance requires regular shop visits for cleaning, conditioning, and rerolling. Use only non-petroleum-based oils; heavy oils cause buildup and attract debris.',
      highlight: 'Locks are permanent — removal requires cutting them off',
    },

    // Section 5b: Building Volume
    {
      type: 'contentBlock',
      id: 'building-volume',
      title: 'Building Volume with Blowdryer and Brush',
      content: 'Adding volume to specific areas creates proportional balance and an even contour throughout the haircut. The crown, crest, and top areas are the most common zones requiring extra lift. To build volume, lift the hair with a brush while bending the section, directing the blowdryer at the base of the section and following through to the ends. Use horizontal partings when styling the sides down, and vertical or diagonal partings when brushing the sides back. Keep the dryer moving to avoid burning the scalp.',
      highlight: 'Lift with the brush, bend the section, and direct heat at the base',
    },

    // Section 6: Blowdrying Techniques
    {
      type: 'contentBlock',
      id: 'blowdrying-intro',
      title: 'Blowdrying Techniques',
      content: 'Proper blowdrying technique is essential for finishing any haircut. Different methods create different results — from natural texture to polished styles.',
      highlight: 'Proper blowdrying technique is essential for finishing any haircut',
    },
    {
      type: 'tabbed',
      id: 'blowdrying-methods',
      title: 'Blowdrying Methods',
      subtitle: 'Four techniques for different finishes',
      tabs: [
        {
          id: 'freeform',
          label: 'Freeform',
          title: 'Freeform Blowdrying',
          bullets: [
            { label: 'Step 1', description: 'Hold dryer 6 to 10 inches from hair' },
            { label: 'Step 2', description: 'Angle nozzle pointing downward' },
            { label: 'Step 3', description: 'Dry layers underneath first' },
            { label: 'Step 4', description: 'Move dryer briskly from side to side' },
            { label: 'Step 5', description: 'As hair underneath dries, release next section' },
            { label: 'Step 6', description: 'Comb or brush hair down after each section' },
            { label: 'Step 7', description: 'Dry sides in same manner' },
            { label: 'Step 8', description: 'Dry top loosely; comb or brush into desired style' },
          ],
        },
        {
          id: 'stylized',
          label: 'Stylized',
          title: 'Stylized Blowdrying',
          bullets: [
            { label: 'Step 1', description: 'Begin in back section' },
            { label: 'Step 2', description: 'Lift section with comb or brush' },
            { label: 'Step 3', description: 'Follow movement of comb with dryer' },
            { label: 'Step 4', description: 'Apply concentrated stream of heated air' },
            { label: 'Step 5', description: 'Dry from scalp to ends' },
            { label: 'Step 6', description: 'Repeat until section is dry' },
            { label: 'Step 7', description: 'Move to next section and sides' },
          ],
        },
        {
          id: 'blow-waving',
          label: 'Blow Waving',
          title: 'Blow Waving',
          bullets: [
            { label: 'Step 1', description: 'Use blow-waving technique to create lift or direction in top section' },
            { label: 'Step 2', description: 'Work from natural part' },
            { label: 'Step 3', description: 'Elevate hair to create desired fullness' },
            { label: 'Step 4', description: 'Insert comb 1½ inches from hairline' },
            { label: 'Step 5', description: 'Draw comb to back then toward hairline in one motion' },
            { label: 'Step 6', description: 'This creates ridge or bend to set style' },
            { label: 'Step 7', description: 'Apply heat until soft ridge is formed' },
            { label: 'Step 8', description: 'Repeat in subsequent sections' },
            { label: 'Step 9', description: 'Apply suitable styling aid to finish' },
          ],
        },
        {
          id: 'diffused',
          label: 'Diffused',
          title: 'Diffused Drying',
          bullets: [
            { label: 'Step 1', description: 'Pick hair out into basic shape of desired style' },
            { label: 'Step 2', description: 'Begin drying in back section, working toward crown and sides' },
            { label: 'Step 3', description: 'Gently pick hair out as dryer moves from section to section' },
            { label: 'Step 4', description: 'Dry sides in same manner' },
            { label: 'Step 5', description: 'Dry top section forward from crown' },
            { label: 'Step 6', description: 'Apply suitable styling aid to complete' },
          ],
        },
      ],
    },
    {
      type: 'contentBlock',
      id: 'blowdry-safety',
      title: 'Blowdrying Safety',
      content: 'Keep both the airflow and hair constantly moving to prevent burning the client\'s scalp. Never concentrate dryer heat in one spot for extended periods. Keep metal combs away from the scalp during heat application. Dry underneath sections first to prevent missing damp spots and accelerate total drying time.',
      highlight: 'Keep airflow and hair constantly moving to prevent scalp burns',
    },
    {
      type: 'contentBlock',
      id: 'tool-maintenance',
      title: 'Tool Maintenance and Safety',
      content: 'Dull blades pull hair, cause client pain, and degrade haircut quality. Replace blades mid-service if necessary. Keep razors closed when not in active use. Maintain spatial awareness when using sharp implements around others. After each client, clean, disinfect, and properly store all tools. Sweep the floor and dispose of hair clippings between every client to prevent cross-contamination.',
      highlight: 'Dull blades pull hair and cause pain — replace them when needed',
    },

    // Section 7: The Head Shave
    {
      type: 'contentBlock',
      id: 'head-shave-intro',
      title: 'The Head Shave',
      content: 'A complete head shave requires careful preparation and technique. Proper draping, skin examination, and systematic shaving ensure a smooth, irritation-free result.',
      highlight: 'Proper draping, skin examination, and systematic shaving ensure a smooth result',
    },
    {
      type: 'checklist',
      id: 'head-shave-prep',
      title: 'Head Shave Preparation',
      items: [
        { text: 'Wash hands' },
        { text: 'Conduct client consultation' },
        { text: 'Drape client for haircut' },
        { text: 'Face client toward mirror and lock chair' },
        { text: 'Examine scalp for abrasions, lesions, or disorders' },
        { text: 'Remove excess hair length with clippers if necessary' },
        { text: 'Drape for wet service and shampoo remaining hair' },
        { text: 'Re-examine scalp' },
        { text: 'Remove shampoo cape' },
        { text: 'Re-drape with haircutting cape and towels' },
        { text: 'Tuck wiping cloth into neckline' },
      ],
    },
    {
      type: 'checklist',
      id: 'head-shave-procedure',
      title: 'Head Shave Procedure',
      items: [
        { text: 'Apply shaving cream or gel and lather' },
        { text: 'Follow with two or three steamed-towel treatments to soften hair' },
        { text: 'Re-lather scalp' },
        { text: 'Lock chair' },
        { text: 'Start in back section using freehand stroke' },
        { text: 'Shave with grain from crown to nape' },
        { text: 'Use opposite hand to stretch skin taut' },
        { text: 'Follow curve of head' },
        { text: 'Move to front; tip head forward slightly' },
        { text: 'Continue shaving from crown to front hairline' },
        { text: 'Reapply lather as needed' },
        { text: 'Keep skin moist' },
        { text: 'When top is completed, work down sides' },
        { text: 'Hold ear out of way with left hand' },
        { text: 'Carefully shave in front of and around ears' },
        { text: 'Repeat on left side' },
        { text: 'Check for missed areas and re-shave as necessary' },
        { text: 'Wrap warm towel around head' },
        { text: 'Use towel to remove remaining lather' },
        { text: 'Apply witch hazel or skin toner' },
        { text: 'Follow with cool-towel application for 2-3 minutes' },
        { text: 'Apply moisturizing cream or oil as requested' },
      ],
    },

    // Section 8: Cornrow Braiding
    {
      type: 'contentBlock',
      id: 'cornrow-intro',
      title: 'Cornrow Braiding',
      content: 'Cornrows are narrow rows of visible braids that lie close to the scalp. This technique requires precision, even tension, and understanding of hair growth patterns.',
      highlight: 'Cornrows are narrow rows of visible braids that lie close to the scalp',
    },
    {
      type: 'checklist',
      id: 'cornrow-prep',
      title: 'Cornrow Preparation',
      items: [
        { text: 'Wash hands' },
        { text: 'Conduct client consultation' },
        { text: 'Drape for wet service' },
        { text: 'Shampoo and condition hair' },
        { text: 'Remove waterproof cape' },
        { text: 'Replace with towels under and over haircutting cape' },
        { text: 'Face client toward mirror and lock chair' },
      ],
    },
    {
      type: 'checklist',
      id: 'cornrow-procedure',
      title: 'Cornrow Braiding Procedure',
      items: [
        { text: 'Start with clean, damp hair' },
        { text: 'Apply and massage essential oil to scalp' },
        { text: 'Determine correct size and direction of cornrow base' },
        { text: 'Use tail comb to part off top section on right side' },
        { text: 'Secure with clip' },
        { text: 'Use mirror to determine where to section left side' },
        { text: 'Secure with clip' },
        { text: 'Create two parallel partings in center of top section' },
        { text: 'Form neat row for cornrow base' },
        { text: 'Divide parting into three strands' },
        { text: 'Place fingers close to base' },
        { text: 'Cross left strand under center strand' },
        { text: 'Cross right strand under center strand' },
        { text: 'With each crossing under, pick up hair from base of panel' },
        { text: 'Add to outer strand before crossing under center' },
        { text: 'When braid is finished, secure ends with small rubber band' },
        { text: 'Braid subsequent panels left and right of center' },
        { text: 'Once top three braids complete, complete braids on left and right' },
        { text: 'Maintain even tension' },
        { text: 'Follow curvature of head' },
        { text: 'Finish with oil sheen or appropriate styling aid' },
      ],
    },

    // Section 9: Clean-Up and Disinfection
    {
      type: 'contentBlock',
      id: 'cleanup-intro',
      title: 'Clean-Up and Disinfection',
      content: 'After every haircutting service, proper clean-up and disinfection protect both the barber and the client. Following standard precautions ensures a safe, professional environment.',
      highlight: 'Proper clean-up and disinfection protect both the barber and the client',
    },
    {
      type: 'checklist',
      id: 'cleanup-checklist',
      title: 'Post-Service Clean-Up Checklist',
      items: [
        { text: 'Clean and disinfect all tools and implements' },
        { text: 'Clean and disinfect the work area' },
        { text: 'Clean surfaces and chair' },
        { text: 'Sweep up hair and deposit in closed receptacle' },
        { text: 'Deposit used blades in sharps container' },
        { text: 'Dispose of single-use items' },
        { text: 'Place all used linens, towels, and capes in laundry' },
        { text: 'Wash hands thoroughly' },
      ],
    },
    {
      type: 'contentBlock',
      id: 'sharps-warning',
      title: 'Sharps Safety',
      content: 'Never leave used blades on the counter or in regular trash. Always use a proper sharps container. Improper disposal risks injury and violates health codes.',
      highlight: 'Always use a proper sharps container',
    },

    // Section 10: Key Takeaways
    {
      type: 'contentBlock',
      id: 'key-takeaways',
      title: 'Chapter 14 Key Takeaways',
      content: 'Mastering men\'s haircutting and styling requires understanding consultation, facial shapes, cutting techniques, and finishing methods. Always prioritize safety, sanitation, and client satisfaction.',
      highlight: 'Always prioritize safety, sanitation, and client satisfaction',
    },
    {
      type: 'checklist',
      id: 'chapter-summary',
      title: 'Chapter Summary',
      items: [
        { text: 'Always conduct a thorough consultation before cutting' },
        { text: 'Seven facial shapes: oval, round, square, inverted triangular, pear-shaped, oblong, diamond' },
        { text: 'Four facial profiles: straight, convex, concave, angular' },
        { text: 'Five design elements: line, form, space, texture, color' },
        { text: 'Four line types: horizontal, vertical, diagonal, curved' },
        { text: 'Elevation degrees: 0°, 45°, 90°, 180° and their effects' },
        { text: 'Guide types: stationary and traveling' },
        { text: 'Basic techniques: clipper-over-comb, shear-over-comb, freehand, blending, fading' },
        { text: 'Razor techniques: razor-over-comb, razor rotation, fingers-and-razor' },
        { text: 'Thinning methods: slicing, carving, slithering, point cutting, notching' },
        { text: 'Classic styles: flat top, crew cut, high and tight, fade, taper, pompadour, Caesar, quo vadis' },
        { text: 'Shadow fade uses adjustable-blade clipper with/without guards' },
        { text: 'Pompadour fade requires sectioning and careful blending' },
        { text: 'Blowdrying methods: freeform, stylized, blow waving, diffused' },
        { text: 'Building volume: lift with brush, bend section, direct heat at base' },
        { text: 'Head shave requires steamed towels and careful stretching of skin' },
        { text: 'Cornrow braiding involves picking up hair with each strand cross' },
        { text: 'Locks take 6–12 months to form and are permanent' },
        { text: 'Always follow proper clean-up and disinfection procedures' },
        { text: 'Dispose of blades in sharps container only' },
        { text: 'Guards are NOT acceptable for state board practical exams' },
      ],
    },
  ],
}
