// Chapter 16: Women's Haircutting & Styling — PREMIUM MCQ QUIZ
// 30 questions generated STRICTLY from Chapter 16 premium flashcards and curriculum
// Source: CHAPTER_16_QUIZ_PHASE_Q2A_DRAFT.md
//         CHAPTER_16_QUIZ_PHASE_Q2B_DRAFT.md
//         CHAPTER_16_QUIZ_PHASE_Q2C_DRAFT.md

import { QuizQuestion } from '@/types'

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 16: FULL QUESTION BANK (30 questions)
// Cognitive distribution: 14 Recall / 12 Application / 4 Analysis
// ═══════════════════════════════════════════════════════════════════════════════
export const chapter16PremiumQuizQuestions: QuizQuestion[] = [
  // === SECTION 2 — WHY WOMEN'S HAIRCUTTING MATTERS (1 question) ===
  {
    id: 'qq-16-001',
    quiz_id: 'quiz-16',
    question: "Before beginning a women's haircutting service, what is the most important first step?",
    answer_a: 'Select the cutting structure based on the client\'s inspiration photo',
    answer_b: 'Perform a thorough consultation to confirm goals, history, and expectations',
    answer_c: 'Drape the client and prepare the tools',
    answer_d: 'Choose the elevation angle that matches the desired shape',
    correct_answer: 'b',
    explanation: 'A thorough consultation is the foundation of every professional service. It confirms what the client wants, reveals hair history and lifestyle factors, and sets realistic expectations before any cutting begins. Choosing a structure or elevation without consulting the client risks a result that does not match the client\'s goals.',
    difficulty: 'easy',
    order_index: 1,
  },

  // === SECTION 3 — HAIRCUT DESIGN PHILOSOPHY (2 questions) ===
  {
    id: 'qq-16-002',
    quiz_id: 'quiz-16',
    question: 'In haircut design, texture refers to:',
    answer_a: 'The direction the hair flows after cutting',
    answer_b: 'The surface quality of each strand and the overall head of hair',
    answer_c: 'The angle at which hair is held away from the head',
    answer_d: 'The overall silhouette of the finished cut',
    correct_answer: 'b',
    explanation: 'Texture describes the surface quality of the hair — whether it is fine, medium, or coarse. It directly affects how hair responds to tension, layering, and texturizing techniques. Movement, elevation, and shape are separate design elements.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-16-003',
    quiz_id: 'quiz-16',
    question: 'A client has coarse, resistant hair and wants a precise bob with a solid bottom line. Which design element most directly affects the choice of structure and technique?',
    answer_a: 'Movement, because coarse hair needs layers to move',
    answer_b: 'Texture, because coarse hair responds differently to tension and texturizing than fine hair',
    answer_c: 'Weight, because coarse hair always requires graduation',
    answer_d: 'Shape, because the silhouette determines the elevation angle',
    correct_answer: 'b',
    explanation: 'Texture influences how the hair behaves under tension and how it responds to cutting and texturizing. Coarse hair may need different section sizes, tension, and finishing techniques than fine hair. While shape, weight, and movement matter, texture is the element that most directly drives those practical choices.',
    difficulty: 'medium',
    order_index: 3,
  },

  // === SECTION 4 — FOUR FOUNDATIONAL HAIRCUTS (3 questions) ===
  {
    id: 'qq-16-004',
    quiz_id: 'quiz-16',
    question: 'Which foundational haircut uses little to no elevation and keeps maximum weight concentrated along the perimeter?',
    answer_a: 'Graduated cut',
    answer_b: 'Uniform-layered cut',
    answer_c: 'Blunt cut',
    answer_d: 'Long-layered cut',
    correct_answer: 'c',
    explanation: 'The blunt cut is defined by low or zero elevation. Keeping the hair close to its natural fall concentrates weight along the outside edge, creating a strong, solid perimeter. Graduated, uniform-layered, and long-layered cuts all use higher elevation to move or distribute weight.',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-16-005',
    quiz_id: 'quiz-16',
    question: 'A client wants a shoulder-length style with fullness and a soft, stacked shape through the back. Which foundational structure is most appropriate?',
    answer_a: 'Blunt cut',
    answer_b: 'Graduated cut',
    answer_c: 'Uniform-layered cut',
    answer_d: 'Long-layered cut',
    correct_answer: 'b',
    explanation: 'A graduated cut uses controlled elevation to build weight along a design line, creating the stacked or wedge-shaped silhouette the client wants. A blunt cut would create a solid perimeter without the stacked fullness, while layered cuts would remove weight rather than build it.',
    difficulty: 'medium',
    order_index: 5,
  },
  {
    id: 'qq-16-006',
    quiz_id: 'quiz-16',
    question: 'How does a graduated cut differ from a blunt cut in terms of weight placement?',
    answer_a: 'A blunt cut builds weight gradually, while a graduated cut keeps weight at the perimeter.',
    answer_b: 'A graduated cut removes all weight, while a blunt cut leaves weight throughout.',
    answer_c: 'A blunt cut keeps maximum weight at the perimeter, while a graduated cut builds weight along a design line.',
    answer_d: 'Both cuts keep weight at the perimeter; only the cutting-line direction differs.',
    correct_answer: 'c',
    explanation: 'The defining difference between these two structures is how weight is placed. A blunt cut uses little to no elevation to keep weight at the bottom perimeter. A graduated cut uses controlled elevation to stack weight gradually along a design line, often at the nape or back of the head.',
    difficulty: 'easy',
    order_index: 6,
  },

  // === SECTION 5 — THE BLUNT CUT (4 questions) ===
  {
    id: 'qq-16-007',
    quiz_id: 'quiz-16',
    question: 'In a blunt cut, zero elevation means:',
    answer_a: 'Hair is held straight out from the head at 90 degrees',
    answer_b: 'Hair is lifted overhead at 180 degrees',
    answer_c: 'Hair is not lifted away from the head before cutting',
    answer_d: 'Hair is overdirected away from its natural fall',
    correct_answer: 'c',
    explanation: 'Zero elevation means the hair is combed to its natural falling position and cut without being lifted. This keeps the maximum weight at the perimeter, which is the goal of a blunt cut. Any elevation would begin to remove weight or create layers.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-16-008',
    quiz_id: 'quiz-16',
    question: 'A client asks for a chin-length blunt bob. During the cut, the client\'s head tilts forward and is not corrected. What is the most likely result when the head returns to its normal upright position?',
    answer_a: 'The perimeter will be shorter in the back and longer in the front',
    answer_b: 'The perimeter will be uneven and no longer form a clean horizontal line',
    answer_c: 'The perimeter will have a strong diagonal-forward line',
    answer_d: 'The hair will be overdirected and lose its blunt weight line',
    correct_answer: 'b',
    explanation: 'Head position directly affects the cutting line. When the head tilts forward, the hair falls differently than it does in a neutral position. Cutting in that tilted state produces a line that looks straight at the moment but becomes uneven once the client sits upright.',
    difficulty: 'medium',
    order_index: 8,
  },
  {
    id: 'qq-16-009',
    quiz_id: 'quiz-16',
    question: 'A barber finishes a blunt cut and notices small dips and corners only after blow-drying the hair. Which mistake most likely caused this?',
    answer_a: 'The barber used a round brush instead of a paddle brush',
    answer_b: 'The barber skipped cross-checking the line before drying',
    answer_c: 'The barber applied heat protectant before cutting',
    answer_d: 'The barber used a traveling guide instead of a stationary guide',
    correct_answer: 'b',
    explanation: 'Cross-checking reveals dips, corners, and uneven weight that are not visible when following the original cutting line. Wet hair can also hide small errors that become obvious once the hair is dry and styled. The brush choice, heat protectant, and guide type are not the cause of an uneven blunt perimeter.',
    difficulty: 'medium',
    order_index: 9,
  },
  {
    id: 'qq-16-010',
    quiz_id: 'quiz-16',
    question: 'In a blunt cut, how does changing from a horizontal cutting line to a diagonal-forward cutting line around the face affect the finished shape?',
    answer_a: 'It creates stacked fullness at the nape',
    answer_b: 'It changes the shape around the face or perimeter rather than keeping a strong, even baseline',
    answer_c: 'It removes weight evenly throughout the haircut',
    answer_d: 'It preserves perimeter length while adding interior layers',
    correct_answer: 'b',
    explanation: 'A horizontal cutting line produces a strong, even baseline. A diagonal-forward line changes the direction of the perimeter around the face or other areas, creating a different silhouette while still using low elevation. Stacked fullness, even weight removal, and interior layers are effects of other structures and techniques.',
    difficulty: 'medium',
    order_index: 10,
  },

  // === SECTION 6 — THE GRADUATED CUT (4 questions) ===
  {
    id: 'qq-16-011',
    quiz_id: 'quiz-16',
    question: 'In haircutting, what is the main difference between a traveling guide and a stationary guide?',
    answer_a: 'A traveling guide stays fixed while a stationary guide moves with each section',
    answer_b: 'A traveling guide moves with each new section, while a stationary guide stays in one fixed position',
    answer_c: 'A traveling guide is used only for blunt cuts, while a stationary guide is used only for graduated cuts',
    answer_d: 'A traveling guide controls perimeter length, while a stationary guide controls interior layers',
    correct_answer: 'b',
    explanation: 'A traveling guide moves with each new section, carrying the established length and angle forward through the haircut. A stationary guide stays in one place and is used to maintain a consistent perimeter or weight line in a specific area. Both can be used across different structures depending on the desired result.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-16-012',
    quiz_id: 'quiz-16',
    question: 'A client wants a bob with fullness through the back but a softer overall shape than a one-length cut. Which structure best meets this goal?',
    answer_a: 'Blunt cut',
    answer_b: 'Graduated cut',
    answer_c: 'Uniform-layered cut',
    answer_d: 'Long-layered cut',
    correct_answer: 'b',
    explanation: 'A graduated cut uses controlled elevation to build weight along a design line, creating the stacked fullness the client wants in the back. It is softer overall than a blunt one-length cut because the weight is graduated rather than concentrated in a single heavy perimeter.',
    difficulty: 'medium',
    order_index: 12,
  },
  {
    id: 'qq-16-013',
    quiz_id: 'quiz-16',
    question: 'Why should subsections remain narrow and controlled when cutting a graduated shape?',
    answer_a: 'Narrow sections speed up the haircut by reducing the number of cuts needed',
    answer_b: 'Small sections make it easier to see the angle and maintain even elevation',
    answer_c: 'Narrow sections prevent the client from feeling the comb on the scalp',
    answer_d: 'Small sections allow the barber to skip cross-checking',
    correct_answer: 'b',
    explanation: 'Narrow subsections let the barber clearly see the cutting angle and maintain consistent elevation from one section to the next. Large sections hide errors and make it impossible to control the weight buildup, which leads to an uneven silhouette.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-16-014',
    quiz_id: 'quiz-16',
    question: 'A barber raises the finger angle while cutting a graduated section. What is the most likely effect on the finished silhouette?',
    answer_a: 'The weight buildup will shift higher and the stack will become more pronounced',
    answer_b: 'The perimeter will become blunt and lose all graduation',
    answer_c: 'The hair will be cut at 90 degrees, creating uniform layers',
    answer_d: 'The sections will automatically become traveling guides',
    correct_answer: 'a',
    explanation: 'Finger angle directly controls where weight is built and how the silhouette flows. Changing the finger angle changes the cutting angle, which shifts the weight line and alters the stack. A higher finger angle typically moves the weight buildup higher and changes the curve of the silhouette.',
    difficulty: 'medium',
    order_index: 14,
  },

  // === SECTION 7 — THE UNIFORM LAYERED CUT (2 questions) ===
  {
    id: 'qq-16-015',
    quiz_id: 'quiz-16',
    question: 'A uniform-layered cut relies primarily on which elevation?',
    answer_a: 'Little to no elevation',
    answer_b: '45-degree elevation',
    answer_c: '90-degree elevation',
    answer_d: '180-degree elevation',
    correct_answer: 'c',
    explanation: 'A uniform-layered cut uses 90-degree elevation, holding the hair straight out from the head. This creates equal-length layers and distributes weight evenly throughout the head. Lower elevations keep weight at the perimeter, while 180-degree elevation is used for long layers.',
    difficulty: 'easy',
    order_index: 15,
  },
  {
    id: 'qq-16-016',
    quiz_id: 'quiz-16',
    question: 'A client wants a lighter, more versatile haircut with soft movement and no heavy bottom line. Which structure is most appropriate?',
    answer_a: 'Blunt cut',
    answer_b: 'Graduated cut',
    answer_c: 'Uniform-layered cut',
    answer_d: 'Long-layered cut',
    correct_answer: 'c',
    explanation: 'A uniform-layered cut distributes weight evenly throughout the head, creating movement and styling versatility. It removes the heavy bottom line of a blunt cut and avoids the stacked fullness of a graduated cut. A long-layered cut is better when preserving overall length is the priority.',
    difficulty: 'medium',
    order_index: 16,
  },

  // === SECTION 8 — THE LONG LAYERED CUT (2 questions) ===
  {
    id: 'qq-16-017',
    quiz_id: 'quiz-16',
    question: 'In a long-layered cut, 180-degree elevation means the hair is:',
    answer_a: 'Held straight out from the head',
    answer_b: 'Lifted overhead, parallel to the floor',
    answer_c: 'Combed to its natural fall without lifting',
    answer_d: 'Pulled forward toward the face before cutting',
    correct_answer: 'b',
    explanation: '180-degree elevation lifts the hair straight up and overhead, parallel to the floor. This high elevation allows interior layers to be cut shorter while the perimeter falls to its original length. Lower elevations create different structures and weight placements.',
    difficulty: 'easy',
    order_index: 17,
  },
  {
    id: 'qq-16-018',
    quiz_id: 'quiz-16',
    question: 'Which statement best describes a long-layered cut?',
    answer_a: 'It removes weight evenly throughout using 90-degree elevation',
    answer_b: 'It preserves perimeter length while introducing shorter interior layers for movement',
    answer_c: 'It builds weight at the nape using controlled elevation',
    answer_d: 'It creates a strong, solid perimeter with little to no elevation',
    correct_answer: 'b',
    explanation: 'A long-layered cut keeps the outside edge long while removing interior weight with shorter layers. This creates movement and reduces bulk without sacrificing overall length. The other options describe uniform-layered, graduated, and blunt cuts.',
    difficulty: 'easy',
    order_index: 18,
  },

  // === SECTION 9 — HAIR ANALYSIS (2 questions) ===
  {
    id: 'qq-16-019',
    quiz_id: 'quiz-16',
    question: 'In hair analysis, texture refers to strand diameter, while density refers to:',
    answer_a: 'The direction hair grows from the scalp',
    answer_b: 'The total amount of hair on the head',
    answer_c: 'How much the hair shrinks when dry',
    answer_d: 'The curl pattern of the hair',
    correct_answer: 'b',
    explanation: 'Texture describes the thickness of individual strands: fine, medium, or coarse. Density describes the total amount of hair on the head: thin, medium, or thick. Both must be assessed before choosing section sizes, tension, and cutting techniques.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-16-020',
    quiz_id: 'quiz-16',
    question: 'A curly-haired client brings a photo of a style created on straight hair. What is the most professional response?',
    answer_a: 'Copy the photo exactly because the client knows what they want',
    answer_b: 'Explain how shrinkage will affect the result and adapt the design to the client\'s curl pattern and texture',
    answer_c: 'Refuse the service because the style is impossible on curly hair',
    answer_d: 'Cut the hair wet to match the photo length and let it shrink naturally',
    correct_answer: 'b',
    explanation: 'Curly hair shrinks as it dries, so a straight-hair style cannot be copied exactly. The professional response is to analyze the curl pattern and texture, explain shrinkage honestly, and adapt the design to what will actually work for the client. Refusing the service or copying the photo without explanation would damage trust.',
    difficulty: 'medium',
    order_index: 20,
  },

  // === SECTION 10 — ADVANCED TECHNIQUES (6 questions) ===
  {
    id: 'qq-16-021',
    quiz_id: 'quiz-16',
    question: 'What is overdirection in haircutting?',
    answer_a: 'Cutting hair at 180-degree elevation to preserve perimeter length',
    answer_b: 'Combing hair away from its natural falling position before cutting',
    answer_c: 'Using a razor instead of shears to create soft ends',
    answer_d: 'Removing bulk by sliding partially open shears along a section',
    correct_answer: 'b',
    explanation: 'Overdirection means combing hair away from where it naturally falls before cutting. It preserves length where the hair is pulled from and shifts weight toward where it is pulled to. The other options describe long-layered cutting, razor cutting, and slithering.',
    difficulty: 'medium',
    order_index: 21,
  },
  {
    id: 'qq-16-022',
    quiz_id: 'quiz-16',
    question: 'On which hair types is razor cutting generally inappropriate?',
    answer_a: 'Coarse or thick hair',
    answer_b: 'Fine, fragile, or highly porous hair',
    answer_c: 'Curly or coily hair',
    answer_d: 'Straight hair that has never been colored',
    correct_answer: 'b',
    explanation: 'Razor cutting can fray or weaken fine, fragile, or highly porous strands because the razor slices through the cuticle aggressively. It is better suited to stronger hair types that can tolerate the softening effect without damage.',
    difficulty: 'medium',
    order_index: 22,
  },
  {
    id: 'qq-16-023',
    quiz_id: 'quiz-16',
    question: 'Which texturizing technique uses the tips of the shears to soften blunt lines and remove small amounts of bulk from the ends?',
    answer_a: 'Notching',
    answer_b: 'Slithering',
    answer_c: 'Point cutting',
    answer_d: 'Slicing',
    correct_answer: 'c',
    explanation: 'Point cutting uses the tips of the shears to soften blunt lines and remove small amounts of bulk from the ends without dramatically shortening length. Notching removes weight more aggressively, slithering slides along the section, and slicing is a separate technique not emphasized in the approved deck.',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'qq-16-024',
    quiz_id: 'quiz-16',
    question: 'A client has very thick, heavy hair and needs significant weight release at the perimeter. Which texturizing technique is most appropriate?',
    answer_a: 'Point cutting',
    answer_b: 'Notching',
    answer_c: 'Slithering',
    answer_d: 'Razor cutting',
    correct_answer: 'b',
    explanation: 'Notching removes weight in a spaced, aggressive pattern and is designed for thick, heavy hair that needs substantial weight release. Point cutting is too subtle for significant weight removal, slithering removes only a small amount of bulk, and razor cutting is not designed for aggressive weight removal at the perimeter.',
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-16-025',
    quiz_id: 'quiz-16',
    question: 'A barber wants even, natural fall and balanced weight distribution throughout the haircut. Why should overdirection be avoided in this case?',
    answer_a: 'Overdirection intentionally shifts length and weight away from natural fall',
    answer_b: 'Overdirection always creates graduation',
    answer_c: 'Overdirection removes too much perimeter length',
    answer_d: 'Overdirection requires 180-degree elevation',
    correct_answer: 'a',
    explanation: 'Overdirection is used deliberately to shift length and weight from one area to another. When the goal is balanced, natural fall and even weight distribution, overdirection works against that goal because it moves hair out of its natural position before cutting.',
    difficulty: 'medium',
    order_index: 25,
  },
  {
    id: 'qq-16-026',
    quiz_id: 'quiz-16',
    question: 'A client has dense hair that feels heavy but wants to preserve overall length. Which technique best addresses the goal, and why?',
    answer_a: 'Notching, because it aggressively removes weight from thick hair',
    answer_b: 'Slithering, because it removes a small amount of bulk while preserving length',
    answer_c: 'Point cutting, because it shortens the ends significantly',
    answer_d: 'Razor cutting, because it is safe for all dense hair types',
    correct_answer: 'b',
    explanation: 'Slithering slides partially open shears along a section to remove a small amount of bulk while keeping the overall length intact. Notching would remove too much and change the perimeter. Point cutting primarily softens ends rather than reducing bulk. Razor cutting is not universally safe and is inappropriate for fragile or porous hair.',
    difficulty: 'hard',
    order_index: 26,
  },

  // === SECTION 11 — STYLING & FINISHING (4 questions) ===
  {
    id: 'qq-16-027',
    quiz_id: 'quiz-16',
    question: 'Which statement about thermal styling safety is correct?',
    answer_a: 'Thermal tools can be used on damp hair to speed up drying',
    answer_b: 'Heat protectant is optional for healthy hair',
    answer_c: 'Fine or damaged hair should be styled with lower heat, and tools should keep moving',
    answer_d: 'Thermal tools should be placed directly on the styling station between sections',
    correct_answer: 'c',
    explanation: 'Fine or damaged hair cannot tolerate high heat and should be styled at lower temperatures. Keeping tools moving prevents heat from concentrating in one spot and causing damage. Heat protectant is important for all hair types, thermal tools on damp hair can cause steam damage, and hot tools should rest on a heat-safe mat.',
    difficulty: 'medium',
    order_index: 27,
  },
  {
    id: 'qq-16-028',
    quiz_id: 'quiz-16',
    question: 'At the end of a styling service, what should a barber include in client education?',
    answer_a: 'Only the price of the products used',
    answer_b: 'How to recreate the style at home, which products to use, and how to protect hair from heat',
    answer_c: 'A warning that the style will only look good in the shop',
    answer_d: 'The names of the tools used, but not how to use them',
    correct_answer: 'b',
    explanation: 'Client education should empower the client to recreate the style at home safely. This includes explaining products, blow-dry technique, brush selection, airflow direction, and heat protection. Simply naming prices or tools without instruction does not improve client satisfaction or loyalty.',
    difficulty: 'medium',
    order_index: 28,
  },
  {
    id: 'qq-16-029',
    quiz_id: 'quiz-16',
    question: 'A barber wants to create smoothness and shine during a blow-dry. How should the airflow be directed?',
    answer_a: 'Upward at the roots to create volume',
    answer_b: 'Downward along the hair shaft, following the cuticle direction',
    answer_c: 'Directly into the ends to speed drying',
    answer_d: 'From side to side to increase movement',
    correct_answer: 'b',
    explanation: 'Airflow directed downward along the hair shaft smooths the cuticle and creates shine. Airflow directed upward at the roots creates volume. Side-to-side or end-focused airflow does not produce the smooth, polished finish described in the goal.',
    difficulty: 'medium',
    order_index: 29,
  },
  {
    id: 'qq-16-030',
    quiz_id: 'quiz-16',
    question: 'A barber finishes cutting and immediately dismisses the client without styling. What important opportunity is lost?',
    answer_a: 'The chance to sell additional products',
    answer_b: 'The chance to reveal the true balance, movement, and weight distribution of the cut',
    answer_c: 'The chance to perform the final sanitation steps',
    answer_d: 'The chance to take a before-and-after photo',
    correct_answer: 'b',
    explanation: 'Styling is the final step of the service because it reveals how the haircut truly balances, moves, and behaves. Wet hair can hide uneven layers or heavy spots. Without styling, the barber cannot fully evaluate the cut or show the client the finished result. Sanitation and photos are important, but they do not replace the evaluative purpose of styling.',
    difficulty: 'medium',
    order_index: 30,
  },
]

export default chapter16PremiumQuizQuestions
