import { Flashcard } from '@/types'

// Chapter 18: Haircoloring and Lightening — 50 premium flashcards
export const chapter18PremiumFlashcards: Flashcard[] = [
  {
    id: 'fc-ch18-001',
    standardId: 'CH18-F001',
    chapter_id: 'ch-18',
    front: "Haircoloring",
    back: "The professional service of changing, enhancing, or blending hair color using a product and procedure permitted for the intended use.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch18-002',
    standardId: 'CH18-F002',
    chapter_id: 'ch-18',
    front: "Hair Lightening",
    back: "A service that reduces natural or artificial pigment to create a lighter result. The exact chemistry, lift, and permitted use depend on the lightening system.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-ch18-003',
    standardId: 'CH18-F003',
    chapter_id: 'ch-18',
    front: "Elasticity",
    back: "The hair's ability to stretch and return without breaking. Reduced elasticity can signal compromised hair and should increase caution before a chemical color or lightening service.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch18-004',
    standardId: 'CH18-F004',
    chapter_id: 'ch-18',
    front: "Texture",
    back: "The diameter of an individual hair strand, commonly described as fine, medium, or coarse. Texture can affect saturation and processing behavior, but developer strength and timing must come from the product system.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch18-005',
    standardId: 'CH18-F005',
    chapter_id: 'ch-18',
    front: "Density",
    back: "The amount of hair present in a given area. Density affects sectioning and saturation needs; use subsection sizes that allow complete, even product application rather than a fixed universal measurement.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-ch18-006',
    standardId: 'CH18-F006',
    chapter_id: 'ch-18',
    front: "Porosity",
    back: "The hair's ability to absorb moisture and product. High porosity can contribute to uneven uptake or faster fading, while low porosity can resist penetration; neither automatically justifies stronger developer.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch18-007',
    standardId: 'CH18-F007',
    chapter_id: 'ch-18',
    front: "Eumelanin & Pheomelanin",
    back: "Eumelanin is associated mainly with brown-to-black natural pigment, while pheomelanin contributes red-to-yellow pigment.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-ch18-008',
    standardId: 'CH18-F008',
    chapter_id: 'ch-18',
    front: "Contributing Pigment",
    back: "The underlying warm pigment revealed as natural hair is lightened. It influences tonal planning and the final color result.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch18-009',
    standardId: 'CH18-F009',
    chapter_id: 'ch-18',
    front: "Color Theory & Color Wheel",
    back: "A framework for understanding relationships among colors, including primary, secondary, tertiary, and complementary relationships used in formulation and neutralization.",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-ch18-010',
    standardId: 'CH18-F010',
    chapter_id: 'ch-18',
    front: "Primary & Secondary Colors",
    back: "In traditional haircolor theory, red, yellow, and blue are primary colors; orange, green, and violet are secondary colors formed by combining primary-color relationships.",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-ch18-011',
    standardId: 'CH18-F011',
    chapter_id: 'ch-18',
    front: "Complementary Colors",
    back: "Colors positioned opposite each other on a traditional color wheel. In color formulation, complementary relationships are used to reduce or neutralize unwanted tonal influence.",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch18-012',
    standardId: 'CH18-F012',
    chapter_id: 'ch-18',
    front: "Level System",
    back: "A system for describing how light or dark a hair color is. Many professional lines use numbered levels, but the exact numbering, names, and endpoints can vary by manufacturer.",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-ch18-013',
    standardId: 'CH18-F013',
    chapter_id: 'ch-18',
    front: "Tone, Hue & Saturation",
    back: "Hue names a color family; tone describes its warm or cool character; saturation or intensity describes how concentrated or vivid the color appears.",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch18-014',
    standardId: 'CH18-F014',
    chapter_id: 'ch-18',
    front: "Base Color",
    back: "The dominant tonal character built into a haircolor formula. The color line's technical chart identifies how its bases are intended to influence or neutralize tone.",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch18-015',
    standardId: 'CH18-F015',
    chapter_id: 'ch-18',
    front: "Temporary Haircolor",
    back: "A short-duration color category that primarily deposits color near the hair surface. How quickly it shampoos out varies by formula, hair condition, and use.",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch18-016',
    standardId: 'CH18-F016',
    chapter_id: 'ch-18',
    front: "Semipermanent Haircolor",
    back: "A generally no-lift color category used mainly for deposit and tonal change. Many formulas are direct-dye systems used without developer, but always follow the specific product's directions and longevity claims.",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch18-017',
    standardId: 'CH18-F017',
    chapter_id: 'ch-18',
    front: "Demipermanent Haircolor",
    back: "An oxidative deposit-focused color category commonly used with a dedicated low-strength developer or activator. Lift, gray blending, longevity, and processing are product-system specific.",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-ch18-018',
    standardId: 'CH18-F018',
    chapter_id: 'ch-18',
    front: "Permanent Haircolor / Tint",
    back: "An oxidative color category mixed with its specified developer to create durable artificial pigment and, depending on the system, lift, deposit, or both. New growth later creates a retouch area.",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch18-019',
    standardId: 'CH18-F019',
    chapter_id: 'ch-18',
    front: "Coal-Tar Hair Dye & Allergy-Alert Testing",
    back: "FDA treats coal-tar hair dyes under a special statutory framework requiring specified caution labeling and adequate directions for a preliminary skin test. Follow the product's exact allergy-alert or skin-test directions before use.",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch18-020',
    standardId: 'CH18-F020',
    chapter_id: 'ch-18',
    front: "Metallic, Progressive & Compound Color Compatibility",
    back: "Some progressive or metallic-salt color histories can create compatibility concerns with later oxidative services. Obtain the client's chemical history and follow the planned product's compatibility warnings or prescribed test before proceeding.",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-ch18-021',
    standardId: 'CH18-F021',
    chapter_id: 'ch-18',
    front: "Developer & Volume",
    back: "Hydrogen-peroxide developer supplies oxidizing action in compatible color and lightener systems. Volume expresses developer strength, but actual lift and permitted use depend on the complete product system.",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch18-022',
    standardId: 'CH18-F022',
    chapter_id: 'ch-18',
    front: "Developer Volumes: 10 / 20 / 30 / 40",
    back: "Common developer volumes represent different peroxide strengths. Do not memorize a universal lift result for each volume: approved strength, gray-coverage use, lift, mixing ratio, scalp use, and timing are defined by the manufacturer.",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch18-023',
    standardId: 'CH18-F023',
    chapter_id: 'ch-18',
    front: "Hydrogen Peroxide / Developer Safety",
    back: "Use only the developer, ratio, tools, container, storage method, and processing limits specified by the color or lightener manufacturer. Wear suitable gloves and do not use damaged or compromised packaging.",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch18-024',
    standardId: 'CH18-F024',
    chapter_id: 'ch-18',
    front: "Lightener & Decolorization",
    back: "Lightening systems use oxidation to reduce natural or artificial pigment. As pigment is removed, underlying warm tones may become visible; the exact progression and endpoint vary with the hair and product system.",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-ch18-025',
    standardId: 'CH18-F025',
    chapter_id: 'ch-18',
    front: "Lightener Formats",
    back: "Professional lighteners are sold in formats such as creams, powders, clays, and other systems. Format alone does not determine strength or on-scalp safety; follow the product's allowed developer, application area, ratio, timing, heat, and overlap rules.",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch18-026',
    standardId: 'CH18-F026',
    chapter_id: 'ch-18',
    front: "Toner",
    back: "A color product used to refine or adjust tone, often after lightening. Toner chemistry can be semipermanent, demipermanent, permanent, or another manufacturer-defined system, so testing and application rules come from that product.",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch18-027',
    standardId: 'CH18-F027',
    chapter_id: 'ch-18',
    front: "Activator / Booster",
    back: "A manufacturer-defined additive or oxidizing component used in some color or lightener systems to support development or lift. Use it only when the specific product system directs it and only at the stated amount.",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch18-028',
    standardId: 'CH18-F028',
    chapter_id: 'ch-18',
    front: "Strand Test",
    back: "A controlled test on a small section of hair used to observe how the hair responds and to assess likely tone, integrity, or processing behavior before the full service when the product or hair history calls for it.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-ch18-029',
    standardId: 'CH18-F029',
    chapter_id: 'ch-18',
    front: "Single-Process vs. Double-Process Haircoloring",
    back: "Single-process color aims to reach the planned result in one color application. Double-process work uses a lightening step followed by a separate toning or color step.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-ch18-030',
    standardId: 'CH18-F030',
    chapter_id: 'ch-18',
    front: "Retouch Application & Line of Demarcation",
    back: "New growth can create a visible line between untreated and previously colored hair. A retouch targets new growth according to the product system while avoiding unnecessary overlap onto previously treated hair.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-ch18-031',
    standardId: 'CH18-F031',
    chapter_id: 'ch-18',
    front: "Virgin Application, Tint-Back & Pre-Softening",
    back: "A virgin application treats hair without prior color in the target area; tint-back restores missing tonal depth when darkening lightened hair; pre-softening is used only in color systems that specifically support it for resistant gray.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch18-032',
    standardId: 'CH18-F032',
    chapter_id: 'ch-18',
    front: "Highlighting, Lowlighting & Special-Effect Techniques",
    back: "Highlighting creates lighter selected strands and lowlighting creates darker selected strands. Foils, caps, painting, and other techniques are chosen according to the desired pattern and the product's permitted use.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch18-033',
    standardId: 'CH18-F033',
    chapter_id: 'ch-18',
    front: "Fillers",
    back: "Products or formulation steps used in some color systems to replace missing underlying tone or help equalize an uneven color result. Choose and use them according to the planned target and manufacturer guidance.",
    category: "Corrective & Support Products",
    difficulty: 'medium',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch18-034',
    standardId: 'CH18-F034',
    chapter_id: 'ch-18',
    front: "Allergy-Alert / Skin-Test Safety Rule",
    back: "Follow the product label's allergy-alert or skin-test instructions before use. FDA advises doing a skin test before each hair-dye use; if the test produces a reaction, do not use that dye product.",
    category: "Safety",
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-ch18-035',
    standardId: 'CH18-F035',
    chapter_id: 'ch-18',
    front: "Lightener Safety Rules",
    back: "Do not apply lightener to irritated or damaged scalp tissue or outside the product's permitted application area. Avoid unapproved overlap on previously lightened or sensitized hair, and follow the manufacturer's developer, timing, heat, and rinsing limits.",
    category: "Safety",
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-ch18-036',
    standardId: 'CH18-F036',
    chapter_id: 'ch-18',
    front: "Facial Hair Coloring Safety",
    back: "Use color on a beard or mustache only when the product manufacturer expressly permits that intended facial-hair use. Follow its allergy-alert, skin-protection, timing, rinsing, and eye-area warnings exactly.",
    category: "Safety",
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch18-037',
    standardId: 'CH18-F037',
    chapter_id: 'ch-18',
    front: "Tertiary Colors",
    back: "Intermediate colors formed from a primary-secondary relationship, such as blue-green, blue-violet, red-violet, red-orange, yellow-green, and yellow-orange.",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch18-038',
    standardId: 'CH18-F038',
    chapter_id: 'ch-18',
    front: "Neutralization with Complementary Colors",
    back: "Complementary color relationships are used to reduce unwanted tonal influence. The exact formula still depends on level, underlying pigment, target tone, and the professional color system.",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch18-039',
    standardId: 'CH18-F039',
    chapter_id: 'ch-18',
    front: "Natural Hair Color / Gray & White Hair",
    back: "Natural color comes from melanin pigments. Gray and white appearance reflects reduced or absent visible natural pigment, while texture, porosity, and resistance can still vary from client to client.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-ch18-040',
    standardId: 'CH18-F040',
    chapter_id: 'ch-18',
    front: "Haircolor",
    back: "A product or formulation used to change, enhance, blend, or refine the color of hair. Product category and intended use determine whether it deposits, lifts, tones, or performs another color function.",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-ch18-041',
    standardId: 'CH18-F041',
    chapter_id: 'ch-18',
    front: "Oxidative vs. Nonoxidative Color",
    back: "Oxidative color develops through an oxidation system, usually with a specified developer or activator. Nonoxidative/direct-dye systems generally deposit preformed color without oxidative development; classify the actual product by its manufacturer instructions.",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch18-042',
    standardId: 'CH18-F042',
    chapter_id: 'ch-18',
    front: "Allergy-Alert / Skin-Test Procedure",
    back: "Use the exact product-label procedure. FDA consumer guidance gives an example of applying a small amount behind the ear or inside the elbow and observing it for two days, but the controlling salon procedure is the product's own directions.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-ch18-043',
    standardId: 'CH18-F043',
    chapter_id: 'ch-18',
    front: "Temporary Color Application",
    back: "Temporary color application depends on the product format. Apply, process, rinse, or style only as the label directs rather than assuming every rinse, spray, mousse, gel, or crayon uses the same procedure.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch18-044',
    standardId: 'CH18-F044',
    chapter_id: 'ch-18',
    front: "Semipermanent Color Application",
    back: "Prepare and apply semipermanent color according to that product's directions. Do not assume every semipermanent formula uses the same hair preparation, developer rule, processing time, wash-count longevity, or allergy-test procedure.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch18-045',
    standardId: 'CH18-F045',
    chapter_id: 'ch-18',
    front: "Demipermanent Color Application",
    back: "Use the dedicated developer or activator, ratio, hair preparation, processing time, and allergy-alert procedure specified for the demipermanent system. Do not rely on a universal shampoo-count or timing rule.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch18-046',
    standardId: 'CH18-F046',
    chapter_id: 'ch-18',
    front: "Permanent Color Virgin & Retouch Application",
    back: "Virgin and retouch placement depends on the color system, target result, existing color, and hair condition. Retouches generally focus on new growth while avoiding unnecessary overlap onto previously treated lengths.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch18-047',
    standardId: 'CH18-F047',
    chapter_id: 'ch-18',
    front: "Mustache and Beard Coloring Procedure",
    back: "Use only a product specifically permitted for the intended beard or mustache application. Follow its skin-protection, allergy-alert, application, timing, rinsing, and eye-area precautions rather than adapting scalp-hair directions.",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch18-048',
    standardId: 'CH18-F048',
    chapter_id: 'ch-18',
    front: "Scalp Safety & Integrity Check",
    back: "Before coloring, inspect the scalp for visible irritation, sunburn, abrasions, open lesions, or other compromised tissue. Do not diagnose disease; postpone the chemical service when the scalp condition conflicts with product or FDA safety guidance.",
    category: "Safety",
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-ch18-049',
    standardId: 'CH18-F049',
    chapter_id: 'ch-18',
    front: "Federal Hair-Dye Labeling & Preliminary Test",
    back: "Federal law gives qualifying coal-tar hair dyes a special treatment when they carry the required caution statement and adequate directions for a preliminary skin test. Do not generalize that framework into one universal 24–48-hour rule for every haircolor product.",
    category: "Safety",
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch18-050',
    standardId: 'CH18-F050',
    chapter_id: 'ch-18',
    front: "General Chemical Precautions",
    back: "Follow the manufacturer's complete directions for gloves, tools, bowls, ventilation, mixing, timing, rinsing, storage, disposal, and incompatible-product warnings. Do not improvise combinations the product system does not authorize.",
    category: "Safety",
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },
]