import { QuizQuestion } from '@/types'

// Chapter 19: Preparing for Licensure and Employment — 15 premium quiz questions
export const chapter19PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-19-01',
    standardId: 'CH19-Q01',
    quiz_id: 'quiz-19',
    question: "What is the first step toward employment success as a barber?",
    answer_a: "Building a large social media following",
    answer_b: "Passing the state board exam and becoming licensed",
    answer_c: "Completing a professional employment portfolio",
    answer_d: "Renting a booth at a local barbershop",
    correct_answer: 'b',
    explanation: "Common mistake: Thinking that marketing materials or portfolio development come before licensure. Correct understanding: You must be licensed to be hired as a barber, so passing the state board exam and obtaining your license is the first concrete step toward employment success. Why it matters: Employers cannot legally hire unlicensed barbers in most states, so all other job-search efforts depend on first achieving licensure. Review: Introduction and Why Study Preparing for Licensure and Employment (p. 707).",
    difficulty: 'easy',
    learningObjective: 'LO-1',
    order_index: 1,
  },
  {
    id: 'qq-19-02',
    standardId: 'CH19-Q02',
    quiz_id: 'quiz-19',
    question: "Which factor is most important in determining how well you perform on a licensing examination?",
    answer_a: "Having a positive relationship with the examiner",
    answer_b: "Wearing professional clothing to the test center",
    answer_c: "Mastery of course content",
    answer_d: "Memorizing every vocabulary word in the textbook",
    correct_answer: 'c',
    explanation: "Common mistake: Believing that test-taking tricks or appearance matter more than actual knowledge. Correct understanding: While test-taking skills, rest, and professional dress help, the most important factor is mastery of course content. Why it matters: Strong test strategies cannot substitute for knowing the material; they only help you demonstrate what you know. Review: Prepare for Licensure (p. 709).",
    difficulty: 'easy',
    learningObjective: 'LO-1',
    order_index: 2,
  },
  {
    id: 'qq-19-03',
    standardId: 'CH19-Q03',
    quiz_id: 'quiz-19',
    question: "Which of the following is usually evaluated during the practical barber licensing examination?",
    answer_a: "Business accounting and tax preparation",
    answer_b: "Creating social media advertisements",
    answer_c: "Negotiating employment contracts",
    answer_d: "Haircutting, shaving, shampooing, and infection control",
    correct_answer: 'd',
    explanation: "Common mistake: Confusing business-management topics with the hands-on skills tested on the practical exam. Correct understanding: Practical exams typically evaluate haircutting, shaving, shampooing, infection control, and sometimes blowdrying or chemical services. Why it matters: Knowing what will be tested helps you focus practice on the correct procedures and safety protocols. Review: The Practical Exam (p. 713).",
    difficulty: 'medium',
    learningObjective: 'LO-1',
    order_index: 3,
  },
  {
    id: 'qq-19-04',
    standardId: 'CH19-Q04',
    quiz_id: 'quiz-19',
    question: "Which personal characteristic is described as the compass that keeps you on course over the long haul of your career?",
    answer_a: "Motivation",
    answer_b: "Enthusiasm",
    answer_c: "Integrity",
    answer_d: "Work ethic",
    correct_answer: 'c',
    explanation: "Common mistake: Choosing motivation or enthusiasm because they are positive career traits. Correct understanding: Integrity is described as the compass that keeps you on course over the long haul of your career because it reflects your commitment to moral and artistic values. Why it matters: Integrity builds trust with employers and clients and guides professional decisions over time. Review: How to Get the Job You Want (p. 716).",
    difficulty: 'easy',
    learningObjective: 'LO-1',
    order_index: 4,
  },
  {
    id: 'qq-19-05',
    standardId: 'CH19-Q05',
    quiz_id: 'quiz-19',
    question: "In the barbering business, having a strong work ethic means:",
    answer_a: "Working the longest hours possible every week",
    answer_b: "Taking pride in your work and consistently doing a good job for clients, employer, and team",
    answer_c: "Accepting every client regardless of your skill level",
    answer_d: "Focusing only on technical skills and ignoring communication",
    correct_answer: 'b',
    explanation: "Common mistake: Equating work ethic with simply working long hours. Correct understanding: A strong work ethic means taking pride in your work and committing yourself to consistently doing a good job for your clients, employer, and barbershop team. Why it matters: Quality, reliability, and consistency matter more to employers and clients than the number of hours clocked. Review: How to Get the Job You Want (p. 716).",
    difficulty: 'easy',
    learningObjective: 'LO-1',
    order_index: 5,
  },
  {
    id: 'qq-19-06',
    standardId: 'CH19-Q06',
    quiz_id: 'quiz-19',
    question: "What is the best definition of transferable skills?",
    answer_a: "Skills that can be transferred from one client to another during a service",
    answer_b: "Skills mastered at other jobs that can be put to use in a new position",
    answer_c: "Skills that are listed on a state barber license",
    answer_d: "Skills that are only useful in barbershops",
    correct_answer: 'b',
    explanation: "Common mistake: Thinking transferable skills are technical barbering skills passed between jobs. Correct understanding: Transferable skills are skills mastered at other jobs that can be put to use in a new position, such as customer-service experience from restaurant work. Why it matters: New graduates can strengthen a résumé by showing how past jobs developed useful, transferable abilities. Review: Résumé Development (p. 716).",
    difficulty: 'easy',
    learningObjective: 'LO-1',
    order_index: 6,
  },
  {
    id: 'qq-19-07',
    standardId: 'CH19-Q07',
    quiz_id: 'quiz-19',
    question: "Approximately how long does an employer typically spend scanning a résumé before deciding whether to grant an interview?",
    answer_a: "About 20 seconds",
    answer_b: "About 5 minutes",
    answer_c: "About 30 minutes",
    answer_d: "About 1 hour",
    correct_answer: 'a',
    explanation: "Common mistake: Assuming employers study résumés in detail before making decisions. Correct understanding: Employers typically scan a résumé for about 20 seconds before deciding whether to grant an interview. Why it matters: Because you have very little time to make an impression, your résumé must be concise, achievement-focused, and visually organized. Review: Résumé Development (p. 716).",
    difficulty: 'medium',
    learningObjective: 'LO-1',
    order_index: 7,
  },
  {
    id: 'qq-19-08',
    standardId: 'CH19-Q08',
    quiz_id: 'quiz-19',
    question: "What is the primary purpose of a cover letter when applying for a barbering position?",
    answer_a: "To request your desired salary in writing",
    answer_b: "To introduce yourself to the employer and identify the position you are seeking",
    answer_c: "To replace the résumé when applying online",
    answer_d: "To list every job you have ever held",
    correct_answer: 'b',
    explanation: "Common mistake: Treating the cover letter as a salary request or a repeat of the entire résumé. Correct understanding: A cover letter is used to introduce yourself to the employer and to identify the position you are seeking. Why it matters: A clear, professional cover letter encourages the employer to read your résumé and consider you for an interview. Review: The Dos and Don'ts of Résumés (p. 717).",
    difficulty: 'medium',
    learningObjective: 'LO-2',
    order_index: 8,
  },
  {
    id: 'qq-19-09',
    standardId: 'CH19-Q09',
    quiz_id: 'quiz-19',
    question: "Which item is an essential element of a strong employment portfolio?",
    answer_a: "A list of your favorite barbering celebrities",
    answer_b: "Before-and-after photographs of services you have performed",
    answer_c: "Copies of every assignment completed in school",
    answer_d: "Your personal social media passwords",
    correct_answer: 'b',
    explanation: "Common mistake: Filling a portfolio with too much unrelated material. Correct understanding: A strong employment portfolio includes diplomas, awards, résumé, reference letters, certificates, before-and-after photos, and a career statement. Why it matters: Before-and-after photos provide visual proof of your skills and are among the most persuasive items for potential employers. Review: Employment Portfolio (p. 719).",
    difficulty: 'medium',
    learningObjective: 'LO-2',
    order_index: 9,
  },
  {
    id: 'qq-19-10',
    standardId: 'CH19-Q10',
    quiz_id: 'quiz-19',
    question: "When should you begin your barbering job search?",
    answer_a: "Only after you have been licensed for at least one year",
    answer_b: "The day after graduation",
    answer_c: "Before graduation so you can compare options carefully",
    answer_d: "Whenever you feel ready, with no specific timeline",
    correct_answer: 'c',
    explanation: "Common mistake: Waiting until after graduation to look for work. Correct understanding: You should begin researching the job market before graduation so you can investigate options carefully instead of accepting the first offer out of desperation. Why it matters: Starting early gives you time to network, visit shops, and target employers that match your career goals. Review: Targeting the Establishment (p. 720).",
    difficulty: 'medium',
    learningObjective: 'LO-2',
    order_index: 10,
  },
  {
    id: 'qq-19-11',
    standardId: 'CH19-Q11',
    quiz_id: 'quiz-19',
    question: "After visiting a barbershop for research, what is the most professional follow-up action?",
    answer_a: "Wait for the owner to contact you first",
    answer_b: "Send a handwritten thank-you note or e-mail",
    answer_c: "Post a public review on social media immediately",
    answer_d: "Ask the owner for a job before leaving",
    correct_answer: 'b',
    explanation: "Common mistake: Failing to follow up or asking for a job too aggressively during the visit. Correct understanding: After a barbershop visit, you should send a handwritten note or e-mail thanking the representative for their time, even if you do not expect to seek employment there. Why it matters: Professional follow-up builds your network and leaves a positive impression without burning bridges. Review: The Barbershop Visit (p. 722).",
    difficulty: 'medium',
    learningObjective: 'LO-2',
    order_index: 11,
  },
  {
    id: 'qq-19-12',
    standardId: 'CH19-Q12',
    quiz_id: 'quiz-19',
    question: "What should you do before an interview if you are unsure of the barbershop's location?",
    answer_a: "Ask the interviewer to send a ride",
    answer_b: "Do a test drive or visit the location the day before",
    answer_c: "Arrive 30 minutes early without checking the route",
    answer_d: "Call the shop repeatedly on the day of the interview",
    correct_answer: 'b',
    explanation: "Common mistake: Relying on GPS alone on the day of the interview without checking the route in advance. Correct understanding: If you are unsure of the location, do a test drive or visit the day before so you can arrive early and avoid delays. Why it matters: Arriving late or flustered creates a poor first impression; punctuality and preparation demonstrate professionalism. Review: Interview Preparation and The Interview (pp. 724, 726).",
    difficulty: 'medium',
    learningObjective: 'LO-2',
    order_index: 12,
  },
  {
    id: 'qq-19-13',
    standardId: 'CH19-Q13',
    quiz_id: 'quiz-19',
    question: "Which approach to interview attire and grooming is most professional?",
    answer_a: "Wear the trendiest outfit possible regardless of the shop's culture",
    answer_b: "Dress professionally in outfits that fit the barbershop's style culture and ensure grooming is neat",
    answer_c: "Arrive with visible earbuds and a coffee in hand",
    answer_d: "Choose large, eye-catching accessories to stand out from other applicants",
    correct_answer: 'b',
    explanation: "Common mistake: Treating the interview as a fashion show or ignoring the shop's culture. Correct understanding: Your appearance is crucial in the barbering industry. Choose professional, fashionable, flattering outfits that match the shop's style culture, keep nails and hair well groomed, use subtle fragrance, and avoid noisy or oversized accessories. Why it matters: Employers judge whether you will fit their brand and clientele within seconds of meeting you; sloppy or mismatched attire can cost you the position. Review: Interview Wardrobe (p. 724).",
    difficulty: 'hard',
    learningObjective: 'LO-3',
    order_index: 13,
  },
  {
    id: 'qq-19-14',
    standardId: 'CH19-Q14',
    quiz_id: 'quiz-19',
    question: "Which of the following is considered an illegal interview question?",
    answer_a: "Are you authorized to work in the United States?",
    answer_b: "What days and hours are you available for work?",
    answer_c: "What is your native language?",
    answer_d: "Are you over the age of 18?",
    correct_answer: 'c',
    explanation: "Common mistake: Thinking employers can ask anything about background or origin. Correct understanding: 'What is your native language?' is an illegal question related to national origin. The legal alternative is 'In which languages are you fluent?' Why it matters: Knowing which questions are illegal helps you respond professionally and protect your rights without being confrontational. Review: Legal Aspects of the Employment Interview (p. 728).",
    difficulty: 'hard',
    learningObjective: 'LO-3',
    order_index: 14,
  },
  {
    id: 'qq-19-15',
    standardId: 'CH19-Q15',
    quiz_id: 'quiz-19',
    question: "When presented with an employment contract such as a noncompete agreement, what is the most prudent professional action?",
    answer_a: "Sign it immediately to show enthusiasm",
    answer_b: "Review it carefully and consult an attorney if any terms are unclear",
    answer_c: "Ask a coworker to sign on your behalf",
    answer_d: "Ignore the written terms because verbal promises are legally binding",
    correct_answer: 'b',
    explanation: "Common mistake: Signing a contract quickly to appear eager, or assuming verbal promises override the written agreement. Correct understanding: Employers can legally require contracts, such as noncompete or confidentiality agreements. Take the contract home, read it completely, and consult a labor-law attorney before signing if anything is unclear. Why it matters: A signed contract can restrict where you work, whether you can contact clients, and other rights; understanding it protects your career and avoids legal disputes. Review: Employee Contracts (p. 729).",
    difficulty: 'hard',
    learningObjective: 'LO-3',
    order_index: 15,
  },
]
