// Chapter 15: Men's Hair Replacement — PREMIUM MCQ QUIZ
// 72 questions generated STRICTLY from Chapter 15 premium flashcards and curriculum
// Randomized question selection and answer order per attempt
// The Restoration Studio Certification Exam

import { QuizQuestion } from '@/types'

// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// CHAPTER 15: FULL QUESTION BANK (72 questions)
// Generated from chapter-15-premium-flashcards.ts
// NOTE: The app randomizes answer order per attempt; correct_answer tracks the text
// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const chapter15PremiumQuizQuestions: QuizQuestion[] = [
  // === TERMINOLOGY & HISTORY (4 questions) ===
  {
    id: 'qq-15-001',
    quiz_id: 'quiz-15',
    question: "What is the modern professional term for a non-surgical hair replacement product?",
    answer_a: 'Hair replacement system or hair solution',
    answer_b: 'Toupee',
    answer_c: 'Wig cap',
    answer_d: 'Hair graft',
    correct_answer: 'a',
    explanation: '“Hair replacement system” and “hair solution” are modern professional terms for nonsurgical hair replacement products and services.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-15-002',
    quiz_id: 'quiz-15',
    question: "Why should the term 'toupee' be avoided in modern client consultations?",
    answer_a: 'It carries stigma from outdated technology and obvious appearance',
    answer_b: 'It is a trademarked term requiring licensing fees',
    answer_c: "It is only used for women's hairpieces",
    answer_d: 'It is the correct medical term for surgical implants',
    correct_answer: 'a',
    explanation: '"Toupee" carries stigma from outdated technology. Modern clients may react negatively to a term associated with unnatural, detectable hairpieces.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-15-003',
    quiz_id: 'quiz-15',
    question: "What was the original meaning of the term 'toupee'?",
    answer_a: 'The foretop — a section of natural hair grown long to blend with a wig',
    answer_b: 'A full wig covering the entire scalp',
    answer_c: 'A surgical hair implant procedure',
    answer_d: 'A type of adhesive used for attachment',
    correct_answer: 'a',
    explanation: 'The foretop was a section of natural hair grown long to blend with a wig. It evolved into the toupee of the 18th century. The term originally described the blending section, not the wig itself.',
    difficulty: 'medium',
    order_index: 3,
  },
  {
    id: 'qq-15-004',
    quiz_id: 'quiz-15',
    question: 'Why is hair replacement a specialized service worth studying?',
    answer_a: 'It combines consultation, fitting, customization, maintenance, and long-term client care',
    answer_b: 'It is legally required for every barbering license',
    answer_c: 'It replaces the need to learn haircutting and styling',
    answer_d: 'It is only used for surgical hair restoration',
    correct_answer: 'a',
    explanation: 'Hair replacement is a specialized barbering service that combines consultation, fitting, customization, maintenance, and ongoing client care.',
    difficulty: 'easy',
    order_index: 4,
  },

  // === CONSULTATION (5 questions) ===
  {
    id: 'qq-15-005',
    quiz_id: 'quiz-15',
    question: "Where should hair replacement consultations take place?",
    answer_a: 'In a setting that protects the client’s privacy and dignity',
    answer_b: 'At the front desk during check-in',
    answer_c: 'In the open shop where other barbers can advise',
    answer_d: 'Over the phone before the appointment',
    correct_answer: 'a',
    explanation: 'Use a private or otherwise discreet setting where sensitive hair-loss details cannot be overheard by unrelated clients.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-15-006',
    quiz_id: 'quiz-15',
    question: "What does the LAB MED framework stand for in hair replacement consultations?",
    answer_a: 'Lifestyle, Age, Budget, Medical history, Expectations, Daily maintenance',
    answer_b: 'Length, Angle, Base, Material, Edge, Density',
    answer_c: 'Look, Appearance, Blend, Match, Evaluate, Design',
    answer_d: 'License, Accreditation, Bonding, Measurement, Evaluation, Delivery',
    correct_answer: 'a',
    explanation: 'LAB MED stands for Lifestyle, Age, Budget, Medical history, Expectations, and Daily maintenance. These six factors guide every professional consultation.',
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-15-007',
    quiz_id: 'quiz-15',
    question: "A 68-year-old client wants jet-black hair styled like a 25-year-old celebrity. What is your professional obligation?",
    answer_a: 'Explain why the request will look unnatural and recommend a more appropriate option',
    answer_b: 'Give him exactly what he wants to keep the sale',
    answer_c: 'Refuse service and ask him to leave',
    answer_d: 'Tell him his age makes him unsuitable for any system',
    correct_answer: 'a',
    explanation: 'Giving an unrealistic system damages your reputation and the client\'s dignity. Educate with respect and recommend a more appropriate option. Never promise what you cannot deliver.',
    difficulty: 'medium',
    order_index: 7,
  },
  {
    id: 'qq-15-008',
    quiz_id: 'quiz-15',
    question: "Why is age an important factor in hair replacement consultation?",
    answer_a: 'Age can inform style goals and expectations, but recommendations should remain individualized',
    answer_b: 'Only clients over 40 are eligible for hair replacement',
    answer_c: 'Age determines the price of the system',
    answer_d: 'Younger clients are not allowed to purchase systems',
    correct_answer: 'a',
    explanation: 'Age can be one consultation factor, but style and color choices should be based on the individual client’s goals, features, existing hair, and expectations rather than stereotypes.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-15-009',
    quiz_id: 'quiz-15',
    question: "A regular client says, 'I\'m starting to look like my father.' What is the most professional response?",
    answer_a: 'Acknowledge his comment and ask if he would like to discuss options in private',
    answer_b: 'Laugh and agree that baldness runs in families',
    answer_c: 'Immediately show him sample systems and pricing',
    answer_d: 'Tell him hair replacement is too expensive for his situation',
    correct_answer: 'a',
    explanation: 'You validated his concern, offered privacy, and invited further conversation without pressure. This respects his dignity while opening the door to a professional consultation.',
    difficulty: 'medium',
    order_index: 9,
  },

  // === ETHICS & MARKETING (3 questions) ===
  {
    id: 'qq-15-010',
    quiz_id: 'quiz-15',
    question: 'What is required before using a client photo for marketing?',
    answer_a: 'Documented permission that meets applicable privacy and advertising requirements',
    answer_b: 'Permission only when the image is posted on social media',
    answer_c: 'No documentation when the client is a friend',
    answer_d: 'Permission only for paid advertising',
    correct_answer: 'a',
    explanation: 'Use client photos only with documented permission that meets applicable privacy, advertising, and recordkeeping requirements.',
    difficulty: 'easy',
    order_index: 10,
  },
  {
    id: 'qq-15-011',
    quiz_id: 'quiz-15',
    question: "How should sample systems be maintained in the shop?",
    answer_a: 'Shampoo after every client who tries it on, style fresh, and replace when worn',
    answer_b: 'Leave them on a shelf for clients to examine on their own',
    answer_c: 'Only clean them once per month regardless of use',
    answer_d: 'Let clients take them home for overnight trials',
    correct_answer: 'a',
    explanation: 'The sample is a silent salesperson. Shampoo after every client who tries it on, style it fresh, and replace when it shows wear.',
    difficulty: 'easy',
    order_index: 11,
  },
  {
    id: 'qq-15-012',
    quiz_id: 'quiz-15',
    question: 'Which approach can support marketing for hair replacement services?',
    answer_a: 'Authentic client education, referrals, and appropriately permitted before-and-after work',
    answer_b: 'Television commercials',
    answer_c: 'Billboard advertising',
    answer_d: 'Direct mail campaigns',
    correct_answer: 'a',
    explanation: 'Educational content, referrals, in-shop examples, and client images used with proper permission can support marketing without relying on unsupported “most effective” claims.',
    difficulty: 'easy',
    order_index: 12,
  },

  // === SCOPE OF PRACTICE (4 questions) ===
  {
    id: 'qq-15-013',
    quiz_id: 'quiz-15',
    question: 'Which activity may fall within a barber’s cosmetic hair-replacement role, subject to local scope rules?',
    answer_a: 'Measuring, fitting, cutting, styling, cleaning, and maintaining systems',
    answer_b: 'Diagnosing the medical cause of hair loss',
    answer_c: 'Choosing prescription medication for a client',
    answer_d: 'Performing hair transplantation surgery',
    correct_answer: 'a',
    explanation: 'Cosmetic hair-replacement services may include measuring, fitting, cutting, styling, cleaning, and maintenance, but permitted scope varies by jurisdiction.',
    difficulty: 'easy',
    order_index: 13,
  },
  {
    id: 'qq-15-014',
    quiz_id: 'quiz-15',
    question: 'A client asks which Minoxidil formulation and schedule to use. How should a barber respond?',
    answer_a: 'Explain that formulations differ and refer the client to product labeling and an appropriate licensed healthcare professional',
    answer_b: 'Recommend the strongest formulation because it works faster',
    answer_c: 'Choose a starting dose based on the client’s age',
    answer_d: 'Claim that barbers may not discuss any general information about the product',
    correct_answer: 'a',
    explanation: 'A barber may provide general educational information but should not choose a formulation or dosing schedule for a client.',
    difficulty: 'medium',
    order_index: 14,
  },
  {
    id: 'qq-15-015',
    quiz_id: 'quiz-15',
    question: 'Which action crosses an appropriate professional boundary for a barber?',
    answer_a: 'Giving individualized prescription-medication dosing advice',
    answer_b: 'Cleaning a client’s hair replacement system',
    answer_c: 'Cutting and blending a stock system',
    answer_d: 'Referring a medical question to an appropriate licensed healthcare professional',
    correct_answer: 'a',
    explanation: 'Individualized medication directions are medical guidance. Cosmetic services and general education should remain separate from diagnosis, prescribing, and dosing advice.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-15-016',
    quiz_id: 'quiz-15',
    question: "What is the professional boundary when discussing surgical hair restoration with clients?",
    answer_a: 'Discuss general options and refer medical or surgical decisions to an appropriately licensed healthcare professional',
    answer_b: 'Choose the surgical procedure that best fits the client’s budget',
    answer_c: 'Discourage every surgical option as unsafe',
    answer_d: 'Perform a minor surgical procedure if the client signs a waiver',
    correct_answer: 'a',
    explanation: 'Hair transplantation and other surgical restoration procedures are medical services. A barber can discuss general concepts and refer the client appropriately.',
    difficulty: 'easy',
    order_index: 16,
  },

  // === ALTERNATIVE TREATMENTS (4 questions) ===
  {
    id: 'qq-15-017',
    quiz_id: 'quiz-15',
    question: 'Which group contains nonsurgical options a barber may discuss in general terms?',
    answer_a: 'Cosmetic cover-up fibers, Minoxidil, and Finasteride',
    answer_b: 'Hair transplantation, scalp reduction, and flap surgery',
    answer_c: 'Bonding, tape attachment, and spirit gum',
    answer_d: 'Human hair, synthetic hair, and mixed hair',
    correct_answer: 'a',
    explanation: 'Cosmetic fibers and medication-based options are nonsurgical. Medication suitability and use remain medical questions for verified labeling and a licensed healthcare professional.',
    difficulty: 'easy',
    order_index: 17,
  },
  {
    id: 'qq-15-018',
    quiz_id: 'quiz-15',
    question: 'What should a barber understand about different Minoxidil products?',
    answer_a: 'Formulations and directions differ, so individualized selection should follow verified labeling and medical guidance',
    answer_b: 'The strongest formulation is always appropriate for every client',
    answer_c: 'All formulations have identical directions and approved uses',
    answer_d: 'A barber should create a dosing schedule based on hair-loss severity',
    correct_answer: 'a',
    explanation: 'Minoxidil products can differ in formulation, strength, directions, and approved use. Do not turn those differences into individualized medication advice.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-15-019',
    quiz_id: 'quiz-15',
    question: 'What is the safest response when a client asks about Finasteride risks?',
    answer_a: 'Explain that it is a prescription medication and refer individualized risk questions to an appropriate licensed healthcare professional',
    answer_b: 'Provide a short fixed list of side effects and assure the client no others matter',
    answer_c: 'Tell the client to change the dose if side effects occur',
    answer_d: 'Recommend stopping or starting the medication based on the barber’s judgment',
    correct_answer: 'a',
    explanation: 'Benefits, risks, contraindications, and individualized use of a prescription medication belong with an appropriate licensed healthcare professional.',
    difficulty: 'medium',
    order_index: 19,
  },
  {
    id: 'qq-15-020',
    quiz_id: 'quiz-15',
    question: 'What is a micrograft in hair transplantation?',
    answer_a: 'A small follicular graft used in a medical hair-transplant procedure',
    answer_b: 'A photograph of the scalp taken before surgery',
    answer_c: 'An adhesive used to attach transplanted hair',
    answer_d: 'A barbering tool used to cut the scalp',
    correct_answer: 'a',
    explanation: 'A micrograft is a small follicular graft used in hair transplantation. Technique, candidacy, risks, and expected durability are medical matters.',
    difficulty: 'medium',
    order_index: 20,
  },

  // === HAIR MATERIALS (5 questions) ===
  {
    id: 'qq-15-021',
    quiz_id: 'quiz-15',
    question: "What are the three main types of hair used in replacement systems?",
    answer_a: 'Human hair, synthetic hair, and mixed hair',
    answer_b: 'Straight, wavy, and curly hair',
    answer_c: 'Blonde, brunette, and red hair',
    answer_d: 'Long, medium, and short hair',
    correct_answer: 'a',
    explanation: 'The three main types are human hair, synthetic hair, and mixed hair (human blended with synthetic or animal fibers).',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-15-022',
    quiz_id: 'quiz-15',
    question: "What is Kanekalon?",
    answer_a: 'A synthetic fiber commonly used in ready-to-wear wigs and hair systems',
    answer_b: 'A type of human hair sourced from Asia',
    answer_c: 'A medical adhesive for bonding systems',
    answer_d: 'A brand of hair transplantation equipment',
    correct_answer: 'a',
    explanation: 'Kanekalon is a synthetic fiber used in wigs and hair systems. Styling, heat, and chemical-care limits depend on the specific product and manufacturer guidance.',
    difficulty: 'easy',
    order_index: 22,
  },
  {
    id: 'qq-15-023',
    quiz_id: 'quiz-15',
    question: 'Which statement about human hair in a replacement system is most accurate?',
    answer_a: 'It can offer natural-looking texture and movement, but heat and chemical services depend on the specific system and manufacturer guidance',
    answer_b: 'It is always less expensive than synthetic hair',
    answer_c: 'It never fades or responds to environmental exposure',
    answer_d: 'It requires no maintenance or styling',
    correct_answer: 'a',
    explanation: 'Human hair can provide natural-looking texture and movement, but processing history, base construction, and manufacturer guidance determine appropriate heat and chemical services.',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'qq-15-024',
    quiz_id: 'quiz-15',
    question: 'Which statement about synthetic hair is most accurate?',
    answer_a: 'Its appearance and chemical/heat limits depend on the specific fiber and product',
    answer_b: 'It always oxidizes and fades quickly in sunlight',
    answer_c: 'It can never hold a preset style',
    answer_d: 'It is always more expensive than human hair',
    correct_answer: 'a',
    explanation: 'Synthetic fibers differ by product. Avoid universal claims about gloss, fading, heat, or chemical tolerance without checking the specific system.',
    difficulty: 'easy',
    order_index: 24,
  },
  {
    id: 'qq-15-025',
    quiz_id: 'quiz-15',
    question: "What is root-turning and why is it important?",
    answer_a: 'Sorting hair so cuticles point toward the ends to prevent tangling',
    answer_b: 'Turning the hair system inside out for cleaning',
    answer_c: 'Rotating the system 180 degrees for even wear',
    answer_d: 'A technique for attaching hair to the base',
    correct_answer: 'a',
    explanation: 'Root-turning sorts hair so the cuticle points toward the ends in natural growth direction. This prevents tangling and matting because cuticles flow correctly.',
    difficulty: 'medium',
    order_index: 25,
  },

  // === BASE CONSTRUCTION (5 questions) ===
  {
    id: 'qq-15-026',
    quiz_id: 'quiz-15',
    question: "What are the five main base materials for hair replacement systems?",
    answer_a: 'Mesh/net, polyurethane, lace, thin skin, and combination',
    answer_b: 'Cotton, silk, wool, nylon, and polyester',
    answer_c: 'Metal, plastic, rubber, foam, and fabric',
    answer_d: 'Leather, suede, canvas, mesh, and vinyl',
    correct_answer: 'a',
    explanation: 'Common base constructions include mesh/net, polyurethane, lace, thin skin/onion skin, and combination bases. Their properties vary by material and design.',
    difficulty: 'easy',
    order_index: 26,
  },
  {
    id: 'qq-15-027',
    quiz_id: 'quiz-15',
    question: 'What is a practical advantage of mesh or net bases?',
    answer_a: 'Open-weave construction can improve airflow and comfort',
    answer_b: 'They are completely waterproof for swimming',
    answer_c: 'They always provide the strongest adhesive bond',
    answer_d: 'They are invisible in every hairline application',
    correct_answer: 'a',
    explanation: 'Mesh/net construction can improve airflow and comfort. Durability, stretch, and wear characteristics vary by the specific system.',
    difficulty: 'easy',
    order_index: 27,
  },
  {
    id: 'qq-15-028',
    quiz_id: 'quiz-15',
    question: 'What is the safest rule when working with lace-front systems?',
    answer_a: 'Use the attachment and removal method approved for that specific lace system and adhesive',
    answer_b: 'Always place tape directly on the lace',
    answer_c: 'Use the same attachment pattern for every lace-front system',
    answer_d: 'Pull the lace dry during removal to avoid solvent',
    correct_answer: 'a',
    explanation: 'Lace is delicate. Attachment placement and removal should follow the specific system and adhesive manufacturer instructions.',
    difficulty: 'easy',
    order_index: 28,
  },
  {
    id: 'qq-15-029',
    quiz_id: 'quiz-15',
    question: 'Why are combination bases used in hair replacement systems?',
    answer_a: 'They combine material characteristics in different zones to balance appearance, airflow, attachment, and durability',
    answer_b: 'They are always the least expensive option',
    answer_c: 'They require no maintenance or cleaning',
    answer_d: 'They are only available as custom-made systems',
    correct_answer: 'a',
    explanation: 'Combination bases use different materials in selected zones so the system can balance multiple performance characteristics.',
    difficulty: 'medium',
    order_index: 29,
  },
  {
    id: 'qq-15-030',
    quiz_id: 'quiz-15',
    question: 'Which method can create a low-profile root appearance without a conventional knot?',
    answer_a: 'V-loop',
    answer_b: 'Single knot',
    answer_c: 'Double knot',
    answer_d: 'Cross-stitch',
    correct_answer: 'a',
    explanation: 'V-looping is one base-construction method that can create a low-profile root appearance. Exact appearance and durability depend on the base and construction.',
    difficulty: 'medium',
    order_index: 30,
  },

  // === STOCK VS CUSTOM (3 questions) ===
  {
    id: 'qq-15-031',
    quiz_id: 'quiz-15',
    question: "What is the main advantage of a stock hair replacement system?",
    answer_a: 'Lower cost and immediate availability',
    answer_b: 'A client-specific fit created from measurements or a template',
    answer_c: 'Unlimited color and style customization',
    answer_d: 'A guaranteed lifetime service life',
    correct_answer: 'a',
    explanation: 'Stock systems use standard sizes/colors and can be adapted after fitting. Custom systems are built from client-specific measurements or templates.',
    difficulty: 'easy',
    order_index: 31,
  },
  {
    id: 'qq-15-032',
    quiz_id: 'quiz-15',
    question: "What is a plaster mold used for in custom system creation?",
    answer_a: 'A three-dimensional head form used to capture contour information for custom fabrication',
    answer_b: 'A decorative display piece for the barbershop',
    answer_c: 'A tool for mixing hair coloring products',
    answer_d: 'A weight to hold the system during cleaning',
    correct_answer: 'a',
    explanation: 'A plaster mold captures three-dimensional head contour information. How a manufacturer converts or stores the form depends on its ordering process.',
    difficulty: 'medium',
    order_index: 32,
  },
  {
    id: 'qq-15-033',
    quiz_id: 'quiz-15',
    question: "A client needs a system in three days for a wedding. He has a standard oval bald area and a $400 budget. What do you recommend?",
    answer_a: 'A stock system in a close color match, customized with cutting and blending',
    answer_b: 'A custom system made from a plaster mold',
    answer_c: 'Surgical hair transplantation',
    answer_d: 'Wait until after the wedding to begin the process',
    correct_answer: 'a',
    explanation: 'Stock systems are available immediately, fit the budget, and can be cut and styled to look natural for the event. Custom systems and surgery require timelines and budgets he does not have.',
    difficulty: 'medium',
    order_index: 33,
  },

  // === MEASUREMENT & TEMPLATES (3 questions) ===
  {
    id: 'qq-15-034',
    quiz_id: 'quiz-15',
    question: "How are hair replacement system sizes measured?",
    answer_a: 'In inches — length by width (e.g., 6x4 means six inches front-to-back)',
    answer_b: 'In centimeters — diameter of the bald area',
    answer_c: 'By cup size like bras (A, B, C, D)',
    answer_d: 'By weight in ounces',
    correct_answer: 'a',
    explanation: 'System sizes are measured in inches — length by width. A 6x4 piece means six inches front-to-back and four inches side-to-side. The larger number typically refers to length.',
    difficulty: 'easy',
    order_index: 34,
  },
  {
    id: 'qq-15-035',
    quiz_id: 'quiz-15',
    question: "What is the purpose of a template in custom system creation?",
    answer_a: 'A pattern of the client\'s bald area that becomes the manufacturer\'s blueprint',
    answer_b: 'A decorative stencil for applying adhesive',
    answer_c: 'A marketing brochure showing before-and-after photos',
    answer_d: 'A legal document for the client to sign',
    correct_answer: 'a',
    explanation: 'A template is created with plastic wrap and tape, marked with a grease pencil, and transferred to pattern paper. It becomes the manufacturer\'s blueprint for cutting the base to exact specifications.',
    difficulty: 'easy',
    order_index: 35,
  },
  {
    id: 'qq-15-036',
    quiz_id: 'quiz-15',
    question: 'Why should product compatibility be checked for hair replacement supplies?',
    answer_a: 'Adhesives, removers, and cleaners must be compatible with the specific system and used according to manufacturer instructions',
    answer_b: 'Standard barber products are always more expensive',
    answer_c: 'Manufacturer-approved products are never available locally',
    answer_d: 'Product compatibility affects fragrance only',
    correct_answer: 'a',
    explanation: 'Use products compatible with the specific system and follow manufacturer instructions for adhesives, removers, cleaners, and solvents.',
    difficulty: 'easy',
    order_index: 36,
  },

  // === ATTACHMENT METHODS (5 questions) ===
  {
    id: 'qq-15-037',
    quiz_id: 'quiz-15',
    question: 'What is full-head bonding?',
    answer_a: 'Using an adhesive system across the intended scalp contact area',
    answer_b: 'Using tape only at the front hairline',
    answer_c: 'Sewing the system to the client’s natural hair',
    answer_d: 'Clipping the system with metal barrettes',
    correct_answer: 'a',
    explanation: 'Full-head bonding uses an adhesive system across the intended contact area. Security, water exposure, wear duration, cure time, and removal depend on the system and adhesive.',
    difficulty: 'easy',
    order_index: 37,
  },
  {
    id: 'qq-15-038',
    quiz_id: 'quiz-15',
    question: 'What determines when a bonded system can be shampooed or exposed to water?',
    answer_a: 'The adhesive manufacturer’s cure and water-exposure instructions',
    answer_b: 'A universal 24-hour rule for every adhesive',
    answer_c: 'A universal 48-hour rule for every adhesive',
    answer_d: 'Whether the client prefers morning or evening shampooing',
    correct_answer: 'a',
    explanation: 'Cure time is product-specific. Follow the adhesive manufacturer’s instructions before shampooing, swimming, heavy sweating, or wetting the attachment area.',
    difficulty: 'easy',
    order_index: 38,
  },
  {
    id: 'qq-15-039',
    quiz_id: 'quiz-15',
    question: 'What can be an advantage of tape attachment?',
    answer_a: 'Some tape systems can be easier to remove and reattach than extended-wear bonding',
    answer_b: 'Tape is always more secure for swimming than bonding',
    answer_c: 'Tape is completely invisible on every base and hairline',
    answer_d: 'Tape never requires replacement or maintenance',
    correct_answer: 'a',
    explanation: 'Tape may be easier to remove and reattach in some systems. Security, wear duration, water exposure, and edge behavior depend on the product and system.',
    difficulty: 'easy',
    order_index: 39,
  },
  {
    id: 'qq-15-040',
    quiz_id: 'quiz-15',
    question: 'A competitive swimmer expects frequent water exposure. What is the best attachment approach?',
    answer_a: 'Choose a system and attachment product specifically rated for the expected water exposure and follow its cure and maintenance instructions',
    answer_b: 'Assume every full-head adhesive is waterproof',
    answer_c: 'Use any perimeter tape because all tapes tolerate repeated swimming',
    answer_d: 'Ignore product instructions once the system feels secure',
    correct_answer: 'a',
    explanation: 'Match the attachment method to verified product ratings and manufacturer instructions rather than assuming a universal waterproof option.',
    difficulty: 'medium',
    order_index: 40,
  },
  {
    id: 'qq-15-041',
    quiz_id: 'quiz-15',
    question: 'How should spirit gum be used for a facial-hair piece?',
    answer_a: 'Use it only when appropriate for the piece and follow the product instructions for skin preparation, tack time, placement, and removal',
    answer_b: 'Mix it into shampoo before application',
    answer_c: 'Inject it under the skin for permanent attachment',
    answer_d: 'Apply and remove it without checking product directions',
    correct_answer: 'a',
    explanation: 'Spirit gum use is product-specific. Follow the adhesive directions and remove the piece without force.',
    difficulty: 'easy',
    order_index: 41,
  },

  // === MAINTENANCE & CLEANING (5 questions) ===
  {
    id: 'qq-15-042',
    quiz_id: 'quiz-15',
    question: 'What water-temperature approach is appropriate for synthetic systems?',
    answer_a: 'Follow the specific system’s approved temperature guidance; the source cautions against hot water',
    answer_b: 'Use hot water for every deep cleaning',
    answer_c: 'Use boiling water to sterilize the system',
    answer_d: 'Use ice water for every synthetic fiber',
    correct_answer: 'a',
    explanation: 'The source cautions against hot water on synthetic systems, while the exact approved range should follow the fiber and manufacturer guidance.',
    difficulty: 'easy',
    order_index: 42,
  },
  {
    id: 'qq-15-043',
    quiz_id: 'quiz-15',
    question: 'What maintenance interval does the Chapter 15 source use as a study baseline?',
    answer_a: 'Initial cleaning around one week, then about every three to four weeks',
    answer_b: 'Daily cleaning after every wear for all systems',
    answer_c: 'Exactly once per year for every system',
    answer_d: 'No cleaning until visible soil appears',
    correct_answer: 'a',
    explanation: 'The source uses an initial cleaning around one week and then about every three to four weeks as a study baseline. Actual timing should follow manufacturer guidance and wear conditions.',
    difficulty: 'easy',
    order_index: 43,
  },
  {
    id: 'qq-15-044',
    quiz_id: 'quiz-15',
    question: 'When can a backup or rotation system be useful?',
    answer_a: 'When cleaning, drying, repair, or service would otherwise leave the client without a wearable system',
    answer_b: 'Every client is required to own exactly two systems',
    answer_c: 'Systems must always be worn in pairs',
    answer_d: 'A backup eliminates the need for maintenance',
    correct_answer: 'a',
    explanation: 'A backup can be useful for some maintenance plans, but it is not a universal requirement.',
    difficulty: 'easy',
    order_index: 44,
  },
  {
    id: 'qq-15-045',
    quiz_id: 'quiz-15',
    question: 'What is the safest meaning of the first “O” in the updated COOL care reminder?',
    answer_a: 'Observe the system’s approved water-temperature guidance',
    answer_b: 'Open the windows during drying',
    answer_c: 'Oil the base after every cleaning',
    answer_d: 'Overlap the system edges when storing',
    correct_answer: 'a',
    explanation: 'The updated COOL reminder emphasizes observing the specific system’s approved water-temperature guidance instead of treating one temperature as universal.',
    difficulty: 'medium',
    order_index: 45,
  },
  {
    id: 'qq-15-046',
    quiz_id: 'quiz-15',
    question: 'How should a hair replacement system be stored when not in use?',
    answer_a: 'Use the support and storage method recommended for that specific system to preserve its shape',
    answer_b: 'Always fold it in half and place it in a drawer',
    answer_c: 'Hang every system by the hair',
    answer_d: 'Roll every system tightly for compact storage',
    correct_answer: 'a',
    explanation: 'Storage should preserve the system’s shape, base, and hair. Follow the manufacturer’s recommended support and storage method.',
    difficulty: 'easy',
    order_index: 46,
  },

  // === CHEMICAL SERVICES (3 questions) ===
  {
    id: 'qq-15-047',
    quiz_id: 'quiz-15',
    question: 'What is the floating technique for systems approved for permanent waving?',
    answer_a: 'Support perm rods with roller picks so they do not rest directly on the base',
    answer_b: 'Float the entire system in waving solution',
    answer_c: 'Submerge the client’s head during processing',
    answer_d: 'Suspend the system from the ceiling while processing',
    correct_answer: 'a',
    explanation: 'For systems specifically approved for permanent waving, the source describes supporting rods with roller picks so they do not rest on the base.',
    difficulty: 'medium',
    order_index: 47,
  },
  {
    id: 'qq-15-048',
    quiz_id: 'quiz-15',
    question: 'What determines whether a chemical service is appropriate for a hair replacement system?',
    answer_a: 'Fiber type, base construction, prior processing, and manufacturer approval',
    answer_b: 'Whether the service is safe on natural hair',
    answer_c: 'Whether the client signs a waiver',
    answer_d: 'Whether the barber has used the chemical before',
    correct_answer: 'a',
    explanation: 'Do not assume natural-hair lightening, coloring, or waving procedures are safe for a system. Compatibility depends on the fiber, base, prior processing, and manufacturer guidance.',
    difficulty: 'easy',
    order_index: 48,
  },
  {
    id: 'qq-15-049',
    quiz_id: 'quiz-15',
    question: 'What is the safest rule for coloring a hair replacement system?',
    answer_a: 'Use only products and methods approved for that specific system',
    answer_b: 'Temporary rinses are universally safe on every system',
    answer_c: 'Permanent color is safe on every human-hair system',
    answer_d: 'Bleach is acceptable whenever the client requests a lighter shade',
    correct_answer: 'a',
    explanation: 'Color-service limits depend on fiber, base, prior processing, and manufacturer approval. No single color product is universally safe for every system.',
    difficulty: 'easy',
    order_index: 49,
  },

  // === CUTTING & BLENDING (4 questions) ===
  {
    id: 'qq-15-050',
    quiz_id: 'quiz-15',
    question: "At what elevation is the top section of a hair system cut?",
    answer_a: '90 degrees using clipper-over-comb or fingers-and-shear',
    answer_b: '45 degrees for maximum layering',
    answer_c: '180 degrees for extreme volume',
    answer_d: '0 degrees for a blunt cut',
    correct_answer: 'a',
    explanation: 'The top section is cut at 90-degree elevation using clipper-over-comb or fingers-and-shear, working forward from crown to forehead for seamless transitions.',
    difficulty: 'medium',
    order_index: 50,
  },
  {
    id: 'qq-15-051',
    quiz_id: 'quiz-15',
    question: "What is slide cutting and why is it essential for blending?",
    answer_a: 'The shear slides through hair at an angle to create a feathered, tapered edge',
    answer_b: 'Cutting the hair while sliding the system across the client\'s head',
    answer_c: 'Using a sliding scale to determine the price of the cut',
    answer_d: 'A technique for sliding the system onto the scalp',
    correct_answer: 'a',
    explanation: 'Slide cutting creates a feathered, tapered edge that disappears into natural hair. It is essential for making the transition between system and natural hair invisible.',
    difficulty: 'medium',
    order_index: 51,
  },
  {
    id: 'qq-15-052',
    quiz_id: 'quiz-15',
    question: "What is the golden rule when customizing stock systems?",
    answer_a: 'Be conservative — you can always cut more, but you cannot put hair back',
    answer_b: 'Remove as much hair as possible for a lightweight feel',
    answer_c: 'Always cut the system to the shortest requested length immediately',
    answer_d: 'Use thinning shears on the entire system for uniform density',
    correct_answer: 'a',
    explanation: 'A common irreversible mistake is removing too much hair. Work conservatively and remove length gradually because cut hair cannot be restored to the system.',
    difficulty: 'easy',
    order_index: 52,
  },
  {
    id: 'qq-15-053',
    quiz_id: 'quiz-15',
    question: "Why should thinning shears be used with narrow partings near the base?",
    answer_a: 'Wide partings create visible gaps that ruin the finished appearance',
    answer_b: 'Narrow partings speed up the cutting process',
    answer_c: 'Wide partings are only for experienced barbers',
    answer_d: 'Narrow partings prevent the client from feeling the shears',
    correct_answer: 'a',
    explanation: 'Wide partings create visible gaps that ruin the blend. Narrow partings allow controlled bulk removal without creating holes in the finished appearance.',
    difficulty: 'medium',
    order_index: 53,
  },

  // === SAFETY (2 questions) ===
  {
    id: 'qq-15-054',
    quiz_id: 'quiz-15',
    question: "Why must dull blades be replaced during system customization?",
    answer_a: 'Dull blades pull hair, causing damage and uneven cuts on expensive systems',
    answer_b: 'Sharp blades are required by state law for all haircuts',
    answer_c: 'Dull blades make the cutting process faster',
    answer_d: 'Clients can hear the difference between sharp and dull blades',
    correct_answer: 'a',
    explanation: 'Dull blades pull hair, causing damage to the system and creating uneven cuts. Sharp tools are essential for clean, precise work on expensive systems.',
    difficulty: 'easy',
    order_index: 54,
  },
  {
    id: 'qq-15-055',
    quiz_id: 'quiz-15',
    question: 'What is a common irreversible mistake when customizing stock systems?',
    answer_a: 'Removing too much hair during initial customization',
    answer_b: 'Not cutting enough and leaving the system too heavy',
    answer_c: 'Using the wrong type of adhesive',
    answer_d: 'Failing to obtain a model release',
    correct_answer: 'a',
    explanation: 'Work conservatively and remove length gradually because cut hair cannot be restored to the system.',
    difficulty: 'easy',
    order_index: 55,
  },

  // === BOARD EXAM TRAPS (5 questions) ===
  {
    id: 'qq-15-056',
    quiz_id: 'quiz-15',
    question: 'Knowledge Check: Should a barber recommend a specific prescription-medication dosage to a client?',
    answer_a: 'No — individualized medication directions belong with an appropriate licensed healthcare professional',
    answer_b: 'Yes — barbers are trained to choose prescription doses',
    answer_c: 'Yes — if the product is used for hair loss',
    answer_d: 'No — barbers cannot discuss any general medication information',
    correct_answer: 'a',
    explanation: 'A barber can provide general education but should not choose or direct prescription medication dosing for a client.',
    difficulty: 'easy',
    order_index: 56,
  },
  {
    id: 'qq-15-057',
    quiz_id: 'quiz-15',
    question: 'Knowledge Check: Does hotter water always clean synthetic systems better?',
    answer_a: 'No — follow the system’s approved temperature guidance; the source cautions against hot water',
    answer_b: 'Yes — hotter water always removes more oil safely',
    answer_c: 'Yes — all synthetic fibers tolerate hot water',
    answer_d: 'No — every synthetic system requires ice water',
    correct_answer: 'a',
    explanation: 'Water-temperature limits are product-specific. The source cautions against hot water on synthetic systems.',
    difficulty: 'easy',
    order_index: 57,
  },
  {
    id: 'qq-15-058',
    quiz_id: 'quiz-15',
    question: 'Knowledge Check: Does every lace-front system use the same tape placement?',
    answer_a: 'No — attachment placement depends on the specific lace system and adhesive instructions',
    answer_b: 'Yes — tape always belongs directly on the lace',
    answer_c: 'Yes — every lace system uses the same pattern',
    answer_d: 'No — tape is never used with any hair system',
    correct_answer: 'a',
    explanation: 'Lace is delicate. Use the attachment and removal method approved for the specific system and adhesive.',
    difficulty: 'easy',
    order_index: 58,
  },
  {
    id: 'qq-15-059',
    quiz_id: 'quiz-15',
    question: 'Knowledge Check: Can every bonded system be shampooed immediately after application?',
    answer_a: 'No — follow the adhesive manufacturer’s cure and water-exposure instructions',
    answer_b: 'Yes — every modern adhesive cures instantly',
    answer_c: 'Yes — shampoo type determines whether curing is needed',
    answer_d: 'No — every adhesive requires exactly one full week',
    correct_answer: 'a',
    explanation: 'Cure time is product-specific. A fixed 24–48-hour rule is not universal.',
    difficulty: 'easy',
    order_index: 59,
  },
  {
    id: 'qq-15-060',
    quiz_id: 'quiz-15',
    question: 'Knowledge Check: Is hair transplantation a barbering service?',
    answer_a: 'No — it is a medical procedure and requires an appropriately licensed medical professional',
    answer_b: 'Yes — any barber can perform it after a short course',
    answer_c: 'Yes — scalp reduction is allowed even if transplantation is not',
    answer_d: 'No — but a barber should choose the surgical technique for the client',
    correct_answer: 'a',
    explanation: 'Hair transplantation is a medical procedure, not a cosmetic barbering service. Refer the client appropriately.',
    difficulty: 'easy',
    order_index: 60,
  },

  // === SCENARIO-BASED APPLICATION (4 questions) ===
  {
    id: 'qq-15-061',
    quiz_id: 'quiz-15',
    question: 'A client reports a wool allergy and is considering a mixed-hair system. What should the barber do?',
    answer_a: 'Verify the system’s fiber composition and avoid materials that may trigger the reported allergy',
    answer_b: 'Assure the client that wool allergies never matter in hair systems',
    answer_c: 'Recommend taking allergy medication before each wear',
    answer_d: 'Tell the client every mixed-hair system contains wool',
    correct_answer: 'a',
    explanation: 'Mixed systems can contain different fibers. When a client reports an allergy or sensitivity, verify composition and avoid materials that may trigger it.',
    difficulty: 'medium',
    order_index: 61,
  },
  {
    id: 'qq-15-062',
    quiz_id: 'quiz-15',
    question: 'A client wants a human-hair system lightened. What is the best response?',
    answer_a: 'Verify whether the specific system, base, prior processing, and manufacturer instructions support that chemical service before proceeding',
    answer_b: 'Use bleach automatically because the hair is human',
    answer_c: 'Use a fixed developer strength on every human-hair system',
    answer_d: 'Assume temporary color is the only option without checking the system',
    correct_answer: 'a',
    explanation: 'Human hair does not automatically make natural-hair chemical procedures appropriate. The system’s fiber, base, prior processing, and manufacturer guidance control compatibility.',
    difficulty: 'medium',
    order_index: 62,
  },
  {
    id: 'qq-15-063',
    quiz_id: 'quiz-15',
    question: 'A client asks why a synthetic system looks shinier than a previous system. What is the best explanation?',
    answer_a: 'Synthetic fibers vary by product; gloss and finish are characteristics of the specific fiber and construction',
    answer_b: 'Every synthetic fiber has the same high-gloss finish',
    answer_c: 'Shine always means the system was cleaned incorrectly',
    answer_d: 'All manufacturers apply a coating that wears off on a fixed schedule',
    correct_answer: 'a',
    explanation: 'Synthetic systems vary by fiber and product. Avoid treating gloss or finish as identical across all synthetic materials.',
    difficulty: 'medium',
    order_index: 63,
  },
  {
    id: 'qq-15-064',
    quiz_id: 'quiz-15',
    question: 'A client prioritizes a highly individualized, natural-looking result. What is the best planning approach?',
    answer_a: 'Evaluate custom measurements, appropriate hair fiber, base design, and professional blending together',
    answer_b: 'Assume human hair and lace always guarantee an undetectable result',
    answer_c: 'Choose the most expensive adhesive first',
    answer_d: 'Use a stock system without measuring because cost is not a concern',
    correct_answer: 'a',
    explanation: 'Natural-looking results depend on multiple factors, including fit, fiber, base design, density, color, attachment, and blending; no single combination guarantees an undetectable result.',
    difficulty: 'hard',
    order_index: 64,
  },

  // === MEMORY ANCHORS & KEY CONCEPTS (3 questions) ===
  {
    id: 'qq-15-065',
    quiz_id: 'quiz-15',
    question: "What does the memory anchor 'LAB MED' help barbers remember?",
    answer_a: 'The six factors to cover in every hair replacement consultation',
    answer_b: 'The five main base construction materials',
    answer_c: 'The four primary attachment methods',
    answer_d: 'The three types of hair used in systems',
    correct_answer: 'a',
    explanation: 'LAB MED stands for Lifestyle, Age, Budget, Medical history, Expectations, and Daily maintenance — the six factors that guide every professional consultation.',
    difficulty: 'easy',
    order_index: 65,
  },
  {
    id: 'qq-15-066',
    quiz_id: 'quiz-15',
    question: "In the 'Hovering Helicopters' memory anchor for floating perm rods, what represents the landing gear?",
    answer_a: 'Roller picks',
    answer_b: 'Perm rods',
    answer_c: 'The base material',
    answer_d: "The client's head",
    correct_answer: 'a',
    explanation: 'The rod is the helicopter, the base is the landing pad, and the roller picks are the landing gear. The helicopter hovers above the pad to avoid crushing it.',
    difficulty: 'medium',
    order_index: 66,
  },
  {
    id: 'qq-15-067',
    quiz_id: 'quiz-15',
    question: 'What is a key principle for making a hair replacement system look natural?',
    answer_a: 'Blend the transition between system hair and natural hair carefully',
    answer_b: 'Use only human hair and never synthetic fiber',
    answer_c: 'Use the most expensive adhesive available',
    answer_d: 'Always choose a stock system instead of custom',
    correct_answer: 'a',
    explanation: 'Careful blending, density control, tapering, and appropriate cutting help create a natural transition.',
    difficulty: 'easy',
    order_index: 67,
  },

  // === HARD QUESTIONS — COMPREHENSIVE APPLICATION (3 questions) ===
  {
    id: 'qq-15-068',
    quiz_id: 'quiz-15',
    question: 'A client wearing a bonded system develops itching and redness at the hairline. What is the safest professional response?',
    answer_a: 'Stop the service, avoid assuming the cause, follow removal/product safety instructions, and refer persistent or significant symptoms for medical evaluation',
    answer_b: 'Diagnose adhesive allergy and switch fibers immediately',
    answer_c: 'Recommend a stronger clarifying shampoo as treatment',
    answer_d: 'Tell the client the reaction is normal and to ignore it',
    correct_answer: 'a',
    explanation: 'Irritation has multiple possible causes. A barber should not diagnose it. Stop aggravating exposure, follow product safety/removal directions, and refer medical concerns appropriately.',
    difficulty: 'hard',
    order_index: 68,
  },
  {
    id: 'qq-15-069',
    quiz_id: 'quiz-15',
    question: "A barber is customizing a stock system for a client. The top looks bulky, the sides are too long, and the back extends past the natural hairline. In what order should the barber proceed?",
    answer_a: 'Thin the top with narrow partings, taper the sides with slide cutting, then blend the back with thinning shears',
    answer_b: 'Cut the back first to establish length, then the top, then the sides',
    answer_c: 'Remove all bulk from the top first with clippers at zero guard',
    answer_d: 'Style the system first to see how it falls, then make adjustments',
    correct_answer: 'a',
    explanation: 'The correct order: thin heavy top areas with narrow partings and thinning shears, taper sides to match natural hairlines with slide cutting, then blend the back. Be conservative — you can always cut more.',
    difficulty: 'hard',
    order_index: 69,
  },
  {
    id: 'qq-15-070',
    quiz_id: 'quiz-15',
    question: 'A client with early thinning, a limited budget, and low commitment tolerance asks about options. What is the best consultation approach?',
    answer_a: 'Present cosmetic and medical categories neutrally, discuss stock/custom system options, and refer individualized medical decisions appropriately',
    answer_b: 'Recommend a custom system as the only professional solution',
    answer_c: 'Tell the client to wait until hair loss becomes severe',
    answer_d: 'Recommend a surgical procedure as the cheapest long-term choice',
    correct_answer: 'a',
    explanation: 'A professional consultation should present relevant options without pressure, match cosmetic choices to the client’s goals and budget, and refer individualized medical decisions appropriately.',
    difficulty: 'hard',
    order_index: 70,
  },

  // === KEY TAKEAWAYS (2 questions) ===
  {
    id: 'qq-15-071',
    quiz_id: 'quiz-15',
    question: "What are barbers actually selling when they provide hair replacement services?",
    answer_a: 'The reflection the client wants to see — confidence and self-image restoration',
    answer_b: 'Hair fibers and base materials at a markup',
    answer_c: 'A medical procedure that requires physician supervision',
    answer_d: 'A temporary cosmetic cover-up',
    correct_answer: 'a',
    explanation: 'Clients are not buying hair — they are buying the man they used to see in the mirror. The barber\'s job is to deliver that reflection with honesty, skill, and care.',
    difficulty: 'easy',
    order_index: 71,
  },
  {
    id: 'qq-15-072',
    quiz_id: 'quiz-15',
    question: 'Why is scope-of-practice knowledge important for barbers offering hair replacement?',
    answer_a: 'It helps separate cosmetic services from diagnosis, prescribing, surgery, and individualized medical advice while accounting for local rules',
    answer_b: 'Scope of practice applies only to haircutting',
    answer_c: 'Barbers have unlimited scope for all hair-related services',
    answer_d: 'Scope rules are identical in every jurisdiction',
    correct_answer: 'a',
    explanation: 'Scope knowledge helps protect professional boundaries. Verify the rules in the jurisdiction where you practice rather than assuming one universal standard.',
    difficulty: 'easy',
    order_index: 72,
  },
]

export default chapter15PremiumQuizQuestions
