// Chapter 5: Implements, Tools, and Equipment — PREMIUM MCQ QUIZ
// 50 questions generated STRICTLY from Chapter 5 flashcards
// Randomized question selection and answer order per attempt
// The Barber's Forge Certification Exam

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 5: FULL QUESTION BANK (50 questions)
// Generated from chapter-5-premium-flashcards.ts
// NATURAL answer distribution (NOT forced balanced)
// ───────────────────────────────────────────────
export const chapter5PremiumQuizQuestions: QuizQuestion[] = [
  // COMBS & BRUSHES (6 questions)
  {
    id: 'qq-5-001',
    quiz_id: 'quiz-5',
    question: 'What are the two most durable and heat-resistant comb materials?',
    answer_a: 'Carbon fiber and hard rubber',
    answer_b: 'Plastic and wood',
    answer_c: 'Metal and ceramic',
    answer_d: 'Bamboo and silicone',
    correct_answer: 'a',
    explanation: 'Carbon fiber and hard rubber resist heat from thermal tools and last longer than plastic combs. This is a board exam favorite.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-5-002',
    quiz_id: 'quiz-5',
    question: 'What is the standard length of an all-purpose cutting comb?',
    answer_a: '5-6 inches',
    answer_b: '7-8 inches',
    answer_c: '9-10 inches',
    answer_d: '3-4 inches',
    correct_answer: 'b',
    explanation: 'All-purpose cutting combs are 7-8 inches with fine teeth on one end and medium teeth on the other for versatility.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-5-003',
    quiz_id: 'quiz-5',
    question: 'What is the primary purpose of a taper comb?',
    answer_a: 'Detangling wet hair after washing',
    answer_b: 'Blow-drying and styling long hair',
    answer_c: 'Clipper-over-comb and scissor-over-comb tapering with firm grip',
    answer_d: 'Sectioning hair for color applications',
    correct_answer: 'c',
    explanation: 'Taper combs are shorter, sturdier, with teeth spaced to grip hair firmly for clipper-over-comb and scissor-over-comb tapering.',
    difficulty: 'medium',
    order_index: 3,
  },
  {
    id: 'qq-5-004',
    quiz_id: 'quiz-5',
    question: 'CLIPPER GUARD SIZES: What length does a #2 guard cut?',
    answer_a: '1/8 inch (3mm)',
    answer_b: '1/4 inch (6mm)',
    answer_c: '3/8 inch (10mm)',
    answer_d: '1/2 inch (13mm)',
    correct_answer: 'b',
    explanation: '#2 guard = 1/4 inch (6mm). Memorize: #0=1/16in, #1=1/8in, #2=1/4in, #3=3/8in, #4=1/2in.',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-5-005',
    quiz_id: 'quiz-5',
    question: 'Which brush type creates volume and curl during blow-drying?',
    answer_a: 'Paddle brush',
    answer_b: 'Vent brush',
    answer_c: 'Round brush',
    answer_d: 'Pick comb',
    correct_answer: 'c',
    explanation: 'Round brush creates volume and curl. Barrel size matters — larger barrels create bigger curls. Paddle brushes smooth; vent brushes speed drying.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-5-006',
    quiz_id: 'quiz-5',
    question: 'When should you replace a comb?',
    answer_a: 'Only when it breaks completely in half',
    answer_b: 'When teeth become worn, broken, or missing',
    answer_c: 'Every 6 months regardless of condition',
    answer_d: 'Only when the color fades',
    correct_answer: 'b',
    explanation: 'Replace combs with worn, broken, or missing teeth. Damaged teeth snag hair, damage the cuticle, and create uneven sections.',
    difficulty: 'easy',
    order_index: 6,
  },

  // SHEARS & SCISSORS (8 questions)
  {
    id: 'qq-5-007',
    quiz_id: 'quiz-5',
    question: 'What is the difference between a convex edge and a beveled edge on shears?',
    answer_a: 'There is no difference — they are the same thing',
    answer_b: 'Convex is duller; beveled is sharper',
    answer_c: 'Convex is for left-handed use; beveled is for right-handed use',
    answer_d: 'Convex is sharper but more fragile; beveled is more durable but cuts less smoothly',
    correct_answer: 'd',
    explanation: 'Convex edge (hollow ground) is sharper and cuts more smoothly but is more fragile. Beveled edge is more durable and lasts longer but cuts less smoothly.',
    difficulty: 'medium',
    order_index: 7,
  },
  {
    id: 'qq-5-008',
    quiz_id: 'quiz-5',
    question: 'What is the most versatile shear length for barbering?',
    answer_a: '4 to 5 inches',
    answer_b: '5.5 to 6 inches',
    answer_c: '7 to 8 inches',
    answer_d: '3 to 4 inches',
    correct_answer: 'b',
    explanation: '5.5 to 6 inches handles 90% of haircutting work. This length offers the best balance of control and reach.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-5-009',
    quiz_id: 'quiz-5',
    question: 'How do you perform the shear tension test?',
    answer_a: 'Tap the blades together and listen for a ringing sound',
    answer_b: 'Weigh the shears on a scale',
    answer_c: 'Submerge in water and check for bubbles',
    answer_d: 'Hold tips up, lift one handle — blades should open partially',
    correct_answer: 'd',
    explanation: 'Hold tips pointing up, lift one handle. Blades should open partially — not fall completely open (too loose) and not stay closed (too tight).',
    difficulty: 'medium',
    order_index: 9,
  },
  {
    id: 'qq-5-010',
    quiz_id: 'quiz-5',
    question: 'What happens if shear tension is too loose?',
    answer_a: 'The blades overheat during cutting',
    answer_b: 'Hair bends between blades instead of cutting cleanly',
    answer_c: 'The shears become sharper',
    answer_d: 'Nothing — loose tension is preferred',
    correct_answer: 'b',
    explanation: 'Too loose = blades fall completely open. Hair bends between blades instead of cutting cleanly, creating split ends and uneven lines.',
    difficulty: 'easy',
    order_index: 10,
  },
  {
    id: 'qq-5-011',
    quiz_id: 'quiz-5',
    question: 'What is an offset handle and why is it preferred?',
    answer_a: 'The handle is removable for cleaning',
    answer_b: 'The handle is angled upward for overhead cutting',
    answer_c: 'The thumb hole is set back from the finger hole for ergonomic benefit',
    answer_d: 'The handle is heated for comfort',
    correct_answer: 'c',
    explanation: 'Offset handle: thumb hole set back from finger hole. Most ergonomic design, reducing wrist strain and RSI risk.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-5-012',
    quiz_id: 'quiz-5',
    question: 'What is the primary purpose of thinning/texturizing shears?',
    answer_a: 'To create blunt, straight lines in the haircut',
    answer_b: 'To remove bulk and create texture without changing overall length',
    answer_c: 'To shave the neckline clean',
    answer_d: 'To disinfect tools between clients',
    correct_answer: 'b',
    explanation: 'Thinning shears have one blade with teeth (20-40 count). They remove bulk and create texture WITHOUT changing overall length.',
    difficulty: 'medium',
    order_index: 12,
  },
  {
    id: 'qq-5-013',
    quiz_id: 'quiz-5',
    question: 'Why should left-handed barbers use left-handed shears?',
    answer_a: 'Using right-handed shears left-handed crushes the cutting edge',
    answer_b: 'They are cheaper than right-handed shears',
    answer_c: 'Left-handed shears are sharper by default',
    answer_d: 'State boards require left-handed shears for left-handed barbers',
    correct_answer: 'a',
    explanation: 'Left-handed shears have reversed blades. Using right-handed shears in the left hand crushes the cutting edge and ruins the blade.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-5-014',
    quiz_id: 'quiz-5',
    question: 'What should you NEVER cut with professional shears?',
    answer_a: 'Wet hair',
    answer_b: 'Paper, plastic, wire, or anything other than clean hair',
    answer_c: 'Synthetic hair extensions',
    answer_d: 'Curly hair',
    correct_answer: 'b',
    explanation: 'NEVER cut paper, plastic, wire, or anything other than clean hair. These materials instantly damage the edge.',
    difficulty: 'easy',
    order_index: 14,
  },

  // CLIPPERS & TRIMMERS (7 questions)
  {
    id: 'qq-5-015',
    quiz_id: 'quiz-5',
    question: 'What is the main difference between clippers and trimmers?',
    answer_a: 'Clippers are for bulk removal and fades; trimmers are for precision outlining and detail',
    answer_b: 'Clippers are battery-powered; trimmers are corded',
    answer_c: 'Clippers are more expensive; trimmers are disposable',
    answer_d: 'There is no difference — they are interchangeable',
    correct_answer: 'a',
    explanation: 'Clippers are larger, more powerful, for bulk removal, fades, and tapers. Trimmers are smaller, precise tools for outlining, edging, and detail work.',
    difficulty: 'easy',
    order_index: 15,
  },
  {
    id: 'qq-5-016',
    quiz_id: 'quiz-5',
    question: 'Which clipper motor type is the professional standard for handling all hair types?',
    answer_a: 'Magnetic/Pivot motor',
    answer_b: 'Rotary motor',
    answer_c: 'Cordless NiCad motor',
    answer_d: 'Solar-powered motor',
    correct_answer: 'b',
    explanation: 'Rotary motor runs cooler, lasts longer, and has the power to cut through thick, coarse, and wet hair. It is the professional standard.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-5-017',
    quiz_id: 'quiz-5',
    question: 'What is zero-gap on a trimmer?',
    answer_a: 'A trimmer with no battery',
    answer_b: 'A safety feature that prevents cutting',
    answer_c: 'A trimmer that cannot be cleaned',
    answer_d: 'Blades adjusted to cut extremely close for sharp lines',
    correct_answer: 'd',
    explanation: 'Zero-gap means trimmer blades are adjusted to cut extremely close. Creates razor-sharp lines but can cause razor burn if used improperly.',
    difficulty: 'medium',
    order_index: 17,
  },
  {
    id: 'qq-5-018',
    quiz_id: 'quiz-5',
    question: 'What does it mean when clippers start pulling hair instead of cutting?',
    answer_a: 'The motor is overheating',
    answer_b: 'The blades are dull and need replacement',
    answer_c: 'The guard is too tight',
    answer_d: 'The client has thick hair',
    correct_answer: 'b',
    explanation: 'Pulling hair means the blades are DULL. Dull blades cause pain, create uneven cuts, and damage your reputation. Replace immediately.',
    difficulty: 'easy',
    order_index: 18,
  },
  {
    id: 'qq-5-019',
    quiz_id: 'quiz-5',
    question: 'What is the T-blade design on trimmers used for?',
    answer_a: 'Cutting bulk hair on the top of the head',
    answer_b: 'Extremely close, clean lines around necklines, beards, and hairlines',
    answer_c: 'Shaving the entire head bald',
    answer_d: 'Applying hair products evenly',
    correct_answer: 'b',
    explanation: 'T-blade allows for extremely close, clean lines around necklines, beards, and hairlines. The extended blade reaches tight corners.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-5-020',
    quiz_id: 'quiz-5',
    question: 'Why is lithium-ion battery technology preferred for cordless clippers?',
    answer_a: 'It makes the clipper lighter in weight',
    answer_b: 'Consistent power until depleted, faster charging, longer life',
    answer_c: 'It is cheaper than other battery types',
    answer_d: 'It changes color when the battery is low',
    correct_answer: 'b',
    explanation: 'Lithium-ion provides consistent power until depleted — no gradual weakening. Charges faster, lasts longer, maintains full cutting power.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'qq-5-021',
    quiz_id: 'quiz-5',
    question: 'Why should you start with the longest guard and work down when fading?',
    answer_a: 'It is faster than starting short',
    answer_b: 'Long guards are sharper than short guards',
    answer_c: 'You can always cut more off — you cannot put it back',
    answer_d: 'State boards require this method',
    correct_answer: 'c',
    explanation: 'Starting long prevents mistakes and allows gradual refinement. You can always cut more off — you cannot put it back.',
    difficulty: 'easy',
    order_index: 21,
  },

  // STRAIGHT RAZORS (7 questions)
  {
    id: 'qq-5-022',
    quiz_id: 'quiz-5',
    question: 'What is the main difference between a traditional cut-throat razor and a shavette?',
    answer_a: 'The shavette is heavier than the cut-throat',
    answer_b: 'Cut-throat is only for professionals; shavette is for home use',
    answer_c: 'Cut-throat has a permanent blade; shavette uses replaceable blades',
    answer_d: 'There is no difference',
    correct_answer: 'c',
    explanation: 'Traditional cut-throat has a permanent blade requiring honing and stropping. Shavette uses replaceable single-edge blades — more sanitary, lower maintenance.',
    difficulty: 'medium',
    order_index: 22,
  },
  {
    id: 'qq-5-023',
    quiz_id: 'quiz-5',
    question: 'What is stropping and how often should it be done?',
    answer_a: 'Sharpening the blade with a stone — done monthly',
    answer_b: 'Polishing and aligning the edge on leather — done before every shave',
    answer_c: 'Cleaning the blade with alcohol — done after every client',
    answer_d: 'Replacing the blade — done weekly',
    correct_answer: 'b',
    explanation: 'Stropping polishes and aligns the edge on leather. Does NOT remove metal. Done BEFORE every shave — 20-30 passes on canvas, then leather.',
    difficulty: 'medium',
    order_index: 23,
  },
  {
    id: 'qq-5-024',
    quiz_id: 'quiz-5',
    question: 'BOARD EXAM ALERT: Which razor grip is used for the upper lip and chin?',
    answer_a: 'Freehand grip',
    answer_b: 'Backhand grip',
    answer_c: 'Reverse backhand',
    answer_d: 'Reverse freehand',
    correct_answer: 'd',
    explanation: 'Reverse freehand: hand turned toward you, edge facing up, semi-curved strokes. NEVER use reverse backhand on the face — neck only.',
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-5-025',
    quiz_id: 'quiz-5',
    question: 'BOARD EXAM ALERT: Which razor grip is RESTRICTED to sides of neck only?',
    answer_a: 'Freehand grip',
    answer_b: 'Backhand grip',
    answer_c: 'Reverse freehand',
    answer_d: 'Reverse backhand',
    correct_answer: 'd',
    explanation: 'Reverse backhand is RESTRICTED to sides of neck only. Using it on the face is a critical safety error that fails the practical exam.',
    difficulty: 'medium',
    order_index: 25,
  },
  {
    id: 'qq-5-026',
    quiz_id: 'quiz-5',
    question: 'What is the difference between hollow-ground and wedge grind razors?',
    answer_a: 'Hollow-ground has a concave profile for precision; wedge has a sharp angle for power',
    answer_b: 'Hollow-ground is for coarse beards; wedge is for fine beards',
    answer_c: 'Hollow-ground is heavier; wedge is lighter',
    answer_d: 'They are the same grind with different names',
    correct_answer: 'a',
    explanation: 'Hollow-ground: concave profile, "singing" edge, preferred for fine beards and precision. Wedge: sharp angle, powers through coarse, thick beards.',
    difficulty: 'hard',
    order_index: 26,
  },
  {
    id: 'qq-5-027',
    quiz_id: 'quiz-5',
    question: 'What should you do if you drop a straight razor?',
    answer_a: 'Catch it quickly before it hits the ground',
    answer_b: 'Step back and let it fall, then inspect for damage',
    answer_c: 'Kick it away from your feet',
    answer_d: 'Ignore it and grab a new one',
    correct_answer: 'b',
    explanation: 'STEP BACK and let it fall. NEVER attempt to catch a falling razor. A reflexive grab can cause a severe cut.',
    difficulty: 'easy',
    order_index: 27,
  },
  {
    id: 'qq-5-028',
    quiz_id: 'quiz-5',
    question: 'What is a crocus finish on a razor?',
    answer_a: 'The finest polish indicating superior edge retention and craftsmanship',
    answer_b: 'A type of blade guard',
    answer_c: 'A safety feature that prevents cuts',
    answer_d: 'A type of razor handle material',
    correct_answer: 'a',
    explanation: 'Crocus finish is the finest polish on razor steel — mirror-like smoothness indicating superior edge retention. Mark of master craftsmanship.',
    difficulty: 'hard',
    order_index: 28,
  },

  // THERMAL TOOLS (6 questions)
  {
    id: 'qq-5-029',
    quiz_id: 'quiz-5',
    question: 'What is a Marcel iron and why is it the professional standard?',
    answer_a: 'An automatic curling iron with a spring-loaded clamp',
    answer_b: 'A heated comb for textured hair',
    answer_c: 'A type of hair straightener',
    answer_d: 'A manual thermal iron with rotating handle for precise control',
    correct_answer: 'd',
    explanation: 'Marcel iron has a rotating handle for precise temperature and winding control. No spring — the barber controls clamp pressure and rotation.',
    difficulty: 'medium',
    order_index: 29,
  },
  {
    id: 'qq-5-030',
    quiz_id: 'quiz-5',
    question: 'What is the tissue test for thermal tools?',
    answer_a: 'Wiping the tool with a tissue to clean it',
    answer_b: 'Wrapping tissue around the client\'s neck',
    answer_c: 'Dragging the heated tool across tissue to check temperature',
    answer_d: 'Testing the tissue for moisture content',
    correct_answer: 'c',
    explanation: 'Drag the heated tool across tissue paper before client contact. Clean pass = ready. Scorching = too hot. Let cool and retest.',
    difficulty: 'easy',
    order_index: 30,
  },
  {
    id: 'qq-5-031',
    quiz_id: 'quiz-5',
    question: 'Why should you NEVER use a metal pressing comb directly on the scalp?',
    answer_a: 'It will tangle in the hair',
    answer_b: 'Metal on scalp causes serious burns',
    answer_c: 'It damages the comb',
    answer_d: 'It is against manufacturer warranty',
    correct_answer: 'b',
    explanation: 'Metal on scalp causes serious burns. Always maintain safe distance from skin. Pressing combs straighten hair sections, not touch scalp.',
    difficulty: 'easy',
    order_index: 31,
  },
  {
    id: 'qq-5-032',
    quiz_id: 'quiz-5',
    question: 'What blowdryer nozzle type disperses air for textured and curly hair to reduce frizz?',
    answer_a: 'Diffuser',
    answer_b: 'Concentrator',
    answer_c: 'Pick',
    answer_d: 'Vent',
    correct_answer: 'a',
    explanation: 'Diffuser disperses air for textured and curly hair to reduce frizz. Concentrator = precision. Pick = lifts roots and adds volume.',
    difficulty: 'easy',
    order_index: 32,
  },
  {
    id: 'qq-5-033',
    quiz_id: 'quiz-5',
    question: 'Is heat protectant mandatory before using thermal tools?',
    answer_a: 'Yes — mandatory for every client, no exceptions',
    answer_b: 'Only for clients with fine hair',
    answer_c: 'Only when using high heat settings',
    answer_d: 'No — it is optional and rarely needed',
    correct_answer: 'a',
    explanation: 'Heat protectant is MANDATORY — no exceptions. Creates a barrier preventing damage, breakage, and moisture loss. Apply to EVERY client.',
    difficulty: 'easy',
    order_index: 33,
  },
  {
    id: 'qq-5-034',
    quiz_id: 'quiz-5',
    question: 'Why should you never use a blowdryer near water?',
    answer_a: 'Water makes the hair too heavy to dry',
    answer_b: 'Electrocution risk — water and electricity are deadly',
    answer_c: 'It voids the warranty',
    answer_d: 'Water damages the motor over time',
    correct_answer: 'b',
    explanation: 'Electrocution risk. Water and electricity are a deadly combination. Keep blowdryers away from sinks, wet floors, and damp hands.',
    difficulty: 'easy',
    order_index: 34,
  },

  // STATION & SAFETY (6 questions)
  {
    id: 'qq-5-035',
    quiz_id: 'quiz-5',
    question: 'What temperature should towels be washed at to meet sanitation standards?',
    answer_a: '100°F (38°C)',
    answer_b: '120°F (49°C)',
    answer_c: '200°F (93°C)',
    answer_d: '160°F+ (71°C+)',
    correct_answer: 'd',
    explanation: '160°F+ (71°C+) hot water kills bacteria and pathogens. Towels must be completely dry and stored in a closed cabinet.',
    difficulty: 'easy',
    order_index: 35,
  },
  {
    id: 'qq-5-036',
    quiz_id: 'quiz-5',
    question: 'What is the purpose of a neck strip?',
    answer_a: 'To hold the cape closed',
    answer_b: 'A barrier preventing hair from touching skin and clothing',
    answer_c: 'To measure hair length',
    answer_d: 'To apply styling products',
    correct_answer: 'b',
    explanation: 'Neck strip is a barrier placed around the neck before the cape. Prevents hair from touching skin and clothing. One client, one strip.',
    difficulty: 'easy',
    order_index: 36,
  },
  {
    id: 'qq-5-037',
    quiz_id: 'quiz-5',
    question: 'What is styptic powder or pencil used for?',
    answer_a: 'Cleaning tools between clients',
    answer_b: 'Sharpening razor blades',
    answer_c: 'Applying aftershave',
    answer_d: 'Stopping bleeding from minor nicks and cuts instantly',
    correct_answer: 'd',
    explanation: 'Styptic stops bleeding from minor nicks and cuts instantly. Every station must have styptic. It contracts blood vessels and seals the cut.',
    difficulty: 'easy',
    order_index: 37,
  },
  {
    id: 'qq-5-038',
    quiz_id: 'quiz-5',
    question: 'What type of disinfectant is required for barbering tools?',
    answer_a: 'EPA-registered hospital-grade disinfectant',
    answer_b: 'Any cleaning spray from the grocery store',
    answer_c: 'Household bleach diluted with water',
    answer_d: 'Rubbing alcohol only',
    correct_answer: 'a',
    explanation: 'EPA-registered hospital-grade disinfectant proven effective against bacteria, viruses, AND fungi. Check the EPA registration number.',
    difficulty: 'medium',
    order_index: 38,
  },
  {
    id: 'qq-5-039',
    quiz_id: 'quiz-5',
    question: 'How long is the minimum contact time for disinfectant immersion?',
    answer_a: '2 minutes',
    answer_b: '5 minutes',
    answer_c: '10 minutes',
    answer_d: '30 minutes',
    correct_answer: 'c',
    explanation: '10 minutes minimum. At 5 minutes you kill ~50% of pathogens. At 10 minutes you kill 99.9%. SET A TIMER.',
    difficulty: 'medium',
    order_index: 39,
  },
  {
    id: 'qq-5-040',
    quiz_id: 'quiz-5',
    question: 'What should you do if a tool falls on the floor during service?',
    answer_a: 'Replace with a clean tool or stop and fully disinfect before continuing',
    answer_b: 'Wipe it on your apron and continue',
    answer_c: 'Rinse it under the sink quickly',
    answer_d: 'Blow on it to remove dust',
    correct_answer: 'a',
    explanation: 'Tools that touch the floor are contaminated. Replace with a clean tool or stop and fully disinfect. Never wipe on apron and reuse.',
    difficulty: 'easy',
    order_index: 40,
  },

  // BOARD EXAM ALERTS (6 questions)
  {
    id: 'qq-5-041',
    quiz_id: 'quiz-5',
    question: 'BOARD EXAM: What length does a #1 clipper guard cut?',
    answer_a: '1/16 inch (1.5mm)',
    answer_b: '3/8 inch (10mm)',
    answer_c: '1/4 inch (6mm)',
    answer_d: '1/8 inch (3mm)',
    correct_answer: 'd',
    explanation: '#1 = 1/8 inch (3mm). Memorize: #0=1/16in, #1=1/8in, #2=1/4in, #3=3/8in, #4=1/2in.',
    difficulty: 'easy',
    order_index: 41,
  },
  {
    id: 'qq-5-042',
    quiz_id: 'quiz-5',
    question: 'BOARD EXAM: Which shear handle types reduce repetitive strain injury (RSI) risk?',
    answer_a: 'Opposing handles only',
    answer_b: 'Offset and crane handles',
    answer_c: 'Traditional straight handles',
    answer_d: 'All handle types equally',
    correct_answer: 'b',
    explanation: 'Offset and crane handles reduce RSI risk. Offset: thumb hole set back. Crane: extreme offset with downward angle. Both are ergonomic.',
    difficulty: 'medium',
    order_index: 42,
  },
  {
    id: 'qq-5-043',
    quiz_id: 'quiz-5',
    question: 'BOARD EXAM: What is the difference between forged and cast shears?',
    answer_a: 'Forged shears are denser, stronger, and more durable',
    answer_b: 'Cast shears are denser and stronger',
    answer_c: 'There is no difference in quality',
    answer_d: 'Forged shears are always cheaper',
    correct_answer: 'a',
    explanation: 'Forged shears are denser, stronger, and more durable. Look for the weld line — it proves forged construction.',
    difficulty: 'hard',
    order_index: 43,
  },
  {
    id: 'qq-5-044',
    quiz_id: 'quiz-5',
    question: 'BOARD EXAM: What are the three types of shears and their primary uses?',
    answer_a: 'Straight (standard cutting), thinning (remove bulk), blending (blend clipper lines)',
    answer_b: 'Small, medium, and large shears for different hand sizes',
    answer_c: 'Cheap, mid-range, and expensive shears',
    answer_d: 'Left-handed, right-handed, and ambidextrous shears',
    correct_answer: 'a',
    explanation: 'Straight = standard cutting (90% of work). Thinning = remove bulk without changing length. Blending = blend lines between clipper and shear work.',
    difficulty: 'medium',
    order_index: 44,
  },
  {
    id: 'qq-5-045',
    quiz_id: 'quiz-5',
    question: 'BOARD EXAM: Which motor type is quiet, light, and best for fine to medium hair?',
    answer_a: 'Rotary motor',
    answer_b: 'Magnetic/Pivot motor',
    answer_c: 'Cordless lithium motor',
    answer_d: 'Hydraulic motor',
    correct_answer: 'b',
    explanation: 'Magnetic/Pivot motor: fast blade speed, quieter, lighter, best for fine to medium hair. Rotary is the professional standard for all hair types.',
    difficulty: 'medium',
    order_index: 45,
  },
  {
    id: 'qq-5-046',
    quiz_id: 'quiz-5',
    question: 'BOARD EXAM: What is the proper straight razor shaving sequence?',
    answer_a: 'Against the grain first, then with the grain',
    answer_b: 'Across the grain only',
    answer_c: 'With the grain first, then across, then against if needed',
    answer_d: 'Against the grain only for speed',
    correct_answer: 'c',
    explanation: 'With the grain first, then across, then against ONLY if needed and skin tolerates it. Stretch skin taut and use minimal pressure.',
    difficulty: 'medium',
    order_index: 46,
  },

  // SCENARIO CARDS (4 questions)
  {
    id: 'qq-5-047',
    quiz_id: 'quiz-5',
    question: 'SCENARIO: Your clippers start pulling hair mid-fade. The client winces. What is your FIRST action?',
    answer_a: 'Oil the blades and continue',
    answer_b: 'Switch to shears for the rest of the cut',
    answer_c: 'Tell the client to hold still',
    answer_d: 'STOP immediately, apologize, and switch to backup clippers',
    correct_answer: 'd',
    explanation: 'STOP immediately. Apologize professionally. Switch to backup clippers. Replace dull blades before next client. Never continue with dull blades.',
    difficulty: 'medium',
    order_index: 47,
  },
  {
    id: 'qq-5-048',
    quiz_id: 'quiz-5',
    question: 'SCENARIO: A client wants a skin fade with sharp lines and a beard trim. Which tools are REQUIRED?',
    answer_a: 'Shears and comb only',
    answer_b: 'Just clippers with a #1 guard',
    answer_c: 'Clippers with guards, trimmer, straight razor, and comb',
    answer_d: 'Trimmer and straight razor only',
    correct_answer: 'c',
    explanation: 'Clippers with guards for fade, trimmer for sharp lineup, straight razor for final edge and neck shave, comb for sectioning. Shears alone cannot create a skin fade.',
    difficulty: 'medium',
    order_index: 48,
  },
  {
    id: 'qq-5-049',
    quiz_id: 'quiz-5',
    question: 'SCENARIO: The practical exam examiner asks for the proper razor grip for the upper lip. Which grip?',
    answer_a: 'Reverse freehand',
    answer_b: 'Backhand grip',
    answer_c: 'Freehand grip',
    answer_d: 'Reverse backhand',
    correct_answer: 'a',
    explanation: 'Reverse freehand for upper lip and chin. Reverse backhand is NECK ONLY — using it on the face fails the exam.',
    difficulty: 'hard',
    order_index: 49,
  },
  {
    id: 'qq-5-050',
    quiz_id: 'quiz-5',
    question: 'SCENARIO: A tool falls on the floor during a haircut. Can you wipe it on your apron and continue?',
    answer_a: 'Yes, if the floor looks clean',
    answer_b: 'Yes, but only for the current client',
    answer_c: 'Only if you spray it with water first',
    answer_d: 'No — tools that touch the floor are contaminated and must be disinfected or replaced',
    correct_answer: 'd',
    explanation: 'NO. Tools that touch the floor are contaminated. Replace with a clean tool or stop and fully disinfect. Wiping on an apron does NOT disinfect.',
    difficulty: 'easy',
    order_index: 50,
  },
]

// Stats
export const chapter5QuizStats = {
  total: chapter5PremiumQuizQuestions.length,
  byDifficulty: {
    easy: chapter5PremiumQuizQuestions.filter((q) => q.difficulty === 'easy').length,
    medium: chapter5PremiumQuizQuestions.filter((q) => q.difficulty === 'medium').length,
    hard: chapter5PremiumQuizQuestions.filter((q) => q.difficulty === 'hard').length,
  },
}


