import type { QuizQuestion } from '@/types'
import type { ConceptId } from './chapter-2-concepts/types'
type A='a'|'b'|'c'|'d'; type D='easy'|'medium'|'hard'
interface S{conceptId:ConceptId;sourceBlockIds:readonly string[];sourceBasis:string;items:readonly {question:string;answer_a:string;answer_b:string;answer_c:string;answer_d:string;correct_answer:A;explanation:string;difficulty:D}[]}
const seeds:readonly S[]=[
{conceptId:'C-2-03',sourceBlockIds:['daily-discipline','mindset-challenges'],sourceBasis:'ASCYN Chapter 2 lesson and instructor notes: motivation can start action; discipline sustains action when motivation fades; procrastination and perfectionistic delay weaken follow-through.',items:[
{question:'A student feels unmotivated but still completes the scheduled practice block. Which Chapter 2 concept is being demonstrated most directly?',answer_a:'Discipline continues the planned action even when motivation is low.',answer_b:'Motivation automatically increases whenever a schedule is written down.',answer_c:'Perfectionism improves consistency because it raises standards.',answer_d:'Procrastination is useful when inspiration is temporarily low.',correct_answer:'a',explanation:'Chapter 2 distinguishes motivation from discipline: motivation can start action, while discipline carries planned action through low-motivation periods.',difficulty:'medium'},
{question:'A student keeps saying, “I will practice when I feel inspired.” What is the strongest Chapter 2 correction?',answer_a:'Wait for a stronger goal because a good goal creates constant motivation.',answer_b:'Build a repeatable schedule so action is not dependent on how motivated you feel that day.',answer_c:'Practice only on high-energy days to protect confidence.',answer_d:'Replace scheduled practice with watching skilled barbers online.',correct_answer:'b',explanation:'Discipline uses routines and commitments to reduce dependence on temporary feelings, which is why a schedule is stronger than waiting for inspiration.',difficulty:'medium'},
{question:'Which pattern is most likely to interfere with disciplined progress?',answer_a:'Reviewing a plan and adjusting a realistic deadline.',answer_b:'Completing a small scheduled task before relaxing.',answer_c:'Delaying action repeatedly while waiting for perfect conditions.',answer_d:'Using an accountability partner to check progress.',correct_answer:'c',explanation:'Repeated delay and perfectionistic waiting are Chapter 2 examples of habits that prevent consistent action and weaken progress.',difficulty:'medium'},
{question:'A student starts each week enthusiastically but stops practicing by Wednesday. What change best targets the underlying problem?',answer_a:'Choose a more exciting career goal each Monday.',answer_b:'Increase the difficulty of every practice session.',answer_c:'Avoid tracking practice because missed days can feel discouraging.',answer_d:'Use smaller scheduled commitments and follow them even after the initial enthusiasm fades.',correct_answer:'d',explanation:'The problem is weak follow-through rather than weak initial motivation; smaller scheduled commitments create discipline that can persist after enthusiasm declines.',difficulty:'hard'}]},
{conceptId:'C-2-04',sourceBlockIds:['mission-foundations','mission-creation','mission-evaluation'],sourceBasis:'ASCYN Chapter 2 lesson and instructor notes: a mission statement expresses identity, values, and direction; a goal is a target with an endpoint.',items:[
{question:'Which statement is most like a personal mission rather than a short-term goal?',answer_a:'I aim to serve clients with skill, respect, and continuous growth throughout my career.',answer_b:'I will complete twenty practice cuts before the end of this month.',answer_c:'I will save five hundred dollars by the first day of summer.',answer_d:'I will post three portfolio photos each week for eight weeks.',correct_answer:'a',explanation:'A mission expresses enduring identity, values, and direction. The other statements are measurable targets with endpoints, which makes them goals.',difficulty:'medium'},
{question:'A student writes, “Pass my licensing exam in January,” and calls it a mission statement. What is the best correction?',answer_a:'It is a mission because it describes an important career milestone.',answer_b:'It is a goal because it has a specific endpoint; a mission should express broader identity and direction.',answer_c:'It is neither because it does not mention money.',answer_d:'It becomes a mission if written in first person.',correct_answer:'b',explanation:'Instructor guidance uses the expiration test: if the statement ends when achieved, it functions as a goal rather than an enduring mission.',difficulty:'medium'},
{question:'What should a strong personal mission help a barber evaluate?',answer_a:'Whether every daily task produces immediate income.',answer_b:'Whether other barbers agree with every career decision.',answer_c:'Whether choices and habits are consistent with the professional they intend to become.',answer_d:'Whether each goal can be completed in less than one year.',correct_answer:'c',explanation:'A mission provides a durable reference point for identity, values, and direction, helping a person test whether choices align with that larger purpose.',difficulty:'hard'},
{question:'A mission statement has become so narrow that it only describes one temporary project. What is the best revision?',answer_a:'Add more deadlines and numerical targets.',answer_b:'Replace it with a list of every monthly task.',answer_c:'Remove all reference to values.',answer_d:'Broaden it to reflect enduring values, purpose, and how the barber intends to serve and grow.',correct_answer:'d',explanation:'Mission statements guide beyond a single project. Broadening toward enduring values and professional direction restores the intended function.',difficulty:'hard'}]},
{conceptId:'C-2-05',sourceBlockIds:['attitude-framework','attitude-composure','attitude-communication','attitude-interest','attitude-positivity','attitude-scenarios'],sourceBasis:'ASCYN Chapter 2 lesson: professional attitude appears through composure, respectful communication, genuine interest, reliability, and constructive behavior on difficult days.',items:[
{question:'A barber is having a difficult day but has a client arriving in five minutes. Which response best reflects a positive professional attitude?',answer_a:'Reset, greet the client respectfully, and keep personal frustration from controlling the service interaction.',answer_b:'Explain every personal problem so the client understands any drop in quality.',answer_c:'Rush the service so the difficult day ends sooner.',answer_d:'Cancel automatically whenever mood is not ideal.',correct_answer:'a',explanation:'Professional attitude requires composure and respectful client care despite ordinary personal frustration; it does not require pretending every day is perfect.',difficulty:'hard'},
{question:'Which behavior best demonstrates professional composure?',answer_a:'Responding to criticism immediately while emotions are highest.',answer_b:'Pausing, listening, and answering respectfully instead of reacting defensively.',answer_c:'Avoiding every difficult conversation to preserve a positive mood.',answer_d:'Agreeing with every statement even when clarification is needed.',correct_answer:'b',explanation:'Composure is visible in managing reactions, listening, and communicating respectfully under pressure rather than becoming defensive or avoidant.',difficulty:'medium'},
{question:'A barber wants clients to experience genuine professional interest. Which action best supports that goal?',answer_a:'Use the exact same conversation script with every client.',answer_b:'Keep conversation focused on the barber’s own experiences.',answer_c:'Pay attention to the client’s preferences, ask relevant questions, and respond to what they actually say.',answer_d:'Avoid conversation entirely so no misunderstanding can occur.',correct_answer:'c',explanation:'Genuine interest is demonstrated through attention, respectful questions, and responsive communication rather than a fixed script or self-focused conversation.',difficulty:'medium'},
{question:'Which statement best captures Chapter 2’s idea of a positive professional attitude?',answer_a:'A professional must feel cheerful every moment.',answer_b:'A professional should hide every concern rather than discuss problems appropriately.',answer_c:'A positive attitude means accepting poor behavior from clients or coworkers.',answer_d:'A professional chooses reliable, respectful, constructive behavior even when the day is difficult.',correct_answer:'d',explanation:'The chapter frames attitude as chosen professional behavior—composure, reliability, respectful communication, and constructive action—not constant happiness or passivity.',difficulty:'medium'}]}
]
export const chapter2G5ReassessmentQuestionsP2:QuizQuestion[]=seeds.flatMap((s,si)=>s.items.map((x,qi)=>({id:`qq-2-${String(84+si*4+qi).padStart(3,'0')}`,quiz_id:'quiz-2',...x,order_index:84+si*4+qi})))
export const chapter2G5ReassessmentMappingsP2=chapter2G5ReassessmentQuestionsP2.map((q,i)=>({questionId:q.id as `qq-2-${string}`,conceptId:seeds[Math.floor(i/4)].conceptId}))
export const chapter2G5ReassessmentAuditP2=chapter2G5ReassessmentQuestionsP2.map((q,i)=>{const s=seeds[Math.floor(i/4)];return{questionId:q.id,conceptId:s.conceptId,sourceBlockIds:s.sourceBlockIds,sourceBasis:s.sourceBasis}})
