import type { QuizQuestion } from '@/types'
import type { ConceptId } from './chapter-2-concepts/types'
type A='a'|'b'|'c'|'d'; type D='easy'|'medium'|'hard'
interface S{conceptId:ConceptId;sourceBlockIds:readonly string[];sourceBasis:string;items:readonly {question:string;answer_a:string;answer_b:string;answer_c:string;answer_d:string;correct_answer:A;explanation:string;difficulty:D}[]}
const seeds:readonly S[]=[
{conceptId:'C-2-16',sourceBlockIds:['mental-health'],sourceBasis:'ASCYN Chapter 2 lesson: work-life balance uses boundaries, support, outside interests, and sustainable scheduling so work does not consume every part of life.',items:[
{question:'A barber answers client messages at all hours and rarely takes personal time. Which Chapter 2 change best supports work-life balance?',answer_a:'Set reasonable communication boundaries and protect personal recovery time.',answer_b:'Stop replying to clients altogether.',answer_c:'Add more late-night work so messages never accumulate.',answer_d:'Use personal time only when the appointment book is empty.',correct_answer:'a',explanation:'Chapter 2 treats boundaries and recovery time as part of sustainable professional performance rather than allowing work to occupy every available hour.',difficulty:'medium'},
{question:'Why can hobbies outside barbering support a healthier career?',answer_a:'They guarantee higher income.',answer_b:'They provide another source of identity and recovery instead of making work the only source of energy or self-worth.',answer_c:'They replace the need for professional development.',answer_d:'They eliminate stressful clients.',correct_answer:'b',explanation:'The lesson encourages interests outside work because they can recharge the person and help prevent the job from consuming all emotional and personal space.',difficulty:'medium'},
{question:'A student regularly sacrifices sleep to complete every optional task. What is the strongest Chapter 2 correction?',answer_a:'Keep the schedule because productivity always matters more than rest.',answer_b:'Skip school whenever fatigue becomes noticeable.',answer_c:'Rebalance commitments so necessary work and recovery can coexist instead of treating sleep as expendable.',answer_d:'Add caffeine and keep the same routine.',correct_answer:'c',explanation:'Work-life balance requires sustainable tradeoffs; routinely sacrificing recovery can undermine performance and is not the model Chapter 2 teaches.',difficulty:'hard'},
{question:'Which statement best reflects healthy professional boundaries?',answer_a:'A good barber is always available to every client.',answer_b:'Boundaries are useful only for shop owners.',answer_c:'Saying no is unprofessional when a client asks for extra time.',answer_d:'Reliable service can coexist with clear limits on hours, availability, and personal time.',correct_answer:'d',explanation:'Chapter 2 frames boundaries as compatible with professionalism: the goal is dependable service without treating unlimited availability as a requirement.',difficulty:'medium'}]},
{conceptId:'C-2-17',sourceBlockIds:['communication-intro','communication-mistakes','comm-challenges'],sourceBasis:'ASCYN Chapter 2 lesson: professional communication combines clear verbal messages, nonverbal awareness, respectful tone, and appropriate responses to misunderstandings.',items:[
{question:'A client looks confused after the barber explains the service plan. What is the best communication response?',answer_a:'Restate the plan in clearer language and verify understanding before proceeding.',answer_b:'Repeat the same explanation louder.',answer_c:'Assume the client will understand once the service begins.',answer_d:'Avoid further questions so the appointment stays on time.',correct_answer:'a',explanation:'Professional communication includes adapting the message when the first explanation does not create understanding, then confirming that both people agree on the plan.',difficulty:'medium'},
{question:'Which factor can weaken otherwise correct verbal communication?',answer_a:'Using a respectful greeting.',answer_b:'A dismissive tone or body language that conflicts with the words being spoken.',answer_c:'Asking one clarifying question.',answer_d:'Confirming an appointment time.',correct_answer:'b',explanation:'Communication is not only the words used; tone and nonverbal behavior can contradict the spoken message and affect how the client receives it.',difficulty:'medium'},
{question:'A coworker misinterprets a brief message and becomes upset. What is the most professional next step?',answer_a:'Ignore the issue because the original message was technically accurate.',answer_b:'Send several more short messages without context.',answer_c:'Clarify the intent directly and respectfully, then confirm that the misunderstanding is resolved.',answer_d:'Ask another coworker to explain it instead.',correct_answer:'c',explanation:'When communication fails, professional practice is to clarify directly and respectfully rather than defend the original wording or let the misunderstanding continue.',difficulty:'hard'},
{question:'Which habit most often improves professional communication?',answer_a:'Using technical terms whenever possible.',answer_b:'Speaking continuously so no silence occurs.',answer_c:'Assuming familiar clients already know what is meant.',answer_d:'Matching the message to the situation and checking whether it was understood.',correct_answer:'d',explanation:'Effective communication is audience-aware and includes confirmation, especially when details affect expectations, timing, or the service result.',difficulty:'medium'}]},
{conceptId:'C-2-18',sourceBlockIds:['active-listening','consultation-skills'],sourceBasis:'ASCYN Chapter 2 lesson and instructor notes: active listening is demonstrated by attention, clarifying questions, and accurate repeat-back before service decisions are made.',items:[
{question:'A client says, “Just make it look cleaner,” without giving details. What should the barber do first?',answer_a:'Ask specific questions and repeat the agreed plan back before starting.',answer_b:'Choose the barber’s usual interpretation of “cleaner.”',answer_c:'Start conservatively and ask only if the client objects.',answer_d:'Skip the consultation because the request is simple.',correct_answer:'a',explanation:'Chapter 2 makes active listening observable through clarification and repeat-back, especially when the client’s first request is vague.',difficulty:'hard'},
{question:'What is the strongest evidence that a barber actually listened during a consultation?',answer_a:'The barber remained silent while the client talked.',answer_b:'The barber can accurately summarize the client’s priorities and confirm them before service.',answer_c:'The barber gave several suggestions quickly.',answer_d:'The barber used professional terminology.',correct_answer:'b',explanation:'Silence alone is not active listening. Accurate summarization and confirmation show that the client’s actual message was heard and understood.',difficulty:'medium'},
{question:'A client changes one detail after hearing the barber repeat the plan. What does that indicate?',answer_a:'The consultation failed because the first plan changed.',answer_b:'The client is being indecisive and should choose immediately.',answer_c:'The repeat-back worked by exposing a mismatch before the service began.',answer_d:'The barber should return to the original plan to stay efficient.',correct_answer:'c',explanation:'The purpose of confirmation is to catch mismatched expectations early; a correction before service is a successful consultation outcome.',difficulty:'application'},
{question:'Which behavior is least consistent with active listening?',answer_a:'Clarifying unfamiliar terms.',answer_b:'Watching for relevant nonverbal cues.',answer_c:'Repeating the key request in your own words.',answer_d:'Planning your response while the client is still talking instead of attending to what they say.',correct_answer:'d',explanation:'Instructor guidance explicitly distinguishes active listening from merely waiting to speak; attention must remain on understanding the client before formulating a response.',difficulty:'hard'}]},
{conceptId:'C-2-19',sourceBlockIds:['conflict-intro','step-1-listen','step-2-empathize','step-3-fix','step-4-follow-up','conflict-pro-tip','conflict-actions'],sourceBasis:'ASCYN Chapter 2 lesson: conflict resolution uses private, calm communication focused on the behavior, listening first, empathy, a workable solution, and follow-up.',items:[
{question:'A coworker repeatedly leaves a shared station messy. What is the best first conflict-resolution approach?',answer_a:'Speak privately, describe the specific behavior calmly, and invite a practical solution.',answer_b:'Correct the coworker publicly so the message is clear.',answer_c:'Stop speaking to the coworker until the problem changes.',answer_d:'Complain to clients so they understand the frustration.',correct_answer:'a',explanation:'Chapter 2 conflict resolution is private, calm, and focused on the behavior rather than humiliating the person or avoiding the issue.',difficulty:'hard'},
{question:'Why is listening the first step in resolving many conflicts?',answer_a:'It proves the other person is correct.',answer_b:'It helps identify the actual concern before choosing a response or solution.',answer_c:'It prevents the need for any later action.',answer_d:'It allows the listener to delay the conversation indefinitely.',correct_answer:'b',explanation:'Listening gives the professional enough information to understand the problem accurately before reacting, defending, or proposing a fix.',difficulty:'medium'},
{question:'A conflict has been discussed and a solution agreed on. What should happen next?',answer_a:'Assume the agreement will work and never mention it again.',answer_b:'Tell other coworkers who was at fault.',answer_c:'Follow up later to confirm the agreement is working and adjust if needed.',answer_d:'Create a stricter rule for every unrelated situation.',correct_answer:'c',explanation:'Follow-up is part of the Chapter 2 conflict sequence because it checks whether the solution actually resolved the issue rather than only ending the conversation.',difficulty:'medium'},
{question:'Which behavior most often escalates conflict unnecessarily?',answer_a:'Using specific examples of the behavior.',answer_b:'Choosing a private setting.',answer_c:'Acknowledging the other person’s perspective.',answer_d:'Turning the issue into a personal attack instead of addressing the behavior.',correct_answer:'d',explanation:'Personal attacks make conflict about identity and defensiveness; Chapter 2 keeps the discussion specific to the behavior and the workable change needed.',difficulty:'hard'}]},
{conceptId:'C-2-20',sourceBlockIds:['networking-intro','networking-myths','where-to-network','building-relationships'],sourceBasis:'ASCYN enrichment in Chapter 2: networking means building genuine professional relationships through engagement, giving value, staying in touch, and showing gratitude.',items:[
{question:'A student wants to begin networking before graduation. What is the best first move?',answer_a:'Build genuine relationships with instructors, classmates, local barbers, and industry contacts already within reach.',answer_b:'Wait until licensed because students have nothing useful to contribute.',answer_c:'Buy advertising so professionals recognize the student’s name first.',answer_d:'Ask strangers for jobs before learning anything about their work.',correct_answer:'a',explanation:'ASCYN networking starts with authentic relationships in the student’s existing professional environment rather than waiting or immediately asking for favors.',difficulty:'medium'},
{question:'Which action best reflects the “give first” networking principle?',answer_a:'Ask every new contact for a referral during the first conversation.',answer_b:'Share a useful resource, make a helpful introduction, or support someone’s work before asking for something.',answer_c:'Contact people only when a job opening appears.',answer_d:'Measure each relationship only by immediate financial return.',correct_answer:'b',explanation:'The Chapter 2 networking material emphasizes contributing value and building trust before treating the relationship as a source of favors.',difficulty:'medium'},
{question:'Why does staying in touch matter after meeting a professional contact?',answer_a:'It guarantees the person will eventually offer a job.',answer_b:'It keeps the contact obligated to respond.',answer_c:'Occasional genuine engagement helps a relationship remain active instead of disappearing after one meeting.',answer_d:'It replaces the need to develop professional skill.',correct_answer:'c',explanation:'Relationships weaken when they are only one-time exchanges; simple authentic follow-up helps maintain connection without turning it into pressure.',difficulty:'application'},
{question:'Which behavior is least consistent with genuine networking?',answer_a:'Showing sincere interest in another barber’s work.',answer_b:'Thanking someone who offered useful guidance.',answer_c:'Attending industry or school events to meet people.',answer_d:'Pretending interest only long enough to ask the person for an immediate favor.',correct_answer:'d',explanation:'ASCYN distinguishes genuine relationship building from transactional behavior; networking should not be fake interest used only to obtain something quickly.',difficulty:'hard'}]}
]
export const chapter2G5ReassessmentQuestionsP5:QuizQuestion[]=seeds.flatMap((s,si)=>s.items.map((x,qi)=>({id:`qq-2-${String(136+si*4+qi).padStart(3,'0')}`,quiz_id:'quiz-2',...x,order_index:136+si*4+qi})))
export const chapter2G5ReassessmentMappingsP5=chapter2G5ReassessmentQuestionsP5.map((q,i)=>({questionId:q.id as `qq-2-${string}`,conceptId:seeds[Math.floor(i/4)].conceptId}))
export const chapter2G5ReassessmentAuditP5=chapter2G5ReassessmentQuestionsP5.map((q,i)=>{const s=seeds[Math.floor(i/4)];return{questionId:q.id,conceptId:s.conceptId,sourceBlockIds:s.sourceBlockIds,sourceBasis:s.sourceBasis}})
