// Chapter 2 Premium Flashcard System
// Life Skills — 45 premium flashcards
// Categories: Foundation Knowledge, Definitions, Board Exam Alerts, Visual Identification,
//             Scenario Thinking, Procedure/Process Knowledge, Safety Concepts, Memory Reinforcement
// Source: Chapter 2 textbook curriculum, learning objectives, and board exam concepts

import { Flashcard } from '@/types'

export const chapter2PremiumFlashcards: Flashcard[] = [
  // ═══════════════════════════════════════════════════════════════
  // CATEGORY 1: FOUNDATION KNOWLEDGE (10 cards)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'fc-2-001',
    chapter_id: 'ch-2',
    front: 'According to the Chapter 2 curriculum, what percentage of barber success comes from life and business skills versus technical skills?',
    back: '60% of barber success comes from life and business skills. Only 40% comes from technical skills like cutting, styling, and sanitation. This is why life skills are equally essential to master.',
    category: 'Foundation Knowledge',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-2-002',
    chapter_id: 'ch-2',
    front: 'List the seven essential life skills that barbers need for career success.',
    back: '1) Communication, 2) Decision-making, 3) Image-building, 4) Customer service, 5) Self-actualization, 6) Goal-setting, and 7) Time management. These skills ensure positive interactions with diverse clients and coworkers.',
    category: 'Foundation Knowledge',
    difficulty: 'medium',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-2-003',
    chapter_id: 'ch-2',
    front: 'What is self-actualization, and why is it described as requiring "lifelong commitment"?',
    back: 'Self-actualization is fulfilling your full potential. It requires lifelong commitment because personal growth, skill development, and career advancement are continuous processes — not one-time achievements.',
    category: 'Foundation Knowledge',
    difficulty: 'medium',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-2-004',
    chapter_id: 'ch-2',
    front: 'What are the three destructive habits that kill productivity, according to Chapter 2?',
    back: '1) Procrastination — putting things off; 2) Perfectionism — unhealthy need to do everything flawlessly; 3) Lack of a game plan — no organized goals or direction. All three prevent progress.',
    category: 'Foundation Knowledge',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-2-005',
    chapter_id: 'ch-2',
    front: 'What is the difference between short-term goals and long-term goals in the context of barber career planning?',
    back: 'Short-term goals are accomplished in one year or less (passing an exam, graduating school). Long-term goals span two or more years (owning a barbershop in five years). Both require written action plans.',
    category: 'Foundation Knowledge',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-2-006',
    chapter_id: 'ch-2',
    front: 'What does the acronym SMART stand for in goal-setting, and why is each element important for barbers?',
    back: 'S = Specific (clear target), M = Measurable (track progress), A = Achievable (realistic), R = Relevant (career-aligned), T = Time-bound (deadline-driven). Vague goals like "get better" fail because they lack measurable criteria.',
    category: 'Foundation Knowledge',
    difficulty: 'medium',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-2-007',
    chapter_id: 'ch-2',
    front: 'According to the 50/30/20 rule, how should a barber allocate their income across needs, wants, and savings?',
    back: '50% to needs (rent, food, utilities), 30% to wants (entertainment, dining out), and 20% to savings and debt repayment. This budgeting framework helps barbers build financial stability.',
    category: 'Foundation Knowledge',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-2-008',
    chapter_id: 'ch-2',
    front: 'What percentage of income should booth renters set aside for taxes, and why is this higher than traditional employees?',
    back: 'Booth renters should set aside 25-30% of income for taxes. They are self-employed and responsible for their own tax payments, including self-employment tax, with no employer withholding.',
    category: 'Foundation Knowledge',
    difficulty: 'medium',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-2-009',
    chapter_id: 'ch-2',
    front: 'What is the recommended starting amount for an emergency fund, and what is the ultimate savings goal?',
    back: 'Start with a $1,000 mini emergency fund. Build to 3 months of expenses, then aim for 6 months as the ultimate goal. This protects against income gaps common in the barbering profession.',
    category: 'Foundation Knowledge',
    difficulty: 'easy',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-2-010',
    chapter_id: 'ch-2',
    front: 'What is the 2-Minute Rule for time management, and how does it apply in a busy barbershop?',
    back: 'If a task takes less than 2 minutes, do it immediately rather than letting small tasks pile up. In a barbershop, this means wiping stations, sanitizing tools, or confirming appointments right away.',
    category: 'Foundation Knowledge',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // CATEGORY 2: DEFINITIONS (8 cards)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'fc-2-011',
    chapter_id: 'ch-2',
    front: 'Define "mission statement" and explain its purpose for a barber professional.',
    back: 'A mission statement defines your purpose, values, and direction. It provides focus and becomes the "cultural pulse" of your professional life. Example: "I am dedicated to pursuing a successful career with dignity, honesty, and integrity."',
    category: 'Definitions',
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-2-012',
    chapter_id: 'ch-2',
    front: 'Define "ethics" as it applies to the barbering profession.',
    back: 'Ethics are the moral principles that guide how barbers live and work. They include honesty, integrity, confidentiality, and providing skilled, competent services to every client.',
    category: 'Definitions',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-2-013',
    chapter_id: 'ch-2',
    front: 'Define "diplomacy" (or "tact") and explain why it is essential in client communication.',
    back: 'Diplomacy is delivering truthful messages and feedback in a kind, respectful manner that preserves relationships. It prevents unnecessary conflict while maintaining professional honesty.',
    category: 'Definitions',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-2-014',
    chapter_id: 'ch-2',
    front: 'Define "emotional stability" and explain its importance for barbers dealing with difficult clients.',
    back: 'Emotional stability is the ability to remain calm and professional during confrontations or stressful situations. Barbers encounter diverse personalities daily; emotional stability ensures reactive behavior does not damage client relationships.',
    category: 'Definitions',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-2-015',
    chapter_id: 'ch-2',
    front: 'Define "self-esteem" and describe how it impacts professional performance.',
    back: 'Self-esteem is how much you value yourself and your abilities. High self-esteem helps barbers handle challenges, accept constructive criticism, and project confidence — all of which attract and retain clients.',
    category: 'Definitions',
    difficulty: 'easy',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-2-016',
    chapter_id: 'ch-2',
    front: 'Define "burnout" and list three warning signs that a barber should watch for.',
    back: 'Burnout is chronic physical and emotional exhaustion from prolonged stress. Warning signs: dreading work, chronic fatigue, irritability with clients, physical aches, and loss of creativity.',
    category: 'Definitions',
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-2-017',
    chapter_id: 'ch-2',
    front: 'Define "continuing education" and explain why it is considered an ethical responsibility.',
    back: 'Continuing education is ongoing learning to maintain and enhance professional skills. It is an ethical responsibility because barbers must stay current with techniques, sanitation standards, and industry trends to serve clients competently.',
    category: 'Definitions',
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-2-018',
    chapter_id: 'ch-2',
    front: 'Define "active listening" and contrast it with passive hearing.',
    back: 'Active listening is fully concentrating on what is being said, processing the message, and responding appropriately. Passive hearing is simply letting sound enter your ears without engagement. Active listening prevents misunderstandings during client consultations.',
    category: 'Definitions',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // CATEGORY 3: BOARD EXAM ALERTS (6 cards)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'fc-2-019',
    chapter_id: 'ch-2',
    front: 'BOARD EXAM ALERT: What are the five professional actions that demonstrate ethical conduct on the state board exam?',
    back: '1) Provide skilled and competent services, 2) Be honest, courteous, and sincere, 3) Keep client information confidential (discretion), 4) Participate in continuing education, 5) Give accurate information about treatments and products.',
    category: 'Board Exam Alerts',
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-2-020',
    chapter_id: 'ch-2',
    front: 'BOARD EXAM ALERT: Why is client confidentiality a legal and ethical requirement that may appear on licensing exams?',
    back: 'Clients share personal information during services. Protecting their privacy builds trust and is a core ethical obligation. Violating confidentiality can result in disciplinary action, fines, or license revocation.',
    category: 'Board Exam Alerts',
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-2-021',
    chapter_id: 'ch-2',
    front: 'BOARD EXAM ALERT: What is the recommended emergency fund amount that state board exams may reference as a financial responsibility standard?',
    back: 'State boards and financial literacy standards recommend starting with $1,000, building to 3 months of expenses, and ultimately maintaining 6 months of expenses as an emergency fund.',
    category: 'Board Exam Alerts',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-2-022',
    chapter_id: 'ch-2',
    front: 'BOARD EXAM ALERT: When recommending products to clients, what is the ethical rule that protects both the barber and the client?',
    back: 'Only recommend products that genuinely help the client. Recommending unnecessary products destroys trust and may violate consumer protection laws. Ethical barbers prioritize client benefit over commission.',
    category: 'Board Exam Alerts',
    difficulty: 'easy',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-2-023',
    chapter_id: 'ch-2',
    front: 'BOARD EXAM ALERT: What is the service recovery paradox, and why should barbers understand it for both the exam and real practice?',
    back: 'The service recovery paradox states that clients whose problems are resolved professionally often become MORE loyal than clients who never experienced issues. This means complaints are opportunities, not threats.',
    category: 'Board Exam Alerts',
    difficulty: 'hard',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-2-024',
    chapter_id: 'ch-2',
    front: 'BOARD EXAM ALERT: What is the most important rule of shop etiquette regarding another barber\'s regular clients?',
    back: 'Never poach another barber\'s regular clients. If their client asks you for a cut, redirect them back to their regular barber. Violating this destroys shop harmony and professional reputation.',
    category: 'Board Exam Alerts',
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // CATEGORY 4: VISUAL IDENTIFICATION (5 cards)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'fc-2-025',
    chapter_id: 'ch-2',
    front: 'IDENTIFY: A visual planning tool where the main topic sits in the center, with branches radiating outward using key words, colors, and symbols.',
    back: 'A MIND MAP. This study technique helps barber students organize complex information visually, making it easier to recall during exams and apply in practice.',
    category: 'Visual Identification',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-2-026',
    chapter_id: 'ch-2',
    front: 'IDENTIFY: A time management technique using 25-minute focused work blocks followed by short breaks — often visualized as a tomato-shaped timer.',
    back: 'The POMODORO TECHNIQUE. Twenty-five minutes of focused study followed by a 5-minute break. After four cycles, take a longer 15-30 minute break. Ideal for barber students balancing school and work.',
    category: 'Visual Identification',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-2-027',
    chapter_id: 'ch-2',
    front: 'IDENTIFY: A financial tracking method where income is divided into three categories: 50% needs, 30% wants, 20% savings.',
    back: 'The 50/30/20 BUDGET RULE. This visual framework helps barbers allocate income responsibly. Booth renters must also account for the 25-30% self-employment tax within their "needs" category.',
    category: 'Visual Identification',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-2-028',
    chapter_id: 'ch-2',
    front: 'IDENTIFY: A communication technique where you repeat back what the client wants and get their approval before picking up any tool.',
    back: 'THE CONSULTATION CONFIRMATION STEP. This visual/verbal check prevents misunderstandings. Example: "So you want a low fade with a 2 on top, blended into the beard — is that correct?"',
    category: 'Visual Identification',
    difficulty: 'medium',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-2-029',
    chapter_id: 'ch-2',
    front: 'IDENTIFY: A weekly planning session where a barber maps out priorities, appointments, and personal time before Monday begins.',
    back: 'THE SUNDAY PLANNING SESSION. Spending 30 minutes on Sunday organizing the week ensures you know your priorities before the workweek starts. Visual planners and digital calendars both work.',
    category: 'Visual Identification',
    difficulty: 'easy',
    order_index: 29,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // CATEGORY 5: SCENARIO THINKING (5 cards)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'fc-2-030',
    chapter_id: 'ch-2',
    front: 'SCENARIO: A client is unhappy with their haircut and raises their voice in the shop. What is the FIRST step in the complaint recovery system?',
    back: 'Listen fully without interrupting or defending. Let the client express their concerns completely. The first step is NEVER to argue, blame, or offer solutions before understanding the full problem.',
    category: 'Scenario Thinking',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-2-031',
    chapter_id: 'ch-2',
    front: 'SCENARIO: You are a booth renter and tax season approaches. You have not set aside any money for taxes. What should you have done, and what do you do now?',
    back: 'You should have set aside 25-30% of every payment in a separate tax savings account. Now: immediately calculate estimated taxes, set up quarterly payments, create a stricter budget, and consult a tax professional.',
    category: 'Scenario Thinking',
    difficulty: 'hard',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-2-032',
    chapter_id: 'ch-2',
    front: 'SCENARIO: A new client walks in and asks for a style you are not confident executing. They say, "I saw you do this on Instagram." What is the most ethical response?',
    back: 'Be honest: "I want to give you exactly what you want, and I am not confident I can execute that style to my standards today. Let me refer you to [colleague] who specializes in this, or we can book a consultation to plan it together."',
    category: 'Scenario Thinking',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-2-033',
    chapter_id: 'ch-2',
    front: 'SCENARIO: Your shop is extremely busy on a Saturday. A walk-in expects immediate service, but you are already 20 minutes behind. How do you handle this professionally?',
    back: 'Stay calm, communicate honestly: "I would love to take care of you. I am running about 20 minutes behind. I can fit you in at [specific time], or I can book you for [later time] to give you my full attention." Never rush quality.',
    category: 'Scenario Thinking',
    difficulty: 'medium',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-2-034',
    chapter_id: 'ch-2',
    front: 'SCENARIO: You notice a coworker is showing signs of burnout — dreading work, irritable with clients, and making mistakes. As a team member, what should you do?',
    back: 'Privately express concern, offer support, and suggest they talk to the shop owner or take a mental health day. Burnout affects the entire shop. Encourage breaks, proper rest, and professional help if needed.',
    category: 'Scenario Thinking',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // CATEGORY 6: PROCEDURE/PROCESS KNOWLEDGE (6 cards)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'fc-2-035',
    chapter_id: 'ch-2',
    front: 'What is the correct step-by-step process for breaking a big goal into actionable steps?',
    back: 'Step 1: Write the big goal clearly. Step 2: Break it into smaller milestones. Step 3: Create action plans for each milestone. Step 4: Set deadlines. Step 5: Revisit and adjust regularly. Example: "Open shop in 3 years" becomes monthly savings targets, licensing steps, and location research.',
    category: 'Procedure/Process Knowledge',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-2-036',
    chapter_id: 'ch-2',
    front: 'Describe the proper note-taking process for barber students to maximize retention.',
    back: '1) Listen for emphasized words and directives ("you need to know"), 2) Use templates, key words, symbols, and colors, 3) Write complete sentences for complex concepts, 4) Review notes within 24 hours, 5) Transfer key information to flashcards or mind maps for long-term memory.',
    category: 'Procedure/Process Knowledge',
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-2-037',
    chapter_id: 'ch-2',
    front: 'What is the proper procedure for handling a client complaint from start to finish?',
    back: '1) Listen without defending, 2) Acknowledge their feelings ("I understand why you are disappointed"), 3) Apologize sincerely, 4) Offer a specific solution (fix, refund, or reschedule), 5) Follow up to ensure satisfaction. Never blame the client or make excuses.',
    category: 'Procedure/Process Knowledge',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-2-038',
    chapter_id: 'ch-2',
    front: 'What is the recommended procedure for creating an effective study schedule as a barber student?',
    back: '1) Identify your most alert hours, 2) Block 25-50 minute focused study sessions (Pomodoro), 3) Schedule review sessions spaced over days (spaced repetition), 4) Include practice time on mannequins or models, 5) Plan rest days to prevent burnout, 6) Adjust weekly based on progress.',
    category: 'Procedure/Process Knowledge',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-2-039',
    chapter_id: 'ch-2',
    front: 'Describe the proper networking process for barbers who want to build professional relationships.',
    back: '1) Give first — share knowledge, make introductions, offer help, 2) Attend industry events, hair shows, and local business meetups, 3) Follow up within 48 hours of meeting someone, 4) Maintain relationships through periodic check-ins, 5) Build genuine connections before asking for anything.',
    category: 'Procedure/Process Knowledge',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-2-040',
    chapter_id: 'ch-2',
    front: 'What is the proper procedure for managing time in a busy barbershop with both appointments and walk-ins?',
    back: '1) Arrive early to prep your station, 2) Build buffer time between appointments (5-10 minutes), 3) Communicate wait times honestly to walk-ins, 4) Handle add-ons efficiently or schedule them separately, 5) Coordinate with the team during high-volume periods, 6) End on time whenever possible to respect the next client.',
    category: 'Procedure/Process Knowledge',
    difficulty: 'hard',
    order_index: 40,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // CATEGORY 7: SAFETY CONCEPTS (3 cards)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'fc-2-041',
    chapter_id: 'ch-2',
    front: 'Why is maintaining a healthy work-life balance considered a safety concept for barbers?',
    back: 'Poor work-life balance leads to burnout, fatigue, and stress — all of which increase the risk of mistakes (cuts, chemical burns, sanitation errors). A rested barber is a safe barber. Set boundaries, take days off, and prioritize sleep.',
    category: 'Safety Concepts',
    difficulty: 'medium',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-2-042',
    chapter_id: 'ch-2',
    front: 'How does financial stress impact barber safety and service quality?',
    back: 'Financial stress causes distraction, rushed services, and corner-cutting. A barber worried about rent may rush sanitation, skip tool maintenance, or overbook clients — all of which create safety hazards. Building an emergency fund is a safety investment.',
    category: 'Safety Concepts',
    difficulty: 'medium',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-2-043',
    chapter_id: 'ch-2',
    front: 'What safety risk arises when a barber fails to practice emotional stability during a confrontational situation?',
    back: 'Emotional reactivity can lead to aggressive responses, escalating conflicts, and potentially violent situations. It may also result in impulsive decisions like refusing service improperly or violating shop policies. Emotional stability protects both physical and professional safety.',
    category: 'Safety Concepts',
    difficulty: 'hard',
    order_index: 43,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // CATEGORY 8: MEMORY REINFORCEMENT (7 cards)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'fc-2-044',
    chapter_id: 'ch-2',
    front: 'MEMORY DRILL: List the four memory and study techniques recommended for barber students.',
    back: '1) REPETITION — verbal, written, and hands-on practice; 2) ORGANIZATION — break topics into smaller segments; 3) MNEMONICS — acronyms (SHAPES for skin functions), word associations, songs/rhymes; 4) MIND MAPPING — visual branching from central topics.',
    category: 'Memory Reinforcement',
    difficulty: 'easy',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-2-045',
    chapter_id: 'ch-2',
    front: 'MEMORY DRILL: What are the eight characteristics of a healthy, positive attitude that barbers should develop?',
    back: '1) Diplomacy (tact), 2) Pleasing tone of voice, 3) Emotional stability, 4) Sensitivity, 5) Values and goals, 6) Receptivity, 7) Effective communication skills, 8) Sense of humor.',
    category: 'Memory Reinforcement',
    difficulty: 'hard',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-2-046',
    chapter_id: 'ch-2',
    front: 'MEMORY DRILL: What are the five action steps for building self-esteem and achieving success?',
    back: '1) Build self-esteem (trust your abilities, use positive affirmations), 2) Visualize success (imagine working in your dream shop), 3) Build on your strengths, 4) Be kind to yourself (eliminate negative self-talk), 5) Stay true to yourself (be authentic and professional).',
    category: 'Memory Reinforcement',
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-2-047',
    chapter_id: 'ch-2',
    front: 'MEMORY DRILL: List four key time management strategies specifically for barbers.',
    back: '1) Prioritize tasks by importance, 2) Create flexible daily/weekly schedules, 3) Learn to say "no" kindly to avoid overcommitment, 4) Use lists or digital planning tools. Bonus: Schedule physical activity and free time daily.',
    category: 'Memory Reinforcement',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-2-048',
    chapter_id: 'ch-2',
    front: 'MEMORY DRILL: What are the five professional ethics actions every barber must practice?',
    back: '1) Provide skilled and competent services, 2) Be honest, courteous, and sincere, 3) Keep client information confidential, 4) Participate in continuing education, 5) Give accurate information about treatments and products.',
    category: 'Memory Reinforcement',
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-2-049',
    chapter_id: 'ch-2',
    front: 'MEMORY DRILL: What are the three components of effective communication that barbers must master?',
    back: '1) VERBAL communication — clear, professional language; 2) NONVERBAL communication — body language, posture, eye contact; 3) ACTIVE LISTENING — fully concentrating on the speaker, processing the message, and responding appropriately.',
    category: 'Memory Reinforcement',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-2-050',
    chapter_id: 'ch-2',
    front: 'MEMORY DRILL: What are the four tips for enhancing creativity in barbering?',
    back: '1) Be positive (criticism blocks ideas), 2) Look for creative inspiration (art, music, hair shows, magazines), 3) Improve your vocabulary (use words like explore, analyze, determine), 4) Surround yourself with passionate people (teamwork sparks better ideas).',
    category: 'Memory Reinforcement',
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },
]
