// Chapter 6: General Anatomy and Physiology — PREMIUM QUIZ
// C6-3: 50 difficult exam-style questions mapped to canonical Chapter 6 concepts
// Every explanation reinforces the locked five-step test-taking strategy.

import { QuizQuestion } from '@/types'

function strategyExplanation(keyword: string, eliminate: string, safetyProcedure: string, bestChoice: string): string {
  return [
    'Read carefully.',
    `Identify the keyword: ${keyword}.`,
    `Eliminate wrong answers: ${eliminate}.`,
    `Apply safety/procedure logic: ${safetyProcedure}.`,
    `Then make the best remaining choice: ${bestChoice}.`,
  ].join(' ')
}

export const chapter6PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-6-001',
    quiz_id: 'quiz-6',
    question: "A superficial abrasion begins repairing. Which process BEST produces new somatic cells for tissue renewal?",
    answer_a: "Mitosis",
    answer_b: "Metabolism",
    answer_c: "Diffusion",
    answer_d: "Keratinization",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST", "metabolism, diffusion, and keratinization do not directly divide one somatic cell into two", "choose the process responsible for ordinary growth and repair", "mitosis"),
    difficulty: 'hard',
    order_index: 1,
  },
  {
    id: 'qq-6-002',
    quiz_id: 'quiz-6',
    question: "A student says the nucleus and cell membrane have the same job because both 'control the cell.' Which correction is MOST accurate?",
    answer_a: "The membrane stores DNA while the nucleus controls entry and exit",
    answer_b: "The nucleus directs reproduction and contains DNA, while the membrane regulates what enters and exits",
    answer_c: "The nucleus produces ATP while the membrane produces proteins",
    answer_d: "The membrane performs mitosis while the nucleus forms connective tissue",
    correct_answer: 'b',
    explanation: strategyExplanation("MOST accurate", "reject answers that swap organelle functions or invent functions", "match each structure to its established role", "nucleus = genetic/control center; membrane = selective boundary"),
    difficulty: 'hard',
    order_index: 2,
  },
  {
    id: 'qq-6-003',
    quiz_id: 'quiz-6',
    question: "Which pairing BEST distinguishes cytoplasm from protoplasm in the chapter’s terminology?",
    answer_a: "Cytoplasm is the fluid around the nucleus; protoplasm refers broadly to the living material of the cell",
    answer_b: "Cytoplasm is DNA; protoplasm is the cell membrane",
    answer_c: "Cytoplasm is connective tissue; protoplasm is epithelial tissue",
    answer_d: "Cytoplasm is an organ; protoplasm is a gland",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST distinguishes", "remove category errors and swapped definitions", "use the definitions taught in the lesson", "cytoplasm is the intracellular fluid region while protoplasm is the broader living cell substance"),
    difficulty: 'hard',
    order_index: 3,
  },
  {
    id: 'qq-6-004',
    quiz_id: 'quiz-6',
    question: "A tissue sample contracts to create movement. Which tissue family should be identified FIRST?",
    answer_a: "Epithelial",
    answer_b: "Connective",
    answer_c: "Muscular",
    answer_d: "Nervous",
    correct_answer: 'c',
    explanation: strategyExplanation("FIRST", "covering, support, and signaling do not primarily describe contraction", "identify the function before naming the tissue", "muscular tissue contracts"),
    difficulty: 'hard',
    order_index: 4,
  },
  {
    id: 'qq-6-005',
    quiz_id: 'quiz-6',
    question: "A barber wants to remember why blood is classified differently from skin. Which statement is BEST?",
    answer_a: "Blood is connective tissue; skin surface is primarily epithelial tissue",
    answer_b: "Blood is epithelial tissue; skin is nervous tissue",
    answer_c: "Blood is muscular tissue; skin is connective tissue only",
    answer_d: "Blood and skin are both organs, not tissues",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST", "eliminate answers that misclassify major tissue families", "classify by tissue type, not by where it is encountered", "blood is connective tissue and epidermal covering is epithelial"),
    difficulty: 'hard',
    order_index: 5,
  },
  {
    id: 'qq-6-006',
    quiz_id: 'quiz-6',
    question: "Which scenario BEST demonstrates homeostasis rather than metabolism?",
    answer_a: "The body maintaining a stable internal temperature despite room-temperature changes",
    answer_b: "Cells breaking nutrients down to release energy",
    answer_c: "A follicle producing new cells by mitosis",
    answer_d: "A gland secreting sebum onto the skin",
    correct_answer: 'a',
    explanation: strategyExplanation("homeostasis", "metabolism is chemical reaction activity; mitosis is division; secretion is gland function", "choose the example of internal stability", "temperature regulation is homeostasis"),
    difficulty: 'hard',
    order_index: 6,
  },
  {
    id: 'qq-6-007',
    quiz_id: 'quiz-6',
    question: "A question asks for the body system a barber works on MOST directly during haircutting, shaving, and skin contact. Which is the BEST answer?",
    answer_a: "Integumentary",
    answer_b: "Skeletal",
    answer_c: "Endocrine",
    answer_d: "Urinary",
    correct_answer: 'a',
    explanation: strategyExplanation("MOST directly", "other systems support the body but are not the primary service surface", "focus on the structures physically contacted in routine barbering", "integumentary system"),
    difficulty: 'hard',
    order_index: 7,
  },
  {
    id: 'qq-6-008',
    quiz_id: 'quiz-6',
    question: "Which statement BEST separates anatomy from physiology?",
    answer_a: "Anatomy studies structure; physiology studies function",
    answer_b: "Anatomy studies disease; physiology studies sanitation",
    answer_c: "Anatomy studies chemicals; physiology studies bones only",
    answer_d: "They are interchangeable terms",
    correct_answer: 'a',
    explanation: strategyExplanation("separates", "discard answers that narrow either field incorrectly", "match structure versus function", "anatomy = structure, physiology = function"),
    difficulty: 'hard',
    order_index: 8,
  },
  {
    id: 'qq-6-009',
    quiz_id: 'quiz-6',
    question: "A barber notices that several body systems interact during a service. Which conclusion is MOST accurate?",
    answer_a: "Body systems function independently and should be memorized separately",
    answer_b: "Body systems are integrated, so one service can involve skin, nerves, muscles, and circulation at the same time",
    answer_c: "Only the integumentary system matters in barbering",
    answer_d: "The endocrine system directly controls every other system",
    correct_answer: 'b',
    explanation: strategyExplanation("MOST accurate", "reject isolation and universal-control claims", "choose the integrated-systems explanation", "multiple systems interact during real services"),
    difficulty: 'hard',
    order_index: 9,
  },
  {
    id: 'qq-6-010',
    quiz_id: 'quiz-6',
    question: "Which statement BEST explains why physiology matters to safe barbering?",
    answer_a: "It explains how structures function and respond during services",
    answer_b: "It allows barbers to diagnose disease",
    answer_c: "It replaces sanitation rules",
    answer_d: "It permits medical treatment of skin conditions",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST explains", "scope-of-practice violations eliminate diagnosis and treatment claims", "use physiology to understand normal function without crossing scope", "physiology supports safer service decisions"),
    difficulty: 'hard',
    order_index: 10,
  },
  {
    id: 'qq-6-011',
    quiz_id: 'quiz-6',
    question: "A difficult anatomy item asks for the correct wrist-to-finger sequence. Which answer should remain after eliminating the mismatched bone groups?",
    answer_a: "Carpals → metacarpals → phalanges",
    answer_b: "Metacarpals → carpals → humerus",
    answer_c: "Phalanges → radius → metacarpals",
    answer_d: "Ulna → carpals → humerus",
    correct_answer: 'a',
    explanation: strategyExplanation("wrist-to-finger sequence", "humerus, radius, and ulna are arm/forearm bones rather than the wrist-palm-finger sequence", "move anatomically from wrist to palm to digits", "carpals → metacarpals → phalanges"),
    difficulty: 'hard',
    order_index: 11,
  },
  {
    id: 'qq-6-012',
    quiz_id: 'quiz-6',
    question: "A barber uses the cheekbone as a visual landmark for beard design. Which bone is being referenced?",
    answer_a: "Zygomatic",
    answer_b: "Occipital",
    answer_c: "Parietal",
    answer_d: "Nasal",
    correct_answer: 'a',
    explanation: strategyExplanation("cheekbone", "the other options correspond to back of skull, roof/sides, or nose", "match the landmark to the facial bone", "zygomatic bone"),
    difficulty: 'hard',
    order_index: 12,
  },
  {
    id: 'qq-6-013',
    quiz_id: 'quiz-6',
    question: "During neckline design, which skull region is MOST relevant as a posterior head landmark?",
    answer_a: "Occipital",
    answer_b: "Frontal",
    answer_c: "Maxillary",
    answer_d: "Zygomatic",
    correct_answer: 'a',
    explanation: strategyExplanation("posterior", "remove anterior facial bones", "use the back-of-skull location", "occipital bone"),
    difficulty: 'hard',
    order_index: 13,
  },
  {
    id: 'qq-6-014',
    quiz_id: 'quiz-6',
    question: "Which statement about the adult spinal column is MOST accurate for this chapter?",
    answer_a: "It is described as 26 bones because the sacrum and coccyx are fused in adults",
    answer_b: "It contains only 24 bones total",
    answer_c: "It contains 33 separate bones in every adult",
    answer_d: "It excludes the cervical region",
    correct_answer: 'a',
    explanation: strategyExplanation("adult", "distinguish developmental vertebral segments from adult fused bones", "use the adult-anatomy convention in the lesson", "26 bones including fused sacrum and coccyx"),
    difficulty: 'hard',
    order_index: 14,
  },
  {
    id: 'qq-6-015',
    quiz_id: 'quiz-6',
    question: "A barber adjusts a client’s head position during shampooing. Which region should receive the MOST direct neck-support awareness?",
    answer_a: "Cervical spine",
    answer_b: "Lumbar spine",
    answer_c: "Sacrum",
    answer_d: "Coccyx",
    correct_answer: 'a',
    explanation: strategyExplanation("neck-support", "lower-spine structures are not located in the neck", "match the service position to the anatomical region", "cervical spine"),
    difficulty: 'hard',
    order_index: 15,
  },
  {
    id: 'qq-6-016',
    quiz_id: 'quiz-6',
    question: "A client clenches the jaw during beard shaping and the jaw angle becomes more prominent. Which muscle is MOST responsible?",
    answer_a: "Masseter",
    answer_b: "Frontalis",
    answer_c: "Orbicularis oculi",
    answer_d: "Platysma",
    correct_answer: 'a',
    explanation: strategyExplanation("jaw angle", "eyebrow, eyelid, and broad-neck muscles do not primarily close the jaw", "choose the major jaw-closing muscle", "masseter"),
    difficulty: 'hard',
    order_index: 16,
  },
  {
    id: 'qq-6-017',
    quiz_id: 'quiz-6',
    question: "Which muscle should a barber associate MOST directly with rotating and flexing the head?",
    answer_a: "Sternocleidomastoid",
    answer_b: "Orbicularis oris",
    answer_c: "Buccinator",
    answer_d: "Frontalis",
    correct_answer: 'a',
    explanation: strategyExplanation("rotating and flexing", "mouth, cheek, and forehead muscles do not perform primary neck rotation", "match movement to the neck muscle", "sternocleidomastoid"),
    difficulty: 'hard',
    order_index: 17,
  },
  {
    id: 'qq-6-018',
    quiz_id: 'quiz-6',
    question: "A student must distinguish forearm rotation from elbow flexion. Which pairing is MOST accurate?",
    answer_a: "Pronator turns the palm inward/downward; supinator turns it upward/outward",
    answer_b: "Pronator extends the elbow; supinator flexes the shoulder",
    answer_c: "Biceps pronates the forearm; triceps supinates it",
    answer_d: "Deltoid pronates the palm; masseter supinates it",
    correct_answer: 'a',
    explanation: strategyExplanation("forearm rotation", "elbow/shoulder actions and facial muscles do not define pronation and supination", "match the movement words to palm direction", "pronator inward/downward; supinator upward/outward"),
    difficulty: 'hard',
    order_index: 18,
  },
  {
    id: 'qq-6-019',
    quiz_id: 'quiz-6',
    question: "Which pairing is CORRECT?",
    answer_a: "Orbicularis oculi—closes the eyelid",
    answer_b: "Orbicularis oris—raises the eyebrow",
    answer_c: "Buccinator—rotates the head",
    answer_d: "Platysma—closes the jaw as the main chewing muscle",
    correct_answer: 'a',
    explanation: strategyExplanation("CORRECT", "the distractors mismatch function and muscle", "match anatomy to action", "orbicularis oculi closes the eyelid"),
    difficulty: 'hard',
    order_index: 19,
  },
  {
    id: 'qq-6-020',
    quiz_id: 'quiz-6',
    question: "A question contrasts skeletal, smooth, and cardiac muscle. Which feature BEST identifies cardiac muscle?",
    answer_a: "Involuntary striated muscle of the heart",
    answer_b: "Voluntary muscle attached to bone",
    answer_c: "Involuntary muscle of vessel walls",
    answer_d: "Voluntary muscle around hair follicles",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST identifies", "the other descriptions belong to skeletal or smooth muscle", "use location plus control pattern", "cardiac muscle is involuntary, striated, and heart-specific"),
    difficulty: 'hard',
    order_index: 20,
  },
  {
    id: 'qq-6-021',
    quiz_id: 'quiz-6',
    question: "A client can feel touch on the face but cannot voluntarily move one side of the mouth normally. Which distinction is MOST useful to remember?",
    answer_a: "Cranial nerve V is strongly associated with facial sensation and chewing; VII with facial expression",
    answer_b: "Cranial nerve VII carries all facial sensation and V controls hearing",
    answer_c: "Both nerves have identical functions",
    answer_d: "Neither nerve is relevant to facial movement",
    correct_answer: 'a',
    explanation: strategyExplanation("distinction", "eliminate reversed or identical-function claims", "do not diagnose; only match taught nerve functions", "V = sensation/chewing, VII = facial expression"),
    difficulty: 'hard',
    order_index: 21,
  },
  {
    id: 'qq-6-022',
    quiz_id: 'quiz-6',
    question: "Which pathway BEST describes a sensory nerve message from the skin?",
    answer_a: "Toward the CNS for processing",
    answer_b: "Away from the CNS to a muscle only",
    answer_c: "Directly to an endocrine gland",
    answer_d: "From the heart to the skin",
    correct_answer: 'a',
    explanation: strategyExplanation("sensory", "motor pathways carry commands outward", "direction matters", "sensory information travels toward the CNS"),
    difficulty: 'hard',
    order_index: 22,
  },
  {
    id: 'qq-6-023',
    quiz_id: 'quiz-6',
    question: "A client becomes dizzy during forceful neck work. What is the BEST immediate barber response?",
    answer_a: "Stop the service, keep the client safely positioned, assess responsiveness/symptoms, and follow first-aid or emergency procedures as needed",
    answer_b: "Increase pressure to finish the massage",
    answer_c: "Diagnose vagus-nerve stimulation",
    answer_d: "Continue if the client says they can tolerate it",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST immediate", "continuing, increasing pressure, or diagnosing violates safety/scope", "stop the provoking service and protect the client first", "stop, position safely, assess, and escalate appropriately"),
    difficulty: 'hard',
    order_index: 23,
  },
  {
    id: 'qq-6-024',
    quiz_id: 'quiz-6',
    question: "A board-style question asks which nerve supplies much of the posterior scalp and extends toward the top of the head. Which choice is BEST?",
    answer_a: "Greater occipital nerve",
    answer_b: "Buccal branch of the facial nerve",
    answer_c: "Mandibular branch of the trigeminal nerve",
    answer_d: "Cervical cutaneous nerve",
    correct_answer: 'a',
    explanation: strategyExplanation("posterior scalp", "mouth/jaw/front-side neck landmarks do not match the posterior scalp description", "match the sensory landmark to the cervical nerve", "greater occipital nerve"),
    difficulty: 'hard',
    order_index: 24,
  },
  {
    id: 'qq-6-025',
    quiz_id: 'quiz-6',
    question: "A question asks which cranial nerve has ophthalmic, maxillary, and mandibular branches. Which is the BEST answer?",
    answer_a: "Trigeminal nerve (V)",
    answer_b: "Facial nerve (VII)",
    answer_c: "Vagus nerve (X)",
    answer_d: "Optic nerve (II)",
    correct_answer: 'a',
    explanation: strategyExplanation("three branches", "eliminate nerves not organized into those three named divisions", "match the branch names", "trigeminal nerve"),
    difficulty: 'hard',
    order_index: 25,
  },
  {
    id: 'qq-6-026',
    quiz_id: 'quiz-6',
    question: "Which rule is MOST reliable when distinguishing arteries from veins on an exam?",
    answer_a: "Arteries carry blood away from the heart; veins return blood toward the heart",
    answer_b: "Arteries always carry oxygenated blood; veins always carry deoxygenated blood",
    answer_c: "Arteries are only in the head; veins are only in the neck",
    answer_d: "Veins pump blood; arteries filter it",
    correct_answer: 'a',
    explanation: strategyExplanation("MOST reliable", "oxygen content has pulmonary exceptions and the other claims are false", "use direction relative to the heart", "away = arteries, return = veins"),
    difficulty: 'hard',
    order_index: 26,
  },
  {
    id: 'qq-6-027',
    quiz_id: 'quiz-6',
    question: "During neck work, which safety principle should control technique around the carotid area?",
    answer_a: "Avoid sustained or forceful pressure",
    answer_b: "Use deep pressure to improve circulation",
    answer_c: "Compress both sides to assess pulse strength",
    answer_d: "Massage until dizziness resolves",
    correct_answer: 'a',
    explanation: strategyExplanation("safety principle", "the distractors increase risk", "avoid unnecessary vessel compression", "use gentle technique and avoid sustained/forceful carotid pressure"),
    difficulty: 'hard',
    order_index: 27,
  },
  {
    id: 'qq-6-028',
    quiz_id: 'quiz-6',
    question: "A question asks which artery supplies the chin and lower-lip region. Which answer is MOST accurate?",
    answer_a: "Submental artery",
    answer_b: "Supraorbital artery",
    answer_c: "Parietal artery",
    answer_d: "Posterior auricular artery",
    correct_answer: 'a',
    explanation: strategyExplanation("chin and lower lip", "forehead, crown, and behind-ear vessels do not match the target region", "match the named artery to its facial territory", "submental artery"),
    difficulty: 'hard',
    order_index: 28,
  },
  {
    id: 'qq-6-029',
    quiz_id: 'quiz-6',
    question: "What is the heart’s PRIMARY role in the cardiovascular system?",
    answer_a: "Pump blood through the circulation",
    answer_b: "Filter lymph",
    answer_c: "Produce sebum",
    answer_d: "Control facial expression",
    correct_answer: 'a',
    explanation: strategyExplanation("PRIMARY", "the other options belong to different systems or structures", "identify the core cardiovascular function", "pump blood"),
    difficulty: 'hard',
    order_index: 29,
  },
  {
    id: 'qq-6-030',
    quiz_id: 'quiz-6',
    question: "Which statement BEST explains why circulation matters to living scalp tissues?",
    answer_a: "Blood flow delivers oxygen and nutrients to living tissues and carries wastes away",
    answer_b: "Hair shafts receive oxygen directly from the lungs",
    answer_c: "The epidermis contains its own blood vessels",
    answer_d: "Sebum transports oxygen to follicles",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST explains", "lungs do not deliver oxygen directly to hair shafts, epidermis is avascular, and sebum is not a blood substitute", "use circulation rather than cosmetic-product logic", "blood supports living tissues"),
    difficulty: 'hard',
    order_index: 30,
  },
  {
    id: 'qq-6-031',
    quiz_id: 'quiz-6',
    question: "A client has a persistent swollen area behind the ear that may involve a lymph node. What is the BEST barber action?",
    answer_a: "Avoid manipulating it, do not diagnose, and recommend appropriate medical evaluation",
    answer_b: "Massage it firmly to drain it",
    answer_c: "Tell the client it is an infection",
    answer_d: "Apply heat until it shrinks",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST barber action", "massage, diagnosis, and treatment exceed safe scope", "observe, avoid manipulation, and refer when persistent/concerning", "professional referral without diagnosis"),
    difficulty: 'hard',
    order_index: 31,
  },
  {
    id: 'qq-6-032',
    quiz_id: 'quiz-6',
    question: "Which statement about lymph nodes is MOST accurate?",
    answer_a: "They filter lymph and support immune activity; swelling can have multiple causes",
    answer_b: "They pump blood to the scalp",
    answer_c: "They produce sebum",
    answer_d: "Any swelling proves infection",
    correct_answer: 'a',
    explanation: strategyExplanation("MOST accurate", "blood pumping and sebum are unrelated, and swelling is not single-cause proof", "avoid diagnostic absolutes", "filtering and immune support are correct"),
    difficulty: 'hard',
    order_index: 32,
  },
  {
    id: 'qq-6-033',
    quiz_id: 'quiz-6',
    question: "Which organ is correctly identified as the largest lymphatic organ?",
    answer_a: "Spleen",
    answer_b: "Thyroid",
    answer_c: "Pituitary",
    answer_d: "Pancreas",
    correct_answer: 'a',
    explanation: strategyExplanation("largest lymphatic organ", "the other organs are endocrine or digestive/endocrine", "match organ to system", "spleen"),
    difficulty: 'hard',
    order_index: 33,
  },
  {
    id: 'qq-6-034',
    quiz_id: 'quiz-6',
    question: "A barber notices tenderness near a suspected lymph node during a service. Which principle should guide the next step?",
    answer_a: "Do not manipulate the abnormal area and stay within barber scope",
    answer_b: "Use deeper pressure to test whether it is movable",
    answer_c: "Attempt drainage",
    answer_d: "Explain the exact disease causing it",
    correct_answer: 'a',
    explanation: strategyExplanation("principle", "testing, drainage, and diagnosis exceed scope", "safety and scope override service completion", "avoid manipulation and refer appropriately"),
    difficulty: 'hard',
    order_index: 34,
  },
  {
    id: 'qq-6-035',
    quiz_id: 'quiz-6',
    question: "Which skin layer contains hair follicles, glands, blood vessels, and nerve endings?",
    answer_a: "Dermis",
    answer_b: "Epidermis",
    answer_c: "Stratum corneum only",
    answer_d: "Hair shaft",
    correct_answer: 'a',
    explanation: strategyExplanation("contains", "the epidermis is avascular and hair shaft is not a skin layer", "match structures to layer", "dermis"),
    difficulty: 'hard',
    order_index: 35,
  },
  {
    id: 'qq-6-036',
    quiz_id: 'quiz-6',
    question: "Which statement about the epidermis is MOST accurate?",
    answer_a: "It is avascular and receives nourishment by diffusion from deeper vascular tissues",
    answer_b: "It contains large blood vessels",
    answer_c: "It contains all hair follicles",
    answer_d: "It is the same as subcutaneous tissue",
    correct_answer: 'a',
    explanation: strategyExplanation("MOST accurate", "blood vessels and follicles are deeper; subcutaneous tissue is below skin", "remember epidermis = no blood vessels", "avascular epidermis"),
    difficulty: 'hard',
    order_index: 36,
  },
  {
    id: 'qq-6-037',
    quiz_id: 'quiz-6',
    question: "A barber sees an oily scalp. Which statement is the BEST anatomy-based explanation without overstepping scope?",
    answer_a: "Sebaceous glands produce sebum that lubricates skin and hair, but oiliness can vary for many reasons",
    answer_b: "Oiliness proves a hormonal disorder",
    answer_c: "Sweat glands produce sebum",
    answer_d: "The epidermis pumps oil into follicles",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST", "diagnosis is too strong and the other anatomy is wrong", "give general anatomy without assigning a disease cause", "sebaceous glands produce sebum"),
    difficulty: 'hard',
    order_index: 37,
  },
  {
    id: 'qq-6-038',
    quiz_id: 'quiz-6',
    question: "Which gland-function pairing is CORRECT?",
    answer_a: "Sudoriferous glands—perspiration",
    answer_b: "Sebaceous glands—lymph filtration",
    answer_c: "Ceruminous glands—blood production",
    answer_d: "Pituitary gland—sebum secretion",
    correct_answer: 'a',
    explanation: strategyExplanation("CORRECT", "the distractors cross unrelated systems", "match each gland to its known secretion/function", "sudoriferous glands produce perspiration"),
    difficulty: 'hard',
    order_index: 38,
  },
  {
    id: 'qq-6-039',
    quiz_id: 'quiz-6',
    question: "Which statement BEST describes epidermal renewal?",
    answer_a: "New cells form in deeper epidermal layers and move toward the surface over a period that varies by age, site, and individual factors",
    answer_b: "The entire epidermis always replaces itself in exactly 27 days",
    answer_c: "Only the dermis renews",
    answer_d: "Renewal occurs by blood vessels entering the epidermis",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST describes", "fixed-day absolutes and vascular-epidermis claims are incorrect", "prefer qualified biological timing", "renewal occurs over several weeks with variation"),
    difficulty: 'hard',
    order_index: 39,
  },
  {
    id: 'qq-6-040',
    quiz_id: 'quiz-6',
    question: "A question asks why the integumentary system is especially relevant to barbering. Which answer is BEST?",
    answer_a: "It includes skin, hair, nails, and glands—the structures barbers work with most directly",
    answer_b: "It controls every other body system",
    answer_c: "It replaces sanitation procedures",
    answer_d: "It allows medical diagnosis of skin disease",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST", "universal control, sanitation replacement, and diagnosis are wrong", "choose the direct professional relevance", "it is the primary service interface"),
    difficulty: 'hard',
    order_index: 40,
  },
  {
    id: 'qq-6-041',
    quiz_id: 'quiz-6',
    question: "Which statement about the pituitary gland is MOST accurate?",
    answer_a: "It is often called the master gland because its hormones regulate several other endocrine glands, but it does not control every endocrine gland",
    answer_b: "It directly controls every endocrine gland",
    answer_c: "It is a sweat gland",
    answer_d: "It is located in the skin",
    correct_answer: 'a',
    explanation: strategyExplanation("MOST accurate", "reject the absolute and category errors", "use qualified endocrine relationships", "regulates several, not all, endocrine glands"),
    difficulty: 'hard',
    order_index: 41,
  },
  {
    id: 'qq-6-042',
    quiz_id: 'quiz-6',
    question: "A client asks whether hair thinning proves a thyroid disorder. What is the BEST response within barber scope?",
    answer_a: "Hair changes can have many causes; avoid diagnosing and suggest appropriate medical evaluation if the change is persistent or concerning",
    answer_b: "Yes, thinning proves thyroid disease",
    answer_c: "No, thyroid hormones never affect hair",
    answer_d: "Recommend a specific thyroid medication",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST response", "proof, denial, and prescribing are inappropriate", "maintain observation/referral boundaries", "acknowledge multiple causes and refer when appropriate"),
    difficulty: 'hard',
    order_index: 42,
  },
  {
    id: 'qq-6-043',
    quiz_id: 'quiz-6',
    question: "Which statement about androgens is MOST accurate?",
    answer_a: "They can influence facial-hair development and sebaceous activity, with individual variation",
    answer_b: "They guarantee the same beard growth in everyone",
    answer_c: "They are produced only by the pituitary gland",
    answer_d: "They have no relationship to hair or skin",
    correct_answer: 'a',
    explanation: strategyExplanation("MOST accurate", "guarantees and exclusions are false", "use influence rather than certainty", "androgens influence hair and oil production variably"),
    difficulty: 'hard',
    order_index: 43,
  },
  {
    id: 'qq-6-044',
    quiz_id: 'quiz-6',
    question: "A teenager asks why skin seems oilier during puberty. Which answer is BEST?",
    answer_a: "Hormonal changes, including androgen activity, can increase sebaceous-gland activity, but oiliness varies and should not be self-diagnosed as a disorder",
    answer_b: "Poor hygiene is always the cause",
    answer_c: "Oiliness proves diabetes",
    answer_d: "The lymphatic system produces facial oil",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST", "avoid blame, diagnosis, and incorrect system functions", "provide general education within scope", "pubertal hormone changes can influence sebaceous activity"),
    difficulty: 'hard',
    order_index: 44,
  },
  {
    id: 'qq-6-045',
    quiz_id: 'quiz-6',
    question: "Which distinction between endocrine and exocrine glands is MOST accurate?",
    answer_a: "Endocrine glands are ductless and release hormones into blood; exocrine glands use ducts to deliver products",
    answer_b: "Endocrine glands use ducts while exocrine glands release only hormones into blood",
    answer_c: "Both gland types are identical except for their location",
    answer_d: "Sweat and sebaceous glands are endocrine because they affect skin",
    correct_answer: 'a',
    explanation: strategyExplanation("endocrine and exocrine", "the distractors reverse or erase the defining duct relationship", "identify whether the secretion enters blood directly or travels through a duct", "endocrine = ductless hormone release; exocrine = ducted product"),
    difficulty: 'hard',
    order_index: 45,
  },
  {
    id: 'qq-6-046',
    quiz_id: 'quiz-6',
    question: "Which statement BEST describes the respiratory system’s role in oxygen supply?",
    answer_a: "It brings oxygen into the body; the cardiovascular system then transports oxygen to tissues",
    answer_b: "It directly pumps oxygen through arteries",
    answer_c: "It delivers oxygen only to hair follicles",
    answer_d: "It replaces cardiovascular circulation",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST describes", "transport through tissues is cardiovascular, not direct respiratory pumping", "separate gas exchange from transport", "respiration loads oxygen; circulation delivers it"),
    difficulty: 'hard',
    order_index: 46,
  },
  {
    id: 'qq-6-047',
    quiz_id: 'quiz-6',
    question: "Which statement BEST describes the digestive system?",
    answer_a: "It breaks food down so nutrients can be absorbed and used by the body",
    answer_b: "It filters lymph",
    answer_c: "It pumps blood",
    answer_d: "It produces all hormones",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST describes", "the other functions belong to other systems", "identify the core system function", "digestion and nutrient absorption"),
    difficulty: 'hard',
    order_index: 47,
  },
  {
    id: 'qq-6-048',
    quiz_id: 'quiz-6',
    question: "A barber notices dry skin and wonders if it proves a kidney problem. Which conclusion is BEST?",
    answer_a: "Dry skin is nonspecific; barbers should not infer kidney function or diagnose disease from that sign alone",
    answer_b: "Dry skin proves kidney disease",
    answer_c: "Kidneys directly produce skin oil",
    answer_d: "The urinary system is unrelated to fluid balance",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST", "proof claims and incorrect physiology should be eliminated", "apply scope and nonspecific-sign logic", "do not diagnose from a single visible sign"),
    difficulty: 'hard',
    order_index: 48,
  },
  {
    id: 'qq-6-049',
    quiz_id: 'quiz-6',
    question: "Which statement BEST characterizes the urinary system?",
    answer_a: "It helps remove wastes and regulate fluid/electrolyte balance",
    answer_b: "It controls facial expression",
    answer_c: "It produces sebum",
    answer_d: "It performs gas exchange",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST", "the distractors belong to nervous/muscular, integumentary, or respiratory functions", "match the system to its core physiology", "waste removal and fluid balance"),
    difficulty: 'hard',
    order_index: 49,
  },
  {
    id: 'qq-6-050',
    quiz_id: 'quiz-6',
    question: "Which statement BEST explains why reproductive-system changes are included in this chapter?",
    answer_a: "Life-stage hormonal changes can influence hair-growth patterns, texture, and skin condition, with individual variation",
    answer_b: "They allow barbers to diagnose pregnancy from hair changes",
    answer_c: "They guarantee identical hair changes in everyone",
    answer_d: "They replace endocrine-system function",
    correct_answer: 'a',
    explanation: strategyExplanation("BEST explains", "diagnosis, guarantees, and system replacement are incorrect", "use association and variation, not certainty", "life-stage hormones can influence hair and skin"),
    difficulty: 'hard',
    order_index: 50,
  },
]

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

export function randomizeQuestionAnswers(question: QuizQuestion): QuizQuestion {
  const answers = [
    { key: 'a', text: question.answer_a },
    { key: 'b', text: question.answer_b },
    { key: 'c', text: question.answer_c },
    { key: 'd', text: question.answer_d },
  ]
  const shuffled = shuffleArray(answers)
  const correct = shuffled.find((a) => a.key === question.correct_answer)!
  const correctLetter = ['a', 'b', 'c', 'd'][shuffled.indexOf(correct)] as 'a' | 'b' | 'c' | 'd'
  return { ...question, answer_a: shuffled[0].text, answer_b: shuffled[1].text, answer_c: shuffled[2].text, answer_d: shuffled[3].text, correct_answer: correctLetter }
}

export function generateChapter6Exam(questionCount: number = 50): QuizQuestion[] {
  return shuffleArray(chapter6PremiumQuizQuestions).slice(0, Math.min(questionCount, chapter6PremiumQuizQuestions.length)).map(randomizeQuestionAnswers)
}

export function getChapter6QuestionBank(): QuizQuestion[] { return chapter6PremiumQuizQuestions }

export const chapter6QuizStats = {
  totalQuestions: chapter6PremiumQuizQuestions.length,
  easy: chapter6PremiumQuizQuestions.filter((q) => q.difficulty === 'easy').length,
  medium: chapter6PremiumQuizQuestions.filter((q) => q.difficulty === 'medium').length,
  hard: chapter6PremiumQuizQuestions.filter((q) => q.difficulty === 'hard').length,
}
