// Chapter 14: Men's Haircutting and Styling — PREMIUM MCQ QUIZ
// 40 questions generated STRICTLY from Chapter 14 premium flashcards
// Randomized question selection and answer order per attempt
// The Barber's Chair Certification Exam

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 14: FULL QUESTION BANK (40 questions)
// Generated from chapter-14-premium-flashcards.ts
// NATURAL answer distribution (NOT forced balanced)
// ───────────────────────────────────────────────
export const chapter14PremiumQuizQuestions: QuizQuestion[] = [
  // === INTRODUCTION & CONSULTATION (5 questions) ===
  {
    id: 'qq-14-001',
    quiz_id: 'quiz-14',
    question: "Why is haircutting considered the foundation of barbering?",
    answer_a: 'It is the core skill that defines a barber and builds client loyalty',
    answer_b: 'It is required by law before any other service',
    answer_c: 'It is the easiest skill to learn',
    answer_d: 'It pays more than any other service',
    correct_answer: 'a',
    explanation: 'Haircutting is the core skill that defines a barber. It allows customization, mastery of techniques, building a loyal client base, and increasing revenue.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-14-002',
    quiz_id: 'quiz-14',
    question: "What is the primary purpose of a client consultation?",
    answer_a: 'To prevent misunderstandings and ensure client satisfaction',
    answer_b: 'To sell additional products',
    answer_c: 'To determine how much to charge',
    answer_d: 'To check the client\'s ID',
    correct_answer: 'a',
    explanation: 'A thorough consultation prevents misunderstandings, builds trust, and ensures the final result meets the client\'s expectations.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-14-003',
    quiz_id: 'quiz-14',
    question: "When a client says 'just a trim,' what should you do?",
    answer_a: 'Always clarify by showing exactly how much hair will be removed',
    answer_b: 'Cut off exactly 1 inch',
    answer_c: 'Ask no further questions and begin cutting',
    answer_d: 'Explain that you do not do trims',
    correct_answer: 'a',
    explanation: 'A trim means different things to different people. Always demonstrate length with fingers or a comb and confirm before cutting.',
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-14-004',
    quiz_id: 'quiz-14',
    question: "Which of the following is NOT a key consultation question?",
    answer_a: 'What is your annual income?',
    answer_b: 'How short do you want it?',
    answer_c: 'Do you want a fade, taper, or all one length?',
    answer_d: 'Do you have any cowlicks or growth patterns?',
    correct_answer: 'a',
    explanation: 'Income is irrelevant to haircutting. Key questions focus on desired length, style, and hair growth patterns.',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-14-005',
    quiz_id: 'quiz-14',
    question: "Why should you face the client toward the mirror during a haircut?",
    answer_a: 'So the client can see progress and provide feedback',
    answer_b: 'So you can see your own reflection',
    answer_c: 'It is required by state board regulations',
    answer_d: 'To make the room appear larger',
    correct_answer: 'a',
    explanation: 'Facing the client toward the mirror allows them to see progress and provide feedback during the service.',
    difficulty: 'easy',
    order_index: 5,
  },

  // === FACIAL SHAPES (5 questions) ===
  {
    id: 'qq-14-006',
    quiz_id: 'quiz-14',
    question: "Which facial shape is considered the ideal shape?",
    answer_a: 'Oval',
    answer_b: 'Round',
    answer_c: 'Square',
    answer_d: 'Heart',
    correct_answer: 'a',
    explanation: 'The oval face has balanced proportions with similar width of forehead and jaw, and the face is longer than wide.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-14-007',
    quiz_id: 'quiz-14',
    question: "What is the design goal for a round face?",
    answer_a: 'Add height and minimize width',
    answer_b: 'Add width to the sides',
    answer_c: 'Keep all lengths equal',
    answer_d: 'Shave the head completely',
    correct_answer: 'a',
    explanation: 'For round faces, the goal is to add height and minimize width. Avoid styles that add volume to the sides.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-14-008',
    quiz_id: 'quiz-14',
    question: "What is the design goal for a square face?",
    answer_a: 'Soften angles while maintaining masculine features',
    answer_b: 'Add sharp angles',
    answer_c: 'Make the face appear rounder',
    answer_d: 'Add maximum volume on top',
    correct_answer: 'a',
    explanation: 'For square faces, the goal is to soften angles while maintaining masculine features. Avoid too much volume on top.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-14-009',
    quiz_id: 'quiz-14',
    question: "A client has a wider forehead and narrower chin. What face shape is this?",
    answer_a: 'Inverted triangular (heart)',
    answer_b: 'Round',
    answer_c: 'Square',
    answer_d: 'Oval',
    correct_answer: 'a',
    explanation: 'An inverted triangular (heart) face has a wider forehead and narrower chin. The goal is to add width at the jawline.',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-14-010',
    quiz_id: 'quiz-14',
    question: "Which design principle focuses on creating visual equilibrium?",
    answer_a: 'Balance',
    answer_b: 'Proportion',
    answer_c: 'Emphasis',
    answer_d: 'Rhythm',
    correct_answer: 'a',
    explanation: 'Balance creates visual equilibrium between all elements of the haircut.',
    difficulty: 'easy',
    order_index: 10,
  },

  // === TECHNIQUES (5 questions) ===
  {
    id: 'qq-14-011',
    quiz_id: 'quiz-14',
    question: "What technique uses clippers over a comb to create precise lines?",
    answer_a: 'Clipper-over-comb',
    answer_b: 'Shear-over-comb',
    answer_c: 'Freehand clipper',
    answer_d: 'Blending',
    correct_answer: 'a',
    explanation: 'Clipper-over-comb uses clippers over a comb to create precise, clean lines and gradual fades.',
    difficulty: 'easy',
    order_index: 11,
  },
  {
    id: 'qq-14-012',
    quiz_id: 'quiz-14',
    question: "Which technique creates softer, more blended results than clippers?",
    answer_a: 'Shear-over-comb',
    answer_b: 'Clipper-over-comb',
    answer_c: 'Freehand clipper',
    answer_d: 'Fading',
    correct_answer: 'a',
    explanation: 'Shear-over-comb uses shears over a comb for softer, more blended results than clippers.',
    difficulty: 'easy',
    order_index: 12,
  },
  {
    id: 'qq-14-013',
    quiz_id: 'quiz-14',
    question: "What is fading in haircutting?",
    answer_a: 'Gradually tapering hair from short to shorter or to skin',
    answer_b: 'Cutting all hair to the same length',
    answer_c: 'Using only shears for the entire haircut',
    answer_d: 'Dyeing the hair a lighter color',
    correct_answer: 'a',
    explanation: 'Fading gradually tapers hair from short to shorter or to skin.',
    difficulty: 'easy',
    order_index: 13,
  },
  {
    id: 'qq-14-014',
    quiz_id: 'quiz-14',
    question: "What is the purpose of blending?",
    answer_a: 'Creating smooth transitions between different lengths',
    answer_b: 'Cutting hair against the grain',
    answer_c: 'Applying color to the hair',
    answer_d: 'Removing all hair from the neck',
    correct_answer: 'a',
    explanation: 'Blending creates smooth transitions between different lengths in a haircut.',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-14-015',
    quiz_id: 'quiz-14',
    question: "What is freehand clipper technique used for?",
    answer_a: 'Outlining and detail work without a comb',
    answer_b: 'Creating long layers',
    answer_c: 'Blowdrying the hair',
    answer_d: 'Applying hair products',
    correct_answer: 'a',
    explanation: 'Freehand clipper technique uses clippers without a comb for outlining and detail work.',
    difficulty: 'easy',
    order_index: 15,
  },

  // === PROCEDURES (5 questions) ===
  {
    id: 'qq-14-016',
    quiz_id: 'quiz-14',
    question: "What is the first step in a basic clipper haircut?",
    answer_a: 'Determine the desired length on top',
    answer_b: 'Start at the nape',
    answer_c: 'Apply shaving cream',
    answer_d: 'Blowdry the hair',
    correct_answer: 'a',
    explanation: 'The first step in a basic clipper haircut is to determine the desired length on top.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-14-017',
    quiz_id: 'quiz-14',
    question: "What tool is used for a shadow fade cut?",
    answer_a: 'Adjustable-blade clipper with and without guards',
    answer_b: 'Only shears',
    answer_c: 'A straight razor',
    answer_d: 'Hair dye',
    correct_answer: 'a',
    explanation: 'A shadow fade is performed using an adjustable-blade clipper with and without guards.',
    difficulty: 'easy',
    order_index: 17,
  },
  {
    id: 'qq-14-018',
    quiz_id: 'quiz-14',
    question: "Cutting against the grain achieves what result?",
    answer_a: 'A closer cut than cutting with the grain',
    answer_b: 'A longer cut than cutting with the grain',
    answer_c: 'No difference in length',
    answer_d: 'A curlier texture',
    correct_answer: 'a',
    explanation: 'Cutting against the grain achieves a closer cut than cutting with the grain.',
    difficulty: 'easy',
    order_index: 18,
  },
  {
    id: 'qq-14-019',
    quiz_id: 'quiz-14',
    question: "What is cross-checking in haircutting?",
    answer_a: 'Checking the haircut from multiple angles for evenness',
    answer_b: 'Asking the client to pay before finishing',
    answer_c: 'Using two mirrors simultaneously',
    answer_d: 'Cutting hair in a cross pattern',
    correct_answer: 'a',
    explanation: 'Cross-checking means checking the haircut from multiple angles and directions to ensure evenness and proper blending.',
    difficulty: 'medium',
    order_index: 19,
  },
  {
    id: 'qq-14-020',
    quiz_id: 'quiz-14',
    question: "What is a guide in haircutting?",
    answer_a: 'A section of hair cut to desired length used as a reference',
    answer_b: 'A book about haircutting',
    answer_c: 'The client\'s friend who watches',
    answer_d: 'A type of comb',
    correct_answer: 'a',
    explanation: 'A guide is a section of hair cut to the desired length and used as a reference for cutting subsequent sections.',
    difficulty: 'easy',
    order_index: 20,
  },

  // === BLOWDRYING (5 questions) ===
  {
    id: 'qq-14-021',
    quiz_id: 'quiz-14',
    question: "How far should the dryer be held from the hair during freeform blowdrying?",
    answer_a: '6 to 10 inches',
    answer_b: '1 to 2 inches',
    answer_c: '20 to 24 inches',
    answer_d: 'Touching the hair',
    correct_answer: 'a',
    explanation: 'During freeform blowdrying, hold the dryer 6 to 10 inches from the hair.',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-14-022',
    quiz_id: 'quiz-14',
    question: "What is the purpose of blow waving?",
    answer_a: 'To create lift or direction in the top section',
    answer_b: 'To remove all moisture from the hair',
    answer_c: 'To straighten curly hair',
    answer_d: 'To apply hair color',
    correct_answer: 'a',
    explanation: 'Blow waving creates lift or direction in the top section by forming a ridge or bend to set the style.',
    difficulty: 'medium',
    order_index: 22,
  },
  {
    id: 'qq-14-023',
    quiz_id: 'quiz-14',
    question: "When is diffused drying used?",
    answer_a: 'For curly or textured hair to maintain natural curl pattern',
    answer_b: 'Only for straight hair',
    answer_c: 'To create a slicked-back look',
    answer_d: 'To remove hair product',
    correct_answer: 'a',
    explanation: 'Diffused drying is used for curly or textured hair to maintain the natural curl pattern and volume.',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'qq-14-024',
    quiz_id: 'quiz-14',
    question: "In stylized blowdrying, where should you begin?",
    answer_a: 'In the back section',
    answer_b: 'On the top section',
    answer_c: 'Around the ears',
    answer_d: 'At the hairline',
    correct_answer: 'a',
    explanation: 'In stylized blowdrying, begin in the back section and work systematically through the hair.',
    difficulty: 'easy',
    order_index: 24,
  },
  {
    id: 'qq-14-025',
    quiz_id: 'quiz-14',
    question: "What angle should the dryer nozzle point during freeform blowdrying?",
    answer_a: 'Downward',
    answer_b: 'Upward',
    answer_c: 'Directly at the scalp',
    answer_d: 'Sideways',
    correct_answer: 'a',
    explanation: 'During freeform blowdrying, angle the nozzle pointing downward to smooth the hair cuticle.',
    difficulty: 'easy',
    order_index: 25,
  },

  // === HEAD SHAVE (5 questions) ===
  {
    id: 'qq-14-026',
    quiz_id: 'quiz-14',
    question: "What should be examined before performing a head shave?",
    answer_a: 'The scalp for abrasions, lesions, or disorders',
    answer_b: 'The client\'s shoes',
    answer_c: 'The weather outside',
    answer_d: 'The client\'s wallet',
    correct_answer: 'a',
    explanation: 'Before a head shave, examine the scalp for abrasions, lesions, or disorders. Do not proceed if any are found.',
    difficulty: 'easy',
    order_index: 26,
  },
  {
    id: 'qq-14-027',
    quiz_id: 'quiz-14',
    question: "How many steamed-towel treatments are recommended before shaving the head?",
    answer_a: 'Two or three',
    answer_b: 'None',
    answer_c: 'Ten',
    answer_d: 'One quick rinse',
    correct_answer: 'a',
    explanation: 'Two or three steamed-towel treatments are recommended to soften the hair before shaving the head.',
    difficulty: 'easy',
    order_index: 27,
  },
  {
    id: 'qq-14-028',
    quiz_id: 'quiz-14',
    question: "In what direction should you shave the head?",
    answer_a: 'With the grain',
    answer_b: 'Against the grain',
    answer_c: 'In a circular motion',
    answer_d: 'Only on the sides',
    correct_answer: 'a',
    explanation: 'Shave the head with the grain, from crown to nape and from crown to front hairline.',
    difficulty: 'easy',
    order_index: 28,
  },
  {
    id: 'qq-14-029',
    quiz_id: 'quiz-14',
    question: "What is applied after a head shave to soothe the skin?",
    answer_a: 'Witch hazel or skin toner',
    answer_b: 'Hot sauce',
    answer_c: 'Hair dye',
    answer_d: 'Nail polish',
    correct_answer: 'a',
    explanation: 'After a head shave, apply witch hazel or skin toner, followed by a cool-towel application, then moisturizing cream or oil.',
    difficulty: 'easy',
    order_index: 29,
  },
  {
    id: 'qq-14-030',
    quiz_id: 'quiz-14',
    question: "Why is it important to stretch the skin taut during a head shave?",
    answer_a: 'To create a smooth surface and prevent cuts',
    answer_b: 'To make the client taller',
    answer_c: 'To remove more hair at once',
    answer_d: 'To speed up the service',
    correct_answer: 'a',
    explanation: 'Stretching the skin taut creates a smooth surface for the razor and helps prevent cuts and nicks.',
    difficulty: 'easy',
    order_index: 30,
  },

  // === CORNROWS (3 questions) ===
  {
    id: 'qq-14-031',
    quiz_id: 'quiz-14',
    question: "What are cornrows?",
    answer_a: 'Narrow rows of visible braids that lie close to the scalp',
    answer_b: 'A type of clipper guard',
    answer_c: 'A hair coloring technique',
    answer_d: 'A type of shampoo',
    correct_answer: 'a',
    explanation: 'Cornrows are narrow rows of visible braids that lie close to the scalp.',
    difficulty: 'easy',
    order_index: 31,
  },
  {
    id: 'qq-14-032',
    quiz_id: 'quiz-14',
    question: "How are cornrow ends secured?",
    answer_a: 'With small rubber bands',
    answer_b: 'With glue',
    answer_c: 'They are left loose',
    answer_d: 'With tape',
    correct_answer: 'a',
    explanation: 'Cornrow ends are secured with small rubber bands.',
    difficulty: 'easy',
    order_index: 32,
  },
  {
    id: 'qq-14-033',
    quiz_id: 'quiz-14',
    question: "What is the braiding pattern for cornrows?",
    answer_a: 'Cross left under center, then right under center, picking up hair with each cross',
    answer_b: 'Cross left over center, then right over center',
    answer_c: 'Braid only two strands',
    answer_d: 'Use a comb to weave hair',
    correct_answer: 'a',
    explanation: 'Cornrows use an underhand braiding pattern: cross left under center, then right under center, picking up hair from the base with each cross.',
    difficulty: 'medium',
    order_index: 33,
  },

  // === SAFETY & CLEAN-UP (5 questions) ===
  {
    id: 'qq-14-034',
    quiz_id: 'quiz-14',
    question: "Where should used blades be disposed of?",
    answer_a: 'In a sharps container',
    answer_b: 'In the regular trash',
    answer_c: 'On the counter',
    answer_d: 'In the sink',
    correct_answer: 'a',
    explanation: 'Used blades must be deposited in a sharps container — never in regular trash or on the counter.',
    difficulty: 'easy',
    order_index: 34,
  },
  {
    id: 'qq-14-035',
    quiz_id: 'quiz-14',
    question: "Why is it important to lock the chair during a haircut?",
    answer_a: 'To prevent movement and ensure client safety',
    answer_b: 'To keep the client from leaving',
    answer_c: 'To make the chair more comfortable',
    answer_d: 'It is not important',
    correct_answer: 'a',
    explanation: 'Locking the chair prevents movement and ensures client safety during the service.',
    difficulty: 'easy',
    order_index: 35,
  },
  {
    id: 'qq-14-036',
    quiz_id: 'quiz-14',
    question: "What is the purpose of a neck strip?",
    answer_a: 'To provide a sanitary barrier between the client\'s neck and the cape',
    answer_b: 'To measure hair length',
    answer_c: 'To hold tools',
    answer_d: 'To decorate the chair',
    correct_answer: 'a',
    explanation: 'A neck strip provides a sanitary barrier between the client\'s neck and the haircutting cape.',
    difficulty: 'easy',
    order_index: 36,
  },
  {
    id: 'qq-14-037',
    quiz_id: 'quiz-14',
    question: "What should you do if a client has a scalp disorder before a head shave?",
    answer_a: 'Do not proceed and refer to a medical professional',
    answer_b: 'Shave more carefully',
    answer_c: 'Use extra shaving cream',
    answer_d: 'Shave only the healthy areas',
    correct_answer: 'a',
    explanation: 'If a client has a scalp disorder, do not proceed with the shave. Refer the client to a medical professional.',
    difficulty: 'easy',
    order_index: 37,
  },
  {
    id: 'qq-14-038',
    quiz_id: 'quiz-14',
    question: "What is the last step in post-service clean-up?",
    answer_a: 'Wash hands thoroughly',
    answer_b: 'Take a break',
    answer_c: 'Call the next client',
    answer_d: 'Post on social media',
    correct_answer: 'a',
    explanation: 'The final step in post-service clean-up is always washing hands thoroughly.',
    difficulty: 'easy',
    order_index: 38,
  },

  // === ANATOMY (2 questions) ===
  {
    id: 'qq-14-039',
    quiz_id: 'quiz-14',
    question: "What is the parietal ridge?",
    answer_a: 'The curved area where the sides meet the top of the head',
    answer_b: 'The lowest part of the neck',
    answer_c: 'The front hairline',
    answer_d: 'The area behind the ears',
    correct_answer: 'a',
    explanation: 'The parietal ridge is the curved area of the head where the sides meet the top — an important reference point for sectioning and blending.',
    difficulty: 'easy',
    order_index: 39,
  },
  {
    id: 'qq-14-040',
    quiz_id: 'quiz-14',
    question: "What is the occipital area?",
    answer_a: 'The back and base of the head, below the crown and above the nape',
    answer_b: 'The top of the head',
    answer_c: 'The sides of the head',
    answer_d: 'The forehead',
    correct_answer: 'a',
    explanation: 'The occipital area is the back and base of the head, below the crown and above the nape.',
    difficulty: 'easy',
    order_index: 40,
  },
  {
    id: 'qq-14-041',
    quiz_id: 'quiz-14',
    question: "How many facial shapes are there in total?",
    answer_a: 'Seven',
    answer_b: 'Five',
    answer_c: 'Four',
    answer_d: 'Nine',
    correct_answer: 'a',
    explanation: 'There are seven facial shapes: oval, round, square, inverted triangular, pear-shaped, oblong, and diamond.',
    difficulty: 'easy',
    order_index: 41,
  },
  {
    id: 'qq-14-042',
    quiz_id: 'quiz-14',
    question: "What is the design goal for a client with a convex profile?",
    answer_a: 'Minimize forehead bulge with close hair arrangement at the forehead',
    answer_b: 'Add volume over the forehead',
    answer_c: 'Create sharp angles',
    answer_d: 'Leave hair long all over',
    correct_answer: 'a',
    explanation: 'A convex profile has a receding forehead and chin. The design goal is to minimize the forehead bulge by using close hair arrangement at the forehead.',
    difficulty: 'medium',
    order_index: 42,
  },
  {
    id: 'qq-14-043',
    quiz_id: 'quiz-14',
    question: "What is the parietal ridge (crest)?",
    answer_a: 'The widest section of the head when a comb is held flat against the sides',
    answer_b: 'The lowest part of the neck',
    answer_c: 'The front hairline',
    answer_d: 'The area behind the ears',
    correct_answer: 'a',
    explanation: 'The parietal ridge (also called crest, hatband, or horseshoe) is the widest section of the head, starting at the temples and ending just below the crown.',
    difficulty: 'easy',
    order_index: 43,
  },
  {
    id: 'qq-14-044',
    quiz_id: 'quiz-14',
    question: "How fast does hair grow on average?",
    answer_a: 'Approximately one-half inch per month',
    answer_b: 'One inch per week',
    answer_c: 'One-quarter inch per year',
    answer_d: 'Two inches per month',
    correct_answer: 'a',
    explanation: 'Hair grows approximately one-half inch per month on average. This helps barbers estimate how much hair has grown since the client\'s last visit.',
    difficulty: 'easy',
    order_index: 44,
  },
  {
    id: 'qq-14-045',
    quiz_id: 'quiz-14',
    question: "What is 'envisioning' in haircutting?",
    answer_a: 'Mentally visualizing the haircut before beginning the procedure',
    answer_b: 'Using a mirror to show the client the finished style',
    answer_c: 'Drawing the haircut on paper first',
    answer_d: 'Watching a video tutorial before cutting',
    correct_answer: 'a',
    explanation: 'Envisioning is the process of mentally visualizing the haircut before beginning the actual procedure. It develops through practice and experience.',
    difficulty: 'medium',
    order_index: 45,
  },

  // === DESIGN ELEMENTS & ELEVATION (Batch 2 additions) ===
  {
    id: 'qq-14-046',
    quiz_id: 'quiz-14',
    question: "What effect do horizontal lines create in a haircut?",
    answer_a: 'Build weight and create one-length or low-elevation designs',
    answer_b: 'Remove weight and create layers',
    answer_c: 'Create diagonal slopes within the design',
    answer_d: 'Soften the overall appearance',
    correct_answer: 'a',
    explanation: 'Horizontal lines build weight and are used to create one-length designs and low-elevation or blunt designs. Weight lines are usually created at the perimeter or occipital area.',
    difficulty: 'medium',
    order_index: 46,
  },
  {
    id: 'qq-14-047',
    quiz_id: 'quiz-14',
    question: "What is zero elevation and what does it produce?",
    answer_a: 'The lowest elevation; produces weight, bulk, and maximum length at the perimeter',
    answer_b: 'A medium elevation that creates layers',
    answer_c: 'A high elevation used for tapering',
    answer_d: 'An angle that removes all bulk from the hair',
    correct_answer: 'a',
    explanation: 'Zero elevation is the lowest elevation where hair is combed straight down from where it grows. It produces weight, bulk, and maximum length at the perimeter and creates the design line that guides all subsequent partings.',
    difficulty: 'medium',
    order_index: 47,
  },
  {
    id: 'qq-14-048',
    quiz_id: 'quiz-14',
    question: "What is the most common elevation used in men's haircutting?",
    answer_a: 'Ninety-degree elevation',
    answer_b: 'Zero elevation',
    answer_c: 'Forty-five degree elevation',
    answer_d: 'One hundred eighty-degree elevation',
    correct_answer: 'a',
    explanation: 'Ninety-degree elevation is the most common projection used in men\'s haircutting. It produces layering, tapering, and blended effects.',
    difficulty: 'medium',
    order_index: 48,
  },
  {
    id: 'qq-14-049',
    quiz_id: 'quiz-14',
    question: "What is the purpose of cross-checking in haircutting?",
    answer_a: 'To check the precision of cutting lines by parting subsections in the opposite direction',
    answer_b: 'To blend the hair more smoothly',
    answer_c: 'To create a sharper outline',
    answer_d: 'To remove excess bulk from the haircut',
    correct_answer: 'a',
    explanation: 'Cross-checking is parting off subsections opposite from the elevation or direction at which they were cut to check the precision of cutting lines or blending.',
    difficulty: 'medium',
    order_index: 49,
  },
  {
    id: 'qq-14-050',
    quiz_id: 'quiz-14',
    question: "Why do state barber boards most often require a taper cut on the practical exam?",
    answer_a: 'It requires several cutting techniques using different tools',
    answer_b: 'It is the easiest haircut to perform',
    answer_c: 'It takes the least amount of time',
    answer_d: 'It requires only one tool',
    correct_answer: 'a',
    explanation: 'A taper cut requires several cutting techniques using different tools to perform properly, including fingers-and-shear, shear-over-comb, freehand shear, freehand clipper, clipper-over-comb, and razor cutting.',
    difficulty: 'hard',
    order_index: 50,
  },
]
