// Chapter 7: Basics of Chemistry — PREMIUM FLASHCARDS
// The Barber's Laboratory — Master the Formulas Behind Every Product
// Categories: Matter & Properties, Redox Reactions, Solutions & Emulsions, pH & Water, Shampoos & Conditioners, Product Chemistry, Safety & USP, Board Exam Alerts
// Source: Chapter 7 textbook images (textbook-images/chapter-7/)

import { Flashcard } from '@/types'

export const chapter7PremiumFlashcards: Flashcard[] = [
  // ==========================================
  // CATEGORY 1: MATTER & PROPERTIES (10 cards)
  // ==========================================
  {
    id: 'fc-7-001',
    chapter_id: 'ch-7',
    front: "What does chemistry study?",
    back: "Chemistry examines the composition, structure, properties, and changes of matter. In barbering, it helps explain how products and chemical services behave.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-7-002',
    chapter_id: 'ch-7',
    front: "How should you distinguish organic chemistry from inorganic chemistry?",
    back: "Organic chemistry focuses on carbon-containing substances and compounds. Inorganic chemistry covers substances such as water, minerals, metals, ammonia, and other materials generally studied outside organic carbon chemistry. Do not use a living-versus-nonliving shortcut.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-7-003',
    chapter_id: 'ch-7',
    front: "Can organic or inorganic classification tell you whether a chemical is safe or flammable?",
    back: "No. Organic versus inorganic describes chemical composition, not hazard level. Safety depends on the specific product, concentration, pH, ingredients, exposure route, and directions for use.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-7-004',
    chapter_id: 'ch-7',
    front: "What is matter?",
    back: "Matter is anything that has mass and occupies space. In basic chemistry, common physical states include solids, liquids, and gases.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-7-005',
    chapter_id: 'ch-7',
    front: "How do physical properties differ from chemical properties?",
    back: "A physical property can be observed without changing a substance’s chemical identity. A chemical property describes how a substance behaves when it undergoes a chemical reaction.",
    category: 'Matter & Properties',
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-7-006',
    chapter_id: 'ch-7',
    front: "How do you tell a physical change from a chemical change?",
    back: "A physical change alters form, state, or another physical characteristic without creating a new chemical substance. A chemical change involves a reaction that changes chemical composition and produces substances with different chemical properties.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-7-007',
    chapter_id: 'ch-7',
    front: "What is an element?",
    back: "An element is a basic form of matter made of one type of atom. Examples important to chemistry include hydrogen, oxygen, carbon, and nitrogen.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-7-008',
    chapter_id: 'ch-7',
    front: "What are the three main subatomic particles and their charges?",
    back: "Protons carry a positive charge, neutrons have no charge, and electrons carry a negative charge.",
    category: 'Matter & Properties',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-7-009',
    chapter_id: 'ch-7',
    front: "How does a molecule differ from a compound?",
    back: "A molecule contains two or more chemically joined atoms. A compound contains atoms of different elements combined in definite proportions.",
    category: 'Matter & Properties',
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-7-010',
    chapter_id: 'ch-7',
    front: "How does a pure substance differ from a mixture?",
    back: "A pure substance has a fixed composition. A mixture combines substances physically and can vary in composition.",
    category: 'Matter & Properties',
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 2: REDOX REACTIONS (8 cards)
  // ==========================================
  {
    id: 'fc-7-011',
    chapter_id: 'ch-7',
    front: "What is oxidation?",
    back: "Oxidation can involve gaining oxygen or losing hydrogen. In barbering chemistry, oxidation is important in services such as oxidation haircolor.",
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-7-012',
    chapter_id: 'ch-7',
    front: "What is reduction?",
    back: "Reduction can involve losing oxygen or gaining hydrogen. It occurs together with oxidation in a redox reaction.",
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-7-013',
    chapter_id: 'ch-7',
    front: "Why are oxidation and reduction treated as a pair?",
    back: "They occur together in a redox reaction. One substance is oxidized while another is reduced. In Chapter 7, track the oxygen or hydrogen change to identify which process is occurring.",
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-7-014',
    chapter_id: 'ch-7',
    front: "What chemical changes occur during permanent waving?",
    back: "The waving phase uses reduction to break or rearrange disulfide bonds. The neutralizing phase uses oxidation to reform bonds in the new shape.",
    category: 'Redox Reactions',
    difficulty: 'hard',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-7-015',
    chapter_id: 'ch-7',
    front: "What role does hydrogen peroxide play in oxidation haircolor?",
    back: "Hydrogen peroxide acts as an oxidizing agent by supplying oxygen for the color-development reaction. As it loses oxygen, it is reduced.",
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-7-016',
    chapter_id: 'ch-7',
    front: "What is an exothermic reaction?",
    back: "An exothermic reaction releases heat to its surroundings. During a chemical service, unexpected or excessive heat is a safety signal to stop and follow the product directions rather than assuming all warmth is normal.",
    category: 'Redox Reactions',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-7-017',
    chapter_id: 'ch-7',
    front: "What is an endothermic reaction?",
    back: "An endothermic reaction absorbs heat from its surroundings. In barbering chemistry, some reactions may require an external heat source rather than producing heat on their own.",
    category: 'Redox Reactions',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-7-018',
    chapter_id: 'ch-7',
    front: "What happens during permanent-wave neutralization?",
    back: "The neutralizer oxidizes the hair so disulfide bonds can reform after the reduction phase. This oxidation step helps stabilize the new shape.",
    category: 'Redox Reactions',
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 3: SOLUTIONS, SUSPENSIONS & EMULSIONS (8 cards)
  // ==========================================
  {
    id: 'fc-7-019',
    chapter_id: 'ch-7',
    front: "What makes a mixture a solution?",
    back: "A solution is a stable, uniform mixture in which the dissolved substance is distributed throughout the solvent and does not settle out. Stability and uniform distribution are more reliable clues than appearance alone.",
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-7-020',
    chapter_id: 'ch-7',
    front: "What makes a mixture a suspension?",
    back: "A suspension contains dispersed particles large enough to settle over time. If the product label directs you to shake or redistribute the product, follow that instruction before use.",
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-7-021',
    chapter_id: 'ch-7',
    front: "What is an emulsion?",
    back: "An emulsion is a mixture of two liquids that normally do not mix, such as oil and water, held together with the help of an emulsifying agent or surfactant.",
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-7-022',
    chapter_id: 'ch-7',
    front: "What is the difference between oil-in-water and water-in-oil emulsions?",
    back: "In an oil-in-water emulsion, oil droplets are dispersed through a continuous water phase. In a water-in-oil emulsion, water droplets are dispersed through a continuous oil phase.",
    category: 'Solutions & Emulsions',
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-7-023',
    chapter_id: 'ch-7',
    front: "What is a surfactant?",
    back: "A surfactant lowers surface tension and helps water interact with oils and soils. Its structure includes a water-attracting portion and an oil-attracting portion.",
    category: 'Solutions & Emulsions',
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-7-024',
    chapter_id: 'ch-7',
    front: "What are the four main surfactant classifications?",
    back: "Anionic surfactants carry a negative charge, cationic surfactants a positive charge, nonionic surfactants no charge, and amphoteric surfactants can carry different charges depending on conditions.",
    category: 'Solutions & Emulsions',
    difficulty: 'hard',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-7-025',
    chapter_id: 'ch-7',
    front: "Why might a product label tell you to shake before use?",
    back: "Some mixtures can separate or allow dispersed particles to settle while standing. Shaking redistributes the contents. The label instruction matters more than trying to identify the product type from the words “shake well” alone.",
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-7-026',
    chapter_id: 'ch-7',
    front: "Can shampoos and conditioners be emulsions?",
    back: "Yes. Chapter 7 uses shampoos and conditioners as examples of emulsions. The exact type and ingredient balance depend on the individual formula.",
    category: 'Solutions & Emulsions',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 4: pH & WATER (12 cards)
  // ==========================================
  {
    id: 'fc-7-027',
    chapter_id: 'ch-7',
    front: "What does pH tell you?",
    back: "pH reflects hydrogen-ion conditions in a water-based solution. On the standard scale, values below 7 are acidic, 7 is neutral, and values above 7 are alkaline.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-7-028',
    chapter_id: 'ch-7',
    front: "What pH range is commonly associated with hair and skin?",
    back: "Hair and skin are commonly around pH 4.5–5.5, which is slightly acidic. Product effects still depend on concentration, ingredients, hair or skin condition, and correct use.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-7-029',
    chapter_id: 'ch-7',
    front: "How can acidic conditions affect hair?",
    back: "Milder acidic conditions can contract and harden hair and help tighten the cuticle. Very strong acid can damage or dissolve hair. Always consider strength and concentration instead of treating every acidic product the same.",
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-7-030',
    chapter_id: 'ch-7',
    front: "How can alkaline conditions affect hair?",
    back: "As alkalinity increases, hair can swell and become more porous as the cuticle opens. Strong alkalis can damage or dissolve hair, so product strength and manufacturer directions are critical.",
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-7-031',
    chapter_id: 'ch-7',
    front: "What is acid-alkali neutralization, and what should you not confuse it with?",
    back: "Acid-alkali neutralization occurs when an acid and alkali react to form water and a salt. Do not confuse that reaction with oxidation neutralization in permanent waving; they are different chemical processes.",
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-7-032',
    chapter_id: 'ch-7',
    front: "How does soft water differ from hard water?",
    back: "Soft water contains fewer dissolved minerals and usually lathers more easily. Hard water contains more minerals, such as calcium and magnesium, and can reduce lather and leave deposits.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-7-033',
    chapter_id: 'ch-7',
    front: "How can water affect the size of the hair fiber?",
    back: "Water can penetrate the hair and cause it to swell. This helps explain why water and pH are important when evaluating how products and chemical services affect the hair.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-7-034',
    chapter_id: 'ch-7',
    front: "What happens to hair at extreme pH levels?",
    back: "Very strong acids and very strong alkalis can severely damage or dissolve hair. The safe takeaway is to follow the labeled product strength, timing, and application directions rather than memorize a single danger cutoff for every formula.",
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-7-035',
    chapter_id: 'ch-7',
    front: "Why is water important as a solvent in barbering?",
    back: "Water dissolves many substances and is widely used in cleansing, product formulation, and chemical reactions. Oils generally require surfactants or emulsifiers to disperse effectively in water.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-7-036',
    chapter_id: 'ch-7',
    front: "What are common methods used to purify water?",
    back: "Chapter 7 discusses boiling, filtration, and distillation. Each method removes or reduces different types of impurities.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-7-037',
    chapter_id: 'ch-7',
    front: "How can hard water affect shampoo performance?",
    back: "Minerals in hard water can reduce lather and contribute to deposits on the hair. Product choice should be based on the client’s condition and the actual buildup present.",
    category: 'pH & Water',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-7-038',
    chapter_id: 'ch-7',
    front: "Why are many conditioners formulated on the acidic side?",
    back: "Acidic conditioner formulas can help contract and smooth the hair surface and improve manageability. The exact formula and pH vary by product, so use the product’s intended purpose and directions.",
    category: 'pH & Water',
    difficulty: 'easy',
    order_index: 38,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 5: SHAMPOOS & CONDITIONERS (12 cards)
  // ==========================================
  {
    id: 'fc-7-039',
    chapter_id: 'ch-7',
    front: "What is the main purpose of shampoo?",
    back: "Shampoo is designed to cleanse the hair and scalp by helping remove oil, soil, debris, and product buildup.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-7-040',
    chapter_id: 'ch-7',
    front: "How do the main surfactant classes differ in shampoo chemistry?",
    back: "Anionic surfactants are commonly used for cleansing, cationic ingredients are associated more with conditioning, nonionic surfactants carry no charge, and amphoteric surfactants can be mild and change charge behavior with conditions.",
    category: 'Shampoos & Conditioners',
    difficulty: 'hard',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-7-041',
    chapter_id: 'ch-7',
    front: "How does a clarifying shampoo differ from a moisturizing or conditioning shampoo?",
    back: "Clarifying shampoos target product or mineral buildup with stronger cleansing or chelating action. Moisturizing or conditioning shampoos are designed to cleanse while supporting dry or compromised hair. Frequency should match the client’s condition and product directions.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-7-042',
    chapter_id: 'ch-7',
    front: "When is a neutralizing or balancing shampoo appropriate?",
    back: "Use it when a specific chemical service or product system directs you to remove or counter unwanted alkaline residue. It does not replace permanent-wave oxidation neutralization, and it is not a universal step after every chemical service.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-7-043',
    chapter_id: 'ch-7',
    front: "What is a medicated shampoo?",
    back: "A medicated shampoo contains active ingredients intended for a particular scalp condition. Use it according to its label and the client’s condition.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-7-044',
    chapter_id: 'ch-7',
    front: "What is the purpose of a sulfate-free shampoo?",
    back: "A sulfate-free shampoo uses little or no sulfate surfactant and may be selected when a less-stripping cleansing approach is appropriate for the client.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-7-045',
    chapter_id: 'ch-7',
    front: "What are the main conditioner categories in Chapter 7?",
    back: "Conditioner categories include instant or rinse-out conditioners, treatment or repair conditioners, and leave-in conditioners. Their use depends on the condition of the hair and the product directions.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-7-046',
    chapter_id: 'ch-7',
    front: "What kinds of ingredients may be found in conditioners?",
    back: "Conditioners may include proteins, oils or fatty materials, humectants, moisturizers, and film-forming ingredients. Their effects depend on the formula and the condition of the hair.",
    category: 'Shampoos & Conditioners',
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-7-047',
    chapter_id: 'ch-7',
    front: "When might a dry or powder shampoo be used?",
    back: "A dry or powder shampoo can be used when a wet shampoo is not appropriate or practical for the client’s hair condition. Follow the product directions for application and removal.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-7-048',
    chapter_id: 'ch-7',
    front: "What is a balancing shampoo intended to do?",
    back: "A balancing shampoo is designed for oily hair or scalp conditions, helping remove excess oil while avoiding unnecessarily harsh cleansing.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-7-049',
    chapter_id: 'ch-7',
    front: "What is the purpose of a color-enhancing shampoo?",
    back: "Color-enhancing shampoos combine cleansing with color-supporting ingredients that can help refresh or enhance selected tones. Choose the product to match the intended color result and follow its directions.",
    category: 'Shampoos & Conditioners',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-7-050',
    chapter_id: 'ch-7',
    front: "How should you choose a shampoo for a client?",
    back: "Match the shampoo’s purpose to the client’s hair and scalp condition, chemical history, buildup level, and service goal. Product labels and manufacturer directions are more reliable than a rigid one-shampoo-per-hair-type rule.",
    category: 'Shampoos & Conditioners',
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 6: PRODUCT CHEMISTRY & INGREDIENTS (12 cards)
  // ==========================================
  {
    id: 'fc-7-051',
    chapter_id: 'ch-7',
    front: "What does USP refer to in cosmetic-ingredient terminology?",
    back: "USP refers to the United States Pharmacopeia, a standards source for the identity, strength, quality, and purity of certain ingredients and preparations.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-7-052',
    chapter_id: 'ch-7',
    front: "What role does hydrogen peroxide play in hair chemistry?",
    back: "Hydrogen peroxide acts as an oxidizing agent in services such as oxidation haircolor and lightening. Its concentration and use must match the specific professional product and manufacturer directions.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-7-053',
    chapter_id: 'ch-7',
    front: "What is glycerin used for in cosmetic products?",
    back: "Glycerin is a humectant used in many hair and skin preparations to help attract and retain moisture.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-7-054',
    chapter_id: 'ch-7',
    front: "What is petrolatum used for in barbering preparations?",
    back: "Petrolatum is an oily, protective ingredient used in some creams, ointments, pomades, and barrier-type preparations. Its purpose depends on the product formulation.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-7-055',
    chapter_id: 'ch-7',
    front: "Why is ammonia used in some hair products?",
    back: "Ammonia is an alkaline ingredient that raises pH and can help swell the hair and open the cuticle so other service chemicals can act more effectively.",
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-7-056',
    chapter_id: 'ch-7',
    front: "What are alkanolamines used for in cosmetic products?",
    back: "Alkanolamines are alkaline ingredients used to adjust pH or neutralize acids in some cosmetic formulations. Their exact role depends on the product.",
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-7-057',
    chapter_id: 'ch-7',
    front: "What is alum used for in barbering products?",
    back: "Alum is an astringent or styptic ingredient associated with helping control minor surface bleeding. Its use should follow the product directions and applicable infection-control rules.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-7-058',
    chapter_id: 'ch-7',
    front: "What are quaternary ammonium compounds?",
    back: "Quaternary ammonium compounds are a class of ingredients used in some professional formulations. Their function and safe use depend on the specific product, concentration, label, and manufacturer directions.",
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-7-059',
    chapter_id: 'ch-7',
    front: "How are alcohols used in cosmetic preparations?",
    back: "Alcohols may be used as solvents and in products such as astringents or other cosmetic preparations. Different alcohols and concentrations behave differently, so follow the product label rather than relying on one universal concentration rule.",
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-7-060',
    chapter_id: 'ch-7',
    front: "Why should ingredients with significant inhalation or exposure hazards be handled cautiously?",
    back: "Some cosmetic ingredients can present meaningful exposure risks. Use the product label, SDS when applicable, ventilation guidance, and manufacturer directions to control exposure rather than relying on memory alone.",
    category: 'Product Chemistry',
    difficulty: 'medium',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-7-061',
    chapter_id: 'ch-7',
    front: "What do silicones do in some hair products?",
    back: "Silicones are film-forming ingredients used in some conditioners and styling products to improve feel, shine, smoothness, and manageability. Effects vary by formula.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-7-062',
    chapter_id: 'ch-7',
    front: "What is witch hazel used for in barbering preparations?",
    back: "Witch hazel is used as an astringent in some skin preparations, toners, and aftershave products.",
    category: 'Product Chemistry',
    difficulty: 'easy',
    order_index: 62,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 7: SAFETY & SDS (8 cards)
  // ==========================================
  {
    id: 'fc-7-063',
    chapter_id: 'ch-7',
    front: "What is the purpose of a Safety Data Sheet (SDS)?",
    back: "An SDS provides standardized hazard, handling, storage, exposure-control, first-aid, and emergency information for a chemical product. Use it when a product is covered by workplace hazard-communication requirements.",
    category: 'Safety & SDS',
    difficulty: 'medium',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-7-064',
    chapter_id: 'ch-7',
    front: "What kind of information is organized in an SDS?",
    back: "An SDS organizes information such as product identification, hazards, composition, first aid, fire response, accidental release, handling and storage, exposure controls, physical and chemical properties, stability, and toxicology.",
    category: 'Safety & SDS',
    difficulty: 'hard',
    order_index: 64,
    is_active: true,
  },
  {
    id: 'fc-7-065',
    chapter_id: 'ch-7',
    front: "Why should incompatible chemicals not be mixed?",
    back: "Some chemical combinations can create dangerous reactions or harmful vapors. Never combine products unless the label or manufacturer directions specifically permit it.",
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-7-066',
    chapter_id: 'ch-7',
    front: "How should a barber handle pre-service testing for a chemical product?",
    back: "Check the product label, manufacturer directions, and applicable rules for the required test and timing. Predisposition, strand, or other pre-service tests are product- and service-specific, so do not use one universal method for every chemical service.",
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-7-067',
    chapter_id: 'ch-7',
    front: "How should PPE be selected for chemical services?",
    back: "Choose gloves, eye protection, protective clothing, and other PPE according to the product label, SDS when applicable, and the specific service being performed.",
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-7-068',
    chapter_id: 'ch-7',
    front: "What should you do after chemical exposure to the eye?",
    back: "Begin flushing the eye with clean water immediately and follow the product label or SDS emergency directions. Do not try to neutralize the exposure with another chemical.",
    category: 'Safety & SDS',
    difficulty: 'medium',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-7-069',
    chapter_id: 'ch-7',
    front: "Why is ventilation important around chemical products?",
    back: "Ventilation helps reduce the buildup of vapors and airborne chemical exposure. Follow the product label, SDS, and workplace ventilation requirements for the service.",
    category: 'Safety & SDS',
    difficulty: 'easy',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-7-070',
    chapter_id: 'ch-7',
    front: "What should you check on a professional product label before use?",
    back: "Confirm the product identity, intended use, directions, warnings or precautions, and any required preparation or testing information. Do not assume every professional product must display the same optional details such as pH or an expiration date.",
    category: 'Safety & SDS',
    difficulty: 'medium',
    order_index: 70,
    is_active: true,
  },

  // ==========================================
  // CATEGORY 8: BOARD EXAM ALERTS (10 cards)
  // ==========================================
  {
    id: 'fc-7-071',
    chapter_id: 'ch-7',
    front: "What are the three common states of matter?",
    back: "Solid, liquid, and gas. A change from one state to another can be a physical change when the chemical identity remains the same.",
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 71,
    is_active: true,
  },
  {
    id: 'fc-7-072',
    chapter_id: 'ch-7',
    front: "How can chemical compounds be grouped in basic chemistry?",
    back: "Chapter 7 discusses compound groups such as oxides, acids, alkalis or bases, and salts. The important skill is recognizing how each group behaves rather than memorizing the list without context.",
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 72,
    is_active: true,
  },
  {
    id: 'fc-7-073',
    chapter_id: 'ch-7',
    front: "What does the formula H₂O tell you about water?",
    back: "H₂O shows that each water molecule contains two hydrogen atoms and one oxygen atom. Water is central to solution, pH, and product-chemistry concepts.",
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 73,
    is_active: true,
  },
  {
    id: 'fc-7-074',
    chapter_id: 'ch-7',
    front: "What happens in acid-alkali neutralization?",
    back: "An acid and alkali react to form water and a salt. This chemistry is different from permanent-wave oxidation neutralization, so identify the actual reaction used by the service before choosing a neutralizing step.",
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 74,
    is_active: true,
  },
  {
    id: 'fc-7-075',
    chapter_id: 'ch-7',
    front: "Why do alkaline conditions matter in some chemical hair services?",
    back: "Alkaline conditions can swell the hair and increase porosity by opening the cuticle, which can help certain service chemicals penetrate. The required pH depends on the product system.",
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 75,
    is_active: true,
  },
  {
    id: 'fc-7-076',
    chapter_id: 'ch-7',
    front: "How can temporary and oxidation haircolor differ chemically?",
    back: "Temporary color can produce mainly a physical deposit on or near the hair surface, while oxidation haircolor relies on a chemical oxidation reaction to develop color inside the hair.",
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 76,
    is_active: true,
  },
  {
    id: 'fc-7-077',
    chapter_id: 'ch-7',
    front: "Is one exact pH range ideal for every shampoo?",
    back: "No. Shampoo formulas are selected by purpose, hair or scalp condition, and manufacturer design. pH matters because acidic and alkaline conditions affect hair differently, but one universal “ideal” number should not replace product-specific guidance.",
    category: 'Board Exam Alert',
    difficulty: 'easy',
    order_index: 77,
    is_active: true,
  },
  {
    id: 'fc-7-078',
    chapter_id: 'ch-7',
    front: "What does a chelating ingredient do in a cleansing product?",
    back: "A chelating ingredient binds certain metal or mineral ions so they can be removed more effectively. Chelating or clarifying products may be useful when mineral buildup is actually present.",
    category: 'Board Exam Alert',
    difficulty: 'hard',
    order_index: 78,
    is_active: true,
  },
  {
    id: 'fc-7-079',
    chapter_id: 'ch-7',
    front: "What is the difference between an elemental molecule and a compound?",
    back: "An elemental molecule contains atoms of the same element, such as O₂. A compound contains atoms of different elements combined in definite proportions, such as H₂O.",
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 79,
    is_active: true,
  },
  {
    id: 'fc-7-080',
    chapter_id: 'ch-7',
    front: "What principles should guide chemical storage in a barbershop?",
    back: "Keep products in properly identified containers, follow label and SDS storage directions, protect them from incompatible conditions, and separate incompatible chemicals when required. Storage rules should come from the actual product information.",
    category: 'Board Exam Alert',
    difficulty: 'medium',
    order_index: 80,
    is_active: true,
  },
]
