import { Flashcard } from '@/types'

// Chapter 21: The Business of Barbering — 60 premium flashcards
export const chapter21PremiumFlashcards: Flashcard[] = [
  // ───────────────────────────────────────────────
  // Category: Paths Into Business and Opening Considerations (001–010)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-001',
    standardId: 'CH21-F001',
    chapter_id: 'ch-21',
    front: "What are two broad paths for a barber who wants more business independence?",
    back: "Open or acquire a shop, or use a properly structured booth/chair rental arrangement; the real duties depend on the agreement and working relationship.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch21-002',
    standardId: 'CH21-F002',
    chapter_id: 'ch-21',
    front: "What is one major advantage of owning a barbershop?",
    back: "Greater control over branding, pricing, culture, staffing, and operations, balanced against greater financial and management responsibility.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-ch21-003',
    standardId: 'CH21-F003',
    chapter_id: 'ch-21',
    front: "What is a major financial risk of opening a barbershop?",
    back: "The owner may take on lease, build-out, equipment, payroll, insurance, and slow-period costs that must be covered even when revenue is uncertain.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch21-004',
    standardId: 'CH21-F004',
    chapter_id: 'ch-21',
    front: "Why can booth or chair rental involve less overhead than full shop ownership?",
    back: "A renter may avoid some property, build-out, staffing, and whole-shop costs, but the actual risk and payment terms depend on the agreement and working relationship.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch21-005',
    standardId: 'CH21-F005',
    chapter_id: 'ch-21',
    front: "What trade-offs should a barber evaluate in a booth-rental arrangement?",
    back: "Compare business independence with rent, shop rules, control of pricing/schedule, client records, expenses, insurance, and limits set by the actual agreement.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-ch21-006',
    standardId: 'CH21-F006',
    chapter_id: 'ch-21',
    front: "List three factors to consider when choosing a barbershop location.",
    back: "Visibility, parking, foot traffic, target client proximity, and rent affordability.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch21-007',
    standardId: 'CH21-F007',
    chapter_id: 'ch-21',
    front: "Why should a startup budget include an operating-cash reserve?",
    back: "Revenue may ramp gradually while fixed expenses continue. Estimate the reserve from projected costs, financing, expected revenue, and risk rather than one universal number of months.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-ch21-008',
    standardId: 'CH21-F008',
    chapter_id: 'ch-21',
    front: "What is a staffing model?",
    back: "The planned way a shop structures work and responsibilities, such as employees or properly structured rental arrangements, based on the actual relationship and applicable rules.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch21-009',
    standardId: 'CH21-F009',
    chapter_id: 'ch-21',
    front: "Why does shop culture matter when opening a barbershop?",
    back: "Culture attracts the right clients, keeps barbers engaged, and shapes the daily experience inside the shop.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-ch21-010',
    standardId: 'CH21-F010',
    chapter_id: 'ch-21',
    front: "What should a barber evaluate before moving from rental to shop ownership?",
    back: "Capital, experience, client demand, projected costs, management readiness, financing, legal requirements, and tolerance for long-term business risk.",
    category: "Paths Into Business and Opening Considerations",
    difficulty: 'hard',
    order_index: 10,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Types of Barbershop Ownership (011–020)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-011',
    standardId: 'CH21-F011',
    chapter_id: 'ch-21',
    front: "What is a sole proprietorship?",
    back: "A business owned by one person with no legal separation between the owner and the business.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch21-012',
    standardId: 'CH21-F012',
    chapter_id: 'ch-21',
    front: "What liability issue should a sole proprietor understand?",
    back: "A sole proprietorship generally does not create a separate entity-level liability shield, so business obligations may expose the owner personally depending on the facts and law.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-ch21-013',
    standardId: 'CH21-F013',
    chapter_id: 'ch-21',
    front: "What is a partnership?",
    back: "A business owned by two or more people who share profits, responsibilities, and risks.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch21-014',
    standardId: 'CH21-F014',
    chapter_id: 'ch-21',
    front: "Why is a written agreement important for multiple business owners?",
    back: "It can define contributions, authority, profit/loss allocation, decisions, dispute handling, and exit terms so important expectations are not left to assumptions.",
    category: "Types of Barbershop Ownership",
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch21-015',
    standardId: 'CH21-F015',
    chapter_id: 'ch-21',
    front: "What does LLC stand for?",
    back: "Limited Liability Company.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch21-016',
    standardId: 'CH21-F016',
    chapter_id: 'ch-21',
    front: "Why might a barbershop owner consider an LLC?",
    back: "An LLC may offer limited-liability protection and flexible tax treatment, but protection is not absolute and the best structure depends on the owner's facts and current rules.",
    category: "Types of Barbershop Ownership",
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch21-017',
    standardId: 'CH21-F017',
    chapter_id: 'ch-21',
    front: "How can a corporation differ from an LLC?",
    back: "Corporations use shareholder ownership and formal governance; LLC ownership, governance, tax treatment, filings, and recordkeeping can differ by state and elections.",
    category: "Types of Barbershop Ownership",
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-ch21-018',
    standardId: 'CH21-F018',
    chapter_id: 'ch-21',
    front: "What does double taxation usually mean in a corporate-tax context?",
    back: "It can mean tax at the corporate level and again when certain profits are distributed to shareholders; actual treatment depends on the entity and valid tax elections.",
    category: "Types of Barbershop Ownership",
    difficulty: 'hard',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch21-019',
    standardId: 'CH21-F019',
    chapter_id: 'ch-21',
    front: "What is a franchise arrangement?",
    back: "A contractual business arrangement allowing use of an established brand and system under defined fees, standards, disclosures, and operating requirements.",
    category: "Types of Barbershop Ownership",
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch21-020',
    standardId: 'CH21-F020',
    chapter_id: 'ch-21',
    front: "What trade-offs should a prospective franchisee evaluate?",
    back: "Brand recognition and support may come with fees, operating standards, contract limits, disclosure requirements, and less control; the actual franchise agreement governs.",
    category: "Types of Barbershop Ownership",
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Business Plan Components (021–030)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-021',
    standardId: 'CH21-F021',
    chapter_id: 'ch-21',
    front: "What is a business plan?",
    back: "A written document that describes the business, market, operations, and financial projections.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch21-022',
    standardId: 'CH21-F022',
    chapter_id: 'ch-21',
    front: "Why is a business plan important even if you do not need a loan?",
    back: "It forces you to answer hard questions and think through location, costs, clients, and operations before spending money.",
    category: "Business Plan Components",
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch21-023',
    standardId: 'CH21-F023',
    chapter_id: 'ch-21',
    front: "What is the purpose of the executive summary?",
    back: "To provide a one-page overview of the business concept, market, ownership, and goals.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch21-024',
    standardId: 'CH21-F024',
    chapter_id: 'ch-21',
    front: "What should the business description include?",
    back: "Services offered, what makes the shop different, mission, vision, and guiding values.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-ch21-025',
    standardId: 'CH21-F025',
    chapter_id: 'ch-21',
    front: "What is market analysis?",
    back: "Research on competitors, target clients, pricing, and gaps the business can fill in the local market.",
    category: "Business Plan Components",
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch21-026',
    standardId: 'CH21-F026',
    chapter_id: 'ch-21',
    front: "What belongs in the organization and management section?",
    back: "Ownership structure, key people, their roles, experience, and the staffing plan.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch21-027',
    standardId: 'CH21-F027',
    chapter_id: 'ch-21',
    front: "What should the services and pricing section explain?",
    back: "The menu of services, prices, and the pricing strategy compared to competitors.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch21-028',
    standardId: 'CH21-F028',
    chapter_id: 'ch-21',
    front: "What belongs in the marketing and sales strategy?",
    back: "Target client, brand identity, advertising channels, referral programs, and grand-opening plans.",
    category: "Business Plan Components",
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-ch21-029',
    standardId: 'CH21-F029',
    chapter_id: 'ch-21',
    front: "What are financial projections?",
    back: "Startup budget, projected income, cash-flow forecast, and break-even analysis.",
    category: "Business Plan Components",
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-ch21-030',
    standardId: 'CH21-F030',
    chapter_id: 'ch-21',
    front: "Why should financial projections use realistic assumptions?",
    back: "Overly optimistic forecasts can hide cash needs and business risk. Document assumptions, test ranges, and update projections as real results become available.",
    category: "Business Plan Components",
    difficulty: 'hard',
    order_index: 30,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Record Keeping and Booth Rental (031–040)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-031',
    standardId: 'CH21-F031',
    chapter_id: 'ch-21',
    front: "Why is record keeping important for a barber business?",
    back: "Reliable records support tax and legal reporting, cash-flow decisions, financing applications, client service, and documentation when questions or disputes arise.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch21-032',
    standardId: 'CH21-F032',
    chapter_id: 'ch-21',
    front: "What kinds of financial records may a barber need to keep?",
    back: "Examples include service revenue, tips, product sales, rent, supplies, utilities, insurance, taxes, bank records, receipts, and other supporting documents required for the business.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch21-033',
    standardId: 'CH21-F033',
    chapter_id: 'ch-21',
    front: "What principle should guide client recordkeeping?",
    back: "Keep only information needed for legitimate service or business purposes, protect access, and follow applicable privacy/security requirements for contact details, history, formulas, and notes.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch21-034',
    standardId: 'CH21-F034',
    chapter_id: 'ch-21',
    front: "How should cash payments be treated for income reporting?",
    back: "Cash is not automatically exempt from tax or reporting. Track taxable income accurately and follow current federal, state, and local requirements for the actual business arrangement.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-ch21-035',
    standardId: 'CH21-F035',
    chapter_id: 'ch-21',
    front: "What business performance metrics can records reveal?",
    back: "Average ticket, client retention, retail sales per service, no-show rate, and profit margin.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-ch21-036',
    standardId: 'CH21-F036',
    chapter_id: 'ch-21',
    front: "How should tax responsibility be determined in a booth-rental arrangement?",
    back: "Use the actual worker classification, business structure, agreement, income, withholding, and current tax rules; the booth-renter label alone does not determine tax treatment.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch21-037',
    standardId: 'CH21-F037',
    chapter_id: 'ch-21',
    front: "Should a booth renter use one fixed percentage to plan for taxes?",
    back: "No. Estimated tax needs vary with income, deductions, structure, withholding, state rules, and other facts; use current guidance or a qualified tax professional.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch21-038',
    standardId: 'CH21-F038',
    chapter_id: 'ch-21',
    front: "What expenses should a booth renter verify in the rental agreement?",
    back: "Confirm responsibility for rent, insurance, tools, products, linens, sanitation supplies, utilities, software, merchant fees, and other operating costs rather than assuming a universal list.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'easy',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch21-039',
    standardId: 'CH21-F039',
    chapter_id: 'ch-21',
    front: "Why should a barber read a booth-rental agreement carefully?",
    back: "It should clarify payment terms, included services, insurance, supplies, client records, scheduling/pricing rights, termination, and shop rules; compare it with the actual working relationship.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-ch21-040',
    standardId: 'CH21-F040',
    chapter_id: 'ch-21',
    front: "Why can a personal client base matter in a rental arrangement?",
    back: "Depending on the agreement and shop model, the renter may be responsible for generating enough business to cover rent and other expenses rather than relying on shop-provided demand.",
    category: "Record Keeping and Booth Rental",
    difficulty: 'medium',
    order_index: 40,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Successful Barbershop Operations (041–050)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-041',
    standardId: 'CH21-F041',
    chapter_id: 'ch-21',
    front: "What is one sign of a well-run barbershop schedule?",
    back: "Clients can book easily, receive reminders, and experience minimal wait times or no-shows.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch21-042',
    standardId: 'CH21-F042',
    chapter_id: 'ch-21',
    front: "Why does cleanliness matter operationally in a barbershop?",
    back: "Cleanliness supports professionalism and client confidence; actual infection-control and sanitation procedures must follow the dedicated safety curriculum and current board/legal requirements.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-ch21-043',
    standardId: 'CH21-F043',
    chapter_id: 'ch-21',
    front: "How does strong customer service build a successful shop?",
    back: "It turns one-time clients into regulars who return, spend more, and refer others.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch21-044',
    standardId: 'CH21-F044',
    chapter_id: 'ch-21',
    front: "Why should roles and accountability be clearly defined in a shop?",
    back: "Ambiguity leads to missed tasks, conflict, and inconsistent client experiences.",
    category: "Successful Barbershop Operations",
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch21-045',
    standardId: 'CH21-F045',
    chapter_id: 'ch-21',
    front: "How can appropriate retail and add-on services affect revenue?",
    back: "When lawful, suitable, and honestly recommended, they can increase revenue per visit without relying only on the base service price.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch21-046',
    standardId: 'CH21-F046',
    chapter_id: 'ch-21',
    front: "What does financial discipline mean for a shop owner?",
    back: "Watching key numbers such as rent-to-revenue ratio, labor costs, retail margins, and cash flow rather than spending based on how busy the shop feels.",
    category: "Successful Barbershop Operations",
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch21-047',
    standardId: 'CH21-F047',
    chapter_id: 'ch-21',
    front: "Why is positive shop culture important?",
    back: "Clients feel the energy; drama and negativity drive away both clients and talented barbers.",
    category: "Successful Barbershop Operations",
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch21-048',
    standardId: 'CH21-F048',
    chapter_id: 'ch-21',
    front: "What is the relationship between operations and client retention?",
    back: "Smooth operations create reliable, pleasant experiences that make clients want to return.",
    category: "Successful Barbershop Operations",
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-ch21-049',
    standardId: 'CH21-F049',
    chapter_id: 'ch-21',
    front: "What should a shop owner do when certain days are consistently slow?",
    back: "Review demand, rebooking, staffing, pricing, and campaign data, then test targeted changes such as compliant promotions or reminders instead of assuming one tactic will work.",
    category: "Successful Barbershop Operations",
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch21-050',
    standardId: 'CH21-F050',
    chapter_id: 'ch-21',
    front: "Why is it risky to spend money just because the shop appears busy?",
    back: "Busy days do not always equal profit; cash flow, expenses, and margins determine actual financial health.",
    category: "Successful Barbershop Operations",
    difficulty: 'hard',
    order_index: 50,
    is_active: true,
  },

  // ───────────────────────────────────────────────
  // Category: Advertising and Business Growth (051–060)
  // ───────────────────────────────────────────────
  {
    id: 'fc-ch21-051',
    standardId: 'CH21-F051',
    chapter_id: 'ch-21',
    front: "Why is advertising vital for a barbershop?",
    back: "It builds awareness, attracts ideal clients, reminds current clients to return, and differentiates the shop from competitors.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-ch21-052',
    standardId: 'CH21-F052',
    chapter_id: 'ch-21',
    front: "What happens if a skilled barber does not advertise?",
    back: "Potential clients may never know the barber exists, no matter how talented they are.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-ch21-053',
    standardId: 'CH21-F053',
    chapter_id: 'ch-21',
    front: "What is a target market?",
    back: "The specific group of clients a business aims to attract through its services, pricing, and messaging.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-ch21-054',
    standardId: 'CH21-F054',
    chapter_id: 'ch-21',
    front: "What are examples of advertising channels a barbershop might evaluate?",
    back: "Examples include social media, local search listings, flyers, referral cards, email/text outreach, partnerships, and community sponsorships, subject to consent and applicable rules.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-ch21-055',
    standardId: 'CH21-F055',
    chapter_id: 'ch-21',
    front: "Why can consistency matter in advertising?",
    back: "A consistent, measurable presence can improve recognition, but quality, accuracy, audience fit, consent, and results matter too; there is no rule that frequency always beats quality.",
    category: "Advertising and Business Growth",
    difficulty: 'medium',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-ch21-056',
    standardId: 'CH21-F056',
    chapter_id: 'ch-21',
    front: "Why can authentic reviews and referrals help marketing?",
    back: "They can add social proof from real experiences, but testimonials should be genuine, not misleading, and used in line with platform, advertising, and incentive-disclosure rules.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-ch21-057',
    standardId: 'CH21-F057',
    chapter_id: 'ch-21',
    front: "What should a barber verify before using an identifiable client photo in marketing?",
    back: "Obtain clear permission using the form required by applicable law or policy, and follow privacy, advertising, platform, school, and shop rules before posting.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-ch21-058',
    standardId: 'CH21-F058',
    chapter_id: 'ch-21',
    front: "How can nearby-business partnerships support marketing?",
    back: "An ethical, mutually understood cross-promotion can introduce the shop to a relevant audience; disclose important terms and follow applicable advertising/referral rules.",
    category: "Advertising and Business Growth",
    difficulty: 'medium',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-ch21-059',
    standardId: 'CH21-F059',
    chapter_id: 'ch-21',
    front: "What is a practical first step for a new barber planning online advertising?",
    back: "Choose a channel that matches the target client, define a truthful message and measurable goal, confirm consent/rules, then test results before expanding.",
    category: "Advertising and Business Growth",
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-ch21-060',
    standardId: 'CH21-F060',
    chapter_id: 'ch-21',
    front: "How can rebooking support business growth?",
    back: "Rebooking can improve retention and schedule predictability when it fits the client's needs, but it does not guarantee a full book or replace broader marketing and service quality.",
    category: "Advertising and Business Growth",
    difficulty: 'easy',
    order_index: 60,
    is_active: true,
  },
]
