import { Flashcard } from '@/types'

// Chapter 15: Men's Hair Replacement
// Created strictly from Chapter 15 textbook images and premium curriculum
// All content sourced from: textbook-images/chapter-15/ and chapter-15-premium.ts

export const chapter15PremiumFlashcards: Flashcard[] = [
  // === INTRODUCTION & MARKET ===
  {
    id: 'fc-ch15-001',
    chapter_id: 'ch-15',
    front: 'Why should barbers study men\'s hair replacement?',
    back: 'Hair replacement is a specialized barbering service that combines consultation, fitting, customization, maintenance, and long-term client care.',
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch15-002',
    chapter_id: 'ch-15',
    front: 'What is the primary psychological benefit clients seek from hair replacement?',
    back: 'Clients are not buying hair — they are buying the man they used to see in the mirror. The barber\'s job is to deliver that reflection with honesty, skill, and care.',
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },

  // === HISTORY & TERMINOLOGY ===
  {
    id: 'fc-ch15-003',
    chapter_id: 'ch-15',
    front: 'What is the historical origin of the term "toupee"?',
    back: 'The foretop — a section of natural hair grown long to blend with a wig — evolved into the toupee of the 18th century. The term originally described the blending section, not the wig itself.',
    category: 'History',
    difficulty: 'medium',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch15-004',
    chapter_id: 'ch-15',
    front: 'What modern professional terms are used for nonsurgical hair replacement?',
    back: '“Hair replacement system” and “hair solution” are modern professional terms for nonsurgical hair replacement products and services.',
    category: 'Terminology',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch15-005',
    chapter_id: 'ch-15',
    front: 'Why should the term "toupee" be avoided in client consultations?',
    back: 'It carries stigma from outdated technology and obvious appearance. Modern clients may react negatively to a term associated with unnatural, detectable hairpieces.',
    category: 'Terminology',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },

  // === CONSULTATION ===
  {
    id: 'fc-ch15-006',
    chapter_id: 'ch-15',
    front: 'Where should hair replacement consultations take place?',
    back: 'Use a setting that protects the client’s privacy and dignity, such as a private room or another discreet area where sensitive details cannot be overheard.',
    category: 'Consultation',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch15-007',
    chapter_id: 'ch-15',
    front: 'What does the LAB MED framework stand for in hair replacement consultations?',
    back: 'Lifestyle, Age, Budget, Medical history, Expectations, Daily maintenance. These six factors guide every professional consultation.',
    category: 'Consultation',
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-ch15-008',
    chapter_id: 'ch-15',
    front: 'Why is age an important factor in hair replacement consultation?',
    back: 'Younger clients may want gradual transitions; older clients often prefer conservative styles. Dark, opaque colors look artificial on older clients — salt-and-pepper blends look more natural.',
    category: 'Consultation',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch15-009',
    chapter_id: 'ch-15',
    front: 'What is the professional obligation when a client requests an unrealistic style?',
    back: 'Educate with respect and recommend a more appropriate option. Giving an unrealistic system damages your reputation and the client\'s dignity. Never promise what you cannot deliver.',
    category: 'Consultation',
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },

  // === MARKETING & ETHICS ===
  {
    id: 'fc-ch15-010',
    chapter_id: 'ch-15',
    front: 'What are the most effective marketing channels for hair replacement services?',
    back: 'Social media (before-and-after photos with model releases), in-shop displays of sample systems, personal referrals from satisfied clients, and print advertising. A barber who wears a system becomes a walking advertisement.',
    category: 'Marketing',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-ch15-011',
    chapter_id: 'ch-15',
    front: 'What permission is needed before using client photos?',
    back: 'Use client photos only with documented permission that meets applicable privacy, advertising, and recordkeeping requirements. Personal relationships do not replace consent.',
    category: 'Marketing',
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch15-012',
    chapter_id: 'ch-15',
    front: 'How should sample systems be maintained in the shop?',
    back: 'Shampoo after every client who tries it on. Style it fresh. Replace when it shows wear. The sample is a silent salesperson — treat it accordingly.',
    category: 'Marketing',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },

  // === ALTERNATIVE TREATMENTS ===
  {
    id: 'fc-ch15-013',
    chapter_id: 'ch-15',
    front: 'What nonsurgical hair-loss options may a barber discuss generally?',
    back: 'Examples include cosmetic cover-up fibers and medication-based options such as Minoxidil and Finasteride. Medication suitability belongs with verified labeling and a licensed healthcare professional.',
    category: 'Alternatives',
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch15-014',
    chapter_id: 'ch-15',
    front: 'What should a barber know about different Minoxidil formulations?',
    back: 'Minoxidil products differ in formulation, strength, directions, and approved use. Do not choose a formulation or dosing schedule for a client; refer to labeling and a licensed healthcare professional.',
    category: 'Alternatives',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch15-015',
    chapter_id: 'ch-15',
    front: 'What is the barber’s role when a client asks about Finasteride?',
    back: 'Finasteride is a prescription medication. Benefits, risks, contraindications, and individualized use are medical questions for an appropriate licensed healthcare professional.',
    category: 'Alternatives',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch15-016',
    chapter_id: 'ch-15',
    front: 'What are the three main surgical hair restoration procedures?',
    back: 'Hair transplantation (follicles moved from donor areas), scalp reduction (bald scalp surgically removed and surrounding scalp pulled together), and flap surgery (hair-bearing skin flap repositioned).',
    category: 'Alternatives',
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch15-017',
    chapter_id: 'ch-15',
    front: 'What is a micrograft in hair transplantation?',
    back: 'A small follicular graft used in hair transplantation. Technique, candidacy, risks, and expected durability are medical matters for an appropriately licensed clinician.',
    category: 'Alternatives',
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },

  // === SCOPE OF PRACTICE ===
  {
    id: 'fc-ch15-018',
    chapter_id: 'ch-15',
    front: 'What cosmetic hair-replacement services may fall within a barber’s role?',
    back: 'Services may include measuring, fitting, cutting, styling, cleaning, and maintaining systems, but permitted scope varies by jurisdiction. Refer medical questions appropriately.',
    category: 'Scope of Practice',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch15-019',
    chapter_id: 'ch-15',
    front: 'What professional boundary should barbers maintain around medical hair-loss care?',
    back: 'Keep cosmetic hair-replacement services separate from diagnosis, prescribing, surgery, and individualized medication advice, and verify the scope rules where you practice.',
    category: 'Scope of Practice',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch15-020',
    chapter_id: 'ch-15',
    front: 'How should a barber answer a client asking which Minoxidil formulation to use?',
    back: 'Explain that formulations differ and refer the client to verified product labeling and an appropriate licensed healthcare professional for individualized guidance.',
    category: 'Scope of Practice',
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },

  // === HAIR MATERIALS ===
  {
    id: 'fc-ch15-021',
    chapter_id: 'ch-15',
    front: 'What are the three main types of hair used in replacement systems?',
    back: 'Human hair, synthetic hair, and mixed hair (human blended with synthetic or animal fibers).',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch15-022',
    chapter_id: 'ch-15',
    front: 'What are the advantages of human hair in replacement systems?',
    back: 'Human hair can provide a natural look and texture. Chemical and heat services depend on the system’s fiber, base, prior processing, and manufacturer instructions.',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch15-023',
    chapter_id: 'ch-15',
    front: 'What are the disadvantages of human hair in replacement systems?',
    back: 'Reacts to humidity and temperature; fades with sun exposure; requires regular styling; can become damaged like natural hair.',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch15-024',
    chapter_id: 'ch-15',
    front: 'What is Kanekalon?',
    back: 'A synthetic fiber commonly used in ready-to-wear wigs and hair systems. Styling, heat, and chemical-care limits depend on the specific product and manufacturer guidance.',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-ch15-025',
    chapter_id: 'ch-15',
    front: 'What are the disadvantages of synthetic hair?',
    back: 'High gloss makes it more noticeable; mats and tangles when blended with human hair; limited chemical processing options.',
    category: 'Materials',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch15-026',
    chapter_id: 'ch-15',
    front: 'What is mixed hair and what fibers may it contain?',
    back: 'Human hair blended with synthetic or animal fibers — horse, yak, angora, or sheep\'s wool. Angora provides finer texture for natural front hairlines.',
    category: 'Materials',
    difficulty: 'medium',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch15-027',
    chapter_id: 'ch-15',
    front: 'What should be considered when a mixed-hair system contains animal-derived fibers?',
    back: 'Verify fiber composition when a client reports an allergy or sensitivity, and avoid materials that may trigger a reaction.',
    category: 'Materials',
    difficulty: 'medium',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch15-028',
    chapter_id: 'ch-15',
    front: 'What is root-turning and why is it important?',
    back: 'Sorting hair so the cuticle points toward the ends in natural growth direction. Root-turned hair prevents tangling and matting because cuticles flow correctly.',
    category: 'Materials',
    difficulty: 'medium',
    order_index: 28,
    is_active: true,
  },

  // === BASE CONSTRUCTION ===
  {
    id: 'fc-ch15-029',
    chapter_id: 'ch-15',
    front: 'What are five common base constructions for hair replacement systems?',
    back: 'Mesh/net, polyurethane, lace, thin skin/onion skin, and combination constructions. They differ in breathability, durability, edge visibility, and attachment compatibility.',
    category: 'Base Construction',
    difficulty: 'easy',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-ch15-030',
    chapter_id: 'ch-15',
    front: 'What is the memory anchor for remembering base materials?',
    back: '"My Nylon Socks Pull Lace Tight" — Mesh, Nylon (polyurethane), Socks (thin skin), Pull (polyurethane), Lace, Tight (thin skin).',
    category: 'Base Construction',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-ch15-031',
    chapter_id: 'ch-15',
    front: 'What is a practical advantage of mesh/net bases?',
    back: 'Open-weave mesh/net construction can improve airflow and comfort. Durability, stretch, and wear characteristics vary by material and system design.',
    category: 'Base Construction',
    difficulty: 'easy',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch15-032',
    chapter_id: 'ch-15',
    front: 'What is a practical advantage of polyurethane bases?',
    back: 'Polyurethane can provide a durable, low-porosity attachment surface. Breathability, water resistance, and adhesive compatibility depend on the specific base and manufacturer.',
    category: 'Base Construction',
    difficulty: 'easy',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch15-033',
    chapter_id: 'ch-15',
    front: 'What is the key handling rule for lace-front systems?',
    back: 'Lace is delicate and can be damaged by aggressive attachment or removal. Use only the tape, adhesive placement, and removal method approved for that specific system.',
    category: 'Base Construction',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch15-034',
    chapter_id: 'ch-15',
    front: 'Why are combination bases used in hair replacement systems?',
    back: 'They combine materials in selected zones to balance characteristics such as edge appearance, attachment compatibility, airflow, and durability.',
    category: 'Base Construction',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },

  // === KNOTTING METHODS ===
  {
    id: 'fc-ch15-035',
    chapter_id: 'ch-15',
    front: 'What are four hair-attachment methods used in base construction?',
    back: 'Single knot, double knot, V-loop, and single-hair injection. Their appearance and durability depend on the base and construction method.',
    category: 'Base Construction',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },

  // === STOCK VS CUSTOM ===
  {
    id: 'fc-ch15-036',
    chapter_id: 'ch-15',
    front: 'What is the difference between stock and custom hair replacement systems?',
    back: 'Stock systems come in standard sizes and colors and can be customized after fitting. Custom systems use client-specific measurements or templates for a more individualized fit and usually require more time and cost.',
    category: 'System Types',
    difficulty: 'easy',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch15-037',
    chapter_id: 'ch-15',
    front: 'When is a stock system the best choice for a client?',
    back: 'When the client has a common head shape, standard color needs, a limited budget, or needs the system quickly. Stock systems can be customized with cutting and styling.',
    category: 'System Types',
    difficulty: 'easy',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch15-038',
    chapter_id: 'ch-15',
    front: 'What is a plaster mold used for in custom hair replacement?',
    back: 'A three-dimensional head form used to capture contour information for custom fabrication. How a manufacturer converts and stores that form depends on its ordering process.',
    category: 'System Types',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch15-039',
    chapter_id: 'ch-15',
    front: 'Why should color samples be taken from multiple areas of the client\'s head?',
    back: 'Hair color varies across the scalp. Samples from the crown, temple, side, and back ensure accurate color matching — especially critical for natural-looking gray blending at the system edges.',
    category: 'System Types',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },

  // === SUPPLIES & MEASUREMENT ===
  {
    id: 'fc-ch15-040',
    chapter_id: 'ch-15',
    front: 'How are hair replacement system sizes measured?',
    back: 'In inches — length by width. A 6x4 piece means six inches front-to-back and four inches side-to-side. The larger number typically refers to length unless the manufacturer specifies otherwise.',
    category: 'Measurement',
    difficulty: 'easy',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-ch15-041',
    chapter_id: 'ch-15',
    front: 'What is the purpose of a template in custom system creation?',
    back: 'A pattern of the client\'s bald area created with plastic wrap and tape, marked with a grease pencil. It becomes the manufacturer\'s blueprint for cutting the base to exact specifications.',
    category: 'Measurement',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch15-042',
    chapter_id: 'ch-15',
    front: 'What product-selection rule applies to hair replacement adhesives, removers, and cleaners?',
    back: 'Use products compatible with the specific system and follow manufacturer instructions for adhesives, removers, cleaners, and solvents.',
    category: 'Supplies',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },

  // === ATTACHMENT METHODS ===
  {
    id: 'fc-ch15-043',
    chapter_id: 'ch-15',
    front: 'What are the five main attachment methods for hair replacement systems?',
    back: 'Full head bonding (copolymer adhesive across entire scalp), tape attachment (double-sided tape at perimeter), lace-front bonding (adhesive to skin, not lace), spirit gum (for facial hair), and full wig with elastic bands.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch15-044',
    chapter_id: 'ch-15',
    front: 'What is the BLF-F memory anchor for attachment methods?',
    back: 'Bonding, Lace-front, Facial, Full wigs — plus Tape. Think "Bluff" with an extra T for Tape.',
    category: 'Attachment',
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch15-045',
    chapter_id: 'ch-15',
    front: 'What is full-head bonding?',
    back: 'Bonding uses an adhesive system across the intended scalp contact area. Security, water exposure, wear duration, cure time, and removal depend on the specific system and adhesive manufacturer.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch15-046',
    chapter_id: 'ch-15',
    front: 'What determines cure time after a bonded hair system is applied?',
    back: 'Follow the adhesive manufacturer’s cure and water-exposure instructions before shampooing, swimming, heavy sweating, or wetting the attachment area. A fixed 24–48-hour rule is not universal.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch15-047',
    chapter_id: 'ch-15',
    front: 'What is the main advantage of tape attachment over full bonding?',
    back: 'Easier to remove and reattach. Good for clients who take their systems off daily. Less secure than full bonding and may lift at edges during heavy activity.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch15-048',
    chapter_id: 'ch-15',
    front: 'How is spirit gum used for facial hair pieces?',
    back: 'Use spirit gum only when appropriate for the specific piece and follow the adhesive manufacturer’s directions for skin preparation, tack time, placement, and removal without force.',
    category: 'Attachment',
    difficulty: 'easy',
    order_index: 48,
    is_active: true,
  },

  // === CLEANING & MAINTENANCE ===
  {
    id: 'fc-ch15-049',
    chapter_id: 'ch-15',
    front: 'What is a safer way to remember the COOL care rules?',
    back: 'C — Clean with the approved cleaner. O — Observe water-temperature guidance. O — Observe the approved drying method. L — Let manufacturer care instructions guide cleaning and drying.',
    category: 'Maintenance',
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch15-050',
    chapter_id: 'ch-15',
    front: 'What water-temperature rule applies to synthetic systems?',
    back: 'The source cautions against hot water on synthetic systems, but the exact approved temperature range should follow the specific fiber and manufacturer guidance.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 50,
    is_active: true,
  },
  {
    id: 'fc-ch15-051',
    chapter_id: 'ch-15',
    front: 'What cleaning products should be used on human-hair systems?',
    back: 'Use cleaners and conditioners approved for the specific human-hair system. Avoid unverified solvents or chemicals that the manufacturer does not support.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-ch15-052',
    chapter_id: 'ch-15',
    front: 'What maintenance interval does the Chapter 15 source use as a study baseline?',
    back: 'The source uses an initial cleaning around one week and then about every 3–4 weeks as a study baseline. Actual timing should follow manufacturer guidance and the client’s wear conditions.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-ch15-053',
    chapter_id: 'ch-15',
    front: 'When can a backup or rotation hair system be useful?',
    back: 'A backup can help when cleaning, drying, repair, or service would otherwise leave the client without a wearable system. It is an option, not a universal requirement.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-ch15-054',
    chapter_id: 'ch-15',
    front: 'What is the goal when storing a hair replacement system?',
    back: 'Preserve the system’s shape, base, and hair during storage. Use the support and storage method recommended for that specific system.',
    category: 'Maintenance',
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },

  // === CHEMICAL SERVICES ON SYSTEMS ===
  {
    id: 'fc-ch15-055',
    chapter_id: 'ch-15',
    front: 'What is the floating technique for perming approved hair systems?',
    back: 'For systems specifically approved for permanent waving, the source describes supporting rods with roller picks so they do not rest directly on the base.',
    category: 'Chemical Services',
    difficulty: 'medium',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-ch15-056',
    chapter_id: 'ch-15',
    front: 'What determines whether a chemical service is appropriate for a hair replacement system?',
    back: 'Fiber type, base construction, prior processing, and manufacturer approval determine whether a chemical service is appropriate. Do not assume natural-hair chemical procedures are safe for a system.',
    category: 'Chemical Services',
    difficulty: 'easy',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-ch15-057',
    chapter_id: 'ch-15',
    front: 'What is the memory anchor for floating perm rods?',
    back: '"Hovering Helicopters" — the rod is the helicopter, the base is the landing pad, and the roller picks are the landing gear. The helicopter hovers above the pad to avoid crushing it.',
    category: 'Chemical Services',
    difficulty: 'medium',
    order_index: 57,
    is_active: true,
  },

  // === CUTTING & BLENDING ===
  {
    id: 'fc-ch15-058',
    chapter_id: 'ch-15',
    front: 'What is the key principle for making a hair replacement system undetectable?',
    back: 'Blending. The transition between system hair and natural hair must be invisible. You are not just cutting hair — you are erasing the boundary between artificial and natural.',
    category: 'Cutting',
    difficulty: 'easy',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-ch15-059',
    chapter_id: 'ch-15',
    front: 'How is the top section of a system cut?',
    back: 'At 90-degree elevation using clipper-over-comb or fingers-and-shear. Work forward from crown to forehead, blending with shears to create seamless transitions.',
    category: 'Cutting',
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-ch15-060',
    chapter_id: 'ch-15',
    front: 'What is slide cutting and why is it essential for blending?',
    back: 'The shear slides through hair at an angle instead of cutting straight across. This creates a feathered, tapered edge that disappears into the client\'s natural hair. Practice until the motion feels automatic.',
    category: 'Cutting',
    difficulty: 'medium',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-ch15-061',
    chapter_id: 'ch-15',
    front: 'What is the golden rule when customizing stock systems?',
    back: 'Be conservative — you can always cut more, but you cannot put hair back. Remove excess length gradually, taper sides to match natural hairlines, and thin heavy areas with narrow partings.',
    category: 'Cutting',
    difficulty: 'easy',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-ch15-062',
    chapter_id: 'ch-15',
    front: 'Why should thinning shears be used with narrow partings near the base?',
    back: 'Wide partings create visible gaps that ruin the finished appearance. Narrow partings allow controlled bulk removal without creating holes in the blend.',
    category: 'Cutting',
    difficulty: 'medium',
    order_index: 62,
    is_active: true,
  },

  // === KNOWLEDGE TRAPS ===
  {
    id: 'fc-ch15-063',
    chapter_id: 'ch-15',
    front: 'Knowledge Trap: Should a barber tell a client which prescription hair-loss medication to use?',
    back: 'No. A barber should not choose or direct prescription medication use. Refer individualized medication questions to an appropriate licensed healthcare professional.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-ch15-064',
    chapter_id: 'ch-15',
    front: 'Knowledge Trap: Can every synthetic system be permed with standard solution?',
    back: 'No. Synthetic fibers have product-specific chemical limits; do not use a perm solution unless the system manufacturer explicitly supports it.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 64,
    is_active: true,
  },
  {
    id: 'fc-ch15-065',
    chapter_id: 'ch-15',
    front: 'Knowledge Trap: Does hotter water always clean synthetic systems better?',
    back: 'No. Follow the system’s approved water-temperature guidance; the source cautions against hot water on synthetic systems.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-ch15-066',
    chapter_id: 'ch-15',
    front: 'Knowledge Trap: Does every lace-front system use the same tape placement?',
    back: 'No. Lace is delicate, and attachment placement depends on the specific system and adhesive. Follow the approved method for that product combination.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-ch15-067',
    chapter_id: 'ch-15',
    front: 'Knowledge Trap: Can every bonded system be shampooed immediately?',
    back: 'No. The attachment must cure according to the adhesive manufacturer’s instructions before water exposure; a fixed 24–48-hour rule is not universal.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-ch15-068',
    chapter_id: 'ch-15',
    front: 'Knowledge Trap: Is hair transplantation a barbering service?',
    back: 'No. Hair transplantation is a medical procedure, not a cosmetic barbering service. Refer the client to an appropriately licensed medical professional.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-ch15-069',
    chapter_id: 'ch-15',
    front: 'Knowledge Trap: Can a human-hair system automatically receive natural-hair chemical services?',
    back: 'No. Chemical-service limits depend on fiber, base, prior processing, and manufacturer approval.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-ch15-070',
    chapter_id: 'ch-15',
    front: 'Knowledge Trap: Does every daily-wear client need exactly two systems?',
    back: 'No. A backup can be useful for some maintenance plans, but the appropriate number depends on the client’s wear and service needs.',
    category: 'Exam Traps',
    difficulty: 'easy',
    order_index: 70,
    is_active: true,
  },

  // === SCENARIO CARDS ===
  {
    id: 'fc-ch15-071',
    chapter_id: 'ch-15',
    front: 'Scenario: A regular client says "I\'m starting to look like my father." What is your most professional response?',
    back: 'Acknowledge his comment and ask if he would like to discuss options in private. You validated his concern, offered privacy, and invited further conversation without pressure.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 71,
    is_active: true,
  },
  {
    id: 'fc-ch15-072',
    chapter_id: 'ch-15',
    front: 'Scenario: A 68-year-old client wants jet-black hair styled like a 25-year-old celebrity. What is your professional obligation?',
    back: 'Explain why the request will look unnatural and recommend a more appropriate option. Educate with respect. Show samples of age-appropriate colors and styles that restore confidence without looking ridiculous.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 72,
    is_active: true,
  },
  {
    id: 'fc-ch15-073',
    chapter_id: 'ch-15',
    front: 'Scenario: A client needs a system in three days for a wedding. He has a standard oval bald area and a $400 budget. What do you recommend?',
    back: 'A stock system in a close color match, customized with cutting and blending. Stock systems are available immediately, fit the budget, and can be cut and styled to look natural for the event.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 73,
    is_active: true,
  },
  {
    id: 'fc-ch15-074',
    chapter_id: 'ch-15',
    front: 'Scenario: A competitive swimmer expects frequent water exposure. What attachment approach is safest?',
    back: 'Select a system and attachment product specifically rated for the expected water exposure, then follow the manufacturer’s preparation, cure, maintenance, and removal instructions.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 74,
    is_active: true,
  },
  {
    id: 'fc-ch15-075',
    chapter_id: 'ch-15',
    front: 'Scenario: A client asks which Minoxidil formulation and schedule to use. How do you respond?',
    back: 'Explain that formulations differ and refer the client to verified product labeling and an appropriate licensed healthcare professional for individualized guidance.',
    category: 'Scenarios',
    difficulty: 'medium',
    order_index: 75,
    is_active: true,
  },

  // === COMPARISON CARDS ===
  {
    id: 'fc-ch15-076',
    chapter_id: 'ch-15',
    front: 'Compare human hair vs synthetic hair for replacement systems.',
    back: 'Human: natural-looking texture and movement, with care needs affected by processing and environment. Synthetic: manufactured fiber with product-specific styling, heat, and chemical-care limits.',
    category: 'Comparisons',
    difficulty: 'easy',
    order_index: 76,
    is_active: true,
  },
  {
    id: 'fc-ch15-077',
    chapter_id: 'ch-15',
    front: 'Compare stock vs custom hair replacement systems.',
    back: 'Stock: standard sizes/colors and adaptable after fitting. Custom: built from client-specific measurements or templates for a more individualized fit, usually with greater time and cost.',
    category: 'Comparisons',
    difficulty: 'easy',
    order_index: 77,
    is_active: true,
  },
  {
    id: 'fc-ch15-078',
    chapter_id: 'ch-15',
    front: 'Compare bonding vs tape attachment.',
    back: 'They differ in security, removal, wear pattern, and maintenance. Water tolerance and cure time depend on the specific system, attachment product, and manufacturer directions.',
    category: 'Comparisons',
    difficulty: 'easy',
    order_index: 78,
    is_active: true,
  },
  {
    id: 'fc-ch15-079',
    chapter_id: 'ch-15',
    front: 'Compare mesh vs polyurethane base materials.',
    back: 'Mesh can provide airflow and flexibility; polyurethane can provide a low-porosity attachment surface. Exact durability, water resistance, warmth, and adhesive compatibility vary by system.',
    category: 'Comparisons',
    difficulty: 'easy',
    order_index: 79,
    is_active: true,
  },

  // === PROCEDURE CARDS ===
  {
    id: 'fc-ch15-080',
    chapter_id: 'ch-15',
    front: 'What are the steps for creating a template for a custom system?',
    back: '1. Cover bald area with plastic wrap, smoothing flat. 2. Apply transparent tape over the wrap to create rigidity. 3. Mark front hairline, sides, and nape with grease pencil. 4. Remove carefully and transfer to pattern paper.',
    category: 'Procedures',
    difficulty: 'medium',
    order_index: 80,
    is_active: true,
  },
  {
    id: 'fc-ch15-081',
    chapter_id: 'ch-15',
    front: 'How should a synthetic hair system be cleaned?',
    back: 'Follow the system manufacturer’s cleaning sequence, approved cleaner, water-temperature range, support method, and drying limits. The source emphasizes gentle handling and avoiding excessive heat.',
    category: 'Procedures',
    difficulty: 'medium',
    order_index: 81,
    is_active: true,
  },
  {
    id: 'fc-ch15-082',
    chapter_id: 'ch-15',
    front: 'How should a facial hair piece be applied with spirit gum?',
    back: 'Use spirit gum only when appropriate for the piece, and follow product instructions for skin preparation, tack time, placement, and removal.',
    category: 'Procedures',
    difficulty: 'easy',
    order_index: 82,
    is_active: true,
  },
  {
    id: 'fc-ch15-083',
    chapter_id: 'ch-15',
    front: 'What is the cutting and blending procedure for a new system?',
    back: 'Top: cut at 90° elevation, work crown to forehead. Sides: comb down, blend to natural hairline, taper with slide cutting. Back: cut excess, blend with thinning shears. Final check from all angles under different lighting.',
    category: 'Procedures',
    difficulty: 'medium',
    order_index: 83,
    is_active: true,
  },

  // === SAFETY CARDS ===
  {
    id: 'fc-ch15-084',
    chapter_id: 'ch-15',
    front: 'What is a common irreversible mistake when customizing stock systems?',
    back: 'Removing too much hair during initial customization. Work conservatively because cut hair cannot be restored to the system.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 84,
    is_active: true,
  },
  {
    id: 'fc-ch15-085',
    chapter_id: 'ch-15',
    front: 'What is the goal of proper system storage?',
    back: 'Preserve the system’s shape, base, and hair. Use the support and storage method recommended for that specific system.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 85,
    is_active: true,
  },
  {
    id: 'fc-ch15-086',
    chapter_id: 'ch-15',
    front: 'Why must dull blades be replaced during system customization?',
    back: 'Dull blades pull hair, causing damage to the system and creating uneven cuts. Sharp tools are essential for clean, precise work on expensive systems.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 86,
    is_active: true,
  },

  // === KEY TAKEAWAYS ===
  {
    id: 'fc-ch15-087',
    chapter_id: 'ch-15',
    front: 'What is the most important principle of men\'s hair replacement?',
    back: 'You are not selling hair. You are restoring the reflection your client wants to see every morning. Technical skill, ethical practice, and emotional intelligence are all required.',
    category: 'Key Takeaways',
    difficulty: 'easy',
    order_index: 87,
    is_active: true,
  },
  {
    id: 'fc-ch15-088',
    chapter_id: 'ch-15',
    front: 'What makes the difference between an obvious hairpiece and an undetectable system?',
    back: 'Blending. The transition between system hair and natural hair must be invisible. Slide cutting, proper thinning, and careful tapering create the illusion that all hair is natural.',
    category: 'Key Takeaways',
    difficulty: 'easy',
    order_index: 88,
    is_active: true,
  },
  {
    id: 'fc-ch15-089',
    chapter_id: 'ch-15',
    front: 'Why is scope-of-practice knowledge important for hair replacement barbers?',
    back: 'It separates cosmetic hair-replacement services from diagnosis, prescribing, surgery, and individualized medical advice. Always verify the rules in the jurisdiction where you practice.',
    category: 'Key Takeaways',
    difficulty: 'easy',
    order_index: 89,
    is_active: true,
  },
  {
    id: 'fc-ch15-090',
    chapter_id: 'ch-15',
    front: 'Why should cure time be verified after a bonded system is applied?',
    back: 'Bonded systems need adequate cure time before water exposure, but the interval depends on the adhesive and manufacturer instructions. Some source material uses 24–48 hours as a study reference, not a universal rule.',
    category: 'Key Takeaways',
    difficulty: 'easy',
    order_index: 90,
    is_active: true,
  },
]

export default chapter15PremiumFlashcards
