// Chapter 9 Premium Flashcards — The Skin Safety Academy
// 50 cards derived from Chapter 9 V2 immersive content
// Categories: Skin Structure, Epidermis Layers, Dermis & Subcutaneous, Glands & Functions,
//             Primary Lesions, Secondary Lesions, Sebaceous Disorders, Sudoriferous & Inflammations,
//             Pigment & Hypertrophies, Skin Cancer & Safety

import { Flashcard } from '@/types'

export const chapter9PremiumFlashcards: Flashcard[] = [
  // ═══════════════════════════════════════════════════
  // CATEGORY 1: SKIN STRUCTURE & BASICS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-001',
    chapter_id: 'ch-9',
    front: 'What is the largest organ of the human body?',
    back: 'The SKIN. It is the body\'s first line of defense against disease and the environment, and it protects internal organs while regulating temperature and providing sensory information.',
    category: 'Skin Structure & Basics',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-9-002',
    chapter_id: 'ch-9',
    front: 'What is the normal pH of healthy skin, and why does it matter?',
    back: 'Healthy skin maintains a SLIGHTLY ACIDIC pH of approximately 5.5. This acidity creates a protective barrier against microorganisms, inhibiting bacterial growth. Do not strip it with harsh alkaline products.',
    category: 'Skin Structure & Basics',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-9-003',
    chapter_id: 'ch-9',
    front: 'Where is the THINNEST skin on the body? Where is the THICKEST?',
    back: 'THINNEST: Eyelids. THICKEST: Palms and soles. Skin thickness varies across the body, which affects absorption rates and service sensitivity.',
    category: 'Skin Structure & Basics',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-9-004',
    chapter_id: 'ch-9',
    front: 'Approximately what percentage of the body\'s blood supply goes to the skin?',
    back: 'About HALF (50%) of the body\'s blood supply flows through the skin. This massive blood flow is why the skin is considered an organ, not just a covering, and why it plays a critical role in temperature regulation.',
    category: 'Skin Structure & Basics',
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-9-005',
    chapter_id: 'ch-9',
    front: 'What are the two main divisions of the skin?',
    back: '1. EPIDERMIS — outermost protective layer (no blood vessels)\n2. DERMIS — underlying thicker layer containing glands, vessels, follicles, and nerves.\n\nThe subcutaneous tissue (hypodermis/adipose) is below the dermis but is not technically a division of the skin itself.',
    category: 'Skin Structure & Basics',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 2: EPIDERMIS LAYERS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-006',
    chapter_id: 'ch-9',
    front: 'What are the five layers of the epidermis, from deepest to surface?',
    back: '1. Stratum GERMINATIVUM (basal cell layer)\n2. Stratum SPINOSUM (spiny layer)\n3. Stratum GRANULOSUM (granular layer)\n4. Stratum LUCIDUM (clear layer)\n5. Stratum CORNEUM (horny layer)\n\nMnemonic: "Go Somewhere Good, Life Continues."',
    category: 'Epidermis Layers',
    difficulty: 'medium',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-9-007',
    chapter_id: 'ch-9',
    front: 'Which epidermis layer contains melanocytes, and what do they produce?',
    back: 'The STRATUM GERMINATIVUM (basal cell layer) contains MELANOCYTES, which produce MELANIN — the pigment that gives skin its color and protects against UV damage.',
    category: 'Epidermis Layers',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-9-008',
    chapter_id: 'ch-9',
    front: 'BOARD EXAM ALERT: Does the epidermis contain blood vessels?',
    back: 'NO — the epidermis contains NO blood vessels. It receives nutrients entirely by diffusion from the dermis below. This is one of the most commonly tested facts on state board exams.',
    category: 'Epidermis Layers',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-9-009',
    chapter_id: 'ch-9',
    front: 'What is the function of the stratum corneum, and what waterproofs it?',
    back: 'The STRATUM CORNEUM is the outermost layer of tightly packed, scale-like cells that are continually shed and replaced. It is waterproofed by SEBUM from sebaceous glands, which prevents moisture loss and microbial entry.',
    category: 'Epidermis Layers',
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-9-010',
    chapter_id: 'ch-9',
    front: 'In which layer of the epidermis are cells filled with keratin and becoming almost dead?',
    back: 'The STRATUM GRANULOSUM (granular layer). Keratin is the protein that makes skin waterproof and durable. By the time cells reach this layer, they are transitioning from living to dead.',
    category: 'Epidermis Layers',
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 3: DERMIS, SUBCUTANEOUS & NERVES (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-011',
    chapter_id: 'ch-9',
    front: 'How much thicker is the dermis than the epidermis?',
    back: 'The dermis is approximately 25× THICKER than the epidermis. It contains all the skin\'s functional structures: glands, blood vessels, hair follicles, lymph glands, arrector pili muscles, and oil glands.',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'easy',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-9-012',
    chapter_id: 'ch-9',
    front: 'What are the two layers of the dermis, and what does each contain?',
    back: '1. PAPILLARY LAYER (superficial): Contains papillae (conical projections), tactile corpuscles for touch, looped capillaries, and some melanin.\n2. RETICULAR LAYER (deeper): Supplies oxygen and nutrients. Contains fat cells, sweat glands, blood vessels, hair follicles, lymph glands, arrector pili muscles, and oil glands.',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-9-013',
    chapter_id: 'ch-9',
    front: 'What are the three types of nerve fibers in the skin, and what does each control?',
    back: '1. MOTOR nerve fibers — control arrector pili muscles (goose bumps) and stimulate glandular activity.\n2. SENSORY nerve fibers — react to heat, cold, touch, pressure, and pain.\n3. SECRETORY nerve fibers — regulate sweat and oil gland secretion.',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-9-014',
    chapter_id: 'ch-9',
    front: 'What provides skin elasticity, and what happens when these substances decrease?',
    back: 'COLLAGEN provides strength and structural support. ELASTIN provides elasticity — the ability to stretch and return to shape. When production decreases with age, skin sags and wrinkles form. Smoking, sun damage, and poor nutrition accelerate this breakdown.',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-9-015',
    chapter_id: 'ch-9',
    front: 'What is the subcutaneous tissue also called, and what are its four functions?',
    back: 'Also called HYPODERMIS or ADIPOSE TISSUE. Its four functions are:\n1. SMOOTHNESS — provides smoothness and contour\n2. ENERGY STORAGE — stores fat as an energy reserve\n3. CUSHIONING — protects underlying organs from impact\n4. INSULATION — helps regulate body temperature',
    category: 'Dermis, Subcutaneous & Nerves',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 4: GLANDS & SKIN FUNCTIONS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-016',
    chapter_id: 'ch-9',
    front: 'What does the SHAPES mnemonic stand for — the six functions of the skin?',
    back: 'S — SENSATION (touch, pressure, pain, heat, cold)\nH — HEAT REGULATION (maintains ~98.6°F via blood flow and sweat)\nA — ABSORPTION (limited; topical medications)\nP — PROTECTION (barrier against pathogens, injury, chemicals)\nE — EXCRETION (perspiration removes waste)\nS — SECRETION (sebum lubricates skin and hair)',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-9-017',
    chapter_id: 'ch-9',
    front: 'What is the difference between sebaceous glands and sudoriferous glands?',
    back: 'SEBACEOUS (oil) glands: Connected to hair follicles, produce SEBUM to lubricate skin and hair, most active on face and scalp.\nSUDORIFEROUS (sweat) glands: Coiled base with duct to surface, produce SWEAT to regulate body temperature and eliminate waste.\n\nMnemonic: SEBACEOUS = SEbum. SUDORIFEROUS = SWeat.',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-9-018',
    chapter_id: 'ch-9',
    front: 'What happens when sebum becomes blocked in a hair follicle?',
    back: 'Blocked sebum + debris forms COMEDONES:\n• BLACKHEAD (open comedo) — plugged follicle open to air; dark color comes from oxidation of sebum and melanin, NOT dirt.\n• WHITEHEAD (closed comedo) — plugged follicle covered by skin; appears as a small white bump.',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-9-019',
    chapter_id: 'ch-9',
    front: 'Where are sudoriferous (sweat) glands most numerous on the body?',
    back: 'Most numerous on PALMS, SOLES, FOREHEAD, and ARMPITS. The body has 2–4 million sweat glands. They are essential for thermoregulation — without them, overheating would be life-threatening.',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-9-020',
    chapter_id: 'ch-9',
    front: 'What is melanin, where is it produced, and what is its primary function?',
    back: 'MELANIN is pigment produced by MELANOCYTES in the STRATUM GERMINATIVUM (basal layer) of the epidermis. Its PRIMARY FUNCTION is UV PROTECTION — it absorbs harmful ultraviolet rays before they damage deeper skin layers and DNA. More melanin means darker skin and more natural UV protection.',
    category: 'Glands & Skin Functions',
    difficulty: 'easy',
    order_index: 20,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 5: PRIMARY LESIONS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-021',
    chapter_id: 'ch-9',
    front: 'What is the difference between a BULLA and a VESICLE?',
    back: 'Both are fluid-filled blisters, but SIZE is the distinguishing factor:\n• BULLA — LARGE blister with watery fluid (e.g., contact dermatitis, burns)\n• VESICLE — SMALL blister with clear fluid (e.g., poison ivy, chicken pox)\n\nBOARD EXAM ALERT: Size is the only difference — know this distinction cold.',
    category: 'Primary Lesions',
    difficulty: 'medium',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-9-022',
    chapter_id: 'ch-9',
    front: 'What is a PUSTULE, and why is it important for barbers to recognize?',
    back: 'A PUSTULE is a raised, inflamed papule containing PUS. Examples: acne, impetigo, folliculitis.\n\nBARBER IMPACT: Never perform services on skin with pustules — the risk of infection spread is high. Pustules indicate active infection.',
    category: 'Primary Lesions',
    difficulty: 'easy',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-9-023',
    chapter_id: 'ch-9',
    front: 'What is a MACULE, and how can you tell it apart from other lesions?',
    back: 'A MACULE is a flat spot or discoloration with NO change in skin texture. Examples: freckle, liver spot, birthmark.\n\nKey identifier: Macules are NON-PALPABLE — you cannot feel them by touch. If a spot is raised, it is NOT a macule. Monitor macules for changes that could signal melanoma.',
    category: 'Primary Lesions',
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-9-024',
    chapter_id: 'ch-9',
    front: 'What is a WHEAL, and what causes it?',
    back: 'A WHEAL is an itchy, swollen lesion caused by fluid accumulation in the skin. Examples: hives, insect bites, allergic reactions.\n\nWheals are temporary — they appear suddenly and can disappear within hours. They indicate an allergic or inflammatory response.',
    category: 'Primary Lesions',
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-9-025',
    chapter_id: 'ch-9',
    front: 'What is the difference between a PAPULE and a NODULE?',
    back: 'Both are solid, raised lesions:\n• PAPULE — small elevation of the skin with no pus (e.g., early acne, warts)\n• NODULE — solid bump LARGER than 0.4 inch, extending DEEPER into the skin (e.g., swollen lymph nodes, cystic acne)\n\nA papule becomes a pustule when it fills with pus.',
    category: 'Primary Lesions',
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 6: SECONDARY LESIONS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-026',
    chapter_id: 'ch-9',
    front: 'What is the difference between PRIMARY and SECONDARY skin lesions?',
    back: 'PRIMARY lesions are the ORIGINAL lesions — they appear first, directly from a disease process or injury. They are typically different in color and may be raised.\n\nSECONDARY lesions EVOLVE from primary lesions through accumulation, infection, or healing. Example: a vesicle that breaks open and dries becomes a CRUST.',
    category: 'Secondary Lesions',
    difficulty: 'easy',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-9-027',
    chapter_id: 'ch-9',
    front: 'What is a KELOID, and who is more prone to developing them?',
    back: 'A KELOID is a thick scar resulting from EXCESSIVE fibrous tissue growth. It extends beyond the original wound boundaries.\n\nMore common in DARKER SKIN TYPES. Can form after piercings, cuts, or any skin injury. Unlike normal scars, keloids do not flatten over time.',
    category: 'Secondary Lesions',
    difficulty: 'medium',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-9-028',
    chapter_id: 'ch-9',
    front: 'What is a FISSURE, and where are common locations?',
    back: 'A FISSURE is a CRACK in the skin that penetrates into the dermis. Examples: chapped hands, cracked lips, athlete\'s foot fissures.\n\nFissures are painful and can become infected. In barbering, be cautious when working around cracked skin on hands or lips — avoid irritating products.',
    category: 'Secondary Lesions',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-9-029',
    chapter_id: 'ch-9',
    front: 'What is an ULCER, and why must barbers never shave over one?',
    back: 'An ULCER is an open lesion with LOSS OF SKIN DEPTH. Examples: chicken pox scars, herpes lesions, diabetic ulcers.\n\nBARBER SAFETY: Never shave over ulcers — they indicate compromised skin integrity. Shaving could cause bleeding, infection, and delayed healing. Always refer clients with open ulcers to a physician.',
    category: 'Secondary Lesions',
    difficulty: 'easy',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-9-030',
    chapter_id: 'ch-9',
    front: 'What is a SCALE, and what conditions cause it?',
    back: 'A SCALE is thin, dry, or oily flakes of dead skin cells. Examples: dandruff, psoriasis, seborrheic dermatitis.\n\nScales are common on the scalp — a barber\'s primary work area. Gentle handling and appropriate products can help manage scaling conditions, but refer severe or unknown cases.',
    category: 'Secondary Lesions',
    difficulty: 'easy',
    order_index: 30,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 7: SEBACEOUS GLAND DISORDERS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-031',
    chapter_id: 'ch-9',
    front: 'What causes acne (acne vulgaris), and what are the four grades?',
    back: 'CAUSE: Bacteria (Propionibacterium acnes) multiply in clogged follicles, causing inflammation and infection. Hormonal changes and excess sebum contribute.\n\nGRADES:\nI — Mild: minor breakouts, mostly blackheads\nII — Moderate: more blackheads, papules, some pustules\nIII — Severe: numerous papules and pustules, inflammation spreading\nIV — Very severe: cystic acne with deep, painful lesions',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-9-032',
    chapter_id: 'ch-9',
    front: 'What is ROSACEA, and what are common triggers?',
    back: 'ROSACEA is a chronic condition causing flushing, redness, dilated blood vessels, and papules/pustules on the cheeks and nose.\n\nTRIGGERS: Sun exposure, spicy food, alcohol, stress, hot beverages, extreme temperatures.\n\nBARBER IMPACT: Handle rosacea clients gently. Avoid hot towels, harsh products, and friction. Do not attempt to treat — refer to a dermatologist.',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-9-033',
    chapter_id: 'ch-9',
    front: 'What is SEBORRHEIC DERMATITIS, and is it contagious?',
    back: 'SEBORRHEIC DERMATITIS causes oily, red, scaly, crusty patches — dandruff-like on the scalp. It is NOT contagious.\n\nIt is manageable with proper medicated products and hygiene. As a barber, you will encounter this frequently on the scalp. Handle gently and avoid irritating the skin further.',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-9-034',
    chapter_id: 'ch-9',
    front: 'BOARD EXAM ALERT: What is the relationship between a sebaceous cyst and a steatoma?',
    back: 'They are the SAME CONDITION with different names. Both refer to a large pocket filled with SEBUM. A sebaceous cyst may also be called a steatoma or wen.\n\nKnow BOTH terms for the exam — board questions may use either name.',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-9-035',
    chapter_id: 'ch-9',
    front: 'What is ASTEATOSIS, and who is most commonly affected?',
    back: 'ASTEATOSIS is dry, scaly skin caused by SEBUM DEFICIENCY. Most common in older adults and in cold climates where skin loses moisture.\n\nAs a barber, you may see this on clients\' scalps and faces. Recommend moisturizing products, but do not diagnose — suggest a dermatologist for persistent dryness.',
    category: 'Sebaceous Gland Disorders',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 8: SUDORIFEROUS DISORDERS & INFLAMMATIONS (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-036',
    chapter_id: 'ch-9',
    front: 'What is ANHIDROSIS, and why is it life-threatening?',
    back: 'ANHIDROSIS is the deficiency or complete INABILITY TO SWEAT. It is life-threatening in severe cases because the body cannot cool itself through evaporation.\n\nBARBER IMPACT: Clients with anhidrosis may overheat during services under warm towels or steam. Use caution with heat-based treatments and monitor for signs of overheating.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-9-037',
    chapter_id: 'ch-9',
    front: 'What is the difference between DERMATITIS and ECZEMA?',
    back: 'DERMATITIS is a general term for any SKIN INFLAMMATION (can be irritant or allergic contact).\n\nECZEMA is a specific CHRONIC inflammatory condition with itching, burning, and redness. It is often triggered by stress, allergens, or irritants.\n\nNeither is contagious. Both can be irritated by harsh products, hot water, or friction from shaving.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-9-038',
    chapter_id: 'ch-9',
    front: 'What is PSORIASIS, and how should a barber handle a client who has it?',
    back: 'PSORIASIS is a chronic condition causing red patches covered with SILVERY SCALES. It is autoimmune-related and NOT contagious.\n\nBARBER HANDLING: Clients with scalp psoriasis may have flakes resembling severe dandruff. Handle GENTLY. Avoid irritating the skin with harsh products, hot water, or vigorous brushing. Do not attempt to remove scales.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'easy',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-9-039',
    chapter_id: 'ch-9',
    front: 'Why should a barber NEVER shave over active HERPES SIMPLEX (cold sore) lesions?',
    back: 'Herpes simplex is HIGHLY CONTAGIOUS during active outbreaks. The virus spreads by contact with fluid from blisters.\n\nShaving over active lesions:\n• Spreads the virus to other areas of the face\n• Can infect the barber\n• Violates sanitation standards\n\nALWAYS postpone facial services until lesions are completely healed. Gloves do NOT prevent transmission in this context.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'easy',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-9-040',
    chapter_id: 'ch-9',
    front: 'What is MILIARIA RUBRA (prickly heat), and when should barbers avoid heat-based treatments?',
    back: 'MILIARIA RUBRA is acute inflammation with small red vesicles and intense itching caused by heat and blocked sweat ducts. Common in hot, humid conditions.\n\nBARBER SAFETY: Avoid heat-based treatments (warm towels, steam) on clients showing signs of prickly heat. The additional heat worsens the condition and causes discomfort.',
    category: 'Sudoriferous Disorders & Inflammations',
    difficulty: 'easy',
    order_index: 40,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 9: PIGMENT DISORDERS & HYPERTROPHIES (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-041',
    chapter_id: 'ch-9',
    front: 'What is the difference between HYPERPIGMENTATION and HYPOPIGMENTATION?',
    back: 'HYPERPIGMENTATION — darker than normal skin patches (e.g., chloasma/mask of pregnancy, freckles, liver spots)\n\nHYPOPIGMENTATION — lighter or white patches (e.g., vitiligo, leukoderma)\n\nBoth are changes in melanin production. Neither is contagious. As a barber, note these conditions but do not treat — they are cosmetic concerns, not contraindications for most services.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-9-042',
    chapter_id: 'ch-9',
    front: 'What is ALBINISM, and what precautions do affected clients need?',
    back: 'ALBINISM is a congenital ABSENCE of melanin production. Characterized by white hair, very light skin, and pinkish eyes.\n\nPRECAUTIONS: Clients with albinism have NO natural UV protection. They require extreme sun protection (SPF 50+, protective clothing) and should avoid prolonged sun exposure. Be gentle with their skin — it is highly sensitive.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-9-043',
    chapter_id: 'ch-9',
    front: 'What is a VERRUCA (wart), and why is it a barber safety concern?',
    back: 'A VERRUCA is caused by HUMAN PAPILLOMAVIRUS (HPV). It is CONTAGIOUS and can spread by scratching or contact.\n\nBARBER SAFETY: NEVER shave over warts. The virus can spread to other areas and to you. Refer clients with warts for medical treatment. Warts on the face, neck, or scalp require professional removal by a physician.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-9-044',
    chapter_id: 'ch-9',
    front: 'What is a KERATOMA, and should a barber remove it?',
    back: 'A KERATOMA is a thickened patch of skin caused by friction or pressure. Calluses and corns are types of keratomas.\n\nBARBER RULE: Do NOT remove calluses or corns. They are the skin\'s NATURAL DEFENSE against continued pressure. Removing them exposes underlying tissue to injury and infection.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'easy',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-9-045',
    chapter_id: 'ch-9',
    front: 'What is a NEVUS (mole), and when should it concern a barber?',
    back: 'A NEVUS is a small brownish spot or growth. Most are benign and harmless.\n\nCONCERN: Monitor moles for ABCDE changes — Asymmetry, Border irregularity, Color variation, Diameter >6mm, Evolution (changing). If you notice a client\'s mole has changed, mention it professionally and suggest a dermatologist visit. You could save their life.',
    category: 'Pigment Disorders & Hypertrophies',
    difficulty: 'medium',
    order_index: 45,
    is_active: true,
  },

  // ═══════════════════════════════════════════════════
  // CATEGORY 10: SKIN CANCER & SAFETY (5 cards)
  // ═══════════════════════════════════════════════════
  {
    id: 'fc-9-046',
    chapter_id: 'ch-9',
    front: 'What are the three types of skin cancer, ranked from most common/least severe to least common/most dangerous?',
    back: '1. BASAL CELL CARCINOMA — most common (80% of cases), least severe, pearly nodules, rarely metastasizes\n2. SQUAMOUS CELL CARCINOMA — more serious (20% of cases), scaly red papules, can metastasize\n3. MALIGNANT MELANOMA — least common but MOST DANGEROUS, 100% fatal if untreated, black/brown uneven patches\n\nMnemonic: "Basal = Best outcome. Melanoma = Most deadly."',
    category: 'Skin Cancer & Safety',
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-9-047',
    chapter_id: 'ch-9',
    front: 'What does the ABCDE rule stand for in melanoma detection?',
    back: 'A — ASYMMETRY (one half does not match the other)\nB — BORDER irregularity (notched, blurred edges)\nC — COLOR variation (multiple colors: brown, black, tan, red, white, blue)\nD — DIAMETER (>6mm, about pencil eraser size)\nE — EVOLUTION (any change in size, shape, color, or new symptoms)\n\nThis appears on EVERY board exam. Memorize it — it could save a client\'s life.',
    category: 'Skin Cancer & Safety',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-9-048',
    chapter_id: 'ch-9',
    front: 'BOARD EXAM ALERT: What is the 5-year survival rate for melanoma detected early versus after it spreads?',
    back: 'EARLY DETECTION: 99% 5-year survival rate\nAFTER SPREADING: Drops to 27%\n\nThis is why barbers matter — you may be the first to notice changes on the scalp, ears, or neck. Early detection is literally the difference between life and death.',
    category: 'Skin Cancer & Safety',
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-9-049',
    chapter_id: 'ch-9',
    front: 'What contagious skin conditions must a barber NEVER perform services on?',
    back: 'NEVER perform services on:\n• PEDICULOSIS (lice)\n• SCABIES\n• IMPETIGO\n• Open HERPES lesions\n• Active VERUCA (wart) outbreaks\n\nPerforming services on contagious conditions is a SANITATION VIOLATION that can result in license suspension. When in doubt, STOP and REFER.',
    category: 'Skin Cancer & Safety',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-9-050',
    chapter_id: 'ch-9',
    front: 'MASTER SAFETY RULE: What is a barber\'s professional obligation when they see a suspicious skin condition?',
    back: 'RECOGNIZE — Do not diagnose. You are a barber, not a doctor.\nREFER — Suggest a dermatologist or physician visit.\nDOCUMENT — Note your observation and the conversation.\nPROTECT — Do not perform services that could worsen the condition or spread infection.\n\nYour license and your client\'s health matter more than one appointment. A canceled service is better than a lawsuit or permanent damage.',
    category: 'Skin Cancer & Safety',
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },
]
