import { Flashcard } from '@/types'

// Chapter 18: Haircoloring and Lightening — 50 premium flashcards
export const chapter18PremiumFlashcards: Flashcard[] = [
  {
    id: 'fc-ch18-001',
    standardId: 'CH18-F001',
    chapter_id: 'ch-18',
    front: "Haircoloring",
    back: "The art and science of changing the color of the hair. (p. 641)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch18-002',
    standardId: 'CH18-F002',
    chapter_id: 'ch-18',
    front: "Hair Lightening",
    back: "The partial or total removal of natural pigment or artificial color from the hair. (p. 641)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-ch18-003',
    standardId: 'CH18-F003',
    chapter_id: 'ch-18',
    front: "Elasticity",
    back: "Shows how strong the cortex is. Normal wet hair can stretch up to 50 percent of its original length and return without breaking. (p. 642-643)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch18-004',
    standardId: 'CH18-F004',
    chapter_id: 'ch-18',
    front: "Texture",
    back: "The diameter of a single hair strand: fine, medium, or coarse. Fine hair takes color faster; coarse hair may take longer to process. (p. 643)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch18-005',
    standardId: 'CH18-F005',
    chapter_id: 'ch-18',
    front: "Density",
    back: "The number of hairs per square inch on the scalp. Thick hair needs smaller subsections, as thin as \u215b inch, for proper color coverage. (p. 643)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-ch18-006',
    standardId: 'CH18-F006',
    chapter_id: 'ch-18',
    front: "Porosity",
    back: "The hair's ability to absorb moisture. Porous hair absorbs color faster and may fade faster; low-porosity hair resists chemical penetration. (p. 643)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch18-007',
    standardId: 'CH18-F007',
    chapter_id: 'ch-18',
    front: "Eumelanin & Pheomelanin",
    back: "Eumelanin gives hair black and brown pigment. Pheomelanin gives hair yellow, blond, and red pigment. (p. 644)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-ch18-008',
    standardId: 'CH18-F008',
    chapter_id: 'ch-18',
    front: "Contributing Pigment",
    back: "The undertone, or color, that lies underneath the natural hair color. It is exposed when hair is lightened and affects the final result. (p. 644)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch18-009',
    standardId: 'CH18-F009',
    chapter_id: 'ch-18',
    front: "Laws of Color & Color Wheel",
    back: "A system for understanding how colors relate to each other and how they mix to make other colors. The color wheel shows these relationships. (p. 644)",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-ch18-010',
    standardId: 'CH18-F010',
    chapter_id: 'ch-18',
    front: "Primary & Secondary Colors",
    back: "Primary colors (red, yellow, blue) cannot be made by mixing. Secondary colors (green, violet, orange) are made by mixing equal parts of two primary colors. (p. 644-645)",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-ch18-011',
    standardId: 'CH18-F011',
    chapter_id: 'ch-18',
    front: "Complementary Colors",
    back: "A primary color and a secondary color directly opposite each other on the color wheel. They neutralize each other when mixed. (p. 645)",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch18-012',
    standardId: 'CH18-F012',
    chapter_id: 'ch-18',
    front: "Level System",
    back: "A scale of 1 to 10 that measures how light or dark a hair color is. 1 is black and 10 is the lightest blond. (p. 646)",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-ch18-013',
    standardId: 'CH18-F013',
    chapter_id: 'ch-18',
    front: "Tone, Hue & Saturation",
    back: "Hue is the basic name of a color. Tone is its warmth or coolness. Saturation (intensity) is the concentration or strength of a color. (p. 646)",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch18-014',
    standardId: 'CH18-F014',
    chapter_id: 'ch-18',
    front: "Base Color",
    back: "The main tone of a haircoloring product. It strongly influences the final color result, such as violet reducing yellow or blue reducing orange. (p. 646-647)",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch18-015',
    standardId: 'CH18-F015',
    chapter_id: 'ch-18',
    front: "Temporary Haircolor",
    back: "Uses large color molecules that coat the outside of the cuticle and wash out with one shampoo. Examples include color rinses, sprays, mousses, gels, and crayons. (p. 649, 651)",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch18-016',
    standardId: 'CH18-F016',
    chapter_id: 'ch-18',
    front: "Semipermanent Haircolor",
    back: "A no-lift, deposit-only color that stains the cuticle and lasts about six to eight shampoos. It does not require hydrogen peroxide. (p. 652)",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch18-017',
    standardId: 'CH18-F017',
    chapter_id: 'ch-18',
    front: "Demipermanent Haircolor",
    back: "A deposit-only oxidation color mixed with a low-volume developer right before use. It lasts longer than semipermanent color and does not lift. (p. 653)",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-ch18-018',
    standardId: 'CH18-F018',
    chapter_id: 'ch-18',
    front: "Permanent Haircolor / Tint",
    back: "Mixed with developer to lift and deposit color into the cortex. It stays in the hair until it grows out, requiring retouch applications. (p. 653-654)",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch18-019',
    standardId: 'CH18-F019',
    chapter_id: 'ch-18',
    front: "Aniline Derivative & Patch Test",
    back: "An uncolored dye precursor that combines with peroxide to form permanent color. The FDA requires a patch test 24 to 48 hours before each application. (p. 650)",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch18-020',
    standardId: 'CH18-F020',
    chapter_id: 'ch-18',
    front: "Metallic & Compound Dyes",
    back: "Nonprofessional products, also called progressive colors or color restorers. They contain metals that can damage hair and react dangerously with professional chemicals. (p. 655)",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-ch18-021',
    standardId: 'CH18-F021',
    chapter_id: 'ch-18',
    front: "Developer & Volume",
    back: "Hydrogen peroxide is an oxidizing agent that supplies oxygen to develop color molecules. Volume measures its strength; higher volume means greater lifting or lightening. (p. 655-656)",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch18-022',
    standardId: 'CH18-F022',
    chapter_id: 'ch-18',
    front: "Developer Volumes: 10 / 20 / 30 / 40",
    back: "10-volume deposits with little lift. 20-volume is standard for permanent color and gray coverage. 30-volume lifts up to three levels. 40-volume lifts up to four levels. (p. 656)",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch18-023',
    standardId: 'CH18-F023',
    chapter_id: 'ch-18',
    front: "Hydrogen Peroxide Safety",
    back: "Use clean tools, avoid metal, don't pour into another product's lid, avoid breathing fumes, cap tightly, and throw away bulging bottles. (p. 656)",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch18-024',
    standardId: 'CH18-F024',
    chapter_id: 'ch-18',
    front: "Lightener & Decolorization",
    back: "A chemical compound of bleach and hydrogen peroxide that disperses, dissolves, and decolorizes natural melanin. Hair passes through stages from dark red brown to pale yellow. (p. 656-657)",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-ch18-025',
    standardId: 'CH18-F025',
    chapter_id: 'ch-18',
    front: "Lightener Types: Cream, Powder & Oil",
    back: "Cream lighteners are popular on-the-scalp products. Powder lighteners are stronger and usually off-the-scalp. Oil lighteners are the mildest and may add temporary color. (p. 657-658)",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch18-026',
    standardId: 'CH18-F026',
    chapter_id: 'ch-18',
    front: "Toner",
    back: "A haircolor used on pre-lightened hair to refine tone or neutralize unwanted undertones. A toner may be semipermanent, demipermanent, or permanent haircolor. A patch test is required. (p. 659-660)",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch18-027',
    standardId: 'CH18-F027',
    chapter_id: 'ch-18',
    front: "Activator",
    back: "A powdered persulfate salt oxidizer added to haircolor, lightener, or peroxide to increase lifting power. Also called boosters, protinators, or accelerators. (p. 657)",
    category: "Developers, Lighteners & Toners",
    difficulty: 'medium',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch18-028',
    standardId: 'CH18-F028',
    chapter_id: 'ch-18',
    front: "Strand Test",
    back: "A test on a small section of hair to determine how the hair will react, how long it takes to process, and what the final color will look like. (p. 661, 680)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-ch18-029',
    standardId: 'CH18-F029',
    chapter_id: 'ch-18',
    front: "Single-Process vs. Double-Process Haircoloring",
    back: "Single-process lightens or deposits color in one application. Double-process lightens first, then applies a toner or tint in a second step. (p. 662-663)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-ch18-030',
    standardId: 'CH18-F030',
    chapter_id: 'ch-18',
    front: "Retouch Application & Line of Demarcation",
    back: "New growth creates a visible line of demarcation. A retouch applies color or lightener only to the new growth to blend it with previously treated hair. (p. 662)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-ch18-031',
    standardId: 'CH18-F031',
    chapter_id: 'ch-18',
    front: "Virgin Application, Tint Back & Pre-softening",
    back: "A virgin application colors hair that has never been colored. A tint back returns hair to its natural shade. Pre-softening opens resistant gray hair so color can penetrate. (p. 662, 663, 674)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch18-032',
    standardId: 'CH18-F032',
    chapter_id: 'ch-18',
    front: "Highlighting, Lowlighting & Special-Effect Techniques",
    back: "Highlighting lightens strands; lowlighting darkens strands. Common techniques include cap frost, foil frost, and free-form painting (balayage). (p. 663, 672)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch18-033',
    standardId: 'CH18-F033',
    chapter_id: 'ch-18',
    front: "Fillers",
    back: "Products that correct excessive porosity and create a color base in the hair, helping produce even color from scalp to ends. (p. 660)",
    category: "Corrective & Support Products",
    difficulty: 'medium',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch18-034',
    standardId: 'CH18-F034',
    chapter_id: 'ch-18',
    front: "Patch Test Safety Rule",
    back: "The FDA requires a patch test 24 to 48 hours before each application of an aniline derivative product. Do not perform the service if the test is positive. (p. 650, 676)",
    category: "Safety",
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-ch18-035',
    standardId: 'CH18-F035',
    chapter_id: 'ch-18',
    front: "Lightener Safety Rules",
    back: "Do not use lightener on irritated or abraded scalps. Do not overlap on previously lightened hair. Keep lightener moist during processing, and use cool water and mild shampoo after. (p. 657, 677)",
    category: "Safety",
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-ch18-036',
    standardId: 'CH18-F036',
    chapter_id: 'ch-18',
    front: "Facial Hair Coloring Safety",
    back: "Never use aniline derivative tints or metallic dyes on mustaches or beards. Use only products made for facial hair coloring and keep product off the skin. (p. 674, 698)",
    category: "Safety",
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch18-037',
    standardId: 'CH18-F037',
    chapter_id: 'ch-18',
    front: "Tertiary Colors",
    back: "Intermediate colors made by mixing a primary and a secondary color; examples include blue-green, blue-violet, red-violet, red-orange, yellow-green, and yellow-orange. (pp. 644-645)",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch18-038',
    standardId: 'CH18-F038',
    chapter_id: 'ch-18',
    front: "Neutralization with Complementary Colors",
    back: "Colors opposite each other on the color wheel neutralize or cancel each other when combined; used to tone down unwanted warm or cool reflects. (p. 645)",
    category: "Color Theory",
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch18-039',
    standardId: 'CH18-F039',
    chapter_id: 'ch-18',
    front: "Natural Hair Color / Gray & White Hair",
    back: "Natural color is created by eumelanin (brown/black) and pheomelanin (red/yellow); gray/white hair has little to no pigment and may be resistant or porous. (pp. 644, 672, 673)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-ch18-040',
    standardId: 'CH18-F040',
    chapter_id: 'ch-18',
    front: "Haircolor",
    back: "The product used to change, enhance, or blend the color of hair; distinct from the service term \"haircoloring.\" (pp. 701-703)",
    category: "Hair Analysis & Structure",
    difficulty: 'medium',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-ch18-041',
    standardId: 'CH18-F041',
    chapter_id: 'ch-18',
    front: "Oxidative vs. Nonoxidative Color",
    back: "Nonoxidative colors (temporary, semipermanent) do not require developer. Oxidative colors (demipermanent, permanent) mix with developer and use oxidation to develop color. (pp. 649-654)",
    category: "Haircolor Products",
    difficulty: 'medium',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch18-042',
    standardId: 'CH18-F042',
    chapter_id: 'ch-18',
    front: "Patch Test Procedure",
    back: "Apply a small amount of prepared color behind the ear or inside the elbow; leave 24-48 hours; examine for redness, burning, or swelling before service. (pp. 678-679)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-ch18-043',
    standardId: 'CH18-F043',
    chapter_id: 'ch-18',
    front: "Temporary Color Rinse Application",
    back: "Shampoo hair, apply rinse at the bowl, process briefly, and rinse; color shampoos out with the next wash. (pp. 682-683)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch18-044',
    standardId: 'CH18-F044',
    chapter_id: 'ch-18',
    front: "Semipermanent Color Application",
    back: "Apply to clean, towel-dried hair; no peroxide or developer; lasts about 6-8 shampoos; patch test required. (pp. 652, 666, 667)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch18-045',
    standardId: 'CH18-F045',
    chapter_id: 'ch-18',
    front: "Demipermanent Color Application",
    back: "Mix with low-volume developer; deposit-only; processes on towel-dried hair; lasts up to 24 shampoos; patch test required. (pp. 684-685)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch18-046',
    standardId: 'CH18-F046',
    chapter_id: 'ch-18',
    front: "Permanent Color Virgin & Retouch Application",
    back: "Virgin application covers all hair from scalp to ends; retouch applies color only to new growth to blend with previously colored hair and avoid banding. (pp. 686-688)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch18-047',
    standardId: 'CH18-F047',
    chapter_id: 'ch-18',
    front: "Mustache and Beard Coloring Procedure",
    back: "Use products made specifically for facial hair; apply petroleum jelly around the hairline; keep product off skin; follow manufacturer timing. (pp. 698-700)",
    category: "Application Terms & Procedures",
    difficulty: 'medium',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch18-048',
    standardId: 'CH18-F048',
    chapter_id: 'ch-18',
    front: "Scalp Safety & Abrasion Checks",
    back: "Inspect scalp for cuts, abrasions, inflammation, or disease before applying color; do not service compromised skin. (pp. 676-677)",
    category: "Safety",
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-ch18-049',
    standardId: 'CH18-F049',
    chapter_id: 'ch-18',
    front: "FDA Requirements / Predisposition Test",
    back: "Federal law requires a predisposition (patch) test 24-48 hours before applying aniline derivative haircolor to identify allergic reactions. (pp. 650, 676)",
    category: "Safety",
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch18-050',
    standardId: 'CH18-F050',
    chapter_id: 'ch-18',
    front: "General Chemical Precautions",
    back: "Use nonmetallic tools and bowls, keep bottles tightly capped, mix in ventilated areas, wear gloves, discard leftover mixed product, and follow all manufacturer directions. (pp. 656, 676, 677)",
    category: "Safety",
    difficulty: 'medium',
    order_index: 50,
    is_active: true,
  },
]