// Chapter 12: Men's Facial Massage and Treatments — PREMIUM MCQ QUIZ
// 45 questions generated STRICTLY from Chapter 12 premium flashcards
// Randomized question selection and answer order per attempt
// The Facial Mastery Certification Exam

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 12: FULL QUESTION BANK (45 questions)
// Generated from chapter-12-premium-flashcards.ts
// NATURAL answer distribution (NOT forced balanced)
// ───────────────────────────────────────────────
export const chapter12PremiumQuizQuestions: QuizQuestion[] = [
  // === INTRODUCTION & BENEFITS (3 questions) ===
  {
    id: 'qq-12-001',
    quiz_id: 'quiz-12',
    question: "Why should barbers study men's facial massage and treatments?",
    answer_a: 'To perform all licensed services and attract repeat clients through improved skin services',
    answer_b: 'Because it is required by federal law for all barbers',
    answer_c: 'To replace hair cutting as the primary barber service',
    answer_d: 'Because facial massage is only performed in medical clinics',
    correct_answer: 'a',
    explanation: 'Barbers need to be competent in all licensed services. Men increasingly want facial massage benefits, and facials improve skin tone, texture, and appearance, leading to repeat clients and referrals.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-12-002',
    quiz_id: 'quiz-12',
    question: "Approximately what percentage of skin care clientele in spas and salons are male?",
    answer_a: 'About 20 percent',
    answer_b: 'About 5 percent',
    answer_c: 'About 50 percent',
    answer_d: 'About 75 percent',
    correct_answer: 'a',
    explanation: 'About 20 percent of skin care clientele in spas and salons are male, and this percentage is expected to grow.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-12-003',
    quiz_id: 'quiz-12',
    question: "Facials are often used as finishing steps after which service?",
    answer_a: 'After a shave',
    answer_b: 'After a haircut only',
    answer_c: 'Before chemical treatments',
    answer_d: 'During hair coloring',
    correct_answer: 'a',
    explanation: 'Facials are finishing steps after a shave, helping to soothe and refresh the skin.',
    difficulty: 'easy',
    order_index: 3,
  },

  // === ANATOMY BASICS (4 questions) ===
  {
    id: 'qq-12-004',
    quiz_id: 'quiz-12',
    question: "What are the three subdermal systems associated with facial treatments?",
    answer_a: 'Muscles, nerves, and arteries',
    answer_b: 'Bones, ligaments, and tendons',
    answer_c: 'Skin, hair, and nails',
    answer_d: 'Veins, capillaries, and lymph nodes',
    correct_answer: 'a',
    explanation: 'The three subdermal systems are muscles (produce movement), nerves (carry messages), and arteries (transport blood under high pressure).',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-12-005',
    quiz_id: 'quiz-12',
    question: "What is the definition of a muscle?",
    answer_a: 'Fibrous tissues that stretch and contract to produce all body movements',
    answer_b: 'Thin-walled vessels that carry blood to the heart',
    answer_c: 'Cords that carry messages from the brain to the body',
    answer_d: 'Elastic tubes that transport blood under high pressure',
    correct_answer: 'a',
    explanation: 'Muscles are fibrous tissues that have the ability to stretch and contract to produce all body movements.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-12-006',
    quiz_id: 'quiz-12',
    question: "What is the definition of a nerve?",
    answer_a: 'Long, white, fibrous cords that carry messages to and from all parts of the body',
    answer_b: 'Thick-walled vessels that transport blood under high pressure',
    answer_c: 'Tissues that contract to produce body movement',
    answer_d: 'Thin-walled vessels with valves that prevent backward blood flow',
    correct_answer: 'a',
    explanation: 'Nerves are long, white, fibrous cords that act as message carriers from the brain and spinal column to and from all parts of the body.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-12-007',
    quiz_id: 'quiz-12',
    question: "What is the definition of a vein?",
    answer_a: 'Thin-walled vessels with valves that keep blood flowing to the heart',
    answer_b: 'Elastic, thick-walled vessels that transport blood under high pressure',
    answer_c: 'Fibrous tissues that contract to produce movement',
    answer_d: 'Cords that carry messages from the brain to the body',
    correct_answer: 'a',
    explanation: 'Veins are thin-walled vessels that contain valves to keep blood flowing to the heart and prevent backward flow.',
    difficulty: 'easy',
    order_index: 7,
  },

  // === MUSCLES (8 questions) ===
  {
    id: 'qq-12-008',
    quiz_id: 'quiz-12',
    question: "What is the epicranius (occipitofrontalis)?",
    answer_a: 'A broad muscle covering the top of the skull with frontalis and occipitalis parts',
    answer_b: 'A muscle surrounding the eye socket that closes the eyelid',
    answer_c: 'A chewing muscle that coordinates opening and closing of the mouth',
    answer_d: 'A muscle that covers the back of the neck and moves the shoulders',
    correct_answer: 'a',
    explanation: 'The epicranius is a broad muscle covering the top of the skull, consisting of the frontalis at the front and the occipitalis at the back, connected by the epicranial aponeurosis.',
    difficulty: 'medium',
    order_index: 8,
  },
  {
    id: 'qq-12-009',
    quiz_id: 'quiz-12',
    question: "What does the frontalis muscle do?",
    answer_a: 'Draws the scalp forward and causes wrinkles across the forehead',
    answer_b: 'Draws the scalp backward',
    answer_c: 'Closes the eyelid',
    answer_d: 'Compresses the cheeks and expels air',
    correct_answer: 'a',
    explanation: 'The frontalis draws the scalp forward and causes wrinkles across the forehead.',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-12-010',
    quiz_id: 'quiz-12',
    question: "What does the occipitalis muscle do?",
    answer_a: 'Draws the scalp backward',
    answer_b: 'Draws the scalp forward and wrinkles the forehead',
    answer_c: 'Surrounds the eye socket and closes the eyelid',
    answer_d: 'Pulls the mouth upward when laughing',
    correct_answer: 'a',
    explanation: 'The occipitalis draws the scalp backward.',
    difficulty: 'easy',
    order_index: 10,
  },
  {
    id: 'qq-12-011',
    quiz_id: 'quiz-12',
    question: "What is the epicranial aponeurosis?",
    answer_a: 'The tendon connecting the occipitalis and frontalis muscles',
    answer_b: 'A muscle that closes the eyelid',
    answer_c: 'A nerve controlling facial expressions',
    answer_d: 'An artery supplying blood to the scalp',
    correct_answer: 'a',
    explanation: 'The epicranial aponeurosis is the tendon that connects the occipitalis and frontalis muscles.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-12-012',
    quiz_id: 'quiz-12',
    question: "What does the orbicularis oculi muscle do?",
    answer_a: 'Surrounds the eye socket and closes the eyelid',
    answer_b: 'Draws the eyebrows down and wrinkles the forehead vertically',
    answer_c: 'Compresses the cheeks and expels air between the lips',
    answer_d: 'Coordinates opening and closing of the mouth',
    correct_answer: 'a',
    explanation: 'The orbicularis oculi surrounds the eye socket and closes the eyelid.',
    difficulty: 'easy',
    order_index: 12,
  },
  {
    id: 'qq-12-013',
    quiz_id: 'quiz-12',
    question: "What does the masseter muscle do?",
    answer_a: 'Coordinates opening and closing of the mouth as a chewing muscle',
    answer_b: 'Draws the scalp forward',
    answer_c: 'Surrounds the eye socket',
    answer_d: 'Moves the shoulders',
    correct_answer: 'a',
    explanation: 'The masseter coordinates opening and closing of the mouth and is a chewing muscle.',
    difficulty: 'easy',
    order_index: 13,
  },
  {
    id: 'qq-12-014',
    quiz_id: 'quiz-12',
    question: "What does the temporalis muscle do?",
    answer_a: 'Coordinates opening and closing of the mouth, working with the masseter',
    answer_b: 'Draws the scalp backward',
    answer_c: 'Compresses the cheeks',
    answer_d: 'Elevates the lower lip and wrinkles the chin',
    correct_answer: 'a',
    explanation: 'The temporalis coordinates opening and closing of the mouth and works with the masseter as a chewing muscle.',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-12-015',
    quiz_id: 'quiz-12',
    question: "What does the trapezius muscle do?",
    answer_a: 'Covers the back of the neck and allows movement of the shoulders',
    answer_b: 'Draws the scalp forward',
    answer_c: 'Surrounds the eye socket',
    answer_d: 'Compresses the cheeks and expels air',
    correct_answer: 'a',
    explanation: 'The trapezius covers the back of the neck, allowing movement of the shoulders.',
    difficulty: 'easy',
    order_index: 15,
  },

  // === CRANIAL NERVES (4 questions) ===
  {
    id: 'qq-12-016',
    quiz_id: 'quiz-12',
    question: "How many pairs of cranial nerves are there?",
    answer_a: '12 pairs',
    answer_b: '5 pairs',
    answer_c: '8 pairs',
    answer_d: '31 pairs',
    correct_answer: 'a',
    explanation: 'There are 12 pairs of cranial nerves, all connected to a part of the brain surface.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-12-017',
    quiz_id: 'quiz-12',
    question: "What is the fifth cranial nerve (trigeminal nerve)?",
    answer_a: 'The chief sensory nerve of the face that controls chewing',
    answer_b: 'The motor nerve that controls neck muscle motions',
    answer_c: 'The nerve that controls facial expressions and scalp motion',
    answer_d: 'A spinal nerve supplying the back of the head',
    correct_answer: 'a',
    explanation: 'The fifth cranial nerve (trigeminal) is the chief sensory nerve of the face and also serves as the motor nerve controlling chewing.',
    difficulty: 'medium',
    order_index: 17,
  },
  {
    id: 'qq-12-018',
    quiz_id: 'quiz-12',
    question: "What is the seventh cranial nerve (facial nerve)?",
    answer_a: 'The sensory-motor nerve controlling motions of the face, scalp, and neck',
    answer_b: 'The chief sensory nerve controlling chewing',
    answer_c: 'The motor nerve controlling neck muscles only',
    answer_d: 'A spinal nerve supplying the scalp at the back of the head',
    correct_answer: 'a',
    explanation: 'The seventh cranial nerve (facial nerve) is the sensory-motor nerve that controls motions of the face, scalp, and neck and sections of the palate and tongue.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-12-019',
    quiz_id: 'quiz-12',
    question: "What are cervical nerves?",
    answer_a: 'Spinal nerves whose branches supply muscles and scalp at the back of the head and neck',
    answer_b: 'Cranial nerves controlling facial expressions',
    answer_c: 'Nerves that control chewing motions',
    answer_d: 'Nerves that supply blood to the face',
    correct_answer: 'a',
    explanation: 'Cervical nerves are spinal nerves that originate at the spinal cord; their branches supply the muscles and scalp at the back of the head and neck.',
    difficulty: 'medium',
    order_index: 19,
  },

  // === CIRCULATION (4 questions) ===
  {
    id: 'qq-12-020',
    quiz_id: 'quiz-12',
    question: "What are the common carotid arteries?",
    answer_a: 'The main sources of blood supply to the head, face, and neck located at the sides of the neck',
    answer_b: 'Veins that return deoxygenated blood from the head to the heart',
    answer_c: 'Nerves controlling facial muscle movement',
    answer_d: 'Arteries supplying blood only to the lower face',
    correct_answer: 'a',
    explanation: 'The common carotid arteries are the main sources of blood supply to the head, face, and neck and are located at the sides of the neck.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'qq-12-021',
    quiz_id: 'quiz-12',
    question: "What does the superficial temporal artery supply?",
    answer_a: 'Muscles, skin, and scalp on the front, side, and top of the head',
    answer_b: 'The lower region of the face, mouth, and nose only',
    answer_c: 'The scalp and back of the head up to the crown',
    answer_d: 'The scalp behind and above the ear only',
    correct_answer: 'a',
    explanation: 'The superficial temporal artery supplies muscles, skin, and scalp on the front, side, and top of the head.',
    difficulty: 'medium',
    order_index: 21,
  },
  {
    id: 'qq-12-022',
    quiz_id: 'quiz-12',
    question: "What does the occipital artery supply?",
    answer_a: 'The scalp and back of the head up to the crown',
    answer_b: 'The lower region of the face and mouth',
    answer_c: 'Muscles and skin on the front and side of the head',
    answer_d: 'The scalp behind and above the ear only',
    correct_answer: 'a',
    explanation: 'The occipital artery supplies the scalp and back of the head up to the crown.',
    difficulty: 'medium',
    order_index: 22,
  },
  {
    id: 'qq-12-023',
    quiz_id: 'quiz-12',
    question: "How does deoxygenated blood from the head, face, and neck return to the heart?",
    answer_a: 'Through the internal jugular and external jugular veins on each side of the neck',
    answer_b: 'Through the common carotid arteries',
    answer_c: 'Through the superficial temporal arteries',
    answer_d: 'Through the cervical nerves',
    correct_answer: 'a',
    explanation: 'Deoxygenated blood returns through the internal jugular and external jugular veins located on each side of the neck.',
    difficulty: 'medium',
    order_index: 23,
  },

  // === MASSAGE THEORY (3 questions) ===
  {
    id: 'qq-12-024',
    quiz_id: 'quiz-12',
    question: "What are beneficial results of proper massage?",
    answer_a: 'Nourishes skin, stimulates muscles, soothes nerves, increases circulation, and softens skin',
    answer_b: 'Removes all facial hair permanently',
    answer_c: 'Changes the bone structure of the face',
    answer_d: 'Eliminates the need for daily cleansing',
    correct_answer: 'a',
    explanation: 'Proper massage nourishes skin structures, stimulates muscle fiber, soothes nerves, increases blood circulation, stimulates gland activity, softens skin, and sometimes relieves pain.',
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-12-025',
    quiz_id: 'quiz-12',
    question: "What is a motor point?",
    answer_a: 'A point on the skin where nerves controlling the underlying muscle are located',
    answer_b: 'The center of a muscle where blood flow is highest',
    answer_c: 'A trigger point that radiates pain to other locations',
    answer_d: 'The insertion point where a muscle attaches to bone',
    correct_answer: 'a',
    explanation: 'A motor point is a point on the skin where nerves that control the underlying muscle are located. When electrical stimulation is applied, the muscle responds by contracting.',
    difficulty: 'medium',
    order_index: 25,
  },
  {
    id: 'qq-12-026',
    quiz_id: 'quiz-12',
    question: "What is a trigger point?",
    answer_a: 'A tender area in a muscle caused by a localized knot that can radiate pain',
    answer_b: 'A point where nerves control underlying muscles',
    answer_c: 'The origin point where a muscle attaches to immovable bone',
    answer_d: 'A point on the skin with maximum blood circulation',
    correct_answer: 'a',
    explanation: 'A trigger point is a tender area in a muscle caused by a localized knot or spasm that can radiate pain to other locations. It is hypersensitive to electrical stimulation and pressure.',
    difficulty: 'medium',
    order_index: 26,
  },

  // === MASSAGE MOVEMENTS (6 questions) ===
  {
    id: 'qq-12-027',
    quiz_id: 'quiz-12',
    question: "What is effleurage?",
    answer_a: 'A light, continuous stroking movement applied slowly with no pressure',
    answer_b: 'A kneading movement with light, firm pressure',
    answer_c: 'Short, quick tapping movements to stimulate nerves',
    answer_d: 'A rapid shaking movement over the skin',
    correct_answer: 'a',
    explanation: 'Effleurage is a light, continuous stroking movement applied slowly and rhythmically over the skin with no pressure. Palms are used over large surfaces; fingertips work small surfaces.',
    difficulty: 'easy',
    order_index: 27,
  },
  {
    id: 'qq-12-028',
    quiz_id: 'quiz-12',
    question: "What is petrissage?",
    answer_a: 'A kneading movement performed with light, firm pressure by grasping and gently squeezing the skin',
    answer_b: 'A light, continuous stroking movement with no pressure',
    answer_c: 'Short, quick tapping movements to stimulate nerves',
    answer_d: 'A deep rubbing movement over underlying structures',
    correct_answer: 'a',
    explanation: 'Petrissage is a kneading movement performed with light, firm pressure. The skin and flesh are grasped between the thumb and fingers, then gently squeezed, rolled, or pinched.',
    difficulty: 'easy',
    order_index: 28,
  },
  {
    id: 'qq-12-029',
    quiz_id: 'quiz-12',
    question: "What is friction in massage?",
    answer_a: 'A deep rubbing movement with pressure applied while moving over an underlying structure',
    answer_b: 'A light, continuous stroking movement',
    answer_c: 'Short, quick tapping or slapping movements',
    answer_d: 'A rapid shaking movement with fingertips',
    correct_answer: 'a',
    explanation: 'Friction is a deep rubbing movement in which pressure is applied on the skin with the fingers or palms while moving over an underlying structure. Light circular friction is used on the face and neck.',
    difficulty: 'easy',
    order_index: 29,
  },
  {
    id: 'qq-12-030',
    quiz_id: 'quiz-12',
    question: "What is percussion (tapotement)?",
    answer_a: 'Short, quick tapping, slapping, or hacking movements used to stimulate nerves and tone muscles',
    answer_b: 'A light, continuous stroking movement with no pressure',
    answer_c: 'A kneading movement with firm pressure',
    answer_d: 'A deep rubbing movement over underlying structures',
    correct_answer: 'a',
    explanation: 'Percussion (tapotement) consists of short, quick tapping, slapping, or hacking movements used to stimulate nerves, tone muscles, and impart a healthy glow. It is the most stimulating form of massage.',
    difficulty: 'easy',
    order_index: 30,
  },
  {
    id: 'qq-12-031',
    quiz_id: 'quiz-12',
    question: "What is vibration in massage?",
    answer_a: 'A rapid shaking movement over the skin with fingertips or an electric massager',
    answer_b: 'A kneading movement with light, firm pressure',
    answer_c: 'Short, quick tapping movements to stimulate nerves',
    answer_d: 'A deep rubbing movement with sustained pressure',
    correct_answer: 'a',
    explanation: 'Vibration is a rapid shaking movement over the skin section with the fingertips or an electric massager, used to transmit a trembling movement to the skin and underlying structures.',
    difficulty: 'easy',
    order_index: 31,
  },
  {
    id: 'qq-12-032',
    quiz_id: 'quiz-12',
    question: "How long should vibration be used on any one area?",
    answer_a: 'Not more than a few seconds to avoid overstimulation',
    answer_b: 'At least 5 minutes for maximum benefit',
    answer_c: 'Until the client requests stopping',
    answer_d: 'For the entire duration of the massage',
    correct_answer: 'a',
    explanation: 'Vibration should not be used more than a few seconds on any one area to avoid overstimulation.',
    difficulty: 'easy',
    order_index: 32,
  },

  // === MASSAGE GUIDELINES (3 questions) ===
  {
    id: 'qq-12-033',
    quiz_id: 'quiz-12',
    question: "What direction should massage pressure be applied on the face?",
    answer_a: 'In an upward direction to avoid loss of skin resiliency',
    answer_b: 'In a downward direction to follow gravity',
    answer_c: 'In circular motions only, regardless of direction',
    answer_d: 'Against the direction of beard growth only',
    correct_answer: 'a',
    explanation: 'Massage pressure on the face should be applied in an upward direction to avoid loss of skin resiliency. When facial hair is present, direct movements in the direction of beard growth.',
    difficulty: 'easy',
    order_index: 33,
  },
  {
    id: 'qq-12-034',
    quiz_id: 'quiz-12',
    question: "What is feathering-off?",
    answer_a: 'Gradually reducing pressure when removing hands from the client\'s face',
    answer_b: 'Applying rapid vibration at the end of a massage',
    answer_c: 'Using light tapping movements to finish a treatment',
    answer_d: 'Removing excess product with a feather-like tool',
    correct_answer: 'a',
    explanation: 'Feathering-off is gradually reducing pressure when removing hands from the client\'s face to gently lift from the skin surface.',
    difficulty: 'easy',
    order_index: 34,
  },
  {
    id: 'qq-12-035',
    quiz_id: 'quiz-12',
    question: "Which condition contraindicates massage?",
    answer_a: 'Acute inflammation of the skin or high blood pressure',
    answer_b: 'Normal skin with good water-oil balance',
    answer_c: 'Slightly dry skin on the cheeks',
    answer_d: 'Mild tension in the shoulders',
    correct_answer: 'a',
    explanation: 'Conditions that contraindicate massage include acute inflammation of the skin, severe skin lesions, pus-containing pimples, high blood pressure, and skin infections.',
    difficulty: 'easy',
    order_index: 35,
  },

  // === EQUIPMENT (3 questions) ===
  {
    id: 'qq-12-036',
    quiz_id: 'quiz-12',
    question: "What is an electric massager used for?",
    answer_a: 'Transmitting vibrations to the client\'s skin and muscles over heavy muscle tissue',
    answer_b: 'Applying chemical peels to exfoliate the skin',
    answer_c: 'Removing facial hair permanently',
    answer_d: 'Injecting moisturizers into the skin',
    correct_answer: 'a',
    explanation: 'An electric massager is a handheld unit that transmits vibrations through the barber\'s hand and fingertips to the client\'s skin and muscles, used over heavy muscle tissue like the scalp and shoulders.',
    difficulty: 'easy',
    order_index: 36,
  },
  {
    id: 'qq-12-037',
    quiz_id: 'quiz-12',
    question: "What type of water should be used in a facial steamer?",
    answer_a: 'Only distilled or filtered water',
    answer_b: 'Tap water only',
    answer_c: 'Salt water for antiseptic effect',
    answer_d: 'Mineral water for extra nutrients',
    correct_answer: 'a',
    explanation: 'Only distilled or filtered water should be used in a facial steamer to avoid mineral and calcium deposits that can damage the unit.',
    difficulty: 'easy',
    order_index: 37,
  },
  {
    id: 'qq-12-038',
    quiz_id: 'quiz-12',
    question: "What is a hot-towel cabinet used for?",
    answer_a: 'Ensuring a ready supply of warm towels for facial services',
    answer_b: 'Storing cleaning chemicals at a safe temperature',
    answer_c: 'Heating facial products before application',
    answer_d: 'Drying used towels quickly between clients',
    correct_answer: 'a',
    explanation: 'A hot-towel cabinet ensures a ready supply of warm towels for facial services. Towels are folded, dampened with hot water, wrung out, and placed in the cabinet.',
    difficulty: 'easy',
    order_index: 38,
  },

  // === ELECTROTHERAPY (5 questions) ===
  {
    id: 'qq-12-039',
    quiz_id: 'quiz-12',
    question: "What are the two electrotherapy modalities most often used in facial treatments?",
    answer_a: 'High-frequency current and galvanic current',
    answer_b: 'Ultraviolet and infrared light only',
    answer_c: 'Microcurrent and LED therapy only',
    answer_d: 'Steam and hot towels only',
    correct_answer: 'a',
    explanation: 'The two electrotherapy modalities most often used in facial treatments are high-frequency current and galvanic current.',
    difficulty: 'easy',
    order_index: 39,
  },
  {
    id: 'qq-12-040',
    quiz_id: 'quiz-12',
    question: "What is high-frequency current (tesla current)?",
    answer_a: 'A current with a high rate of oscillation used for scalp and facial treatments',
    answer_b: 'A low-level current used only for toning aging skin',
    answer_c: 'A current that converts AC into DC for chemical reactions',
    answer_d: 'A heat-only treatment using infrared lamps',
    correct_answer: 'a',
    explanation: 'High-frequency current (tesla current) is characterized by a high rate of oscillation and is used for scalp and facial treatments. Its primary actions are thermal and antiseptic.',
    difficulty: 'medium',
    order_index: 40,
  },
  {
    id: 'qq-12-041',
    quiz_id: 'quiz-12',
    question: "How long should a general high-frequency facial or scalp treatment last?",
    answer_a: 'No more than 5 minutes',
    answer_b: 'At least 15 minutes',
    answer_c: 'Exactly 10 minutes',
    answer_d: 'Until the client feels warmth',
    correct_answer: 'a',
    explanation: 'A general high-frequency facial or scalp treatment should last no more than 5 minutes.',
    difficulty: 'easy',
    order_index: 41,
  },
  {
    id: 'qq-12-042',
    quiz_id: 'quiz-12',
    question: "What is desincrustation?",
    answer_a: 'A galvanic treatment to facilitate deep pore cleansing by emulsifying sebum',
    answer_b: 'A high-frequency treatment for antiseptic action',
    answer_c: 'A massage movement using rapid vibration',
    answer_d: 'A light therapy treatment using LED lights',
    correct_answer: 'a',
    explanation: 'Desincrustation is a galvanic treatment to facilitate deep pore cleansing. An acid-based solution is applied, and a chemical reaction emulsifies sebum and waste for easy extraction.',
    difficulty: 'medium',
    order_index: 42,
  },
  {
    id: 'qq-12-043',
    quiz_id: 'quiz-12',
    question: "What is microcurrent?",
    answer_a: 'A galvanic treatment using very low-level electrical current for toning and lifting',
    answer_b: 'A high-frequency current with rapid oscillation',
    answer_c: 'A mechanical exfoliation using microcrystals',
    answer_d: 'A heat treatment using infrared lamps',
    correct_answer: 'a',
    explanation: 'Microcurrent is a type of galvanic treatment using very low-level electrical current, best known for toning skin and producing a lifting effect on aging skin lacking elasticity.',
    difficulty: 'medium',
    order_index: 43,
  },

  // === SKIN TYPES (4 questions) ===
  {
    id: 'qq-12-044',
    quiz_id: 'quiz-12',
    question: "What are the four basic skin types?",
    answer_a: 'Dry, normal, combination, and oily',
    answer_b: 'Sensitive, acne-prone, mature, and sun-damaged',
    answer_c: 'Fair, medium, olive, and dark',
    answer_d: 'Tight, loose, rough, and smooth',
    correct_answer: 'a',
    explanation: 'The four basic skin types are dry (alipidic), normal, combination, and oily.',
    difficulty: 'easy',
    order_index: 44,
  },
  {
    id: 'qq-12-045',
    quiz_id: 'quiz-12',
    question: "What characterizes combination skin?",
    answer_a: 'Both oily and dry in different areas, with T-zone typically oily',
    answer_b: 'Excess sebum production all over the face',
    answer_c: 'Good water-oil balance with normal pore size',
    answer_d: 'Dehydrated skin that appears flaky with fine lines',
    correct_answer: 'a',
    explanation: 'Combination skin has both oily and dry areas. The T-zone (forehead, nose, chin) tends to be oily, while cheeks and outer areas tend to be dry.',
    difficulty: 'easy',
    order_index: 45,
  },
]

export default chapter12PremiumQuizQuestions
