// Chapter 2 Premium Quiz — Flashcard-Driven Multiple Choice System
// Life Skills — 39 questions generated from Chapter 2 flashcard curriculum
// Randomized order, randomized answers, board-exam style
// Source: chapter-2-premium-flashcards.ts (50 cards)

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 2 QUIZ: Life Skills (39 Questions)
// Difficulty mix: 14 easy, 15 medium, 10 hard
// Correct answer distribution: A=8, B=15, C=9, D=7
// Sources: Foundation, Definitions, Board Exam, Visual ID, Scenarios, Procedures, Safety, Memory
// ───────────────────────────────────────────────

export const chapter2PremiumQuizQuestions: QuizQuestion[] = [
  // ═══════════════════════════════════════════════════════════
  // EASY QUESTIONS (10) — Correct: A=3, B=2, C=3, D=2
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-2-001',
    quiz_id: 'quiz-2',
    question: 'According to Chapter 2, what percentage of barber success comes from life and business skills?',
    answer_a: '60%',
    answer_b: '40%',
    answer_c: '75%',
    answer_d: '50%',
    correct_answer: 'a',
    explanation: '60% of barber success comes from life and business skills. Only 40% comes from technical skills like cutting, styling, and sanitation.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-2-002',
    quiz_id: 'quiz-2',
    question: 'What does the "T" in SMART goals stand for?',
    answer_a: 'Time-bound',
    answer_b: 'Targeted',
    answer_c: 'Tactical',
    answer_d: 'Trackable',
    correct_answer: 'a',
    explanation: 'The T in SMART stands for Time-bound — setting a deadline like "By December 31st" creates urgency and focus.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-2-003',
    quiz_id: 'quiz-2',
    question: 'According to the 50/30/20 rule, what percentage of income should go to savings and debt repayment?',
    answer_a: '20%',
    answer_b: '10%',
    answer_c: '30%',
    answer_d: '50%',
    correct_answer: 'a',
    explanation: 'The 50/30/20 rule allocates 50% to needs, 30% to wants, and 20% to savings and debt repayment.',
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-2-004',
    quiz_id: 'quiz-2',
    question: 'What is the recommended starting amount for an emergency fund?',
    answer_a: '$1,000',
    answer_b: '$500',
    answer_c: '$5,000',
    answer_d: '$2,500',
    correct_answer: 'a',
    explanation: 'The chapter recommends starting with a $1,000 mini emergency fund, then building to 3 months of expenses, and eventually 6 months.',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-2-005',
    quiz_id: 'quiz-2',
    question: 'What is the 2-Minute Rule for time management?',
    answer_a: 'Take a 2-minute break every hour',
    answer_b: 'If a task takes less than 2 minutes, do it immediately',
    answer_c: 'Spend 2 minutes planning each morning',
    answer_d: 'Limit social media to 2 minutes per day',
    correct_answer: 'b',
    explanation: 'The 2-Minute Rule states that if a task takes less than 2 minutes, do it immediately rather than letting small tasks pile up.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-2-006',
    quiz_id: 'quiz-2',
    question: 'Which of the following is NOT one of the three destructive habits that kill productivity?',
    answer_a: 'Time management',
    answer_b: 'Procrastination',
    answer_c: 'Perfectionism',
    answer_d: 'Lack of a game plan',
    correct_answer: 'a',
    explanation: 'The three productivity killers are procrastination, perfectionism, and lack of a game plan. Time management is a solution, not a problem.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-2-007',
    quiz_id: 'quiz-2',
    question: 'What is a mission statement?',
    answer_a: 'A financial tracking spreadsheet',
    answer_b: 'A definition of your purpose, values, and direction',
    answer_c: 'A list of daily tasks',
    answer_d: 'A client appointment schedule',
    correct_answer: 'b',
    explanation: 'A mission statement defines your purpose, values, and direction. It provides focus and becomes the "cultural pulse" of your professional life.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-2-008',
    quiz_id: 'quiz-2',
    question: 'What is the Pomodoro Technique?',
    answer_a: 'Working until a task is finished without breaks',
    answer_b: '25 minutes of focused work followed by a short break',
    answer_c: 'A 2-hour deep work session',
    answer_d: 'Studying for 50 minutes then resting for 10',
    correct_answer: 'b',
    explanation: 'The Pomodoro Technique uses 25-minute focused work blocks followed by a 5-minute break. After four cycles, take a longer 15-30 minute break.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-2-009',
    quiz_id: 'quiz-2',
    question: 'How long are short-term goals typically accomplished?',
    answer_a: '5-10 years',
    answer_b: 'In a year or less',
    answer_c: '2-5 years',
    answer_d: '10+ years',
    correct_answer: 'b',
    explanation: 'Short-term goals are accomplished in one year or less (e.g., passing an exam, graduating school). Long-term goals span two or more years.',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-2-010',
    quiz_id: 'quiz-2',
    question: 'What is active listening?',
    answer_a: 'Nodding occasionally while looking at your phone',
    answer_b: 'Fully concentrating on what is being said and responding appropriately',
    answer_c: 'Hearing the client while thinking about your next cut',
    answer_d: 'Interrupting to ask clarifying questions immediately',
    correct_answer: 'b',
    explanation: 'Active listening is fully concentrating on what is being said, processing the message, and responding appropriately. It prevents misunderstandings during consultations.',
    difficulty: 'easy',
    order_index: 10,
  },

  // ═══════════════════════════════════════════════════════════
  // MEDIUM QUESTIONS (10) — Correct: A=2, B=3, C=2, D=3
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-2-011',
    quiz_id: 'quiz-2',
    question: 'Which of the following is the best example of a SMART goal?',
    answer_a: '"Be the best barber ever"',
    answer_b: '"Complete 100 practice fades by December 31st"',
    answer_c: '"Get better at cutting hair"',
    answer_d: '"Make more money this year"',
    correct_answer: 'b',
    explanation: '"Complete 100 practice fades by December 31st" is Specific, Measurable, Achievable, Relevant, and Time-bound. The other options are vague and lack measurable criteria.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-2-012',
    quiz_id: 'quiz-2',
    question: 'What percentage of income should booth renters set aside for taxes?',
    answer_a: '25-30%',
    answer_b: '10-15%',
    answer_c: '15-20%',
    answer_d: '5-10%',
    correct_answer: 'a',
    explanation: 'Booth renters should set aside 25-30% of income for taxes since they are self-employed and responsible for their own tax payments, including self-employment tax.',
    difficulty: 'medium',
    order_index: 12,
  },
  {
    id: 'qq-2-013',
    quiz_id: 'quiz-2',
    question: 'Which networking approach is most effective according to Chapter 2?',
    answer_a: 'Only network once you have experience',
    answer_b: 'Give first and build genuine relationships',
    answer_c: 'Ask for favors immediately upon meeting',
    answer_d: 'Only network at formal industry events',
    correct_answer: 'b',
    explanation: 'The chapter emphasizes giving first — sharing knowledge, making introductions, and offering help before asking for anything — as the foundation of effective networking.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-2-014',
    quiz_id: 'quiz-2',
    question: 'What is diplomacy (tact) in professional communication?',
    answer_a: 'Avoiding all difficult conversations',
    answer_b: 'Delivering truthful messages in a kind, respectful manner',
    answer_c: 'Telling clients exactly what they want to hear',
    answer_d: 'Using formal language exclusively',
    correct_answer: 'b',
    explanation: 'Diplomacy is delivering truthful messages and feedback in a kind, respectful manner that preserves relationships and avoids unnecessary conflict.',
    difficulty: 'medium',
    order_index: 14,
  },
  {
    id: 'qq-2-015',
    quiz_id: 'quiz-2',
    question: 'Why is continuing education considered an ethical responsibility?',
    answer_a: 'It is only required to renew licenses',
    answer_b: 'Barbers must stay current with techniques and standards to serve clients competently',
    answer_c: 'It is optional and not ethically relevant',
    answer_d: 'It is only for barbers who want to teach',
    correct_answer: 'b',
    explanation: 'Participating in continuing education ensures barbers maintain skilled and competent services, which is a core ethical obligation to clients.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-2-016',
    quiz_id: 'quiz-2',
    question: 'What is the first step in the complaint recovery system?',
    answer_a: 'Offer a refund immediately',
    answer_b: 'Listen without defending',
    answer_c: 'Explain why the mistake happened',
    answer_d: 'Ask the client to leave',
    correct_answer: 'b',
    explanation: 'The first step is to listen fully without interrupting or defending. Let the client express their concerns completely before offering solutions.',
    difficulty: 'medium',
    order_index: 16,
  },
  {
    id: 'qq-2-017',
    quiz_id: 'quiz-2',
    question: 'Which of the following is a warning sign of burnout?',
    answer_a: 'Arriving early to work',
    answer_b: 'Dreading work',
    answer_c: 'Learning new techniques',
    answer_d: 'Building client relationships',
    correct_answer: 'b',
    explanation: 'Dreading work is a key warning sign of burnout. Other signs include chronic fatigue, irritability with clients, physical aches, and loss of creativity.',
    difficulty: 'medium',
    order_index: 17,
  },
  {
    id: 'qq-2-018',
    quiz_id: 'quiz-2',
    question: 'What is the service recovery paradox?',
    answer_a: 'Clients who complain are always lost forever',
    answer_b: 'Clients whose problems are resolved well often become more loyal than those who never had problems',
    answer_c: 'It is cheaper to lose a client than to fix a mistake',
    answer_d: 'Complaints should be ignored to avoid liability',
    correct_answer: 'b',
    explanation: 'The service recovery paradox states that clients whose problems are resolved professionally often become MORE loyal than clients who never experienced issues.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-2-019',
    quiz_id: 'quiz-2',
    question: 'What is the most important rule of shop etiquette regarding another barber\'s regular clients?',
    answer_a: 'Accept every walk-in regardless of whose client they are',
    answer_b: 'Never poach another barber\'s regular clients',
    answer_c: 'Only serve your own regulars',
    answer_d: 'Encourage clients to switch barbers frequently',
    correct_answer: 'b',
    explanation: 'Never solicit another barber\'s regular clients. If their client asks you for a cut, redirect them back to their regular barber. Violating this destroys shop harmony.',
    difficulty: 'medium',
    order_index: 19,
  },
  {
    id: 'qq-2-020',
    quiz_id: 'quiz-2',
    question: 'What is the difference between motivation and discipline?',
    answer_a: 'Motivation is permanent; discipline is temporary',
    answer_b: 'Motivation is a feeling; discipline is a habit system that works without feelings',
    answer_c: 'They are the same thing',
    answer_d: 'Discipline is only needed for athletes',
    correct_answer: 'b',
    explanation: 'Motivation is temporary excitement. Discipline is the habit system that keeps you going even when motivation fades.',
    difficulty: 'medium',
    order_index: 20,
  },

  // ═══════════════════════════════════════════════════════════
  // HARD QUESTIONS (10) — Correct: A=3, B=3, C=2, D=2
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-2-021',
    quiz_id: 'quiz-2',
    question: 'Which of the following is NOT one of the seven essential life skills for barber success?',
    answer_a: 'Communication',
    answer_b: 'Advanced chemistry',
    answer_c: 'Decision-making',
    answer_d: 'Time management',
    correct_answer: 'b',
    explanation: 'The seven essential life skills are communication, decision-making, image-building, customer service, self-actualization, goal-setting, and time management. Advanced chemistry is a technical skill, not a life skill.',
    difficulty: 'hard',
    order_index: 21,
  },
  {
    id: 'qq-2-022',
    quiz_id: 'quiz-2',
    question: 'A client is unhappy with their haircut and raises their voice. According to the complaint recovery procedure, what should you AVOID saying?',
    answer_a: '"Let me fix this for you"',
    answer_b: '"You said you wanted it this way"',
    answer_c: '"I understand why you are disappointed"',
    answer_d: '"I apologize for the misunderstanding"',
    correct_answer: 'b',
    explanation: 'Blaming the client with phrases like "You said..." escalates tension. Instead, take responsibility and focus on solutions.',
    difficulty: 'hard',
    order_index: 22,
  },
  {
    id: 'qq-2-023',
    quiz_id: 'quiz-2',
    question: 'What is self-actualization, and why does it require lifelong commitment?',
    answer_a: 'Getting a job promotion; climbing the career ladder',
    answer_b: 'Fulfilling your full potential; personal growth is continuous',
    answer_c: 'Making lots of money; it takes time to build wealth',
    answer_d: 'Graduating from barber school; education is ongoing',
    correct_answer: 'b',
    explanation: 'Self-actualization is fulfilling your full potential. It requires lifelong commitment because personal growth, skill development, and career advancement are continuous processes.',
    difficulty: 'hard',
    order_index: 23,
  },
  {
    id: 'qq-2-024',
    quiz_id: 'quiz-2',
    question: 'How does financial stress specifically create safety hazards in a barbershop?',
    answer_a: 'It causes barbers to work fewer hours',
    answer_b: 'It leads to rushed services, skipped sanitation, and overbooking',
    answer_c: 'It makes barbers refuse to serve difficult clients',
    answer_d: 'It forces barbers to use cheaper but safer products',
    correct_answer: 'b',
    explanation: 'Financial stress causes distraction, rushed services, and corner-cutting. A barber worried about rent may rush sanitation, skip tool maintenance, or overbook clients — all safety hazards.',
    difficulty: 'hard',
    order_index: 24,
  },
  {
    id: 'qq-2-025',
    quiz_id: 'quiz-2',
    question: 'What are the three components of effective communication that barbers must master?',
    answer_a: 'Speaking loudly, using technical terms, and giving advice',
    answer_b: 'Verbal communication, nonverbal communication, and active listening',
    answer_c: 'Social media, email, and text messaging',
    answer_d: 'Consultation, cutting, and styling',
    correct_answer: 'b',
    explanation: 'The three components are verbal communication (clear, professional language), nonverbal communication (body language, posture, eye contact), and active listening (fully concentrating and responding appropriately).',
    difficulty: 'hard',
    order_index: 25,
  },
  {
    id: 'qq-2-026',
    quiz_id: 'quiz-2',
    question: 'What is the proper procedure for managing time when a barbershop has both appointments and walk-ins?',
    answer_a: 'Serve walk-ins first to avoid losing them',
    answer_b: 'Arrive early, build buffer time, communicate wait times honestly, and coordinate with the team',
    answer_c: 'Accept only appointments to maintain control',
    answer_d: 'Rush through appointments to fit in walk-ins',
    correct_answer: 'b',
    explanation: 'Proper time management includes arriving early, building 5-10 minute buffers, communicating honest wait times, handling add-ons efficiently, coordinating with the team, and ending on time.',
    difficulty: 'hard',
    order_index: 26,
  },
  {
    id: 'qq-2-027',
    quiz_id: 'quiz-2',
    question: 'Which of the following is NOT one of the five professional ethics actions every barber must practice?',
    answer_a: 'Provide skilled and competent services',
    answer_b: 'Recommend the most expensive products to increase revenue',
    answer_c: 'Keep client information confidential',
    answer_d: 'Participate in continuing education',
    correct_answer: 'b',
    explanation: 'The five ethics actions are: provide skilled services, be honest/courteous/sincere, keep client information confidential, participate in continuing education, and give accurate information. Recommending expensive products for revenue violates ethics.',
    difficulty: 'hard',
    order_index: 27,
  },
  {
    id: 'qq-2-028',
    quiz_id: 'quiz-2',
    question: 'What is the recommended procedure for creating an effective study schedule as a barber student?',
    answer_a: 'Cram all night before exams',
    answer_b: 'Identify alert hours, use Pomodoro sessions, schedule spaced repetition, include practice time, plan rest days',
    answer_c: 'Study only on weekends for long sessions',
    answer_d: 'Focus only on theory and skip hands-on practice',
    correct_answer: 'b',
    explanation: 'An effective study schedule includes identifying alert hours, blocking 25-50 minute Pomodoro sessions, scheduling spaced repetition review, including hands-on practice, planning rest days, and adjusting weekly.',
    difficulty: 'hard',
    order_index: 28,
  },
  {
    id: 'qq-2-029',
    quiz_id: 'quiz-2',
    question: 'Why is emotional stability considered a safety concept in barbering?',
    answer_a: 'It helps barbers win arguments with clients',
    answer_b: 'It prevents aggressive responses and escalating conflicts',
    answer_c: 'It eliminates the need for breaks during the workday',
    answer_d: 'Only managers need emotional stability',
    correct_answer: 'b',
    explanation: 'Emotional reactivity can lead to aggressive responses, escalating conflicts, and potentially violent situations. Emotional stability protects both physical and professional safety.',
    difficulty: 'hard',
    order_index: 29,
  },
  {
    id: 'qq-2-030',
    quiz_id: 'quiz-2',
    question: 'What are the four memory and study techniques recommended for barber students?',
    answer_a: 'Cramming, guessing, skipping hard topics, and copying notes',
    answer_b: 'Repetition, organization, mnemonics, and mind mapping',
    answer_c: 'Sleeping with textbooks, listening to loud music, studying alone, and avoiding practice',
    answer_d: 'Memorizing only, ignoring hands-on training, avoiding review, and skipping quizzes',
    correct_answer: 'b',
    explanation: 'The four techniques are repetition (verbal, written, hands-on), organization (breaking topics into segments), mnemonics (acronyms, word associations), and mind mapping (visual branching from central topics).',
    difficulty: 'hard',
    order_index: 30,
  },

  // ═══════════════════════════════════════════════════════════
  // PHASE 5A ADDITIONS — C-2-07 Goal Tracking & Achievement
  // Added 2026-08-16 per ASCYN_PRO_CH02_PHASE5A_C-2-07_CHECKPOINT.md
  // Addresses GAP-3: C-2-07 zero quiz coverage
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-2-031',
    quiz_id: 'quiz-2',
    question: 'A barber student sets a goal to "build a full client book within 12 months of graduating." After 3 months, they have only 5 regular clients. According to Chapter 2\'s goal-tracking principles, what should the student do first?',
    answer_a: 'Abandon the goal and set a smaller one',
    answer_b: 'Review their progress data, identify what is and isn\'t working, and adjust their action steps',
    answer_c: 'Work longer hours without changing their approach',
    answer_d: 'Wait until the 6-month mark before evaluating progress',
    correct_answer: 'b',
    explanation: 'Goal tracking requires regular progress review and adjustment. The chapter teaches that tracking systems (journals, visual trackers, accountability partners) exist precisely so you can identify shortfalls early and adjust your action steps — not abandon the goal or ignore the data. Waiting longer without evaluating wastes time; working harder without changing approach repeats the same results.',
    difficulty: 'medium',
    order_index: 31,
  },
  {
    id: 'qq-2-032',
    quiz_id: 'quiz-2',
    question: 'Which of the following is NOT a recommended goal-tracking method according to Chapter 2?',
    answer_a: 'Keeping a daily progress journal',
    answer_b: 'Using visual trackers like charts or apps',
    answer_c: 'Relying on memory alone to recall weekly progress',
    answer_d: 'Sharing goals with an accountability partner',
    correct_answer: 'c',
    explanation: 'Chapter 2 recommends three specific tracking methods: progress journals (write daily accomplishments), visual trackers (charts, calendars, apps showing streaks/milestones), and accountability partners (someone who checks in on your progress). Relying on memory alone is not a tracking system — it provides no external record, no visible momentum, and no accountability structure.',
    difficulty: 'easy',
    order_index: 32,
  },
  // ═══════════════════════════════════════════════════════════
  // Added 2026-08-16 per ASCYN_PRO_CH02_PHASE5A_C-2-13_CHECKPOINT.md
  // Addresses GAP-4: C-2-13 zero quiz coverage
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-2-034',
    quiz_id: 'quiz-2',
    question: 'A client mentions during their haircut that they are going through a divorce. Which of the following best describes your professional obligation?',
    answer_a: 'You may share this with coworkers if they promise not to tell anyone else',
    answer_b: 'You must keep this information confidential as part of your ethical and professional duty',
    answer_c: 'You may share this with other clients if it comes up in conversation',
    answer_d: 'You should ask the client for permission before discussing it with anyone',
    correct_answer: 'b',
    explanation: 'Client confidentiality is a core ethical obligation in barbering. Personal information and private conversations shared during services must be protected. Sharing with coworkers or other clients violates this trust. The obligation exists because clients share personal information during services, and protecting their privacy builds trust. D is incorrect because the source establishes protecting client personal information and private conversations as a professional obligation. In this scenario, the appropriate response is to maintain confidentiality.',
    difficulty: 'easy',
    order_index: 34,
  },
  {
    id: 'qq-2-035',
    quiz_id: 'quiz-2',
    question: 'A client tells you about a personal health issue during their appointment. Later, a coworker asks you, "What was that client talking about earlier? They seemed upset." What should you do?',
    answer_a: 'Share the information with the coworker since they work with the same clients',
    answer_b: 'Keep the client\'s information confidential and not share it with the coworker',
    answer_c: 'Tell the coworker to ask the client directly',
    answer_d: 'Share only general information without specific details',
    correct_answer: 'b',
    explanation: 'Client confidentiality requires protecting personal information and health details — not even with coworkers or friends. When a coworker asks about a client\'s private conversation, the appropriate response is to maintain confidentiality. Sharing the information or sharing partial details violates the principle that what happens in your chair stays in your chair. C is incorrect because the barber\'s professional obligation is to protect the client\'s information and not disclose it. Telling the coworker to ask the client does not change or replace that obligation.',
    difficulty: 'medium',
    order_index: 35,
  },
  {
    id: 'qq-2-037',
    quiz_id: 'quiz-2',
    question: 'A barber has been working 6 days a week for 3 months, skipping lunch breaks, and answering client texts until midnight. They feel exhausted and irritable. According to Chapter 2\'s work-life balance principles, which of the following is the MOST appropriate first step?',
    answer_a: 'Continue the current schedule without changing any work or communication boundaries',
    answer_b: 'Set boundaries for client communication and take days off',
    answer_c: 'Quit the job and find a less demanding career',
    answer_d: 'Ignore the symptoms because they are normal for new barbers',
    correct_answer: 'b',
    explanation: 'Chapter 2 teaches that work-life balance requires setting boundaries (mental-health block), prioritizing sleep and nutrition (physical-self-care block), and recognizing burnout warning signs (burnout-signs block). The barber\'s symptoms — exhaustion and irritability — match the burnout warning signs. The most appropriate first step is to set boundaries, which is explicitly taught as a work-life balance strategy. A is incorrect because the approved content teaches that setting boundaries is a work-life balance strategy, and continuing without changing any boundaries is the opposite of that strategy. C is not the best answer because the question asks for the response that applies Chapter 2\'s work-life-balance strategies. The approved content specifically teaches setting boundaries and taking days off. D is incorrect because the chapter teaches that burnout signs should be recognized and addressed, not ignored.',
    difficulty: 'medium',
    order_index: 37,
  },

  // ═══════════════════════════════════════════════════════════
  // PHASE 5A ADDITIONS — C-2-23 Cultural Competence & Inclusive Service
  // Added 2026-08-16 per ASCYN_PRO_CH02_PHASE5A_C-2-23_CHECKPOINT.md
  // Addresses GAP-7: C-2-23 zero quiz coverage
  // Eligible: Chapter Quiz, Adaptive Review, Remediation Assessment
  // NOT eligible: Practice Final, DIRECT VERIFIED exam-readiness contribution
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-2-038',
    quiz_id: 'quiz-2',
    question: 'According to Chapter 2, what is the BEST approach when serving a client whose background or preferences you are unsure about?',
    answer_a: 'Assume their preferences based on their appearance to save time',
    answer_b: 'Ask respectful questions and let them guide the conversation',
    answer_c: 'Avoid conversation entirely to prevent making mistakes',
    answer_d: 'Use the same techniques and communication style for every client',
    correct_answer: 'b',
    explanation: 'Chapter 2 teaches that cultural competence means approaching every client with curiosity, respect, and a willingness to learn. The inclusive-practices block specifically instructs barbers not to assume someone\'s background, preferences, or style based on appearance, but instead to ask respectful questions and let the client guide the conversation. A is incorrect because assuming preferences based on appearance contradicts the source teaching. C is incorrect because avoidance is not the source-supported approach; respectful engagement is. D is incorrect because the source emphasizes adapting to individual clients rather than using a uniform approach.',
    difficulty: 'easy',
    order_index: 38,
  },
  {
    id: 'qq-2-039',
    quiz_id: 'quiz-2',
    question: 'A new client sits in your chair and mentions they prefer a specific term for their hair texture that you have not heard before. According to Chapter 2\'s cultural competence principles, what should you do?',
    answer_a: 'Politely correct them with the technical term you learned in school',
    answer_b: 'Ignore the term and continue using your usual terminology',
    answer_c: 'Ask them to explain the term and then use their preferred language',
    answer_d: 'Assume they are using slang and translate it to standard terminology',
    correct_answer: 'c',
    explanation: 'Chapter 2\'s cultural-scenarios block teaches that when a client uses a term you are unfamiliar with, the appropriate response is to ask them politely to explain and then use their preferred terms. This shows respect for the client\'s identity and builds trust. A is incorrect because correcting the client prioritizes the barber\'s knowledge over the client\'s comfort. B is incorrect because ignoring the client\'s preferred term dismisses their identity. D is not the source-supported answer because the source explicitly states not to assume someone\'s preferences or style based on appearance and teaches the barber to ask respectful questions.',
    difficulty: 'medium',
    order_index: 39,
  },

  // ═══════════════════════════════════════════════════════════
  // PHASE 5A ADDITIONS — C-2-24 Career Planning & Specialization
  // Added 2026-08-17 per ASCYN_PRO_CH02_PHASE5A_C-2-24_CHECKPOINT.md
  // Addresses GAP-8: C-2-24 zero quiz coverage
  // Eligible: Chapter Quiz, Adaptive Review, Remediation Assessment
  // NOT eligible: Practice Final, DIRECT VERIFIED exam-readiness contribution
  // ═══════════════════════════════════════════════════════════
  {
    id: 'qq-2-040',
    quiz_id: 'quiz-2',
    question: 'According to Chapter 2, what is the primary purpose of a career roadmap?',
    answer_a: 'To guarantee career success within five years',
    answer_b: 'To give direction, support better decisions, and maintain motivation',
    answer_c: 'To identify the single most profitable specialization',
    answer_d: 'To establish a fixed timeline that must be followed exactly',
    correct_answer: 'b',
    explanation: 'Chapter 2 teaches that a career roadmap gives you direction, helps you make better decisions, and keeps you motivated when progress feels slow. The plan doesn\'t need to be perfect — it needs to exist and be reviewed regularly as a living document that grows with you. A is incorrect because the source does not claim that a roadmap guarantees success; it presents the roadmap as a tool for direction and motivation, not a guarantee. C is incorrect because while the source discusses specialization paths, it does not claim that a roadmap\'s purpose is to identify the most profitable one; profitability is not the focus. D is incorrect because the source explicitly states the plan "doesn\'t need to be perfect" and should be "a living document that grows with you" — not a fixed timeline that must be followed exactly.',
    difficulty: 'easy',
    order_index: 40,
  },
  {
    id: 'qq-2-041',
    quiz_id: 'quiz-2',
    question: 'A barber has been licensed for 18 months, has 60 regular clients, and has mastered 5 core cuts. According to Chapter 2\'s career milestones, which activity is MOST appropriate for this barber\'s current stage?',
    answer_a: 'Opening their own shop and hiring a team',
    answer_b: 'Specializing in one technique like fades or beard sculpting',
    answer_c: 'Building passive income streams through product sales',
    answer_d: 'Developing a personal brand and launching a signature style',
    correct_answer: 'b',
    explanation: 'Chapter 2\'s career milestones identify Year 2 as the "Skill Refiner" stage, where barbers should specialize in one technique (fades, beard sculpting, designs), attend industry events, build social media presence, and start mentoring newer barbers. With 18 months of experience and 60 regular clients, this barber is between Year 1 (Foundation Builder) and Year 2 (Skill Refiner). Specializing in one technique is the most appropriate next step. A is incorrect because opening a shop is a Year 5 milestone, not appropriate for this stage. C is incorrect because building passive income is a Year 5 milestone. D is incorrect because developing a personal brand is a Year 3 milestone.',
    difficulty: 'medium',
    order_index: 41,
  },
]
