// Chapter 11: Treatment of the Hair and Scalp — PREMIUM MCQ QUIZ
// 50 questions generated STRICTLY from Chapter 11 premium flashcards
// Randomized question selection and answer order per attempt
// The Treatment Sanctuary Certification Exam

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 11: FULL QUESTION BANK (50 questions)
// Generated from chapter-11-premium-flashcards.ts
// NATURAL answer distribution (NOT forced balanced)
// ───────────────────────────────────────────────
export const chapter11PremiumQuizQuestions: QuizQuestion[] = [
  // SHAMPOO SERVICE FUNDAMENTALS (8 questions)
  {
    id: 'qq-11-001',
    quiz_id: 'quiz-11',
    question: 'What is the primary purpose of a shampoo service?',
    answer_a: 'To cleanse the scalp and hair, removing oils, dirt, and product buildup',
    answer_b: 'To style the hair before the client leaves the chair',
    answer_c: 'To apply chemical treatments to the hair',
    answer_d: 'To trim split ends before cutting',
    correct_answer: 'a',
    explanation: 'The primary purpose of shampooing is to cleanse the scalp and hair, removing oils, dirt, and product buildup before cutting or styling.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-11-002',
    quiz_id: 'quiz-11',
    question: 'Why should barbers shampoo hair before cutting?',
    answer_a: 'Clean hair is free from oils and products that can interfere with cutting tools',
    answer_b: 'It is required by law in all states',
    answer_c: 'Shampooing makes the hair darker and easier to see',
    answer_d: 'It permanently straightens the hair for easier cutting',
    correct_answer: 'a',
    explanation: 'Shampooing before cutting ensures clean hair that is free from oils and products that can interfere with cutting tools and haircut results.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-11-003',
    quiz_id: 'quiz-11',
    question: 'What is the typical pH range of most shampoo products?',
    answer_a: '4.5 to 7.5',
    answer_b: '1.0 to 3.0',
    answer_c: '8.0 to 10.0',
    answer_d: '11.0 to 14.0',
    correct_answer: 'a',
    explanation: 'Most shampoos have a pH range of 4.5 to 7.5, which is milder than soaps and detergents and leaves hair more manageable.',
    difficulty: 'medium',
    order_index: 3,
  },
  {
    id: 'qq-11-004',
    quiz_id: 'quiz-11',
    question: 'What is the typical pH range of most hair conditioners?',
    answer_a: '3.0 to 5.5',
    answer_b: '6.0 to 8.0',
    answer_c: '1.0 to 2.5',
    answer_d: '9.0 to 11.0',
    correct_answer: 'a',
    explanation: 'Hair conditioners typically range from 3.0 to 5.5 on the pH scale, helping restore moisture and smooth the cuticle after cleansing.',
    difficulty: 'medium',
    order_index: 4,
  },
  {
    id: 'qq-11-005',
    quiz_id: 'quiz-11',
    question: 'What are the two main types of draping capes used in barbering?',
    answer_a: 'Shampoo capes (vinyl) and haircutting capes (nylon/synthetic)',
    answer_b: 'Cotton capes and silk capes',
    answer_c: 'Disposable paper capes and cloth capes',
    answer_d: 'Leather capes and plastic capes',
    correct_answer: 'a',
    explanation: 'The two main types are shampoo capes (waterproof vinyl for wet/chemical services) and haircutting capes (nylon or synthetic for dry services).',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-11-006',
    quiz_id: 'quiz-11',
    question: 'Why is a neck strip or towel required between the client\'s skin and the cape?',
    answer_a: 'To prevent direct contact and maintain infection control compliance',
    answer_b: 'To make the client look more professional',
    answer_c: 'To keep the cape from getting dirty',
    answer_d: 'It is only required for chemical services',
    correct_answer: 'a',
    explanation: 'A neck strip or towel prevents direct contact between the cape and client\'s skin, maintaining infection control compliance with state barber laws.',
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-11-007',
    quiz_id: 'quiz-11',
    question: 'What are the two methods of shampooing and rinsing?',
    answer_a: 'Reclined method and inclined method',
    answer_b: 'Hot method and cold method',
    answer_c: 'Standing method and sitting method',
    answer_d: 'Dry method and wet method',
    correct_answer: 'a',
    explanation: 'The two methods are the reclined method (client lies back in shampoo bowl) and the inclined method (client bends forward over sink).',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-11-008',
    quiz_id: 'quiz-11',
    question: 'Which shampooing method is most commonly used and why?',
    answer_a: 'Reclined method — more comfortable for client and more efficient for barber',
    answer_b: 'Inclined method — faster and uses less water',
    answer_c: 'Reclined method — required by state law',
    answer_d: 'Inclined method — better for clients with neck problems',
    correct_answer: 'a',
    explanation: 'The reclined method is most common because it is more comfortable for the client and allows greater speed and efficiency for the barber.',
    difficulty: 'easy',
    order_index: 8,
  },

  // WATER TEMPERATURE & SAFETY (4 questions)
  {
    id: 'qq-11-009',
    quiz_id: 'quiz-11',
    question: 'What water temperature is recommended for shampooing?',
    answer_a: 'Comfortably warm water',
    answer_b: 'Hot water for better cleansing',
    answer_c: 'Cold water to close the cuticle',
    answer_d: 'Alternating hot and cold water',
    correct_answer: 'a',
    explanation: 'Comfortably warm water is recommended. Cold water causes discomfort and poor lathering; hot water can burn the scalp or cause dryness.',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-11-010',
    quiz_id: 'quiz-11',
    question: 'What can happen if shampoo water is too hot?',
    answer_a: 'It can burn or blister the skin and cause scalp dryness',
    answer_b: 'It makes the hair grow faster',
    answer_c: 'It permanently straightens curly hair',
    answer_d: 'It has no negative effects on the scalp',
    correct_answer: 'a',
    explanation: 'Water that is too hot can burn or blister the skin and cause the scalp to flake or become dry.',
    difficulty: 'easy',
    order_index: 10,
  },
  {
    id: 'qq-11-011',
    quiz_id: 'quiz-11',
    question: 'Why should you always test water temperature before applying it to the client\'s head?',
    answer_a: 'To prevent scalding or discomfort',
    answer_b: 'It is only necessary for children',
    answer_c: 'To check if the water pressure is adequate',
    answer_d: 'To ensure the shampoo will lather properly',
    correct_answer: 'a',
    explanation: 'Always test water temperature to prevent scalding or discomfort — water that feels fine to your hand may be too hot for the client\'s scalp.',
    difficulty: 'easy',
    order_index: 11,
  },
  {
    id: 'qq-11-012',
    quiz_id: 'quiz-11',
    question: 'Which of the following is a common client complaint about shampoo services?',
    answer_a: 'All of these are common complaints',
    answer_b: 'Extreme water temperatures',
    answer_c: 'Fingernail scratching of the scalp',
    answer_d: 'Insufficient rinsing',
    correct_answer: 'a',
    explanation: 'Common complaints include improper product selection, insufficient scalp massage, extreme water temperatures, water running onto face/eyes, soiled clothing, fingernail scratching, improper blotting, and insufficient rinsing.',
    difficulty: 'medium',
    order_index: 12,
  },

  // PRODUCT SELECTION (5 questions)
  {
    id: 'qq-11-013',
    quiz_id: 'quiz-11',
    question: 'What six characteristics should be analyzed before choosing shampoo and conditioner products?',
    answer_a: 'Scalp condition, hair condition, density, texture, porosity, and elasticity',
    answer_b: 'Client age, height, weight, eye color, skin tone, and gender',
    answer_c: 'Hair length, style preference, brand loyalty, price, scent, and color',
    answer_d: 'Time of day, season, weather, mood, occasion, and budget',
    correct_answer: 'a',
    explanation: 'Before choosing products, analyze scalp condition, hair condition, hair density, hair texture, hair porosity, and hair elasticity.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-11-014',
    quiz_id: 'quiz-11',
    question: 'What type of shampoo is recommended for fine straight hair?',
    answer_a: 'Volumizing shampoo and protein treatments',
    answer_b: 'Heavy moisturizing shampoo',
    answer_c: 'Clarifying shampoo with high alcohol content',
    answer_d: 'Hot oil treatment shampoo',
    correct_answer: 'a',
    explanation: 'Fine straight hair benefits from volumizing shampoo, fine-hair shampoo, and protein treatments that add body without weighing hair down.',
    difficulty: 'medium',
    order_index: 14,
  },
  {
    id: 'qq-11-015',
    quiz_id: 'quiz-11',
    question: 'What products are recommended for dry, damaged, chemically treated hair?',
    answer_a: 'Gentle cleansing shampoo, moisturizing conditioner, and protein repair treatments',
    answer_b: 'Clarifying shampoo and alcohol-based tonics',
    answer_c: 'Regular soap and hot water rinses',
    answer_d: 'No products — let the hair recover naturally',
    correct_answer: 'a',
    explanation: 'Dry, damaged, chemically treated hair needs gentle cleansing shampoo, moisturizing conditioner, protein and moisturizing repair treatments, and spray-on thermal protection.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-11-016',
    quiz_id: 'quiz-11',
    question: 'Why should barbers read product labels and manufacturer directions?',
    answer_a: 'To understand how products affect hair and scalp for proper selection',
    answer_b: 'It is only necessary for new products',
    answer_c: 'To memorize ingredients for the state board exam',
    answer_d: 'To check expiration dates only',
    correct_answer: 'a',
    explanation: 'Reading labels helps barbers understand how products affect hair and scalp, enabling proper selection and recommendation for each client\'s needs.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-11-017',
    quiz_id: 'quiz-11',
    question: 'What is a scalp conditioner?',
    answer_a: 'A cream or ointment for scalp maintenance or medicinal treatment',
    answer_b: 'A type of shampoo with extra lather',
    answer_c: 'A tool used to detangle hair',
    answer_d: 'A spray that adds color to the scalp',
    correct_answer: 'a',
    explanation: 'A scalp conditioner is a cream or ointment used for overall scalp maintenance or to treat conditions requiring a medicinal product.',
    difficulty: 'easy',
    order_index: 17,
  },

  // SCALP MASSAGE TECHNIQUES (7 questions)
  {
    id: 'qq-11-018',
    quiz_id: 'quiz-11',
    question: 'What are the three main scalp massage manipulations?',
    answer_a: 'Rotary, sliding, and back-and-forth',
    answer_b: 'Pounding, squeezing, and twisting',
    answer_c: 'Rubbing, patting, and pulling',
    answer_d: 'Pressing, rolling, and tapping',
    correct_answer: 'a',
    explanation: 'The three main scalp massage manipulations are rotary movement, sliding movement, and back-and-forth movement.',
    difficulty: 'easy',
    order_index: 18,
  },
  {
    id: 'qq-11-019',
    quiz_id: 'quiz-11',
    question: 'Describe the rotary massage movement.',
    answer_a: 'Overlapping circular movements with thumbs and fingertips',
    answer_b: 'Straight up-and-down strokes with the palms',
    answer_c: 'Rapid tapping with the knuckles',
    answer_d: 'Pulling the hair in small sections',
    correct_answer: 'a',
    explanation: 'Rotary movement uses thumbs and/or fingertips to produce overlapping circular movements with moderate to firm pressure throughout the scalp area.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-11-020',
    quiz_id: 'quiz-11',
    question: 'Describe the sliding massage movement.',
    answer_a: 'Sliding strokes with thumbs and fingertips that often overlap',
    answer_b: 'Circular rubbing with the entire palm',
    answer_c: 'Quick jabbing motions with fingertips',
    answer_d: 'Gentle hair pulling in alternating directions',
    correct_answer: 'a',
    explanation: 'Sliding movement uses thumbs and fingertips to produce sliding strokes with moderate to firm pressure; hands often overlap as they meet over a section of the head.',
    difficulty: 'easy',
    order_index: 20,
  },
  {
    id: 'qq-11-021',
    quiz_id: 'quiz-11',
    question: 'What four physiological effects does scalp massage achieve?',
    answer_a: 'Increased blood/lymph flow, soothed nerves, stimulated muscles/glands, flexible scalp',
    answer_b: 'Hair growth, color change, straightening, and thickening',
    answer_c: 'Permanent wave creation, curl removal, shine, and volume',
    answer_d: 'Scalp tanning, pore closing, oil elimination, and cooling',
    correct_answer: 'a',
    explanation: 'Scalp massage increases blood and lymph flow, soothes nerves, stimulates scalp muscles and glands, and creates a more flexible scalp.',
    difficulty: 'medium',
    order_index: 21,
  },
  {
    id: 'qq-11-022',
    quiz_id: 'quiz-11',
    question: 'Where should massage manipulations start on the scalp?',
    answer_a: 'At the hairline',
    answer_b: 'At the crown',
    answer_c: 'At the nape of the neck',
    answer_d: 'Behind the ears',
    correct_answer: 'a',
    explanation: 'Massage manipulations should start at the hairline, working with even pressure and continuous synchronized movements.',
    difficulty: 'easy',
    order_index: 22,
  },
  {
    id: 'qq-11-023',
    quiz_id: 'quiz-11',
    question: 'What should be avoided during scalp massage?',
    answer_a: 'Pulling the hair in any way',
    answer_b: 'Using any pressure at all',
    answer_c: 'Touching the client\'s ears',
    answer_d: 'Massaging for more than 30 seconds',
    correct_answer: 'a',
    explanation: 'Pulling the hair should be avoided — keep fingertips on the scalp, not grasping hair strands.',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'qq-11-024',
    quiz_id: 'quiz-11',
    question: 'Which massage movements are typically used during a shampoo service?',
    answer_a: 'Rotary/circular and back-and-forth scrubbing movements',
    answer_b: 'Only sliding movements',
    answer_c: 'Only rotary movements',
    answer_d: 'Pounding and tapping movements',
    correct_answer: 'a',
    explanation: 'Shampoo massage typically uses a combination of rotary/circular movements and back-and-forth scrubbing-type movements.',
    difficulty: 'medium',
    order_index: 24,
  },

  // SCALP & HAIR TREATMENTS (8 questions)
  {
    id: 'qq-11-025',
    quiz_id: 'quiz-11',
    question: 'What is the purpose of scalp and hair treatments?',
    answer_a: 'To preserve health and appearance, and prevent or combat disorders',
    answer_b: 'To permanently change hair color',
    answer_c: 'To remove all natural oils from the scalp',
    answer_d: 'To straighten curly hair without chemicals',
    correct_answer: 'a',
    explanation: 'Scalp and hair treatments preserve the health and appearance of hair and scalp, and help prevent or combat disorders like dandruff, dryness, and oiliness.',
    difficulty: 'easy',
    order_index: 25,
  },
  {
    id: 'qq-11-026',
    quiz_id: 'quiz-11',
    question: 'What are the two essential requirements for healthy hair and scalp?',
    answer_a: 'Cleanliness and stimulation',
    answer_b: 'Heat and chemicals',
    answer_c: 'Darkness and moisture',
    answer_d: 'Cutting and coloring',
    correct_answer: 'a',
    explanation: 'Cleanliness and stimulation are the two essential requirements for maintaining healthy hair and scalp.',
    difficulty: 'easy',
    order_index: 26,
  },
  {
    id: 'qq-11-027',
    quiz_id: 'quiz-11',
    question: 'What causes dry scalp and hair?',
    answer_a: 'Inactivity of oil glands, poor circulation, and harsh products',
    answer_b: 'Too much shampooing with warm water',
    answer_c: 'Excessive scalp massage',
    answer_d: 'Using pH-balanced products',
    correct_answer: 'a',
    explanation: 'Dry scalp and hair are caused by inactivity of oil glands, poor blood circulation, and excessive removal of natural oils by harsh products.',
    difficulty: 'medium',
    order_index: 27,
  },
  {
    id: 'qq-11-028',
    quiz_id: 'quiz-11',
    question: 'What is the technical term for dandruff?',
    answer_a: 'Pityriasis',
    answer_b: 'Seborrhea',
    answer_c: 'Alopecia',
    answer_d: 'Folliculitis',
    correct_answer: 'a',
    explanation: 'The technical term for dandruff is pityriasis.',
    difficulty: 'easy',
    order_index: 28,
  },
  {
    id: 'qq-11-029',
    quiz_id: 'quiz-11',
    question: 'What causes dandruff?',
    answer_a: 'The fungus Malassezia growing out of control',
    answer_b: 'Washing hair too frequently',
    answer_c: 'Using cold water to rinse',
    answer_d: 'Lack of sunlight on the scalp',
    correct_answer: 'a',
    explanation: 'Dandruff is caused by the fungus Malassezia growing out of control on the scalp.',
    difficulty: 'medium',
    order_index: 29,
  },
  {
    id: 'qq-11-030',
    quiz_id: 'quiz-11',
    question: 'What are common antifungal ingredients in antidandruff shampoos?',
    answer_a: 'Pyrithione zinc, selenium sulfide, and ketoconazole',
    answer_b: 'Aloe vera, coconut oil, and honey',
    answer_c: 'Lemon juice, vinegar, and baking soda',
    answer_d: 'Baby oil, petroleum jelly, and mineral oil',
    correct_answer: 'a',
    explanation: 'Common antifungal ingredients in antidandruff shampoos include pyrithione zinc, selenium sulfide, and ketoconazole.',
    difficulty: 'medium',
    order_index: 30,
  },
  {
    id: 'qq-11-031',
    quiz_id: 'quiz-11',
    question: 'What is seborrheic dermatitis?',
    answer_a: 'Severe dandruff accompanied by redness and inflammation',
    answer_b: 'A type of hair loss caused by genetics',
    answer_c: 'A bacterial infection of hair follicles',
    answer_d: 'A parasitic infestation of the scalp',
    correct_answer: 'a',
    explanation: 'Seborrheic dermatitis is a condition where severe dandruff (pityriasis steatoides) is accompanied by redness and inflammation; it may also appear on eyebrows and beard.',
    difficulty: 'medium',
    order_index: 31,
  },
  {
    id: 'qq-11-032',
    quiz_id: 'quiz-11',
    question: 'What services may be included in a hair or scalp treatment?',
    answer_a: 'All of these may be included',
    answer_b: 'Scalp steaming and massage',
    answer_c: 'Infrared/ultraviolet lamps and high-frequency current',
    answer_d: 'Application of tonics, astringents, and antiseptics',
    correct_answer: 'a',
    explanation: 'Hair or scalp treatments may include cleansing with shampoo, scalp steaming, massage with hands or electric appliance, infrared/ultraviolet lamps, high-frequency current, and application of tonics, astringents, antiseptics, or ointments.',
    difficulty: 'medium',
    order_index: 32,
  },

  // SCALP STEAM & EQUIPMENT (5 questions)
  {
    id: 'qq-11-033',
    quiz_id: 'quiz-11',
    question: 'What is the purpose of scalp steam?',
    answer_a: 'To relax pores, soften scalp and hair, and increase circulation',
    answer_b: 'To permanently straighten the hair',
    answer_c: 'To remove all natural oils from the scalp',
    answer_d: 'To dye the hair a darker color',
    correct_answer: 'a',
    explanation: 'Scalp steam relaxes pores, softens the scalp and hair, and increases blood circulation before massage and treatments.',
    difficulty: 'easy',
    order_index: 33,
  },
  {
    id: 'qq-11-034',
    quiz_id: 'quiz-11',
    question: 'What can be used as an alternative to a scalp steamer?',
    answer_a: 'Hot towels prepared in a cabinet or soaked in hot water',
    answer_b: 'A hair dryer on high heat',
    answer_c: 'Ice packs wrapped in plastic',
    answer_d: 'A fan blowing warm air',
    correct_answer: 'a',
    explanation: 'Hot towels — prepared in a hot-towel cabinet or soaked in hot water, wrung out, and applied to the head — can be used as an alternative to a scalp steamer.',
    difficulty: 'easy',
    order_index: 34,
  },
  {
    id: 'qq-11-035',
    quiz_id: 'quiz-11',
    question: 'How should an electric massager be positioned on the hand?',
    answer_a: 'On the back of the hand, leaving thumb and fingers free',
    answer_b: 'In the palm, gripping tightly',
    answer_c: 'Between the fingers like a pencil',
    answer_d: 'Strapped to the wrist with a band',
    correct_answer: 'a',
    explanation: 'An electric massager should be placed on the back of the hand, leaving the thumb and fingers free to move over the scalp.',
    difficulty: 'medium',
    order_index: 35,
  },
  {
    id: 'qq-11-036',
    quiz_id: 'quiz-11',
    question: 'How often should scalp massage be performed for normal scalp maintenance?',
    answer_a: 'Once a week',
    answer_b: 'Every day',
    answer_c: 'Once a month',
    answer_d: 'Only when the client requests it',
    correct_answer: 'a',
    explanation: 'Scalp massage should be performed once a week for normal scalp maintenance — more frequently for scalp disorders only under a dermatologist\'s direction.',
    difficulty: 'medium',
    order_index: 36,
  },
  {
    id: 'qq-11-037',
    quiz_id: 'quiz-11',
    question: 'What are the five steps of a hair tonic treatment?',
    answer_a: 'Apply tonic, massage, steam, massage again, comb into style',
    answer_b: 'Shampoo, condition, rinse, dry, and style',
    answer_c: 'Cut, color, rinse, dry, and trim',
    answer_d: 'Steam, shampoo, steam again, condition, and rinse',
    correct_answer: 'a',
    explanation: 'The five steps are: 1) Apply hair tonic, 2) Massage scalp, 3) Apply scalp steam, 4) Massage again with hands or vibrator, 5) Comb into desired style.',
    difficulty: 'medium',
    order_index: 37,
  },

  // CONTRAINDICATIONS & SAFETY (7 questions)
  {
    id: 'qq-11-038',
    quiz_id: 'quiz-11',
    question: 'What scalp conditions prohibit a barber from performing services?',
    answer_a: 'Parasitic infestations, fungal infections, staph infections, and open abrasions',
    answer_b: 'Only visible dandruff',
    answer_c: 'Oily scalp conditions',
    answer_d: 'Dry scalp conditions',
    correct_answer: 'a',
    explanation: 'Barbers must not perform services on clients with parasitic infestations (head lice, scabies), fungal infections (tinea), staphylococcus infections, open abrasions, or signs of irritation and inflammation.',
    difficulty: 'medium',
    order_index: 38,
  },
  {
    id: 'qq-11-039',
    quiz_id: 'quiz-11',
    question: 'What should a barber do if parasites are found during scalp analysis?',
    answer_a: 'Do not begin service and refer to a physician or pharmacist',
    answer_b: 'Proceed with the service using extra disinfectant',
    answer_c: 'Shampoo with hot water to kill the parasites',
    answer_d: 'Tell the client to come back next week',
    correct_answer: 'a',
    explanation: 'If parasites are found, do not begin any service — refer the client to a physician or pharmacist.',
    difficulty: 'easy',
    order_index: 39,
  },
  {
    id: 'qq-11-040',
    quiz_id: 'quiz-11',
    question: 'Should chemical services be performed on irritated or abraded scalps?',
    answer_a: 'No — do not proceed with chemical services',
    answer_b: 'Yes, but use a milder formula',
    answer_c: 'Yes, if the client signs a waiver',
    answer_d: 'Only if the irritation is minor',
    correct_answer: 'a',
    explanation: 'Do not proceed with chemical services if there are signs of irritation or abrasions on the scalp.',
    difficulty: 'easy',
    order_index: 40,
  },
  {
    id: 'qq-11-041',
    quiz_id: 'quiz-11',
    question: 'Is dandruff contagious?',
    answer_a: 'No — current research shows dandruff is not contagious',
    answer_b: 'Yes — it spreads through shared combs and brushes',
    answer_c: 'Only in its severe form (pityriasis steatoides)',
    answer_d: 'Yes, but only between family members',
    correct_answer: 'a',
    explanation: 'Current research has determined dandruff is not contagious, though barbers must still disinfect tools between clients as standard practice.',
    difficulty: 'medium',
    order_index: 41,
  },
  {
    id: 'qq-11-042',
    quiz_id: 'quiz-11',
    question: 'Is tinea (ringworm) contagious?',
    answer_a: 'Yes — highly contagious through infected scales and contaminated items',
    answer_b: 'No — it only affects the person who has it',
    answer_c: 'Only if the person has open wounds',
    answer_d: 'Only during the first 24 hours of infection',
    correct_answer: 'a',
    explanation: 'Tinea is highly contagious and spreads through infected skin scales, hair, unclean combs, brushes, and contact with contaminated surfaces.',
    difficulty: 'easy',
    order_index: 42,
  },
  {
    id: 'qq-11-043',
    quiz_id: 'quiz-11',
    question: 'What should a barber do if a client has suspected or confirmed tinea?',
    answer_a: 'Refer to a physician and do not perform services until cleared',
    answer_b: 'Proceed with the service wearing gloves',
    answer_c: 'Use a strong disinfectant on the scalp',
    answer_d: 'Shampoo with antifungal soap only',
    correct_answer: 'a',
    explanation: 'Clients with suspected or confirmed tinea should be referred to a physician for medical treatment, and services should not be performed until the condition has cleared.',
    difficulty: 'easy',
    order_index: 43,
  },
  {
    id: 'qq-11-044',
    quiz_id: 'quiz-11',
    question: 'Should gloves be worn when shampooing a client with dandruff?',
    answer_a: 'Yes — advisable as a precautionary measure',
    answer_b: 'No — dandruff is not contagious so gloves are unnecessary',
    answer_c: 'Only if the dandruff is severe',
    answer_d: 'Gloves are never worn during shampooing',
    correct_answer: 'a',
    explanation: 'It is advisable to wear gloves when shampooing a client with dandruff as a precautionary measure.',
    difficulty: 'easy',
    order_index: 44,
  },

  // HAIR ANALYSIS (6 questions)
  {
    id: 'qq-11-045',
    quiz_id: 'quiz-11',
    question: 'Why is touch considered the key sense for analyzing hair condition?',
    answer_a: 'It reveals texture, thickness, elasticity, and porosity',
    answer_b: 'It is the fastest sense to use',
    answer_c: 'It does not require looking at the client',
    answer_d: 'It can detect hair color changes',
    correct_answer: 'a',
    explanation: 'Touch reveals texture, thickness, elasticity, and porosity that cannot be determined by sight alone.',
    difficulty: 'medium',
    order_index: 45,
  },
  {
    id: 'qq-11-046',
    quiz_id: 'quiz-11',
    question: 'How is hair texture determined?',
    answer_a: 'By feeling a single strand of dry hair between the fingers',
    answer_b: 'By looking at the hair under bright light',
    answer_c: 'By measuring the hair with a ruler',
    answer_d: 'By weighing the hair on a scale',
    correct_answer: 'a',
    explanation: 'Hair texture is determined by feeling a single strand of dry hair between the fingers and rolling it to assess diameter — classified as coarse, medium, or fine.',
    difficulty: 'medium',
    order_index: 46,
  },
  {
    id: 'qq-11-047',
    quiz_id: 'quiz-11',
    question: 'How is hair porosity tested?',
    answer_a: 'Slide fingers up and down dry hair strands toward the scalp',
    answer_b: 'Submerge hair in water for 30 minutes',
    answer_c: 'Apply heat with a blow dryer',
    answer_d: 'Cut the hair and examine the cross-section',
    correct_answer: 'a',
    explanation: 'Slide thumb and forefinger up and down dry hair strands toward the scalp — smooth hair indicates low porosity; roughness or raised scales indicate high porosity.',
    difficulty: 'medium',
    order_index: 47,
  },
  {
    id: 'qq-11-048',
    quiz_id: 'quiz-11',
    question: 'How is hair elasticity tested?',
    answer_a: 'Gently tug a few strands of clean, wet hair',
    answer_b: 'Comb the hair vigorously while dry',
    answer_c: 'Apply a chemical relaxer and observe',
    answer_d: 'Heat the hair with a flat iron',
    correct_answer: 'a',
    explanation: 'Gently tug a few strands of clean, wet hair — normal hair stretches and returns to original length; low elasticity breaks or fails to return.',
    difficulty: 'medium',
    order_index: 48,
  },
  {
    id: 'qq-11-049',
    quiz_id: 'quiz-11',
    question: 'What is the average number of hairs on a human head?',
    answer_a: 'Approximately 100,000 individual strands',
    answer_b: 'Approximately 50,000 individual strands',
    answer_c: 'Approximately 200,000 individual strands',
    answer_d: 'Approximately 25,000 individual strands',
    correct_answer: 'a',
    explanation: 'The average human head has approximately 100,000 individual strands, with about 2,200 strands per square inch.',
    difficulty: 'medium',
    order_index: 49,
  },
  {
    id: 'qq-11-050',
    quiz_id: 'quiz-11',
    question: 'What is the professional scope of practice for barbers regarding scalp disorders?',
    answer_a: 'General maintenance for non-medical conditions; refer medical cases to physicians',
    answer_b: 'Diagnose and treat all scalp conditions including infections',
    answer_c: 'Prescribe medicated shampoos and topical antibiotics',
    answer_d: 'Perform minor surgical procedures on the scalp',
    correct_answer: 'a',
    explanation: 'Barbers may perform general scalp maintenance and corrective treatments for non-medical conditions, but must refer clients with parasitic infestations, staphylococcus infections, or abnormal scalp conditions to a physician.',
    difficulty: 'hard',
    order_index: 50,
  },
]

export default chapter11PremiumQuizQuestions
