// Chapter 7: Basics of Chemistry — hardened assessment bank
// Source-grounded to Chapter 7 coverage; NIC-aligned for barber chemistry competency.
// ASCYN PRO original wording. One primary concept mapping per scored item.

import { QuizQuestion } from '@/types'

export const chapter7PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: "qq-7-001",
    quiz_id: 'quiz-7',
    question: "Which statement best describes organic chemistry in the context of Chapter 7?",
    answer_a: "It focuses on carbon-containing substances and compounds",
    answer_b: "It includes only substances that came from living organisms",
    answer_c: "It includes every product that can burn",
    answer_d: "It excludes synthetic carbon-containing materials",
    correct_answer: "a",
    explanation: "Organic chemistry focuses on carbon-containing substances and compounds. Living-versus-nonliving and flammability are not reliable classification shortcuts.",
    difficulty: "easy",
    order_index: 1,
  },
  {
    id: "qq-7-002",
    quiz_id: 'quiz-7',
    question: "A product contains several carbon-based conditioning ingredients, while another preparation is primarily water and mineral salts. Which classification is most defensible?",
    answer_a: "The first is associated with organic chemistry; the second contains important inorganic substances",
    answer_b: "Both are inorganic because both are professional products",
    answer_c: "The first is organic only if every ingredient came from a plant",
    answer_d: "The second is organic because water is used on living hair",
    correct_answer: "a",
    explanation: "Carbon-based ingredients fall within organic chemistry, while water and mineral salts are common inorganic examples. Classification depends on composition, not product use or origin stories.",
    difficulty: "medium",
    order_index: 2,
  },
  {
    id: "qq-7-003",
    quiz_id: 'quiz-7',
    question: "A barber knows Product A is mostly organic compounds and Product B is mostly inorganic substances. What can the barber conclude about which product is more hazardous?",
    answer_a: "Product A is automatically more flammable and dangerous",
    answer_b: "Product B is automatically safer because it is inorganic",
    answer_c: "Neither classification alone establishes hazard; the label, concentration, pH, ingredients, and exposure information must be checked",
    answer_d: "Both products have the same hazard because chemistry classification never matters",
    correct_answer: "c",
    explanation: "Organic versus inorganic classification does not by itself determine hazard. Safety decisions require product-specific information such as concentration, pH, ingredients, label directions, and exposure guidance.",
    difficulty: "medium",
    order_index: 3,
  },
  {
    id: "qq-7-004",
    quiz_id: 'quiz-7',
    question: "Which description defines matter?",
    answer_a: "Anything that has mass and occupies space",
    answer_b: "Only substances visible without magnification",
    answer_c: "Only solids and liquids",
    answer_d: "Any material that reacts chemically",
    correct_answer: "a",
    explanation: "Matter has mass and occupies space. Solids, liquids, and gases are common physical states of matter.",
    difficulty: "easy",
    order_index: 4,
  },
  {
    id: "qq-7-005",
    quiz_id: 'quiz-7',
    question: "A sample contains only one type of atom and cannot be chemically separated into simpler substances. How should it be classified?",
    answer_a: "Element",
    answer_b: "Compound",
    answer_c: "Suspension",
    answer_d: "Emulsion",
    correct_answer: "a",
    explanation: "An element is a basic form of matter made of one type of atom. A compound contains different elements chemically combined.",
    difficulty: "medium",
    order_index: 5,
  },
  {
    id: "qq-7-006",
    quiz_id: 'quiz-7',
    question: "A molecule contains two hydrogen atoms chemically joined to one oxygen atom. Which statement is most accurate?",
    answer_a: "It is a compound because different elements are chemically joined in a definite proportion",
    answer_b: "It is an element because all atoms belong to one molecule",
    answer_c: "It is a mixture because hydrogen and oxygen can exist separately",
    answer_d: "It is a suspension because the atoms are dispersed",
    correct_answer: "a",
    explanation: "A compound contains atoms of different elements chemically joined in definite proportions. H₂O is therefore a compound as well as a molecule.",
    difficulty: "medium",
    order_index: 6,
  },
  {
    id: "qq-7-007",
    quiz_id: 'quiz-7',
    question: "A barber mixes two compatible liquid ingredients in different proportions without creating a new chemical substance. Which classification best fits the result?",
    answer_a: "Physical mixture",
    answer_b: "Element",
    answer_c: "Pure compound",
    answer_d: "Single atom",
    correct_answer: "a",
    explanation: "A physical mixture combines substances without requiring a new chemical substance and may vary in composition.",
    difficulty: "hard",
    order_index: 7,
  },
  {
    id: "qq-7-008",
    quiz_id: 'quiz-7',
    question: "Which observation is a physical property rather than a chemical property?",
    answer_a: "The liquid has a higher viscosity than water",
    answer_b: "The product oxidizes when exposed to an oxidizing agent",
    answer_c: "The ingredient reacts with an alkali",
    answer_d: "The substance forms a new compound when heated",
    correct_answer: "a",
    explanation: "Viscosity can be observed without changing chemical identity, so it is a physical property. The other choices describe chemical behavior.",
    difficulty: "medium",
    order_index: 8,
  },
  {
    id: "qq-7-009",
    quiz_id: 'quiz-7',
    question: "Ice melts in a bowl while oxidation haircolor develops on hair. Which comparison is correct?",
    answer_a: "Melting is a physical change; color development is a chemical change",
    answer_b: "Both are physical changes because both can change appearance",
    answer_c: "Melting is chemical; color development is physical",
    answer_d: "Both are chemical because energy is involved",
    correct_answer: "a",
    explanation: "Melting changes physical state without creating a new chemical substance. Oxidation haircolor involves a chemical reaction that changes chemical composition.",
    difficulty: "medium",
    order_index: 9,
  },
  {
    id: "qq-7-010",
    quiz_id: 'quiz-7',
    question: "A temporary color product mainly deposits color near the hair surface, while an oxidation haircolor develops through a chemical reaction. What concept is being tested?",
    answer_a: "Physical change versus chemical change",
    answer_b: "Organic versus inorganic chemistry",
    answer_c: "Hard water versus soft water",
    answer_d: "Solution versus suspension",
    correct_answer: "a",
    explanation: "Surface deposition can primarily represent a physical change, while oxidation haircolor depends on a chemical reaction. The key is whether chemical composition changes.",
    difficulty: "hard",
    order_index: 10,
  },
  {
    id: "qq-7-011",
    quiz_id: 'quiz-7',
    question: "A student says, “If a change is difficult to reverse, it must be chemical.” Which response is best?",
    answer_a: "Not necessarily; the better test is whether a new chemical substance or changed chemical composition results",
    answer_b: "Correct; reversibility alone defines every chemical change",
    answer_c: "Correct only when heat is released",
    answer_d: "Incorrect because chemical changes never alter composition",
    correct_answer: "a",
    explanation: "Reversibility is not the defining test. A chemical change involves a reaction that changes chemical composition; a physical change does not.",
    difficulty: "hard",
    order_index: 11,
  },
  {
    id: "qq-7-012",
    quiz_id: 'quiz-7',
    question: "Which change describes oxidation in the Chapter 7 framework?",
    answer_a: "Gain of oxygen or loss of hydrogen",
    answer_b: "Loss of oxygen or gain of hydrogen",
    answer_c: "Loss of water only",
    answer_d: "Gain of mineral salts",
    correct_answer: "a",
    explanation: "Oxidation can involve gaining oxygen or losing hydrogen.",
    difficulty: "medium",
    order_index: 12,
  },
  {
    id: "qq-7-013",
    quiz_id: 'quiz-7',
    question: "Which change describes reduction in the Chapter 7 framework?",
    answer_a: "Loss of oxygen or gain of hydrogen",
    answer_b: "Gain of oxygen or loss of hydrogen",
    answer_c: "Increase in pH only",
    answer_d: "Decrease in temperature only",
    correct_answer: "a",
    explanation: "Reduction can involve losing oxygen or gaining hydrogen.",
    difficulty: "medium",
    order_index: 13,
  },
  {
    id: "qq-7-014",
    quiz_id: 'quiz-7',
    question: "During permanent waving, which sequence best describes the redox chemistry?",
    answer_a: "Reduction changes disulfide bonds first; oxidation during neutralization helps reform them in the new shape",
    answer_b: "Oxidation breaks the bonds first; reduction permanently seals the cuticle",
    answer_c: "Acid-alkali neutralization breaks and reforms the bonds",
    answer_d: "No redox reaction is involved if the hair is wrapped on rods",
    correct_answer: "a",
    explanation: "The waving phase uses reduction to alter disulfide bonds, followed by oxidation during neutralization to help reform bonds in the new shape.",
    difficulty: "hard",
    order_index: 14,
  },
  {
    id: "qq-7-015",
    quiz_id: 'quiz-7',
    question: "An oxidation haircolor formula uses hydrogen peroxide. What is its primary chemistry role?",
    answer_a: "Act as an oxidizing agent that supplies oxygen for the color-development reaction",
    answer_b: "Act only as a conditioner that smooths the cuticle",
    answer_c: "Neutralize all alkaline ingredients by forming salt",
    answer_d: "Convert the formula into a suspension",
    correct_answer: "a",
    explanation: "Hydrogen peroxide functions as an oxidizing agent in oxidation haircolor and lightening systems. Its concentration and use depend on the specific product directions.",
    difficulty: "hard",
    order_index: 15,
  },
  {
    id: "qq-7-016",
    quiz_id: 'quiz-7',
    question: "A chemical service unexpectedly becomes much hotter than anticipated. Which response best applies exothermic-reaction and safety logic?",
    answer_a: "Stop and follow the product’s safety directions rather than assuming all heat is normal",
    answer_b: "Continue because any heat proves the product is working correctly",
    answer_c: "Add water automatically to cool every chemical formula",
    answer_d: "Cover the product to trap the heat until processing is complete",
    correct_answer: "a",
    explanation: "Exothermic reactions release heat, but unexpected or excessive heat should trigger product-specific safety action rather than an assumption that the reaction is normal.",
    difficulty: "hard",
    order_index: 16,
  },
  {
    id: "qq-7-017",
    quiz_id: 'quiz-7',
    question: "In a redox reaction, Substance X gains oxygen. What must be true about the paired process?",
    answer_a: "Substance X is being oxidized while another substance is being reduced",
    answer_b: "Substance X is being reduced and no other process is required",
    answer_c: "The reaction must also be acid-alkali neutralization",
    answer_d: "The reaction must absorb heat",
    correct_answer: "a",
    explanation: "Oxidation and reduction occur together. If one substance is oxidized, another substance in the reaction is reduced.",
    difficulty: "hard",
    order_index: 17,
  },
  {
    id: "qq-7-018",
    quiz_id: 'quiz-7',
    question: "Which mixture is best described as stable and uniform, with dissolved material that does not settle out?",
    answer_a: "Solution",
    answer_b: "Suspension",
    answer_c: "Emulsion",
    answer_d: "Pure element",
    correct_answer: "a",
    explanation: "A solution is a stable, uniform mixture in which dissolved material remains distributed throughout the solvent.",
    difficulty: "easy",
    order_index: 18,
  },
  {
    id: "qq-7-019",
    quiz_id: 'quiz-7',
    question: "A product separates while standing, and its label instructs the barber to redistribute the contents before use. Which mixture behavior is most consistent with that observation?",
    answer_a: "Suspension-like settling",
    answer_b: "A pure element changing state",
    answer_c: "A fixed-composition compound",
    answer_d: "A neutral pH reaction",
    correct_answer: "a",
    explanation: "Suspensions contain dispersed particles that can settle. The product label remains the controlling instruction for whether and how to redistribute the product.",
    difficulty: "medium",
    order_index: 19,
  },
  {
    id: "qq-7-020",
    quiz_id: 'quiz-7',
    question: "In an oil-in-water emulsion, which phase is continuous?",
    answer_a: "Water, with oil droplets dispersed through it",
    answer_b: "Oil, with water droplets dispersed through it",
    answer_c: "A solid phase containing both liquids",
    answer_d: "Neither phase; emulsions contain no continuous phase",
    correct_answer: "a",
    explanation: "In an oil-in-water emulsion, water is the continuous phase and oil is dispersed as droplets.",
    difficulty: "medium",
    order_index: 20,
  },
  {
    id: "qq-7-021",
    quiz_id: 'quiz-7',
    question: "A cleanser must help water interact with oily soil so the soil can be rinsed away. Which ingredient function is most directly responsible?",
    answer_a: "Surfactant action that lowers surface tension and interacts with both water and oil",
    answer_b: "A styptic action that contracts tissue",
    answer_c: "A pigment action that deposits color",
    answer_d: "A hard-water mineral that increases residue",
    correct_answer: "a",
    explanation: "Surfactants contain water-attracting and oil-attracting portions, helping water interact with oily soil and supporting cleansing.",
    difficulty: "hard",
    order_index: 21,
  },
  {
    id: "qq-7-022",
    quiz_id: 'quiz-7',
    question: "A formula needs a surfactant class commonly associated with strong cleansing and a negative charge. Which class fits best?",
    answer_a: "Anionic",
    answer_b: "Cationic",
    answer_c: "Nonionic",
    answer_d: "Amphoteric",
    correct_answer: "a",
    explanation: "Anionic surfactants carry a negative charge and are commonly associated with cleansing.",
    difficulty: "hard",
    order_index: 22,
  },
  {
    id: "qq-7-023",
    quiz_id: 'quiz-7',
    question: "A student identifies every product labeled “shake well” as a suspension. What is the best correction?",
    answer_a: "Settling may suggest suspension behavior, but product type should not be identified from one label phrase alone",
    answer_b: "The student is always correct because only suspensions are shaken",
    answer_c: "The student is wrong because suspensions never separate",
    answer_d: "Any product that is shaken must be an emulsion",
    correct_answer: "a",
    explanation: "Some suspensions settle and may require redistribution, but a single label phrase is not enough to classify every product. Use the product’s actual formulation and directions.",
    difficulty: "hard",
    order_index: 23,
  },
  {
    id: "qq-7-024",
    quiz_id: 'quiz-7',
    question: "Which statement correctly describes the standard pH scale?",
    answer_a: "Values below 7 are acidic, 7 is neutral, and values above 7 are alkaline",
    answer_b: "Values below 7 are alkaline, 7 is acidic, and values above 7 are neutral",
    answer_c: "Only values from 4.5 to 5.5 have meaningful pH",
    answer_d: "pH describes product thickness rather than hydrogen-ion conditions",
    correct_answer: "a",
    explanation: "On the standard pH scale, values below 7 are acidic, 7 is neutral, and values above 7 are alkaline.",
    difficulty: "easy",
    order_index: 24,
  },
  {
    id: "qq-7-025",
    quiz_id: 'quiz-7',
    question: "Hair and skin are commonly associated with which pH range in Chapter 7?",
    answer_a: "About 4.5–5.5",
    answer_b: "About 7.5–8.5",
    answer_c: "About 9.5–10.5",
    answer_d: "Exactly 7.0 in every condition",
    correct_answer: "a",
    explanation: "Hair and skin are commonly about pH 4.5–5.5, a slightly acidic range.",
    difficulty: "medium",
    order_index: 25,
  },
  {
    id: "qq-7-026",
    quiz_id: 'quiz-7',
    question: "A service uses a more alkaline product than the hair’s usual range. Which effect is most consistent with Chapter 7 chemistry?",
    answer_a: "Hair can swell and become more porous as the cuticle opens",
    answer_b: "Hair automatically becomes chemically neutral",
    answer_c: "Hair must contract and harden regardless of concentration",
    answer_d: "The product becomes a pure substance",
    correct_answer: "a",
    explanation: "Increasing alkalinity can swell hair and increase porosity as the cuticle opens. The exact effect depends on product strength, formula, and correct use.",
    difficulty: "medium",
    order_index: 26,
  },
  {
    id: "qq-7-027",
    quiz_id: 'quiz-7',
    question: "A student says permanent-wave neutralizer and acid-alkali neutralization are the same reaction because both use the word “neutralize.” What is the best response?",
    answer_a: "They are different: permanent-wave neutralization is an oxidation step, while acid-alkali neutralization forms water and a salt",
    answer_b: "They are identical because every neutralizer lowers pH to 7",
    answer_c: "They are identical only when hydrogen peroxide is absent",
    answer_d: "They are both physical changes with no chemical reaction",
    correct_answer: "a",
    explanation: "Permanent-wave neutralization uses oxidation chemistry. Acid-alkali neutralization is a different reaction in which an acid and alkali form water and a salt.",
    difficulty: "hard",
    order_index: 27,
  },
  {
    id: "qq-7-028",
    quiz_id: 'quiz-7',
    question: "A client has persistent mineral buildup associated with hard water. Which chemistry fact most directly explains why a clarifying or chelating cleanser may be considered?",
    answer_a: "Hard water contains more dissolved minerals that can contribute deposits on hair",
    answer_b: "Hard water is more acidic than all shampoos",
    answer_c: "Soft water permanently closes the cuticle",
    answer_d: "Minerals convert every shampoo into a suspension",
    correct_answer: "a",
    explanation: "Hard water contains higher levels of minerals such as calcium and magnesium, which can contribute deposits and affect lather. Product choice should match the actual buildup and client condition.",
    difficulty: "hard",
    order_index: 28,
  },
  {
    id: "qq-7-029",
    quiz_id: 'quiz-7',
    question: "Which safety conclusion is best when working with a very strong acid or very strong alkali?",
    answer_a: "Either extreme can severely damage hair, so product strength, timing, application, and manufacturer directions matter",
    answer_b: "Only strong alkalis can damage hair; strong acids are always safe on hair",
    answer_c: "Any product below pH 7 is too dangerous for professional use",
    answer_d: "A product’s pH eliminates the need to read its label",
    correct_answer: "a",
    explanation: "Very strong acids and very strong alkalis can severely damage or dissolve hair. Safe use depends on the specific product, concentration, timing, and directions.",
    difficulty: "hard",
    order_index: 29,
  },
  {
    id: "qq-7-030",
    quiz_id: 'quiz-7',
    question: "A barber is choosing between two products with different pH values for chemically treated hair. Which decision rule is strongest?",
    answer_a: "Consider pH together with product purpose, formula, hair condition, chemical history, and manufacturer directions",
    answer_b: "Choose the product closest to pH 7 regardless of its intended use",
    answer_c: "Choose the most acidic product because acid is always beneficial",
    answer_d: "Choose the most alkaline product because it always cleans better",
    correct_answer: "a",
    explanation: "pH is important, but it must be interpreted with the product’s purpose, formula, client condition, history, and directions.",
    difficulty: "hard",
    order_index: 30,
  },
  {
    id: "qq-7-031",
    quiz_id: 'quiz-7',
    question: "Which statement best describes the primary purpose of shampoo?",
    answer_a: "Cleanse the hair and scalp by helping remove oil, soil, debris, and buildup",
    answer_b: "Permanently change the hair’s natural texture",
    answer_c: "Disinfect reusable implements",
    answer_d: "Replace every conditioning product",
    correct_answer: "a",
    explanation: "Shampoo is primarily a cleansing product for the hair and scalp.",
    difficulty: "medium",
    order_index: 31,
  },
  {
    id: "qq-7-032",
    quiz_id: 'quiz-7',
    question: "A client has noticeable product and mineral buildup but already reports dryness. Which choice best applies product-purpose reasoning?",
    answer_a: "Consider a clarifying or chelating cleanser for the buildup while avoiding an automatic fixed schedule and supporting the hair’s condition",
    answer_b: "Use clarifying shampoo every day because buildup is present",
    answer_c: "Use medicated shampoo because it is stronger",
    answer_d: "Use any shampoo because all surfactants have the same purpose",
    correct_answer: "a",
    explanation: "Clarifying or chelating products may address buildup, but frequency and follow-up should match the client’s hair condition and product directions rather than a fixed schedule.",
    difficulty: "medium",
    order_index: 32,
  },
  {
    id: "qq-7-033",
    quiz_id: 'quiz-7',
    question: "A client with color-treated hair wants a cleanser that is less stripping. Which product category is most relevant to consider?",
    answer_a: "A sulfate-free or otherwise gentler cleansing formula appropriate for the client",
    answer_b: "A depilatory because it removes protein",
    answer_c: "A styptic preparation because it contracts tissue",
    answer_d: "A strong alkaline product regardless of label",
    correct_answer: "a",
    explanation: "A sulfate-free or otherwise gentler cleanser may be appropriate when a less-stripping approach fits the client’s condition. Selection still depends on the specific formula and directions.",
    difficulty: "hard",
    order_index: 33,
  },
  {
    id: "qq-7-034",
    quiz_id: 'quiz-7',
    question: "A client cannot receive a conventional wet shampoo at the moment. Which Chapter 7 product category is most relevant to evaluate?",
    answer_a: "Dry or powder shampoo, if appropriate for the client and used according to directions",
    answer_b: "Permanent-wave neutralizer",
    answer_c: "Styptic powder",
    answer_d: "Chemical relaxer",
    correct_answer: "a",
    explanation: "Dry or powder shampoos provide a waterless cleansing option when a wet shampoo is not appropriate or practical.",
    difficulty: "hard",
    order_index: 34,
  },
  {
    id: "qq-7-035",
    quiz_id: 'quiz-7',
    question: "After a chemical service, a product system specifically directs the barber to remove alkaline residue with a balancing cleanser. Which statement is most accurate?",
    answer_a: "Use the directed balancing or neutralizing cleanser, but do not confuse it with permanent-wave oxidation neutralization",
    answer_b: "Any neutralizing shampoo can replace the permanent-wave neutralizer",
    answer_c: "The cleanser should be used after every chemical service even if the system does not direct it",
    answer_d: "The step is unnecessary because pH never affects hair",
    correct_answer: "a",
    explanation: "A balancing cleanser may be appropriate when the product system directs it for alkaline residue. That is different from the oxidation neutralization used in permanent waving.",
    difficulty: "hard",
    order_index: 35,
  },
  {
    id: "qq-7-036",
    quiz_id: 'quiz-7',
    question: "Which list contains Chapter 7 conditioner categories?",
    answer_a: "Instant/rinse-out, treatment/repair, and leave-in",
    answer_b: "Organic, inorganic, and elemental",
    answer_c: "Acid, alkali, and salt",
    answer_d: "Solution, suspension, and emulsion",
    correct_answer: "a",
    explanation: "Chapter 7 includes instant or rinse-out, treatment or repair, and leave-in conditioner categories.",
    difficulty: "easy",
    order_index: 36,
  },
  {
    id: "qq-7-037",
    quiz_id: 'quiz-7',
    question: "Hair needs brief conditioning after shampooing and the product is designed to be rinsed out shortly after application. Which category best fits?",
    answer_a: "Instant/rinse-out conditioner",
    answer_b: "Leave-in conditioner",
    answer_c: "Dry shampoo",
    answer_d: "Styling wax",
    correct_answer: "a",
    explanation: "An instant or rinse-out conditioner is applied after shampooing, left on briefly according to directions, and then rinsed.",
    difficulty: "medium",
    order_index: 37,
  },
  {
    id: "qq-7-038",
    quiz_id: 'quiz-7',
    question: "Why can an acidic conditioner formula improve the feel and manageability of hair?",
    answer_a: "Acidic conditions can help contract and smooth the hair surface, depending on the formula and hair condition",
    answer_b: "Acidic products always dissolve the cuticle completely",
    answer_c: "Acidic conditioner permanently changes disulfide bonds",
    answer_d: "Acidic conditioner converts hair into a pure substance",
    correct_answer: "a",
    explanation: "Acidic conditioner formulas can help contract and smooth the hair surface. Effects depend on the specific formula and condition of the hair.",
    difficulty: "hard",
    order_index: 38,
  },
  {
    id: "qq-7-039",
    quiz_id: 'quiz-7',
    question: "A conditioner contains humectants, oils, proteins, and film-forming ingredients. What is the best way to predict the product’s effect?",
    answer_a: "Evaluate the whole formula, intended purpose, and hair condition rather than assuming one ingredient determines the result",
    answer_b: "Assume every protein repairs all hair damage",
    answer_c: "Assume every silicone always provides heat protection",
    answer_d: "Ignore the formula because all conditioners act identically",
    correct_answer: "a",
    explanation: "Conditioner effects depend on the complete formula and the condition of the hair. Individual ingredient names should not be treated as universal guarantees.",
    difficulty: "hard",
    order_index: 39,
  },
  {
    id: "qq-7-040",
    quiz_id: 'quiz-7',
    question: "What does USP indicate when it appears with certain cosmetic or pharmaceutical ingredients?",
    answer_a: "A recognized standard related to identity, strength, quality, or purity",
    answer_b: "A guarantee that the product is appropriate for every client",
    answer_c: "A required pH of 7 for the finished product",
    answer_d: "A classification showing the product is organic",
    correct_answer: "a",
    explanation: "USP refers to United States Pharmacopeia standards used for the identity, strength, quality, or purity of certain ingredients and preparations.",
    difficulty: "medium",
    order_index: 40,
  },
  {
    id: "qq-7-041",
    quiz_id: 'quiz-7',
    question: "Which ingredient-purpose pairing is most defensible?",
    answer_a: "Glycerin — humectant used to help attract and retain moisture",
    answer_b: "Alum — surfactant used to emulsify oil and water",
    answer_c: "Petrolatum — oxidizing agent used to develop haircolor",
    answer_d: "Witch hazel — reducing agent used to break disulfide bonds",
    correct_answer: "a",
    explanation: "Glycerin is commonly used as a humectant. The other pairings assign unrelated chemistry functions.",
    difficulty: "medium",
    order_index: 41,
  },
  {
    id: "qq-7-042",
    quiz_id: 'quiz-7',
    question: "A formula needs an alkaline ingredient to adjust pH but the exact role depends on the product system. Which Chapter 7 ingredient family is relevant?",
    answer_a: "Alkanolamines",
    answer_b: "Humectants only",
    answer_c: "Styptic salts only",
    answer_d: "Chelating agents only",
    correct_answer: "a",
    explanation: "Alkanolamines are alkaline ingredients used in some cosmetic formulations to adjust pH or neutralize acids.",
    difficulty: "hard",
    order_index: 42,
  },
  {
    id: "qq-7-043",
    quiz_id: 'quiz-7',
    question: "A barber is selecting among a styling aid, massage cream, astringent, and moisturizer. What should drive the choice?",
    answer_a: "The intended service purpose, client condition, formula, and product directions",
    answer_b: "The product with the strongest fragrance",
    answer_c: "The product with the highest pH regardless of use",
    answer_d: "The product labeled organic because organic products are always safer",
    correct_answer: "a",
    explanation: "Cosmetic preparations serve different purposes. Product selection should match the service goal, client condition, formula, and directions.",
    difficulty: "hard",
    order_index: 43,
  },
  {
    id: "qq-7-044",
    quiz_id: 'quiz-7',
    question: "Before using an unfamiliar chemical product, which information source should the barber prioritize?",
    answer_a: "The product label and manufacturer directions, plus the SDS when applicable",
    answer_b: "A social-media comment describing another person’s use",
    answer_c: "The color of the container",
    answer_d: "A general rule learned for a different product",
    correct_answer: "a",
    explanation: "Labels, manufacturer directions, and applicable SDS information provide product-specific use and safety guidance.",
    difficulty: "medium",
    order_index: 44,
  },
  {
    id: "qq-7-045",
    quiz_id: 'quiz-7',
    question: "Two chemical products are available at the station, but neither label authorizes mixing them. What is the safest decision?",
    answer_a: "Do not mix them; check the product directions or manufacturer information first",
    answer_b: "Mix a small amount because small quantities cannot react dangerously",
    answer_c: "Combine them if their colors look similar",
    answer_d: "Add water first because dilution makes every combination safe",
    correct_answer: "a",
    explanation: "Chemical interactions can create hazards. Do not combine products unless their directions or manufacturer guidance specifically permit the mixture.",
    difficulty: "medium",
    order_index: 45,
  },
  {
    id: "qq-7-046",
    quiz_id: 'quiz-7',
    question: "A chemical service may require a predisposition, strand, or other pre-service test. How should the barber determine the correct test and timing?",
    answer_a: "Use the specific product label, manufacturer directions, and applicable rules",
    answer_b: "Use the same 24-hour patch test for every service",
    answer_c: "Skip testing whenever the client has used the product before",
    answer_d: "Choose the test based only on product fragrance",
    correct_answer: "a",
    explanation: "Pre-service testing is product- and service-specific. The required method and timing come from the product directions and applicable rules.",
    difficulty: "medium",
    order_index: 46,
  },
  {
    id: "qq-7-047",
    quiz_id: 'quiz-7',
    question: "A chemical splashes into a client’s eye. Which immediate response best follows safety logic?",
    answer_a: "Begin flushing with clean water and follow the product label or SDS emergency directions; do not try to neutralize with another chemical",
    answer_b: "Apply an opposite-pH product to neutralize the chemical in the eye",
    answer_c: "Wait for visible redness before acting",
    answer_d: "Cover the eye and continue the service",
    correct_answer: "a",
    explanation: "Immediate flushing and product-specific emergency guidance are appropriate. Attempting to neutralize an eye exposure with another chemical can worsen the injury.",
    difficulty: "hard",
    order_index: 47,
  },
  {
    id: "qq-7-048",
    quiz_id: 'quiz-7',
    question: "A product label and SDS call for eye protection and ventilation during mixing. Which action best demonstrates correct chemical-safety practice?",
    answer_a: "Use the specified PPE and ventilation before mixing",
    answer_b: "Skip PPE if the barber has used the product many times",
    answer_c: "Use only gloves because one form of PPE replaces the others",
    answer_d: "Increase processing time to compensate for ventilation",
    correct_answer: "a",
    explanation: "PPE and ventilation should follow the product-specific label, SDS, and service requirements.",
    difficulty: "hard",
    order_index: 48,
  },
  {
    id: "qq-7-049",
    quiz_id: 'quiz-7',
    question: "Which storage practice is most defensible for professional chemical products?",
    answer_a: "Keep products properly identified and follow label/SDS storage directions, including separation of incompatible chemicals when required",
    answer_b: "Transfer chemicals into unlabeled containers to save space",
    answer_c: "Store all chemicals together because professional products are compatible",
    answer_d: "Ignore temperature or light instructions once the container is opened",
    correct_answer: "a",
    explanation: "Chemical storage should preserve identification and follow product-specific storage and compatibility directions.",
    difficulty: "hard",
    order_index: 49,
  },
  {
    id: "qq-7-050",
    quiz_id: 'quiz-7',
    question: "A client’s hair is already compromised, the service uses an alkaline chemical, and the product directions warn against overprocessing. Which reasoning sequence is best?",
    answer_a: "Recognize that alkalinity can increase swelling and porosity, assess the hair condition, follow the exact timing/directions, and stop if safety limits are reached",
    answer_b: "Assume a higher pH guarantees a better result and extend the processing time",
    answer_c: "Neutralize the product by adding an acid before applying it",
    answer_d: "Ignore the client’s chemical history because pH alone determines the outcome",
    correct_answer: "a",
    explanation: "Safe chemical-service reasoning combines chemistry with client condition and product directions. Alkalinity can increase swelling and porosity, so overprocessing risk must be controlled.",
    difficulty: "hard",
    order_index: 50,
  },
]
