import { Flashcard } from '@/types'

// Chapter 12: Men's Facial Massage and Treatments
// Repository legacy source note referenced textbook-images/chapter-12/.
// C12-3 audits this bank against the retained Chapter 12 repository analysis
// and hardened lesson boundaries; it is not a fresh page-by-page textbook verification.

export const chapter12PremiumFlashcards: Flashcard[] = [
  // === LEARNING OBJECTIVES & INTRODUCTION ===
  {
    id: 'fc-ch12-001',
    chapter_id: 'ch-12',
    front: "Why should barbers study facial massage and facial treatments?",
    back: "Chapter 12 treats facial massage and facial treatments as professional cosmetic grooming services. Barbers should understand the services that are within their applicable scope, including consultation, sanitation, safe technique, contraindications, product selection, client comfort, and referral boundaries.",
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch12-002',
    chapter_id: 'ch-12',
    front: "What client-demand point does Chapter 12 make about facial services?",
    back: "The retained Chapter 12 material presents facial services as an area of client interest and professional grooming opportunity. C12-3 does not retain the legacy percentage-growth claim because the current repository source does not independently establish that market statistic.",
    category: 'Introduction',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },

  // === SUBDERMAL SYSTEMS ===
  {
    id: 'fc-ch12-003',
    chapter_id: 'ch-12',
    front: 'What are the three subdermal systems associated with facial treatments?',
    back: 'Muscles, nerves, and arteries. Muscles produce movement, nerves carry messages, and arteries transport blood under high pressure.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch12-004',
    chapter_id: 'ch-12',
    front: 'What is the definition of a muscle?',
    back: 'Fibrous tissues that have the ability to stretch and contract to produce all body movements.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch12-005',
    chapter_id: 'ch-12',
    front: 'What is the definition of a nerve?',
    back: 'Long, white, fibrous cords that act as message carriers from the brain and spinal column to and from all parts of the body.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-ch12-006',
    chapter_id: 'ch-12',
    front: 'What is the definition of an artery?',
    back: 'Elastic, muscular, thick-walled blood vessels that transport blood under high pressure.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch12-007',
    chapter_id: 'ch-12',
    front: 'What is the definition of a vein?',
    back: 'Thin-walled vessels that contain valves that keep the blood flowing to the heart and prevent it from flowing backward.',
    category: 'Anatomy',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },

  // === MUSCLES ===
  {
    id: 'fc-ch12-008',
    chapter_id: 'ch-12',
    front: 'What is the epicranius (occipitofrontalis)?',
    back: 'A broad muscle that covers the top of the skull. It consists of the frontalis at the front and the occipitalis at the back, connected by the epicranial aponeurosis.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch12-009',
    chapter_id: 'ch-12',
    front: 'What does the frontalis muscle do?',
    back: 'Draws the scalp forward and causes wrinkles across the forehead.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-ch12-010',
    chapter_id: 'ch-12',
    front: 'What does the occipitalis muscle do?',
    back: 'Draws the scalp backward.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-ch12-011',
    chapter_id: 'ch-12',
    front: 'What is the epicranial aponeurosis?',
    back: 'The tendon that connects the occipitalis and frontalis muscles.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch12-012',
    chapter_id: 'ch-12',
    front: 'What does the orbicularis oculi muscle do?',
    back: 'Surrounds the eye socket and closes the eyelid.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-ch12-013',
    chapter_id: 'ch-12',
    front: 'What does the corrugator muscle do?',
    back: 'Draws the eyebrows down and in, and wrinkles the forehead vertically.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch12-014',
    chapter_id: 'ch-12',
    front: 'What does the procerus muscle do?',
    back: 'Covers the top of the nose, depresses the eyebrow, and causes wrinkles across the bridge of the nose.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch12-015',
    chapter_id: 'ch-12',
    front: 'What does the buccinator muscle do?',
    back: 'A thin, flat muscle between the upper and lower jaws that compresses the cheeks and expels air between the lips.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch12-016',
    chapter_id: 'ch-12',
    front: 'What does the orbicularis oris muscle do?',
    back: 'A flat band of muscle around the upper and lower lips that compresses, contracts, puckers, and wrinkles the lips.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch12-017',
    chapter_id: 'ch-12',
    front: 'What does the masseter muscle do?',
    back: 'Coordinates opening and closing of the mouth; a chewing muscle.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-ch12-018',
    chapter_id: 'ch-12',
    front: 'What does the temporalis muscle do?',
    back: 'Coordinates opening and closing of the mouth; a chewing muscle that works with the masseter.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch12-019',
    chapter_id: 'ch-12',
    front: 'What does the platysma muscle do?',
    back: 'A broad muscle extending from the chest and shoulder muscles to the side of the chin; responsible for depressing the lower jaw and lip.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch12-020',
    chapter_id: 'ch-12',
    front: 'What does the sternocleidomastoideus muscle do?',
    back: 'Extends from the collar and chest bones to the temporal bone behind the ear; bends and rotates the head.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },
  {
    id: 'fc-ch12-021',
    chapter_id: 'ch-12',
    front: 'What does the trapezius muscle do?',
    back: 'Covers the back of the neck, allowing movement of the shoulders.',
    category: 'Muscles',
    difficulty: 'easy',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch12-022',
    chapter_id: 'ch-12',
    front: 'What does the zygomaticus major muscle do?',
    back: 'Pulls the mouth upward and backward, as when laughing or smiling.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch12-023',
    chapter_id: 'ch-12',
    front: 'What does the mentalis muscle do?',
    back: 'Elevates the lower lip and raises and wrinkles the skin of the chin.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch12-024',
    chapter_id: 'ch-12',
    front: 'What does the risorius muscle do?',
    back: 'Draws the corner of the mouth out and back, as when grinning.',
    category: 'Muscles',
    difficulty: 'medium',
    order_index: 24,
    is_active: true,
  },

  // === CRANIAL NERVES ===
  {
    id: 'fc-ch12-025',
    chapter_id: 'ch-12',
    front: 'How many pairs of cranial nerves are there?',
    back: '12 pairs, all connected to a part of the brain surface.',
    category: 'Nerves',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch12-026',
    chapter_id: 'ch-12',
    front: 'What is the fifth cranial nerve (trigeminal nerve)?',
    back: 'The chief sensory nerve of the face that also serves as the motor nerve that controls chewing.',
    category: 'Nerves',
    difficulty: 'medium',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch12-027',
    chapter_id: 'ch-12',
    front: 'What is the seventh cranial nerve (facial nerve)?',
    back: 'The sensory-motor nerve that controls motions of the face, scalp, and neck and sections of the palate and tongue.',
    category: 'Nerves',
    difficulty: 'medium',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch12-028',
    chapter_id: 'ch-12',
    front: 'What is the eleventh cranial nerve (accessory nerve)?',
    back: 'The motor nerve that controls motions of the neck muscles.',
    category: 'Nerves',
    difficulty: 'medium',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-ch12-029',
    chapter_id: 'ch-12',
    front: 'What are cervical nerves?',
    back: 'Spinal nerves that originate at the spinal cord; their branches supply the muscles and scalp at the back of the head and neck.',
    category: 'Nerves',
    difficulty: 'medium',
    order_index: 29,
    is_active: true,
  },

  // === ARTERIES & VEINS ===
  {
    id: 'fc-ch12-030',
    chapter_id: 'ch-12',
    front: 'What are the common carotid arteries?',
    back: 'The main sources of blood supply to the head, face, and neck; located at the sides of the neck.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-ch12-031',
    chapter_id: 'ch-12',
    front: 'What does the external maxillary (facial) artery supply?',
    back: 'The lower region of the face, mouth, and nose.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch12-032',
    chapter_id: 'ch-12',
    front: 'What does the superficial temporal artery supply?',
    back: 'Muscles, skin, and scalp on the front, side, and top of the head.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch12-033',
    chapter_id: 'ch-12',
    front: 'What does the occipital artery supply?',
    back: 'The scalp and back of the head up to the crown.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch12-034',
    chapter_id: 'ch-12',
    front: 'What does the posterior auricular artery supply?',
    back: 'The scalp behind and above the ear.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-ch12-035',
    chapter_id: 'ch-12',
    front: 'How does deoxygenated blood from the head, face, and neck return to the heart?',
    back: 'Through the internal jugular and external jugular veins located on each side of the neck.',
    category: 'Circulation',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },

  // === PHYSIOLOGICAL EFFECTS OF MASSAGE ===
  {
    id: 'fc-ch12-036',
    chapter_id: 'ch-12',
    front: "What determines whether a facial massage technique is appropriate and effective as a cosmetic service?",
    back: "Use the source-covered movement, pressure, direction, rhythm, and duration with continuous attention to client comfort and contraindications. Keep expected outcomes within cosmetic-service scope rather than promising medical, pain-relief, fat-reduction, or other therapeutic effects.",
    category: 'Massage Theory',
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch12-037',
    chapter_id: 'ch-12',
    front: 'What factors determine the benefits of a massage manipulation?',
    back: 'The type of massage movement used, the amount of pressure used, the direction of the movement, and the duration of the manipulation.',
    category: 'Massage Theory',
    difficulty: 'medium',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch12-038',
    chapter_id: 'ch-12',
    front: 'What is a motor point?',
    back: 'A point on the skin where nerves that control the underlying muscle are located. When electrical stimulation is applied, the muscle responds by contracting.',
    category: 'Massage Theory',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch12-039',
    chapter_id: 'ch-12',
    front: "How should a barber treat the Chapter 12 term “trigger point” within scope?",
    back: "Chapter 12 uses the term for a tender localized area in muscle. A barber may recognize the source term for study purposes, but should not diagnose the cause of pain or present facial massage as medical treatment.",
    category: 'Massage Theory',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },

  // === MASSAGE MANIPULATIONS ===
  {
    id: 'fc-ch12-040',
    chapter_id: 'ch-12',
    front: 'What is effleurage?',
    back: 'A light, continuous stroking movement applied slowly and rhythmically over the skin with no pressure. Palms are used over large surfaces; fingertips work small surfaces like around the eyes.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-ch12-041',
    chapter_id: 'ch-12',
    front: 'What is petrissage?',
    back: 'A kneading movement performed with light, firm pressure. The skin and flesh are grasped between the thumb and fingers, then gently squeezed, rolled, or pinched. Provides deeper stimulation to muscles, nerves, and skin glands.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch12-042',
    chapter_id: 'ch-12',
    front: 'What is friction?',
    back: 'A deep rubbing movement in which pressure is applied on the skin with the fingers or palms while moving over an underlying structure. Light circular friction is used on the face and neck.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-ch12-043',
    chapter_id: 'ch-12',
    front: "What is percussion (tapotement)?",
    back: "Short, quick tapping, slapping, or hacking movements. In facial-service use, apply only the source-appropriate light form with controlled pressure and client comfort; do not promise nerve, muscle-toning, or medical effects.",
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },
  {
    id: 'fc-ch12-044',
    chapter_id: 'ch-12',
    front: 'What are the three forms of tapotement?',
    back: 'Tapping (gentlest, fingertips down), slapping (lower to mid-fingers strike lightly), and hacking/chopping (outer edges of hands, used only on back and shoulders).',
    category: 'Massage Movements',
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch12-045',
    chapter_id: 'ch-12',
    front: 'What is vibration?',
    back: 'A rapid shaking movement over the skin section with the fingertips or an electric massager. Used to transmit a trembling movement to the skin and underlying structures.',
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch12-046',
    chapter_id: 'ch-12',
    front: "How should duration be handled when using vibration on one area?",
    back: "Keep vibration brief and controlled, monitor client comfort, and follow the applicable device or service guidance. Do not treat one legacy time statement as a universal device setting.",
    category: 'Massage Movements',
    difficulty: 'easy',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch12-047',
    chapter_id: 'ch-12',
    front: 'What direction should massage pressure be applied on the face?',
    back: 'In an upward direction to avoid loss of skin resiliency. When facial hair is present, direct movements in the direction of beard growth.',
    category: 'Massage Guidelines',
    difficulty: 'easy',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch12-048',
    chapter_id: 'ch-12',
    front: 'What is the correct direction for massage movements relative to muscle attachment?',
    back: 'From the insertion (attachment to movable bone) toward the origin (attachment to immovable bone).',
    category: 'Massage Guidelines',
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-ch12-049',
    chapter_id: 'ch-12',
    front: 'What is feathering-off?',
    back: 'Gradually reducing pressure when removing hands from the client\'s face to gently lift from the skin surface.',
    category: 'Massage Guidelines',
    difficulty: 'easy',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch12-050',
    chapter_id: 'ch-12',
    front: "What is the safe rule for massage contraindications?",
    back: "Do not massage skin that is actively inflamed, open, potentially contagious, or otherwise unsuitable for the planned service. If a health condition, medication, recent procedure, or client response makes safety uncertain, modify or defer the service and recommend appropriate evaluation without diagnosing.",
    category: 'Massage Guidelines',
    difficulty: 'easy',
    order_index: 50,
    is_active: true,
  },
  {
    id: 'fc-ch12-051',
    chapter_id: 'ch-12',
    front: 'How often can normal skin or scalp be kept in good condition with treatments?',
    back: 'Weekly treatments with proper home care.',
    category: 'Massage Guidelines',
    difficulty: 'easy',
    order_index: 51,
    is_active: true,
  },

  // === FACIAL EQUIPMENT ===
  {
    id: 'fc-ch12-052',
    chapter_id: 'ch-12',
    front: 'What is an electric massager?',
    back: 'A handheld unit that transmits vibrations through the barber\'s hand and fingertips to the client\'s skin and muscles. Used over heavy muscle tissue like the scalp and shoulders.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-ch12-053',
    chapter_id: 'ch-12',
    front: "How should an electric massager be used in a facial or scalp service?",
    back: "Use it only for the cosmetic service purpose described by the device instructions, with controlled contact and client comfort. Do not promise physiological, glandular, circulatory, or therapeutic outcomes beyond supported product or device directions.",
    category: 'Equipment',
    difficulty: 'medium',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-ch12-054',
    chapter_id: 'ch-12',
    front: "When should an electric massager not be used?",
    back: "Do not use it when the device label, client consultation, observable condition, or applicable rules indicate a contraindication, or when safe use cannot be established. Defer the service rather than interpreting a medical condition.",
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-ch12-055',
    chapter_id: 'ch-12',
    front: 'What is a brush machine?',
    back: 'An electrical appliance with interchangeable brushes that attach to a rotating head. Used for mechanical exfoliation to stimulate, cleanse, and remove dead cells.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 55,
    is_active: true,
  },
  {
    id: 'fc-ch12-056',
    chapter_id: 'ch-12',
    front: "When should mechanical brushing be avoided or deferred?",
    back: "Avoid brushing irritated, injured, recently exfoliated, or otherwise unsuitable skin. If medication or a recent procedure may affect service safety, rely on product/device guidance and appropriate professional evaluation rather than making a medical determination.",
    category: 'Equipment',
    difficulty: 'medium',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-ch12-057',
    chapter_id: 'ch-12',
    front: "What is a facial steamer?",
    back: "An electrical appliance that produces moist steam for a cosmetic facial service. Use it according to manufacturer directions, maintain comfortable exposure, and avoid unsupported claims that steam disinfects, treats disease, or produces guaranteed physiological effects.",
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-ch12-058',
    chapter_id: 'ch-12',
    front: 'What type of water should be used in a facial steamer?',
    back: 'Only distilled or filtered water to avoid mineral and calcium deposits that can damage the unit.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-ch12-059',
    chapter_id: 'ch-12',
    front: 'What is a hot-towel cabinet used for?',
    back: 'Ensures a ready supply of warm towels for facial services. Towels are folded, dampened with hot water, wrung out, and placed in the cabinet.',
    category: 'Equipment',
    difficulty: 'easy',
    order_index: 59,
    is_active: true,
  },

  // === ELECTROTHERAPY ===
  {
    id: 'fc-ch12-060',
    chapter_id: 'ch-12',
    front: 'What are the two electrotherapy modalities most often used in facial treatments?',
    back: 'High-frequency current and galvanic current.',
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-ch12-061',
    chapter_id: 'ch-12',
    front: 'What is an electrode?',
    back: 'A device used to apply and direct electrical current to the client\'s skin. High-frequency uses one electrode; galvanic uses two (positive anode and negative cathode).',
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-ch12-062',
    chapter_id: 'ch-12',
    front: "What is high-frequency current (tesla current) in Chapter 12?",
    back: "A high-rate oscillating electrical modality described in the Chapter 12 source for facial and scalp service. Use only within device instructions, training, applicable scope, and client-safety guidance; do not generalize legacy therapeutic claims.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 62,
    is_active: true,
  },
  {
    id: 'fc-ch12-063',
    chapter_id: 'ch-12',
    front: "What should a barber know about claimed high-frequency effects?",
    back: "The legacy material lists several physiological and antiseptic effects, but C12-3 does not present those as guaranteed outcomes. For service decisions, follow the specific device labeling, training, contraindications, and cosmetic scope.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-ch12-064',
    chapter_id: 'ch-12',
    front: "How should high-frequency treatment time be determined?",
    back: "Follow the specific device manufacturer’s directions and applicable training or rules. Do not use a single legacy minute value as a universal setting for every high-frequency device or service.",
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 64,
    is_active: true,
  },
  {
    id: 'fc-ch12-065',
    chapter_id: 'ch-12',
    front: "What are the two source-presented high-frequency application methods?",
    back: "Direct application places the electrode at the service area; indirect application uses the client as part of the circuit as described by the device method. Use either method only when the specific device instructions and training support it, without making germicidal or medical-treatment promises.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-ch12-066',
    chapter_id: 'ch-12',
    front: "How should high-frequency contraindications be handled?",
    back: "Use the device manufacturer’s contraindications, client consultation, applicable rules, and training. When a health condition, implanted device, medication, pregnancy, skin finding, or other factor makes safety uncertain, defer rather than independently deciding medical suitability.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-ch12-067',
    chapter_id: 'ch-12',
    front: "How should high-frequency electrodes be cleaned and disinfected?",
    back: "Follow the electrode and disinfectant manufacturer directions and applicable infection-control rules. Protect electrical components from improper immersion and store processed electrodes so they remain clean; do not rely on one universal contact-time recipe.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-ch12-068',
    chapter_id: 'ch-12',
    front: "What does a galvanic machine do?",
    back: "It converts alternating current to direct current for source-presented galvanic facial-service methods such as desincrustation or ion-based product application. Use only within device instructions and cosmetic scope; do not present it as acne treatment.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 68,
    is_active: true,
  },
  {
    id: 'fc-ch12-069',
    chapter_id: 'ch-12',
    front: "What is desincrustation in the Chapter 12 source?",
    back: "A galvanic-service method described for loosening or emulsifying surface oil and debris to support cosmetic cleansing. Follow the specific product and device directions rather than claiming “deep pore” cleansing or medical treatment.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 69,
    is_active: true,
  },
  {
    id: 'fc-ch12-070',
    chapter_id: 'ch-12',
    front: "What is iontophoresis in the Chapter 12 source?",
    back: "A galvanic method using ion-containing, water-soluble products with electrical current. Use the technique only as directed by the specific device and product; avoid broad claims that any product will penetrate to a guaranteed depth.",
    category: 'Electrotherapy',
    difficulty: 'hard',
    order_index: 70,
    is_active: true,
  },
  {
    id: 'fc-ch12-071',
    chapter_id: 'ch-12',
    front: "What is cataphoresis in the Chapter 12 source?",
    back: "The source term for use of the positive pole (anode) with compatible products in a galvanic service. Follow the product and device instructions and avoid promising follicle-closing, anti-inflammatory, nerve-soothing, or tissue-hardening medical effects.",
    category: 'Electrotherapy',
    difficulty: 'hard',
    order_index: 71,
    is_active: true,
  },
  {
    id: 'fc-ch12-072',
    chapter_id: 'ch-12',
    front: "What is anaphoresis in the Chapter 12 source?",
    back: "The source term for use of the negative pole (cathode) with compatible products in a galvanic service. Follow the product and device instructions and avoid promising circulatory, neurologic, or tissue-changing outcomes.",
    category: 'Electrotherapy',
    difficulty: 'hard',
    order_index: 72,
    is_active: true,
  },
  {
    id: 'fc-ch12-073',
    chapter_id: 'ch-12',
    front: "What is microcurrent?",
    back: "A low-level electrical modality included in the Chapter 12 equipment coverage. Use it only within training, manufacturer directions, client-safety guidance, and applicable scope; do not guarantee lifting, anti-aging, or medical outcomes.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 73,
    is_active: true,
  },
  {
    id: 'fc-ch12-074',
    chapter_id: 'ch-12',
    front: 'What is microdermabrasion?',
    back: 'A form of mechanical exfoliation that sprays aluminum oxide or other microcrystals across the skin to exfoliate dead cells, which are then vacuumed off.',
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 74,
    is_active: true,
  },
  {
    id: 'fc-ch12-075',
    chapter_id: 'ch-12',
    front: "What is light therapy in the Chapter 12 equipment section?",
    back: "The source groups ultraviolet, infrared, and LED/light modalities under light-based equipment. Device type, purpose, exposure, contraindications, eye protection, and scope depend on the specific device and applicable guidance.",
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 75,
    is_active: true,
  },
  {
    id: 'fc-ch12-076',
    chapter_id: 'ch-12',
    front: "How should the source terms UVA, UVB, and UVC be studied?",
    back: "Recognize them as different ultraviolet bands identified in the legacy Chapter 12 material. Do not convert historical labels such as “therapeutic” or “germicidal” into a promise that a barbering service treats disease or sterilizes skin.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 76,
    is_active: true,
  },
  {
    id: 'fc-ch12-077',
    chapter_id: 'ch-12',
    front: "How should lamp distance be determined for ultraviolet or infrared equipment?",
    back: "Use the specific device manufacturer’s operating distance and safety instructions. C12-3 does not retain one universal distance because equipment and instructions can vary.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 77,
    is_active: true,
  },
  {
    id: 'fc-ch12-078',
    chapter_id: 'ch-12',
    front: "How should infrared exposure time be determined?",
    back: "Use the specific device manufacturer’s exposure limits and safety instructions, monitor client comfort, and stop if the service becomes unsafe. Do not treat one legacy minute value as universal.",
    category: 'Electrotherapy',
    difficulty: 'easy',
    order_index: 78,
    is_active: true,
  },
  {
    id: 'fc-ch12-079',
    chapter_id: 'ch-12',
    front: "How should general electrotherapy contraindications be handled?",
    back: "Follow the specific device contraindications, manufacturer directions, client consultation, applicable rules, and training. If a health condition, implanted device, medication, pregnancy, skin finding, or other factor creates uncertainty, defer the service rather than make a medical suitability decision.",
    category: 'Electrotherapy',
    difficulty: 'medium',
    order_index: 79,
    is_active: true,
  },

  // === SAFETY PRECAUTIONS ===
  {
    id: 'fc-ch12-080',
    chapter_id: 'ch-12',
    front: 'What are key safety precautions when using electrical equipment in the barbershop?',
    back: 'Disconnect when not in use, study instructions first, keep wires/plugs safe, inspect frequently, avoid wet cords, clean/disinfect electrodes, protect the client, avoid touching metal during treatments, do not leave the room when client is attached to a device.',
    category: 'Safety',
    difficulty: 'medium',
    order_index: 80,
    is_active: true,
  },
  {
    id: 'fc-ch12-081',
    chapter_id: 'ch-12',
    front: "What is the safe rule for products used before electrical facial equipment?",
    back: "Use only products that the specific device and product instructions identify as compatible. Avoid flammable or otherwise incompatible preparations and follow all manufacturer safety directions.",
    category: 'Safety',
    difficulty: 'medium',
    order_index: 81,
    is_active: true,
  },

  // === SKIN TYPES ===
  {
    id: 'fc-ch12-082',
    chapter_id: 'ch-12',
    front: 'What are the four basic skin types?',
    back: 'Dry (alipidic), normal, combination, and oily.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 82,
    is_active: true,
  },
  {
    id: 'fc-ch12-083',
    chapter_id: 'ch-12',
    front: "What characterizes dry (alipidic) skin in the Chapter 12 analysis framework?",
    back: "It is described by reduced surface oil and may show dryness or flaking. Use this as a cosmetic observation for product selection, not as a medical diagnosis or a reason to promise stimulation of oil production.",
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 83,
    is_active: true,
  },
  {
    id: 'fc-ch12-084',
    chapter_id: 'ch-12',
    front: 'What characterizes normal skin?',
    back: 'Good water-oil balance, normal pore size, free of blemishes. Needs maintenance and preservative care.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 84,
    is_active: true,
  },
  {
    id: 'fc-ch12-085',
    chapter_id: 'ch-12',
    front: "What characterizes oily skin in the Chapter 12 analysis framework?",
    back: "It is described by visible surface oil and may have more noticeable follicle openings. Use the observation to choose appropriate cosmetic products and service steps rather than assuming one universal cleansing or exfoliation prescription.",
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 85,
    is_active: true,
  },
  {
    id: 'fc-ch12-086',
    chapter_id: 'ch-12',
    front: 'What characterizes combination skin?',
    back: 'Both oily and dry in different areas. The T-zone (forehead, nose, chin) tends to be oily; cheeks and outer areas tend to be dry.',
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 86,
    is_active: true,
  },
  {
    id: 'fc-ch12-087',
    chapter_id: 'ch-12',
    front: "What is the T-zone?",
    back: "The forehead, nose, and chin area. In the Chapter 12 skin-analysis framework, these areas may show different oiliness or visible follicle-opening patterns than the cheeks.",
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 87,
    is_active: true,
  },
  {
    id: 'fc-ch12-088',
    chapter_id: 'ch-12',
    front: "How should a barber discuss visible lines and wrinkles during skin analysis?",
    back: "Describe observable lines and texture without assigning a medical cause. The legacy material lists aging, dryness, repeated movement, and skin changes, but cosmetic consultation should focus on observation and appropriate product/service selection.",
    category: 'Skin Types',
    difficulty: 'easy',
    order_index: 88,
    is_active: true,
  },

  // === SKIN ANALYSIS ===
  {
    id: 'fc-ch12-089',
    chapter_id: 'ch-12',
    front: 'What tool is preferable for analyzing skin?',
    back: 'A magnifying lamp or light. If unavailable, a close inspection will suffice.',
    category: 'Skin Analysis',
    difficulty: 'easy',
    order_index: 89,
    is_active: true,
  },
  {
    id: 'fc-ch12-090',
    chapter_id: 'ch-12',
    front: 'What are the five steps for performing a skin analysis and client consultation?',
    back: '1. Observe skin type, condition, and appearance; feel texture. 2. Ask about appearance and home care. 3. Discuss procedure, products, and why. 4. Encourage questions and determine action together. 5. Record information for next visit.',
    category: 'Skin Analysis',
    difficulty: 'medium',
    order_index: 90,
    is_active: true,
  },

  // === SKIN CARE PRODUCTS ===
  {
    id: 'fc-ch12-091',
    chapter_id: 'ch-12',
    front: 'What are the five categories of skin care products?',
    back: 'Cleansers, exfoliants, skin tonics, masks, and moisturizers.',
    category: 'Products',
    difficulty: 'easy',
    order_index: 91,
    is_active: true,
  },
  {
    id: 'fc-ch12-092',
    chapter_id: 'ch-12',
    front: 'What is the difference between face washes, cleansing lotions, and cleansing creams?',
    back: 'Face washes are water-based with neutral/slightly acidic pH for oily/combination skin. Cleansing lotions are water-based emulsions with emollients for normal/combination skin. Cleansing creams are heavier oil-based emulsions for dissolving dirt and makeup.',
    category: 'Products',
    difficulty: 'medium',
    order_index: 92,
    is_active: true,
  },
  {
    id: 'fc-ch12-093',
    chapter_id: 'ch-12',
    front: "How does Chapter 12 distinguish fresheners, toners, and astringents?",
    back: "They are different cosmetic product categories/formulations used after cleansing or as part of a service plan. Because formulations vary, use the actual label and client analysis rather than memorizing one universal alcohol-percentage range.",
    category: 'Products',
    difficulty: 'medium',
    order_index: 93,
    is_active: true,
  },
  {
    id: 'fc-ch12-094',
    chapter_id: 'ch-12',
    front: 'What is witch hazel used for in facial treatments?',
    back: 'Works as an astringent and can be used as a toning tonic in facial treatments and shave services.',
    category: 'Products',
    difficulty: 'easy',
    order_index: 94,
    is_active: true,
  },
  {
    id: 'fc-ch12-095',
    chapter_id: 'ch-12',
    front: 'What do moisturizers contain?',
    back: 'Moisture-attracting humectants and emollients that prevent moisture from evaporating from the skin.',
    category: 'Products',
    difficulty: 'easy',
    order_index: 95,
    is_active: true,
  },
  {
    id: 'fc-ch12-096',
    chapter_id: 'ch-12',
    front: 'What is rolling cream?',
    back: 'A thick, smooth, nongranular exfoliating cream, usually pink. Applied in a thin layer and rolled off with firm stroking motions to lift dead cells and impurities.',
    category: 'Products',
    difficulty: 'medium',
    order_index: 96,
    is_active: true,
  },
  {
    id: 'fc-ch12-097',
    chapter_id: 'ch-12',
    front: "When should rolling cream be avoided?",
    back: "Avoid it when the skin is irritated, injured, very sensitive, recently exfoliated, or otherwise unsuitable, and follow the product label. Do not treat a skin-type list as a universal contraindication for every formulation.",
    category: 'Products',
    difficulty: 'medium',
    order_index: 97,
    is_active: true,
  },
  {
    id: 'fc-ch12-098',
    chapter_id: 'ch-12',
    front: "What are chemical exfoliants?",
    back: "Cosmetic exfoliating products that may use acids or enzymes to loosen surface dead-cell buildup. Use only within product directions, training, applicable scope, and any jurisdiction-specific requirements.",
    category: 'Products',
    difficulty: 'medium',
    order_index: 98,
    is_active: true,
  },
  {
    id: 'fc-ch12-099',
    chapter_id: 'ch-12',
    front: 'What are the four types of masks?',
    back: 'Clay masks (oily/combination, absorb sebum), cream masks (dry skin, moisturizing), gel masks (sensitive/dehydrated), and paraffin wax masks (pack method).',
    category: 'Products',
    difficulty: 'medium',
    order_index: 99,
    is_active: true,
  },
  {
    id: 'fc-ch12-100',
    chapter_id: 'ch-12',
    front: 'What is the general order of product application during a basic facial?',
    back: '1. Cleansing cream/lotion, 2. Exfoliant, 3. Massage cream, 4. Cleansing cream/lotion, 5. Freshener, 6. Mask/pack, 7. Toner/astringent, 8. Moisturizer.',
    category: 'Products',
    difficulty: 'medium',
    order_index: 100,
    is_active: true,
  },

  // === FACIAL TREATMENTS ===
  {
    id: 'fc-ch12-101',
    chapter_id: 'ch-12',
    front: "How should preservative and corrective facial-service terms be understood?",
    back: "The legacy source uses “preservative” for maintenance-oriented cosmetic care and “corrective” for services aimed at visible cosmetic concerns. Keep both within cosmetic scope; do not present a facial service as treatment for acne, disease, or another medical condition.",
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 101,
    is_active: true,
  },
  {
    id: 'fc-ch12-102',
    chapter_id: 'ch-12',
    front: 'What is a basic facial (scientific rest facial)?',
    back: 'The foundation for all facial treatments. Includes cleansing, exfoliating, massage manipulations, toning, a mask or pack, and moisturizing.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 102,
    is_active: true,
  },
  {
    id: 'fc-ch12-103',
    chapter_id: 'ch-12',
    front: 'What is a vibratory facial?',
    back: 'Performed using a combination of hand massage and an electric massager. Uses direct application (massager on skin) or indirect application (massager on barber\'s hand over client\'s skin).',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 103,
    is_active: true,
  },
  {
    id: 'fc-ch12-104',
    chapter_id: 'ch-12',
    front: 'What is the difference between direct and indirect vibratory application?',
    back: 'Direct: massager attached to dominant hand, vibrations travel through fingertips/palms to skin (for jaw, forehead). Indirect: nondominant hand on skin, massager on top of that hand (for delicate areas like nose and upper cheek).',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 104,
    is_active: true,
  },
  {
    id: 'fc-ch12-105',
    chapter_id: 'ch-12',
    front: "What is the cosmetic objective of a facial for dry skin?",
    back: "Select gentle cleansing, massage medium, mask, and moisturizer steps appropriate to the client’s observable dryness and product directions. Do not promise that electrical modalities will restore sebum production or treat a medical condition.",
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 105,
    is_active: true,
  },
  {
    id: 'fc-ch12-106',
    chapter_id: 'ch-12',
    front: 'What causes blackheads (comedones)?',
    back: 'Hardened masses of sebum formed inside a follicle. The sebaceous material darkens when exposed to oxygen.',
    category: 'Treatments',
    difficulty: 'easy',
    order_index: 106,
    is_active: true,
  },
  {
    id: 'fc-ch12-107',
    chapter_id: 'ch-12',
    front: "How should massage be handled when skin is acne-prone or inflamed?",
    back: "Use consultation and observation to decide whether massage is appropriate. Avoid vigorous manipulation on inflamed, open, or otherwise unsuitable skin, and defer when safety is uncertain rather than treating acne as an infectious condition.",
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 107,
    is_active: true,
  },
  {
    id: 'fc-ch12-108',
    chapter_id: 'ch-12',
    front: 'What are three guidelines for successful facial treatments?',
    back: 'Help the client relax, explain benefits during consultation, provide a quiet atmosphere, work efficiently, maintain clean conditions, analyze skin systematically, protect eyes, keep nails smooth and short, warm cold hands, test hot towels, avoid rough massage, avoid excess product, avoid excessive conversation.',
    category: 'Treatments',
    difficulty: 'medium',
    order_index: 108,
    is_active: true,
  },

  // === MODALITIES ===
  {
    id: 'fc-ch12-109',
    chapter_id: 'ch-12',
    front: "What service modalities does Chapter 12 group with facial treatment equipment and technique?",
    back: "The source discusses hand/electric massage, electrical currents, light-based equipment, heat/moist heat, and cosmetic products. Each modality must be used according to its own directions, training, contraindications, and barbering scope.",
    category: 'Modalities',
    difficulty: 'medium',
    order_index: 109,
    is_active: true,
  },
  {
    id: 'fc-ch12-110',
    chapter_id: 'ch-12',
    front: "How should heat and cold be used in a facial service?",
    back: "Use temperature only as a controlled cosmetic-service factor, following product/device guidance and client comfort. Do not promise a specific neurologic or therapeutic effect from heat or cold.",
    category: 'Modalities',
    difficulty: 'easy',
    order_index: 110,
    is_active: true,
  },

  // === MEN\'S PRODUCT PREFERENCES ===
  {
    id: 'fc-ch12-111',
    chapter_id: 'ch-12',
    front: "How should product preferences be discussed with male clients?",
    back: "Ask the individual client about fragrance, texture, finish, routine, and product preferences. The legacy material mentions simple routines and matte/non-fragranced products, but do not assume those preferences apply to every man.",
    category: 'Men\'s Products',
    difficulty: 'easy',
    order_index: 111,
    is_active: true,
  },
  {
    id: 'fc-ch12-112',
    chapter_id: 'ch-12',
    front: "How should packaging preferences be handled when recommending skin-care products?",
    back: "Ask the client what packaging and size work for their routine, hygiene needs, travel, and storage. Do not assume a universal preference based on gender.",
    category: 'Men\'s Products',
    difficulty: 'easy',
    order_index: 112,
    is_active: true,
  },

  // === ADDITIONAL SAFETY ===
  {
    id: 'fc-ch12-113',
    chapter_id: 'ch-12',
    front: 'Why should products be removed from containers with a spatula?',
    back: 'To prevent contamination. Do not dip fingers into containers.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 113,
    is_active: true,
  },
  {
    id: 'fc-ch12-114',
    chapter_id: 'ch-12',
    front: 'Why should latex-free gloves and supplies be available?',
    back: 'Some clients are sensitive to latex and may have a negative reaction.',
    category: 'Safety',
    difficulty: 'easy',
    order_index: 114,
    is_active: true,
  },

  // === HISTORICAL CONTEXT ===
  {
    id: 'fc-ch12-115',
    chapter_id: 'ch-12',
    front: 'What were standard facial services historically performed by barbers?',
    back: 'Hot towels and rolling cream facials were standard customer services.',
    category: 'History',
    difficulty: 'easy',
    order_index: 115,
    is_active: true,
  },
]

export default chapter12PremiumFlashcards
