import { QuizQuestion } from '@/types'

// Chapter 20: Working Behind the Chair — 17 premium quiz questions
export const chapter20PremiumQuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-20-01',
    standardId: 'CH20-Q01',
    quiz_id: 'quiz-20',
    question: "What is the biggest adjustment a new barber must make when transitioning from school to work?",
    answer_a: "Learning to work faster without regard for quality",
    answer_b: "Putting the needs of the barbershop and its clients ahead of personal convenience",
    answer_c: "Switching from practical training to purely theoretical study",
    answer_d: "Working without any supervision or feedback",
    correct_answer: 'b',
    explanation: "Common mistake: Thinking the main change is simply working faster or independently. Correct understanding: In school, mistakes are accepted and schedules can be flexible, but at work the barber must put the shop and clients first, arriving on time and prepared regardless of personal circumstances. Why it matters: Clients who are inconvenienced may not return, and coworkers asked to absorb your appointments may resent the added burden. Review: From Student to Professional.",
    difficulty: 'easy',
    learningObjective: 'LO-20-01',
    order_index: 1,
  },
  {
    id: 'qq-20-02',
    standardId: 'CH20-Q02',
    quiz_id: 'quiz-20',
    question: "A new barber is offered concert tickets for a day she is scheduled to work. According to ASCYN PRO guidance, what is the most professional response?",
    answer_a: "Take the day off; personal enjoyment is part of work-life balance.",
    answer_b: "Trade shifts with a coworker without telling management.",
    answer_c: "Honor the scheduled shift because clients and coworkers depend on her.",
    answer_d: "Call in sick to avoid a direct conflict.",
    correct_answer: 'c',
    explanation: "Common mistake: Believing that occasional personal events justify missing scheduled work. Correct understanding: Taking the day off would inconvenience clients who may decide not to return and burden coworkers who must cover the appointments. Why it matters: Reliability builds trust with clients, the team, and management and is a cornerstone of professional behavior. Review: From Student to Professional.",
    difficulty: 'medium',
    learningObjective: 'LO-20-01',
    order_index: 2,
  },
  {
    id: 'qq-20-03',
    standardId: 'CH20-Q03',
    quiz_id: 'quiz-20',
    question: "If a barbershop does not provide a written job description, what should a new employee do?",
    answer_a: "Assume duties are whatever the manager says each day.",
    answer_b: "Write one for herself and present it to the manager for review.",
    answer_c: "Wait several months and then formally request one.",
    answer_d: "Refuse to perform any task not listed in writing.",
    correct_answer: 'b',
    explanation: "Common mistake: Waiting passively or treating the absence of a job description as an excuse to avoid tasks. Correct understanding: A job description outlines duties, responsibilities, attitudes, and opportunities; if the shop does not use one, the new employee can draft it and review it with the manager to ensure mutual understanding. Why it matters: Clear expectations reduce conflict, protect both parties, and influence future opportunities and financial rewards. Review: From Student to Professional.",
    difficulty: 'medium',
    learningObjective: 'LO-20-01',
    order_index: 3,
  },
  {
    id: 'qq-20-04',
    standardId: 'CH20-Q04',
    quiz_id: 'quiz-20',
    question: "Which workplace principle best describes being willing to fold towels, make appointments, or help with tasks when not busy servicing clients?",
    answer_a: "Strive to help",
    answer_b: "Pitch in",
    answer_c: "Share your knowledge",
    answer_d: "Remain positive",
    correct_answer: 'b',
    explanation: "Common mistake: Confusing general helpfulness with the specific habit of doing whatever needs doing around the shop. Correct understanding: 'Pitch in' means being willing to help with whatever needs to be done, from folding towels to booking appointments, when you are not with a client. Why it matters: Team members who pitch in keep the shop running smoothly and demonstrate that the success of the business matters to them. Review: Habits of a Good Barbershop Team Player.",
    difficulty: 'easy',
    learningObjective: 'LO-20-02',
    order_index: 4,
  },
  {
    id: 'qq-20-05',
    standardId: 'CH20-Q05',
    quiz_id: 'quiz-20',
    question: "When conflict arises with a coworker, what does ASCYN PRO guidance identify as the behavior of a true teammate?",
    answer_a: "Discuss the conflict with others in the shop to gain support.",
    answer_b: "Ignore the conflict until it resolves itself.",
    answer_c: "Address the conflict directly with the individual and work toward resolution.",
    answer_d: "Ask the manager to mediate every disagreement immediately.",
    correct_answer: 'c',
    explanation: "Common mistake: Venting to others or avoiding conflict altogether. Correct understanding: A real teammate knows that conflict and tension harm everyone involved and the shop as a whole, so she discusses the issue with the individual and works constructively toward resolution. Why it matters: Handling conflict professionally preserves working relationships, morale, and the shop's reputation. Review: Habits of a Good Barbershop Team Player.",
    difficulty: 'medium',
    learningObjective: 'LO-20-02',
    order_index: 5,
  },
  {
    id: 'qq-20-06',
    standardId: 'CH20-Q06',
    quiz_id: 'quiz-20',
    question: "A new barber disagrees with an experienced coworker's preferred workflow. Which response best reflects professional teamwork?",
    answer_a: "Follow every instruction without question, even if it seems inappropriate or unsafe.",
    answer_b: "Respect the coworker's experience, ask clarifying questions, and raise legitimate concerns professionally.",
    answer_c: "Refuse unfamiliar tasks until the new barber has equal seniority.",
    answer_d: "Discuss the disagreement with other coworkers instead of addressing it directly.",
    correct_answer: 'b',
    explanation: "Professional teamwork requires humility and respect for experience without demanding blind obedience. A new barber should ask questions, learn assigned responsibilities, and communicate legitimate concerns directly and professionally. Appropriate boundaries still matter; unsafe or improper expectations should not be accepted merely because another person has more seniority. Review: Habits of a Good Barbershop Team Player.",
    difficulty: 'hard',
    learningObjective: 'LO-20-02',
    order_index: 6,
  },
  {
    id: 'qq-20-07',
    standardId: 'CH20-Q07',
    quiz_id: 'quiz-20',
    question: "When deciding whether a barber is an employee or an independent contractor, which approach is most accurate?",
    answer_a: "Use the title written on the shop's schedule as the deciding factor.",
    answer_b: "Evaluate the actual working relationship, including control, financial independence, and the relationship between the parties.",
    answer_c: "Treat anyone paid by commission as an independent contractor.",
    answer_d: "Treat anyone renting a chair as automatically exempt from employment rules.",
    correct_answer: 'b',
    explanation: "Worker classification is based on the real facts and circumstances, not a title, commission method, or chair-rental label alone. Relevant factors include behavioral control, financial control, and the nature of the relationship. Why it matters: Misclassification can create tax, wage, benefit, and recordkeeping consequences, so important questions should be verified using current official guidance or qualified professional advice. Review: Employment Classifications and Compensation.",
    difficulty: 'medium',
    learningObjective: 'LO-20-03',
    order_index: 7,
  },
  {
    id: 'qq-20-08',
    standardId: 'CH20-Q08',
    quiz_id: 'quiz-20',
    question: "A shop offers a compensation plan with a stated base amount plus an additional percentage tied to service revenue. Which description best matches that plan?",
    answer_a: "Straight hourly pay with no production component.",
    answer_b: "Straight commission with no base component.",
    answer_c: "A base-plus-commission arrangement whose exact calculation should be confirmed in the written compensation terms.",
    answer_d: "A booth-rental payment owed by the barber to the shop.",
    correct_answer: 'c',
    explanation: "A plan that combines a stated base amount with an additional percentage tied to service revenue is a base-plus-commission arrangement. The exact formula, thresholds, deductions, and eligibility terms can vary by employer, so the written compensation plan should control rather than a generic label. Review: Employment Classifications and Compensation.",
    difficulty: 'medium',
    learningObjective: 'LO-20-03',
    order_index: 8,
  },
  {
    id: 'qq-20-09',
    standardId: 'CH20-Q09',
    quiz_id: 'quiz-20',
    question: "Before accepting a booth-rental arrangement, what should a barber verify first?",
    answer_a: "That booth renters always set every shop-wide operating rule.",
    answer_b: "The actual agreement and applicable rules for scheduling, pricing, client records, fees, taxes, insurance, and other business responsibilities.",
    answer_c: "That the shop will issue the same payroll documents used for employees.",
    answer_d: "That booth rental automatically creates independent-contractor status in every jurisdiction.",
    correct_answer: 'b',
    explanation: "Booth rental can involve operating an independent business within a shop, but responsibilities depend on the actual agreement, facts, and applicable law. The barber should verify who controls scheduling, pricing, records, fees, supplies, insurance, taxes, and other terms rather than assuming the label answers those questions. Review: Employment Classifications and Compensation.",
    difficulty: 'hard',
    learningObjective: 'LO-20-03',
    order_index: 9,
  },
  {
    id: 'qq-20-10',
    standardId: 'CH20-Q10',
    quiz_id: 'quiz-20',
    question: "Which practice best supports accurate tax reporting for tips and other taxable barbering income?",
    answer_a: "Ignore cash amounts because only electronic payments create tax records.",
    answer_b: "Record only income shown on an employee paycheck.",
    answer_c: "Track income consistently and follow current reporting requirements for the barber's actual work arrangement.",
    answer_d: "Wait until year-end and estimate income from memory.",
    correct_answer: 'c',
    explanation: "Accurate reporting starts with consistent records of taxable income, including tips and other work income when applicable. Reporting duties can differ for employees and self-employed workers, so current IRS and applicable state or local requirements should be verified for the actual arrangement. Review: Manage Your Money.",
    difficulty: 'easy',
    learningObjective: 'LO-20-04',
    order_index: 10,
  },
  {
    id: 'qq-20-11',
    standardId: 'CH20-Q11',
    quiz_id: 'quiz-20',
    question: "What is the recommended method for tracking tips and additional income?",
    answer_a: "Estimate the amounts at the end of the year.",
    answer_b: "Keep a daily log, weekly totals, monthly summary, and yearly total.",
    answer_c: "Only record income shown on a paycheck.",
    answer_d: "Report only amounts over $100 per transaction.",
    correct_answer: 'b',
    explanation: "Common mistake: Relying on memory or only tracking paycheck income. Correct understanding: The best practice is to keep a daily log of tips and additional income, add weekly totals, maintain a monthly summary on a single page, and use the yearly total for tax reporting. Why it matters: A consistent system makes year-end reporting easy, accurate, and defensible if income is ever questioned. Review: Manage Your Money.",
    difficulty: 'medium',
    learningObjective: 'LO-20-04',
    order_index: 11,
  },
  {
    id: 'qq-20-12',
    standardId: 'CH20-Q12',
    quiz_id: 'quiz-20',
    question: "A barber is considering a service-price increase. Which approach best matches the hardened Chapter 20 guidance?",
    answer_a: "Raise prices on a fixed schedule regardless of costs, demand, or shop policy.",
    answer_b: "Copy the highest local competitor's price without reviewing the barber's own business conditions.",
    answer_c: "Evaluate skill level, costs, demand, client communication, market conditions, and shop policy before changing prices.",
    answer_d: "Avoid price changes permanently once a client base has been established.",
    correct_answer: 'c',
    explanation: "There is no universal calendar rule for raising prices. A professional decision considers the barber's skill and service quality, costs, demand, market conditions, client communication, and any shop policies or agreements that affect pricing. Review: Manage Your Money.",
    difficulty: 'hard',
    learningObjective: 'LO-20-04',
    order_index: 12,
  },
  {
    id: 'qq-20-13',
    standardId: 'CH20-Q13',
    quiz_id: 'quiz-20',
    question: "What is the best first step in successfully selling retail products or services to a client?",
    answer_a: "Memorize a single sales script and use it with every client.",
    answer_b: "Establish rapport and identify the client's specific needs.",
    answer_c: "Recommend the most expensive product to maximize commission.",
    answer_d: "Focus on making the sale before building trust.",
    correct_answer: 'b',
    explanation: "Common mistake: Treating selling as a one-size-fits-all pitch or pushy transaction. Correct understanding: The first step in selling is to sell yourself; clients must like and trust you before they buy. Successful selling begins with rapport, recognizing needs, and recommending only products or services that truly address those needs. Why it matters: Client-centered selling creates repeat business, protects the barber's reputation, and turns retailing into genuine service. Review: Ethical Selling Behind the Chair.",
    difficulty: 'medium',
    learningObjective: 'LO-20-05',
    order_index: 13,
  },
  {
    id: 'qq-20-14',
    standardId: 'CH20-Q14',
    quiz_id: 'quiz-20',
    question: "A client says they already own a similar product. Which response best reflects ethical selling?",
    answer_a: "Insist the recommended product is better and continue until the client agrees.",
    answer_b: "Acknowledge the client's concern, clarify the need, explain relevant benefits honestly, and respect the client's decision.",
    answer_c: "End the consultation immediately because any objection means the client will never buy.",
    answer_d: "Offer a large discount before determining whether the product actually fits the client's needs.",
    correct_answer: 'b',
    explanation: "Ethical objection handling begins by listening to the concern and identifying whether the recommendation genuinely meets a need. The barber can explain relevant benefits without pressure, exaggeration, or guarantees, and the client remains free to decline. Review: Ethical Selling Behind the Chair.",
    difficulty: 'hard',
    learningObjective: 'LO-20-05',
    order_index: 14,
  },
  {
    id: 'qq-20-15',
    standardId: 'CH20-Q15',
    quiz_id: 'quiz-20',
    question: "Which technique is most effective for rebooking clients and maintaining a loyal client base?",
    answer_a: "Waiting until clients call to schedule their next appointment.",
    answer_b: "Discussing their next visit while they are still in the chair.",
    answer_c: "Only contacting clients when business is slow.",
    answer_d: "Asking clients to refer friends before providing service.",
    correct_answer: 'b',
    explanation: "Common mistake: Treating rebooking as an afterthought or waiting for the client to take the initiative. Correct understanding: The best time to think about getting clients back into the shop is while they are still in the chair; talking about their hair condition, home care, and the benefits of regular maintenance naturally leads to booking the next appointment. Why it matters: Proactive rebooking keeps the chair full, builds loyalty, and prevents clients from drifting to competitors. Review: Keep Current Clients and Expand Your Client Base.",
    difficulty: 'medium',
    learningObjective: 'LO-20-06',
    order_index: 15,
  },
  {
    id: 'qq-20-16',
    standardId: 'CH20-Q16',
    quiz_id: 'quiz-20',
    question: "Which strategy helps a barber reach new clients by building mutually beneficial relationships with nearby businesses?",
    answer_a: "Posting daily price lists in the shop window",
    answer_b: "Creating local business referral partnerships",
    answer_c: "Requiring existing clients to bring a friend to every visit",
    answer_d: "Lowering all service prices below competitor rates",
    correct_answer: 'b',
    explanation: "Common mistake: Thinking client growth depends only on advertising or discounting. Correct understanding: Local business referral partnerships—such as swapping referrals with gyms, tailors, diners, or cigar shops—introduce your services to people who already trust another business in the community. Why it matters: Cross-promotion builds credibility, strengthens community ties, and creates a steady stream of referrals without heavy advertising costs. Review: Keep Current Clients and Expand Your Client Base.",
    difficulty: 'medium',
    learningObjective: 'LO-20-06',
    order_index: 16,
  },
  {
    id: 'qq-20-17',
    standardId: 'CH20-Q17',
    quiz_id: 'quiz-20',
    question: "When posting client photos on social media to market barbering services, what is the most important rule?",
    answer_a: "Use flattering lighting and professional filters.",
    answer_b: "Tag the client so their network sees the post.",
    answer_c: "Get the client's permission before posting.",
    answer_d: "Include as many trending hashtags as possible.",
    correct_answer: 'c',
    explanation: "Client privacy and consent come before marketing exposure. Obtain clear permission before posting identifiable client content, and follow applicable privacy, advertising, platform, school, and shop rules. Written permission may be appropriate when required by policy or law, but Chapter 20 does not treat one consent format as universal. Review: Keep Current Clients and Expand Your Client Base.",
    difficulty: 'easy',
    learningObjective: 'LO-20-06',
    order_index: 17,
  },
]
