// Chapter 3: Professional Image — CANONICAL INITIAL QUIZ (C3-1)
//
// Rebuilt around the locked curriculum: exactly 30 original ASCYN PRO
// questions mapped to the four concept families:
//   LO1 ch3-healthful-habits   = 8 questions
//   LO2 ch3-professional-image = 7 questions
//   LO3 ch3-ergonomics         = 8 questions
//   LO4 ch3-human-relations    = 7 questions
// Difficulty: 12 easy / 12 medium / 6 hard (hard = application/scenario).
//
// Question → concept mapping lives in chapter-3-concepts/mappings.ts.
// Question order and answer order are shuffled per attempt by QuizClient.
//
// Removed from the legacy bank (documented, IDs never reused):
//   qq-3-006/010/011 — LO2 coverage balance (concepts retained as flashcards)
//   qq-3-013 — tattoo policy → ASCYN enrichment (not core assessment)
//   qq-3-015 — "7 seconds" claim had no source support (C3-C001)
//   qq-3-017 — phone etiquette → ASCYN enrichment
//   qq-3-020 — universal photo-consent legal claim removed (C3-C003)
//   qq-3-023 — scope-of-practice → re-home recommendation (Ch9)
//   qq-3-024 — gratuity etiquette → ASCYN enrichment
//   qq-3-025/026/027 — station sanitation/dropped tools/sweeping → Ch4
//   qq-3-029 — CE-maintains-licensure claim removed (C3-C004)
//   qq-3-030 — client-base development → re-home recommendation (Ch17/20)
//
// Dead legacy utilities (generateChapter3Exam, randomizeQuestionAnswers,
// chapter3QuizStats) were removed — QuizClient owns runtime shuffling and
// nothing imported them (C3-C015).

import { QuizQuestion } from '@/types'

export const chapter3PremiumQuizQuestions: QuizQuestion[] = [
  // ── LO1 · HEALTHFUL HABITS (8) ──
  {
    id: 'qq-3-001',
    quiz_id: 'quiz-3',
    question: 'Why is daily bathing essential for a professional barber?',
    answer_a: 'It prevents body odor, removes bacteria, and ensures cleanliness',
    answer_b: 'It is only necessary when working with chemicals',
    answer_c: 'It helps style hair more effectively',
    answer_d: 'It is only necessary before shop inspections',
    correct_answer: 'a',
    explanation: 'Daily bathing prevents body odor, removes bacteria, and ensures personal cleanliness. Clients notice hygiene immediately.',
    difficulty: 'easy',
    learningObjective: 'LO-3-01',
    order_index: 1,
  },
  {
    id: 'qq-3-002',
    quiz_id: 'quiz-3',
    question: 'How often should a barber wash their hands during the workday?',
    answer_a: 'Only at the beginning and end of the shift',
    answer_b: 'Once every hour regardless of activity',
    answer_c: 'Throughout the day, including at the start of each service, after eating, and after restroom use',
    answer_d: 'Only when hands look dirty',
    correct_answer: 'c',
    explanation: 'Wash hands throughout the day, including at the beginning of each service, after eating, after using the restroom, and anytime hands become contaminated.',
    difficulty: 'easy',
    learningObjective: 'LO-3-01',
    order_index: 2,
  },
  {
    id: 'qq-3-004',
    quiz_id: 'quiz-3',
    question: 'What is the proper way to maintain oral hygiene as a barber?',
    answer_a: 'Chew gum throughout the day',
    answer_b: 'Rinse with water after meals only',
    answer_c: 'Brush and floss daily and use mouthwash',
    answer_d: 'Oral hygiene is not important for barbers',
    correct_answer: 'c',
    explanation: 'Brush and floss daily, use mouthwash, and keep breath mints available. You work in close proximity to clients.',
    difficulty: 'easy',
    learningObjective: 'LO-3-01',
    order_index: 4,
  },
  {
    id: 'qq-3-031',
    quiz_id: 'quiz-3',
    question: 'Which set lists the four important daily personal hygiene habits for a barber?',
    answer_a: 'Hand washing, self-checks and freshening, oral care, no smoking during work hours',
    answer_b: 'Daily haircut, clean shoes, pressed uniform, trimmed nails',
    answer_c: 'Mouthwash, cologne, gloves, hair spray',
    answer_d: 'Stretching, hand washing, posture checks, water intake',
    correct_answer: 'a',
    explanation: 'The four habits are: wash hands throughout the day (including at the start of each service), do self-checks and freshen up, brush and floss with mouthwash or mints, and do not smoke during work hours.',
    difficulty: 'easy',
    learningObjective: 'LO-3-01',
    order_index: 31,
  },
  {
    id: 'qq-3-032',
    quiz_id: 'quiz-3',
    question: 'Why do healthful-habits guidelines emphasize getting enough sleep?',
    answer_a: 'It gives you time to study product labels',
    answer_b: 'It lets the body recover from fatigue so you look, think, and work better',
    answer_c: 'It reduces the number of clients you need per day',
    answer_d: 'It replaces the need for regular exercise',
    correct_answer: 'b',
    explanation: 'Adequate sleep — an average of seven to eight hours — lets the body recover from fatigue. Rested barbers look healthier, think clearly, and perform better.',
    difficulty: 'easy',
    learningObjective: 'LO-3-01',
    order_index: 32,
  },
  {
    id: 'qq-3-033',
    quiz_id: 'quiz-3',
    question: 'Which daily pattern best supports a barber\'s nutrition and hydration during a long shift?',
    answer_a: 'Skipping meals to save time, then eating one large late dinner',
    answer_b: 'Energy drinks between clients instead of water',
    answer_c: 'Balanced meals with vitamins and minerals, plenty of water, and limiting sugar, salt, caffeine, and heavily processed foods',
    answer_d: 'Whatever is fastest from the vending machine',
    correct_answer: 'c',
    explanation: 'What you eat affects health, appearance, personality, and job performance. A balanced diet plus water fuels long days; excess sugar, salt, caffeine, and processed foods work against you.',
    difficulty: 'medium',
    learningObjective: 'LO-3-01',
    order_index: 33,
  },
  {
    id: 'qq-3-034',
    quiz_id: 'quiz-3',
    question: 'According to the healthful-habits model, how should a barber manage stress?',
    answer_a: 'Push through it — stress is part of the job and needs no management',
    answer_b: 'By working extra hours to stay ahead of it',
    answer_c: 'By avoiding all difficult clients permanently',
    answer_d: 'Through rest, relaxation, exercise, and daily routines that give the body and mind time to recover',
    correct_answer: 'd',
    explanation: 'Stress is the inability to cope with a real or imagined threat. Manage it with rest, relaxation, exercise, and recovery routines — a life of moderation and balance creates harmony.',
    difficulty: 'medium',
    learningObjective: 'LO-3-01',
    order_index: 34,
  },
  {
    id: 'qq-3-035',
    quiz_id: 'quiz-3',
    question: 'A new barber averages five hours of sleep, drinks energy drinks instead of water, skips meals, and never exercises. They feel burned out by midweek. Which change set best matches healthful-habits guidance?',
    answer_a: 'Add a second energy drink in the afternoon and power through',
    answer_b: 'Take one day off per month to catch up on everything at once',
    answer_c: 'Consistent sleep, water through the day, regular balanced meals, and regular physical activity',
    answer_d: 'Switch to decaf coffee and keep everything else the same',
    correct_answer: 'c',
    explanation: 'The healthful-habits foundation is sleep for recovery, hydration and balanced nutrition for performance, exercise for stamina, and relaxation for stress relief — not short-term stimulant fixes.',
    difficulty: 'hard',
    learningObjective: 'LO-3-01',
    order_index: 35,
  },

  // ── LO2 · PROFESSIONAL IMAGE & GROOMING (7) ──
  {
    id: 'qq-3-003',
    quiz_id: 'quiz-3',
    question: 'How should a barber maintain their nails for client services?',
    answer_a: 'Let them grow to any length as long as polish is fresh',
    answer_b: 'Keep them clean and well maintained, at a length that stays safe for client contact',
    answer_c: 'Nail care only matters for manicurists',
    answer_d: 'Cover them with gloves at all times',
    correct_answer: 'b',
    explanation: 'Keep nails clean and well maintained. Broken nails and chipped polish happen occasionally, but they should not be a regular occurrence in front of clients.',
    difficulty: 'medium',
    learningObjective: 'LO-3-02',
    order_index: 3,
  },
  {
    id: 'qq-3-005',
    quiz_id: 'quiz-3',
    question: 'Why should barbers avoid wearing strong fragrances at work?',
    answer_a: 'Fragrance is too expensive for daily use',
    answer_b: 'Clients cannot smell fragrance over hair products',
    answer_c: 'Clients prefer the smell of hair products only',
    answer_d: 'Strong fragrances can trigger allergies and overwhelm clients in close quarters',
    correct_answer: 'd',
    explanation: 'Perfume oils and strong scents can trigger allergies and overwhelm clients in close quarters. Many shops adopt no-fragrance policies.',
    difficulty: 'medium',
    learningObjective: 'LO-3-02',
    order_index: 5,
  },
  {
    id: 'qq-3-007',
    quiz_id: 'quiz-3',
    question: 'What type of footwear is most appropriate for barbers?',
    answer_a: 'Open-toed sandals for easy cleaning',
    answer_b: 'High heels for professional appearance',
    answer_c: 'Supportive, polished, closed-toe shoes in good repair',
    answer_d: 'Any comfortable shoe, even worn-out flip-flops',
    correct_answer: 'c',
    explanation: 'Supportive, polished, closed-toe shoes protect your feet around electrical tools and sharp implements and keep you comfortable through long hours of standing.',
    difficulty: 'easy',
    learningObjective: 'LO-3-02',
    order_index: 7,
  },
  {
    id: 'qq-3-008',
    quiz_id: 'quiz-3',
    question: 'Why is it important for barbers to wear a clean uniform or apron?',
    answer_a: 'It keeps hair clippings off the floor',
    answer_b: 'It protects clothing and presents a professional image',
    answer_c: 'Uniforms are provided free by all shops',
    answer_d: 'Clients cannot see stains anyway',
    correct_answer: 'b',
    explanation: 'A clean, pressed uniform protects your clothing and presents a professional image — keep it stain-free, not just dirt-free.',
    difficulty: 'easy',
    learningObjective: 'LO-3-02',
    order_index: 8,
  },
  {
    id: 'qq-3-009',
    quiz_id: 'quiz-3',
    question: 'What jewelry is considered appropriate for barbers to wear while working?',
    answer_a: 'Large dangling earrings and multiple bracelets',
    answer_b: 'Rings on every finger for style',
    answer_c: 'Minimal accessories — nothing noisy, dangling into a client\'s face, or able to catch in equipment',
    answer_d: 'Any jewelry the barber personally prefers',
    correct_answer: 'c',
    explanation: 'Accessorize carefully: nothing that makes noise, dangles into a client\'s face, or can catch in equipment. A waterproof wristwatch is a practical choice.',
    difficulty: 'medium',
    learningObjective: 'LO-3-02',
    order_index: 9,
  },
  {
    id: 'qq-3-012',
    quiz_id: 'quiz-3',
    question: 'Why is it important for barbers to maintain well-groomed facial hair?',
    answer_a: 'Clients are not permitted to have beards',
    answer_b: 'Facial hair protects against chemicals',
    answer_c: 'Clients prefer barbers with beards',
    answer_d: 'It demonstrates your grooming skills to clients',
    correct_answer: 'd',
    explanation: 'A neat, trimmed beard or mustache testifies to your barbering skill. If you prefer clean-shaven, shave daily to avoid undue stubble.',
    difficulty: 'easy',
    learningObjective: 'LO-3-02',
    order_index: 12,
  },
  {
    id: 'qq-3-036',
    quiz_id: 'quiz-3',
    question: 'It is your first day at an upscale shop with a written dress code and a no-fragrance policy. Which choice best fits dressing for success?',
    answer_a: 'Your boldest cologne and trendiest outfit — first impressions need personality',
    answer_b: 'Gym shoes and headphones so you can zone in',
    answer_c: 'Clean, pressed attire within the dress code, supportive polished shoes, minimal quiet accessories, and no fragrance',
    answer_d: 'A borrowed smock with a faint bleach stain — nobody looks closely',
    correct_answer: 'c',
    explanation: 'Dressing for success means a professional image consistent with the shop: clean and pressed, functional and comfortable, careful accessories, supportive polished shoes, and respect for fragrance policy.',
    difficulty: 'hard',
    learningObjective: 'LO-3-02',
    order_index: 36,
  },

  // ── LO3 · ERGONOMICS & BODY MECHANICS (8) ──
  {
    id: 'qq-3-014',
    quiz_id: 'quiz-3',
    question: 'Why is good posture important when working as a barber?',
    answer_a: 'It makes haircuts finish faster',
    answer_b: 'It conveys confidence and prevents fatigue and chronic pain',
    answer_c: 'Clients can see your posture in the mirror',
    answer_d: 'Good posture improves your grip strength',
    correct_answer: 'b',
    explanation: 'Good posture conveys an image of confidence and prevents fatigue and the chronic neck, shoulder, back, and leg problems that come from working improperly.',
    difficulty: 'easy',
    learningObjective: 'LO-3-03',
    order_index: 14,
  },
  {
    id: 'qq-3-028',
    quiz_id: 'quiz-3',
    question: 'What is the purpose of an anti-fatigue mat at a barber station?',
    answer_a: 'To decorate the station with color',
    answer_b: 'To prevent tools from rolling away',
    answer_c: 'To catch hair clippings for easy cleanup',
    answer_d: 'To reduce leg and back strain from standing',
    correct_answer: 'd',
    explanation: 'Anti-fatigue mats provide cushioned flooring that reduces leg and back strain from standing for long periods.',
    difficulty: 'easy',
    learningObjective: 'LO-3-03',
    order_index: 28,
  },
  {
    id: 'qq-3-037',
    quiz_id: 'quiz-3',
    question: 'What is ergonomics?',
    answer_a: 'The study of muscle growth for physical labor',
    answer_b: 'The science of designing the workplace and its equipment and tools to make body movements more comfortable, efficient, and safe',
    answer_c: 'A stretching routine performed before each client',
    answer_d: 'The practice of standing as still as possible while working',
    correct_answer: 'b',
    explanation: 'Ergonomics is the science of designing the workplace — along with its equipment and tools — to make specific body movements more comfortable, efficient, and safe.',
    difficulty: 'medium',
    learningObjective: 'LO-3-03',
    order_index: 37,
  },
  {
    id: 'qq-3-038',
    quiz_id: 'quiz-3',
    question: 'Which description matches correct standing posture for a barber?',
    answer_a: 'Head up with chin parallel to the floor, neck elongated, chest lifted, shoulders level and relaxed, spine straight',
    answer_b: 'Weight on one hip, shoulders rounded forward, chin tucked down',
    answer_c: 'Knees locked, back arched, arms raised high',
    answer_d: 'Leaning slightly on the station to take weight off the feet',
    correct_answer: 'a',
    explanation: 'Standing posture: head up with chin parallel to the floor, neck elongated and balanced above the shoulders, chest lifted without slouching, shoulders level and relaxed, spine straight.',
    difficulty: 'medium',
    learningObjective: 'LO-3-03',
    order_index: 38,
  },
  {
    id: 'qq-3-039',
    quiz_id: 'quiz-3',
    question: 'How should a barber position their arms and wrists while cutting?',
    answer_a: 'Arms straight overhead for maximum reach, wrists bent back',
    answer_b: 'Whatever feels natural — positioning does not matter',
    answer_c: 'Elbows locked tight against the ribs, fists clenched on the shears',
    answer_d: 'Arms at less than about a 60-degree angle from the body, wrists kept straight and neutral, without gripping tools tightly',
    correct_answer: 'd',
    explanation: 'Position arms at less than about a 60-degree angle when holding them away from the body, keep wrists straight or neutral, and avoid gripping tools tightly or constantly bending the wrist up or down.',
    difficulty: 'medium',
    learningObjective: 'LO-3-03',
    order_index: 39,
  },
  {
    id: 'qq-3-040',
    quiz_id: 'quiz-3',
    question: 'Which list names posture problems barbers are taught to recognize?',
    answer_a: 'Hunchback, swayback, and combined hunchback-swayback',
    answer_b: 'Runner\'s knee, tennis elbow, and swimmer\'s shoulder',
    answer_c: 'Flat feet, bow legs, and pigeon toes',
    answer_d: 'Whiplash, sprain, and strain',
    correct_answer: 'a',
    explanation: 'Common posture problems include hunchback (rounded upper back), swayback (exaggerated lower-back curve), and combined hunchback-swayback. Recognize them early and correct through awareness and exercise.',
    difficulty: 'easy',
    learningObjective: 'LO-3-03',
    order_index: 40,
  },
  {
    id: 'qq-3-041',
    quiz_id: 'quiz-3',
    question: 'After months of cutting, a barber develops wrist pain and numbness in the hand. What is the most likely issue, and which prevention set applies?',
    answer_a: 'A skin allergy; switch soaps and keep cutting as usual',
    answer_b: 'Normal aging; nothing can be done',
    answer_c: 'Carpal tunnel syndrome; neutral wrists, ergonomic tools, stretching at intervals, and avoiding tight grips',
    answer_d: 'A shoulder problem; only shoulder exercises will help',
    correct_answer: 'c',
    explanation: 'Wrist pain and numbness after repetitive hand movements points to carpal tunnel syndrome. Prevention: neutral wrist positions, ergonomically designed tools, no tight gripping, and regular stretch intervals.',
    difficulty: 'hard',
    learningObjective: 'LO-3-03',
    order_index: 41,
  },
  {
    id: 'qq-3-042',
    quiz_id: 'quiz-3',
    question: 'A barber ends every day with lower-back and shoulder fatigue and catches themselves bending forward and twisting to reach the client. Which setup change addresses the cause?',
    answer_a: 'Raise the client chair so the client\'s head is at a comfortable working level, stand hip-width with knees slightly bent, and stretch or walk between clients',
    answer_b: 'Lower the chair so you lean over less far, and lock your knees for stability',
    answer_c: 'Move faster through each cut so there is less time to feel tired',
    answer_d: 'Sit on the station ledge between clients without changing anything else',
    correct_answer: 'a',
    explanation: 'Bending and twisting to reach the client drives back and shoulder fatigue. Bring the client to you — chair at a comfortable working level, head tilted for access — keep a balanced stance, and counter repetitive positions with stretch and walk intervals.',
    difficulty: 'hard',
    learningObjective: 'LO-3-03',
    order_index: 42,
  },

  // ── LO4 · HUMAN RELATIONS & COMMUNICATION (7) ──
  {
    id: 'qq-3-016',
    quiz_id: 'quiz-3',
    question: 'What does "talking less, listening more" mean in practice?',
    answer_a: 'Letting the client talk while you plan the next appointment',
    answer_b: 'Staying fully attentive to what the client says and asking questions whenever something is unclear',
    answer_c: 'Hearing the client out, then doing what you had already decided',
    answer_d: 'Avoiding all conversation during the service',
    correct_answer: 'b',
    explanation: 'Practice good listening skills: stay fully attentive, and if something is unclear, ask questions to gain understanding.',
    difficulty: 'medium',
    learningObjective: 'LO-3-04',
    order_index: 16,
  },
  {
    id: 'qq-3-018',
    quiz_id: 'quiz-3',
    question: 'What should a barber do if they are running late for an appointment?',
    answer_a: 'Hope the client does not notice',
    answer_b: 'Cancel the appointment without explanation',
    answer_c: 'Rush through the current service to save time',
    answer_d: 'Call the client as soon as possible to inform them',
    correct_answer: 'd',
    explanation: 'Call the client as soon as possible, apologize sincerely, offer a revised time, and thank them for their patience.',
    difficulty: 'medium',
    learningObjective: 'LO-3-04',
    order_index: 18,
  },
  {
    id: 'qq-3-019',
    quiz_id: 'quiz-3',
    question: 'How should a barber handle a client who is unhappy with their haircut?',
    answer_a: 'Defend your work and explain why they are wrong',
    answer_b: 'Offer a discount but do not change the cut',
    answer_c: 'Tell them to go to another barber',
    answer_d: 'Stay calm, listen, apologize sincerely, and offer to fix it promptly',
    correct_answer: 'd',
    explanation: 'Stay calm, listen without defending, apologize sincerely, and take care of the problem promptly and to the client\'s satisfaction.',
    difficulty: 'medium',
    learningObjective: 'LO-3-04',
    order_index: 19,
  },
  {
    id: 'qq-3-021',
    quiz_id: 'quiz-3',
    question: 'Why should barbers avoid gossiping about clients or coworkers?',
    answer_a: 'Gossip is boring to most people',
    answer_b: 'It damages trust, creates a toxic work environment, and violates confidentiality',
    answer_c: 'Gossip takes too much time during work hours',
    answer_d: 'Clients enjoy hearing gossip about others',
    correct_answer: 'b',
    explanation: 'Gossip damages trust and violates the ethical standard of confidentiality. Professional barbers never discuss other clients or coworkers.',
    difficulty: 'medium',
    learningObjective: 'LO-3-04',
    order_index: 21,
  },
  {
    id: 'qq-3-022',
    quiz_id: 'quiz-3',
    question: 'What is client confidentiality and why does it matter?',
    answer_a: 'Keeping personal information and conversations private',
    answer_b: 'Keeping the client\'s appointment time private',
    answer_c: 'Only sharing client information with coworkers',
    answer_d: 'Confidentiality is not important in barbering',
    correct_answer: 'a',
    explanation: 'Client confidentiality means keeping personal information, conversations, and details private. Violating that trust is hard to repair.',
    difficulty: 'easy',
    learningObjective: 'LO-3-04',
    order_index: 22,
  },
  {
    id: 'qq-3-043',
    quiz_id: 'quiz-3',
    question: 'A client sits down and says, "Just trim it over the ears." What is the most professional next step?',
    answer_a: 'Clarify what "over the ears" means to them, then repeat your interpretation back before cutting',
    answer_b: 'Start cutting — "trim" is clear enough',
    answer_c: 'Show them a photo of your favorite cut and talk them into it',
    answer_d: 'Ask a coworker what they think the client means',
    correct_answer: 'a',
    explanation: 'Apply the three-step framework: organize your thoughts about what you need to know, clarify the client\'s terminology ("over the ears" can mean more than one thing), and repeat your interpretation so the client can confirm or correct it.',
    difficulty: 'hard',
    learningObjective: 'LO-3-04',
    order_index: 43,
  },
  {
    id: 'qq-3-044',
    quiz_id: 'quiz-3',
    question: 'Mid-service, a client loudly criticizes your work in front of other clients. Which response shows emotional control?',
    answer_a: 'Stay even-tempered, listen, and address the concern professionally without showing anger',
    answer_b: 'Point out everything wrong with their hair in return',
    answer_c: 'Stop the service and ask them to leave immediately',
    answer_d: 'Finish in silence and complain about them to coworkers afterward',
    correct_answer: 'a',
    explanation: 'Emotional control means responding rather than reacting — not revealing negative emotions through gestures, facial expressions, or conversation. Even-tempered professionals earn respect.',
    difficulty: 'hard',
    learningObjective: 'LO-3-04',
    order_index: 44,
  },
]

export default chapter3PremiumQuizQuestions
