import { Flashcard } from '@/types'

// Chapter 16: Women's Haircutting & Styling
// 68 premium flashcards — 43 Board Essential + 25 Professional Essential
// Source: ascyn-pro-audit/CHAPTER_16_FLASHCARDS_PHASE_3A_DRAFT.md
//         ascyn-pro-audit/CHAPTER_16_FLASHCARDS_PHASE_3B_DRAFT.md
//         ascyn-pro-audit/CHAPTER_16_FLASHCARDS_PHASE_3C_DRAFT.md
//         ascyn-pro-audit/CHAPTER_16_FLASHCARDS_PHASE_3D_DRAFT.md

export const chapter16PremiumFlashcards: Flashcard[] = [
  // === BOARD ESSENTIAL — Phase 3A (cards 1–20) ===
  {
    id: 'fc-ch16-001',
    chapter_id: 'ch-16',
    front: 'What is **shape** in haircut design?',
    back: 'Shape is the overall silhouette or outline of the haircut.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'fc-ch16-002',
    chapter_id: 'ch-16',
    front: 'What is **weight** in haircut design?',
    back: 'Weight is where hair mass is concentrated in a haircut.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'fc-ch16-003',
    chapter_id: 'ch-16',
    front: 'What is **elevation** in haircut design?',
    back: 'Elevation is the angle at which hair is held away from the head before cutting.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'fc-ch16-004',
    chapter_id: 'ch-16',
    front: 'What is **movement** in haircut design?',
    back: 'Movement is how the hair flows, falls, and responds to styling after cutting.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'fc-ch16-005',
    chapter_id: 'ch-16',
    front: 'What is **texture** in haircut design, and how does it influence technique selection?',
    back: 'Texture is the surface quality of each strand and the overall head of hair. It determines how hair responds to tension, layering, and texturizing.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'fc-ch16-006',
    chapter_id: 'ch-16',
    front: 'What elevation and weight placement define a **blunt cut**?',
    back: 'A blunt cut uses little to no elevation, keeping maximum weight concentrated along the perimeter in a strong, solid line.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'fc-ch16-007',
    chapter_id: 'ch-16',
    front: 'What elevation and weight effect define a **graduated cut**?',
    back: 'A graduated cut uses moderate elevation to build weight along a design line, creating a stacked or wedge-shaped silhouette.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 7,
    is_active: true,
  },
  {
    id: 'fc-ch16-008',
    chapter_id: 'ch-16',
    front: 'What elevation and weight distribution define a **uniform-layered cut**?',
    back: 'A uniform-layered cut uses 90-degree elevation to create equal-length layers and distribute weight evenly throughout the head.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 8,
    is_active: true,
  },
  {
    id: 'fc-ch16-009',
    chapter_id: 'ch-16',
    front: 'What elevation and perimeter effect define a **long-layered cut**?',
    back: 'A long-layered cut uses high elevation, commonly 180 degrees, to preserve perimeter length while creating shorter interior layers.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 9,
    is_active: true,
  },
  {
    id: 'fc-ch16-010',
    chapter_id: 'ch-16',
    front: 'What are the **perimeter** and **weight line** of a haircut?',
    back: 'The perimeter is the outside edge or outline of the haircut. The weight line is the visual area where the hair ends collect and create heaviness.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 10,
    is_active: true,
  },
  {
    id: 'fc-ch16-011',
    chapter_id: 'ch-16',
    front: 'What is **natural fall**, and why does it matter in a blunt cut?',
    back: 'Natural fall is how hair hangs when it is not lifted or forced into position. In a blunt cut, cutting against natural fall changes the finished line.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 11,
    is_active: true,
  },
  {
    id: 'fc-ch16-012',
    chapter_id: 'ch-16',
    front: 'What is **zero elevation**, and what effect does it have on weight?',
    back: 'Zero elevation means hair is not lifted away from the head before cutting. It keeps the maximum weight at the perimeter.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 12,
    is_active: true,
  },
  {
    id: 'fc-ch16-013',
    chapter_id: 'ch-16',
    front: 'What is a **guide** in haircutting?',
    back: 'A guide is a section of hair used as a reference to control the length and angle of following sections.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 13,
    is_active: true,
  },
  {
    id: 'fc-ch16-014',
    chapter_id: 'ch-16',
    front: 'Why is **head position** critical when cutting a blunt line?',
    back: 'A tilted head moves the cutting line. Keeping the head upright and consistent keeps the perimeter balanced.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 14,
    is_active: true,
  },
  {
    id: 'fc-ch16-015',
    chapter_id: 'ch-16',
    front: 'Why is **cross-checking** required after a blunt cut?',
    back: 'Cross-checking reveals dips, corners, or uneven weight that are not visible when following the original cutting line.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 15,
    is_active: true,
  },
  {
    id: 'fc-ch16-016',
    chapter_id: 'ch-16',
    front: 'What is **graduation**, and how does it build weight?',
    back: 'Graduation cuts hair at an angle, leaving shorter layers underneath and longer layers above, which stacks weight along a design line.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 16,
    is_active: true,
  },
  {
    id: 'fc-ch16-017',
    chapter_id: 'ch-16',
    front: 'What is a **traveling guide**?',
    back: 'A traveling guide is a guide that moves with each new section as the haircut progresses, carrying the established length and angle forward.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 17,
    is_active: true,
  },
  {
    id: 'fc-ch16-018',
    chapter_id: 'ch-16',
    front: 'What is a **stationary guide**?',
    back: 'A stationary guide stays in one fixed position while other sections are cut to match it.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 18,
    is_active: true,
  },
  {
    id: 'fc-ch16-019',
    chapter_id: 'ch-16',
    front: 'Why must **hair analysis** be performed before cutting?',
    back: 'Hair analysis reveals texture, density, growth patterns, and curl pattern. These factors determine which technique will produce a safe, predictable result.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 19,
    is_active: true,
  },
  {
    id: 'fc-ch16-020',
    chapter_id: 'ch-16',
    front: 'Why does **curly hair shrink** after drying?',
    back: 'Curly hair springs up as it dries because the curl pattern contracts, making dry length shorter than wet length.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 20,
    is_active: true,
  },

  // === BOARD ESSENTIAL — Phase 3B (cards 21–43) ===
  {
    id: 'fc-ch16-021',
    chapter_id: 'ch-16',
    front: 'How does **cutting-line direction** affect the finished shape of a blunt cut?',
    back: 'A horizontal cutting line creates a strong, even baseline. A diagonal line changes the shape around the face or perimeter.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 21,
    is_active: true,
  },
  {
    id: 'fc-ch16-022',
    chapter_id: 'ch-16',
    front: 'How does **finger angle** affect the finished graduated shape?',
    back: 'The angle of the fingers and shears directly changes where weight is built and how the silhouette flows.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 22,
    is_active: true,
  },
  {
    id: 'fc-ch16-023',
    chapter_id: 'ch-16',
    front: 'What is the **silhouette** of a haircut?',
    back: 'The silhouette is the overall outline or shape of the haircut as seen from the side or back.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 23,
    is_active: true,
  },
  {
    id: 'fc-ch16-024',
    chapter_id: 'ch-16',
    front: 'What is a **uniform layer**?',
    back: 'A uniform layer is a haircut in which all layers are cut to the same length when projected at a consistent elevation.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 24,
    is_active: true,
  },
  {
    id: 'fc-ch16-025',
    chapter_id: 'ch-16',
    front: 'What is **90-degree elevation**?',
    back: '90-degree elevation means hair is held straight out from the head, perpendicular to the scalp.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 25,
    is_active: true,
  },
  {
    id: 'fc-ch16-026',
    chapter_id: 'ch-16',
    front: 'How do **uniform layers** distribute weight, and why is consistent elevation critical?',
    back: 'Uniform layers spread weight evenly throughout the head instead of concentrating it at the perimeter or nape. Consistent elevation is required because changing the angle changes layer length, breaking the even, balanced result that defines a uniform layer.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 26,
    is_active: true,
  },
  {
    id: 'fc-ch16-027',
    chapter_id: 'ch-16',
    front: 'What are **long layers**?',
    back: 'Long layers are layers that preserve perimeter length while introducing shorter interior layers for movement and reduced weight.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 27,
    is_active: true,
  },
  {
    id: 'fc-ch16-028',
    chapter_id: 'ch-16',
    front: 'What is **180-degree elevation**?',
    back: '180-degree elevation means hair is lifted straight up, overhead and parallel to the floor, before cutting.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 28,
    is_active: true,
  },
  {
    id: 'fc-ch16-029',
    chapter_id: 'ch-16',
    front: 'What is **perimeter preservation** in a long-layered cut?',
    back: 'Perimeter preservation means keeping the outside edge of the haircut long while removing weight from the interior.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 29,
    is_active: true,
  },
  {
    id: 'fc-ch16-030',
    chapter_id: 'ch-16',
    front: 'How do **interior layers** reduce weight in a long-layered cut?',
    back: 'Interior layers are shorter layers cut inside the haircut. They remove bulk from within while the perimeter stays long.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 30,
    is_active: true,
  },
  {
    id: 'fc-ch16-031',
    chapter_id: 'ch-16',
    front: 'What is **texture** in hair analysis?',
    back: 'Texture is the strand diameter of the hair: fine, medium, or coarse.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 31,
    is_active: true,
  },
  {
    id: 'fc-ch16-032',
    chapter_id: 'ch-16',
    front: 'What is **density** in hair analysis?',
    back: 'Density is the total amount of hair on the head: thin, medium, or thick.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 32,
    is_active: true,
  },
  {
    id: 'fc-ch16-033',
    chapter_id: 'ch-16',
    front: 'What is a **growth pattern**?',
    back: 'A growth pattern is the direction in which hair naturally grows from the scalp.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 33,
    is_active: true,
  },
  {
    id: 'fc-ch16-034',
    chapter_id: 'ch-16',
    front: 'What is a **cowlick**?',
    back: 'A cowlick is an area where hair growth changes direction abruptly, creating a swirl or resistant section.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 34,
    is_active: true,
  },
  {
    id: 'fc-ch16-035',
    chapter_id: 'ch-16',
    front: 'What is **overdirection**, and what effect does it have?',
    back: 'Overdirection means combing hair away from its natural falling position before cutting. It preserves length where the hair is pulled from and shifts weight toward where it is pulled to.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 35,
    is_active: true,
  },
  {
    id: 'fc-ch16-036',
    chapter_id: 'ch-16',
    front: 'What is **razor cutting**, and on which hair types is it inappropriate?',
    back: 'Razor cutting uses a razor to soften ends and create movement. It is not appropriate for fine, fragile, or highly porous hair because it can fray or weaken the strands.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 36,
    is_active: true,
  },
  {
    id: 'fc-ch16-037',
    chapter_id: 'ch-16',
    front: 'What is **point cutting**?',
    back: 'Point cutting uses the tips of the shears to soften blunt lines and remove small amounts of bulk from the ends.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 37,
    is_active: true,
  },
  {
    id: 'fc-ch16-038',
    chapter_id: 'ch-16',
    front: 'What is **notching**?',
    back: 'Notching removes weight in a spaced, aggressive pattern from thick, heavy hair, usually at the perimeter or interior.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 38,
    is_active: true,
  },
  {
    id: 'fc-ch16-039',
    chapter_id: 'ch-16',
    front: 'What is **slithering**?',
    back: 'Slithering slides partially open shears along a section to remove a small amount of bulk while preserving length.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 39,
    is_active: true,
  },
  {
    id: 'fc-ch16-040',
    chapter_id: 'ch-16',
    front: 'Why must **heat protectant** be applied before thermal styling?',
    back: 'Heat protectant forms a barrier that reduces heat damage to the cuticle and helps prevent dryness, breakage, and scorching.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 40,
    is_active: true,
  },
  {
    id: 'fc-ch16-041',
    chapter_id: 'ch-16',
    front: 'Why should thermal tools never be applied to damp hair unless designed for it?',
    back: 'Applying heat to damp hair causes rapid steam expansion inside the strand, which can damage the cuticle and weaken the hair.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 41,
    is_active: true,
  },
  {
    id: 'fc-ch16-042',
    chapter_id: 'ch-16',
    front: 'How does hair condition affect thermal tool temperature selection, and how do you protect the client?',
    back: 'Fine or damaged hair needs lower heat; healthy, coarse hair can tolerate more. Always keep tools moving, protect skin and ears from hot surfaces, and place tools on a heat-safe mat when not in use.',
    category: 'Board Essential',
    difficulty: 'medium',
    order_index: 42,
    is_active: true,
  },
  {
    id: 'fc-ch16-043',
    chapter_id: 'ch-16',
    front: 'What sanitation and cleanup steps must be completed after every haircut and styling service?',
    back: 'Remove the cape and neck strip, clean the client, disinfect all tools, and restore the workstation to professional standards.',
    category: 'Board Essential',
    difficulty: 'easy',
    order_index: 43,
    is_active: true,
  },

  // === PROFESSIONAL ESSENTIAL — Phase 3C (cards 44–55) ===
  {
    id: 'fc-ch16-044',
    chapter_id: 'ch-16',
    front: 'Why must a thorough consultation happen before every women\'s haircutting service?',
    back: 'A thorough consultation confirms the client\'s goals, hair history, lifestyle, and realistic expectations before any cutting begins.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 44,
    is_active: true,
  },
  {
    id: 'fc-ch16-045',
    chapter_id: 'ch-16',
    front: 'How do **precision, balance, and wearability** work together to satisfy a client?',
    back: 'Precision creates clean lines, balance keeps the shape even, and wearability ensures the style looks good and behaves well at home.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 45,
    is_active: true,
  },
  {
    id: 'fc-ch16-046',
    chapter_id: 'ch-16',
    front: 'When is a **blunt cut** the best choice for a client?',
    back: 'A blunt cut is best when the client wants a strong, heavy perimeter, a one-length shape, or a classic bob with fullness at the bottom.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 46,
    is_active: true,
  },
  {
    id: 'fc-ch16-047',
    chapter_id: 'ch-16',
    front: 'When is a **graduated cut** the best design choice?',
    back: 'A graduated cut is best when the client wants stacked fullness, a shaped silhouette, or controlled volume in a specific area such as the nape.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 47,
    is_active: true,
  },
  {
    id: 'fc-ch16-048',
    chapter_id: 'ch-16',
    front: 'When is a **uniform-layered cut** the best choice for a client?',
    back: 'A uniform-layered cut is best when the client wants lighter weight, soft movement, and styling versatility without a heavy bottom line.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 48,
    is_active: true,
  },
  {
    id: 'fc-ch16-049',
    chapter_id: 'ch-16',
    front: 'When is a **long-layered cut** the right choice?',
    back: 'A long-layered cut is right when the client wants to keep overall length while reducing interior weight and adding movement.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 49,
    is_active: true,
  },
  {
    id: 'fc-ch16-050',
    chapter_id: 'ch-16',
    front: 'How should a barber adjust sectioning and technique based on hair **texture** and **density**?',
    back: 'Fine or thin hair needs smaller sections and conservative layering to preserve fullness. Coarse or thick hair needs controlled sectioning and may require weight release.',
    category: 'Professional Essential',
    difficulty: 'hard',
    order_index: 50,
    is_active: true,
  },
  {
    id: 'fc-ch16-051',
    chapter_id: 'ch-16',
    front: 'How should a barber respond when a curly-haired client brings a straight-hair inspiration photo?',
    back: 'The barber should analyze the curl pattern and texture, explain how shrinkage will affect the result, and adapt the design rather than copying the photo exactly.',
    category: 'Professional Essential',
    difficulty: 'hard',
    order_index: 51,
    is_active: true,
  },
  {
    id: 'fc-ch16-052',
    chapter_id: 'ch-16',
    front: 'When should **point cutting** be used?',
    back: 'Point cutting is used to soften blunt lines and remove small amounts of bulk from the ends without dramatically shortening length.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 52,
    is_active: true,
  },
  {
    id: 'fc-ch16-053',
    chapter_id: 'ch-16',
    front: 'When should **notching** be used?',
    back: 'Notching is used on thick, heavy hair that needs significant weight release at the perimeter or interior.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 53,
    is_active: true,
  },
  {
    id: 'fc-ch16-054',
    chapter_id: 'ch-16',
    front: 'When should **slithering** be used?',
    back: 'Slithering is used on dense hair that needs subtle weight reduction while preserving overall length.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 54,
    is_active: true,
  },
  {
    id: 'fc-ch16-055',
    chapter_id: 'ch-16',
    front: 'What should be included in **client education** at the end of a styling service?',
    back: 'Client education should include how to recreate the style at home, which products to use, how to protect the hair from heat, and when to return for maintenance.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 55,
    is_active: true,
  },

  // === PROFESSIONAL ESSENTIAL — Phase 3D (cards 56–68) ===
  {
    id: 'fc-ch16-056',
    chapter_id: 'ch-16',
    front: 'Why is haircutting considered a **design process** rather than simply removing hair?',
    back: 'Haircutting is a design process because it requires planning shape, weight, elevation, movement, texture, and finishing to meet the client\'s goal.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 56,
    is_active: true,
  },
  {
    id: 'fc-ch16-057',
    chapter_id: 'ch-16',
    front: 'What are common blunt-cut mistakes related to tension and section size?',
    back: 'Common mistakes include using uneven tension, taking sections that are too thick, lifting the hair too much, and losing the guide.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 57,
    is_active: true,
  },
  {
    id: 'fc-ch16-058',
    chapter_id: 'ch-16',
    front: 'What are common graduated-cut mistakes?',
    back: 'Common mistakes include confusing graduation with layering, losing the traveling guide, changing finger angle, using sections that are too large, and allowing uneven elevation.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 58,
    is_active: true,
  },
  {
    id: 'fc-ch16-059',
    chapter_id: 'ch-16',
    front: 'Why should subsections remain narrow and controlled in a graduated cut?',
    back: 'Narrow subsections let the barber see the angle and maintain even elevation, which prevents uneven weight buildup.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 59,
    is_active: true,
  },
  {
    id: 'fc-ch16-060',
    chapter_id: 'ch-16',
    front: 'How do **uniform layers** create movement?',
    back: 'Uniform layers create movement because equal-length layers and even weight distribution let the hair flow and respond to styling as one unit.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 60,
    is_active: true,
  },
  {
    id: 'fc-ch16-061',
    chapter_id: 'ch-16',
    front: 'What are common long-layer mistakes?',
    back: 'Common mistakes include removing too much perimeter length, inconsistent elevation, losing the traveling guide, uneven tension, unintentional overdirection, and skipping the cross-check.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 61,
    is_active: true,
  },
  {
    id: 'fc-ch16-062',
    chapter_id: 'ch-16',
    front: 'When should **overdirection** be avoided?',
    back: 'Overdirection should be avoided when the goal is balanced, natural fall or even weight distribution, because it intentionally shifts length and weight.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 62,
    is_active: true,
  },
  {
    id: 'fc-ch16-063',
    chapter_id: 'ch-16',
    front: 'Why must advanced techniques serve the haircut structure rather than replace it?',
    back: 'Advanced techniques refine a haircut only when the underlying structure is sound. Using them without a clear plan damages balance and design.',
    category: 'Professional Essential',
    difficulty: 'hard',
    order_index: 63,
    is_active: true,
  },
  {
    id: 'fc-ch16-064',
    chapter_id: 'ch-16',
    front: 'Why is styling considered the final step of a haircut service?',
    back: 'Styling reveals the true balance, movement, and weight distribution of the cut. It also shows the client how the hair will look and behave after leaving the shop.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 64,
    is_active: true,
  },
  {
    id: 'fc-ch16-065',
    chapter_id: 'ch-16',
    front: 'What is the purpose of **wet styling**?',
    back: 'Wet styling shapes the hair while damp and sets it into a finished form as it dries, useful for polished, classic looks that hold a set.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 65,
    is_active: true,
  },
  {
    id: 'fc-ch16-066',
    chapter_id: 'ch-16',
    front: 'What is the purpose of **hair wrapping**?',
    back: 'Hair wrapping smooths the cuticle and preserves a straight, sleek finish by keeping the hair flat and directed along the scalp.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 66,
    is_active: true,
  },
  {
    id: 'fc-ch16-067',
    chapter_id: 'ch-16',
    front: 'How does **airflow direction** affect blow-dry finish?',
    back: 'Airflow directed upward at the roots creates volume. Airflow directed downward along the cuticle creates smoothness and shine.',
    category: 'Professional Essential',
    difficulty: 'medium',
    order_index: 67,
    is_active: true,
  },
  {
    id: 'fc-ch16-068',
    chapter_id: 'ch-16',
    front: 'How do you select a blow-dry brush?',
    back: 'Round brushes add volume and curve, paddle brushes smooth and straighten, and vent brushes speed drying with less tension.',
    category: 'Professional Essential',
    difficulty: 'easy',
    order_index: 68,
    is_active: true,
  },
]

export default chapter16PremiumFlashcards
