import type { QuizQuestion } from '@/types'
import type { ConceptId } from './chapter-2-concepts/types'
type A='a'|'b'|'c'|'d'; type D='easy'|'medium'|'hard'
interface S{conceptId:ConceptId;sourceBlockIds:readonly string[];sourceBasis:string;items:readonly {question:string;answer_a:string;answer_b:string;answer_c:string;answer_d:string;correct_answer:A;explanation:string;difficulty:D}[]}
const seeds:readonly S[]=[
{conceptId:'C-2-21',sourceBlockIds:['financial-truth','financial-rules','barber-finances','money-goals','money-levels'],sourceBasis:'ASCYN enrichment in Chapter 2: financial literacy includes tracking income, using a budget framework as a starting point, planning for taxes, savings, and emergency reserves.',items:[
{question:'A new barber earns irregular weekly income. What is the best first financial habit?',answer_a:'Track all income and expenses consistently so decisions are based on actual numbers.',answer_b:'Estimate income from memory at the end of each month.',answer_c:'Spend cash income first because it is harder to track.',answer_d:'Wait until earnings become stable before using a budget.',correct_answer:'a',explanation:'ASCYN financial literacy starts with knowing what is actually coming in and going out; consistent tracking makes budgeting and planning possible.',difficulty:'medium'},
{question:'How should the 50/30/20 framework be used in Chapter 2?',answer_a:'As a fixed law that every barber must follow exactly.',answer_b:'As a practical starting framework that can be adapted to the person’s real income and obligations.',answer_c:'Only for salaried workers with predictable pay.',answer_d:'As a replacement for tracking taxes and business expenses.',correct_answer:'b',explanation:'Instructor guidance explicitly treats 50/30/20 as a flexible starting framework, not a rule that makes every different allocation wrong.',difficulty:'medium'},
{question:'A booth renter receives strong cash income but sets nothing aside for taxes. What is the main risk?',answer_a:'The barber will automatically lose all deductions.',answer_b:'The shop owner becomes responsible for the barber’s taxes.',answer_c:'Tax obligations can create a large cash-flow problem later if income is not tracked and money is not reserved.',answer_d:'Cash income does not count until deposited.',correct_answer:'c',explanation:'ASCYN’s financial-literacy material emphasizes tracking income and maintaining tax set-aside habits so tax time does not become a preventable crisis.',difficulty:'hard'},
{question:'Why is an emergency fund useful for a barber?',answer_a:'It guarantees the barber will never need insurance.',answer_b:'It should replace retirement saving permanently.',answer_c:'It allows every unexpected expense to be paid without review.',answer_d:'It creates a buffer when income drops or an unplanned expense would otherwise disrupt essential obligations.',correct_answer:'d',explanation:'An emergency reserve is career protection because variable income and unexpected costs can otherwise force short-term financial decisions that destabilize the barber.',difficulty:'medium'}]},
{conceptId:'C-2-23',sourceBlockIds:['cultural-competence-intro','inclusive-practices','cultural-awareness','cultural-scenarios'],sourceBasis:'ASCYN Chapter 2 lesson: culturally competent service uses curiosity, respect, individualized consultation, and avoidance of assumptions about background, hair, identity, or preferences.',items:[
{question:'A client has a hair texture the barber has limited experience with. What is the strongest first response?',answer_a:'Ask respectful questions about the client’s hair history and preferences, then use appropriate learning or referral when needed.',answer_b:'Use the barber’s usual technique without mentioning the difference.',answer_c:'Assume the client wants the style most common for that texture.',answer_d:'Decline every client whose hair is unfamiliar.',correct_answer:'a',explanation:'Chapter 2 teaches curiosity, humility, and individualized consultation rather than guessing, stereotyping, or automatically excluding unfamiliar clients.',difficulty:'hard'},
{question:'What does “avoid assumptions” mean in an inclusive consultation?',answer_a:'Never ask the client any questions about preferences.',answer_b:'Do not predict style, communication, or identity preferences from appearance; ask respectfully instead.',answer_c:'Use the same service plan for everyone to stay fair.',answer_d:'Avoid discussing hair history because it may feel personal.',correct_answer:'b',explanation:'Inclusive service is individualized. Respectful questions let the client define their own needs instead of having the barber infer them from appearance or background.',difficulty:'medium'},
{question:'A client asks the barber to use a term the barber has not heard before. What response best fits Chapter 2?',answer_a:'Ignore the request and use familiar language.',answer_b:'Apologize repeatedly and make the client explain the entire topic.',answer_c:'Ask briefly and respectfully what the client prefers, then use that preference.',answer_d:'Avoid speaking for the rest of the appointment.',correct_answer:'c',explanation:'The cultural-competence section encourages respectful curiosity and adaptation; a simple clarification is more appropriate than avoidance or defensiveness.',difficulty:'application'},
{question:'Which shop behavior best supports an inclusive environment?',answer_a:'Assuming regular clients define what everyone else will find comfortable.',answer_b:'Using stereotypes as harmless humor if most clients laugh.',answer_c:'Avoiding clients with unfamiliar preferences.',answer_d:'Creating a respectful environment where different clients can communicate preferences without being judged or stereotyped.',correct_answer:'d',explanation:'ASCYN frames inclusion as making the space welcoming and respectful for different backgrounds, communication styles, hair needs, and personal preferences.',difficulty:'hard'}]},
{conceptId:'C-2-24',sourceBlockIds:['career-planning-intro','career-milestones','specialization-paths','career-levels'],sourceBasis:'ASCYN Chapter 2 lesson: career planning is a living roadmap with milestones, periodic review, skill development, and possible specialization based on evolving goals and opportunities.',items:[
{question:'What is the main purpose of a career roadmap?',answer_a:'Give direction and milestones so current decisions support longer-term professional goals.',answer_b:'Predict the exact shop and income a barber will have years from now.',answer_c:'Prevent the barber from changing interests later.',answer_d:'Replace short-term practice goals with one long plan.',correct_answer:'a',explanation:'The lesson presents a career roadmap as direction for decisions and milestones, while recognizing that the plan should evolve as the barber grows.',difficulty:'medium'},
{question:'A barber’s interests change after a year of work. How should the career plan respond?',answer_a:'Keep the original plan unchanged so the first decision remains binding.',answer_b:'Review and update the roadmap to reflect new skills, interests, and opportunities.',answer_c:'Abandon planning because career paths are unpredictable.',answer_d:'Choose whichever specialization appears most popular online.',correct_answer:'b',explanation:'Instructor guidance describes the roadmap as a living document; useful planning includes periodic revision rather than rigidly preserving outdated assumptions.',difficulty:'application'},
{question:'What is a strong reason to explore a specialization?',answer_a:'It guarantees premium pricing immediately.',answer_b:'It removes the need to maintain core skills.',answer_c:'It can deepen expertise in an area that fits the barber’s interests, market, and long-term direction.',answer_d:'Every barber is required to specialize after the first year.',correct_answer:'c',explanation:'Chapter 2 presents specialization as one possible career-development path, useful when it aligns with interests, skills, opportunities, and the broader roadmap.',difficulty:'medium'},
{question:'Which action best turns a career roadmap into a working plan?',answer_a:'Write the final career title and never revisit it.',answer_b:'Focus only on distant goals five years away.',answer_c:'Wait for opportunities instead of identifying development steps.',answer_d:'Set near-term milestones that build skills, clientele, savings, or experience toward the larger direction.',correct_answer:'d',explanation:'Milestones connect long-term direction with present action, which is what makes a career roadmap useful instead of merely aspirational.',difficulty:'hard'}]},
{conceptId:'C-2-25',sourceBlockIds:['leadership-intro','leadership-qualities','mentorship-actions','leadership-actions'],sourceBasis:'ASCYN enrichment in Chapter 2: leadership is influence through example, constructive feedback, team culture, knowledge sharing, and investment in others rather than title alone.',items:[
{question:'Which behavior best demonstrates leadership before someone has a formal title?',answer_a:'Model reliable professional behavior and help others improve when appropriate.',answer_b:'Wait until promoted before offering any useful guidance.',answer_c:'Correct every coworker publicly to establish authority.',answer_d:'Keep useful techniques private to maintain an advantage.',correct_answer:'a',explanation:'ASCYN defines leadership as influence rather than title; example, support, and constructive contribution can begin while someone is still a student or junior barber.',difficulty:'medium'},
{question:'What makes feedback constructive?',answer_a:'It focuses only on what was wrong so the lesson is memorable.',answer_b:'It identifies what is working, what needs adjustment, and gives the learner a useful next step.',answer_c:'It is delivered publicly so everyone can learn from the mistake.',answer_d:'It avoids any criticism and gives praise only.',correct_answer:'b',explanation:'The leadership material emphasizes feedback that protects growth: clear guidance should help the learner understand both strengths and the specific adjustment needed.',difficulty:'hard'},
{question:'A mentor always takes over when a learner struggles. What is the main weakness in that approach?',answer_a:'It makes the service take too long.',answer_b:'It requires too much patience from the mentor.',answer_c:'It removes the learner’s opportunity to practice, receive coaching, and build independent skill.',answer_d:'It creates too much positive feedback.',correct_answer:'c',explanation:'Mentorship should demonstrate and coach while still allowing the learner to practice; constant takeover can prevent the learner from developing independent competence.',difficulty:'application'},
{question:'Which action most strengthens team culture?',answer_a:'Competing for every advantage and keeping knowledge private.',answer_b:'Giving feedback only to close friends.',answer_c:'Ignoring small team problems to avoid tension.',answer_d:'Sharing knowledge, recognizing good work, and contributing to a respectful growth-oriented environment.',correct_answer:'d',explanation:'ASCYN leadership emphasizes positive influence, collaboration, knowledge sharing, and investment in others as ways to strengthen the whole team.',difficulty:'medium'}]},
{conceptId:'C-2-26',sourceBlockIds:['workplace-intro','shop-etiquette','station-respect','coworker-conduct','busy-days','professional-daily','closing-quote','final-boss'],sourceBasis:'ASCYN Chapter 2 lesson: workplace professionalism includes station responsibility, coworker respect, fair shop conduct, calm communication on busy days, boundaries, and leaving shared spaces ready for others.',items:[
{question:'What should a barber do before leaving a shared station after a busy shift?',answer_a:'Reset and clean the area and return shared items so the next person starts ready.',answer_b:'Leave cleanup for whoever opens the next morning.',answer_c:'Clean only if the shop manager specifically asks.',answer_d:'Move the mess to an unused station.',correct_answer:'a',explanation:'Chapter 2 shop etiquette treats station care and shared-space responsibility as basic professional behavior, especially when others depend on the same workspace.',difficulty:'medium'},
{question:'In a walk-in shop, what behavior best supports coworker fairness?',answer_a:'Take every client who asks for you even when the agreed rotation says otherwise.',answer_b:'Follow the shop’s fair rotation and communicate openly when exceptions are necessary.',answer_c:'Let senior barbers take all high-value services.',answer_d:'Avoid helping coworkers so everyone manages their own workload.',correct_answer:'b',explanation:'The coworker-conduct section emphasizes fair floor sharing and respectful teamwork instead of manipulating walk-in distribution for personal advantage.',difficulty:'medium'},
{question:'The shop is slammed and wait times are growing. What is the most professional response?',answer_a:'Rush each service so the waiting room clears faster.',answer_b:'Stop communicating wait times until the rush ends.',answer_c:'Stay calm, focus on one client at a time, communicate realistic waits, and support the team where possible.',answer_d:'Accept every additional client even after capacity is reached.',correct_answer:'c',explanation:'Busy-day professionalism combines calm service, honest timing, teamwork, and quality protection rather than overbooking or rushing clients through.',difficulty:'hard'},
{question:'Which statement best summarizes workplace professionalism in Chapter 2?',answer_a:'Professionalism is mainly formal clothing and speech.',answer_b:'Professionalism matters only when clients are watching.',answer_c:'Professionalism is determined by technical speed.',answer_d:'Professionalism is consistent behavior that respects clients, coworkers, shared space, boundaries, and the operation of the shop.',correct_answer:'d',explanation:'The chapter defines workplace professionalism broadly through reliable daily conduct that helps clients feel comfortable, coworkers respected, and the shop function smoothly.',difficulty:'hard'}]}
]
export const chapter2G5ReassessmentQuestionsP6:QuizQuestion[]=seeds.flatMap((s,si)=>s.items.map((x,qi)=>({id:`qq-2-${String(156+si*4+qi).padStart(3,'0')}`,quiz_id:'quiz-2',...x,order_index:156+si*4+qi})))
export const chapter2G5ReassessmentMappingsP6=chapter2G5ReassessmentQuestionsP6.map((q,i)=>({questionId:q.id as `qq-2-${string}`,conceptId:seeds[Math.floor(i/4)].conceptId}))
export const chapter2G5ReassessmentAuditP6=chapter2G5ReassessmentQuestionsP6.map((q,i)=>{const s=seeds[Math.floor(i/4)];return{questionId:q.id,conceptId:s.conceptId,sourceBlockIds:s.sourceBlockIds,sourceBasis:s.sourceBasis}})
