// Quiz questions for Barber Study Pro V2
// Generated from flashcard content — each question maps to a flashcard concept
// Original wording, board-exam aligned, educational quality

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 1: History of Barbering (25 questions)
// ───────────────────────────────────────────────
export const chapter1QuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-1-001',
    quiz_id: 'quiz-1',
    question: 'What natural materials did early humans use for cutting hair during the Glacial Age?',
    answer_a: 'Metal blades and combs',
    answer_b: 'Sharpened flints, oyster shells, bone fragments, and animal sinew',
    answer_c: 'Bronze knives and wooden picks',
    answer_d: 'Glass shards and leather strips',
    correct_answer: 'b',
    explanation: 'Early humans fashioned rudimentary tools from sharpened flints, oyster shells, bone fragments, and animal sinew for cutting and styling hair.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-1-002',
    quiz_id: 'quiz-1',
    question: 'What was the Egyptian term for barbers, and what social status did they hold?',
    answer_a: 'Scribes — low status workers',
    answer_b: '"Meryma\'at" — high social standing',
    answer_c: 'Priests — religious figures only',
    answer_d: 'Servants — no special status',
    correct_answer: 'b',
    explanation: 'Egyptian barbers were called "Meryma\'at" and enjoyed high social standing and respect in society.',
    difficulty: 'medium',
    order_index: 2,
  },
  {
    id: 'qq-1-003',
    quiz_id: 'quiz-1',
    question: 'Why did Egyptian priests shave their entire bodies daily?',
    answer_a: 'To prevent lice infestation',
    answer_b: 'As a religious purification practice before rituals',
    answer_c: 'To show allegiance to the pharaoh',
    answer_d: 'Because hair was considered unclean',
    correct_answer: 'b',
    explanation: 'Daily full-body shaving was a religious purification practice to maintain spiritual cleanliness before performing rituals.',
    difficulty: 'medium',
    order_index: 3,
  },
  {
    id: 'qq-1-004',
    quiz_id: 'quiz-1',
    question: 'What spiritual belief did many ancient cultures hold about hair?',
    answer_a: 'Hair contained magical healing powers',
    answer_b: 'Hair was the gateway for spirits entering and leaving the body',
    answer_c: 'Long hair brought bad luck',
    answer_d: 'Hair should never be cut after age 30',
    correct_answer: 'b',
    explanation: 'Many ancient cultures believed hair was the gateway for spirits entering and leaving the body, giving it profound spiritual significance.',
    difficulty: 'medium',
    order_index: 4,
  },
  {
    id: 'qq-1-005',
    quiz_id: 'quiz-1',
    question: 'How did Masai warriors use braiding patterns?',
    answer_a: 'To identify enemy tribes',
    answer_b: 'To indicate social rank, warrior status, and tribal position',
    answer_c: 'Only for ceremonial dances',
    answer_d: 'To signal readiness for battle',
    correct_answer: 'b',
    explanation: 'Specific braiding patterns and styles indicated social rank, warrior status, and tribal position within the community.',
    difficulty: 'hard',
    order_index: 5,
  },
  {
    id: 'qq-1-006',
    quiz_id: 'quiz-1',
    question: 'During which prehistoric period were stone razors and scrapers used for hair removal?',
    answer_a: 'Neolithic period (10,000–4,500 BC)',
    answer_b: 'Upper Paleolithic period (40,000–10,000 BC)',
    answer_c: 'Bronze Age (3,300–1,200 BC)',
    answer_d: 'Iron Age (1,200–600 BC)',
    correct_answer: 'b',
    explanation: 'The Upper Paleolithic period, spanning roughly 40,000 to 10,000 BC, saw the use of stone tools for grooming and skinning.',
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-1-007',
    quiz_id: 'quiz-1',
    question: 'What did beards symbolize in ancient cultures?',
    answer_a: 'Wealth and material possessions',
    answer_b: 'Wisdom, physical strength, mature manhood, and religious devotion',
    answer_c: 'Youth and vitality',
    answer_d: 'Political rebellion',
    correct_answer: 'b',
    explanation: 'Beards represented wisdom, physical strength, mature manhood, and deep religious devotion across many civilizations.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-1-008',
    quiz_id: 'quiz-1',
    question: 'Why did Alexander the Great order his soldiers to shave their beards?',
    answer_a: 'To improve hygiene in desert campaigns',
    answer_b: 'Beards could be grabbed by enemies in hand-to-hand combat',
    answer_c: 'To distinguish his army from Persian forces',
    answer_d: 'Religious conversion requirements',
    correct_answer: 'b',
    explanation: 'Beards could be grabbed by enemies during hand-to-hand combat, creating a tactical disadvantage in battle.',
    difficulty: 'medium',
    order_index: 8,
  },
  {
    id: 'qq-1-009',
    quiz_id: 'quiz-1',
    question: 'What event in 1096 led to the formation of the first barber guild in France?',
    answer_a: 'A royal decree requiring all men to be clean-shaven',
    answer_b: 'The Archbishop of Rouen prohibited clergy from wearing beards',
    answer_c: 'The Crusades created demand for battlefield barbers',
    answer_d: 'A plague outbreak required regular shaving',
    correct_answer: 'b',
    explanation: 'The Archbishop of Rouen prohibited clergy from wearing beards, which spurred the organization of barbers into a formal guild.',
    difficulty: 'hard',
    order_index: 9,
  },
  {
    id: 'qq-1-010',
    quiz_id: 'quiz-1',
    question: 'Which Russian ruler famously taxed bearded men?',
    answer_a: 'Ivan the Terrible',
    answer_b: 'Catherine the Great',
    answer_c: 'Peter the Great',
    answer_d: 'Nicholas II',
    correct_answer: 'c',
    explanation: 'Peter the Great imposed a beard tax as part of his modernization efforts to align Russian fashion with Western Europe.',
    difficulty: 'medium',
    order_index: 10,
  },
  {
    id: 'qq-1-011',
    quiz_id: 'quiz-1',
    question: 'What did Pythagoras believe about cutting hair?',
    answer_a: 'It brought good fortune',
    answer_b: 'Trimming hair reduced intellectual capacity and mental abilities',
    answer_c: 'Hair should only be cut during full moons',
    answer_d: 'Cutting hair was a sin against nature',
    correct_answer: 'b',
    explanation: 'The philosopher Pythagoras claimed that trimming hair reduced a person\'s intellectual capacity and mental abilities.',
    difficulty: 'hard',
    order_index: 11,
  },
  {
    id: 'qq-1-012',
    quiz_id: 'quiz-1',
    question: 'What did the Chinese queue hairstyle represent under Manchu rule?',
    answer_a: 'Religious devotion to Buddhism',
    answer_b: 'Political submission and obedience to the ruling government',
    answer_c: 'Membership in the imperial guard',
    answer_d: 'Wealth and merchant status',
    correct_answer: 'b',
    explanation: 'The forced queue hairstyle symbolized political submission and obedience to the ruling Manchu government.',
    difficulty: 'medium',
    order_index: 12,
  },
  {
    id: 'qq-1-013',
    quiz_id: 'quiz-1',
    question: 'What is tonsure, and when was the circular tonsure abolished?',
    answer_a: 'A full-head shave, abolished in 1450',
    answer_b: 'Shaving a patch on the crown, abolished in 1972',
    answer_c: 'A ceremonial beard trim, abolished in 1800',
    answer_d: 'A side-lock hairstyle, still practiced today',
    correct_answer: 'b',
    explanation: 'Tonsure is the practice of shaving a patch on the crown of the head. The circular tonsure of St. Peter was abolished in 1972.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-1-014',
    quiz_id: 'quiz-1',
    question: 'What medical procedures did barber-surgeons perform during the Middle Ages?',
    answer_a: 'Only haircuts and shaves',
    answer_b: 'Bloodletting, minor surgery, herbal remedies, and tooth extractions',
    answer_c: 'Major operations and autopsies',
    answer_d: 'Childbirth assistance and midwifery',
    correct_answer: 'b',
    explanation: 'Beyond grooming, barber-surgeons performed bloodletting, minor surgical procedures, herbal remedies, and tooth extractions.',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-1-015',
    quiz_id: 'quiz-1',
    question: 'What happened at the Council of Tours in 1163 that affected barbers?',
    answer_a: 'Barbers were granted medical licenses',
    answer_b: 'The Pope forbade clergy from practicing medicine, transferring duties to barbers',
    answer_c: 'The first barber school was established',
    answer_d: 'Barbers were banned from performing surgery',
    correct_answer: 'b',
    explanation: 'The Pope forbade clergy from practicing medicine or surgery, transferring those duties to barbers who already handled blades.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-1-016',
    quiz_id: 'quiz-1',
    question: 'When did surgeons officially separate from barbers, ending the barber-surgeon era?',
    answer_a: '1540',
    answer_b: '1605',
    answer_c: '1745',
    answer_d: '1897',
    correct_answer: 'c',
    explanation: 'The complete separation occurred in 1745, when surgeons formally split from barbers to establish independent medical practice.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-1-017',
    quiz_id: 'quiz-1',
    question: 'What do the three colors of the barber pole represent?',
    answer_a: 'Red, white, and blue for the American flag',
    answer_b: 'Red for blood, white for bandages, blue for veins',
    answer_c: 'Red for fire, white for purity, blue for water',
    answer_d: 'Red for courage, white for peace, blue for loyalty',
    correct_answer: 'b',
    explanation: 'Red represents blood, white represents bandages, and blue represents veins — all originating from bloodletting practices.',
    difficulty: 'easy',
    order_index: 17,
  },
  {
    id: 'qq-1-018',
    quiz_id: 'quiz-1',
    question: 'When and where were the earliest scissors developed?',
    answer_a: 'Ancient Rome, 500 BC',
    answer_b: 'The Middle East, between 3000 and 2000 BC',
    answer_c: 'China, during the Han Dynasty',
    answer_d: 'Medieval Europe, 1200 AD',
    correct_answer: 'b',
    explanation: 'The Middle East produced the earliest scissors between 3000 and 2000 BC, revolutionizing hair cutting precision.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-1-019',
    quiz_id: 'quiz-1',
    question: 'Who invented the first practical electric hair clippers, and in what year?',
    answer_a: 'Matthew Andis in 1921',
    answer_b: 'John Oster in 1928',
    answer_c: 'Leo J. Wahl in 1919',
    answer_d: 'Thomas Edison in 1905',
    correct_answer: 'c',
    explanation: 'Leo J. Wahl invented the first practical electric hair clippers in 1919, transforming the barbering industry.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-1-020',
    quiz_id: 'quiz-1',
    question: 'Which three companies dominated early electric clipper manufacturing?',
    answer_a: 'Gillette, Remington, and Philips',
    answer_b: 'Wahl, Andis, and Oster',
    answer_c: 'Sears, Montgomery Ward, and Woolworth',
    answer_d: 'General Electric, Westinghouse, and IBM',
    correct_answer: 'b',
    explanation: 'Wahl Clipper Corporation (1921), Andis (developed by Matthew Andis), and Oster (John Oster marketed motorized clippers in 1928) dominated early manufacturing.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'qq-1-021',
    quiz_id: 'quiz-1',
    question: 'When and where was the first barber-licensing law passed?',
    answer_a: 'New York, 1905',
    answer_b: 'Minnesota, 1897',
    answer_c: 'California, 1910',
    answer_d: 'Illinois, 1885',
    correct_answer: 'b',
    explanation: 'Minnesota passed the first barber-licensing law in 1897, establishing standards for sanitation, education, and disinfection.',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-1-022',
    quiz_id: 'quiz-1',
    question: 'What does NABBA stand for, and when was it founded?',
    answer_a: 'National Association of Barbers and Beauticians, founded 1910',
    answer_b: 'National Association of State Boards of Barber Examiners, founded 1929',
    answer_c: 'North American Barber Brotherhood Alliance, founded 1950',
    answer_d: 'National Academy of Barbering and Beauty Arts, founded 1900',
    correct_answer: 'b',
    explanation: 'The National Association of State Boards of Barber Examiners was founded in 1929 and represents over 300,000 barbers.',
    difficulty: 'easy',
    order_index: 22,
  },
  {
    id: 'qq-1-023',
    quiz_id: 'quiz-1',
    question: 'What are the five main objectives of NABBA?',
    answer_a: 'Profit, expansion, marketing, sales, and recruitment',
    answer_b: 'Promote information exchange, establish exam/licensing standards, set curriculum standards, support continuing education, and protect consumers',
    answer_c: 'Political lobbying, union organization, strike coordination, wage negotiation, and benefits management',
    answer_d: 'Product development, tool manufacturing, school accreditation, advertising, and trade shows',
    correct_answer: 'b',
    explanation: 'NABBA promotes information exchange, establishes exam/licensing standards, sets curriculum standards, supports continuing education, and protects consumers.',
    difficulty: 'hard',
    order_index: 23,
  },
  {
    id: 'qq-1-024',
    quiz_id: 'quiz-1',
    question: 'What factors caused the decline of barbershops in the 1980s–1990s?',
    answer_a: 'Economic recession and high unemployment',
    answer_b: 'Unisex salons, full-service spas, long hair trends, and cosmetology licensing shifts',
    answer_c: 'Government bans on barbering',
    answer_d: 'Lack of interest among young people',
    correct_answer: 'b',
    explanation: 'Unisex salons, full-service spas, long hair fashion trends, and shifts toward cosmetology licensing reduced traditional barbershop demand.',
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-1-025',
    quiz_id: 'quiz-1',
    question: 'What percentage of barbershop clientele are women in some modern shops?',
    answer_a: 'Approximately 10%',
    answer_b: 'Approximately 30%',
    answer_c: 'Approximately 50%',
    answer_d: 'Less than 5%',
    correct_answer: 'b',
    explanation: 'Women now make up approximately 30% of clientele in some barbershops, with female barbers and students also increasing.',
    difficulty: 'medium',
    order_index: 25,
  },
]

// ───────────────────────────────────────────────
// CHAPTER 2: Life Skills (25 questions)
// ───────────────────────────────────────────────
export const chapter2QuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-2-001',
    quiz_id: 'quiz-2',
    question: 'Why are life skills equally important as technical skills in barbering?',
    answer_a: 'They are required by state licensing boards',
    answer_b: 'Barbers interact daily with diverse clients and coworkers, requiring strong interpersonal abilities',
    answer_c: 'They replace the need for technical training',
    answer_d: 'Only senior barbers need life skills',
    correct_answer: 'b',
    explanation: 'Barbers interact daily with diverse clients and coworkers. Strong life skills ensure positive interactions, help navigate difficult situations, and build self-esteem needed for career success.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-2-002',
    quiz_id: 'quiz-2',
    question: 'What is self-actualization, and what does it require?',
    answer_a: 'Earning the highest salary possible',
    answer_b: 'Fulfilling your full potential through lifelong commitment to personal growth',
    answer_c: 'Opening your own barbershop by age 30',
    answer_d: 'Winning competitions and awards',
    correct_answer: 'b',
    explanation: 'Self-actualization means fulfilling your full potential. It requires a lifelong commitment to personal growth, learning, and continuous improvement.',
    difficulty: 'medium',
    order_index: 2,
  },
  {
    id: 'qq-2-003',
    quiz_id: 'quiz-2',
    question: 'What are three destructive habits that kill productivity?',
    answer_a: 'Overworking, multitasking, and perfectionism',
    answer_b: 'Procrastination, perfectionism, and lack of a game plan',
    answer_c: 'Sleeping too much, eating poorly, and exercising rarely',
    answer_d: 'Talking too much, arriving late, and forgetting appointments',
    correct_answer: 'b',
    explanation: 'Procrastination (putting things off), perfectionism (unhealthy need for flawlessness), and lack of a game plan (no organized goals or direction) are productivity killers.',
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-2-004',
    quiz_id: 'quiz-2',
    question: 'How can visualization help achieve professional success?',
    answer_a: 'It replaces the need for actual practice',
    answer_b: 'It reinforces positive beliefs, builds confidence, and programs the mind for achievement',
    answer_c: 'It guarantees clients will book appointments',
    answer_d: 'It is only useful for athletes, not barbers',
    correct_answer: 'b',
    explanation: 'Regularly imagining yourself working competently in your ideal barbershop reinforces positive beliefs, builds confidence, and programs your mind for achievement.',
    difficulty: 'medium',
    order_index: 4,
  },
  {
    id: 'qq-2-005',
    quiz_id: 'quiz-2',
    question: 'Why should barbers keep their personal life separate from work?',
    answer_a: 'State law requires complete separation',
    answer_b: 'Healthy boundaries prevent burnout and ensure full professional focus',
    answer_c: 'Clients do not care about barbers\' personal lives',
    answer_d: 'It makes scheduling easier',
    correct_answer: 'b',
    explanation: 'Maintaining healthy boundaries prevents burnout, protects relationships, and ensures you bring full professional focus to your clients during work hours.',
    difficulty: 'medium',
    order_index: 5,
  },
  {
    id: 'qq-2-006',
    quiz_id: 'quiz-2',
    question: 'What two elements combine to create creativity?',
    answer_a: 'Money and free time',
    answer_b: 'Natural talent combined with unlimited ideas and innovative thinking',
    answer_c: 'Formal education and certification',
    answer_d: 'Expensive tools and premium products',
    correct_answer: 'b',
    explanation: 'Natural talent (artistic ability, cutting skill) combined with an unlimited resource of ideas, solutions, and innovative thinking creates creativity.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-2-007',
    quiz_id: 'quiz-2',
    question: 'How can barbers enhance their creative capabilities?',
    answer_a: 'By copying other barbers\' work exactly',
    answer_b: 'Stay positive, seek inspiration, expand vocabulary, and collaborate with peers',
    answer_c: 'By avoiding feedback and criticism entirely',
    answer_d: 'Only through expensive advanced courses',
    correct_answer: 'b',
    explanation: 'Stay positive (criticism blocks ideas), seek inspiration from art and hair shows, expand vocabulary with analytical words, and collaborate with passionate peers.',
    difficulty: 'medium',
    order_index: 7,
  },
  {
    id: 'qq-2-008',
    quiz_id: 'quiz-2',
    question: 'What is the purpose of a personal mission statement?',
    answer_a: 'To impress clients with fancy language',
    answer_b: 'To define your purpose, core values, and professional direction',
    answer_c: 'To replace the need for business cards',
    answer_d: 'To satisfy licensing requirements',
    correct_answer: 'b',
    explanation: 'A mission statement defines your purpose, core values, and direction. It provides focus and becomes the cultural pulse of your professional life.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-2-009',
    quiz_id: 'quiz-2',
    question: 'What is the recommended length for a mission statement?',
    answer_a: 'One to two pages',
    answer_b: 'One to two sentences',
    answer_c: 'At least ten bullet points',
    answer_d: 'There is no recommended length',
    correct_answer: 'b',
    explanation: 'Keep it concise — one to two sentences that clearly capture your professional purpose and values.',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-2-010',
    quiz_id: 'quiz-2',
    question: 'What is the difference between short-term and long-term goals?',
    answer_a: 'Short-term goals are less important than long-term goals',
    answer_b: 'Short-term goals take one year or less; long-term goals span two or more years',
    answer_c: 'Only long-term goals need to be written down',
    answer_d: 'Short-term goals require no planning',
    correct_answer: 'b',
    explanation: 'Short-term goals take one year or less to achieve (passing an exam, graduating). Long-term goals span two or more years (owning a shop in five years).',
    difficulty: 'easy',
    order_index: 10,
  },
  {
    id: 'qq-2-011',
    quiz_id: 'quiz-2',
    question: 'What are five best practices for effective goal setting?',
    answer_a: 'Dream big, tell everyone, wait for opportunities, hope for success, and avoid risks',
    answer_b: 'Write goals down, break into steps, create action plans, revisit regularly, and set feasible targets',
    answer_c: 'Focus only on money, ignore setbacks, work alone, avoid feedback, and never change plans',
    answer_d: 'Set one massive goal, avoid details, never review progress, and expect overnight success',
    correct_answer: 'b',
    explanation: 'Write goals down, break long-term goals into smaller steps, create action plans, revisit and adjust regularly, and set feasible targets while maintaining consistent focus.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-2-012',
    quiz_id: 'quiz-2',
    question: 'What are four key time management strategies for barbers?',
    answer_a: 'Work faster, skip breaks, multitask constantly, and take every walk-in',
    answer_b: 'Prioritize tasks, create schedules, learn to say no, and use planning tools',
    answer_c: 'Arrive late, leave early, ignore appointments, and avoid lists',
    answer_d: 'Only serve regular clients, refuse new business, and work weekends only',
    correct_answer: 'b',
    explanation: 'Prioritize tasks by importance, create flexible daily/weekly schedules, learn to say no kindly to avoid overcommitment, and use lists or digital planning tools.',
    difficulty: 'easy',
    order_index: 12,
  },
  {
    id: 'qq-2-013',
    quiz_id: 'quiz-2',
    question: 'Why is team communication important for time management in a barbershop?',
    answer_a: 'It reduces the need for individual scheduling',
    answer_b: 'Coordinating appointments versus walk-ins requires team effort and clear communication',
    answer_c: 'Team communication is only needed for large shops',
    answer_d: 'It allows barbers to take longer breaks',
    correct_answer: 'b',
    explanation: 'Coordinating appointments versus walk-ins requires team effort. Clear communication ensures smooth scheduling and prevents conflicts.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-2-014',
    quiz_id: 'quiz-2',
    question: 'Name four memory and study techniques useful for barber students.',
    answer_a: 'Cramming, guessing, skipping hard topics, and copying notes',
    answer_b: 'Repetition, organization, mnemonics, and mind mapping',
    answer_c: 'Sleeping with textbooks, listening to loud music, studying alone, and avoiding practice',
    answer_d: 'Memorizing only, ignoring hands-on training, avoiding review, and skipping quizzes',
    correct_answer: 'b',
    explanation: 'Repetition (verbal, written, hands-on), organization (breaking topics into segments), mnemonics (acronyms, word associations), and mind mapping (visual branching from central topics).',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-2-015',
    quiz_id: 'quiz-2',
    question: 'What does the acronym SHAPES stand for in skin function mnemonics?',
    answer_a: 'Safety, Hygiene, Anatomy, Physiology, Ergonomics, Sanitation',
    answer_b: 'Sensation, Heat regulation, Absorption, Protection, Excretion, Secretion',
    answer_c: 'Shampoo, Condition, Apply product, Evaluate, Style, Finish',
    answer_d: 'Shape, Hold, Angle, Position, Elevation, Section',
    correct_answer: 'b',
    explanation: 'Sensation, Heat regulation, Absorption, Protection, Excretion, Secretion — the six primary functions of healthy skin.',
    difficulty: 'hard',
    order_index: 15,
  },
  {
    id: 'qq-2-016',
    quiz_id: 'quiz-2',
    question: 'Define ethics in the context of professional barbering.',
    answer_a: 'Following every client request without question',
    answer_b: 'The moral principles that guide respectful, courteous, and honest professional behavior',
    answer_c: 'Maximizing profit regardless of method',
    answer_d: 'Avoiding all confrontation with clients',
    correct_answer: 'b',
    explanation: 'Ethics are the moral principles that guide professional behavior, ensuring respectful, courteous, and honest conduct with clients and colleagues.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-2-017',
    quiz_id: 'quiz-2',
    question: 'What are five professional ethical actions every barber should practice?',
    answer_a: 'Charge premium prices, upsell products, work fastest, take shortcuts, and avoid continuing education',
    answer_b: 'Provide skilled services, be honest and courteous, maintain confidentiality, pursue continuing education, and give accurate information',
    answer_c: 'Focus only on regulars, ignore new clients, avoid documentation, and skip sanitation',
    answer_d: 'Promise guaranteed results, hide mistakes, and compete aggressively with coworkers',
    correct_answer: 'b',
    explanation: 'Provide skilled and competent services, be honest and courteous, maintain client confidentiality, participate in continuing education, and give accurate information about treatments and products.',
    difficulty: 'medium',
    order_index: 17,
  },
  {
    id: 'qq-2-018',
    quiz_id: 'quiz-2',
    question: 'Why is client confidentiality considered an ethical obligation?',
    answer_a: 'It is only required for celebrity clients',
    answer_b: 'Clients share personal information; maintaining discretion builds trust and upholds integrity',
    answer_c: 'State boards randomly audit client conversations',
    answer_d: 'Confidentiality agreements are legally binding in all states',
    correct_answer: 'b',
    explanation: 'Clients share personal information during services. Maintaining discretion builds trust, protects privacy, and upholds professional integrity.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-2-019',
    quiz_id: 'quiz-2',
    question: 'What does diplomacy (tact) mean in professional communication?',
    answer_a: 'Avoiding all difficult conversations',
    answer_b: 'Delivering truthful messages in a kind, respectful manner that preserves relationships',
    answer_c: 'Telling clients exactly what they want to hear',
    answer_d: 'Using formal language exclusively',
    correct_answer: 'b',
    explanation: 'Delivering truthful messages and feedback in a kind, respectful manner that preserves relationships and avoids unnecessary conflict.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-2-020',
    quiz_id: 'quiz-2',
    question: 'List seven characteristics of a healthy, positive professional attitude.',
    answer_a: 'Perfectionism, competitiveness, isolation, rigidity, skepticism, defensiveness, and impatience',
    answer_b: 'Diplomacy, pleasing tone, emotional stability, sensitivity, strong values, receptivity, and effective communication',
    answer_c: 'Aggressiveness, dominance, control, speed, volume, intensity, and persistence',
    answer_d: 'Passivity, avoidance, silence, compliance, dependence, hesitation, and conformity',
    correct_answer: 'b',
    explanation: 'Diplomacy, pleasing tone of voice, emotional stability, sensitivity, strong values and goals, receptivity to new ideas, and effective communication skills.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'qq-2-021',
    quiz_id: 'quiz-2',
    question: 'Why is emotional stability important for barbers?',
    answer_a: 'It helps barbers win arguments with clients',
    answer_b: 'Barbers encounter diverse personalities; emotional stability ensures calm, professional responses',
    answer_c: 'It eliminates the need for breaks during the workday',
    answer_d: 'Only managers need emotional stability',
    correct_answer: 'b',
    explanation: 'Barbers encounter diverse personalities and occasional confrontations. Emotional stability ensures professional, calm responses rather than reactive behavior.',
    difficulty: 'medium',
    order_index: 21,
  },
  {
    id: 'qq-2-022',
    quiz_id: 'quiz-2',
    question: 'How does a barber\'s personality impact their professional and personal life?',
    answer_a: 'Personality has no effect on professional success',
    answer_b: 'A pleasing attitude enhances client relationships, workplace harmony, and life satisfaction',
    answer_c: 'Only technical skill matters; personality is irrelevant',
    answer_d: 'Barbers should suppress their personality completely',
    correct_answer: 'b',
    explanation: 'Personality encompasses all characteristics, attitudes, and behaviors. A pleasing attitude enhances client relationships, workplace harmony, and overall life satisfaction.',
    difficulty: 'easy',
    order_index: 22,
  },
  {
    id: 'qq-2-023',
    quiz_id: 'quiz-2',
    question: 'Which of the following is a short-term goal for a barber student?',
    answer_a: 'Owning a barbershop in ten years',
    answer_b: 'Passing the state board exam within six months',
    answer_c: 'Becoming a national educator within five years',
    answer_d: 'Building a million-dollar brand by retirement',
    correct_answer: 'b',
    explanation: 'Short-term goals take one year or less to achieve, such as passing an exam or graduating. Long-term goals span two or more years.',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'qq-2-024',
    quiz_id: 'quiz-2',
    question: 'What is the primary purpose of using mnemonics when studying barbering?',
    answer_a: 'To replace hands-on practice entirely',
    answer_b: 'To create memory aids like acronyms and word associations for easier recall',
    answer_c: 'To impress instructors with creative language',
    answer_d: 'To avoid reading textbooks',
    correct_answer: 'b',
    explanation: 'Mnemonics such as acronyms and word associations help students remember complex information by creating memorable mental connections.',
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-2-025',
    quiz_id: 'quiz-2',
    question: 'Why is continuing education considered an ethical responsibility?',
    answer_a: 'It is only required to renew licenses',
    answer_b: 'Barbers must stay current with techniques, sanitation standards, and industry trends to serve clients competently',
    answer_c: 'Continuing education is optional and not ethically relevant',
    answer_d: 'It is only for barbers who want to teach',
    correct_answer: 'b',
    explanation: 'Participating in continuing education ensures barbers maintain skilled and competent services, which is a core ethical obligation to clients.',
    difficulty: 'medium',
    order_index: 25,
  },
]

// ───────────────────────────────────────────────
// Export all quiz questions by chapter
// ───────────────────────────────────────────────
export const allQuizQuestions: Record<string, QuizQuestion[]> = {
  'quiz-1': chapter1QuizQuestions,
  'quiz-2': chapter2QuizQuestions,
}
