// Quiz questions for Barber Study Pro V2
// Generated from flashcard content — each question maps to a flashcard concept
// Original wording, board-exam aligned, educational quality

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 1: History of Barbering (25 questions)
// ───────────────────────────────────────────────
export const chapter1QuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-1-001',
    quiz_id: 'quiz-1',
    question: 'What natural materials did early humans use for cutting hair during the Glacial Age?',
    answer_a: 'Metal blades and combs',
    answer_b: 'Sharpened flints, oyster shells, bone fragments, and animal sinew',
    answer_c: 'Bronze knives and wooden picks',
    answer_d: 'Glass shards and leather strips',
    correct_answer: 'b',
    explanation: 'Early humans fashioned rudimentary tools from sharpened flints, oyster shells, bone fragments, and animal sinew for cutting and styling hair.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-1-002',
    quiz_id: 'quiz-1',
    question: 'What was the Egyptian term for barbers, and what social status did they hold?',
    answer_a: 'Scribes — low status workers',
    answer_b: '"Meryma\'at" — high social standing',
    answer_c: 'Priests — religious figures only',
    answer_d: 'Servants — no special status',
    correct_answer: 'b',
    explanation: 'Egyptian barbers were called "Meryma\'at" and enjoyed high social standing and respect in society.',
    difficulty: 'medium',
    order_index: 2,
  },
  {
    id: 'qq-1-003',
    quiz_id: 'quiz-1',
    question: 'Why did Egyptian priests shave their entire bodies daily?',
    answer_a: 'To prevent lice infestation',
    answer_b: 'As a religious purification practice before rituals',
    answer_c: 'To show allegiance to the pharaoh',
    answer_d: 'Because hair was considered unclean',
    correct_answer: 'b',
    explanation: 'Daily full-body shaving was a religious purification practice to maintain spiritual cleanliness before performing rituals.',
    difficulty: 'medium',
    order_index: 3,
  },
  {
    id: 'qq-1-004',
    quiz_id: 'quiz-1',
    question: 'What spiritual belief did many ancient cultures hold about hair?',
    answer_a: 'Hair contained magical healing powers',
    answer_b: 'Hair was the gateway for spirits entering and leaving the body',
    answer_c: 'Long hair brought bad luck',
    answer_d: 'Hair should never be cut after age 30',
    correct_answer: 'b',
    explanation: 'Many ancient cultures believed hair was the gateway for spirits entering and leaving the body, giving it profound spiritual significance.',
    difficulty: 'medium',
    order_index: 4,
  },
  {
    id: 'qq-1-005',
    quiz_id: 'quiz-1',
    question: 'How did Masai warriors use braiding patterns?',
    answer_a: 'To identify enemy tribes',
    answer_b: 'To indicate social rank, warrior status, and tribal position',
    answer_c: 'Only for ceremonial dances',
    answer_d: 'To signal readiness for battle',
    correct_answer: 'b',
    explanation: 'Specific braiding patterns and styles indicated social rank, warrior status, and tribal position within the community.',
    difficulty: 'hard',
    order_index: 5,
  },
  {
    id: 'qq-1-006',
    quiz_id: 'quiz-1',
    question: 'During which prehistoric period were stone razors and scrapers used for hair removal?',
    answer_a: 'Neolithic period (10,000–4,500 BC)',
    answer_b: 'Upper Paleolithic period (40,000–10,000 BC)',
    answer_c: 'Bronze Age (3,300–1,200 BC)',
    answer_d: 'Iron Age (1,200–600 BC)',
    correct_answer: 'b',
    explanation: 'The Upper Paleolithic period, spanning roughly 40,000 to 10,000 BC, saw the use of stone tools for grooming and skinning.',
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-1-007',
    quiz_id: 'quiz-1',
    question: 'What did beards symbolize in ancient cultures?',
    answer_a: 'Wealth and material possessions',
    answer_b: 'Wisdom, physical strength, mature manhood, and religious devotion',
    answer_c: 'Youth and vitality',
    answer_d: 'Political rebellion',
    correct_answer: 'b',
    explanation: 'Beards represented wisdom, physical strength, mature manhood, and deep religious devotion across many civilizations.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-1-008',
    quiz_id: 'quiz-1',
    question: 'Why did Alexander the Great order his soldiers to shave their beards?',
    answer_a: 'To improve hygiene in desert campaigns',
    answer_b: 'Beards could be grabbed by enemies in hand-to-hand combat',
    answer_c: 'To distinguish his army from Persian forces',
    answer_d: 'Religious conversion requirements',
    correct_answer: 'b',
    explanation: 'Beards could be grabbed by enemies during hand-to-hand combat, creating a tactical disadvantage in battle.',
    difficulty: 'medium',
    order_index: 8,
  },
  {
    id: 'qq-1-009',
    quiz_id: 'quiz-1',
    question: 'What event in 1096 led to the formation of the first barber guild in France?',
    answer_a: 'A royal decree requiring all men to be clean-shaven',
    answer_b: 'The Archbishop of Rouen prohibited clergy from wearing beards',
    answer_c: 'The Crusades created demand for battlefield barbers',
    answer_d: 'A plague outbreak required regular shaving',
    correct_answer: 'b',
    explanation: 'The Archbishop of Rouen prohibited clergy from wearing beards, which spurred the organization of barbers into a formal guild.',
    difficulty: 'hard',
    order_index: 9,
  },
  {
    id: 'qq-1-010',
    quiz_id: 'quiz-1',
    question: 'Which Russian ruler famously taxed bearded men?',
    answer_a: 'Ivan the Terrible',
    answer_b: 'Catherine the Great',
    answer_c: 'Peter the Great',
    answer_d: 'Nicholas II',
    correct_answer: 'c',
    explanation: 'Peter the Great imposed a beard tax as part of his modernization efforts to align Russian fashion with Western Europe.',
    difficulty: 'medium',
    order_index: 10,
  },
  {
    id: 'qq-1-011',
    quiz_id: 'quiz-1',
    question: 'What did Pythagoras believe about cutting hair?',
    answer_a: 'It brought good fortune',
    answer_b: 'Trimming hair reduced intellectual capacity and mental abilities',
    answer_c: 'Hair should only be cut during full moons',
    answer_d: 'Cutting hair was a sin against nature',
    correct_answer: 'b',
    explanation: 'The philosopher Pythagoras claimed that trimming hair reduced a person\'s intellectual capacity and mental abilities.',
    difficulty: 'hard',
    order_index: 11,
  },
  {
    id: 'qq-1-012',
    quiz_id: 'quiz-1',
    question: 'What did the Chinese queue hairstyle represent under Manchu rule?',
    answer_a: 'Religious devotion to Buddhism',
    answer_b: 'Political submission and obedience to the ruling government',
    answer_c: 'Membership in the imperial guard',
    answer_d: 'Wealth and merchant status',
    correct_answer: 'b',
    explanation: 'The forced queue hairstyle symbolized political submission and obedience to the ruling Manchu government.',
    difficulty: 'medium',
    order_index: 12,
  },
  {
    id: 'qq-1-013',
    quiz_id: 'quiz-1',
    question: 'What is tonsure, and when was the circular tonsure abolished?',
    answer_a: 'A full-head shave, abolished in 1450',
    answer_b: 'Shaving a patch on the crown, abolished in 1972',
    answer_c: 'A ceremonial beard trim, abolished in 1800',
    answer_d: 'A side-lock hairstyle, still practiced today',
    correct_answer: 'b',
    explanation: 'Tonsure is the practice of shaving a patch on the crown of the head. The circular tonsure of St. Peter was abolished in 1972.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-1-014',
    quiz_id: 'quiz-1',
    question: 'What medical procedures did barber-surgeons perform during the Middle Ages?',
    answer_a: 'Only haircuts and shaves',
    answer_b: 'Bloodletting, minor surgery, herbal remedies, and tooth extractions',
    answer_c: 'Major operations and autopsies',
    answer_d: 'Childbirth assistance and midwifery',
    correct_answer: 'b',
    explanation: 'Beyond grooming, barber-surgeons performed bloodletting, minor surgical procedures, herbal remedies, and tooth extractions.',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-1-015',
    quiz_id: 'quiz-1',
    question: 'What happened at the Council of Tours in 1163 that affected barbers?',
    answer_a: 'Barbers were granted medical licenses',
    answer_b: 'The Pope forbade clergy from practicing medicine, transferring duties to barbers',
    answer_c: 'The first barber school was established',
    answer_d: 'Barbers were banned from performing surgery',
    correct_answer: 'b',
    explanation: 'The Pope forbade clergy from practicing medicine or surgery, transferring those duties to barbers who already handled blades.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-1-016',
    quiz_id: 'quiz-1',
    question: 'When did surgeons officially separate from barbers, ending the barber-surgeon era?',
    answer_a: '1540',
    answer_b: '1605',
    answer_c: '1745',
    answer_d: '1897',
    correct_answer: 'c',
    explanation: 'The complete separation occurred in 1745, when surgeons formally split from barbers to establish independent medical practice.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-1-017',
    quiz_id: 'quiz-1',
    question: 'What do the three colors of the barber pole represent?',
    answer_a: 'Red, white, and blue for the American flag',
    answer_b: 'Red for blood, white for bandages, blue for veins',
    answer_c: 'Red for fire, white for purity, blue for water',
    answer_d: 'Red for courage, white for peace, blue for loyalty',
    correct_answer: 'b',
    explanation: 'Red represents blood, white represents bandages, and blue represents veins — all originating from bloodletting practices.',
    difficulty: 'easy',
    order_index: 17,
  },
  {
    id: 'qq-1-018',
    quiz_id: 'quiz-1',
    question: 'When and where were the earliest scissors developed?',
    answer_a: 'Ancient Rome, 500 BC',
    answer_b: 'The Middle East, between 3000 and 2000 BC',
    answer_c: 'China, during the Han Dynasty',
    answer_d: 'Medieval Europe, 1200 AD',
    correct_answer: 'b',
    explanation: 'The Middle East produced the earliest scissors between 3000 and 2000 BC, revolutionizing hair cutting precision.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-1-019',
    quiz_id: 'quiz-1',
    question: 'Who invented the first practical electric hair clippers, and in what year?',
    answer_a: 'Matthew Andis in 1921',
    answer_b: 'John Oster in 1928',
    answer_c: 'Leo J. Wahl in 1919',
    answer_d: 'Thomas Edison in 1905',
    correct_answer: 'c',
    explanation: 'Leo J. Wahl invented the first practical electric hair clippers in 1919, transforming the barbering industry.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-1-020',
    quiz_id: 'quiz-1',
    question: 'Which three companies dominated early electric clipper manufacturing?',
    answer_a: 'Gillette, Remington, and Philips',
    answer_b: 'Wahl, Andis, and Oster',
    answer_c: 'Sears, Montgomery Ward, and Woolworth',
    answer_d: 'General Electric, Westinghouse, and IBM',
    correct_answer: 'b',
    explanation: 'Wahl Clipper Corporation (1921), Andis (developed by Matthew Andis), and Oster (John Oster marketed motorized clippers in 1928) dominated early manufacturing.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'qq-1-021',
    quiz_id: 'quiz-1',
    question: 'When and where was the first barber-licensing law passed?',
    answer_a: 'New York, 1905',
    answer_b: 'Minnesota, 1897',
    answer_c: 'California, 1910',
    answer_d: 'Illinois, 1885',
    correct_answer: 'b',
    explanation: 'Minnesota passed the first barber-licensing law in 1897, establishing standards for sanitation, education, and disinfection.',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-1-022',
    quiz_id: 'quiz-1',
    question: 'What does NABBA stand for, and when was it founded?',
    answer_a: 'National Association of Barbers and Beauticians, founded 1910',
    answer_b: 'National Association of State Boards of Barber Examiners, founded 1929',
    answer_c: 'North American Barber Brotherhood Alliance, founded 1950',
    answer_d: 'National Academy of Barbering and Beauty Arts, founded 1900',
    correct_answer: 'b',
    explanation: 'The National Association of State Boards of Barber Examiners was founded in 1929 and represents over 300,000 barbers.',
    difficulty: 'easy',
    order_index: 22,
  },
  {
    id: 'qq-1-023',
    quiz_id: 'quiz-1',
    question: 'What are the five main objectives of NABBA?',
    answer_a: 'Profit, expansion, marketing, sales, and recruitment',
    answer_b: 'Promote information exchange, establish exam/licensing standards, set curriculum standards, support continuing education, and protect consumers',
    answer_c: 'Political lobbying, union organization, strike coordination, wage negotiation, and benefits management',
    answer_d: 'Product development, tool manufacturing, school accreditation, advertising, and trade shows',
    correct_answer: 'b',
    explanation: 'NABBA promotes information exchange, establishes exam/licensing standards, sets curriculum standards, supports continuing education, and protects consumers.',
    difficulty: 'hard',
    order_index: 23,
  },
  {
    id: 'qq-1-024',
    quiz_id: 'quiz-1',
    question: 'What factors caused the decline of barbershops in the 1980s–1990s?',
    answer_a: 'Economic recession and high unemployment',
    answer_b: 'Unisex salons, full-service spas, long hair trends, and cosmetology licensing shifts',
    answer_c: 'Government bans on barbering',
    answer_d: 'Lack of interest among young people',
    correct_answer: 'b',
    explanation: 'Unisex salons, full-service spas, long hair fashion trends, and shifts toward cosmetology licensing reduced traditional barbershop demand.',
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-1-025',
    quiz_id: 'quiz-1',
    question: 'What percentage of barbershop clientele are women in some modern shops?',
    answer_a: 'Approximately 10%',
    answer_b: 'Approximately 30%',
    answer_c: 'Approximately 50%',
    answer_d: 'Less than 5%',
    correct_answer: 'b',
    explanation: 'Women now make up approximately 30% of clientele in some barbershops, with female barbers and students also increasing.',
    difficulty: 'medium',
    order_index: 25,
  },
]

// ───────────────────────────────────────────────
// CHAPTER 2: Life Skills (15 questions from HTML + 10 original)
// ───────────────────────────────────────────────
export const chapter2QuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-2-001',
    quiz_id: 'quiz-2',
    question: 'According to the chapter, what percentage of barber success comes from life and business skills?',
    answer_a: '25%',
    answer_b: '60%',
    answer_c: '40%',
    answer_d: '80%',
    correct_answer: 'b',
    explanation: 'The chapter states that 60% of barber success comes from life and business skills, while 40% comes from technical skills like cutting, styling, and sanitation.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-2-002',
    quiz_id: 'quiz-2',
    question: 'What does the "T" in SMART goals stand for?',
    answer_a: 'Targeted',
    answer_b: 'Tactical',
    answer_c: 'Time-Bound',
    answer_d: 'Trackable',
    correct_answer: 'c',
    explanation: 'The T in SMART stands for Time-Bound — setting a deadline like "By December 31st" creates urgency and focus.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-2-003',
    quiz_id: 'quiz-2',
    question: 'Which of the following is NOT one of the "time traps" mentioned in the chapter?',
    answer_a: '"I\'ll practice later"',
    answer_b: 'Waking up early to plan',
    answer_c: 'Scrolling social media "for just a minute"',
    answer_d: 'Saying yes to everything',
    correct_answer: 'b',
    explanation: 'Waking up early to plan is a positive habit, not a time trap. The chapter lists "I\'ll practice later," social media scrolling, saying yes to everything, and not planning tomorrow as common time traps.',
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-2-004',
    quiz_id: 'quiz-2',
    question: 'What is the recommended duration for focused study blocks using the Pomodoro Technique?',
    answer_a: '25 minutes',
    answer_b: '45 minutes',
    answer_c: '60 minutes',
    answer_d: '90 minutes',
    correct_answer: 'a',
    explanation: 'The Pomodoro Technique recommends 25-minute focused study blocks followed by short breaks.',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-2-005',
    quiz_id: 'quiz-2',
    question: 'Which of the following is a warning sign of burnout?',
    answer_a: 'Arriving early to work',
    answer_b: 'Learning new techniques',
    answer_c: 'Building client relationships',
    answer_d: 'Dreading work',
    correct_answer: 'd',
    explanation: 'Dreading work is a key warning sign of burnout. Other signs include chronic fatigue, irritability with clients, physical aches, and loss of creativity.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-2-006',
    quiz_id: 'quiz-2',
    question: 'According to the 50/30/20 rule, what percentage of income should go to savings and debt?',
    answer_a: '10%',
    answer_b: '30%',
    answer_c: '20%',
    answer_d: '50%',
    correct_answer: 'c',
    explanation: 'The 50/30/20 rule allocates 50% to needs, 30% to wants, and 20% to savings and debt repayment.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-2-007',
    quiz_id: 'quiz-2',
    question: 'What is the first step in breaking a big goal into action steps?',
    answer_a: 'Schedule daily tasks',
    answer_b: 'Write down your big goal',
    answer_c: 'Find a mentor',
    answer_d: 'Set a deadline',
    correct_answer: 'b',
    explanation: 'The first step is to write down your big goal clearly. Example: "Open my own barbershop in 3 years." Then work backward from there.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-2-008',
    quiz_id: 'quiz-2',
    question: 'What is the recommended starting amount for an emergency fund?',
    answer_a: '$1,000',
    answer_b: '$5,000',
    answer_c: '$500',
    answer_d: '$10,000',
    correct_answer: 'a',
    explanation: 'The chapter recommends starting with a $1,000 mini emergency fund, then building to 3 months of expenses, and eventually 6 months.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-2-009',
    quiz_id: 'quiz-2',
    question: 'Which of the following is the best example of a SMART goal?',
    answer_a: '"Get better at cutting hair"',
    answer_b: '"Make more money"',
    answer_c: '"Be the best barber ever"',
    answer_d: '"Complete 100 practice fades by December 31st"',
    correct_answer: 'd',
    explanation: '"Complete 100 practice fades by December 31st" is Specific, Measurable, Achievable, Relevant, and Time-Bound. The other options are vague and lack measurable criteria.',
    difficulty: 'medium',
    order_index: 9,
  },
  {
    id: 'qq-2-010',
    quiz_id: 'quiz-2',
    question: 'What percentage of income should booth renters set aside for taxes?',
    answer_a: '10%',
    answer_b: '25-30%',
    answer_c: '15%',
    answer_d: '5%',
    correct_answer: 'b',
    explanation: 'Booth renters should set aside 25-30% of income for taxes since they are self-employed and responsible for their own tax payments.',
    difficulty: 'medium',
    order_index: 10,
  },
  {
    id: 'qq-2-011',
    quiz_id: 'quiz-2',
    question: 'Which networking approach is most effective according to the chapter?',
    answer_a: 'Only network once you have experience',
    answer_b: 'Ask for favors immediately upon meeting',
    answer_c: 'Give first and build genuine relationships',
    answer_d: 'Only network at formal events',
    correct_answer: 'c',
    explanation: 'The chapter emphasizes giving first — sharing knowledge, making introductions, and offering help before asking for anything — as the foundation of effective networking.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-2-012',
    quiz_id: 'quiz-2',
    question: 'What is the 2-Minute Rule for time management?',
    answer_a: 'If a task takes less than 2 minutes, do it immediately',
    answer_b: 'Take a 2-minute break every hour',
    answer_c: 'Spend 2 minutes planning each morning',
    answer_d: 'Limit social media to 2 minutes per day',
    correct_answer: 'a',
    explanation: 'The 2-Minute Rule states that if a task takes less than 2 minutes, do it immediately rather than letting small tasks pile up.',
    difficulty: 'easy',
    order_index: 12,
  },
  {
    id: 'qq-2-013',
    quiz_id: 'quiz-2',
    question: 'Which is NOT recommended as a way to track study progress?',
    answer_a: 'Progress journal',
    answer_b: 'Visual trackers',
    answer_c: 'Accountability partner',
    answer_d: 'Comparing yourself to others',
    correct_answer: 'd',
    explanation: 'The chapter recommends progress journals, visual trackers, and accountability partners. Comparing yourself to others is not mentioned and can be demotivating.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-2-014',
    quiz_id: 'quiz-2',
    question: 'What should you do every Sunday according to the time management section?',
    answer_a: 'Deep clean your tools',
    answer_b: 'Plan your week ahead',
    answer_c: 'Take the day completely off',
    answer_d: 'Network with other barbers',
    correct_answer: 'b',
    explanation: 'The Sunday Planning Session involves spending 30 minutes mapping out your week so you know your priorities before Monday hits.',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-2-015',
    quiz_id: 'quiz-2',
    question: 'What is the ultimate goal for emergency fund savings?',
    answer_a: '1 month of expenses',
    answer_b: '2 months of expenses',
    answer_c: '6 months of expenses',
    answer_d: '12 months of expenses',
    correct_answer: 'c',
    explanation: 'The ultimate goal is 6 months of expenses saved, though you start with $1,000 and build to 3 months first.',
    difficulty: 'easy',
    order_index: 15,
  },
  {
    id: 'qq-2-016',
    quiz_id: 'quiz-2',
    question: 'Why are life skills equally important as technical skills in barbering?',
    answer_a: 'They are required by state licensing boards',
    answer_b: 'Barbers interact daily with diverse clients and coworkers, requiring strong interpersonal abilities',
    answer_c: 'They replace the need for technical training',
    answer_d: 'Only senior barbers need life skills',
    correct_answer: 'b',
    explanation: 'Barbers interact daily with diverse clients and coworkers. Strong life skills ensure positive interactions, help navigate difficult situations, and build self-esteem needed for career success.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-2-017',
    quiz_id: 'quiz-2',
    question: 'What are three destructive habits that kill productivity?',
    answer_a: 'Overworking, multitasking, and perfectionism',
    answer_b: 'Procrastination, perfectionism, and lack of a game plan',
    answer_c: 'Sleeping too much, eating poorly, and exercising rarely',
    answer_d: 'Talking too much, arriving late, and forgetting appointments',
    correct_answer: 'b',
    explanation: 'Procrastination (putting things off), perfectionism (unhealthy need for flawlessness), and lack of a game plan (no organized goals or direction) are productivity killers.',
    difficulty: 'easy',
    order_index: 17,
  },
  {
    id: 'qq-2-018',
    quiz_id: 'quiz-2',
    question: 'What is the purpose of a personal mission statement?',
    answer_a: 'To impress clients with fancy language',
    answer_b: 'To define your purpose, core values, and professional direction',
    answer_c: 'To replace the need for business cards',
    answer_d: 'To satisfy licensing requirements',
    correct_answer: 'b',
    explanation: 'A mission statement defines your purpose, core values, and direction. It provides focus and becomes the cultural pulse of your professional life.',
    difficulty: 'easy',
    order_index: 18,
  },
  {
    id: 'qq-2-019',
    quiz_id: 'quiz-2',
    question: 'What does diplomacy (tact) mean in professional communication?',
    answer_a: 'Avoiding all difficult conversations',
    answer_b: 'Delivering truthful messages in a kind, respectful manner that preserves relationships',
    answer_c: 'Telling clients exactly what they want to hear',
    answer_d: 'Using formal language exclusively',
    correct_answer: 'b',
    explanation: 'Delivering truthful messages and feedback in a kind, respectful manner that preserves relationships and avoids unnecessary conflict.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-2-020',
    quiz_id: 'quiz-2',
    question: 'Why is continuing education considered an ethical responsibility?',
    answer_a: 'It is only required to renew licenses',
    answer_b: 'Barbers must stay current with techniques, sanitation standards, and industry trends to serve clients competently',
    answer_c: 'Continuing education is optional and not ethically relevant',
    answer_d: 'It is only for barbers who want to teach',
    correct_answer: 'b',
    explanation: 'Participating in continuing education ensures barbers maintain skilled and competent services, which is a core ethical obligation to clients.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'qq-2-021',
    quiz_id: 'quiz-2',
    question: 'What are four key time management strategies for barbers?',
    answer_a: 'Work faster, skip breaks, multitask constantly, and take every walk-in',
    answer_b: 'Prioritize tasks, create schedules, learn to say no, and use planning tools',
    answer_c: 'Arrive late, leave early, ignore appointments, and avoid lists',
    answer_d: 'Only serve regular clients, refuse new business, and work weekends only',
    correct_answer: 'b',
    explanation: 'Prioritize tasks by importance, create flexible daily/weekly schedules, learn to say no kindly to avoid overcommitment, and use lists or digital planning tools.',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-2-022',
    quiz_id: 'quiz-2',
    question: 'Name four memory and study techniques useful for barber students.',
    answer_a: 'Cramming, guessing, skipping hard topics, and copying notes',
    answer_b: 'Repetition, organization, mnemonics, and mind mapping',
    answer_c: 'Sleeping with textbooks, listening to loud music, studying alone, and avoiding practice',
    answer_d: 'Memorizing only, ignoring hands-on training, avoiding review, and skipping quizzes',
    correct_answer: 'b',
    explanation: 'Repetition (verbal, written, hands-on), organization (breaking topics into segments), mnemonics (acronyms, word associations), and mind mapping (visual branching from central topics).',
    difficulty: 'easy',
    order_index: 22,
  },
  {
    id: 'qq-2-023',
    quiz_id: 'quiz-2',
    question: 'What is the difference between short-term and long-term goals?',
    answer_a: 'Short-term goals are less important than long-term goals',
    answer_b: 'Short-term goals take one year or less; long-term goals span two or more years',
    answer_c: 'Only long-term goals need to be written down',
    answer_d: 'Short-term goals require no planning',
    correct_answer: 'b',
    explanation: 'Short-term goals take one year or less to achieve (passing an exam, graduating). Long-term goals span two or more years (owning a shop in five years).',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'qq-2-024',
    quiz_id: 'quiz-2',
    question: 'How can visualization help achieve professional success?',
    answer_a: 'It replaces the need for actual practice',
    answer_b: 'It reinforces positive beliefs, builds confidence, and programs the mind for achievement',
    answer_c: 'It guarantees clients will book appointments',
    answer_d: 'It is only useful for athletes, not barbers',
    correct_answer: 'b',
    explanation: 'Regularly imagining yourself working competently in your ideal barbershop reinforces positive beliefs, builds confidence, and programs your mind for achievement.',
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-2-025',
    quiz_id: 'quiz-2',
    question: 'Why is emotional stability important for barbers?',
    answer_a: 'It helps barbers win arguments with clients',
    answer_b: 'Barbers encounter diverse personalities; emotional stability ensures calm, professional responses',
    answer_c: 'It eliminates the need for breaks during the workday',
    answer_d: 'Only managers need emotional stability',
    correct_answer: 'b',
    explanation: 'Barbers encounter diverse personalities and occasional confrontations. Emotional stability ensures professional, calm responses rather than reactive behavior.',
    difficulty: 'medium',
    order_index: 25,
  },
  // NEW: Communication Skills
  {
    id: 'qq-2-026',
    quiz_id: 'quiz-2',
    question: 'What is the most important rule of the client consultation?',
    answer_a: 'Cut quickly to save time',
    answer_b: 'Confirm understanding before cutting',
    answer_c: 'Let the client watch in the mirror',
    answer_d: 'Use technical terms to sound professional',
    correct_answer: 'b',
    explanation: 'Always repeat back what the client wants and get their approval before picking up any tool. This prevents misunderstandings and builds trust.',
    difficulty: 'easy',
    order_index: 26,
  },
  {
    id: 'qq-2-027',
    quiz_id: 'quiz-2',
    question: 'Why should barbers ask open-ended questions during consultations?',
    answer_a: 'They are faster than yes/no questions',
    answer_b: 'They reveal the full picture of what the client wants',
    answer_c: 'They impress clients with vocabulary',
    answer_d: 'They are required by law',
    correct_answer: 'b',
    explanation: 'Open-ended questions like "What look are you going for?" reveal the full picture, while yes/no questions limit understanding and can lead to mistakes.',
    difficulty: 'medium',
    order_index: 27,
  },
  {
    id: 'qq-2-028',
    quiz_id: 'quiz-2',
    question: 'Which of the following is a common communication mistake barbers should avoid?',
    answer_a: 'Asking clarifying questions',
    answer_b: 'Assuming you know what the client wants without asking',
    answer_c: 'Using reference photos',
    answer_d: 'Confirming the plan before cutting',
    correct_answer: 'b',
    explanation: 'Assuming you know what the client wants without asking is a major cause of dissatisfaction. Always ask, listen, and confirm before cutting.',
    difficulty: 'easy',
    order_index: 28,
  },
  // NEW: Professional Ethics
  {
    id: 'qq-2-029',
    quiz_id: 'quiz-2',
    question: 'What is the ethical rule regarding product recommendations to clients?',
    answer_a: 'Recommend the most expensive products to increase revenue',
    answer_b: 'Only recommend products that genuinely help the client',
    answer_c: 'Never recommend products to avoid seeming pushy',
    answer_d: 'Let clients choose products without guidance',
    correct_answer: 'b',
    explanation: 'Recommending unnecessary products destroys trust. Ethical barbers only suggest products that genuinely benefit the client.',
    difficulty: 'easy',
    order_index: 29,
  },
  {
    id: 'qq-2-030',
    quiz_id: 'quiz-2',
    question: 'Why is client confidentiality important in barbering?',
    answer_a: 'It is only important for celebrity clients',
    answer_b: 'Clients share personal information in the chair and trust barbers to protect it',
    answer_c: 'It is not important in casual barbershop conversation',
    answer_d: 'Only applies to medical information',
    correct_answer: 'b',
    explanation: 'Clients share personal details during services. Protecting their privacy builds trust and is a core ethical obligation.',
    difficulty: 'easy',
    order_index: 30,
  },
  {
    id: 'qq-2-031',
    quiz_id: 'quiz-2',
    question: 'How does continuing education relate to professional ethics?',
    answer_a: 'It is only required for license renewal',
    answer_b: 'Barbers have an ethical duty to stay current with techniques and standards',
    answer_c: 'It is optional and not ethically relevant',
    answer_d: 'Only barbers who want to teach need continuing education',
    correct_answer: 'b',
    explanation: 'Participating in continuing education ensures barbers maintain competent services, which is a core ethical obligation to clients.',
    difficulty: 'medium',
    order_index: 31,
  },
  // NEW: Conflict Resolution
  {
    id: 'qq-2-032',
    quiz_id: 'quiz-2',
    question: 'What is the first step in the complaint recovery system?',
    answer_a: 'Offer a refund immediately',
    answer_b: 'Listen without defending',
    answer_c: 'Explain why the mistake happened',
    answer_d: 'Ask the client to leave',
    correct_answer: 'b',
    explanation: 'The first step is to listen fully without interrupting or defending. Let the client express their concerns completely.',
    difficulty: 'easy',
    order_index: 32,
  },
  {
    id: 'qq-2-033',
    quiz_id: 'quiz-2',
    question: 'What is the service recovery paradox?',
    answer_a: 'Clients who complain are always lost forever',
    answer_b: 'Clients whose problems are resolved well often become more loyal than those who never had problems',
    answer_c: 'It is cheaper to lose a client than to fix a mistake',
    answer_d: 'Complaints should be ignored to avoid liability',
    correct_answer: 'b',
    explanation: 'The service recovery paradox states that clients whose problems are resolved professionally often become MORE loyal than clients who never experienced issues.',
    difficulty: 'medium',
    order_index: 33,
  },
  {
    id: 'qq-2-034',
    quiz_id: 'quiz-2',
    question: 'When handling a client complaint, what should you avoid saying?',
    answer_a: '"I understand why you are disappointed"',
    answer_b: '"You said you wanted it this way"',
    answer_c: '"Let me fix this for you"',
    answer_d: '"I apologize for the misunderstanding"',
    correct_answer: 'b',
    explanation: 'Blaming the client with phrases like "You said..." escalates tension. Instead, take responsibility and focus on solutions.',
    difficulty: 'medium',
    order_index: 34,
  },
  // NEW: Success Mindset
  {
    id: 'qq-2-035',
    quiz_id: 'quiz-2',
    question: 'What is the key difference between motivation and discipline?',
    answer_a: 'Motivation is permanent; discipline is temporary',
    answer_b: 'Motivation is a feeling; discipline is a habit system that works without feelings',
    answer_c: 'They are the same thing',
    answer_d: 'Discipline is only needed for athletes',
    correct_answer: 'b',
    explanation: 'Motivation is temporary excitement. Discipline is the habit system that keeps you going even when motivation fades.',
    difficulty: 'medium',
    order_index: 35,
  },
  {
    id: 'qq-2-036',
    quiz_id: 'quiz-2',
    question: 'Why is consistency more important than intensity for skill development?',
    answer_a: 'Intense practice is always harmful',
    answer_b: 'Small daily efforts compound into mastery over time',
    answer_c: 'Consistency requires less effort',
    answer_d: 'Intense practice does not build muscle memory',
    correct_answer: 'b',
    explanation: 'Practicing 30 minutes daily builds muscle memory and habits better than occasional marathon sessions. Small repeated efforts compound.',
    difficulty: 'easy',
    order_index: 36,
  },
  {
    id: 'qq-2-037',
    quiz_id: 'quiz-2',
    question: 'How should barbers view mistakes and setbacks?',
    answer_a: 'As proof they should quit',
    answer_b: 'As data and feedback for improvement',
    answer_c: 'As something to hide from others',
    answer_d: 'As evidence of lack of talent',
    correct_answer: 'b',
    explanation: 'Mistakes are learning data. Analyze what went wrong, adjust, and try again. Every master barber has thousands of learning cuts behind them.',
    difficulty: 'easy',
    order_index: 37,
  },
  // NEW: Cultural Competence
  {
    id: 'qq-2-038',
    quiz_id: 'quiz-2',
    question: 'What does cultural competence mean in barbering?',
    answer_a: 'Knowing every culture in detail',
    answer_b: 'Approaching every client with curiosity, respect, and willingness to learn',
    answer_c: 'Only serving clients from your own culture',
    answer_d: 'Avoiding clients from different backgrounds',
    correct_answer: 'b',
    explanation: 'Cultural competence means approaching every client with curiosity, respect, and a willingness to learn about their unique needs and preferences.',
    difficulty: 'easy',
    order_index: 38,
  },
  {
    id: 'qq-2-039',
    quiz_id: 'quiz-2',
    question: 'Why should barbers avoid making assumptions about clients?',
    answer_a: 'Assumptions save time',
    answer_b: 'Assumptions based on appearance lead to mistakes and offense',
    answer_c: 'Clients prefer assumptions',
    answer_d: 'Assumptions are always correct',
    correct_answer: 'b',
    explanation: 'Assumptions based on appearance often lead to errors and can offend clients. Ask respectful questions and let them guide the service.',
    difficulty: 'easy',
    order_index: 39,
  },
  // NEW: Career Planning & Leadership
  {
    id: 'qq-2-040',
    quiz_id: 'quiz-2',
    question: 'What should be a barber\'s primary focus in Year 1 of their career?',
    answer_a: 'Opening multiple locations',
    answer_b: 'Getting licensed, building clientele, and mastering core cuts',
    answer_c: 'Hiring employees',
    answer_d: 'Becoming a social media influencer',
    correct_answer: 'b',
    explanation: 'Year 1 focus: get licensed, build 50+ regular clients, master 5 core cuts, save 3 months of expenses, and create a professional portfolio.',
    difficulty: 'easy',
    order_index: 40,
  },
  {
    id: 'qq-2-041',
    quiz_id: 'quiz-2',
    question: 'What is the most important rule of shop etiquette regarding clients?',
    answer_a: 'Accept every walk-in regardless of whose regular client they are',
    answer_b: 'Never poach another barber\'s regular clients',
    answer_c: 'Only serve your own regulars',
    answer_d: 'Encourage clients to switch barbers frequently',
    correct_answer: 'b',
    explanation: 'Never solicit another barber\'s regular clients. If their client asks you for a cut, redirect them back to their regular barber.',
    difficulty: 'easy',
    order_index: 41,
  },
  {
    id: 'qq-2-042',
    quiz_id: 'quiz-2',
    question: 'What should barbers do on high-volume, stressful days?',
    answer_a: 'Rush through cuts to serve more clients',
    answer_b: 'Stay calm, focus on one client at a time, and support coworkers',
    answer_c: 'Refuse new clients',
    answer_d: 'Take a long break',
    correct_answer: 'b',
    explanation: 'On busy days, stay calm, focus on quality over speed, communicate wait times, and support your team. Rushing leads to mistakes.',
    difficulty: 'easy',
    order_index: 42,
  },
  {
    id: 'qq-2-043',
    quiz_id: 'quiz-2',
    question: 'Why is mentorship valuable for experienced barbers?',
    answer_a: 'It is only valuable for the student',
    answer_b: 'Teaching others often reinforces the mentor\'s own knowledge and builds legacy',
    answer_c: 'It is a waste of time',
    answer_d: 'It is only for barbers who want to teach full-time',
    correct_answer: 'b',
    explanation: 'Mentorship lifts the entire industry and often teaches the mentor as much as the student. The barber who teaches builds an empire.',
    difficulty: 'medium',
    order_index: 43,
  },
  {
    id: 'qq-2-044',
    quiz_id: 'quiz-2',
    question: 'What does it mean to leave the shop cleaner than you found it?',
    answer_a: 'Hire a cleaning service',
    answer_b: 'Take personal responsibility for your station and shared spaces',
    answer_c: 'Only clean your own chair',
    answer_d: 'Leave cleaning for the end of the week',
    correct_answer: 'b',
    explanation: 'Clean your station after every cut, wipe shared spaces, organize tools, and take responsibility for the overall shop environment.',
    difficulty: 'easy',
    order_index: 44,
  },
]

// ───────────────────────────────────────────────
// CHAPTER 3: Professional Image (15 questions)
// ───────────────────────────────────────────────
export const chapter3QuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-3-001',
    quiz_id: 'quiz-3',
    question: 'How long do clients typically take to form a first impression of you?',
    answer_a: '30 seconds',
    answer_b: '7 seconds',
    answer_c: '2 minutes',
    answer_d: '5 minutes',
    correct_answer: 'b',
    explanation: 'Clients decide if they trust you within the first 7 seconds. A clean, professional appearance signals competence and attention to detail.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-3-002',
    quiz_id: 'quiz-3',
    question: 'Why should barbers avoid wearing strong cologne or perfume?',
    answer_a: 'It\'s too expensive',
    answer_b: 'It can trigger allergies and overwhelm clients',
    answer_c: 'It interferes with hair products',
    answer_d: 'It\'s against the law',
    correct_answer: 'b',
    explanation: 'Heavy cologne, perfume, or aftershave can trigger allergies and overwhelm clients in close quarters. Use lightly scented or unscented products.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-3-003',
    quiz_id: 'quiz-3',
    question: 'What is the most important reason for maintaining professional dress standards?',
    answer_a: 'To follow fashion trends',
    answer_b: 'To build client trust and credibility',
    answer_c: 'To impress coworkers',
    answer_d: 'To meet legal requirements',
    correct_answer: 'b',
    explanation: 'Professional dress builds client trust and credibility. You are your own walking advertisement, and a polished image encourages referrals.',
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-3-004',
    quiz_id: 'quiz-3',
    question: 'Which of the following is a key principle of workplace ergonomics for barbers?',
    answer_a: 'Always stand in one position',
    answer_b: 'Adjust chair height so client\'s head is at elbow level',
    answer_c: 'Use the heaviest tools available',
    answer_d: 'Work as fast as possible',
    correct_answer: 'b',
    explanation: 'Adjusting chair height so the client\'s head is at your elbow level prevents strain and allows for proper posture during services.',
    difficulty: 'medium',
    order_index: 4,
  },
  {
    id: 'qq-3-005',
    quiz_id: 'quiz-3',
    question: 'What is carpal tunnel syndrome commonly caused by in barbering?',
    answer_a: 'Standing too long',
    answer_b: 'Repetitive clipper and shear use',
    answer_c: 'Talking to clients',
    answer_d: 'Using too much product',
    correct_answer: 'b',
    explanation: 'Carpal tunnel syndrome is caused by repetitive clipper and shear use. Take breaks, stretch wrists, and use ergonomic tools to prevent it.',
    difficulty: 'medium',
    order_index: 5,
  },
  {
    id: 'qq-3-006',
    quiz_id: 'quiz-3',
    question: 'Which stress management technique can be used between clients?',
    answer_a: 'Deep breathing for 4 counts',
    answer_b: 'Taking a 2-hour nap',
    answer_c: 'Going for a run',
    answer_d: 'Calling in sick',
    correct_answer: 'a',
    explanation: 'Deep breathing (4 counts in, hold, out, hold) is a quick in-the-moment technique that can be used between clients to reset.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-3-007',
    quiz_id: 'quiz-3',
    question: 'What should you do if a client is unhappy with their haircut?',
    answer_a: 'Defend your work',
    answer_b: 'Stay calm, listen, and offer to fix it',
    answer_c: 'Tell them they\'re wrong',
    answer_d: 'Charge them extra',
    correct_answer: 'b',
    explanation: 'Stay calm, listen without defending, apologize sincerely, and offer a solution. "I\'m sorry you\'re not happy. Let me fix this for you right now."',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-3-008',
    quiz_id: 'quiz-3',
    question: 'Why is it important to get client permission before posting their photo on social media?',
    answer_a: 'It\'s legally required and respects their privacy',
    answer_b: 'It takes too much time otherwise',
    answer_c: 'Photos don\'t get likes without permission',
    answer_d: 'It\'s only important for celebrities',
    correct_answer: 'a',
    explanation: 'Getting client permission is legally required and respects their privacy. Posting without consent can damage trust and reputation.',
    difficulty: 'medium',
    order_index: 8,
  },
  {
    id: 'qq-3-009',
    quiz_id: 'quiz-3',
    question: 'What is the best footwear choice for a barber?',
    answer_a: 'Flip-flops for easy cleaning',
    answer_b: 'Closed-toe shoes with cushioning and support',
    answer_c: 'High heels for style',
    answer_d: 'Barefoot for better grip',
    correct_answer: 'b',
    explanation: 'Closed-toe shoes with cushioning and support protect feet from dropped tools and hair clippings while providing comfort for long hours of standing.',
    difficulty: 'easy',
    order_index: 9,
  },
  {
    id: 'qq-3-010',
    quiz_id: 'quiz-3',
    question: 'Which of the following demonstrates active listening during a consultation?',
    answer_a: 'Interrupting to give advice',
    answer_b: 'Maintaining eye contact and asking clarifying questions',
    answer_c: 'Checking your phone',
    answer_d: 'Thinking about your next client',
    correct_answer: 'b',
    explanation: 'Active listening involves maintaining eye contact, nodding, giving verbal acknowledgments, not interrupting, and asking clarifying questions.',
    difficulty: 'easy',
    order_index: 10,
  },
  {
    id: 'qq-3-011',
    quiz_id: 'quiz-3',
    question: 'What is a warning sign of burnout?',
    answer_a: 'Feeling energized at work',
    answer_b: 'Chronic fatigue and irritability',
    answer_c: 'Getting lots of referrals',
    answer_d: 'Learning new techniques',
    correct_answer: 'b',
    explanation: 'Warning signs of burnout include chronic fatigue, irritability, feeling detached, loss of enjoyment, and anxiety. Take them seriously.',
    difficulty: 'easy',
    order_index: 11,
  },
  {
    id: 'qq-3-012',
    quiz_id: 'quiz-3',
    question: 'Why should barbers keep their nails trimmed short?',
    answer_a: 'Long nails look better',
    answer_b: 'Long nails harbor bacteria and can scratch clients',
    answer_c: 'Short nails are required by law',
    answer_d: 'Clients prefer long nails on barbers',
    correct_answer: 'b',
    explanation: 'Long nails harbor bacteria and can scratch clients. Keep nails trimmed short and clean under them thoroughly.',
    difficulty: 'easy',
    order_index: 12,
  },
  {
    id: 'qq-3-013',
    quiz_id: 'quiz-3',
    question: 'What is the purpose of an anti-fatigue mat?',
    answer_a: 'To decorate the shop',
    answer_b: 'To reduce leg and back strain from standing',
    answer_c: 'To catch hair clippings',
    answer_d: 'To make the floor slippery',
    correct_answer: 'b',
    explanation: 'Anti-fatigue mats provide cushioned flooring that reduces leg and back strain from standing for long periods.',
    difficulty: 'easy',
    order_index: 13,
  },
  {
    id: 'qq-3-014',
    quiz_id: 'quiz-3',
    question: 'When consulting with a client, what type of questions should you ask?',
    answer_a: 'Yes/no questions only',
    answer_b: 'Open-ended questions to understand their desires',
    answer_c: 'Personal questions about their income',
    answer_d: 'No questions — just start cutting',
    correct_answer: 'b',
    explanation: 'Open-ended questions like "What are we doing today?" and "How do you want to look?" help you understand the client\'s desires.',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-3-015',
    quiz_id: 'quiz-3',
    question: 'What should you consider before posting anything on social media as a professional barber?',
    answer_a: 'How many likes it will get',
    answer_b: 'Whether you\'d want your best client to see it',
    answer_c: 'What time of day it is',
    answer_d: 'How funny your friends will find it',
    correct_answer: 'b',
    explanation: 'Ask: "Would I want my grandmother, my boss, and my best client to see this?" If no, don\'t post it.',
    difficulty: 'easy',
    order_index: 15,
  },
  // ============================================================
  // NEW QUIZ QUESTIONS: Posture & Body Alignment
  // ============================================================
  {
    id: 'qq-3-016',
    quiz_id: 'quiz-3',
    question: 'What is the correct head position for proper standing posture while barbering?',
    answer_a: 'Head down, looking at the floor',
    answer_b: 'Head up with chin parallel to the floor',
    answer_c: 'Head tilted to one side',
    answer_d: 'Chin jutted forward toward the client',
    correct_answer: 'b',
    explanation: 'Keep head up with chin parallel to the floor. Avoid jutting the chin forward or looking down for extended periods.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-3-017',
    quiz_id: 'quiz-3',
    question: 'What is the recommended maximum arm angle when raising arms during barbering services?',
    answer_a: '90 degrees',
    answer_b: '60 degrees or less',
    answer_c: '120 degrees',
    answer_d: '45 degrees',
    correct_answer: 'b',
    explanation: 'Keep arms at 60 degrees or less when raised away from the body to reduce shoulder strain and prevent fatigue.',
    difficulty: 'medium',
    order_index: 17,
  },
  {
    id: 'qq-3-018',
    quiz_id: 'quiz-3',
    question: 'Which of the following is NOT one of the four common posture problems?',
    answer_a: 'Hunchback',
    answer_b: 'Swayback',
    answer_c: 'Flat back',
    answer_d: 'Twisted spine',
    correct_answer: 'd',
    explanation: 'The four common posture problems are hunchback (rounded upper back), swayback (excessive lower back curve), flat back (lost natural curves), and combined hunchback-swayback.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-3-019',
    quiz_id: 'quiz-3',
    question: 'What is the correct sitting posture for barbers?',
    answer_a: 'Slouching with weight on the tailbone',
    answer_b: 'Hips level, knees over feet, back straight, weight on thigh bones',
    answer_c: 'Crossing legs for extended periods',
    answer_d: 'Leaning forward with rounded shoulders',
    correct_answer: 'b',
    explanation: 'Hips level, knees flexed slightly over feet, back straight with weight on thigh bones (not tailbone), feet flat on floor, and arms at 90-degree angle when working.',
    difficulty: 'medium',
    order_index: 19,
  },
  // ============================================================
  // NEW QUIZ QUESTIONS: Stress-Relief Exercises
  // ============================================================
  {
    id: 'qq-3-020',
    quiz_id: 'quiz-3',
    question: 'How long should you hold each position in the wrist stretch exercise?',
    answer_a: '2 seconds',
    answer_b: '5 seconds',
    answer_c: '10 seconds',
    answer_d: '15 seconds',
    correct_answer: 'b',
    explanation: 'Bend wrists upward and hold for 5 seconds, then bend downward and hold for 5 seconds. Repeat 5 complete cycles.',
    difficulty: 'easy',
    order_index: 20,
  },
  {
    id: 'qq-3-021',
    quiz_id: 'quiz-3',
    question: 'What equipment is recommended for the finger grip exercise?',
    answer_a: 'A dumbbell',
    answer_b: 'A tennis ball or tension ball',
    answer_c: 'A resistance band',
    answer_d: 'A water bottle',
    correct_answer: 'b',
    explanation: 'Squeeze a tennis ball or tension ball tightly for 5 counts, then release. Repeat 5 times per hand.',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-3-022',
    quiz_id: 'quiz-3',
    question: 'How often should shoulder roll exercises be performed during a workday?',
    answer_a: 'Once per day',
    answer_b: 'Hourly',
    answer_c: 'Only when pain occurs',
    answer_d: 'Once per week',
    correct_answer: 'b',
    explanation: 'Perform shoulder rolls hourly to release tension from holding arms raised during cuts. Shrug up, roll back, hold, roll forward, hold.',
    difficulty: 'easy',
    order_index: 22,
  },
  // ============================================================
  // NEW QUIZ QUESTIONS: Good Manners & Mannerisms
  // ============================================================
  {
    id: 'qq-3-023',
    quiz_id: 'quiz-3',
    question: 'Why is gum chewing considered unprofessional in barbering?',
    answer_a: 'It is too expensive',
    answer_b: 'It distracts clients, affects speech clarity, and looks careless',
    answer_c: 'It is illegal in barbershops',
    answer_d: 'Clients prefer barbers who chew gum',
    correct_answer: 'b',
    explanation: 'Gum chewing is universally unprofessional in service industries. It distracts clients, affects speech clarity, and looks careless.',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'qq-3-024',
    quiz_id: 'quiz-3',
    question: 'What should a barber do when needing to yawn during a service?',
    answer_a: 'Yawn openly in front of the client',
    answer_b: 'Turn away and cover with hand or elbow',
    answer_c: 'Ignore it and continue working',
    answer_d: 'Apologize repeatedly',
    correct_answer: 'b',
    explanation: 'Turn away from the client and cover with your hand or elbow. Excuse yourself briefly if needed. Never yawn directly in front of a client.',
    difficulty: 'easy',
    order_index: 24,
  },
  {
    id: 'qq-3-025',
    quiz_id: 'quiz-3',
    question: 'Which nervous habit should barbers avoid during services?',
    answer_a: 'Smiling at clients',
    answer_b: 'Tapping feet or fidgeting with tools',
    answer_c: 'Maintaining eye contact',
    answer_d: 'Asking clarifying questions',
    correct_answer: 'b',
    explanation: 'Tapping feet, playing with hair, fidgeting with tools, and other nervous habits signal anxiety and distract from your professionalism.',
    difficulty: 'easy',
    order_index: 25,
  },
  // ============================================================
  // NEW QUIZ QUESTIONS: Communication Framework
  // ============================================================
  {
    id: 'qq-3-026',
    quiz_id: 'quiz-3',
    question: 'What are the three steps of the communication framework?',
    answer_a: 'Talk, cut, finish',
    answer_b: 'Organize, clarify, repeat',
    answer_c: 'Greet, consult, charge',
    answer_d: 'Listen, nod, agree',
    correct_answer: 'b',
    explanation: 'The three-step framework is: 1) Organize your thoughts, 2) Clarify the client\'s terminology, 3) Repeat your interpretation for confirmation.',
    difficulty: 'medium',
    order_index: 26,
  },
  {
    id: 'qq-3-027',
    quiz_id: 'quiz-3',
    question: 'Why is the "repeat for confirmation" step critical?',
    answer_a: 'It speeds up the service',
    answer_b: 'It prevents misunderstandings before cutting',
    answer_c: 'It impresses clients with vocabulary',
    answer_d: 'It is required by law',
    correct_answer: 'b',
    explanation: 'Restating your interpretation gives the client a chance to correct misunderstandings before you begin. It prevents the #1 cause of client dissatisfaction.',
    difficulty: 'medium',
    order_index: 27,
  },
  {
    id: 'qq-3-028',
    quiz_id: 'quiz-3',
    question: 'In the "clarify" step, what should you do when a client says "over the ears"?',
    answer_a: 'Assume they want it cut around the ears',
    answer_b: 'Ask if they mean covering the tops or cut around',
    answer_c: 'Ignore the detail and cut as you prefer',
    answer_d: 'Tell them to use different words',
    correct_answer: 'b',
    explanation: 'Ensure you understand the client\'s specific terminology. Ask follow-up questions until you can visualize exactly what they want. Never assume.',
    difficulty: 'easy',
    order_index: 28,
  },
  // ============================================================
  // NEW QUIZ QUESTIONS: Conversation Guidelines & Confidentiality
  // ============================================================
  {
    id: 'qq-3-029',
    quiz_id: 'quiz-3',
    question: 'Which conversation topic should be avoided in the barbershop?',
    answer_a: 'Sports',
    answer_b: 'Religion',
    answer_c: 'Movies',
    answer_d: 'Food recommendations',
    correct_answer: 'b',
    explanation: 'Religion, politics, personal problems, and gossip about other clients or coworkers should be avoided. These create division and discomfort.',
    difficulty: 'easy',
    order_index: 29,
  },
  {
    id: 'qq-3-030',
    quiz_id: 'quiz-3',
    question: 'What personal information should never be discussed with coworkers?',
    answer_a: 'Favorite sports teams',
    answer_b: 'Personal wages, tips, rent, or tax information',
    answer_c: 'Weekend plans',
    answer_d: 'Client hair preferences',
    correct_answer: 'b',
    explanation: 'Never discuss personal wages, tips, rent, or tax information with coworkers. These topics create resentment and violate professional boundaries.',
    difficulty: 'easy',
    order_index: 30,
  },
  {
    id: 'qq-3-031',
    quiz_id: 'quiz-3',
    question: 'What is the confidentiality rule in barbering?',
    answer_a: 'Share client stories to build rapport with others',
    answer_b: 'What happens in the chair stays in the chair',
    answer_c: 'Only discuss clients with your manager',
    answer_d: 'Post client photos without asking',
    correct_answer: 'b',
    explanation: 'Never repeat what one client tells you to another person. What happens in the chair stays in the chair. Protect client privacy at all times.',
    difficulty: 'easy',
    order_index: 31,
  },
  {
    id: 'qq-3-032',
    quiz_id: 'quiz-3',
    question: 'How should you handle a client who prefers quiet during their service?',
    answer_a: 'Talk more to make them comfortable',
    answer_b: 'Respect their preference and keep conversation minimal',
    answer_c: 'Ask them why they are quiet',
    answer_d: 'Tell them conversation is part of the service',
    correct_answer: 'b',
    explanation: 'Some clients want conversation; others want quiet. Pay attention to cues like short answers and closed eyes. Respect their preference.',
    difficulty: 'easy',
    order_index: 32,
  },
  // ============================================================
  // NEW QUIZ QUESTIONS: Social Media Best Practices
  // ============================================================
  {
    id: 'qq-3-033',
    quiz_id: 'quiz-3',
    question: 'Which of the following is a social media DON\'T for professional barbers?',
    answer_a: 'Posting helpful tips and content',
    answer_b: 'Using profanity in posts',
    answer_c: 'Engaging professionally with comments',
    answer_d: 'Building community with peers',
    correct_answer: 'b',
    explanation: 'Profane language diminishes your professional image instantly. Keep all public communication clean and respectful.',
    difficulty: 'easy',
    order_index: 33,
  },
  {
    id: 'qq-3-034',
    quiz_id: 'quiz-3',
    question: 'Why should barbers avoid online arguments?',
    answer_a: 'They are fun and engaging',
    answer_b: 'They damage professional reputation and create negativity',
    answer_c: 'They attract more followers',
    answer_d: 'They are required by social media platforms',
    correct_answer: 'b',
    explanation: 'Never participate in or entertain arguments online. If someone posts something negative, respond calmly or not at all. Your reputation is your brand.',
    difficulty: 'easy',
    order_index: 34,
  },
  {
    id: 'qq-3-035',
    quiz_id: 'quiz-3',
    question: 'Why should wristwatches be waterproof for barbers?',
    answer_a: 'Waterproof watches look more professional',
    answer_b: 'Barbers work with water, chemicals, and sanitizing solutions',
    answer_c: 'Clients prefer waterproof watches',
    answer_d: 'It is required by OSHA',
    correct_answer: 'b',
    explanation: 'Wristwatches should be waterproof because barbers work with water, chemicals, and sanitizing solutions that can damage non-waterproof watches.',
    difficulty: 'easy',
    order_index: 35,
  },
  {
    id: 'qq-3-036',
    quiz_id: 'quiz-3',
    question: 'Why should makeup be applied before arriving at work, not at the station?',
    answer_a: 'It takes too long to apply at the station',
    answer_b: 'Applying makeup at the station is unprofessional and shows poor time management',
    answer_c: 'Clients do not like makeup',
    answer_d: 'It is against shop policy',
    correct_answer: 'b',
    explanation: 'Applying makeup at the work station is unprofessional and indicates poor time management. It should be done before arriving so you are ready to serve clients.',
    difficulty: 'easy',
    order_index: 36,
  },
]

// ───────────────────────────────────────────────
// Export all quiz questions by chapter
// ───────────────────────────────────────────────
export const allQuizQuestions: Record<string, QuizQuestion[]> = {
  'quiz-1': chapter1QuizQuestions,
  'quiz-2': chapter2QuizQuestions,
  'quiz-3': chapter3QuizQuestions,
}
