// Quiz questions for Barber Study Pro V2
// Generated from flashcard content — each question maps to a flashcard concept
// Original wording, board-exam aligned, educational quality

import { QuizQuestion } from '@/types'

// ───────────────────────────────────────────────
// CHAPTER 1: History of Barbering (25 questions)
// ───────────────────────────────────────────────
export const chapter1QuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-1-001',
    quiz_id: 'quiz-1',
    question: 'What natural materials did early humans use for cutting hair during the Glacial Age?',
    answer_a: 'Metal blades and combs',
    answer_b: 'Sharpened flints, oyster shells, bone fragments, and animal sinew',
    answer_c: 'Bronze knives and wooden picks',
    answer_d: 'Glass shards and leather strips',
    correct_answer: 'b',
    explanation: 'Early humans fashioned rudimentary tools from sharpened flints, oyster shells, bone fragments, and animal sinew for cutting and styling hair.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-1-002',
    quiz_id: 'quiz-1',
    question: 'What was the Egyptian term for barbers, and what social status did they hold?',
    answer_a: 'Scribes — low status workers',
    answer_b: '"Meryma\'at" — high social standing',
    answer_c: 'Priests — religious figures only',
    answer_d: 'Servants — no special status',
    correct_answer: 'b',
    explanation: 'Egyptian barbers were called "Meryma\'at" and enjoyed high social standing and respect in society.',
    difficulty: 'medium',
    order_index: 2,
  },
  {
    id: 'qq-1-003',
    quiz_id: 'quiz-1',
    question: 'Why did Egyptian priests shave their entire bodies daily?',
    answer_a: 'To prevent lice infestation',
    answer_b: 'As a religious purification practice before rituals',
    answer_c: 'To show allegiance to the pharaoh',
    answer_d: 'Because hair was considered unclean',
    correct_answer: 'b',
    explanation: 'Daily full-body shaving was a religious purification practice to maintain spiritual cleanliness before performing rituals.',
    difficulty: 'medium',
    order_index: 3,
  },
  {
    id: 'qq-1-004',
    quiz_id: 'quiz-1',
    question: 'What spiritual belief did many ancient cultures hold about hair?',
    answer_a: 'Hair contained magical healing powers',
    answer_b: 'Hair was the gateway for spirits entering and leaving the body',
    answer_c: 'Long hair brought bad luck',
    answer_d: 'Hair should never be cut after age 30',
    correct_answer: 'b',
    explanation: 'Many ancient cultures believed hair was the gateway for spirits entering and leaving the body, giving it profound spiritual significance.',
    difficulty: 'medium',
    order_index: 4,
  },
  {
    id: 'qq-1-005',
    quiz_id: 'quiz-1',
    question: 'How did Masai warriors use braiding patterns?',
    answer_a: 'To identify enemy tribes',
    answer_b: 'To indicate social rank, warrior status, and tribal position',
    answer_c: 'Only for ceremonial dances',
    answer_d: 'To signal readiness for battle',
    correct_answer: 'b',
    explanation: 'Specific braiding patterns and styles indicated social rank, warrior status, and tribal position within the community.',
    difficulty: 'hard',
    order_index: 5,
  },
  {
    id: 'qq-1-006',
    quiz_id: 'quiz-1',
    question: 'During which prehistoric period were stone razors and scrapers used for hair removal?',
    answer_a: 'Neolithic period (10,000–4,500 BC)',
    answer_b: 'Upper Paleolithic period (40,000–10,000 BC)',
    answer_c: 'Bronze Age (3,300–1,200 BC)',
    answer_d: 'Iron Age (1,200–600 BC)',
    correct_answer: 'b',
    explanation: 'The Upper Paleolithic period, spanning roughly 40,000 to 10,000 BC, saw the use of stone tools for grooming and skinning.',
    difficulty: 'medium',
    order_index: 6,
  },
  {
    id: 'qq-1-007',
    quiz_id: 'quiz-1',
    question: 'What did beards symbolize in ancient cultures?',
    answer_a: 'Wealth and material possessions',
    answer_b: 'Wisdom, physical strength, mature manhood, and religious devotion',
    answer_c: 'Youth and vitality',
    answer_d: 'Political rebellion',
    correct_answer: 'b',
    explanation: 'Beards represented wisdom, physical strength, mature manhood, and deep religious devotion across many civilizations.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-1-008',
    quiz_id: 'quiz-1',
    question: 'Why did Alexander the Great order his soldiers to shave their beards?',
    answer_a: 'To improve hygiene in desert campaigns',
    answer_b: 'Beards could be grabbed by enemies in hand-to-hand combat',
    answer_c: 'To distinguish his army from Persian forces',
    answer_d: 'Religious conversion requirements',
    correct_answer: 'b',
    explanation: 'Beards could be grabbed by enemies during hand-to-hand combat, creating a tactical disadvantage in battle.',
    difficulty: 'medium',
    order_index: 8,
  },
  {
    id: 'qq-1-009',
    quiz_id: 'quiz-1',
    question: 'What event in 1096 led to the formation of the first barber guild in France?',
    answer_a: 'A royal decree requiring all men to be clean-shaven',
    answer_b: 'The Archbishop of Rouen prohibited clergy from wearing beards',
    answer_c: 'The Crusades created demand for battlefield barbers',
    answer_d: 'A plague outbreak required regular shaving',
    correct_answer: 'b',
    explanation: 'The Archbishop of Rouen prohibited clergy from wearing beards, which spurred the organization of barbers into a formal guild.',
    difficulty: 'hard',
    order_index: 9,
  },
  {
    id: 'qq-1-010',
    quiz_id: 'quiz-1',
    question: 'Which Russian ruler famously taxed bearded men?',
    answer_a: 'Ivan the Terrible',
    answer_b: 'Catherine the Great',
    answer_c: 'Peter the Great',
    answer_d: 'Nicholas II',
    correct_answer: 'c',
    explanation: 'Peter the Great imposed a beard tax as part of his modernization efforts to align Russian fashion with Western Europe.',
    difficulty: 'medium',
    order_index: 10,
  },
  {
    id: 'qq-1-011',
    quiz_id: 'quiz-1',
    question: 'What did Pythagoras believe about cutting hair?',
    answer_a: 'It brought good fortune',
    answer_b: 'Trimming hair reduced intellectual capacity and mental abilities',
    answer_c: 'Hair should only be cut during full moons',
    answer_d: 'Cutting hair was a sin against nature',
    correct_answer: 'b',
    explanation: 'The philosopher Pythagoras claimed that trimming hair reduced a person\'s intellectual capacity and mental abilities.',
    difficulty: 'hard',
    order_index: 11,
  },
  {
    id: 'qq-1-012',
    quiz_id: 'quiz-1',
    question: 'What did the Chinese queue hairstyle represent under Manchu rule?',
    answer_a: 'Religious devotion to Buddhism',
    answer_b: 'Political submission and obedience to the ruling government',
    answer_c: 'Membership in the imperial guard',
    answer_d: 'Wealth and merchant status',
    correct_answer: 'b',
    explanation: 'The forced queue hairstyle symbolized political submission and obedience to the ruling Manchu government.',
    difficulty: 'medium',
    order_index: 12,
  },
  {
    id: 'qq-1-013',
    quiz_id: 'quiz-1',
    question: 'What is tonsure, and when was the circular tonsure abolished?',
    answer_a: 'A full-head shave, abolished in 1450',
    answer_b: 'Shaving a patch on the crown, abolished in 1972',
    answer_c: 'A ceremonial beard trim, abolished in 1800',
    answer_d: 'A side-lock hairstyle, still practiced today',
    correct_answer: 'b',
    explanation: 'Tonsure is the practice of shaving a patch on the crown of the head. The circular tonsure of St. Peter was abolished in 1972.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-1-014',
    quiz_id: 'quiz-1',
    question: 'What medical procedures did barber-surgeons perform during the Middle Ages?',
    answer_a: 'Only haircuts and shaves',
    answer_b: 'Bloodletting, minor surgery, herbal remedies, and tooth extractions',
    answer_c: 'Major operations and autopsies',
    answer_d: 'Childbirth assistance and midwifery',
    correct_answer: 'b',
    explanation: 'Beyond grooming, barber-surgeons performed bloodletting, minor surgical procedures, herbal remedies, and tooth extractions.',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-1-015',
    quiz_id: 'quiz-1',
    question: 'What happened at the Council of Tours in 1163 that affected barbers?',
    answer_a: 'Barbers were granted medical licenses',
    answer_b: 'The Pope forbade clergy from practicing medicine, transferring duties to barbers',
    answer_c: 'The first barber school was established',
    answer_d: 'Barbers were banned from performing surgery',
    correct_answer: 'b',
    explanation: 'The Pope forbade clergy from practicing medicine or surgery, transferring those duties to barbers who already handled blades.',
    difficulty: 'medium',
    order_index: 15,
  },
  {
    id: 'qq-1-016',
    quiz_id: 'quiz-1',
    question: 'When did surgeons officially separate from barbers, ending the barber-surgeon era?',
    answer_a: '1540',
    answer_b: '1605',
    answer_c: '1745',
    answer_d: '1897',
    correct_answer: 'c',
    explanation: 'The complete separation occurred in 1745, when surgeons formally split from barbers to establish independent medical practice.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-1-017',
    quiz_id: 'quiz-1',
    question: 'What do the three colors of the barber pole represent?',
    answer_a: 'Red, white, and blue for the American flag',
    answer_b: 'Red for blood, white for bandages, blue for veins',
    answer_c: 'Red for fire, white for purity, blue for water',
    answer_d: 'Red for courage, white for peace, blue for loyalty',
    correct_answer: 'b',
    explanation: 'Red represents blood, white represents bandages, and blue represents veins — all originating from bloodletting practices.',
    difficulty: 'easy',
    order_index: 17,
  },
  {
    id: 'qq-1-018',
    quiz_id: 'quiz-1',
    question: 'When and where were the earliest scissors developed?',
    answer_a: 'Ancient Rome, 500 BC',
    answer_b: 'The Middle East, between 3000 and 2000 BC',
    answer_c: 'China, during the Han Dynasty',
    answer_d: 'Medieval Europe, 1200 AD',
    correct_answer: 'b',
    explanation: 'The Middle East produced the earliest scissors between 3000 and 2000 BC, revolutionizing hair cutting precision.',
    difficulty: 'medium',
    order_index: 18,
  },
  {
    id: 'qq-1-019',
    quiz_id: 'quiz-1',
    question: 'Who invented the first practical electric hair clippers, and in what year?',
    answer_a: 'Matthew Andis in 1921',
    answer_b: 'John Oster in 1928',
    answer_c: 'Leo J. Wahl in 1919',
    answer_d: 'Thomas Edison in 1905',
    correct_answer: 'c',
    explanation: 'Leo J. Wahl invented the first practical electric hair clippers in 1919, transforming the barbering industry.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-1-020',
    quiz_id: 'quiz-1',
    question: 'Which three companies dominated early electric clipper manufacturing?',
    answer_a: 'Gillette, Remington, and Philips',
    answer_b: 'Wahl, Andis, and Oster',
    answer_c: 'Sears, Montgomery Ward, and Woolworth',
    answer_d: 'General Electric, Westinghouse, and IBM',
    correct_answer: 'b',
    explanation: 'Wahl Clipper Corporation (1921), Andis (developed by Matthew Andis), and Oster (John Oster marketed motorized clippers in 1928) dominated early manufacturing.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'qq-1-021',
    quiz_id: 'quiz-1',
    question: 'When and where was the first barber-licensing law passed?',
    answer_a: 'New York, 1905',
    answer_b: 'Minnesota, 1897',
    answer_c: 'California, 1910',
    answer_d: 'Illinois, 1885',
    correct_answer: 'b',
    explanation: 'Minnesota passed the first barber-licensing law in 1897, establishing standards for sanitation, education, and disinfection.',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-1-022',
    quiz_id: 'quiz-1',
    question: 'What does NABBA stand for, and when was it founded?',
    answer_a: 'National Association of Barbers and Beauticians, founded 1910',
    answer_b: 'National Association of State Boards of Barber Examiners, founded 1929',
    answer_c: 'North American Barber Brotherhood Alliance, founded 1950',
    answer_d: 'National Academy of Barbering and Beauty Arts, founded 1900',
    correct_answer: 'b',
    explanation: 'The National Association of State Boards of Barber Examiners was founded in 1929 and represents over 300,000 barbers.',
    difficulty: 'easy',
    order_index: 22,
  },
  {
    id: 'qq-1-023',
    quiz_id: 'quiz-1',
    question: 'What are the five main objectives of NABBA?',
    answer_a: 'Profit, expansion, marketing, sales, and recruitment',
    answer_b: 'Promote information exchange, establish exam/licensing standards, set curriculum standards, support continuing education, and protect consumers',
    answer_c: 'Political lobbying, union organization, strike coordination, wage negotiation, and benefits management',
    answer_d: 'Product development, tool manufacturing, school accreditation, advertising, and trade shows',
    correct_answer: 'b',
    explanation: 'NABBA promotes information exchange, establishes exam/licensing standards, sets curriculum standards, supports continuing education, and protects consumers.',
    difficulty: 'hard',
    order_index: 23,
  },
  {
    id: 'qq-1-024',
    quiz_id: 'quiz-1',
    question: 'What factors caused the decline of barbershops in the 1980s–1990s?',
    answer_a: 'Economic recession and high unemployment',
    answer_b: 'Unisex salons, full-service spas, long hair trends, and cosmetology licensing shifts',
    answer_c: 'Government bans on barbering',
    answer_d: 'Lack of interest among young people',
    correct_answer: 'b',
    explanation: 'Unisex salons, full-service spas, long hair fashion trends, and shifts toward cosmetology licensing reduced traditional barbershop demand.',
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-1-025',
    quiz_id: 'quiz-1',
    question: 'What percentage of barbershop clientele are women in some modern shops?',
    answer_a: 'Approximately 10%',
    answer_b: 'Approximately 30%',
    answer_c: 'Approximately 50%',
    answer_d: 'Less than 5%',
    correct_answer: 'b',
    explanation: 'Women now make up approximately 30% of clientele in some barbershops, with female barbers and students also increasing.',
    difficulty: 'medium',
    order_index: 25,
  },
]

// ───────────────────────────────────────────────
// CHAPTER 2: Life Skills (15 questions from HTML + 10 original)
// ───────────────────────────────────────────────
export const chapter2QuizQuestions: QuizQuestion[] = [
  {
    id: 'qq-2-001',
    quiz_id: 'quiz-2',
    question: 'According to the chapter, what percentage of barber success comes from life and business skills?',
    answer_a: '25%',
    answer_b: '60%',
    answer_c: '40%',
    answer_d: '80%',
    correct_answer: 'b',
    explanation: 'The chapter states that 60% of barber success comes from life and business skills, while 40% comes from technical skills like cutting, styling, and sanitation.',
    difficulty: 'easy',
    order_index: 1,
  },
  {
    id: 'qq-2-002',
    quiz_id: 'quiz-2',
    question: 'What does the "T" in SMART goals stand for?',
    answer_a: 'Targeted',
    answer_b: 'Tactical',
    answer_c: 'Time-Bound',
    answer_d: 'Trackable',
    correct_answer: 'c',
    explanation: 'The T in SMART stands for Time-Bound — setting a deadline like "By December 31st" creates urgency and focus.',
    difficulty: 'easy',
    order_index: 2,
  },
  {
    id: 'qq-2-003',
    quiz_id: 'quiz-2',
    question: 'Which of the following is NOT one of the "time traps" mentioned in the chapter?',
    answer_a: '"I\'ll practice later"',
    answer_b: 'Waking up early to plan',
    answer_c: 'Scrolling social media "for just a minute"',
    answer_d: 'Saying yes to everything',
    correct_answer: 'b',
    explanation: 'Waking up early to plan is a positive habit, not a time trap. The chapter lists "I\'ll practice later," social media scrolling, saying yes to everything, and not planning tomorrow as common time traps.',
    difficulty: 'easy',
    order_index: 3,
  },
  {
    id: 'qq-2-004',
    quiz_id: 'quiz-2',
    question: 'What is the recommended duration for focused study blocks using the Pomodoro Technique?',
    answer_a: '25 minutes',
    answer_b: '45 minutes',
    answer_c: '60 minutes',
    answer_d: '90 minutes',
    correct_answer: 'a',
    explanation: 'The Pomodoro Technique recommends 25-minute focused study blocks followed by short breaks.',
    difficulty: 'easy',
    order_index: 4,
  },
  {
    id: 'qq-2-005',
    quiz_id: 'quiz-2',
    question: 'Which of the following is a warning sign of burnout?',
    answer_a: 'Arriving early to work',
    answer_b: 'Learning new techniques',
    answer_c: 'Building client relationships',
    answer_d: 'Dreading work',
    correct_answer: 'd',
    explanation: 'Dreading work is a key warning sign of burnout. Other signs include chronic fatigue, irritability with clients, physical aches, and loss of creativity.',
    difficulty: 'easy',
    order_index: 5,
  },
  {
    id: 'qq-2-006',
    quiz_id: 'quiz-2',
    question: 'According to the 50/30/20 rule, what percentage of income should go to savings and debt?',
    answer_a: '10%',
    answer_b: '30%',
    answer_c: '20%',
    answer_d: '50%',
    correct_answer: 'c',
    explanation: 'The 50/30/20 rule allocates 50% to needs, 30% to wants, and 20% to savings and debt repayment.',
    difficulty: 'easy',
    order_index: 6,
  },
  {
    id: 'qq-2-007',
    quiz_id: 'quiz-2',
    question: 'What is the first step in breaking a big goal into action steps?',
    answer_a: 'Schedule daily tasks',
    answer_b: 'Write down your big goal',
    answer_c: 'Find a mentor',
    answer_d: 'Set a deadline',
    correct_answer: 'b',
    explanation: 'The first step is to write down your big goal clearly. Example: "Open my own barbershop in 3 years." Then work backward from there.',
    difficulty: 'easy',
    order_index: 7,
  },
  {
    id: 'qq-2-008',
    quiz_id: 'quiz-2',
    question: 'What is the recommended starting amount for an emergency fund?',
    answer_a: '$1,000',
    answer_b: '$5,000',
    answer_c: '$500',
    answer_d: '$10,000',
    correct_answer: 'a',
    explanation: 'The chapter recommends starting with a $1,000 mini emergency fund, then building to 3 months of expenses, and eventually 6 months.',
    difficulty: 'easy',
    order_index: 8,
  },
  {
    id: 'qq-2-009',
    quiz_id: 'quiz-2',
    question: 'Which of the following is the best example of a SMART goal?',
    answer_a: '"Get better at cutting hair"',
    answer_b: '"Make more money"',
    answer_c: '"Be the best barber ever"',
    answer_d: '"Complete 100 practice fades by December 31st"',
    correct_answer: 'd',
    explanation: '"Complete 100 practice fades by December 31st" is Specific, Measurable, Achievable, Relevant, and Time-Bound. The other options are vague and lack measurable criteria.',
    difficulty: 'medium',
    order_index: 9,
  },
  {
    id: 'qq-2-010',
    quiz_id: 'quiz-2',
    question: 'What percentage of income should booth renters set aside for taxes?',
    answer_a: '10%',
    answer_b: '25-30%',
    answer_c: '15%',
    answer_d: '5%',
    correct_answer: 'b',
    explanation: 'Booth renters should set aside 25-30% of income for taxes since they are self-employed and responsible for their own tax payments.',
    difficulty: 'medium',
    order_index: 10,
  },
  {
    id: 'qq-2-011',
    quiz_id: 'quiz-2',
    question: 'Which networking approach is most effective according to the chapter?',
    answer_a: 'Only network once you have experience',
    answer_b: 'Ask for favors immediately upon meeting',
    answer_c: 'Give first and build genuine relationships',
    answer_d: 'Only network at formal events',
    correct_answer: 'c',
    explanation: 'The chapter emphasizes giving first — sharing knowledge, making introductions, and offering help before asking for anything — as the foundation of effective networking.',
    difficulty: 'medium',
    order_index: 11,
  },
  {
    id: 'qq-2-012',
    quiz_id: 'quiz-2',
    question: 'What is the 2-Minute Rule for time management?',
    answer_a: 'If a task takes less than 2 minutes, do it immediately',
    answer_b: 'Take a 2-minute break every hour',
    answer_c: 'Spend 2 minutes planning each morning',
    answer_d: 'Limit social media to 2 minutes per day',
    correct_answer: 'a',
    explanation: 'The 2-Minute Rule states that if a task takes less than 2 minutes, do it immediately rather than letting small tasks pile up.',
    difficulty: 'easy',
    order_index: 12,
  },
  {
    id: 'qq-2-013',
    quiz_id: 'quiz-2',
    question: 'Which is NOT recommended as a way to track study progress?',
    answer_a: 'Progress journal',
    answer_b: 'Visual trackers',
    answer_c: 'Accountability partner',
    answer_d: 'Comparing yourself to others',
    correct_answer: 'd',
    explanation: 'The chapter recommends progress journals, visual trackers, and accountability partners. Comparing yourself to others is not mentioned and can be demotivating.',
    difficulty: 'medium',
    order_index: 13,
  },
  {
    id: 'qq-2-014',
    quiz_id: 'quiz-2',
    question: 'What should you do every Sunday according to the time management section?',
    answer_a: 'Deep clean your tools',
    answer_b: 'Plan your week ahead',
    answer_c: 'Take the day completely off',
    answer_d: 'Network with other barbers',
    correct_answer: 'b',
    explanation: 'The Sunday Planning Session involves spending 30 minutes mapping out your week so you know your priorities before Monday hits.',
    difficulty: 'easy',
    order_index: 14,
  },
  {
    id: 'qq-2-015',
    quiz_id: 'quiz-2',
    question: 'What is the ultimate goal for emergency fund savings?',
    answer_a: '1 month of expenses',
    answer_b: '2 months of expenses',
    answer_c: '6 months of expenses',
    answer_d: '12 months of expenses',
    correct_answer: 'c',
    explanation: 'The ultimate goal is 6 months of expenses saved, though you start with $1,000 and build to 3 months first.',
    difficulty: 'easy',
    order_index: 15,
  },
  {
    id: 'qq-2-016',
    quiz_id: 'quiz-2',
    question: 'Why are life skills equally important as technical skills in barbering?',
    answer_a: 'They are required by state licensing boards',
    answer_b: 'Barbers interact daily with diverse clients and coworkers, requiring strong interpersonal abilities',
    answer_c: 'They replace the need for technical training',
    answer_d: 'Only senior barbers need life skills',
    correct_answer: 'b',
    explanation: 'Barbers interact daily with diverse clients and coworkers. Strong life skills ensure positive interactions, help navigate difficult situations, and build self-esteem needed for career success.',
    difficulty: 'easy',
    order_index: 16,
  },
  {
    id: 'qq-2-017',
    quiz_id: 'quiz-2',
    question: 'What are three destructive habits that kill productivity?',
    answer_a: 'Overworking, multitasking, and perfectionism',
    answer_b: 'Procrastination, perfectionism, and lack of a game plan',
    answer_c: 'Sleeping too much, eating poorly, and exercising rarely',
    answer_d: 'Talking too much, arriving late, and forgetting appointments',
    correct_answer: 'b',
    explanation: 'Procrastination (putting things off), perfectionism (unhealthy need for flawlessness), and lack of a game plan (no organized goals or direction) are productivity killers.',
    difficulty: 'easy',
    order_index: 17,
  },
  {
    id: 'qq-2-018',
    quiz_id: 'quiz-2',
    question: 'What is the purpose of a personal mission statement?',
    answer_a: 'To impress clients with fancy language',
    answer_b: 'To define your purpose, core values, and professional direction',
    answer_c: 'To replace the need for business cards',
    answer_d: 'To satisfy licensing requirements',
    correct_answer: 'b',
    explanation: 'A mission statement defines your purpose, core values, and direction. It provides focus and becomes the cultural pulse of your professional life.',
    difficulty: 'easy',
    order_index: 18,
  },
  {
    id: 'qq-2-019',
    quiz_id: 'quiz-2',
    question: 'What does diplomacy (tact) mean in professional communication?',
    answer_a: 'Avoiding all difficult conversations',
    answer_b: 'Delivering truthful messages in a kind, respectful manner that preserves relationships',
    answer_c: 'Telling clients exactly what they want to hear',
    answer_d: 'Using formal language exclusively',
    correct_answer: 'b',
    explanation: 'Delivering truthful messages and feedback in a kind, respectful manner that preserves relationships and avoids unnecessary conflict.',
    difficulty: 'easy',
    order_index: 19,
  },
  {
    id: 'qq-2-020',
    quiz_id: 'quiz-2',
    question: 'Why is continuing education considered an ethical responsibility?',
    answer_a: 'It is only required to renew licenses',
    answer_b: 'Barbers must stay current with techniques, sanitation standards, and industry trends to serve clients competently',
    answer_c: 'Continuing education is optional and not ethically relevant',
    answer_d: 'It is only for barbers who want to teach',
    correct_answer: 'b',
    explanation: 'Participating in continuing education ensures barbers maintain skilled and competent services, which is a core ethical obligation to clients.',
    difficulty: 'medium',
    order_index: 20,
  },
  {
    id: 'qq-2-021',
    quiz_id: 'quiz-2',
    question: 'What are four key time management strategies for barbers?',
    answer_a: 'Work faster, skip breaks, multitask constantly, and take every walk-in',
    answer_b: 'Prioritize tasks, create schedules, learn to say no, and use planning tools',
    answer_c: 'Arrive late, leave early, ignore appointments, and avoid lists',
    answer_d: 'Only serve regular clients, refuse new business, and work weekends only',
    correct_answer: 'b',
    explanation: 'Prioritize tasks by importance, create flexible daily/weekly schedules, learn to say no kindly to avoid overcommitment, and use lists or digital planning tools.',
    difficulty: 'easy',
    order_index: 21,
  },
  {
    id: 'qq-2-022',
    quiz_id: 'quiz-2',
    question: 'Name four memory and study techniques useful for barber students.',
    answer_a: 'Cramming, guessing, skipping hard topics, and copying notes',
    answer_b: 'Repetition, organization, mnemonics, and mind mapping',
    answer_c: 'Sleeping with textbooks, listening to loud music, studying alone, and avoiding practice',
    answer_d: 'Memorizing only, ignoring hands-on training, avoiding review, and skipping quizzes',
    correct_answer: 'b',
    explanation: 'Repetition (verbal, written, hands-on), organization (breaking topics into segments), mnemonics (acronyms, word associations), and mind mapping (visual branching from central topics).',
    difficulty: 'easy',
    order_index: 22,
  },
  {
    id: 'qq-2-023',
    quiz_id: 'quiz-2',
    question: 'What is the difference between short-term and long-term goals?',
    answer_a: 'Short-term goals are less important than long-term goals',
    answer_b: 'Short-term goals take one year or less; long-term goals span two or more years',
    answer_c: 'Only long-term goals need to be written down',
    answer_d: 'Short-term goals require no planning',
    correct_answer: 'b',
    explanation: 'Short-term goals take one year or less to achieve (passing an exam, graduating). Long-term goals span two or more years (owning a shop in five years).',
    difficulty: 'easy',
    order_index: 23,
  },
  {
    id: 'qq-2-024',
    quiz_id: 'quiz-2',
    question: 'How can visualization help achieve professional success?',
    answer_a: 'It replaces the need for actual practice',
    answer_b: 'It reinforces positive beliefs, builds confidence, and programs the mind for achievement',
    answer_c: 'It guarantees clients will book appointments',
    answer_d: 'It is only useful for athletes, not barbers',
    correct_answer: 'b',
    explanation: 'Regularly imagining yourself working competently in your ideal barbershop reinforces positive beliefs, builds confidence, and programs your mind for achievement.',
    difficulty: 'medium',
    order_index: 24,
  },
  {
    id: 'qq-2-025',
    quiz_id: 'quiz-2',
    question: 'Why is emotional stability important for barbers?',
    answer_a: 'It helps barbers win arguments with clients',
    answer_b: 'Barbers encounter diverse personalities; emotional stability ensures calm, professional responses',
    answer_c: 'It eliminates the need for breaks during the workday',
    answer_d: 'Only managers need emotional stability',
    correct_answer: 'b',
    explanation: 'Barbers encounter diverse personalities and occasional confrontations. Emotional stability ensures professional, calm responses rather than reactive behavior.',
    difficulty: 'medium',
    order_index: 25,
  },
]

// ───────────────────────────────────────────────
// Export all quiz questions by chapter
// ───────────────────────────────────────────────
export const allQuizQuestions: Record<string, QuizQuestion[]> = {
  'quiz-1': chapter1QuizQuestions,
  'quiz-2': chapter2QuizQuestions,
}
