// Additional Key Terms for Chapters 6-21
const additionalTerms = [
    // Chapter 6: Implements
    { term: "Blades", phonetic: "", definition: "The cutting parts of clippers, usually manufactured from high-quality carbon steel.", chapter: 6 },
    { term: "Canvas Strop", phonetic: "", definition: "Usually one side of a combination strop made of linen or silk that removes metal burrs left after honing.", chapter: 6 },
    { term: "Cast Shears", phonetic: "", definition: "Shears made by heating steel to a liquid form for pouring into a mold.", chapter: 6 },
    { term: "Changeable-Blade Straight Razor", phonetic: "", definition: "A type of straight razor that uses changeable, disposable blades.", chapter: 6 },
    { term: "Clippers", phonetic: "", definition: "Electric haircutting tools with a single adjustable-blade or detachable-blade system.", chapter: 6 },
    { term: "Comedone Extractor", phonetic: "", definition: "An implement used to extract blackheads.", chapter: 6 },
    { term: "Conventional Straight Razor", phonetic: "", definition: "A razor made of hardened steel blade that requires honing and stropping.", chapter: 6 },
    { term: "Forged Shears", phonetic: "", definition: "Shears made by working heated metal into a finished shape through hammering or compression.", chapter: 6 },
    { term: "Guards", phonetic: "", definition: "Attachments that fit over clipper blades to minimize the amount of hair being cut.", chapter: 6 },
    { term: "High-Frequency Machine", phonetic: "", definition: "A machine that produces a high rate of oscillation for stimulating scalp, facial, and body tissues.", chapter: 6 },
    { term: "Hone", phonetic: "", definition: "A sharpening block used to create a cutting edge on conventional straight razors.", chapter: 6 },
    { term: "Palming the Comb", phonetic: "", definition: "The technique used to hold the comb in the hand opposite of the hand that is cutting.", chapter: 6 },
    { term: "Palming the Shears", phonetic: "", definition: "The technique used to hold shears in a safe manner while combing through hair.", chapter: 6 },
    { term: "Russian Strop", phonetic: "", definition: "A type of cowhide strop considered to be one of the best.", chapter: 6 },
    { term: "Set of the Shears", phonetic: "", definition: "The manner in which the blades and shanks of the shears align with each other.", chapter: 6 },
    { term: "Shell Strop", phonetic: "", definition: "A type of horsehide strop made from the muscular rump area of the horse.", chapter: 6 },
    { term: "Strop", phonetic: "", definition: "An elongated piece of leather used to finish the edge of conventional straight razors.", chapter: 6 },
    { term: "Taper Comb", phonetic: "", definition: "Used for cutting hair when a gradual blending from short to longer is required.", chapter: 6 },
    { term: "Texturizing Shears", phonetic: "", definition: "Shears with 14 to 28 teeth that add texture and volume.", chapter: 6 },
    { term: "Thermal Styling Tools", phonetic: "", definition: "Tools that produce heat for hairstyling purposes.", chapter: 6 },
    { term: "Thinning Shears", phonetic: "", definition: "Shears with 30 to 50 teeth used for blending hair ends and removing bulk.", chapter: 6 },
    { term: "Trimmers", phonetic: "", definition: "Small clippers used for detail, precision design, and fine finish work.", chapter: 6 },
    
    // Chapter 7: Anatomy (abbreviated - too many terms)
    { term: "Abductors", phonetic: "", definition: "Muscles that draw a body part away from the midline of the body.", chapter: 7 },
    { term: "Adductors", phonetic: "", definition: "Muscles that draw a body part inward toward the median axis.", chapter: 7 },
    { term: "Adipose Tissue", phonetic: "", definition: "Technical term for fat; gives smoothness and contour to the body.", chapter: 7 },
    { term: "Anatomy", phonetic: "", definition: "The science of the structure of organisms and their parts.", chapter: 7 },
    { term: "Aorta", phonetic: "", definition: "Largest artery in the body.", chapter: 7 },
    { term: "Arteries", phonetic: "", definition: "Thick-walled, muscular, flexible tubes that carry oxygenated blood away from the heart.", chapter: 7 },
    { term: "Cells", phonetic: "", definition: "Basic units of all living things.", chapter: 7 },
    { term: "Circulatory System", phonetic: "", definition: "System that controls the steady circulation of blood through the body.", chapter: 7 },
    { term: "Connective Tissue", phonetic: "", definition: "Fibrous tissue that binds together, protects, and supports various body parts.", chapter: 7 },
    { term: "Cranium", phonetic: "", definition: "An oval, bony case that protects the brain.", chapter: 7 },
    { term: "Cytoplasm", phonetic: "", definition: "Watery fluid that surrounds the nucleus of the cell.", chapter: 7 },
    { term: "Dermis", phonetic: "", definition: "Second layer of the skin; also known as the derma or true skin.", chapter: 7 },
    { term: "Epidermis", phonetic: "", definition: "Outermost layer of the skin.", chapter: 7 },
    { term: "Histology", phonetic: "", definition: "The study of the minute structure of tissues and organs.", chapter: 7 },
    { term: "Muscle Tissue", phonetic: "", definition: "Contracts and moves various parts of the body.", chapter: 7 },
    { term: "Nerve Tissue", phonetic: "", definition: "Carries messages to and from the brain and controls bodily functions.", chapter: 7 },
    { term: "Nucleus", phonetic: "", definition: "Dense, active protoplasm found in the center of a cell.", chapter: 7 },
    { term: "Physiology", phonetic: "", definition: "Study of the functions or activities performed by the body's structures.", chapter: 7 },
    { term: "Subcutaneous Tissue", phonetic: "", definition: "Fatty tissue layer beneath the dermis.", chapter: 7 },
    { term: "Tissue", phonetic: "", definition: "Collections of similar cells that perform a particular function.", chapter: 7 },
    
    // Chapter 8: Chemistry
    { term: "Acids", phonetic: "", definition: "Solutions that have a pH below 7.0.", chapter: 8 },
    { term: "Alkalis", phonetic: "", definition: "Solutions that have a pH above 7.0.", chapter: 8 },
    { term: "Atoms", phonetic: "", definition: "Basic building blocks of all matter.", chapter: 8 },
    { term: "Chemical Change", phonetic: "", definition: "Change in chemical composition by which new substances are formed.", chapter: 8 },
    { term: "Chemistry", phonetic: "", definition: "Science that deals with composition, structure, and properties of matter.", chapter: 8 },
    { term: "Element", phonetic: "", definition: "Simplest form of chemical matter containing only one type of atom.", chapter: 8 },
    { term: "Emulsions", phonetic: "", definition: "Mixtures of two or more immiscible substances united with an emulsifier.", chapter: 8 },
    { term: "Endothermic Reaction", phonetic: "", definition: "Chemical reaction requiring absorption of energy from an external source.", chapter: 8 },
    { term: "Exothermic Reaction", phonetic: "", definition: "Release of energy in the form of heat through chemical reactions.", chapter: 8 },
    { term: "Matter", phonetic: "", definition: "Anything that occupies space and has mass.", chapter: 8 },
    { term: "Molecule", phonetic: "", definition: "Two or more atoms joined chemically.", chapter: 8 },
    { term: "Oxidation", phonetic: "", definition: "Addition of oxygen or loss of hydrogen.", chapter: 8 },
    { term: "pH", phonetic: "", definition: "Potential hydrogen - relative degree of acidity or alkalinity.", chapter: 8 },
    { term: "Physical Change", phonetic: "", definition: "Change in form without formation of a new substance.", chapter: 8 },
    { term: "Reduction", phonetic: "", definition: "Subtraction of oxygen from or addition of hydrogen to a substance.", chapter: 8 },
    { term: "Salts", phonetic: "", definition: "Compounds formed by the reaction of acids and bases.", chapter: 8 },
    { term: "Solution", phonetic: "", definition: "Uniform mixture of two or more substances.", chapter: 8 },
    { term: "Surfactant", phonetic: "", definition: "Substance that allows oil and water to mix by reducing surface tension.", chapter: 8 },
    
    // Chapter 9: Skin
    { term: "Acne", phonetic: "", definition: "Skin disorder characterized by chronic inflammation of sebaceous glands.", chapter: 9 },
    { term: "Albinism", phonetic: "", definition: "Congenital absence of melanin pigment in the body.", chapter: 9 },
    { term: "Anhidrosis", phonetic: "", definition: "Deficiency in perspiration or inability to sweat.", chapter: 9 },
    { term: "Asteatosis", phonetic: "", definition: "Condition of dry, scaly skin due to deficiency of sebum.", chapter: 9 },
    { term: "Basal Cell Carcinoma", phonetic: "", definition: "Most common and least severe type of skin cancer.", chapter: 9 },
    { term: "Blackhead", phonetic: "", definition: "Open comedo; accumulation of excess oil oxidized to dark color.", chapter: 9 },
    { term: "Bromhidrosis", phonetic: "", definition: "Foul-smelling perspiration.", chapter: 9 },
    { term: "Closed Comedo", phonetic: "", definition: "Whitehead; small bump with white or cream colored sebum.", chapter: 9 },
    { term: "Collagen", phonetic: "", definition: "Fibrous protein that gives skin form and strength.", chapter: 9 },
    { term: "Comedone", phonetic: "", definition: "Mass of hardened sebum in a hair follicle.", chapter: 9 },
    { term: "Dermatitis", phonetic: "", definition: "Inflammatory condition of the skin.", chapter: 9 },
    { term: "Eczema", phonetic: "", definition: "Inflammatory skin condition characterized by painful itching.", chapter: 9 },
    { term: "Elastin", phonetic: "", definition: "Protein base that forms elastic tissue.", chapter: 9 },
    { term: "Herpes Simplex I", phonetic: "", definition: "Fever blister or cold sore; recurring viral infection.", chapter: 9 },
    { term: "Hyperhidrosis", phonetic: "", definition: "Excessive perspiration or sweating.", chapter: 9 },
    { term: "Keloid", phonetic: "", definition: "Thick scar resulting from excessive tissue growth.", chapter: 9 },
    { term: "Lesion", phonetic: "", definition: "Structural change in tissues caused by injury or disease.", chapter: 9 },
    { term: "Macule", phonetic: "", definition: "Spot or discoloration of the skin, such as a freckle.", chapter: 9 },
    { term: "Malignant Melanoma", phonetic: "", definition: "Most severe form of skin cancer.", chapter: 9 },
    { term: "Melanin", phonetic: "", definition: "Coloring matter or pigment of the skin.", chapter: 9 },
    { term: "Mole", phonetic: "", definition: "Small brownish spot on the skin.", chapter: 9 },
    { term: "Papule", phonetic: "", definition: "Small elevation on the skin containing no fluid.", chapter: 9 },
    { term: "Psoriasis", phonetic: "", definition: "Skin disease characterized by red patches and silvery-white scales.", chapter: 9 },
    { term: "Pustule", phonetic: "", definition: "Raised, inflamed papule with white or yellow center containing pus.", chapter: 9 },
    { term: "Rosacea", phonetic: "", definition: "Chronic congestion of skin characterized by redness and dilation of blood vessels.", chapter: 9 },
    { term: "Sebaceous Glands", phonetic: "", definition: "Oil glands of the skin connected to hair follicles.", chapter: 9 },
    { term: "Sebum", phonetic: "", definition: "Oily substance secreted by sebaceous glands.", chapter: 9 },
    { term: "Squamous Cell Carcinoma", phonetic: "", definition: "Type of skin cancer more serious than basal cell carcinoma.", chapter: 9 },
    { term: "Stratum Corneum", phonetic: "", definition: "Outermost layer of the epidermis; the horny layer.", chapter: 9 },
    { term: "Stratum Germinativum", phonetic: "", definition: "Innermost layer of the epidermis.", chapter: 9 },
    { term: "Sudoriferous Glands", phonetic: "", definition: "Sweat glands of the skin.", chapter: 9 },
    { term: "Verruca", phonetic: "", definition: "Technical name for a wart.", chapter: 9 },
    { term: "Vesicle", phonetic: "", definition: "Small blister containing clear fluid.", chapter: 9 },
    { term: "Vitiligo", phonetic: "", definition: "Acquired leukoderma characterized by milky-white spots.", chapter: 9 },
    { term: "Wart", phonetic: "", definition: "Infectious hypertrophy caused by a virus.", chapter: 9 },
    
    // Chapter 10: Electricity (abbreviated)
    { term: "Alternating Current (AC)", phonetic: "", definition: "Rapid current flowing first in one direction then the opposite.", chapter: 10 },
    { term: "Ampere", phonetic: "", definition: "Standard unit for measuring strength of electric current.", chapter: 10 },
    { term: "Anode", phonetic: "", definition: "Positive electrode.", chapter: 10 },
    { term: "Cathode", phonetic: "", definition: "Negative electrode.", chapter: 10 },
    { term: "Circuit Breaker", phonetic: "", definition: "Switch that automatically interrupts an electric circuit at overload.", chapter: 10 },
    { term: "Conductor", phonetic: "", definition: "Any substance that conducts electricity.", chapter: 10 },
    { term: "Direct Current (DC)", phonetic: "", definition: "Constant current traveling in one direction only.", chapter: 10 },
    { term: "Electric Current", phonetic: "", definition: "Flow of electricity along a conductor.", chapter: 10 },
    { term: "Fuse", phonetic: "", definition: "Device that prevents excessive current from passing through a circuit.", chapter: 10 },
    { term: "Galvanic Current", phonetic: "", definition: "Constant DC with positive and negative poles producing chemical changes.", chapter: 10 },
    { term: "GFI", phonetic: "", definition: "Ground Fault Interrupter - device sensing imbalances in electric current.", chapter: 10 },
    { term: "Infrared Light", phonetic: "", definition: "Invisible rays with long wavelengths producing heat.", chapter: 10 },
    { term: "Insulator", phonetic: "", definition: "Substance that does not easily transfer electricity.", chapter: 10 },
    { term: "LED", phonetic: "", definition: "Light-Emitting Diode - medical device for treating skin conditions.", chapter: 10 },
    { term: "Ohm", phonetic: "", definition: "Unit of electrical resistance.", chapter: 10 },
    { term: "Tesla High-Frequency Current", phonetic: "", definition: "Thermal current with high oscillation rate; violet ray.", chapter: 10 },
    { term: "Ultraviolet Light", phonetic: "", definition: "Invisible rays that kill germs; also called actinic or cold rays.", chapter: 10 },
    { term: "Volt", phonetic: "", definition: "Unit of electrical pressure pushing electron flow.", chapter: 10 },
    { term: "Watt", phonetic: "", definition: "Unit of power indicating electric energy used per second.", chapter: 10 },
    
    // Chapter 11-21: Additional abbreviated terms
    { term: "Anagen", phonetic: "", definition: "Active growth phase of hair.", chapter: 11 },
    { term: "Catagen", phonetic: "", definition: "Transitional phase of hair growth.", chapter: 11 },
    { term: "Cortex", phonetic: "", definition: "Middle layer of hair shaft.", chapter: 11 },
    { term: "Cuticle", phonetic: "", definition: "Outermost layer of hair shaft.", chapter: 11 },
    { term: "Keratin", phonetic: "", definition: "Fibrous protein making up hair.", chapter: 11 },
    { term: "Medulla", phonetic: "", definition: "Innermost layer of hair shaft.", chapter: 11 },
    { term: "Telogen", phonetic: "", definition: "Resting phase of hair growth.", chapter: 11 },
    
    { term: "Effleurage", phonetic: "", definition: "Light, continuous stroking massage.", chapter: 12 },
    { term: "Petrissage", phonetic: "", definition: "Kneading massage movement.", chapter: 12 },
    
    { term: "Toupee", phonetic: "", definition: "Small wig covering a bald spot.", chapter: 13 },
    
    { term: "Balancing Shampoo", phonetic: "", definition: "Designed for oily hair and scalps.", chapter: 14 },
    { term: "Clarifying Shampoo", phonetic: "", definition: "Removes product buildup from hair.", chapter: 14 },
    { term: "Conditioner", phonetic: "", definition: "Improves texture and appearance of hair.", chapter: 14 },
    { term: "Medicated Shampoo", phonetic: "", definition: "Contains agents for controlling dandruff.", chapter: 14 },
    { term: "Neutralizing Shampoo", phonetic: "", definition: "Rebalances pH after chemical relaxing.", chapter: 14 },
    { term: "pH-Balanced Shampoo", phonetic: "", definition: "Balanced to pH of hair and skin (4.5-5.5).", chapter: 14 },
    { term: "Protein Conditioner", phonetic: "", definition: "Penetrating formulation restoring protein.", chapter: 14 },
    
    { term: "Bicep", phonetic: "", definition: "Muscle producing contour of upper arm.", chapter: 15 },
    { term: "Frontalis", phonetic: "", definition: "Muscle of forehead raising eyebrows.", chapter: 15 },
    { term: "Masseter", phonetic: "", definition: "Muscle closing the jaw for chewing.", chapter: 15 },
    { term: "Orbicularis Oculi", phonetic: "", definition: "Muscle surrounding the eye.", chapter: 15 },
    { term: "Orbicularis Oris", phonetic: "", definition: "Muscle around the lips.", chapter: 15 },
    { term: "Platysma", phonetic: "", definition: "Muscle depressing lower jaw and lip.", chapter: 15 },
    { term: "Zygomaticus", phonetic: "", definition: "Muscle raising corner of mouth when smiling.", chapter: 15 },
    
    { term: "Developer", phonetic: "", definition: "Hydrogen peroxide activating haircolor.", chapter: 17 },
    { term: "Gray Coverage", phonetic: "", definition: "Ability to cover gray or white hair.", chapter: 17 },
    { term: "Permanent Color", phonetic: "", definition: "Haircolor permanently changing natural pigment.", chapter: 17 },
    { term: "Semi-Permanent", phonetic: "", definition: "Haircolor lasting 4-6 weeks.", chapter: 17 },
    
    { term: "Complementary Colors", phonetic: "", definition: "Colors opposite each other that neutralize.", chapter: 18 },
    { term: "Primary Colors", phonetic: "", definition: "Red, yellow, and blue.", chapter: 18 },
    { term: "Secondary Colors", phonetic: "", definition: "Orange, green, and violet.", chapter: 18 },
    { term: "Tone", phonetic: "", definition: "Warmth or coolness of haircolor.", chapter: 18 },
    
    { term: "Practical Exam", phonetic: "", definition: "Hands-on portion of state board exam.", chapter: 19 },
    { term: "State Board Exam", phonetic: "", definition: "Examination required for barber license.", chapter: 19 },
    { term: "Written Exam", phonetic: "", definition: "Theory portion of state board exam.", chapter: 19 },
    
    { term: "Booth Rental", phonetic: "", definition: "Paying set fee to use a station.", chapter: 20 },
    { term: "Commission", phonetic: "", definition: "Payment based on percentage of services.", chapter: 20 },
    { term: "Retail", phonetic: "", definition: "Selling products to clients.", chapter: 20 },
    
    { term: "Business Plan", phonetic: "", definition: "Written description of business goals and strategies.", chapter: 21 },
    { term: "Corporation", phonetic: "", definition: "Legal entity separate from owners.", chapter: 21 },
    { term: "Partnership", phonetic: "", definition: "Business owned by two or more people.", chapter: 21 },
    { term: "Sole Proprietorship", phonetic: "", definition: "Business owned by one person.", chapter: 21 }
];

// Export for use in main file
if (typeof module !== 'undefined' && module.exports) {
    module.exports = additionalTerms;
}
