const fs = require('fs');
const path = require('path');

const baseDir = 'C:\\Users\\skyfl\\.openclaw\\workspace\\barber-study-pro';

// Define emoji replacements - most common ones first
const replacements = [
    { find: '🔒 ', replace: '' },
    { find: '⚡ ', replace: '' },
    { find: '⚡', replace: '' },
    { find: '🎯 ', replace: '' },
    { find: '💪 ', replace: '' },
    { find: '🧠 ', replace: '' },
    { find: '🧼 ', replace: '' },
    { find: '🪑 ', replace: '' },
    { find: '👔 ', replace: '' },
    { find: '💬 ', replace: '' },
    { find: '📝 ', replace: '' },
    { find: '🎉', replace: '' },
    { find: '👏', replace: '' },
    { find: '👍', replace: '' },
    { find: '📊 ', replace: '' },
    { find: '💾', replace: '' },
    { find: '🌟', replace: '' },
    { find: '📋', replace: '' },
    { find: '💰', replace: '' },
    { find: '📅', replace: '' },
    { find: '🔄', replace: '' },
    { find: '📞', replace: '' },
    { find: '✓ ', replace: '' },
    { find: '✗ ', replace: '' },
    { find: '✅', replace: '' },
    { find: '❌', replace: '' },
    { find: '📚 ', replace: '' },
    { find: '🪒 ', replace: '' },
    { find: '💈 ', replace: '' },
    { find: '✂️ ', replace: '' },
    { find: '✂ ', replace: '' },
    { find: '👤', replace: '' },
    { find: '👥', replace: '' },
    { find: '🏆', replace: '' },
    { find: '⭐', replace: '' },
    { find: '📖', replace: '' },
    { find: '🔍', replace: '' },
    { find: '💡', replace: '' },
    { find: '🔥', replace: '' },
    { find: '⚠️ ', replace: '' },
    { find: '⚠ ', replace: '' },
    { find: '🎓', replace: '' },
    { find: '⏱️', replace: '' },
    { find: '⏱', replace: '' },
    { find: '⏰ ', replace: '' },
    { find: '💯', replace: '' },
    { find: '🚀', replace: '' },
    { find: '📈 ', replace: '' },
    { find: '🏠', replace: '' },
    { find: '📧', replace: '' },
    { find: '🔑', replace: '' },
    { find: '👋', replace: '' },
    { find: '💬', replace: '' },
    { find: '🗣️', replace: '' },
    { find: '🗣', replace: '' },
    { find: '🧪', replace: '' },
    { find: '🔬', replace: '' },
    { find: '🦠', replace: '' },
    { find: '🧴', replace: '' },
    { find: '🧽', replace: '' },
    { find: '✨', replace: '' },
    { find: '🎨 ', replace: '' },
    { find: '🖌️', replace: '' },
    { find: '🖌', replace: '' },
    { find: '🏪', replace: '' },
    { find: '📍', replace: '' },
    { find: '🌍', replace: '' },
    { find: '🌎', replace: '' },
    { find: '🌏', replace: '' },
    { find: '👨', replace: '' },
    { find: '👩', replace: '' },
    { find: '👶', replace: '' },
    { find: '👴', replace: '' },
    { find: '👵', replace: '' },
    { find: '👱', replace: '' },
    { find: '🎴 ', replace: '' },
    { find: '❓ ', replace: '' },
    { find: '🔊 ', replace: '' },
    { find: '⚖️ ', replace: '' },
    { find: '😊 ', replace: '' },
    { find: '🚪', replace: '' },
    { find: '⚙️', replace: '' },
    { find: '🔔', replace: '' },
    { find: '🧬', replace: '' },
    { find: '🩸', replace: '' },
    { find: '💉', replace: '' },
    { find: '🏥', replace: '' },
    { find: '🧫', replace: '' },
    { find: '🧹', replace: '' },
    { find: '🧺', replace: '' },
    { find: '🛁', replace: '' },
    { find: '🚿', replace: '' },
    { find: '🚰', replace: '' },
    { find: '🧯', replace: '' },
    { find: '🧮', replace: '' },
    { find: '📐', replace: '' },
    { find: '📏', replace: '' },
    { find: '📌', replace: '' },
    { find: '🧷', replace: '' },
    { find: '🧵', replace: '' },
    { find: '🧶', replace: '' },
    { find: '👓', replace: '' },
    { find: '🕶️', replace: '' },
    { find: '🥽', replace: '' },
    { find: '🥼', replace: '' },
    { find: '👕', replace: '' },
    { find: '👖', replace: '' },
    { find: '🧣', replace: '' },
    { find: '🧤', replace: '' },
    { find: '🧥', replace: '' },
    { find: '🧦', replace: '' },
    { find: '👗', replace: '' },
    { find: '👘', replace: '' },
    { find: '👙', replace: '' },
    { find: '👚', replace: '' },
    { find: '👛', replace: '' },
    { find: '👜', replace: '' },
    { find: '👝', replace: '' },
    { find: '🛍️', replace: '' },
    { find: '🎒', replace: '' },
    { find: '👞', replace: '' },
    { find: '👟', replace: '' },
    { find: '👠', replace: '' },
    { find: '👡', replace: '' },
    { find: '👢', replace: '' },
    { find: '👑', replace: '' },
    { find: '👒', replace: '' },
    { find: '🎩', replace: '' },
    { find: '🧢', replace: '' },
    { find: '⛑️', replace: '' },
    { find: '📿', replace: '' },
    { find: '💄', replace: '' },
    { find: '💍', replace: '' },
    { find: '💎', replace: '' },
    { find: '🔇', replace: '' },
    { find: '🔈', replace: '' },
    { find: '🔉', replace: '' },
    { find: '📢', replace: '' },
    { find: '📣', replace: '' },
    { find: '📯', replace: '' },
    { find: '🔕', replace: '' },
    { find: '🎼', replace: '' },
    { find: '🎵', replace: '' },
    { find: '🎶', replace: '' },
    { find: '🎙️', replace: '' },
    { find: '🎚️', replace: '' },
    { find: '🎛️', replace: '' },
    { find: '🎤', replace: '' },
    { find: '🎧', replace: '' },
    { find: '📻', replace: '' },
    { find: '🎷', replace: '' },
    { find: '🎸', replace: '' },
    { find: '🎹', replace: '' },
    { find: '🎺', replace: '' },
    { find: '🎻', replace: '' },
    { find: '🥁', replace: '' },
    { find: '📱', replace: '' },
    { find: '📲', replace: '' },
    { find: '☎️', replace: '' },
    { find: '📟', replace: '' },
    { find: '📠', replace: '' },
    { find: '🔋', replace: '' },
    { find: '🔌', replace: '' },
    { find: '💻', replace: '' },
    { find: '🖥️', replace: '' },
    { find: '🖨️', replace: '' },
    { find: '⌨️', replace: '' },
    { find: '🖱️', replace: '' },
    { find: '🖲️', replace: '' },
    { find: '💽', replace: '' },
    { find: '💿', replace: '' },
    { find: '📀', replace: '' },
    { find: '🎥', replace: '' },
    { find: '🎞️', replace: '' },
    { find: '📽️', replace: '' },
    { find: '🎬', replace: '' },
    { find: '📺', replace: '' },
    { find: '📷', replace: '' },
    { find: '📸', replace: '' },
    { find: '📹', replace: '' },
    { find: '📼', replace: '' },
    { find: '🔎', replace: '' },
    { find: '🕯️', replace: '' },
    { find: '🔦', replace: '' },
    { find: '🏮', replace: '' },
    { find: '📔', replace: '' },
    { find: '📕', replace: '' },
    { find: '📗', replace: '' },
    { find: '📘', replace: '' },
    { find: '📙', replace: '' },
    { find: '📓', replace: '' },
    { find: '📒', replace: '' },
    { find: '📃', replace: '' },
    { find: '📜', replace: '' },
    { find: '📄', replace: '' },
    { find: '📰', replace: '' },
    { find: '🗞️', replace: '' },
    { find: '📑', replace: '' },
    { find: '🔖', replace: '' },
    { find: '🏷️', replace: '' },
    { find: '💴', replace: '' },
    { find: '💵', replace: '' },
    { find: '💶', replace: '' },
    { find: '💷', replace: '' },
    { find: '💸', replace: '' },
    { find: '💳', replace: '' },
    { find: '🧾', replace: '' },
    { find: '💹', replace: '' },
    { find: '💱', replace: '' },
    { find: '💲', replace: '' },
    { find: '✉️', replace: '' },
    { find: '📨', replace: '' },
    { find: '📩', replace: '' },
    { find: '📤', replace: '' },
    { find: '📥', replace: '' },
    { find: '📦', replace: '' },
    { find: '📫', replace: '' },
    { find: '📪', replace: '' },
    { find: '📬', replace: '' },
    { find: '📭', replace: '' },
    { find: '📮', replace: '' },
    { find: '🗳️', replace: '' },
    { find: '✏️', replace: '' },
    { find: '✒️', replace: '' },
    { find: '🖋️', replace: '' },
    { find: '🖊️', replace: '' },
    { find: '🖍️', replace: '' },
    { find: '💼', replace: '' },
    { find: '📁', replace: '' },
    { find: '📂', replace: '' },
    { find: '🗂️', replace: '' },
    { find: '📆', replace: '' },
    { find: '🗒️', replace: '' },
    { find: '🗓️', replace: '' },
    { find: '📇', replace: '' },
    { find: '📉', replace: '' },
    { find: '📎', replace: '' },
    { find: '🖇️', replace: '' },
    { find: '🗃️', replace: '' },
    { find: '🗄️', replace: '' },
    { find: '🗑️', replace: '' },
    { find: '🔓', replace: '' },
    { find: '🔏', replace: '' },
    { find: '🔐', replace: '' },
    { find: '🗝️', replace: '' },
    { find: '🔨', replace: '' },
    { find: '⛏️', replace: '' },
    { find: '⚒️', replace: '' },
    { find: '🛠️', replace: '' },
    { find: '🗡️', replace: '' },
    { find: '⚔️', replace: '' },
    { find: '🔫', replace: '' },
    { find: '🏹', replace: '' },
    { find: '🛡️', replace: '' },
    { find: '🔧', replace: '' },
    { find: '🔩', replace: '' },
    { find: '🗜️', replace: '' },
    { find: '🔗', replace: '' },
    { find: '⛓️', replace: '' },
    { find: '🧰', replace: '' },
    { find: '🧲', replace: '' },
    { find: '⚗️', replace: '' },
    { find: '🔭', replace: '' },
    { find: '📡', replace: '' },
    { find: '💊', replace: '' },
    { find: '🩹', replace: '' },
    { find: '🩺', replace: '' },
    { find: '🌡️', replace: '' },
    { find: '🚽', replace: '' },
    { find: '🛀', replace: '' },
    { find: '🧻', replace: '' },
    { find: '🛒', replace: '' },
    { find: '🚬', replace: '' },
    { find: '⚰️', replace: '' },
    { find: '⚱️', replace: '' },
    { find: '🗿', replace: '' }
];

// Get all HTML files
const files = fs.readdirSync(baseDir).filter(f => f.endsWith('.html'));

let processedCount = 0;

files.forEach(file => {
    const filePath = path.join(baseDir, file);
    let content = fs.readFileSync(filePath, 'utf8');
    let originalContent = content;
    
    // Apply all replacements
    replacements.forEach(({ find, replace }) => {
        content = content.split(find).join(replace);
    });
    
    // Write back if changed
    if (content !== originalContent) {
        fs.writeFileSync(filePath, content, 'utf8');
        console.log(`Updated: ${file}`);
        processedCount++;
    }
});

console.log(`\nProcessing complete. ${processedCount} files were modified.`);
