import type {
  Chapter19ConceptFamilyId,
  Chapter19LearningObjectiveId,
} from './types'
import type { Chapter19Difficulty } from './grading'

export type Chapter19ReassessmentAnswer = 'a' | 'b' | 'c' | 'd'

export interface Chapter19ReassessmentQuestion {
  id: `r19-${string}`
  conceptFamilyId: Chapter19ConceptFamilyId
  learningObjectiveId: Chapter19LearningObjectiveId
  difficulty: Exclude<Chapter19Difficulty, 'recall'>
  question: string
  answer_a: string
  answer_b: string
  answer_c: string
  answer_d: string
  correctAnswer: Chapter19ReassessmentAnswer
  explanation: string
}

const q = (
  id: Chapter19ReassessmentQuestion['id'],
  conceptFamilyId: Chapter19ConceptFamilyId,
  learningObjectiveId: Chapter19LearningObjectiveId,
  difficulty: Chapter19ReassessmentQuestion['difficulty'],
  question: string,
  answer_a: string,
  answer_b: string,
  answer_c: string,
  answer_d: string,
  correctAnswer: Chapter19ReassessmentAnswer,
  explanation: string,
): Chapter19ReassessmentQuestion => ({
  id,
  conceptFamilyId,
  learningObjectiveId,
  difficulty,
  question,
  answer_a,
  answer_b,
  answer_c,
  answer_d,
  correctAnswer,
  explanation,
})

export const chapter19ReassessmentReserve: readonly Chapter19ReassessmentQuestion[] = [
  q(
    'r19-license-001',
    'ch19-licensing-requirements-verification',
    'LO-19-01',
    'application',
    'A student finds two websites with different barber licensing fees. Which source should control the decision?',
    'The website with the lower fee',
    'The most recent official licensing-agency source for that jurisdiction',
    'The website with more reviews',
    'A classmate who applied last year',
    'b',
    'Licensing fees and procedures can change. The current official licensing source for the applicable jurisdiction should control.',
  ),
  q(
    'r19-license-002',
    'ch19-licensing-requirements-verification',
    'LO-19-01',
    'scenario',
    'A candidate bulletin from last year lists one identification rule, but the current exam-provider page lists a different rule. What should the student do?',
    'Follow the older bulletin because it is a PDF',
    'Follow the current official provider instructions and confirm any conflict before test day',
    'Bring no identification and explain the conflict',
    'Ask another candidate which rule seems easier',
    'b',
    'Current official instructions should be verified before exam day when older materials conflict with newer provider guidance.',
  ),
  q(
    'r19-license-003',
    'ch19-licensing-requirements-verification',
    'LO-19-01',
    'understanding',
    'Why is it unsafe to memorize one national barber licensing checklist as universally correct?',
    'Because license names are always secret',
    'Because jurisdiction-specific requirements, fees, eligibility, and exam procedures can differ and change',
    'Because written exams are never used',
    'Because only employers decide who needs a license',
    'b',
    'Licensing authority comes from the applicable jurisdiction, so requirements must be verified rather than generalized across all states.',
  ),
  q(
    'r19-license-004',
    'ch19-licensing-requirements-verification',
    'LO-19-01',
    'application',
    'Before paying an examination fee, which action best reduces the risk of using outdated information?',
    'Confirm the fee and application process with the current official licensing or authorized exam-provider source',
    'Use the amount printed in an old workbook',
    'Pay the amount a friend remembers',
    'Wait until the test date to ask',
    'a',
    'Current official sources should be checked before payment because fees, eligibility, and procedures can change.',
  ),
  q(
    'r19-license-005',
    'ch19-licensing-requirements-verification',
    'LO-19-01',
    'scenario',
    'A student plans to move to another state immediately after graduation. What is the strongest licensing step?',
    'Assume the current state license automatically transfers',
    'Verify the destination jurisdiction’s current licensing, reciprocity, endorsement, or examination rules',
    'Use the current school handbook as final authority',
    'Start services in the new state and apply later',
    'b',
    'Interstate licensing treatment can vary. The destination jurisdiction’s current official rules should be verified before relying on transfer assumptions.',
  ),

  q(
    'r19-exam-001',
    'ch19-exam-preparation-test-reasoning',
    'LO-19-02',
    'application',
    'A student misses several practice questions because the word “except” is overlooked. What is the best correction?',
    'Read only the answer choices',
    'Slow down enough to identify qualifiers in the stem before evaluating choices',
    'Memorize the letter used most often',
    'Skip every question containing “except”',
    'b',
    'Qualifiers can reverse or narrow the task. Identifying them before evaluating answers improves reasoning accuracy.',
  ),
  q(
    'r19-exam-002',
    'ch19-exam-preparation-test-reasoning',
    'LO-19-02',
    'scenario',
    'A student scores well only when practice questions are repeated in the same order. What should the student change?',
    'Keep repeating the same order until it feels familiar',
    'Use varied questions and explain the reasoning behind each answer',
    'Stop reviewing missed concepts',
    'Choose answers by pattern recognition alone',
    'b',
    'Varied practice and explanation reduce dependence on memorized item order and strengthen transferable understanding.',
  ),
  q(
    'r19-exam-003',
    'ch19-exam-preparation-test-reasoning',
    'LO-19-02',
    'understanding',
    'What is the best use of elimination on a multiple-choice question?',
    'Remove choices that clearly conflict with the stem or known principles, then compare what remains',
    'Eliminate the shortest answer automatically',
    'Eliminate any answer containing the word “always” without reading it',
    'Use elimination instead of studying the subject',
    'a',
    'Elimination is a reasoning aid, not a substitute for content knowledge or careful reading.',
  ),
  q(
    'r19-exam-004',
    'ch19-exam-preparation-test-reasoning',
    'LO-19-02',
    'application',
    'A testing system does not allow a candidate to return to previous questions. Which strategy must change?',
    'The candidate should still answer easier questions first by skipping hard items',
    'The candidate should follow the system’s navigation rules and decide before moving on',
    'The candidate should ask the proctor to reopen every item',
    'The candidate should ignore the system instructions',
    'b',
    'Navigation strategies must follow the actual testing system. Advice to skip and return applies only when return navigation is permitted.',
  ),
  q(
    'r19-exam-005',
    'ch19-exam-preparation-test-reasoning',
    'LO-19-02',
    'scenario',
    'A student is using practice questions successfully but cannot explain why wrong choices are wrong. What does this suggest?',
    'The student should focus more on underlying concepts and reasoning',
    'The student has mastered the topic completely',
    'The student should stop studying content',
    'The student should answer faster',
    'a',
    'Being able to explain why choices are correct or incorrect is stronger evidence of understanding than recognizing a memorized answer.',
  ),

  q(
    'r19-safety-001',
    'ch19-practical-exam-safety-readiness',
    'LO-19-03',
    'scenario',
    'During practical-exam rehearsal, a student repeatedly touches a contaminated surface and then continues without the required infection-control response. What should be corrected first?',
    'Speed',
    'The infection-control process required by the current official instructions',
    'The haircut style',
    'The order of unrelated cosmetic steps',
    'b',
    'A required infection-control response is a safety process and must be corrected before speed is prioritized.',
  ),
  q(
    'r19-safety-002',
    'ch19-practical-exam-safety-readiness',
    'LO-19-03',
    'application',
    'A student’s practice kit includes an item not allowed by the current exam-provider instructions. What is the best action?',
    'Bring it anyway in case it helps',
    'Remove or replace it according to the current official kit rules',
    'Hide it under other supplies',
    'Use another state’s list instead',
    'b',
    'Practical-exam supplies must follow the current applicable provider instructions rather than assumptions from another source.',
  ),
  q(
    'r19-safety-003',
    'ch19-practical-exam-safety-readiness',
    'LO-19-03',
    'scenario',
    'A candidate is unsure whether a practical task uses a model, mannequin, or another format. What should the candidate do?',
    'Assume the school practice format is identical',
    'Verify the current official candidate instructions before rehearsing the final setup',
    'Prepare for only the format a friend used',
    'Wait until check-in to find out',
    'b',
    'Format details are provider- and jurisdiction-specific and should be verified before final preparation.',
  ),
  q(
    'r19-safety-004',
    'ch19-practical-exam-safety-readiness',
    'LO-19-03',
    'application',
    'A student can complete a procedure quickly but skips required sanitation steps under time pressure. Which performance should be treated as stronger?',
    'The faster performance',
    'The performance that preserves required infection-control and safety steps within the allowed time',
    'Whichever performance uses more tools',
    'Whichever performance looks more confident',
    'b',
    'Required safety steps are part of competent performance and should not be traded away merely to gain speed.',
  ),
  q(
    'r19-safety-005',
    'ch19-practical-exam-safety-readiness',
    'LO-19-03',
    'scenario',
    'A student notices that the official practical-exam instructions changed after months of practice. What is the safest preparation response?',
    'Continue the old routine because muscle memory matters more',
    'Update the practice routine to match the current official requirements and retrain the changed steps',
    'Ignore the change unless the school confirms it',
    'Use both versions during the exam',
    'b',
    'Current official requirements control. Practice should be updated when the provider changes required procedures or safety expectations.',
  ),

  q(
    'r19-ready-001',
    'ch19-employment-readiness-professionalism',
    'LO-19-04',
    'application',
    'A student is strong at cutting but often arrives late to school clinics. Which employment-readiness issue should be addressed?',
    'Only technical speed',
    'Dependability and professional work habits',
    'Portfolio color choice',
    'Exam-provider registration',
    'b',
    'Employment readiness includes dependable professional behavior as well as technical skill.',
  ),
  q(
    'r19-ready-002',
    'ch19-employment-readiness-professionalism',
    'LO-19-04',
    'scenario',
    'An employer asks whether the applicant has already earned a license that is still pending. What is the best response?',
    'Say yes because approval is expected',
    'State the current status accurately and explain any verified next step',
    'Avoid answering and change the subject',
    'Show a class certificate as if it were the license',
    'b',
    'Professional integrity requires accurate representation of credentials and current status.',
  ),
  q(
    'r19-ready-003',
    'ch19-employment-readiness-professionalism',
    'LO-19-04',
    'understanding',
    'Why is a personal skills inventory useful before job searching?',
    'It guarantees a job offer',
    'It helps identify strengths, gaps, and areas that need more practice',
    'It replaces licensing requirements',
    'It determines the legal employment classification',
    'b',
    'A self-inventory helps the student present strengths accurately and plan improvement for weaker areas.',
  ),
  q(
    'r19-ready-004',
    'ch19-employment-readiness-professionalism',
    'LO-19-04',
    'application',
    'Which statement best demonstrates professional accountability after making a minor mistake in a school clinic?',
    'Hide the mistake',
    'Acknowledge it, follow the instructor’s correction process, and learn from it',
    'Blame the client',
    'Claim the procedure was taught incorrectly',
    'b',
    'Accountability includes acknowledging errors and using feedback to improve future performance.',
  ),
  q(
    'r19-ready-005',
    'ch19-employment-readiness-professionalism',
    'LO-19-04',
    'scenario',
    'A student has retail and military leadership experience but no previous barbershop job. How should those experiences be handled?',
    'Omit them because they are not barbering jobs',
    'Identify truthful transferable skills that are relevant to the barbering role',
    'List them as barbering experience',
    'Convert them into licenses on the résumé',
    'b',
    'Relevant communication, leadership, scheduling, customer-service, or teamwork skills can transfer when presented accurately.',
  ),

  q(
    'r19-materials-001',
    'ch19-resume-portfolio-application-materials',
    'LO-19-05',
    'application',
    'Which résumé statement is strongest?',
    'Licensed barber, when the license is still pending',
    'Completed 1,200 documented training hours, if that number is accurate and relevant',
    'Best barber in the state',
    'Guaranteed to retain every client',
    'b',
    'Application materials should use accurate, supportable information rather than unearned credentials or unverifiable claims.',
  ),
  q(
    'r19-materials-002',
    'ch19-resume-portfolio-application-materials',
    'LO-19-05',
    'scenario',
    'A portfolio contains a client photo taken during school but the student never obtained permission to use it publicly. What is the best action?',
    'Use it because the service was performed by the student',
    'Do not use it until appropriate permission and applicable policy requirements are satisfied',
    'Crop the face and assume permission is unnecessary',
    'Post it first and ask later',
    'b',
    'Client-image use should respect permission and applicable school or workplace policies.',
  ),
  q(
    'r19-materials-003',
    'ch19-resume-portfolio-application-materials',
    'LO-19-05',
    'understanding',
    'What is the main relationship between a résumé and a cover letter?',
    'They should contain exactly the same text',
    'The cover letter should connect relevant qualifications to the opportunity while the résumé summarizes qualifications and experience',
    'The résumé should contain only references',
    'The cover letter replaces all application forms',
    'b',
    'The two documents serve related but different purposes and should support rather than duplicate each other.',
  ),
  q(
    'r19-materials-004',
    'ch19-resume-portfolio-application-materials',
    'LO-19-05',
    'application',
    'An employer requests an online application after receiving a résumé. What should the applicant do?',
    'Refuse because the résumé is enough',
    'Complete the requested application accurately and consistently',
    'Copy unrelated information into every field',
    'Change dates to make the history look stronger',
    'b',
    'Employers may use their own application process. Information should remain accurate and consistent across materials.',
  ),
  q(
    'r19-materials-005',
    'ch19-resume-portfolio-application-materials',
    'LO-19-05',
    'scenario',
    'A student has excellent work samples but a résumé with inconsistent dates. Which issue should be corrected before submitting the application?',
    'Only the portfolio order',
    'The inconsistent résumé information',
    'The paper color',
    'The number of social-media followers',
    'b',
    'Accuracy and consistency in application materials are foundational to professional credibility.',
  ),

  q(
    'r19-search-001',
    'ch19-job-search-shop-research-interview',
    'LO-19-06',
    'application',
    'Before accepting a position, which question is most useful for understanding the opportunity?',
    'What is the owner’s favorite haircut?',
    'What are the schedule, compensation structure, service expectations, support, and growth opportunities?',
    'How many followers does the shop have?',
    'Does every barber use the same chair?',
    'b',
    'Employment research should focus on material expectations and conditions that affect fit and development.',
  ),
  q(
    'r19-search-002',
    'ch19-job-search-shop-research-interview',
    'LO-19-06',
    'scenario',
    'A shop’s website says one thing about hours, but the interviewer describes another schedule. What should the applicant do?',
    'Assume the website is legally binding',
    'Clarify the current schedule directly before deciding',
    'Ignore the difference',
    'Accept first and ask after starting',
    'b',
    'Public information can be outdated. Important terms should be clarified directly.',
  ),
  q(
    'r19-search-003',
    'ch19-job-search-shop-research-interview',
    'LO-19-06',
    'application',
    'An interviewer says a decision will be sent next Tuesday. When is professional follow-up most appropriate?',
    'Call several times before Tuesday',
    'Respect the stated timeline and follow up afterward if needed',
    'Visit the shop every morning',
    'Send messages to other employees asking for the result',
    'b',
    'Professional follow-up should respect the employer’s stated communication timeline.',
  ),
  q(
    'r19-search-004',
    'ch19-job-search-shop-research-interview',
    'LO-19-06',
    'understanding',
    'Why should an applicant research a shop before an interview?',
    'To memorize personal details about employees',
    'To understand services, culture, expectations, and questions worth clarifying',
    'To avoid preparing examples of their own experience',
    'To determine whether licensing rules can be ignored',
    'b',
    'Research helps the applicant evaluate fit and prepare relevant questions without replacing direct clarification of important terms.',
  ),
  q(
    'r19-search-005',
    'ch19-job-search-shop-research-interview',
    'LO-19-06',
    'scenario',
    'A student arrives at the interview location but the suite number does not match the original message. What was the best preventive step?',
    'Arrive exactly at the appointment time and search then',
    'Confirm the address, suite, time, and contact person in advance',
    'Assume navigation apps are always current',
    'Skip route planning because the city is familiar',
    'b',
    'Interview logistics should be confirmed in advance to reduce avoidable delays.',
  ),

  q(
    'r19-law-001',
    'ch19-employment-law-contracts-compliance',
    'LO-19-07',
    'application',
    'A generic online article says a particular interview question is always illegal. What is the strongest next step?',
    'Treat the article as final authority in every state',
    'Verify the applicable rule through an appropriate official, workforce, or qualified legal resource',
    'Assume the employer can ask anything',
    'Treat the issue as a physical-safety emergency',
    'b',
    'Interview-law boundaries can vary by jurisdiction and situation, so generic lists should not be treated as universal legal authority.',
  ),
  q(
    'r19-law-002',
    'ch19-employment-law-contracts-compliance',
    'LO-19-07',
    'scenario',
    'A written booth-rental agreement contains a clause the student does not understand. What is the best response before signing?',
    'Sign because every written clause is enforceable',
    'Ask about the clause, keep a copy, and seek qualified legal advice when the consequences are significant',
    'Ignore the clause because booth-rental contracts are never enforceable',
    'Ask a customer to interpret it',
    'b',
    'Agreement meaning and enforceability depend on wording, facts, and applicable law.',
  ),
  q(
    'r19-law-003',
    'ch19-employment-law-contracts-compliance',
    'LO-19-07',
    'understanding',
    'Why should “employee,” “independent contractor,” and “booth renter” not be treated as interchangeable labels?',
    'Because each label has the same legal effect',
    'Because the actual relationship and applicable law can affect classification and obligations',
    'Because only the worker’s preferred title matters',
    'Because classification is determined by résumé wording',
    'b',
    'Work classification can have legal and financial consequences and should not be reduced to a casual label.',
  ),
  q(
    'r19-law-004',
    'ch19-employment-law-contracts-compliance',
    'LO-19-07',
    'application',
    'A noncompete clause appears in an agreement. Which statement is safest?',
    'It is automatically enforceable everywhere',
    'It is automatically void everywhere',
    'Its meaning and enforceability depend on wording and applicable law',
    'It can be ignored if the applicant dislikes it',
    'c',
    'Restrictive-covenant treatment varies, so blanket conclusions should be avoided.',
  ),
  q(
    'r19-law-005',
    'ch19-employment-law-contracts-compliance',
    'LO-19-07',
    'scenario',
    'An interviewer asks a question that makes the applicant concerned about discrimination. What is the strongest general approach?',
    'Confront the interviewer using a generic online list as final authority',
    'Stay professional and verify the applicable legal rule through an appropriate source',
    'Assume all personal questions are legal',
    'Treat the question as proof of illegal conduct without further context',
    'b',
    'The student should avoid universal legal conclusions and use an appropriate official, workforce, or qualified legal source to verify the applicable rule.',
  ),
]

export function getChapter19ReassessmentReserve(
  conceptFamilyId: Chapter19ConceptFamilyId,
): readonly Chapter19ReassessmentQuestion[] {
  return chapter19ReassessmentReserve.filter(
    (question) => question.conceptFamilyId === conceptFamilyId,
  )
}
