import type { Chapter18ConceptFamilyId } from './types'
import type { Chapter18Difficulty } from './grading'

export type Chapter18ReassessmentAnswer = 'a' | 'b' | 'c' | 'd'

export interface Chapter18ReassessmentQuestion {
  id: `r18-${string}`
  conceptFamilyId: Chapter18ConceptFamilyId
  difficulty: Exclude<Chapter18Difficulty, 'recall'>
  question: string
  answer_a: string
  answer_b: string
  answer_c: string
  answer_d: string
  correctAnswer: Chapter18ReassessmentAnswer
  explanation: string
}

const q = (
  id: Chapter18ReassessmentQuestion['id'],
  conceptFamilyId: Chapter18ConceptFamilyId,
  difficulty: Chapter18ReassessmentQuestion['difficulty'],
  question: string,
  answer_a: string,
  answer_b: string,
  answer_c: string,
  answer_d: string,
  correctAnswer: Chapter18ReassessmentAnswer,
  explanation: string,
): Chapter18ReassessmentQuestion => ({
  id, conceptFamilyId, difficulty, question,
  answer_a, answer_b, answer_c, answer_d, correctAnswer, explanation,
})

export const chapter18ReassessmentReserve: readonly Chapter18ReassessmentQuestion[] = [
  q('r18-analysis-001','ch18-analysis-structure','application',
    'Why should porosity be considered before choosing a haircolor plan?',
    'It determines the exact developer volume by itself','It helps predict how unevenly different areas may take or release color','It replaces the need to assess elasticity','It guarantees the final tone',
    'b','Porosity can affect uptake and retention, but it must be considered with integrity, elasticity, history, level, and product guidance.'),
  q('r18-analysis-002','ch18-analysis-structure','scenario',
    'The regrowth appears healthy, but the mids and ends are fragile and very porous. What is the best next step before a chemical color service?',
    'Use the same formula and timing everywhere automatically','Analyze the zones separately and use a strand test when appropriate','Increase developer on the porous lengths','Ignore the lengths because only regrowth matters',
    'b','Different zones can respond differently. Analyze them separately and use testing when appropriate before committing to one formula.'),
  q('r18-analysis-003','ch18-analysis-structure','understanding',
    'What does elasticity contribute to a haircolor consultation?',
    'It identifies the exact natural level','It gives evidence about fiber integrity and how well hair tolerates manipulation','It determines the gray percentage','It replaces scalp analysis',
    'b','Elasticity is one indicator of fiber condition and must be interpreted with the rest of the analysis.'),
  q('r18-analysis-004','ch18-analysis-structure','application',
    'A client has fine hair with high porosity and a history of repeated lightening. Which principle is most appropriate?',
    'Choose stronger chemistry because fine hair processes slowly','Treat the history and condition as important limits when planning the service','Use density alone to select the formula','Assume porosity guarantees better color retention',
    'b','Repeated lightening and high porosity can increase vulnerability; planning must account for condition, history, and product-system limits.'),
  q('r18-analysis-005','ch18-analysis-structure','scenario',
    'A client wants a major color change, but the hair analysis shows questionable integrity. What should guide the decision?',
    'The desired shade alone','Hair/scalp analysis, service history, testing when appropriate, and product directions','Only the amount of gray hair','Only the client’s willingness to accept risk',
    'b','Service suitability should be based on the full analysis and verified product guidance, not preference alone.'),

  q('r18-theory-001','ch18-color-theory','understanding',
    'What is the best description of level in professional haircolor?',
    'The relative lightness or darkness of a color','The developer volume','The amount of gray coverage','The warmth of a shade only',
    'a','Level describes relative lightness or darkness; numbering conventions can vary by manufacturer.'),
  q('r18-theory-002','ch18-color-theory','application',
    'A pre-lightened section shows strong yellow warmth and the target is cooler. Which complementary direction is used to reduce yellow?',
    'Violet','Orange','Red','Gold',
    'a','Violet is complementary to yellow in traditional color theory. The exact formula still depends on level, hair condition, and the product system.'),
  q('r18-theory-003','ch18-color-theory','scenario',
    'A client wants to reduce unwanted red influence. Which color-wheel relationship should guide the tonal correction?',
    'Use the complementary direction to red','Use more red','Ignore tone and change developer volume','Use any darker shade',
    'a','Complementary relationships guide tonal neutralization; the exact formula still depends on the selected professional system.'),
  q('r18-theory-004','ch18-color-theory','understanding',
    'Why should a barber avoid treating one numeric level chart as universal across all brands?',
    'Because level is unrelated to lightness','Because numbering and shade naming systems can vary by manufacturer','Because level charts apply only to lighteners','Because every brand uses letters only',
    'b','Professional color systems do not all use identical numbering or naming conventions.'),
  q('r18-theory-005','ch18-color-theory','application',
    'A formula must address both target level and unwanted tone. What is the best planning approach?',
    'Choose developer volume first and ignore tone','Use level and tonal relationships together with the product system’s formulation guidance','Choose only the darkest available shade','Use complementary color without considering level',
    'b','Level and tone are separate but related planning variables and should be used together with manufacturer guidance.'),

  q('r18-products-001','ch18-color-products','understanding',
    'Which statement best distinguishes many demipermanent systems from many direct-dye semipermanent systems?',
    'Demipermanent systems commonly use oxidative chemistry with a dedicated activator','Demipermanent color always lifts several levels','Semipermanent color always requires 20-volume developer','Both systems are chemically identical',
    'a','Many demipermanent systems use oxidative chemistry with a dedicated low-strength developer or activator, while many semipermanent systems are direct-dye deposit products.'),
  q('r18-products-002','ch18-color-products','application',
    'A client asks whether a temporary or semipermanent product has a guaranteed fixed shampoo count. What is the best response?',
    'Yes, every product in the category lasts the same number of shampoos','Longevity varies by formula, hair condition, use, and manufacturer claims','Only hair density matters','Developer volume sets the wash count',
    'b','Longevity is product- and hair-dependent rather than one universal wash-count rule.'),
  q('r18-products-003','ch18-color-products','scenario',
    'A client wants durable gray coverage. Which product-selection principle is strongest?',
    'Choose any direct dye','Choose a system whose manufacturer specifically supports the desired gray-coverage result','Choose by fragrance','Choose developer volume without considering the color line',
    'b','Gray-coverage capability and formulation guidance are specific to the chosen product system.'),
  q('r18-products-004','ch18-color-products','understanding',
    'Why is it risky to describe all permanent haircolor as producing the same amount of lift?',
    'Because lift depends on the complete product system, starting hair, and manufacturer instructions','Because permanent color never lifts','Because only toner lifts','Because level and lift mean the same thing',
    'a','The amount of lift is not determined by the category name alone.'),
  q('r18-products-005','ch18-color-products','application',
    'What should a professional verify before substituting one color product class for another?',
    'Only the shade name','The chemistry, intended result, use directions, and compatibility of the selected system','Only the package size','Only the client’s appointment length',
    'b','Different product classes may use different chemistry and are not interchangeable by shade name alone.'),

  q('r18-dev-001','ch18-developers-lighteners-toners','application',
    'What should determine developer strength for a specific professional color service?',
    'A universal 10/20/30/40 lift chart','The exact product system’s permitted developers, ratio, intended use, and hair analysis','Hair density alone','The strongest developer available',
    'b','Developer selection must stay within the selected system’s technical guidance and the client’s hair condition.'),
  q('r18-dev-002','ch18-developers-lighteners-toners','scenario',
    'A lightener is labeled off-scalp only, but the desired placement reaches the scalp. What is the correct response?',
    'Dilute it and use it on scalp','Use an appropriate manufacturer-approved system for the intended application area','Reduce processing time and proceed','Add conditioner to make it safe',
    'b','Application-area restrictions are product-specific safety limits and should not be improvised around.'),
  q('r18-dev-003','ch18-developers-lighteners-toners','understanding',
    'Why should toner chemistry be treated as product-system specific?',
    'Because every toner uses the same chemistry','Because different toner systems may use different chemistry, activators, mixing ratios, and directions','Because toner never requires manufacturer directions','Because toner is only a shampoo',
    'b','Toner systems vary, so the exact product directions control use.'),
  q('r18-dev-004','ch18-developers-lighteners-toners','application',
    'A lightener is processing more slowly than expected. What is the safest general response?',
    'Automatically add heat','Automatically increase developer strength mid-service','Evaluate the hair and follow the selected product’s processing limits and directions','Add more lightener repeatedly',
    'c','Processing changes should not be improvised outside the product system and observed hair condition.'),
  q('r18-dev-005','ch18-developers-lighteners-toners','scenario',
    'Previously lightened ends are fragile during a retouch. What should guide placement?',
    'Overlap all lightener for consistency','Target new growth and protect previously lightened or sensitized areas from unapproved overlap','Use stronger developer on the ends','Ignore prior lightening',
    'b','Retouch placement should avoid unnecessary overlap onto vulnerable previously lightened hair.'),

  q('r18-apply-001','ch18-application-consultation-procedures','scenario',
    'A client cannot identify the home color product used recently. What should happen before a major oxidative service?',
    'Assume it is compatible','Clarify the history as much as possible and use manufacturer-supported compatibility or strand testing before proceeding','Use stronger developer','Skip consultation if the hair feels soft',
    'b','Unknown chemical history can change compatibility and predictability and should be resolved as far as possible before service.'),
  q('r18-apply-002','ch18-application-consultation-procedures','application',
    'What is the best general principle for a lightener retouch?',
    'Reapply to all previously lightened hair','Concentrate application on new growth while following the product’s placement instructions','Apply only to the ends','Use one universal timing rule',
    'b','Retouch work generally targets new growth while respecting the system’s application and overlap rules.'),
  q('r18-apply-003','ch18-application-consultation-procedures','understanding',
    'Why are client service records useful in haircoloring?',
    'They replace consultation','They help track prior formulas, results, reactions, and service history for future planning','They determine the legal developer volume','They remove the need for strand testing',
    'b','Accurate records support safer, more consistent future planning but do not replace current analysis.'),
  q('r18-apply-004','ch18-application-consultation-procedures','scenario',
    'A client requests beard color using a product labeled only for scalp hair. What is the best response?',
    'Use it for half the processing time','Use it only if the manufacturer expressly permits that facial-hair application; otherwise choose an appropriate product','Mix it with conditioner','Apply extra barrier cream and proceed',
    'b','Do not transfer scalp-hair directions to facial hair by assumption.'),
  q('r18-apply-005','ch18-application-consultation-procedures','application',
    'What should determine whether a strand test is useful before a corrective or major color change?',
    'A universal requirement for every service regardless of product','The service plan, hair condition/history, and manufacturer guidance','Only the client’s age','Only the amount of gray hair',
    'b','Strand testing is a planning tool used when appropriate for the service and product system.'),

  q('r18-correct-001','ch18-correction-gray-porosity','scenario',
    'Previously lightened porous lengths are being taken darker. What is the best first planning step?',
    'Use 40-volume developer','Assess the condition and choose a manufacturer-supported tint-back, filler, or equalization strategy','Always choose a shade two levels lighter','Ignore porosity',
    'b','Tint-back planning should be based on analysis and the selected system rather than a universal formula.'),
  q('r18-correct-002','ch18-correction-gray-porosity','application',
    'What should determine a gray-coverage formula?',
    'A universal percentage rule','The chosen system’s gray-coverage capability, shade guidance, developer, ratio, timing, and the client’s hair','Client age alone','Hair density alone',
    'b','Gray-coverage formulation is product-system specific.'),
  q('r18-correct-003','ch18-correction-gray-porosity','understanding',
    'Why can porous hair produce an uneven color result?',
    'Porosity can affect how readily different areas take and retain color','Porosity affects only haircutting','Porosity guarantees uniform absorption','Porosity determines natural level',
    'a','Differences in porosity can cause different areas to respond differently to color.'),
  q('r18-correct-004','ch18-correction-gray-porosity','scenario',
    'A highly porous area grabs color darker than expected during a test strand. What should the professional do next?',
    'Ignore the result','Use the test result to adjust the plan using the product system’s supported porosity/equalization strategy','Increase developer automatically','Apply the same formula faster',
    'b','A strand-test result is evidence for adjusting the service plan rather than ignoring the difference.'),
  q('r18-correct-005','ch18-correction-gray-porosity','application',
    'When is a filler or replacement-tone strategy appropriate?',
    'For every color service','When the analysis and selected product system indicate missing underlying tone should be replaced during a tint-back or correction','Whenever hair is dense','Only when using temporary color',
    'b','Fillers or replacement-tone strategies are situation- and system-specific tools, not universal steps.'),

  q('r18-safe-001','ch18-service-safety-chemical-handling','scenario',
    'The planned color area is visibly sunburned and irritated. What is the safest action?',
    'Use weaker developer','Postpone the chemical color service rather than applying product to compromised tissue','Ask the client to sign a waiver','Apply barrier cream and continue',
    'b','Haircolor should not be applied over visibly irritated, sunburned, or otherwise compromised scalp tissue.'),
  q('r18-safe-002','ch18-service-safety-chemical-handling','application',
    'What is the best approach to product allergy-alert or skin-test instructions?',
    'Use one universal timing rule for every product','Follow the exact product directions for the current use and do not rely on a prior uneventful service','Skip testing after one successful service','Test only permanent color',
    'b','Product-specific directions control the allergy-alert or skin-test procedure.'),
  q('r18-safe-003','ch18-service-safety-chemical-handling','scenario',
    'A developer bottle is swollen and leaking. What should happen?',
    'Open it carefully and use it first','Do not use it; secure it and follow manufacturer/workplace handling and disposal directions','Transfer it to an unlabeled container','Dilute it with water',
    'b','Compromised chemical packaging should not be used or improvised with.'),
  q('r18-safe-004','ch18-service-safety-chemical-handling','scenario',
    'A client reports a history of an unknown progressive or metallic-salt color before a planned oxidative service. What is the safest planning response?',
    'Proceed because all color systems are compatible','Treat the history as a compatibility concern and verify the planned system before proceeding','Use the strongest developer','Ignore the history if the hair looks healthy',
    'b','Unknown or potentially incompatible prior chemistry requires verification before a new oxidative service.'),
  q('r18-safe-005','ch18-service-safety-chemical-handling','application',
    'Which principle best protects against lightener overprocessing?',
    'Extend time whenever lift is slow','Follow product limits, monitor hair integrity, and avoid unapproved overlap onto previously lightened or sensitized hair','Use heat automatically','Apply more product to fragile ends',
    'b','Lightening must stay within manufacturer limits and hair-integrity boundaries.'),
]

export function getChapter18ReassessmentReserve(
  conceptFamilyId: Chapter18ConceptFamilyId,
): readonly Chapter18ReassessmentQuestion[] {
  return chapter18ReassessmentReserve.filter((question) => question.conceptFamilyId === conceptFamilyId)
}
