/**
 * Execution — Execution Queue Model
 *
 * Immutable models representing an ordered queue of executable work items.
 * Generated by the ExecutionQueueBuilder from an ExecutionSession.
 * All items begin as Pending — no execution, no scheduling, no mutation.
 *
 * Milestone 6.2.2: execution queue model only.
 */

// ============================================================================
// QUEUE ITEM STATUS
// ============================================================================

/**
 * The status of a single queue item.
 *
 * - Pending: Item is ready for execution.
 * - Waiting: Item is waiting on a dependency.
 * - Completed: Item finished successfully.
 * - Failed: Item encountered an error.
 * - Skipped: Item was skipped.
 */
export type ExecutionQueueItemStatus = 'Pending' | 'Waiting' | 'Completed' | 'Failed' | 'Skipped'

// ============================================================================
// EXECUTION QUEUE ITEM
// ============================================================================

/**
 * A single item in the execution queue.
 *
 * Immutable: consumers should treat instances as read-only.
 */
export interface ExecutionQueueItem {
  /** Stable identifier for this queue item. */
  readonly itemId: string

  /** The phase this item belongs to. */
  readonly phaseId: string

  /** The step this item represents. */
  readonly stepId: string

  /** Zero-based position in the queue. */
  readonly order: number

  /** Current status of this item. */
  readonly status: ExecutionQueueItemStatus
}

// ============================================================================
// EXECUTION QUEUE
// ============================================================================

/**
 * An ordered, immutable queue of executable work items.
 *
 * Immutable: consumers should treat instances as read-only.
 */
export interface ExecutionQueue {
  /** Stable identifier for this queue. */
  readonly queueId: string

  /** Version of the queue builder. */
  readonly queueVersion: string

  /** The ordered items in this queue. */
  readonly items: readonly ExecutionQueueItem[]

  /** Generic extensible metadata. */
  readonly metadata?: Record<string, unknown>
}
