import type { Chapter17ConceptFamilyId } from './types'
import type { Chapter17Difficulty } from './grading'

export type Chapter17ReassessmentAnswer = 'a' | 'b' | 'c' | 'd'

export interface Chapter17ReassessmentQuestion {
  id: `r17-${string}`
  conceptFamilyId: Chapter17ConceptFamilyId
  difficulty: Exclude<Chapter17Difficulty, 'recall'>
  question: string
  answer_a: string
  answer_b: string
  answer_c: string
  answer_d: string
  correctAnswer: Chapter17ReassessmentAnswer
  explanation: string
}

const q = (
  id: Chapter17ReassessmentQuestion['id'],
  conceptFamilyId: Chapter17ConceptFamilyId,
  difficulty: Chapter17ReassessmentQuestion['difficulty'],
  question: string,
  answer_a: string,
  answer_b: string,
  answer_c: string,
  answer_d: string,
  correctAnswer: Chapter17ReassessmentAnswer,
  explanation: string,
): Chapter17ReassessmentQuestion => ({
  id, conceptFamilyId, difficulty, question,
  answer_a, answer_b, answer_c, answer_d, correctAnswer, explanation,
})

export const chapter17ReassessmentReserve: readonly Chapter17ReassessmentQuestion[] = [
  q('r17-consult-001','ch17-consultation-hair-analysis','scenario',
    'A client with a long chemical-service history is unsure which relaxer was used previously. What should happen before a new texture service is planned?',
    'Assume the prior product was compatible','Clarify the service history and verify compatibility before proceeding','Use only porosity to decide','Proceed with the shortest possible time',
    'b','Unknown prior chemistry is a compatibility concern. Clarify the history and verify the selected product system before proceeding.'),
  q('r17-consult-002','ch17-consultation-hair-analysis','application',
    'Which combination gives the strongest basis for deciding whether a chemical texture service is appropriate?',
    'Porosity alone','Client preference and appointment length','Hair/scalp analysis, prior service history, required testing, and product directions','Hair density alone',
    'c','Service suitability should be based on the complete analysis, history, testing, and product-specific guidance.'),
  q('r17-consult-003','ch17-consultation-hair-analysis','scenario',
    'Visible irritation is present in the planned chemical-service area. What is the appropriate response?',
    'Use a weaker product and continue','Postpone the chemical service and follow appropriate safety/referral guidance','Cover the area and proceed','Let the client sign a waiver',
    'b','Do not perform the chemical service over visibly compromised tissue.'),
  q('r17-consult-004','ch17-consultation-hair-analysis','understanding',
    'What does porosity contribute to a chemical-texture consultation?',
    'It alone determines processing time','It helps indicate how readily hair may accept product and must be considered with the full analysis','It determines the exact chemical family to use','It replaces service history',
    'b','Porosity is one part of a broader assessment rather than a standalone processing rule.'),
  q('r17-consult-005','ch17-consultation-hair-analysis','application',
    'A client wants a chemical service even though required testing cannot be completed reliably. What is the best decision?',
    'Proceed at half the normal time','Proceed only on the ends','Delay or decline the service until the required analysis/testing can be completed safely','Use stronger protection cream',
    'c','Required analysis and testing should not be bypassed to complete the service.'),

  q('r17-chem-001','ch17-chemistry-bond-transformation','understanding',
    'Which statement correctly compares thio and hydroxide chemistry?',
    'Both use the same reduction/oxidation cycle','Thio systems use reduction and compatible oxidation, while hydroxide relaxers use lanthionization chemistry','Hydroxide services only change hydrogen bonds','Thio services do not affect disulfide bonds',
    'b','The two chemical families use different pathways and should not be taught as one identical process.'),
  q('r17-chem-002','ch17-chemistry-bond-transformation','application',
    'Why should an oxidizing neutralizer not be described as the universal finishing step for every relaxer?',
    'Because neutralizers are only cosmetic','Because hydroxide relaxers use a different post-service finishing sequence','Because all relaxers air-neutralize','Because neutralization is optional',
    'b','Oxidizing neutralization applies to compatible thio/permanent-wave systems, not as a universal hydroxide step.'),
  q('r17-chem-003','ch17-chemistry-bond-transformation','scenario',
    'A student says hydroxide and thio are interchangeable because both change hair texture. What is the best correction?',
    'They are interchangeable if the hair is strong','They create similar visual goals but use different chemistry and compatibility rules','They differ only in fragrance','They differ only in processing time',
    'b','Similar service goals do not make different chemical families interchangeable.'),
  q('r17-chem-004','ch17-chemistry-bond-transformation','understanding',
    'What role do disulfide bonds play in many chemical texture services?',
    'They are irrelevant to cortex shape','They are strong side bonds involved in hair shape; how they are altered depends on the chemical system','They are only surface cuticle bonds','They are changed only by heat',
    'b','Disulfide bonds are central to many texture changes, but the mechanism depends on the product family.'),
  q('r17-chem-005','ch17-chemistry-bond-transformation','application',
    'What should guide the chemistry explanation given for a specific chemical texture service?',
    'One universal R-R-O mnemonic for every product','The actual product family and its chemical sequence','The client’s desired result only','Whether the service is performed quickly',
    'b','The chemistry explanation must match the actual product system rather than force all services into one model.'),

  q('r17-perm-001','ch17-permanent-waving-procedures','scenario',
    'A waving system specifies how and when to check test curls. What should the barber do?',
    'Use exactly three test curls regardless of instructions','Follow the product-directed intervals and locations while monitoring the hair','Skip test curls if a timer is running','Double the interval for resistant hair automatically',
    'b','Representative test-curl checks should follow the selected system and service plan.'),
  q('r17-perm-002','ch17-permanent-waving-procedures','application',
    'What should determine added heat during a permanent-wave service?',
    'All acid-balanced waves require it','All alkaline waves prohibit it','The selected product directions and service conditions','Hair density alone',
    'c','Heat use is product-specific rather than a universal acid-versus-alkaline rule.'),
  q('r17-perm-003','ch17-permanent-waving-procedures','scenario',
    'A wave appears to be processing slowly. What is the safest next step?',
    'Automatically add heat and extend time','Follow the product’s evaluation procedure and reassess the hair before changing anything','Switch chemicals mid-service','Apply more solution repeatedly',
    'b','Do not improvise processing changes outside the product directions and observed hair condition.'),
  q('r17-perm-004','ch17-permanent-waving-procedures','understanding',
    'Why must waving solution be rinsed thoroughly before the compatible neutralizer is applied?',
    'To change natural hair color','To remove the waving solution as directed before the next chemical step','To make every wave process faster','To replace blotting',
    'b','Correct rinsing is part of the required service sequence before compatible neutralization.'),
  q('r17-perm-005','ch17-permanent-waving-procedures','application',
    'What can excessive processing do to the hair?',
    'Guarantee a stronger curl','Increase weakness, breakage risk, or an unwanted result','Make neutralization unnecessary','Improve every resistant hair result',
    'b','Processing beyond what the hair/product system supports can weaken the fiber and compromise the result.'),

  q('r17-relax-001','ch17-chemical-relaxing-procedures','understanding',
    'What is a key chemistry feature of hydroxide relaxers?',
    'They rely on the same thio reduction/oxidation cycle','They use highly alkaline chemistry and lanthionization','They only alter hydrogen bonds temporarily','They require an oxidizing perm neutralizer',
    'b','Hydroxide relaxing uses lanthionization rather than the thio reduction/oxidation cycle.'),
  q('r17-relax-002','ch17-chemical-relaxing-procedures','scenario',
    'A client reports burning or pain while relaxer is processing. What should happen?',
    'Continue until the timer expires','Stop the service and remove the product according to its safety directions','Add more base cream over the relaxer','Switch brands without rinsing',
    'b','Burning or pain requires stopping exposure and following the product’s removal/safety directions.'),
  q('r17-relax-003','ch17-chemical-relaxing-procedures','application',
    'What does “no-base” mean in relaxer service planning?',
    'No protective measures are needed','The same full scalp-base step is not required, but product-specific protection directions still apply','The product is always weaker','The product should touch irritated scalp',
    'b','No-base does not mean no protection or unrestricted scalp contact.'),
  q('r17-relax-004','ch17-chemical-relaxing-procedures','scenario',
    'Hair previously treated with hydroxide relaxer is being considered for a thio service. What is the safest rule?',
    'A strand test automatically overrides compatibility concerns','Treat it as incompatible unless verified product-system guidance explicitly supports the service','Proceed after a fixed six-month wait','Use extra neutralizer',
    'b','Known hydroxide/thio incompatibility is not erased by time alone or by a strand test.'),
  q('r17-relax-005','ch17-chemical-relaxing-procedures','application',
    'What should guide relaxer processing time?',
    'A universal time for every client','The selected product directions, hair analysis, and ongoing service monitoring','Only hair density','The client’s desired straightness',
    'b','Processing is controlled by the specific system and the condition being observed, not a universal time.'),

  q('r17-curl-001','ch17-curl-reformation','scenario',
    'Before curl reformation, prior chemical history cannot be verified. What is the best response?',
    'Proceed with the mildest available formula','Clarify the history and verify compatibility before starting the multi-stage service','Skip the first stage','Use extra conditioner',
    'b','Unclear prior chemistry creates a compatibility risk that must be resolved before a multi-stage chemical service.'),
  q('r17-curl-002','ch17-curl-reformation','understanding',
    'Why is curl reformation treated as a higher-control service?',
    'It is only a styling service','It chemically restructures hair through multiple stages, increasing the importance of compatibility and process control','It always uses heat','It never requires neutralization',
    'b','Multiple chemical stages increase the importance of correct sequence, condition checks, and compatibility.'),
  q('r17-curl-003','ch17-curl-reformation','application',
    'What should guide movement from one curl-reformation stage to the next?',
    'A universal timer only','The verified service sequence, product directions, and hair condition','Client preference alone','Whether the first stage looks finished from a distance',
    'b','Each stage should proceed only according to the verified chemical sequence and current hair condition.'),
  q('r17-curl-004','ch17-curl-reformation','scenario',
    'The hair shows significant weakness after an early service stage. What is the safest response?',
    'Continue because the final stage will restore strength','Stop and reassess rather than automatically continuing through the sequence','Add heat to finish sooner','Use more product',
    'b','Do not continue a multi-stage chemical service automatically when the hair shows concerning weakness.'),
  q('r17-curl-005','ch17-curl-reformation','application',
    'Which factor is most important when selecting a curl-reformation system?',
    'Using the same system for every client','Compatibility with prior chemistry, fiber condition, and the manufacturer’s directions','The fastest available system','The largest rod available',
    'b','System selection must fit the client’s chemical history, hair condition, and verified product guidance.'),

  q('r17-safe-001','ch17-safety-strand-tests-compatibility','scenario',
    'A strand test appears acceptable, but the known prior chemistry is incompatible with the planned service. What should happen?',
    'Proceed because the strand test passed','Do not use the test to override the known incompatibility','Repeat the test with more product','Use a shorter processing time',
    'b','A strand test does not make a known incompatible chemical history safe.'),
  q('r17-safe-002','ch17-safety-strand-tests-compatibility','application',
    'What is the best role of porosity and elasticity assessments in safety planning?',
    'Each can independently guarantee a safe service','They add evidence about fiber condition but remain part of a broader compatibility and contraindication review','They replace manufacturer directions','They replace prior chemical history',
    'b','Testing contributes to the decision but does not replace history, compatibility, or product guidance.'),
  q('r17-safe-003','ch17-safety-strand-tests-compatibility','scenario',
    'A client has visible abrasions in the intended application area. What is the correct action?',
    'Cover them and apply product around them','Postpone the chemical service and follow appropriate safety/referral guidance','Proceed with half-strength product','Ask the client to accept responsibility',
    'b','Visible scalp compromise is a reason to postpone the chemical service.'),
  q('r17-safe-004','ch17-safety-strand-tests-compatibility','application',
    'Which situation requires immediate product-removal action during a chemical texture service?',
    'The client asks how long is left','The client reports burning or pain','The hair is dense','The client prefers a straighter result',
    'b','Burning or pain requires stopping exposure and following the product’s safety/removal directions.'),
  q('r17-safe-005','ch17-safety-strand-tests-compatibility','understanding',
    'Why must manufacturer compatibility instructions remain part of a chemical-service decision?',
    'They replace professional judgment completely','They define product-specific limits and sequences that cannot be safely replaced by generic rules','They only matter for color services','They are optional when strand testing is available',
    'b','Product-specific compatibility and safety limits must be respected alongside professional analysis.'),

  q('r17-texture-001','ch17-texturizers-chemical-blowouts','understanding',
    'What best describes the goal of a texturizer?',
    'To always fully straighten the hair','To loosen or soften curl rather than maximize straightening','To guarantee half the processing time of a relaxer','To avoid any chemical bond change',
    'b','The intended outcome is reduced curl rather than maximum straightening; the exact process depends on the selected system.'),
  q('r17-texture-002','ch17-texturizers-chemical-blowouts','application',
    'How should a chemical blowout procedure be selected?',
    'Use one universal mild-relaxer recipe','Use the selected product system, hair analysis, and manufacturer directions for the intended reduction in curl or bulk','Always process for half the time of a relaxer','Use only client preference',
    'b','The procedure is product-specific and must match the hair analysis and intended outcome.'),
  q('r17-texture-003','ch17-texturizers-chemical-blowouts','scenario',
    'A client asks for “just a little loosening.” What should the barber avoid assuming?',
    'That the service goal should be clarified','That every texturizer is simply a weaker formula used for a shorter fixed time','That prior chemistry matters','That product directions matter',
    'b','Texturizing should not be reduced to a universal weaker-formula/shorter-time rule.'),
  q('r17-texture-004','ch17-texturizers-chemical-blowouts','application',
    'What should be reviewed before performing a texturizing or chemical-blowout service?',
    'Only the desired finish','Hair/scalp condition, prior chemistry, product compatibility, and manufacturer directions','Only density','Only the client’s home styling routine',
    'b','These services still require the same disciplined compatibility and safety review as other chemical texture services.'),
  q('r17-texture-005','ch17-texturizers-chemical-blowouts','scenario',
    'The selected product system does not support the desired chemical-blowout procedure on the client’s prior chemistry. What is the best response?',
    'Proceed with a shorter time','Choose another verified-compatible plan or decline/postpone the service','Mix two systems','Use a strand test to override the incompatibility',
    'b','The service plan must stay within verified compatibility and product-system guidance.'),
]

export function getChapter17ReassessmentReserve(
  conceptFamilyId: Chapter17ConceptFamilyId,
): readonly Chapter17ReassessmentQuestion[] {
  return chapter17ReassessmentReserve.filter((question) => question.conceptFamilyId === conceptFamilyId)
}
