import type { Chapter4ConceptFamily, Chapter4ConceptFamilyId, Chapter4LearningObjective } from './types'

export const chapter4LearningObjectives: readonly Chapter4LearningObjective[] = [
  { id: 'LO-4-01', statement: 'Distinguish the roles of regulatory agencies and apply applicable safety requirements.', sourceBasis: 'Textbook regulatory-agency objective; NIC/state verification', conceptFamilyIds: ['ch4-regulatory-chemical-safety'] },
  { id: 'LO-4-02', statement: 'Identify major microorganism types, bacterial classifications, and their relationship to infection.', sourceBasis: 'Textbook microbiology objective', conceptFamilyIds: ['ch4-pathogens-transmission'] },
  { id: 'LO-4-03', statement: 'Explain how bloodborne pathogens and other infectious organisms can be transmitted.', sourceBasis: 'Textbook bloodborne-pathogen objective', conceptFamilyIds: ['ch4-pathogens-transmission','ch4-cross-contamination','ch4-blood-exposure-ppe'] },
  { id: 'LO-4-04', statement: 'Distinguish cleaning, disinfection, and sterilization and select the appropriate process.', sourceBasis: 'Textbook infection-control objective', conceptFamilyIds: ['ch4-disinfection-sterilization','ch4-cross-contamination'] },
  { id: 'LO-4-05', statement: 'Select and safely use appropriate disinfectants and antiseptics for their intended purposes.', sourceBasis: 'Textbook disinfectant/antiseptic objective', conceptFamilyIds: ['ch4-disinfection-sterilization','ch4-regulatory-chemical-safety'] },
  { id: 'LO-4-06', statement: 'Apply Standard Precautions, PPE, and appropriate blood-exposure procedures.', sourceBasis: 'Textbook precautions/exposure objective; current procedure verification required', conceptFamilyIds: ['ch4-blood-exposure-ppe','ch4-safe-practice-compliance'] },
  { id: 'LO-4-07', statement: 'Apply infection-control and workplace-safety practices that reduce contamination, accidents, and injuries.', sourceBasis: 'Textbook safe-work-practice objective', conceptFamilyIds: ['ch4-cross-contamination','ch4-regulatory-chemical-safety','ch4-safe-practice-compliance'] },
  { id: 'LO-4-08', statement: 'Apply a barber’s professional infection-control responsibilities in realistic shop situations.', sourceBasis: 'Textbook professional-responsibility objective; Oklahoma compliance overlay', conceptFamilyIds: ['ch4-safe-practice-compliance'] },
] as const

export const chapter4ConceptFamilies: readonly Chapter4ConceptFamily[] = [
  { id: 'ch4-pathogens-transmission', name: 'Pathogens, Infection & Transmission', learningObjectiveIds: ['LO-4-02','LO-4-03'], description: 'Microorganisms, infection, disease, immunity, bloodborne pathogens, and direct or indirect transmission relevant to barbering.', importance: 'core', professionalRelevance: 'CORE', examRelevance: 'DIRECT_VERIFIED', sourceProvenance: 'TEXTBOOK_DERIVED', status: 'active' },
  { id: 'ch4-disinfection-sterilization', name: 'Cleaning, Disinfection & Sterilization', learningObjectiveIds: ['LO-4-04','LO-4-05'], description: 'Selecting and applying the correct decontamination process, product, labeled contact time, handling, and storage.', importance: 'core', professionalRelevance: 'CORE', examRelevance: 'DIRECT_VERIFIED', sourceProvenance: 'TEXTBOOK_DERIVED', status: 'active' },
  { id: 'ch4-cross-contamination', name: 'Contamination & Cross-Contamination', learningObjectiveIds: ['LO-4-03','LO-4-04','LO-4-07'], description: 'Recognizing contaminated items and preventing transfer among tools, surfaces, hands, linens, clients, and work areas.', importance: 'core', professionalRelevance: 'CORE', examRelevance: 'DIRECT_VERIFIED', sourceProvenance: 'MILADY_SUPPORTED_EXPANSION', status: 'active' },
  { id: 'ch4-blood-exposure-ppe', name: 'Blood Exposure, PPE & Standard Precautions', learningObjectiveIds: ['LO-4-03','LO-4-06'], description: 'Standard Precautions, appropriate PPE, bloodborne-pathogen exposure prevention, and safe exposure response.', importance: 'core', professionalRelevance: 'CORE', examRelevance: 'DIRECT_VERIFIED', sourceProvenance: 'TEXTBOOK_DERIVED', status: 'active' },
  { id: 'ch4-regulatory-chemical-safety', name: 'Regulatory & Chemical Safety', learningObjectiveIds: ['LO-4-01','LO-4-05','LO-4-07'], description: 'OSHA, EPA, SDS/GHS, product labels, chemical handling, and the distinction between workplace and product regulation.', importance: 'core', professionalRelevance: 'CORE', examRelevance: 'DIRECT_VERIFIED', sourceProvenance: 'TEXTBOOK_DERIVED', status: 'active' },
  { id: 'ch4-safe-practice-compliance', name: 'Safe Barbering Practice & Compliance', learningObjectiveIds: ['LO-4-06','LO-4-07','LO-4-08'], description: 'Applying infection-control responsibilities in shop scenarios, including Oklahoma-specific sanitation and service-safety requirements.', importance: 'core', professionalRelevance: 'CORE', examRelevance: 'DIRECT_VERIFIED', sourceProvenance: 'MILADY_SUPPORTED_EXPANSION', status: 'active' },
] as const

export const CHAPTER4_CONCEPT_FAMILY_IDS = ['ch4-pathogens-transmission','ch4-disinfection-sterilization','ch4-cross-contamination','ch4-blood-exposure-ppe','ch4-regulatory-chemical-safety','ch4-safe-practice-compliance'] as const satisfies readonly Chapter4ConceptFamilyId[]
export const ACTIVE_CHAPTER4_CONCEPT_FAMILY_IDS = CHAPTER4_CONCEPT_FAMILY_IDS
export const isChapter4ConceptFamilyId = (value: string): value is Chapter4ConceptFamilyId => (CHAPTER4_CONCEPT_FAMILY_IDS as readonly string[]).includes(value)
export function getChapter4ConceptFamily(id: Chapter4ConceptFamilyId): Chapter4ConceptFamily { const family = chapter4ConceptFamilies.find((item) => item.id === id); if (!family) throw new Error(`Unknown Chapter 4 concept family: ${id}`); return family }
