import type { Chapter6ConceptFamilyId } from './types'
import type { Chapter6Difficulty, Chapter6EvidenceRecord } from './grading'

export type Chapter6MicroCheckAnswer = 'a'|'b'|'c'|'d'
export interface Chapter6MicroCheckQuestion {
  id:`mcq-6-${string}`; conceptFamilyId:Chapter6ConceptFamilyId; difficulty:Exclude<Chapter6Difficulty,'recall'>;
  question:string; answer_a:string; answer_b:string; answer_c:string; answer_d:string;
  correctAnswer:Chapter6MicroCheckAnswer; explanation:string
}
export interface Chapter6MicroCheck {
  id:`mc-6-${string}`; afterSectionId:string; conceptFamilyId:Chapter6ConceptFamilyId; title:string;
  questions:readonly Chapter6MicroCheckQuestion[]
}
const q=(id:Chapter6MicroCheckQuestion['id'],conceptFamilyId:Chapter6ConceptFamilyId,difficulty:Chapter6MicroCheckQuestion['difficulty'],question:string,answer_a:string,answer_b:string,answer_c:string,answer_d:string,correctAnswer:Chapter6MicroCheckAnswer,explanation:string):Chapter6MicroCheckQuestion=>({id,conceptFamilyId,difficulty,question,answer_a,answer_b,answer_c,answer_d,correctAnswer,explanation})

export const chapter6MicroChecks:readonly Chapter6MicroCheck[]=[
{id:'mc-6-01',afterSectionId:'cells-tissues',conceptFamilyId:'ch6-cells-tissues',title:'Cells & Tissues Check',questions:[
q('mcq-6-001','ch6-cells-tissues','understanding','Which structure regulates what enters and leaves a cell?','Cell membrane.','Nucleus.','Ribosome.','Centriole.','a','The cell membrane is the selective boundary controlling movement into and out of the cell.'),
q('mcq-6-002','ch6-cells-tissues','application','A student says mitosis is the same thing as metabolism. What is the best correction?','Mitosis is cell division; metabolism is the body’s life-sustaining chemical activity.','Mitosis is tissue repair through cell division; metabolism is the body’s energy-processing activity.','Mitosis is a form of cell growth; metabolism is the chemical activity that supports that growth.','Mitosis and metabolism are both cellular processes, but mitosis mainly describes growth and metabolism mainly describes repair.','a','Chapter 6 separates cell division from metabolism and homeostasis.')
]},
{id:'mc-6-02',afterSectionId:'body-systems',conceptFamilyId:'ch6-body-systems',title:'Body Systems Check',questions:[
q('mcq-6-003','ch6-body-systems','understanding','What is the difference between anatomy and physiology?','Anatomy studies structure; physiology studies function.','Anatomy describes body structures and their locations; physiology explains how those structures work.','Anatomy focuses on physical organization; physiology focuses on the processes those structures perform.','Anatomy emphasizes form and organization; physiology emphasizes function and activity.','a','Chapter 6 defines anatomy as structure and physiology as function.'),
q('mcq-6-004','ch6-body-systems','scenario','A barber notices a change in a client’s skin and asks what body-system knowledge should be used for. Which answer stays within scope?','Use normal anatomy and physiology knowledge to understand what is observed without diagnosing disease.','Use the observation to narrow the likely body system involved and explain that the client should seek medical evaluation for diagnosis.','Use normal anatomy knowledge to suggest likely causes, then recommend nonprescription care within barber scope.','Use body-system knowledge to determine whether the observed change is more likely endocrine, circulatory, or integumentary.','a','The chapter uses anatomy/physiology to support safe observation and service decisions, not diagnosis.')
]},
{id:'mc-6-03',afterSectionId:'skeletal-system',conceptFamilyId:'ch6-skeletal',title:'Skeletal System Check',questions:[
q('mcq-6-005','ch6-skeletal','understanding','Which bone forms the movable lower jaw?','Mandible.','Maxilla.','Frontal bone.','Hyoid.','a','The mandible is the movable lower jaw.'),
q('mcq-6-006','ch6-skeletal','application','Why do head, face, and neck landmarks matter to a barber?','They help orient service work and understand the structures beneath the service area.','They help estimate how much pressure can be used during massage based on the bones beneath the service area.','They identify where hair-growth patterns begin and therefore replace some consultation steps.','They are mainly used to locate structures that determine haircut elevation and sectioning.','a','Anatomical landmarks support orientation and safer professional service without expanding scope.')
]},
{id:'mc-6-04',afterSectionId:'muscular-system',conceptFamilyId:'ch6-muscular',title:'Muscular System Check',questions:[
q('mcq-6-007','ch6-muscular','understanding','Which statement correctly describes muscle origin and insertion?','The origin is relatively fixed; the insertion moves during contraction.','The origin is the more movable attachment; the insertion is the attachment that stays relatively fixed.','The origin and insertion both move equally, but the insertion is usually closer to the center of the body.','The origin describes the muscle belly; the insertion describes the tendon that receives nerve signals.','a','Chapter 6 distinguishes the relatively fixed origin from the more movable insertion.'),
q('mcq-6-008','ch6-muscular','application','A barber is reviewing facial massage anatomy. What is the safest use of muscle knowledge?','Use it to understand normal structure and movement while staying within taught service boundaries.','Use muscle location and action to identify whether discomfort is muscular before adjusting the service.','Use muscle knowledge to select pressure intended to restore normal movement when a client reports weakness.','Continue within normal massage pressure if the involved muscle is voluntary and no visible injury is present.','a','Muscle knowledge supports service technique and safety, not medical diagnosis or treatment.')
]},
{id:'mc-6-05',afterSectionId:'nervous-system',conceptFamilyId:'ch6-nervous',title:'Nervous System Check',questions:[
q('mcq-6-009','ch6-nervous','understanding','Which pairing is most accurate?','Trigeminal nerve V—facial sensation; facial nerve VII—facial expression.','Trigeminal nerve V—facial expression; facial nerve VII—facial sensation.','Both nerves contribute to facial function, but one is primarily sensory and the other primarily motor.','Both nerves serve the face, but the trigeminal nerve is mainly motor while the facial nerve is mainly sensory.','a','Chapter 6 distinguishes key sensory and motor roles of cranial nerves V and VII.'),
q('mcq-6-010','ch6-nervous','scenario','A client reports unusual numbness during a service. What is the safest professional response?','Stop or modify the service as appropriate and avoid diagnosing the cause.','Pause the service and explain which sensory nerve is most likely involved before deciding whether to continue.','Reduce pressure and continue if the numbness improves quickly during the service.','Massage the area lightly to determine whether normal sensation returns before stopping.','a','Nervous-system knowledge supports safe recognition and scope boundaries, not diagnosis.')
]},
{id:'mc-6-06',afterSectionId:'circulatory-system',conceptFamilyId:'ch6-cardiovascular',title:'Cardiovascular Check',questions:[
q('mcq-6-011','ch6-cardiovascular','understanding','What is the basic artery-versus-vein rule?','Arteries carry blood away from the heart; veins return blood toward it.','Arteries usually carry oxygenated blood and veins usually carry deoxygenated blood, so oxygen content is the main difference.','Arteries carry blood under higher pressure while veins carry it under lower pressure, so pressure is the main distinction.','Arteries are the vessels that carry blood toward working tissues, while veins return it toward the heart.','a','Direction relative to the heart is the core distinction.'),
q('mcq-6-012','ch6-cardiovascular','scenario','Why is knowledge of head and neck blood supply relevant during barbering services?','It supports safer awareness of underlying structures and bleeding risk without authorizing diagnosis.','It helps a barber estimate when visible redness or pallor reflects circulation changes that require service modification.','It helps determine whether a minor cut is likely to bleed heavily enough to require stopping the service.','It allows safer massage pressure decisions when a client reports a history of vascular problems.','a','Anatomy supports service safety but does not replace infection control or medical care.')
]},
{id:'mc-6-07',afterSectionId:'lymphatic-system',conceptFamilyId:'ch6-lymphatic',title:'Lymphatic & Immune Check',questions:[
q('mcq-6-013','ch6-lymphatic','understanding','What is a primary function of lymph nodes?','Filter lymph and support immune activity.','Filter lymph, return tissue fluid toward circulation, and directly generate most immune cells.','Filter lymph and release protective secretions that support immune defense.','Filter lymph and regulate nearby tissue movement during swelling or inflammation.','a','Lymph nodes filter lymph and participate in immune defense.'),
q('mcq-6-014','ch6-lymphatic','scenario','A client has a persistent swollen area near lymph nodes. What is the best professional response?','Avoid manipulating the area, do not diagnose, and recommend appropriate medical evaluation.','Use light massage around the area to encourage drainage without pressing directly on the swelling.','Explain that swollen nodes commonly indicate infection and recommend the client monitor the area before service.','Use mild heat to increase circulation, then continue if the swelling becomes less tender.','a','The chapter explicitly preserves observation/referral boundaries for persistent swelling.')
]},
{id:'mc-6-08',afterSectionId:'integumentary-system',conceptFamilyId:'ch6-integumentary',title:'Integumentary Check',questions:[
q('mcq-6-015','ch6-integumentary','understanding','Which layer contains follicles, glands, blood vessels, and nerve endings?','Dermis.','Epidermis.','Hypodermis.','Basal layer.','a','The dermis contains these structures; the epidermis is avascular.'),
q('mcq-6-016','ch6-integumentary','scenario','A client has an oily scalp. Which statement stays within professional scope?','Sebaceous glands produce sebum, but oiliness alone does not establish a medical diagnosis.','Oiliness can suggest increased sebaceous activity, which may be influenced by hormones, but a barber can identify the likely cause from the pattern.','Sebaceous and sweat glands both contribute oil-like secretions to the skin surface, but through different mechanisms.','Sebum is produced in the epidermis and travels through follicles to lubricate the skin.','a','Chapter 6 uses normal anatomy to explain function while avoiding diagnostic overreach.')
]},
{id:'mc-6-09',afterSectionId:'endocrine-system',conceptFamilyId:'ch6-endocrine',title:'Endocrine System Check',questions:[
q('mcq-6-017','ch6-endocrine','understanding','How do endocrine and exocrine glands differ?','Endocrine glands are ductless and release hormones into blood; exocrine glands use ducts.','Endocrine glands use ducts to deliver hormones locally; exocrine glands release products directly into blood.','Endocrine and exocrine glands both use ducts, but endocrine glands release hormones and exocrine glands release sebum or sweat.','Endocrine glands are defined by hormone production, while exocrine glands are defined by their location in the skin.','a','Chapter 6 distinguishes ductless endocrine secretion from duct-based exocrine secretion.'),
q('mcq-6-018','ch6-endocrine','scenario','A client asks whether hair thinning proves a thyroid disorder. What is the best response?','Hair changes can have many causes; a barber should not diagnose a thyroid disorder from hair thinning.','Hair thinning can strongly suggest thyroid dysfunction when it appears with other visible scalp changes.','Explain that thyroid changes can affect hair and suggest over-the-counter support while the client schedules an evaluation.','Thyroid function influences general metabolism but does not meaningfully affect hair growth patterns.','a','The chapter allows general relationships to be discussed while explicitly preserving diagnostic boundaries.')
]},
{id:'mc-6-10',afterSectionId:'other-systems',conceptFamilyId:'ch6-other-systems',title:'Other Body Systems Check',questions:[
q('mcq-6-019','ch6-other-systems','understanding','How do the respiratory and cardiovascular systems work together?','Respiration brings in oxygen; circulation transports it to tissues.','The lungs pump blood through arteries.','Respiration replaces circulation.','The cardiovascular system performs gas exchange in the lungs by itself.','a','The systems cooperate: gas exchange and transport are related but distinct functions.'),
q('mcq-6-020','ch6-other-systems','scenario','A client has dry skin and asks whether it means a kidney problem. What is the safest answer?','Dry skin is nonspecific and does not allow a barber to infer kidney function or diagnose disease.','Dry skin may indicate kidney dysfunction when it appears with persistent itching or changes in skin tone.','Dry skin is more consistent with surface dehydration than kidney-related problems, so urinary causes are unlikely.','Kidney function can affect skin moisture because the kidneys regulate sebum production through fluid balance.','a','Chapter 6 rejects diagnosis-adjacent inference from nonspecific observations such as dry skin.')
]},
]

export interface Chapter6MicroCheckResponse {questionId:Chapter6MicroCheckQuestion['id'];selectedAnswer:Chapter6MicroCheckAnswer}
export function buildChapter6MicroCheckEvidence(studentId:string,responses:readonly Chapter6MicroCheckResponse[],timestamp:string):Chapter6EvidenceRecord[]{
 const map=new Map(chapter6MicroChecks.flatMap(check=>check.questions.map(question=>[question.id,question] as const)))
 const seen=new Set<string>(); const records:Chapter6EvidenceRecord[]=[]
 for(const response of responses){if(seen.has(response.questionId))continue; const question=map.get(response.questionId); if(!question)continue; seen.add(response.questionId); records.push({studentId,chapterId:'ch-6',conceptFamilyId:question.conceptFamilyId,source:'micro_check',itemId:question.id,difficulty:question.difficulty,correct:response.selectedAnswer===question.correctAnswer,attemptPhase:'initial',timestamp})}
 return records
}
