import type {
  Chapter20ConceptFamilyId,
  Chapter20LearningObjectiveId,
} from './types'
import type { Chapter20Difficulty } from './grading'

export type Chapter20ReassessmentAnswer = 'a' | 'b' | 'c' | 'd'

export interface Chapter20ReassessmentQuestion {
  id: `r20-${string}`
  conceptFamilyId: Chapter20ConceptFamilyId
  learningObjectiveId: Chapter20LearningObjectiveId
  difficulty: Exclude<Chapter20Difficulty, 'recall'>
  question: string
  answer_a: string
  answer_b: string
  answer_c: string
  answer_d: string
  correctAnswer: Chapter20ReassessmentAnswer
  explanation: string
}

const q = (
  id: Chapter20ReassessmentQuestion['id'],
  conceptFamilyId: Chapter20ConceptFamilyId,
  learningObjectiveId: Chapter20LearningObjectiveId,
  difficulty: Chapter20ReassessmentQuestion['difficulty'],
  question: string,
  answer_a: string,
  answer_b: string,
  answer_c: string,
  answer_d: string,
  correctAnswer: Chapter20ReassessmentAnswer,
  explanation: string,
): Chapter20ReassessmentQuestion => ({
  id, conceptFamilyId, learningObjectiveId, difficulty,
  question, answer_a, answer_b, answer_c, answer_d, correctAnswer, explanation,
})

export const chapter20ReassessmentReserve: readonly Chapter20ReassessmentQuestion[] = [
  q('r20-transition-001','ch20-professional-transition-workplace-expectations','LO-20-01','application',
    'A new barber is assigned a closing checklist that was not discussed during orientation. What is the best response?',
    'Ignore the checklist until someone complains',
    'Clarify the expectation and confirm the shop process before assuming the duty does or does not apply',
    'Tell clients the shop is disorganized',
    'Ask another new barber to decide',
    'b','Professional transition includes clarifying expectations, using written policies when available, and communicating directly rather than making assumptions.'),
  q('r20-transition-002','ch20-professional-transition-workplace-expectations','LO-20-01','scenario',
    'You realize you may be late for your first client because of an unexpected delay. What should you do?',
    'Wait until the appointment time to say anything',
    'Notify the shop promptly, follow its lateness procedure, and help protect the client experience',
    'Cancel the rest of the day automatically',
    'Ask a friend to call the client without informing the shop',
    'b','Early communication and following the shop process demonstrate reliability and reduce disruption to clients and coworkers.'),
  q('r20-transition-003','ch20-professional-transition-workplace-expectations','LO-20-01','understanding',
    'Why is a written job description useful to a new barber?',
    'It replaces all future communication with management',
    'It helps clarify duties, expectations, accountability, and evaluation criteria',
    'It guarantees a specific pay increase',
    'It proves every requested task is appropriate',
    'b','A written job description provides a reference point for expectations and evaluation, but it does not replace communication or applicable policies.'),
  q('r20-transition-004','ch20-professional-transition-workplace-expectations','LO-20-01','application',
    'A manager asks you to help with a shared shop task between clients. What is the strongest first response?',
    'Assume shared tasks are beneath licensed barbers',
    'Confirm the expectation and help when it is part of the legitimate shop role and workload',
    'Refuse because only service revenue matters',
    'Complain to clients about the request',
    'b','Professional workplace behavior includes contributing to legitimate shared responsibilities while still communicating about unclear or inappropriate expectations.'),
  q('r20-transition-005','ch20-professional-transition-workplace-expectations','LO-20-01','scenario',
    'You receive corrective feedback about punctuality that you believe is incomplete. What should you do?',
    'Argue in front of clients',
    'Listen, clarify the facts privately, and agree on the expected standard going forward',
    'Ignore the feedback',
    'Post about the manager online',
    'b','Professional accountability includes receiving feedback, clarifying facts respectfully, and understanding the standard expected in the workplace.'),

  q('r20-teamwork-001','ch20-teamwork-workplace-relationships','LO-20-02','application',
    'A coworker repeatedly leaves shared sanitation supplies unstocked. What is the best first step?',
    'Discuss the specific behavior directly and respectfully with the coworker',
    'Complain to clients',
    'Start hiding supplies',
    'Ignore it forever',
    'a','Direct, respectful communication about the specific work impact is generally stronger than gossip, retaliation, or indefinite avoidance.'),
  q('r20-teamwork-002','ch20-teamwork-workplace-relationships','LO-20-02','scenario',
    'A senior barber gives advice you do not fully understand. What is the best response?',
    'Pretend to understand so you do not look inexperienced',
    'Ask a focused question and compare the advice with shop policy and legitimate professional standards',
    'Reject the advice because seniority never matters',
    'Repeat the advice to clients before verifying it',
    'b','Professional teamwork combines respect for experience with questions, verification, and appropriate judgment.'),
  q('r20-teamwork-003','ch20-teamwork-workplace-relationships','LO-20-02','understanding',
    'Which behavior most strengthens a barbershop team?',
    'Addressing work problems directly while helping with shared responsibilities',
    'Avoiding all feedback',
    'Competing for clients by criticizing coworkers',
    'Keeping useful information to yourself',
    'a','Healthy teams rely on direct communication, cooperation, reliability, and appropriate knowledge sharing.'),
  q('r20-teamwork-004','ch20-teamwork-workplace-relationships','LO-20-02','application',
    'Two barbers disagree over use of a shared station. What is the best approach?',
    'Use the station first and force the other barber to adapt',
    'Clarify the scheduling or shop rule and resolve the conflict directly',
    'Ask clients to vote',
    'Post the dispute publicly',
    'b','Shared-resource conflicts should be resolved through direct communication and the shop’s actual process or policy.'),
  q('r20-teamwork-005','ch20-teamwork-workplace-relationships','LO-20-02','scenario',
    'A coworker makes a mistake that affects your schedule. What response best reflects teamwork?',
    'Attack the coworker personally',
    'Address the impact, help solve the immediate problem, and discuss prevention afterward',
    'Tell every other employee first',
    'Refuse to assist because the mistake was not yours',
    'b','Teamwork focuses on solving the work problem and improving the process rather than escalating blame or gossip.'),

  q('r20-classification-001','ch20-employment-classification-compensation','LO-20-03','application',
    'A shop calls a barber a contractor but sets the schedule, pricing, service methods, and client assignment. What is the strongest conclusion?',
    'The contractor label automatically controls',
    'The actual working relationship should be evaluated because labels alone do not determine classification',
    'Owning personal clippers settles the classification',
    'Commission pay always proves contractor status',
    'b','Classification depends on the actual facts and circumstances, including control and financial independence, rather than one label or payment method.'),
  q('r20-classification-002','ch20-employment-classification-compensation','LO-20-03','scenario',
    'A booth-rental agreement does not say who controls client records or pricing. What should the barber do?',
    'Assume the barber controls both',
    'Clarify the written terms and verify applicable legal and tax responsibilities before relying on the arrangement',
    'Assume the owner controls both',
    'Ignore the issue because booth rental answers every question',
    'b','Important responsibilities should be confirmed from the agreement, actual relationship, and applicable rules rather than assumed from the booth-rental label.'),
  q('r20-classification-003','ch20-employment-classification-compensation','LO-20-03','understanding',
    'Which statement about commission pay is most accurate?',
    'Commission automatically means independent contractor',
    'Commission is a compensation method and does not by itself determine worker classification',
    'Commission always includes benefits',
    'Commission eliminates the need for written terms',
    'b','Compensation structure and legal classification are related business issues but one does not automatically determine the other.'),
  q('r20-classification-004','ch20-employment-classification-compensation','LO-20-03','application',
    'A compensation plan promises a base amount plus commission but does not define how commission is calculated. What should the barber do?',
    'Assume it is calculated on gross service revenue',
    'Ask for the calculation, deductions, thresholds, and eligibility terms in writing',
    'Assume all shops use the same formula',
    'Wait until the first paycheck to ask',
    'b','Base-plus-commission formulas can vary, so the actual written terms should be understood before relying on expected pay.'),
  q('r20-classification-005','ch20-employment-classification-compensation','LO-20-03','scenario',
    'Two shops use the same “booth renter” label but operate very differently. What should a barber compare?',
    'Only the monthly rent',
    'Control, scheduling, pricing, records, fees, taxes, insurance, and the written relationship',
    'Only the shop logo',
    'Only how long the owner has been licensed',
    'b','The real responsibilities and degree of business independence matter more than a shared label.'),

  q('r20-finance-001','ch20-financial-responsibility-income-reporting','LO-20-04','application',
    'Which habit best supports accurate reporting of tips and other taxable income?',
    'Estimate the total months later',
    'Keep consistent records as income is received and retain supporting documentation',
    'Track only electronic payments',
    'Ignore side-work income automatically',
    'b','Contemporaneous records are more reliable and support current tax and financial reporting requirements.'),
  q('r20-finance-002','ch20-financial-responsibility-income-reporting','LO-20-04','scenario',
    'A barber sees an old social-media post claiming a specific tax-reporting threshold still applies. What is the best action?',
    'Use the post because it has many shares',
    'Verify the current requirement with the IRS or another appropriate official source',
    'Use whichever threshold is lower',
    'Ask a client to decide',
    'b','Tax rules and forms can change. Current official guidance should be checked before relying on an old threshold.'),
  q('r20-finance-003','ch20-financial-responsibility-income-reporting','LO-20-04','understanding',
    'Why should a barber separate recordkeeping from memory?',
    'Because memory is always illegal',
    'Because consistent records provide more reliable evidence of income, expenses, and obligations',
    'Because receipts automatically reduce every tax',
    'Because written records eliminate professional advice',
    'b','Reliable records support accurate budgeting and reporting and reduce dependence on estimates made long after transactions occur.'),
  q('r20-finance-004','ch20-financial-responsibility-income-reporting','LO-20-04','application',
    'A barber is considering a price increase. What should be reviewed first?',
    'A fixed rule that prices must rise every year',
    'Costs, demand, skill level, client communication, market conditions, and applicable shop policy',
    'The highest competitor price only',
    'A social-media poll only',
    'b','Price decisions should reflect actual business conditions rather than a universal calendar formula.'),
  q('r20-finance-005','ch20-financial-responsibility-income-reporting','LO-20-04','scenario',
    'A barber’s monthly expenses consistently exceed take-home income. What is the strongest first response?',
    'Ignore the pattern',
    'Review the budget, identify controllable costs, and evaluate realistic income changes',
    'Borrow more without reviewing terms',
    'Stop keeping records',
    'b','A budget is useful because it shows where spending and income changes may be needed before additional debt is considered.'),

  q('r20-selling-001','ch20-ethical-selling-retailing','LO-20-05','application',
    'A client says a product recommendation is too expensive. What is the best response?',
    'Pressure the client to buy immediately',
    'Acknowledge the concern, explain relevant benefits honestly, and respect the decision',
    'Guarantee a result',
    'Criticize cheaper products without evidence',
    'b','Ethical selling is client-centered and avoids pressure, exaggeration, or unsupported guarantees.'),
  q('r20-selling-002','ch20-ethical-selling-retailing','LO-20-05','scenario',
    'A product pays a higher commission but does not fit the client’s stated need. What should the barber do?',
    'Recommend it because the commission is higher',
    'Recommend based on the client’s actual need and truthful product fit',
    'Hide the price',
    'Tell the client every barber uses it',
    'b','Professional recommendations should be based on client benefit rather than compensation alone.'),
  q('r20-selling-003','ch20-ethical-selling-retailing','LO-20-05','understanding',
    'What is the difference between ethical selling and pressure selling?',
    'Ethical selling explains relevant benefits and preserves client choice',
    'Ethical selling requires the client to buy',
    'Pressure selling is always more informative',
    'There is no difference',
    'a','Ethical selling supports informed choice; pressure selling attempts to overcome the client’s decision rather than serving the client’s need.'),
  q('r20-selling-004','ch20-ethical-selling-retailing','LO-20-05','application',
    'A client objects because they already own a similar product. What should the barber do?',
    'Ignore the objection',
    'Clarify the need, explain any meaningful difference truthfully, and accept the client’s choice',
    'Claim the existing product is unsafe without evidence',
    'Offer an unrelated service instead',
    'b','A good response addresses the client’s actual concern without inventing claims or removing the client’s ability to decline.'),
  q('r20-selling-005','ch20-ethical-selling-retailing','LO-20-05','scenario',
    'A client asks whether a product will definitely solve a problem. What is the strongest response?',
    'Guarantee success to close the sale',
    'Explain what the product is intended to do and avoid promises you cannot support',
    'Say all professional products always work',
    'Refuse to discuss the product',
    'b','Professional selling uses accurate information and avoids guarantees that exceed the evidence or product claim.'),

  q('r20-retention-001','ch20-client-retention-marketing-consent','LO-20-06','application',
    'A barber wants to post a recognizable client photo. What should happen before posting?',
    'Nothing if the haircut was paid for',
    'Obtain clear client permission and follow applicable shop, platform, privacy, and advertising rules',
    'Post first and ask later',
    'Tag the client instead of asking',
    'b','Identifiable client content should be used only with clear permission and in accordance with applicable rules and policies.'),
  q('r20-retention-002','ch20-client-retention-marketing-consent','LO-20-06','scenario',
    'A referral promotion has several restrictions. What is the strongest marketing practice?',
    'Hide the restrictions until checkout',
    'State the offer terms clearly and follow applicable shop and advertising rules',
    'Change the terms for each client without notice',
    'Require a public review for every discount',
    'b','Clear terms reduce misunderstanding and support ethical, compliant marketing.'),
  q('r20-retention-003','ch20-client-retention-marketing-consent','LO-20-06','understanding',
    'Which action most directly supports client retention?',
    'Reliable service, clear rebooking, and respectful follow-up',
    'Constantly changing appointment policies',
    'Posting client photos without permission',
    'Making guarantees about future results',
    'a','Retention depends on trust, consistency, communication, and making the next appropriate visit easy to schedule.'),
  q('r20-retention-004','ch20-client-retention-marketing-consent','LO-20-06','application',
    'A client agrees verbally to a photo but the shop requires a specific consent form. What should the barber do?',
    'Ignore the shop rule',
    'Follow the applicable shop consent process before posting',
    'Post because verbal consent always overrides policy',
    'Ask another client instead',
    'b','Chapter 20 does not treat one consent format as universal; the barber should follow the applicable policy or legal requirement.'),
  q('r20-retention-005','ch20-client-retention-marketing-consent','LO-20-06','scenario',
    'A barber wants to partner with a nearby gym for referrals. What makes the arrangement strongest?',
    'Clear, ethical terms that both businesses understand and can explain to clients',
    'Hidden payments that clients cannot discover',
    'A promise that every referral will produce the same result',
    'Automatic use of client contact information without permission',
    'a','Referral partnerships should be transparent, mutually understood, and consistent with applicable privacy, advertising, and shop rules.'),
] as const

export function getChapter20ReassessmentReserve(
  conceptFamilyId: Chapter20ConceptFamilyId,
): readonly Chapter20ReassessmentQuestion[] {
  return chapter20ReassessmentReserve.filter(
    (question) => question.conceptFamilyId === conceptFamilyId,
  )
}
