import type { Chapter21ConceptFamilyId, Chapter21LearningObjectiveId } from './types'
import type { Chapter21Difficulty } from './grading'

export type Chapter21ReassessmentAnswer = 'a' | 'b' | 'c' | 'd'

export interface Chapter21ReassessmentQuestion {
  id: `r21-${string}`
  conceptFamilyId: Chapter21ConceptFamilyId
  learningObjectiveId: Chapter21LearningObjectiveId
  difficulty: Exclude<Chapter21Difficulty, 'recall'>
  question: string
  answer_a: string
  answer_b: string
  answer_c: string
  answer_d: string
  correctAnswer: Chapter21ReassessmentAnswer
  explanation: string
}

const q = (id: Chapter21ReassessmentQuestion['id'], conceptFamilyId: Chapter21ConceptFamilyId, learningObjectiveId: Chapter21LearningObjectiveId, difficulty: Chapter21ReassessmentQuestion['difficulty'], question: string, answer_a: string, answer_b: string, answer_c: string, answer_d: string, correctAnswer: Chapter21ReassessmentAnswer, explanation: string): Chapter21ReassessmentQuestion => ({ id, conceptFamilyId, learningObjectiveId, difficulty, question, answer_a, answer_b, answer_c, answer_d, correctAnswer, explanation })

export const chapter21ReassessmentReserve: readonly Chapter21ReassessmentQuestion[] = [
  q("r21-entry-001","ch21-business-entry-paths","LO-21-01","application","A barber wants more control but cannot absorb full-shop overhead. What should be compared first?","A logo redesign","Rental versus ownership costs, control, agreement terms, clientele, and management responsibility","The age of the building","Whether friends prefer ownership","b","Business-entry decisions should match actual financial, operational, and control factors."),
  q("r21-entry-002","ch21-business-entry-paths","LO-21-01","scenario","A barber has strong clientele but no management experience. What is the strongest next step?","Open the largest shop possible","Compare lower-overhead entry options and build management readiness before assuming full ownership","Hire staff immediately","Ignore fixed costs","b","Readiness includes capital, client demand, and management capability."),
  q("r21-entry-003","ch21-business-entry-paths","LO-21-01","understanding","Why is booth or chair rental not automatically the same as independent-contractor status?","Because rent is always hourly","Because legal status depends on the actual agreement and working relationship, not the label alone","Because renters cannot set prices","Because all renters are employees","b","Labels do not control classification; actual facts and applicable rules matter."),
  q("r21-entry-004","ch21-business-entry-paths","LO-21-01","application","Two business paths have similar revenue potential but very different fixed costs. What should the barber examine?","Only gross revenue","Net cash flow, risk, flexibility, control, and obligations under each path","Only décor","Only social-media reach","b","A strong comparison looks beyond revenue to costs, risk, and obligations."),
  q("r21-entry-005","ch21-business-entry-paths","LO-21-01","scenario","A barber wants independence mainly to control scheduling and pricing. What should be verified in a rental option?","That the shop is busy","The written terms and actual control over scheduling, pricing, payments, records, and expenses","That rent is paid weekly","That the barber owns tools","b","The real agreement determines whether the option meets the barber's goals."),
  q("r21-opening-001","ch21-shop-opening-planning","LO-21-02","application","Before signing a lease, which due-diligence step is strongest?","Choose the cheapest space","Verify target market, realistic costs, zoning/occupancy, licensing/registration needs, insurance, and staffing assumptions","Buy chairs first","Assume the landlord checked every requirement","b","Lease decisions should follow business and regulatory due diligence."),
  q("r21-opening-002","ch21-shop-opening-planning","LO-21-02","scenario","A shop budget assumes exactly three months of reserve is always enough. What is the problem?","Three months is illegal","There is no universal reserve period; the amount should reflect fixed costs, financing, revenue ramp, and risk","Six months is always required","Reserve planning is unnecessary","b","Operating reserves should be based on the actual business model."),
  q("r21-opening-003","ch21-shop-opening-planning","LO-21-02","understanding","Why should licensing and permit requirements be verified from current official sources?","They never change","They vary by jurisdiction, structure, location, and activity","Only corporations need permits","Barber schools set all business rules","b","Requirements are context-dependent and can change."),
  q("r21-opening-004","ch21-shop-opening-planning","LO-21-02","application","A location has low rent but weak access and little demand from the target client. What should the owner do?","Choose it automatically","Compare total business fit, accessibility, demand, projected revenue, and occupancy requirements before deciding","Ignore the target client","Spend the rent savings on décor","b","Low rent alone does not make a location viable."),
  q("r21-opening-005","ch21-shop-opening-planning","LO-21-02","scenario","A new owner plans to hire before confirming the staffing model and obligations. What is the best correction?","Hire first and classify later","Define the lawful staffing model and verify payroll, wage, insurance, tax, and recordkeeping duties before onboarding","Use only verbal terms","Call everyone a contractor","b","Staffing decisions should be structured before workers are onboarded."),
  q("r21-ownership-001","ch21-ownership-legal-structures","LO-21-03","application","A single owner wants liability protection and simple administration. What is the best approach?","Assume an LLC is always best","Compare LLC, corporation, and other lawful structures using liability, tax, governance, filing, insurance, and financing factors","Choose the cheapest filing","Ignore insurance","b","Entity choice requires a full comparison, not a universal answer."),
  q("r21-ownership-002","ch21-ownership-legal-structures","LO-21-03","scenario","An owner believes an LLC guarantees personal assets can never be reached. What should be explained?","That is always true","Liability protection is not absolute and depends on proper formation, maintenance, conduct, contracts, insurance, and law","Only corporations can be sued","Insurance is unnecessary after formation","b","Entity protection has limits and does not replace good business practices."),
  q("r21-ownership-003","ch21-ownership-legal-structures","LO-21-03","understanding","What is one reason multiple owners need a written agreement?","To eliminate taxes","To define contributions, authority, profit/loss allocation, decisions, disputes, and exits","To avoid all state filings","To guarantee equal salaries","b","Written agreements reduce ambiguity among owners."),
  q("r21-ownership-004","ch21-ownership-legal-structures","LO-21-03","application","A barber compares a sole proprietorship with a corporation. Which factor belongs in the analysis?","Logo design","Liability exposure, tax treatment, governance, filings, financing, and administrative burden","Haircut technique","Uniform color","b","Ownership structure is a legal/business decision, not a branding decision."),
  q("r21-ownership-005","ch21-ownership-legal-structures","LO-21-03","scenario","Two owners rely only on verbal promises about profit splits and exit rights. What is the main risk?","The shop cannot advertise","Important ownership expectations are undocumented and may be difficult to enforce or resolve","The business must become a franchise","The shop loses its license automatically","b","Clear written terms support governance and dispute resolution."),
  q("r21-plan-001","ch21-business-plan-financial-planning","LO-21-04","application","What makes a revenue forecast credible?","Using the highest possible estimate","Documented assumptions, realistic ranges, market evidence, pricing, capacity, and expense timing","Ignoring seasonality","Assuming every chair is full","b","Forecasts should be evidence-based and transparent about assumptions."),
  q("r21-plan-002","ch21-business-plan-financial-planning","LO-21-04","scenario","A business is profitable on paper but cannot pay bills on time. What likely needs review?","The shop name","Cash-flow timing between receipts and expenses","The logo","The service menu font","b","Profit and cash flow are different; timing can create shortages."),
  q("r21-plan-003","ch21-business-plan-financial-planning","LO-21-04","understanding","What does break-even analysis help estimate?","When total revenue covers total costs under stated assumptions","The legal structure automatically required","Which social platform is best","How many licenses exist","a","Break-even analysis connects costs, pricing, and volume."),
  q("r21-plan-004","ch21-business-plan-financial-planning","LO-21-04","application","A lender questions a forecast that assumes full capacity in month one. What should the owner do?","Defend it without evidence","Revise the model with realistic ramp-up and sensitivity assumptions","Remove expenses","Double prices without analysis","b","Realistic ramp-up assumptions improve planning quality."),
  q("r21-plan-005","ch21-business-plan-financial-planning","LO-21-04","scenario","A shop's pricing plan copies the highest competitor without reviewing costs or clients. What is the best correction?","Keep the copied price","Evaluate costs, positioning, client demand, capacity, service value, and market conditions","Use the lowest price instead","Never change prices","b","Pricing should reflect the actual business rather than one competitor."),
  q("r21-records-001","ch21-recordkeeping-financial-compliance","LO-21-05","application","Which habit best supports accurate financial reporting?","Estimate transactions at year-end","Record income and expenses consistently and retain supporting documentation under current requirements","Track only card payments","Delete receipts after a week","b","Contemporaneous records are more reliable than later estimates."),
  q("r21-records-002","ch21-recordkeeping-financial-compliance","LO-21-05","scenario","A shop keeps wages but not hours, tips, or supporting payroll records. What is the main concern?","Clients may dislike the décor","The shop may be unable to support payroll, tax, or labor compliance if questioned","The shop cannot sell products","The owner must change entity type","b","Complete records support compliance and dispute resolution."),
  q("r21-records-003","ch21-recordkeeping-financial-compliance","LO-21-05","understanding","Why is there no single universal record-retention period?","Records never need retention","Retention depends on document type, tax issue, jurisdiction, business structure, and other legal duties","Only digital records count","Every record must be kept forever","b","Retention rules vary by context."),
  q("r21-records-004","ch21-recordkeeping-financial-compliance","LO-21-05","application","A client form asks for sensitive information unrelated to service. What is the best practice?","Collect it anyway","Collect only information with a legitimate purpose and protect access under applicable privacy/security rules","Post it in a shared spreadsheet","Share it with partners automatically","b","Minimum-necessary collection reduces privacy risk."),
  q("r21-records-005","ch21-recordkeeping-financial-compliance","LO-21-05","scenario","A barber receives cash tips and assumes they do not need documentation. What should happen?","Ignore cash","Track the income accurately and verify current reporting obligations for the actual arrangement","Return all tips","Convert cash to gift cards","b","Cash is not automatically exempt from reporting or recordkeeping."),
  q("r21-rental-001","ch21-booth-rental-independent-business-responsibilities","LO-21-06","application","What should determine responsibilities in a booth-rental arrangement?","The label alone","The written agreement, actual working relationship, control, payments, expenses, insurance, licensing, records, and current rules","Whether rent is weekly","Who owns the mirror","b","The facts and agreement determine responsibilities."),
  q("r21-rental-002","ch21-booth-rental-independent-business-responsibilities","LO-21-06","scenario","A renter is told to use a fixed 25% tax savings rule. What is the strongest response?","Use 25% universally","Estimate obligations from actual income, deductions, structure, withholding, state rules, and current guidance","Use 30% universally","Wait until year-end","b","Tax planning cannot rely on one fixed percentage."),
  q("r21-rental-003","ch21-booth-rental-independent-business-responsibilities","LO-21-06","understanding","Why can two booth-rental arrangements produce different tax or business duties?","Because labels are optional","Because the real facts, control, agreements, and applicable rules can differ","Because all renters choose different tools","Because every state bans booth rental","b","Similar labels can describe different legal and business relationships."),
  q("r21-rental-004","ch21-booth-rental-independent-business-responsibilities","LO-21-06","application","A rental agreement is silent about client records and merchant payments. What should the barber do?","Assume the renter controls both","Clarify those responsibilities in writing and verify the actual operating model before relying on the arrangement","Ignore the issue","Let clients decide","b","Important business responsibilities should not be left ambiguous."),
  q("r21-rental-005","ch21-booth-rental-independent-business-responsibilities","LO-21-06","scenario","A shop controls a renter's schedule, prices, methods, and client assignment. What is the strongest conclusion?","The renter label settles classification","The actual degree of control should be evaluated under current worker-classification rules","Owning clippers settles the issue","Rent amount settles the issue","b","Control and the full facts matter more than the label."),
  q("r21-operations-001","ch21-shop-operations-management","LO-21-07","application","A shop is busy but profits are weak. What should management review first?","Add décor","Revenue mix, costs, staffing, scheduling, utilization, pricing, and process data","Run a giveaway immediately","Assume busy means profitable","b","Operational decisions should begin with evidence."),
  q("r21-operations-002","ch21-shop-operations-management","LO-21-07","scenario","Complaints increase after schedule changes. What is the strongest response?","Ignore the trend","Review client feedback, wait times, staffing, booking flow, and service consistency before changing the process","Cut all prices","Blame clients","b","Root-cause analysis is stronger than guessing."),
  q("r21-operations-003","ch21-shop-operations-management","LO-21-07","understanding","How should Chapter 21 treat cleanliness?","As a replacement for infection-control training","As an operations responsibility while safety procedures remain governed by the dedicated safety curriculum and current rules","As cosmetic only","As optional during busy periods","b","Operations can reinforce cleanliness without duplicating safety rules."),
  q("r21-operations-004","ch21-shop-operations-management","LO-21-07","application","A slow weekday persists for several months. What is the best approach?","Permanent across-the-board discounting","Review demand and operating data, then test targeted changes and measure the result","Do nothing","Fire staff immediately","b","Measured experiments protect margins and reveal what works."),
  q("r21-operations-005","ch21-shop-operations-management","LO-21-07","scenario","A shop adds retail products but no one tracks sales or inventory. What should management do?","Keep ordering the same amount","Create a basic tracking process for sales, margin, inventory, and reorder decisions","Stop all retail forever","Raise every service price","b","Operational controls help determine whether retail is actually contributing."),
  q("r21-marketing-001","ch21-advertising-marketing-client-consent","LO-21-08","application","Before using an identifiable client photo in an ad, what should the barber do?","Post if the client tagged the shop once","Obtain clear permission and follow applicable privacy, advertising, platform, school, and shop rules","Post first and ask later","Crop the photo slightly","b","Identifiable client content requires appropriate permission and rule compliance."),
  q("r21-marketing-002","ch21-advertising-marketing-client-consent","LO-21-08","scenario","A referral promotion hides important restrictions until checkout. What is the main problem?","The font is too small","Material offer terms are not transparent, creating misleading marketing risk","The promotion is too generous","Referrals are never allowed","b","Promotions should clearly disclose important terms."),
  q("r21-marketing-003","ch21-advertising-marketing-client-consent","LO-21-08","understanding","Why can authentic reviews be useful marketing evidence?","They guarantee future results","They can provide social proof when genuine, non-misleading, and compliant with disclosure rules","They replace service quality","They allow hidden incentives","b","Reviews can build trust only when truthful and transparent."),
  q("r21-marketing-004","ch21-advertising-marketing-client-consent","LO-21-08","application","A barber wants to text every past client a promotion. What should be checked first?","Whether the message is funny","Consent, applicable communications rules, opt-out requirements, and the shop's policies","Whether competitors text more often","Whether the barber owns the phone","b","Direct outreach can be regulated and should respect consent and opt-out requirements."),
  q("r21-marketing-005","ch21-advertising-marketing-client-consent","LO-21-08","scenario","A marketing plan promises every new client will become a repeat client. What is the strongest correction?","Keep the guarantee","Use measurable goals and truthful claims instead of promising outcomes that cannot be guaranteed","Add more exclamation points","Remove the budget","b","Marketing plans should use realistic, measurable goals rather than unsupported guarantees."),
] as const

export function getChapter21ReassessmentReserve(conceptFamilyId: Chapter21ConceptFamilyId): readonly Chapter21ReassessmentQuestion[] {
  return chapter21ReassessmentReserve.filter((question) => question.conceptFamilyId === conceptFamilyId)
}