export const RELEASE_PIPELINE_CONTRACT = [
  'CODE TESTS',
  'SECURITY TESTS',
  'BUILD',
  'DEPLOY',
  'PRODUCTION BROWSER MATRIX',
  'PRODUCTION ACCOUNT-INTEGRITY GATE',
  'PRODUCTION AUTHENTICATION SMOKE GATE',
  'FINAL RELEASE GO',
] as const

export const RELEASE_GATE_FAILURE_POLICY = 'FAIL_CLOSED'
